### ISSUE TITLE
psycopg2 conn multihost fails

### ISSUE THREAD

**Issue by batchenr** [psycopg/psycopg2#1003]
Hey,
I have 3 db servers on docker containers, and i used to connect like this from my python app:
`psycopg2.connect(host="db-0", user="user", password="password", database="data")
`This works, but if i add more then 1 host it fails.

```
psycopg2.connect(host="db-0, db-1", user="user", password="password", database="data")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db-0, db-1" to address: Temporary failure in name resolution

```
my package is psycopg2-2.8.4 and using python3.7 and psql 11.5 on docker containers db-0 and db-1
used pip install psycopg2 to install.

**Comment by dvarrazzo** [comment]
What connection string do you use to connect via psql?

**Comment by dvarrazzo** [comment]
Maybe the space after the comman in the hosts list is a problem?

```
In [5]: cnn = psycopg2.connect(host="foo, localhost")
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-5-4b98d10c97f9> in <module>()
----> 1 cnn = psycopg2.connect(host="foo, localhost")

/home/piro/dev/psycopg2/build/lib.2.7/psycopg2/__init__.pyc in connect(dsn, connection_factory, cursor_factory, **kwargs)
    124 
    125     dsn = _ext.make_dsn(dsn, **kwargs)
--> 126     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    127     if cursor_factory is not None:
    128         conn.cursor_factory = cursor_factory

OperationalError: could not translate host name "foo" to address: Name or service not known
could not translate host name " localhost" to address: Name or service not known


In [6]: cnn = psycopg2.connect(host="foo,localhost")
# worketh
```

**Comment by batchenr** [comment]
> Maybe the space after the comman in the hosts list is a problem?
> 
> ```
> In [5]: cnn = psycopg2.connect(host="foo, localhost")
> ---------------------------------------------------------------------------
> OperationalError                          Traceback (most recent call last)
> <ipython-input-5-4b98d10c97f9> in <module>()
> ----> 1 cnn = psycopg2.connect(host="foo, localhost")
> 
> /home/piro/dev/psycopg2/build/lib.2.7/psycopg2/__init__.pyc in connect(dsn, connection_factory, cursor_factory, **kwargs)
>     124 
>     125     dsn = _ext.make_dsn(dsn, **kwargs)
> --> 126     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
>     127     if cursor_factory is not None:
>     128         conn.cursor_factory = cursor_factory
> 
> OperationalError: could not translate host name "foo" to address: Name or service not known
> could not translate host name " localhost" to address: Name or service not known
> 
> 
> In [6]: cnn = psycopg2.connect(host="foo,localhost")
> # worketh
> ```

same : 
>>> psycopg2.connect(host="db-0,db-1", user="slctr", password="password", database="slctr")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db-0,db-1" to address: Temporary failure in name resolution

this is the connection string in my python which works only if i put 1 host

**Comment by dvarrazzo** [comment]
Again, how do you connect with psql?

**Comment by batchenr** [comment]
> Again, how do you connect with psql?

what do you mean ? 
i have a py script that when it connect to psql it runs this code : 
```
    def db_conn(self):
        try:
            self.conn = psycopg2.connect(
                host=self.settings["db"]["host"],
                user=self.settings["db"]["user"],
                password=self.settings["db"]["password"],
                database=self.settings["db"]["database"],
            )
            return self.conn
        except Exception as e:
            return None

```

**Comment by dvarrazzo** [comment]
Can you connect to the same database using `db-0,db-1` via psql?

If you can via psql and not via psycopg we have a thing to investigate.

If you can't via psql then it's an issue on your side you may want to look into, but I can't help.

**Comment by batchenr** [comment]
> Can you connect to the same database using `db-0,db-1` via psql?
> 
> If you can via psql and not via psycopg we have a thing to investigate.
> 
> If you can't via psql then it's an issue on your side you may want to look into, but I can't help.

yes i can, if i replace db-0 with db-1 it works, but just not together..

`psycopg2.connect(host="db-0", user="user", password="password", database="data")
`Works
`psycopg2.connect(host="db-1", user="user", password="password", database="data")
`Works

`psycopg2.connect(host="db-0, db-1", user="user", password="password", database="data")
`Doesnt work

**Comment by batchenr** [comment]
I tried this : 

```
pip3 install postgres

from postgres import Postgres
db = Postgres('postgres://user:password@db-0,db-1:5432/databasename')
db.one("select * from user")

```
And it works, it goes to the first available one.

**Comment by dvarrazzo** [comment]
you can use `psycopg2.connect('postgres://user:password@db-0,db-1:5432/databasename')`. Does it work?

**Comment by batchenr** [comment]
Hey,

i figured out now after testing it that the string 
`psycopg2.connect(host="db-0, db-1", user="user", password="password", database="data")
`
is accepted now, but the connection always try the first one, and if it is down (db-0) then
it doesn't query db-1,   what should i do ? 
is it even meant to work ?

**Comment by dvarrazzo** [comment]
Psycopg just connects using the postgres libpq library. If your behaviour is not what expected you should enquire the postgres developers.
