### ISSUE TITLE
cursor.description does not return all info

### ISSUE THREAD

**Issue by mikaelene** [psycopg/psycopg2#1005]
As per [docs](http://initd.org/psycopg/docs/cursor.html), cursor.description should return column instances with 7 items. For me it only returns the first 2 items. I am on: `psycopg2==2.8.4`

```
import psycopg2

db = psycopg2.connect("host=localhost dbname= postgres")
cur = db.cursor()

cur.execute('SELECT table_schema, column_name, ordinal_position FROM information_schema."columns" fetch first 10 rows only')
print(cur.description)
```

yields:

```(Column(name='table_schema', type_code=1043), Column(name='column_name', type_code=1043), Column(name='ordinal_position', type_code=23))```

**Comment by dvarrazzo** [comment]
That's just the representation. Attributes are available as per docs.

**Comment by mikaelene** [comment]
Get it now! Thanks for quick reply!
