### ISSUE TITLE
CherryPy server talking to PostgresSQL (9.2.7)

### ISSUE THREAD

**Issue by igor-rodrigues1** [psycopg/psycopg2#1013]
CherryPy server talking to PostgresSQL (9.2.7)
- Always on a particular url
- Same line every time `cursor.execute(sale_records_sql, (sales_ids,))`
- Vanishes after the server is restarted
- Emerges again after a indefinite time
  
  ```
    File "/home/ec2-user/venv/lib/python3.4/site-packages/psycopg2/extras.py", line 288, in execute
      return super(NamedTupleCursor, self).execute(query, vars)
  psycopg2.DatabaseError: error with no message from the libpq
  ```

_Originally posted by @ajoyoommen in https://github.com/psycopg/psycopg2/issues/281#issuecomment-133637769_

I am using Linux Mint 19.1 Tessa and installed libghc-postgresql-libpq-dev. That solved the problem.

**Comment by dvarrazzo** [comment]
This is not something that looks like a bug, and nothing we can reproduce. Please provide a way to reproduce the issue.
