### ISSUE TITLE
Disable triggers in copy_from

### ISSUE THREAD

**Issue by GammaGames** [psycopg/psycopg2#1015]
I am using the `copy_from` and `copy_to` commands with an `StringIO` class to mimic the `pg_dump` command to copy a table from one database to another. Other than manually running `ALTER TABLE table_name DISABLE TRIGGER trigger_name` and `ALTER TABLE table_name ENABLE TRIGGER trigger_name` before the copy for each trigger on the table, is there a way to disable triggers on a table while mass-inserting data? Both `pg_dump` and `pg_restore` have the `--disable-triggers` flag as an option, and I think it would be useful to have a similar option in psycopg2.

**Comment by dvarrazzo** [comment]
No, this is not a policy of psycopg2 responsibility. There are many ways to do it, permissions might not be enough, etc.

You should do that yourself: you can issue `ALTER TABLE ... DISABLE/ENABLE TRIGGER all` if your user has the permission.

**Comment by GammaGames** [comment]
Ah, I had forgotten about permissions. They won't be an issue, thank you!
