### ISSUE TITLE
transaction autocommits after rollback is executed in cursor

### ISSUE THREAD

**Issue by alanformstone** [psycopg/psycopg2#1016]
```
import psycopg2

try:
    conn = psycopg2.connect(service='SCFDEV', user='postgres', password='postypots')
except:
    raise

cursor=conn.cursor()

cursor.execute("insert into scfadm.atest values (1)")

#conn.rollback()
cursor.execute('rollback')


cursor.execute("insert into scfadm.atest values (2)")


cursor.close()

print('Exit')
```

The above results in the second insert being committed automatically.  If the connection is rolled back with  conn.rollback()) everything works fine.

**Comment by dvarrazzo** [comment]
You are not supposed to `execute('rollback')`. Don't.

**Comment by asqui** [comment]
@alandmoore : I believe this is a side-effect of the implementation of 'autocommit' -- the Python DB API says that the default behaviour of all database connections when first created is that they have autocommit off, and therefore automatically begin a transaction as soon as you execute a statement.

I'm guessing the way this is implemented in psycopg2 is that it automatically issues a BEGIN the first time you execute on the connection following creation, or a call to `commit()` or `rollback()`. If you `execute('rollback')` then the library doesn't realise you've terminated the transaction*, so doesn't automatically begin another one before executing your next statement.

(*This would require the library to parse and inspect every piece of SQL you execute, which is not practical nor needed, given that there are specific `commit()` and `rollback()` methods that should be used to terminate transactions.)

As an aside, I've found the very concept of 'autocommit' to be confusing and impractical -- the idea that executing a statement has the implicit side-effect of starting a transaction that I then need to explicitly commit or rollback seems weirdly asymmetrical.

I've implemented a `Transaction` context manager that hides these details from you and allow you to write clearer code like this:
```
with Transaction(cxn) as txn:
   # do stuff

# Transaction is automatically committed if the block succeeds,
# and rolled back if an exception is raised out of the block.
```
It also has other advantages, such as support for nested transactions.
Check the README here for more details: https://github.com/asqui/psycopg-nestedtransactions

@dvarrazzo : We've been using this context manager in production for over a year now and I've been meaning to ask; do you have any appetite for including this in psycopg2.extras?

**Comment by alanformstone** [comment]
I bumped into this while porting cx_oracle code to psycopg2. It took a while to track down what was going on so I guess it may come up again in the future for others. At least its documented here though now.
