### ISSUE TITLE
statement_timeout option not helping with hardware fault

### ISSUE THREAD

**Issue by stefanknechtDBE** [psycopg/psycopg2#1017]
Hello

We run the following very simple routine:
`    # Main thread loop

    try:
      while True:
        try:
          x = self.pg.query("select current_user;")
          self.instanceState = "OK"
        except:
          logger.slack("Failed to query database {0}: {1}".format(self.instanceName, str(sys.exc_info()[1]).rstrip()))
          logger.flushSlack()

          self.instanceState = "BAD"
          self.threadReconnect()

        logger.info("Connection check for {} succeeded. Sleeping.. ".format(self.instanceName))
        time.sleep(self.checkDelay + random.random())
    except:
      logger.warning("Thread {0} failed: {1}".format(self.instanceName, str(sys.exc_info())))
      raise`

query() is basically just a wrapper around cursor.execute() with a bit of logging around it.

Our connection string looks like this:

connect(userName = "x", databaseName = "y", instanceName = self.instanceName, options='-c statement_timeout=5000')

This works fine for most cases, incl RDS postgres instance shutdowns, reboots, etc.

But, if there is a hardware failure, and the server is pulled off the network, and AWS triggers a failover, we see a hang of 8 minutes in the execute() call, despite the statement_timeout being 5 seconds.

This is what we see in the log if there is an RDS instance fault and failover:

`2019-11-12 19:10:20,807 - INFO - Thread-38 Connection check for abcd succeeded. Sleeping.. 
2019-11-12 19:10:51,005 - INFO - Thread-38 Connection check for abcd succeeded. Sleeping.. 
2019-11-12 19:18:51,151 - SLACK - Thread-38 Failed to query database abcd: server closed the connection unexpectedly
2019-11-12 19:18:51,153 - DEBUG - Thread-38 Buffering message Failed to query database abcd: server closed the connection unexpectedly
2019-11-12 19:18:51,328 - DEBUG - Thread-38 Connected to database postgres at abcd.xyz.us-west-1.rds.amazonaws.com after 0.0058s
2019-11-12 19:18:51,329 - INFO - Thread-38 Connection check for abcd succeeded. Sleeping.. 
`

The documentation isn't really clear to me, but it appears that options statement_timeout is a server setting? And thus only in effect on the database itself?

This would mean that if there is a hardware failure, the client will keep waiting, regardless of this timeout.

Is there no support for a call-level timeout in psycopg2?

Stefan

**Comment by dvarrazzo** [comment]
Yes, `statement_timeout` is a server setting: the server kills the operation if it times out. If the server is not reachable it won't work.

You can try playing with the timeout of the tcp connection: you can get the file descriptor using `connection.fileno()` and play with syscall but I'm not so experienced here around.

I think the best solution is to not keep connections open for a long amount of time: make a connection, run your queries, then close it. You can use the `connect_timeout` parameter to establish a timeout on connection (see the libpq documentation about it).
