### ISSUE TITLE
Documentation: Link to this issue tracker

### ISSUE THREAD

**Issue by pyropeter** [psycopg/psycopg2#1021]
I only found this issue tracker thanks to the nice people in `#postgresql`.

**Comment by dvarrazzo** [comment]
The homepage http://initd.org/psycopg/ says "report a bug".

The readme, hence the project page on pypi (https://pypi.org/project/psycopg2/) and github (https://github.com/psycopg/psycopg2) say "For any other resource (source code repository, *bug tracker*, mailing list) please check the project homepage."

Google (https://www.google.com/search?q=psycopg+bug) and DuckDuckGo (https://duckduckgo.com/?q=psycopg+bug) report the bugs page (https://github.com/psycopg/psycopg2/issues) as their first hit.

Please say thank you to the nice `#postgresql` people.
