### ISSUE TITLE
ThreadedConnectionPool; putconn...

### ISSUE THREAD

**Issue by bitmodeler** [psycopg/psycopg2#1022]
I used a ThreadedConnectionPool (DictCursor, autocommit=True...)

Under stress-testing, I saw something troubling: I was getting results in cursor sets from PREVIOUS connection queries!

No: I was not doing it wrong. Any queries and cursors on a connection were contained locally in functions. I closed the single cursor sets I was using before executing each of the putconn's. I even rebuilt it from source, to rule out it was not a distro libraries versioning issue.

After much trial+error, I was getting a hint when I tried named cursors as a workaround (I was going to make each one unique...): postgres complained that a transaction needed to be committed.

I had previously made a context manager class for insuring release of connections after exiting "with" blocks (putting a putconn in an __exit__...) I added this before the putconn:

     self._connection.tpc_rollback ()

Fixed it.

So it appears some sort of cleanup is needed in your putconn, to insure that the next user of a connection doesn't get any weirdness (at least it appears that it's needed when you're using autocommit=True...)

**Comment by bitmodeler** [comment]
![tumbleweed](https://user-images.githubusercontent.com/20399979/71596399-5b9ff400-2b0d-11ea-9ae4-12d672de4b8e.gif)

**Comment by dvarrazzo** [comment]
tpc_rollback? Are you using two phase transactions?

**Comment by bitmodeler** [comment]
No; though I am using autocommit, which perhaps impacts transactional processing, right?

It's uncanny. Since I am using a context manager class for the getconn and putconn (inside a \_\_enter\_\_ and \_\_exit\_\_, respectively), I can't see how it's possible that the connections are being shared from one instance to the next. Mind you, it manifests under a high concurrent call volume to the function with the encapsulated context manager (I am using Siege to simulate load...)

I can share more code and whatnot; but before I took your time with that, I reasoned a guess for why that one line addition before the putconn fixes it might be easier for you to take a stab at...

**Comment by dvarrazzo** [comment]
`putconn()` is definitely the right place to do some cleanup. Probably the autocommit status should be reverted. A patch would be well accepted, thank you :)

**Comment by bitmodeler** [comment]
So what do you think; have the putconn do a connection.reset() or connection.cancel()??


-------- Original Message --------
Subject: Re: [psycopg/psycopg2] ThreadedConnectionPool; putconn...
(#1022)

**Comment by dvarrazzo** [comment]
The psycopg2 pool will not receive further improvements. The psycopg3 pool has a hook to execute whatever reset procedure is deemed requested by an application see the [reset arg](https://www.psycopg.org/psycopg3/docs/api/pool.html#psycopg3.pool.ConnectionPool) in the pool constructor docs.
