### ISSUE TITLE
support LoggerAdapter

### ISSUE THREAD

**Issue by jesusch** [psycopg/psycopg2#1026]
while setting up a Logger with context information `LoggingConnection` does not handle this as a Logger. This results in an exception as it tries to use the Logger.write() method
see: https://docs.python.org/3/library/logging.html#loggeradapter-objects 

https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L412
should check if that object isinstance of either logging.Logger or logging. LoggerAdapter

**Comment by jesusch** [comment]
see: PR https://github.com/psycopg/psycopg2/pull/1027

**Comment by jesusch** [comment]
maybe the `else` should check if _logobj is an open file handle and if not just create a Null Logger?

**Comment by dvarrazzo** [comment]
I'm happy to merge #1027 as it is, but not to complicate further the logging connection. It wasn't really meant for production, it has no tests.

**Comment by jesusch** [comment]
I'm happy with #1027 :)

**Comment by jesusch** [comment]
@dvarrazzo any chance this gets merged?

**Comment by dvarrazzo** [comment]
I'll merge it and try to wrap a release in the next days (I'll be a few days out of home with patchy connectivity).
