### ISSUE TITLE
Datetime infered as string when having precision in seconds in execute_values

### ISSUE THREAD

**Issue by PMLP-novo** [psycopg/psycopg2#1028]
When i use execute values to generate a subtable if I use datetimes with precision in seconds the subtable column type is infered to be string. 
```

col_names_concat = ",".join(table_columns)
set_string = ",".join( "{0} = tmp.{0}".format(col_name) for col_name in table_columns if col_name != "id")
update_query=f"""
       UPDATE table SET {set_string}
        FROM (VALUES %s) AS tmp({col_names_concat})
        WHERE tmp.id = lims_raw.id"""
extra.execute_values(cur, update_query, patch_data))

>> psycopg2.errors.DatatypeMismatch: column "reviewed_datetime" is of type timestamp without time zone but expression is of type text

```
When I added a dummy column 
```
dummy_sample = tuple(None  if col_name not in time_columns else datetime.datetime.now())
extra.execute_values(cur, update_query, patch_data+ [dummy_sample ]))
```
it worked when there were only None instances but I got the same error when there was a datetime with seconds precision. So I moved the dummy sample to become the first sample
```
dummy_sample = tuple(None  if col_name not in time_columns else datetime.datetime.now())
extra.execute_values(cur, update_query, [dummy_sample ]+patch_data))
```
And now it worked. So to me it looks like the psycopg in this case has an ambiques way of translating datetimes with exactly presion in seconds. Such that it translates it to string if no extra info is given.

**Comment by dvarrazzo** [comment]
The ambiguity is probably at postgres level, and can be solved using a cast.

This is likely not a psycopg issue, rather a postgres cast system problem. However I can take a look at it but I should see the generated values, not the template. What's the value in `patch_data` that fails insert?

**Comment by PMLP-novo** [comment]
The problematic column has values of the following form, which where made to a text column in the tmp table:
```
[ None, None, None, None, datetime.datetime(2020, 1, 7, 15, 47)]
```
By adding `datetime.datetime(2020, 1, 7, 15, 47, 35, 734804)` it correctly converted it to a datetime column.

**Comment by dvarrazzo** [comment]
It shouldn't make a difference, and I don't see one.

If you look at execute_values, it boils down to calling `cur.mogrify()` on the arguments and mash them into a template, which in your case is just `(%s, %s, ...)` (the default).

`mogrify()` converts the data into a sql string. The two strings generated:

```python
In [1]: import psycopg2
In [2]: cnn = psycopg2.connect('')
In [3]: cur = cnn.cursor()
In [4]: import datetime

In [7]: cur.mogrify("%s", [datetime.datetime(2020, 1, 7, 15, 47, 35, 734804)])
Out[7]: "'2020-01-07T15:47:35.734804'::timestamp"

In [8]: cur.mogrify("%s", [datetime.datetime(2020, 1, 7, 15, 47)])
Out[8]: "'2020-01-07T15:47:00'::timestamp"
```

both look valid:

```
$ psql
=# select '2020-01-07T15:47:35.734804'::timestamp;
         timestamp          
----------------------------
 2020-01-07 15:47:35.734804
(1 row)

Time: 41.613 ms
=# select '2020-01-07T15:47:00'::timestamp;
      timestamp      
---------------------
 2020-01-07 15:47:00
(1 row)
```

I don't think your issue comes from psycopg misinterpreting a datetime with seconds 0. If you think it does please provide a repeatable test failing.
