### ISSUE TITLE
problem about psycopg2 rely on openssl

### ISSUE THREAD

**Issue by pickutechnology** [psycopg/psycopg2#1030]
Recently I upgraded my MAC system , due to the environment on mac has some change.  
before upgraded , the openssl version is 1.0.x .  But now , it 's 1.1.1.
Meanwhile my task has some error with psycopy2(local version 2.8.4) ， the error msg is ： 
"ImportError: dlopen(/Users/tangchen/anaconda3/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libssl.1.0.0.dylib " .
i think the error reason is the psycopg2 rely on openssl version is 1.0.0 .  In openssl 1.1.1 is incompatible。
About my idea is true?

**Comment by dvarrazzo** [comment]
No, not true. Psycopg works with openssl 1.1.1 too. Probably you have to re-install the libpq library (which is the one using openssl - psycopg doesn't use it directly).

I can't help you further on mac: I don't own one.

**Comment by pickutechnology** [comment]
> No, not true. Psycopg works with openssl 1.1.1 too. Probably you have to re-install the libpq library (which is the one using openssl - psycopg doesn't use it directly).
> 
> I can't help you further on mac: I don't own one.

thanks . i had already sloved it .

**Comment by meridsa** [comment]
Hi, sorry for posting in a closed issue but @pickutechnology, how did you solve this?

> thanks . i had already sloved it .

**Comment by darraghenright** [comment]
Hi @pickutechnology — I would like to second the question that @meridsa asked. Encountering the same problem and unable to solve. Reinstalling `openssl` and `libpq` didn't sort it. Thanks a million.

**Comment by carolynjonesconway** [comment]
+1, @pickutechnology would love to know how you solved this

**Comment by pickutechnology** [comment]
> +1, @pickutechnology would love to know how you solved this

You should make sure your Mac is installed postgresql at first , and then to pip install psycopg2 .   
use this command , "brew install postgresql"  to install
