### ISSUE TITLE
The C module should be optional

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#1032]
There should be a pure Python implementation of _psycopg.so using the libpq in cffi.

At install time compiling should be attempted, and the library should fall back to Python if import fails.

**Comment by DzigaV** [comment]
> There should be a pure Python implementation of _psycopg.so using the libpq in cffi.
> 
> At install time compiling should be attempted, and the library should fall back to Python if import fails.

This would be amazing for PyPy, if you can give us a way to force the pure python implementation.

**Comment by dvarrazzo** [comment]
@DzigaV It is happening in psycopg3.

**Comment by dvarrazzo** [comment]
Psycopg3 will have the C layer as an optional thing on top of the Python implementation.

https://www.psycopg.org/psycopg3/docs/install.html
