### ISSUE TITLE
Restore compatibility of Column with tuple-like behaviour

### ISSUE THREAD

**Issue by pakal** [psycopg/psycopg2#1034]
Utilities like Django's "get_table_description(self, cursor, table_name)" seem to still rely on the (named)tuple-like behaviour of Columns, and they broke with v2.8 when columns became custom class instances.

Eg. a line like 

`return [FieldInfo(*line[0:6], *field_map[line.name]) for line in cursor.description]`

raises 

`TypeError: sequence index must be integer, not 'slice'`

Would it be feasible to enhance Column so that it still supports slicing ?

(I assume the behavioral change was not wanted since it doesn't appear in https://www.psycopg.org/docs/news.html#what-s-new-in-psycopg-2-8)

Psycopg2: version 2.8.4

**Comment by dvarrazzo** [comment]
Well, the specs say that the description should behave as a 7-item sequence, not necessarily sliceable.

However in previous version we advertised the object to be a tuple so I can see how people used all its methods.

I think I can ship a version quickly enough with the tuple behaviour restored. Can you provide a patch or I should do it myself?

Thank you for the report.

**Comment by pakal** [comment]
Sorry my CPython skill is a bit too low for this, but I can contribute tests/docs when the C implementation is drafted!

**Comment by dvarrazzo** [comment]
No problem: I'll prepare a branch these days, testing will be welcome, thank you.

**Comment by pakal** [comment]
Thanks a lot!
