### ISSUE TITLE
UniqueViolation on parallel CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by mskoenz** [psycopg/psycopg2#1036]
Hi!

First of, thx for the great module!!

I'm not sure if this is a bug or my lack of understanding, I'm not a postgres expert, but have extensive experience with sqlite.

### Task
I hammer a database in parallel with multiple `CREATE TABLE IF NOT EXISTS` statements. 

postgres is running and has a database demodb.
```bash
mkdir demopg && initdb -D demopg && postgres -D demopg
(second terminal): psql postgres -c 'CREATE DATABASE "demodb";'
```
Then I run:
```python
def module_exe(statement):
    conn = psycopg2.connect(database="demodb")
    # various isolation_level tried
    cur = conn.cursor()
    cur.execute(statement)
    conn.commit()
    cur.close()
    conn.close()

mk_table_cmd = "CREATE TABLE IF NOT EXISTS mytab (nr INT);"
rm_table_cmd = "DROP TABLE IF EXISTS mytab;"

# serial is fine
module_exe(mk_table_cmd)
module_exe(mk_table_cmd)

# I just remove the table again, you can also run a fresh database, same issue.
module_exe(rm_table_cmd)

# parallel is not
from multiprocessing import Pool
with Pool(5) as pool:
    pool.map(module_exe, [mk_table_cmd]*5)
```
### Expected Behavior
I would assume due to server-side locking, that one client creates the table and the others are silent due to the `IF NOT EXISTS` part...

### Observed Behavior
...but I get a UniqueViolation. I tried various isolation_level.
<details><summary>Click for full error</summary>
<p>

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))

  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./demo_fail.py", line 12, in module_exe
    cur.execute(statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.

"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./demo_fail.py", line 29, in <module>
    pool.map(module_exe, [mk_table]*5)
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.
```

</p>
</details>

### Same "behavior" with `psql`

In order to figure out, whether this is a `psycopg`issue, I tried directly with the cli-interface `psql` with identical results. This leads me to belief, that I didnt understand something fully, I still post this here in case other encounter this as well.

```python
...
# but it also is happens with  psql
import subprocess
def psql_exe(statement):
    subprocess.run(["psql", "demodb", "-c", statement], check=True)

psql_exe(rm_table_cmd)  # remove table
# serial is fine
psql_exe(mk_table_cmd)
psql_exe(mk_table_cmd)

psql_exe(rm_table_cmd) # remove table, there is no error if it alredy exists
# parallel is not
with Pool(5) as pool:
    pool.map(psql_exe, [mk_table_cmd]*5)
```
<details><summary>Click for full output and error</summary>
<p>

```
DROP TABLE
CREATE TABLE
NOTICE:  relation "mytab" already exists, skipping
CREATE TABLE
DROP TABLE
CREATE TABLE

ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(mytab, 2200) already exists.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./demo_fail.py", line 39, in psql_exe
    subprocess.run(["psql", "demodb", "-c", statement], check=True)
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['psql', 'demodb', '-c', 'CREATE TABLE IF NOT EXISTS mytab (nr INT);']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./demo_fail.py", line 49, in <module>
    pool.map(psql_exe, [mk_table_cmd]*5)
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/mskoenz/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
subprocess.CalledProcessError: Command '['psql', 'demodb', '-c', 'CREATE TABLE IF NOT EXISTS mytab (nr INT);']' returned non-zero exit status 1.
```

</p>
</details>

### My setup
OSX 10.15.2
Python 3.7.6
psycopg2==2.8.4

**Comment by mskoenz** [comment]
I just checked the same code with python's `sqlite3` which does not run into this issue.

**Comment by dvarrazzo** [comment]
> `<details><summary>Click for full error</summary>`

Lol, I had no idea of about this :D

Thank you for the detailed description. What you see is not a behaviour of psycopg, which is only a client-side library, but of the server, which manages the lock (you are surely aware that this is a different situation from sqlite, which is a library, not a server, so the locks are likely managed by the clients themselves). The fact that psql behaves the same way demonstrates this.

It seems to me that `create table if not exists` gives a sort of promise of atomicity that doesn't maintain. But I don't know if that's a bug (which would be in the server - what postgres version?) or if the current behaviour, with a window between checking if the table exists and creating it, is considered tolerable, _given the intended use case_. I think you are better off asking your question to the pgsql-general@postgresql.org mailing list, where many postgres developers lurk and may answer better.

More about _the intended use case_ - only my opinion though: in postgres, unlike sqlite, you usually set up the layout of the database in an initial schema deployment phase, and then limit your application to use DDL statements; often the second is a less privileged user which cannot manipulate the schema, only the data. DDL statements are the ones really designed for concurrency; DML statements often take [stronger locks](https://www.postgresql.org/docs/current/explicit-locking.html) so are not really parallelizable.

If you really really want to have parallel connections trying to create the same table and the behaviour of `create table if not exists` is unsatisfactory, you might be better off using a [advisory locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS) in your application, which instead are guaranteed atomic. Something like (untested):

```python
cur.execute("select pg_advisory_lock(%s)", [hash(table_name)])
try:
    cur.execute("create table if not exists ...")
finally:
    cur.execute("select pg_advisory_unlock(%s)", [hash(table_name)])
    conn.commit()
```

Hope this helps.

**Comment by mskoenz** [comment]
For completion:
postgres version: 12.1


Thanks for the elaborated answer!
Yes, your arguments make lots of sense, what I'm doing is not the intended use case ^^ I will read up on the guarantees!
I tested your proposition and it works nicely, I just had to not use the hash function, since python hashes are salted, i.e. different subprocs produce different hashes with same input.

``` python
def module_exe(statement):
    conn = psycopg2.connect(database="demodb")
    ilevel = psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT
    conn.set_isolation_level(ilevel)
    cur = conn.cursor()

    myhash = 123456  # in reality some persistent hash
    # myhash = hash("mytab") is bad, since python hash is salted, i.e. different
    # subprocesses produce different hashes with same input (security reasons)
    cur.execute("select pg_advisory_lock(%s)", [myhash])
    try:
        cur.execute(statement)
    finally:
        cur.execute("select pg_advisory_unlock(%s)", [myhash])

    conn.commit()
    cur.close()
    conn.close()

# code above works with this
```

**Comment by dvarrazzo** [comment]
> I just had to not use the hash function, since python hashes are salted, i.e. different subprocs produce different hashes with same input.

Ah sure. Well, 63 bits of the sha1 of the table name should work ok.

**Comment by mskoenz** [comment]
I ended up using a long long, since https://www.postgresql.org/docs/current/view-pg-locks.html states: 

Advisory locks can be acquired on keys consisting of either a single bigint value or two integer values....

```python
lock_byte = str(table_name).encode('utf-8')
digest = hashlib.sha1(lock_byte).digest()
lock_hash = struct.unpack('<q', digest[:8])  #q=long long
cur.execute('select pg_advisory_lock(%s)', [lock_hash])
```
