### ISSUE TITLE
ImportError: /usr/pgsql-11/lib/libpq.so.5: symbol X509_get_signature_nid, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference

### ISSUE THREAD

**Issue by rupert97** [psycopg/psycopg2#1037]
Hi, Any idea how to solve this problem?
python 2.7.5
PostgreSQL 11
psycopg2 2.8.4

Error message ImportError: /usr/pgsql-11/lib/libpq.so.5: symbol X509_get_signature_nid, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference
 
I tried to upgrade OpenSSL but doesn't work
 OpenSSL version OpenSSL 1.0.2u  20 Dec 2019

**Comment by dvarrazzo** [comment]
This is an issue of libpq with libssl on your system, I don't think it's under psycopg control.

Shootgun debugging. Try using the wheel package. If you are using the wheel package then don't.

You can ask your question to the pgsql-general@postgresql.org mailing list, they might be able to help better
