### ISSUE TITLE
How to create citext from executing command.

### ISSUE THREAD

**Issue by rjsnh1522** [psycopg/psycopg2#1038]
Hi,
I am trying to create citext in db; but my command its not working. I cant go inside psql to create citext
I am using the following code but its not working. basically i want to create citext for specific database.
I am creating database from script and want to set citext also.

 ```
 citext_query = "SELECT typarray FROM pg_type where typname = 'citext'"

            try:
                cursor.execute(citext_query)
                citext_array_oid = cursor.fetchone()
                if citext_array_oid:
                    psycopg2.extensions.register_type(
                        psycopg2.extensions.new_array_type(
                            (citext_array_oid[0],), 'CITEXT[]', psycopg2.STRING))
            except Exception as e:
                print("# citext is not available on the database.")
```

**Comment by dvarrazzo** [comment]
I'm sorry but your request is not clear to me, and it is not a bug. Please write the mailing list if you need more information.
