### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by vishal7732** [psycopg/psycopg2#1045]
I am a beginner and I am facing issue in psycopg2 installation in my pycharm (venv) on my windows.  How to solve it...

**error**

(venv) C:\Users\Vishal\PycharmProjects\website>pip install psycopg2
Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\psycopg2.egg-info
    writing pip-egg-info\psycopg2.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\psycopg2.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\psycopg2.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Vishal\AppData\Local\Temp\pip-install-yhws7zqc\psycopg2\

**Comment by dvarrazzo** [comment]
Try updating pip first.
