### ISSUE TITLE
psycopg2 is that support python 3.8?

### ISSUE THREAD

**Issue by AliYmn** [psycopg/psycopg2#1047]
Hi, i when tried install psycopg2, i got some error.

    pip3.8 install psycopg2

OUTPUT:

        ERROR: Command errored out with exit status 1:
        command: /home/aliymn44/env/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-27jfqv73/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-27jfqv73/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-27jfqv73/psycopg2/pip-egg-info
            cwd: /tmp/pip-install-27jfqv73/psycopg2/
        Complete output (7 lines):
        running egg_info
        creating /tmp/pip-install-27jfqv73/psycopg2/pip-egg-info/psycopg2.egg-info
        writing /tmp/pip-install-27jfqv73/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
        writing dependency_links to /tmp/pip-install-27jfqv73/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
        writing top-level names to /tmp/pip-install-27jfqv73/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
        writing manifest file '/tmp/pip-install-27jfqv73/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
        Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

System Informations;
- Ubuntu

**Comment by dvarrazzo** [comment]
> Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'

👆This?

https://www.psycopg.org/docs/install.html#prerequisites

**Comment by Huyassin** [comment]
Instead pip command use:

`sudo apt-get install libpq-dev`
then use:

`pip3 install psycopg2`
UBUNTU 20.04 PYTHON 3.8

IT SOLVES ME THE SAME ERORR
