### ISSUE TITLE
Can not insert valid Postgres Values from a pandas frame

### ISSUE THREAD

**Issue by crauterb** [psycopg/psycopg2#1048]
Heyho.

I am currenlty facing the problem that I can not insert valid values from a Pandas DataFrame into my Postgres using Psycopg2 and would love to get some feedback on the issue.

**Scenario**
I have created a Pandas DataFrame rows composed of multiple rows. For that purpose, I am using `copy_from` and `StringIO`, 

**Expected behaviour**
I am inserting valid values, therefore it should work fine.

**Actual behaviour**
I do get the following error:
```
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: ""
CONTEXT:  COPY processed, line 9877, column messwert: ""
```
**Additional Information**

`pip list` yields: `psycopg2          2.8.4`

The according frame is created as a numeric type:
```
df['messwert'] = df['messwert'].apply(pd.to_numeric)
```

Here is my snippet for writing the data to Postgres:
```
s_io = StringIO()
s_io.write(df.to_csv(index=None, header=None, sep=";", encoding="utf-8, quoting=csv.QUOTE_NONE))
s_io.seek(0)
self.cursor.copy_from(file=s_io, table=f"{self.schema}.{table}", columns=df.columns, sep=";")
self.dbconn.commit()
```
My according table looks (simplified) like this
```
CREATE TABLE my_table (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	messwert numeric NULL,
	CONSTRAINT my_table_pkey PRIMARY KEY (id)
);
```
using PostgreSQL directly (e.g. `psql`), I can insert into the table using empty values or NULL, e.g. 
```
s_io = StringIO()
s_io.write(df.to_csv(index=None, header=None, sep=";", encoding="utf-8, quoting=csv.QUOTE_NONE, na_rep="NULL"))
s_io.seek(0)
self.cursor.copy_from(file=s_io, table=f"{self.schema}.{table}", columns=df.columns, sep=";")
self.dbconn.commit()
```
yields the same error ...

This seem weird to me, as I should be able to pass on values that PostgreSQL would allow me to write - or am I overseeing something? 
Could someone please point me into the right direction if so? :-)

**Comment by dvarrazzo** [comment]
I think you should speak with some pandas group, not here. It seems that object is not generating a number, but that's outside our control.
