### ISSUE TITLE
psycopg2 is slow to connect to postgresql12 server without gssencmode=disable

### ISSUE THREAD

**Issue by akrherz** [psycopg/psycopg2#1049]
I've been banging my head trying to figure out why my python=3.8 psycopg2=2.8.4 install on linux64 is so slow to connect to a postgresql12 server.  For example, using `psql` for illustrative purposes...

```
time for i in `seq 1 100`; do psql -h 192.168.1.245 mesosite -c "select 1" > /dev/null; done
real	0m12.907s
user	0m0.447s
sys	0m0.634s
```

After some thrashing about, I discovered the `gssencmode=disable` setting and wa-la:

```
time for i in `seq 1 100`; do psql -h 192.168.1.245 "dbname=mesosite gssencmode=disable" -c "select 1" > /dev/null; done
real	0m0.787s
user	0m0.238s
sys	0m0.291s
```

Of course, the above is with psql and not psyscopg2, but the same performance difference holds true there too.

```
$ python -m timeit -n 100 -r 1 'import psycopg2; psycopg2.connect("dbname=mesosite host=192.168.1.245").cursor().execute("SELECT 1")'
100 loops, best of 1: 111 msec per loop
$ python -m timeit -n 100 -r 1 'import psycopg2; psycopg2.connect("dbname=mesosite host=192.168.1.245 gssencmode=disable").cursor().execute("SELECT 1")'
100 loops, best of 1: 3.24 msec per loop
```

I figured I would put this issue here for others to perhaps find or perhaps devs here have more commentary on this situation.  Feel free to angrily close as well :)  Thanks for this excellent library!

**Comment by dvarrazzo** [comment]
Yes, of course it is not psycopg-related but it's good to know. Maybe the issue should be discussed with PostgreSQL developer: I don't know if their default err on the side of safety rather than performance, which is reasonable, but maybe they could have some area in the documentation where they explain the implications of the defaults and the way to avoid paying the cost if the environment offers enough border safety.

I also wonder if in psycopg docs we could have similar disclaimers...

**Comment by dvarrazzo** [comment]
I don't know exactly what do do about this. I don't think gssencmode is the only thing to take care of dealing with connection speed (names resolution comes to mind). It doesn't affect psycopg only but anything using libpq. I think there should be a resource with a description of this behaviour, ideally in Postgres docs, but if it's not there I'm ok to add something.

I'm closing this but I'm open to docs patches to explain things in a coherent ways, not just a WARNING in the `psycopg2.connect()` docs.
