### ISSUE TITLE
fail to pip install psycopg2

### ISSUE THREAD

**Issue by abuakram** [psycopg/psycopg2#1050]
ubuntu 19.10
Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.

I tried to install libpq-dev but I get following response:
Unable to locate package libpg-dev
I downloaded the libpg-dev binary file and installed it, but no success

How can I fix this?

**Comment by dvarrazzo** [comment]
> Unable to locate package libpg-dev

it's `libpq-dev`, not `libpg-dev`.

**Comment by abuakram** [comment]
thanks for your quick response
and sorry for my misspelling, but the issue persists...
Unable to locate package linpq-dev

**Comment by dvarrazzo** [comment]
lol, fun
