### ISSUE TITLE
Allow page_size to use scientific notation

### ISSUE THREAD

**Issue by amarvin** [psycopg/psycopg2#1051]
`psycopg2.extras._paginate()`  argument `page_size` must be an integer, so scientific notation cannot be used as they produce a float. This impacts `psycopg2.extras.execute_batch()` and `psycopg2.extras.execute_values()`.

```python
import psycopg2
from psycopg2.extras import execute_batch, execute_values

#... connect with cursor "cur"

# These work, as page_size is an integer
execute_values(cur,
    "insert into testfast (id, val) values %s",
    ((i, i * 10) for i in range(25)),
    page_size=10)
execute_values(cur,
    "insert into testfast (id, val) values %s",
    ((i, i * 10) for i in range(25)),
    page_size=10)

# These fail, as page_size isn't an integer
execute_values(cur,
    "insert into testfast (id, val) values %s",
    ((i, i * 10) for i in range(25)),
    page_size=1e1)
execute_values(cur,
    "insert into testfast (id, val) values %s",
    ((i, i * 10) for i in range(25)),
    page_size=1e1)
```

When page_size is a large integer, it's more convenient to use scientific notation than write out the whole integer. Would be great if psycopg2 just converted the input to integer.

**Comment by dvarrazzo** [comment]
I'm not sure it convinces me. 1e1 _is_ a float, that happens to have no decimal part. Why should the function accept it, as well as accepting a string that happens to represent a number or a complex number that happens to have 0 as imaginary part? For me it is a TypeError.

How large is your page size that you need scientific notation to represent it? 1e18?

**Comment by amarvin** [comment]
Fair point that my PR would then also allow strings and complex numbers. Could the error traceback be improved then for beginners? Currently:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    execute_values(cur, insert_query, data, page_size=1e5)
  File "...\psycopg2\extras.py", line 1265, in execute_values
    for page in _paginate(argslist, page_size=page_size):
  File "...\psycopg2\extras.py", line 1158, in _paginate
    for i in range(page_size):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by dvarrazzo** [comment]
It seems a pretty clear error message to me. It comes directly from Python if you call `range(1e3)`: if you don't think it's clear you should ask the Python devs.
