### ISSUE TITLE
 get the following error when trying to install psycopg2==2.8.4

### ISSUE THREAD

**Issue by abhijeet201998** [psycopg/psycopg2#1054]
Collecting psycopg2==2.8.4
  Using cached psycopg2-2.8.4.tar.gz (377 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/abhijeet/.pyenv/versions/3.7.3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info
         cwd: /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/vq/_rpvmgzx4517hkm98dq9c29c0000gn/T/pip-install-gbhh33k1/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dvarrazzo** [comment]
What version of pip are you using?

**Comment by dvarrazzo** [comment]
Ah you are not on windows. So you are simply not paying attention to the error message.

As the manual say, you either install the dependencies or you install psycopg2-binary. This is not a bug.

**Comment by sparsh-goil** [comment]
The above issue comes when potgres is not installed on the system. Upon Install postgres, the `pg_config` will be automatically set up in config file.
Refer this for installing postgres: [https://www.postgresql.org/download/](https://www.postgresql.org/download/)
