### ISSUE TITLE
No way to change error verbosity?

### ISSUE THREAD

**Issue by alicederyn** [psycopg/psycopg2#1056]
I would like to change the error verbosity to TERSE so potentially sensitive data is not leaked via exceptions. This seems to be done by calling [PQsetErrorVerbosity](https://www.postgresql.org/docs/9.6/libpq-control.html#LIBPQ-PQSETERRORVERBOSITY) which I can't see a call to in this codebase — am I right that this means there's no way to do this without a code change to psycopg2?

**Comment by dvarrazzo** [comment]
Hello,

no, there is no currently exposed way to change the error message verbosity. However you can use the cffi to call the libpq function, passing it the libpq connection pointer exposed by [`pgconn_ptr`](https://www.psycopg.org/docs/connection.html#connection.pgconn_ptr).

You can take a look at the example in the `pgconn_ptr` documentation to have an idea of how.

I'm interested to know if it works: please let us know, thank you.

**Comment by alicederyn** [comment]
We gave this a try. It looks like the verbosity is somehow defaulting to `6`, which is not a valid value for that enum (should be 0-2). Changing it to `0` had no effect on the error verbosity.

```
>>> libpq.PQsetErrorVerbosity(cursor.db.connection.pgconn_ptr, 0)
6
```

Not sure how this could possibly be being set to 6, since libpq sets it to 0 initially and contains no code to change it (other than PQsetErrorVerbosity). Out of sheer confusion, I have spent the day casting around libpq and ctypes to decode the pg_conn struct, and have confirmed that verbosity is definitely set to 6 initially, and it's not a bug in that function. (I also confirmed that the sversion field was erroneously set to 0, as noted in one of your tests.) Is something getting corrupted?

Also baffled why setting it to 0 is having no effect.

**Comment by dvarrazzo** [comment]
Why `INTP`? It seems you have defined the second parameter as a pointer, whereas a normal int should do.

I don't have a test case for verbosity, but ISTM that the return value is consistent with what documented - the previous value. Maybe you are configuring the ctypes parameters wrong?

```python
>>> import ctypes.util
>>> libpq = ctypes.pydll.LoadLibrary(ctypes.util.find_library('pq'))
>>> libpq.PQsetErrorVerbosity.argtypes = [ctypes.c_void_p, ctypes.c_int]
>>> libpq.PQsetErrorVerbosity .restype = ctypes.c_int

>>> cnn = psycopg2.connect('')
>>> libpq.PQsetErrorVerbosity(cnn.pgconn_ptr, 0)
1
>>> libpq.PQsetErrorVerbosity(cnn.pgconn_ptr, 1)
0
>>> libpq.PQsetErrorVerbosity(cnn.pgconn_ptr, 2)
1
>>> libpq.PQsetErrorVerbosity(cnn.pgconn_ptr, 0)
2
```

**Comment by alicederyn** [comment]
Ah, if you're not seeing a starting value of 6 then maybe the issue is in the library we are using that wraps psycopg2, namely Django. Will investigate. Thanks!

**Comment by dvarrazzo** [comment]
I think this can be closed

**Comment by alicederyn** [comment]
Hi @dvarrazzo 

We tracked our problem back to the `psycopg2-binary` package not being built against the same libpq as the one that ships with our OS image. We were able to get the workaround to work with the non-binary `psycopg2` package, but that's unfortunately not the one that Django has as a dependency, and poetry doesn't let us work around that.

If we added a `set_error_verbosity` function to the psycopg2 API, that would be ideal, as it would obviously use whichever libpq it was built against. Would that be a reasonable feature to add? We can work on a PR if so.

**Comment by dvarrazzo** [comment]
Hi @alicederyn 

I don't know what is poetry. I think it's not wise to depend on psycopg2-binary: that is explicitly discouraged in the documentation.

It is probably reasonable to add `set_error_verbosity` to psycopg but we should test if it doesn't interfere with the error message parsing. Typically a new feature is added in major releases but there isn't one scheduled in the immediate future: we may cheekily sneak this one in a dot release, but again, pending checking if it doesn't cause side effects.

A contribution to the project would be welcome: see Sponsor button above the page, thank you.

**Comment by alicederyn** [comment]
poetry is a popular recent alternative to pip: https://python-poetry.org/

**Comment by alicederyn** [comment]
Thanks, Daniele, we'll look into raising a PR
