### ISSUE TITLE
Database binding hanging at _connect

### ISSUE THREAD

**Issue by slyduda** [psycopg/psycopg2#1059]
Hi, I am using a simple async web server and creating a connection to my database with sshtunnel. Unfortunately, my connection hangs on the following line of code within the init file despite the information being supplied correctly:

```python
#found at pycopg2.__init__.py on line 126

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
```

I am unable to debug this because it seems that the _connect function stems from psycopg2._psycopg which is compiled. Please let me know if this is a common issue.

**Comment by dvarrazzo** [comment]
sshtunnel is broken: https://github.com/pahaz/sshtunnel/issues/135
