### ISSUE TITLE
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

### ISSUE THREAD

**Issue by HTG-YT** [psycopg/psycopg2#1062]
**Operating System:** Windows 10 Home
**IDE:** PyCharm Professional
**Python version:** 3.8.2
**pip version:** 19.0.3

I installed `psycopg2` with the command `pip install psycopg2==2.8.4`.

When I did `import psycopg2` inside my Python script, the error(in the title) occurred and following the error I have the problem right here:
```python
from psycopg2._psycopg import (                     # noqa
    BINARY, NUMBER, STRING, DATETIME, ROWID,

    Binary, Date, Time, Timestamp,
    DateFromTicks, TimeFromTicks, TimestampFromTicks,

    Error, Warning, DataError, DatabaseError, ProgrammingError, IntegrityError,
    InterfaceError, InternalError, NotSupportedError, OperationalError,

    _connect, apilevel, threadsafety, paramstyle,
    __version__, __libpq_version__,
)
```
So what happened here?

**Comment by dvarrazzo** [comment]
Upgrade pip.

**Comment by dvarrazzo** [comment]
Also, please open a bug to pycharm. I don't think I'm able to.

https://www.jetbrains.com/help/pycharm/reporting-issues.html#report-an-issue

**Comment by HTG-YT** [comment]
Have upgraded pip to the latest version, the problem is still there.

**Comment by HTG-YT** [comment]
@dvarrazzo and also opened an issue to pycharm. and one more thing the error seems to occur to the _psycopg2 PYD file

**Comment by dvarrazzo** [comment]
See #1006. Please have this problem fixed in pycharm, because psycopg2 works alright with normal Python.

**Comment by chrismahn2020** [comment]
> 
> 
> Have upgraded pip to the latest version, the problem is still there.

python -m pip install pip==19.3.1  should do the trick

**Comment by dvarrazzo** [comment]
@chrismahn2020 19.3.1 is not the last pip version. Why are you suggesting to downgrade pip?

**Comment by iamhpdev** [comment]
the only way to solve this error is downgrade the python version to second last recent version. for ex 10 is latest version then you have to install 9. and problem solved

**Comment by adjenks** [comment]
I'm installing psycopg2 on Windows and I am getting this error.
I have pip 20.2.4
My python is version 3.9.0
I have the latest version of Visual studio installed along with the build tools.
I built it and it failed with the error in the previously linked issue: https://github.com/psycopg/psycopg2/issues/1006
>ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
