### ISSUE TITLE
got issue, running from init.py

### ISSUE THREAD

**Issue by fforius** [psycopg/psycopg2#1063]
psycopg2                    2.6.1
   psycopg2-binary             2.8.4

trying to run __init__.py

    from sqlalchemy import create_engine
    from sqlalchemy.ext.declarative import declarative_base
    from sqlalchemy.orm import sessionmaker, scoped_session
    from userbot import DB_URI
 
    BASE = declarative_base()

    def start() -> scoped_session:

    engine = create_engine(DB_URI)
    BASE.metadata.bind = engine
    BASE.metadata.create_all(engine)
    return scoped_session(sessionmaker(bind=engine, autoflush=False))
   
    SESSION = start()

but i got this

    SESSION = start()
    File "/root/OpenUserBot/userbot/modules/sql_helper/__init__.py", line 10, in start
    engine = create_engine(DB_URI)
    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
    File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 737, in dbapi
    import psycopg2
    File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 104
    connection_factory=None, cursor_factory=None, async=False, **kwargs):
                                                  ^
    SyntaxError: invalid syntax

then when i try to update psycopg2

    Using cached psycopg2-2.8.4.tar.gz (377 kB)
    Building wheels for collected packages: psycopg2
    Building wheel for psycopg2 (setup.py) ... done
    Created wheel for psycopg2: filename=psycopg2-2.8.4-cp38-cp38-linux_x86_64.whl size=383839 
    sha256=1d51773b9023b706731ae2f2d0fe60bc1bb93ee29e1da484c5dfc5585194ea1e
    Stored in directory: 
    /root/.cache/pip/wheels/ac/07/3e/87adc95a2be1ee727bc54f487ce874bd6765ec9f206effb0df
    Successfully built psycopg2
    Installing collected packages: psycopg2
    Attempting uninstall: psycopg2
    Found existing installation: psycopg2 2.6.1

    ERROR: Cannot uninstall 'psycopg2'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by dvarrazzo** [comment]
The syntax error on `async` is something fixed in the most recent version of psycopg2.

Instructions about building psycopg are available in the documentation. Using the binary package is better for you though.

I suggest you `pip uninstall` both the source and the binary package and then install only the binary.

In case of other doubts don't open a bug unless you have read the documentation first, thank you.
