### ISSUE TITLE
DLL load failed while importing aggregations

### ISSUE THREAD

**Issue by hangockhanh** [psycopg/psycopg2#1065]
Hello everyone, when I import module pandas then appear this mistake. I don't know how to fix :(
![image](https://user-images.githubusercontent.com/62347321/77844958-0b503500-71d5-11ea-8ed0-c3126274d9dd.png)

**Comment by dvarrazzo** [comment]
Wrong project.

**Comment by hangockhanh** [comment]
> Wrong project.

what do u mean? Do u know how to fix :(

**Comment by dvarrazzo** [comment]
that this is psycopg2, we talk to the database, not pandas. psycopg2 is not even mentioned in your traceback above. Ask someone in the pandas project, which is not us.
