### ISSUE TITLE
Server Closed the connection unexpectedly

### ISSUE THREAD

**Issue by robdickens** [psycopg/psycopg2#1066]
Hi,

Appreciate there have been a few issues raised in error on this, so I've gone through to make sure I'm not making any obvious mistakes, but it could still be me!

I'm using the following code to raise a connection

`conn_string = "host={0} user={1} dbname={2} password={3} sslmode={4} port={5}".format(host, user, dbname, password, sslmode, port)`
`conn = psycopg2.connect(conn_string)`

where sslmode is "disable" and my DB on Azure does not enforce SSL.
Every time I try to connect, I'm getting "server closed the connection unexpectedly".
Looking at the server logs - is see the following:

```
2020-03-29 14:07:25 UTC-5e80ab9d.20624-LOG:  connection received: host=[hostname] port=8706 pid=132644
2020-03-29 14:07:25 UTC-5e80ab9d.20624-LOG:  connection authorized: user=[username] database=[database] SSL enabled (protocol=TLSv1.2, cipher=[cipher], compression=off)
```

There are a couple of things that stand out which I don't understand whether I've configured something wrong or it is an actual bug.

- with sslmode=disable, the server log still appears to list ssl enabled
- the port number is not what I'm expecting (5432 is what I passed into the connection)

Is there something obvious I'm missing? Any help would be appreciated.

Versions:
psycopg=2.8.4
python=3.7
Azure Database for PostgreSQL server=9.6

**Comment by dvarrazzo** [comment]
Apart from an insecure way to generate the connection string (what if someone's password is `dummy port=8706`?), I don't see anything wrong there: you just connect.

Try maybe to double-check if the dsn on the connection is what you expect. You can't if the above raises an exception, but if you open the connection with `async_=True` then you can have a Python object although not connected, and read the dsn before a `poll()`. So I would do:

```python
conn = psycopg2.connect(
    host=host, user=user, dbname=dbname, password=password, sslmode=sslmode, port=port,
    async_=true
)
print(conn.dsn)
```

I think this should just confirm that the dsn is what you expect to be, and the problem is in Azure's plumbing.

**Comment by robdickens** [comment]
Thanks for the advice @dvarrazzo on the connection string (not what I started with, more of a trial and error so I will replace!)
In the server logs, I'm actually seeing a different port with every connection attempt - which I certainly didn't expect.
Following your suggestion I turned on async and printed the dsn - all as I was expecting and set (including the port number and sslmode).

Now that you've verified my code snippet I'm inclined to agree that this must be an Azure issue, however are you able to provide any options for increased logging within psycopg2 which would help me diagnose the issue further?

Many thanks for the speedy response.

**Comment by robdickens** [comment]
Closing issue as I believe this in an Azure problem

**Comment by dvarrazzo** [comment]
You could actually try to connect with psycopg3: it's not released yet but it has the connection loop in Python so you can investigate with it maybe.

```
In [1]: import logging                                                                                                   
In [2]: logging.basicConfig(level=logging.DEBUG)                                                                         
In [3]: import psycopg3                                                                                                  
In [4]: logging.getLogger("psycopg3.connection").setLevel(logging.DEBUG)                                                 
In [5]: psycopg3.connect("host=localhost")                                                                               
DEBUG:psycopg3.connection:connection started, status STARTED
DEBUG:psycopg3.connection:connection polled, status MADE
DEBUG:psycopg3.connection:connection polled, status SSL_STARTUP
DEBUG:psycopg3.connection:connection polled, status SSL_STARTUP
DEBUG:psycopg3.connection:connection polled, status SSL_STARTUP
DEBUG:psycopg3.connection:connection polled, status SSL_STARTUP
DEBUG:psycopg3.connection:connection polled, status MADE
DEBUG:psycopg3.connection:connection polled, status AWAITING_RESPONSE
DEBUG:psycopg3.connection:connection polled, status AWAITING_RESPONSE
DEBUG:psycopg3.connection:connection polled, status AWAITING_RESPONSE
DEBUG:psycopg3.connection:connection polled, status AWAITING_RESPONSE
DEBUG:psycopg3.connection:connection polled, status AWAITING_RESPONSE
DEBUG:psycopg3.connection:connection polled, status OK
Out[5]: <psycopg3.connection.Connection at 0x7f3245ad4400>
```

You can install it using `pip install -e  "git+https://github.com/psycopg/psycopg3.git#egg=psycopg3"`

and actually if you give it a go I'd be curious to know where it gets stuck.

**Comment by robdickens** [comment]
Thank you @dvarrazzo that's really useful! I will try that now.
I've also got a ticket open with Microsoft so I will feed back my findings and keep you informed
