### ISSUE TITLE
Receiving dictionary or json type when querying a rated tsvector column

### ISSUE THREAD

**Issue by hebelsan** [psycopg/psycopg2#1067]
I'm currently working with the rated tsvector type in postgres.
If in python i query this type with e.g.:
SELECT
     rated_tsv
FROM
    docs
WHERE
    id = 1
i receive the following string.
"'page':2A 'second':1A 'test':3A 'titl':4A 'virus':6A"

My current solution is to have a type_cast_function which transforms this string to a dicitonary.
But this is not very convenient.
It would be nice if the returning object would be of type json or dictionary right away.

best regards,
alex

**Comment by dvarrazzo** [comment]
I don't understand exactly what you want (you say you transform it into a dict but you want a json or a dict: what does it mean? Json is not a Python type, it would be still a dict).

This function is a basic parser for the string above. It doesn't parse the whole tsvector probably but you get the idea and you can adapt if you need:

```python
def cast_tsvector(s, conn):
    if s is None: return None
    return {k.replace("'", ""): v for k, v in [part.split(":") for part in s.split()]}

psycopg2.extensions.register_type(psycopg2.extensions.new_type((3614,), "TSVECTOR", cast_tsvector))
```

then you can use psycopg regularly and it will return a dict on tsvector:

```python
cur.execute("select %s::tsvector", ["'page':2A 'second':1A 'test':3A 'titl':4A 'virus':6A"])
cur.fetchone()[0]
{'page': '2A', 'second': '1A', 'test': '3A', 'titl': '4A', 'virus': '6A'}
```

Does it help?
