### ISSUE TITLE
Connect with SSL Certs as strings

### ISSUE THREAD

**Issue by rorynscott** [psycopg/psycopg2#1069]
Hello!

I am wondering if it's possible, and if so, how, to pass the client cert and private key as strings to the connection object? Our applications typically try to follow the 12-factor recommendations and any secrets or certs are piped in via the environment. I tried creating a file-like object from the strings and passing that in, but that didn't work either. Any helpful hints or tips on how we should approach this if we're not writing or reading certs from the filesystem?

**Comment by dvarrazzo** [comment]
- This is the list of [all the parameters supported](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-PARAMKEYWORDS): 
- And those are the [env variables](https://www.postgresql.org/docs/12/libpq-envars.html) you can use alternatively.

It seems that `PGSSLCERT` and `PGSSLKEY` are the only way to pass the cert to the libpq, and [looking at it source code](https://github.com/postgres/postgres/blob/a80818605e5447b9b846590c3d3fab99060cb53e/src/interfaces/libpq/fe-secure-openssl.c#L987) it just expects a file name to read.
