### ISSUE TITLE
Django Postgres memory leak

### ISSUE THREAD

**Issue by pinkynrg** [psycopg/psycopg2#1070]
I have a custom Django command to start background job executers in a multi-threaded fashion which seems to give me memory leak issues. 

The command can be started like so:
```
./manage.py start_job_executer --thread=1
```

Each thread has a while True loop that picks up jobs from a PostgreSQL table. 

In order to pick up the job and change the status atomically I used transactions:

```python
# atomic transaction to temporary lock the db access and to
# get the most recent job from db with column status = pending
with transaction.atomic():
    job = Job.objects.select_for_update() \
        .filter(status=Job.STATUS['pending']) \
        .order_by('created_at').first()
    if job:
        job.status = Job.STATUS['executing']
        job.save()
```

Il looks like the allocated memory by this Django custom command keeps growing. 

Using tracemalloc I tried to find what is causing the memory leak by creating a background thread that checks the memory allocation:

```python
def check_memory(self):
        while True:
            s1 = tracemalloc.take_snapshot()
            sleep(10)
            s2 = tracemalloc.take_snapshot()
            for alog in s2.compare_to(s1, 'lineno')[:10]:
                log.info(alog)
```

Finding out the following log:

```bash
01.04.20 13:50:06   operations.py:222: size=23.7 KiB (+23.7 KiB), count=66 (+66), average=367 B
01.04.20 13:50:36   operations.py:222: size=127 KiB (+43.7 KiB), count=353 (+122), average=367 B
01.04.20 13:51:04   operations.py:222: size=251 KiB (+66.7 KiB), count=699 (+186), average=367 B
01.04.20 13:51:31   operations.py:222: size=379 KiB (+68.9 KiB), count=1056 (+192), average=367 B
01.04.20 13:51:57   operations.py:222: size=495 KiB (+60.3 KiB), count=1380 (+168), average=367 B
```

Looks like /usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/operations.py:222 does not release memory

The leakage is slow for 1 thread but if I use 8 threads the memory leak is worse:

```bash
01.04.20 13:07:51   operations.py:222: size=68.3 KiB (+68.3 KiB), count=191 (+191), average=366 B
01.04.20 13:08:56   operations.py:222: size=770 KiB (+140 KiB), count=2151 (+390), average=367 B
01.04.20 13:10:07   operations.py:222: size=1476 KiB (+138 KiB), count=4122 (+386), average=367 B

01.04.20 13:36:22   operations.py:222: size=17.3 MiB (+138 KiB), count=49506 (+385), average=367 B

01.04.20 13:48:16   operations.py:222: size=24.5 MiB (+136 KiB), count=69993 (+379), average=367 B
```

This is the code at line 222 in /usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/operations.py:222:

```python
def last_executed_query(self, cursor, sql, params):
        # http://initd.org/psycopg/docs/cursor.html#cursor.query
        # The query attribute is a Psycopg extension to the DB API 2.0.
        if cursor.query is not None:
            return cursor.query.decode() # this is line 222!
        return None
```

I have no clue how to attack this problem. Any ideas at all?

I tried to post issue on GitHub but Django doesn't allow the public to write issues.

I was thinking to maybe fork a new process for every job that needs to be executed, and once finished, the memory would be deallocated with the process itself dying. This would probably work but it seems a little overkill.

Thanks in advance

**Comment by dvarrazzo** [comment]
That's only the line that generated the string. Probably django keeps a copy of it somewhere in its belly. You could try and use [`gc.get_referrers()`](https://docs.python.org/3/library/gc.html#gc.get_referrers) to understand where.

Closing because this is not related to psycopg (`cursor.query` is just a string).

**Comment by tim-schilling** [comment]
@pinkynrg You need to use https://code.djangoproject.com/query for Django issues.
