### ISSUE TITLE
Installation of `psycopg2-binary` (2.8.5) fails with Python 3.4

### ISSUE THREAD

**Issue by crazyscientist** [psycopg/psycopg2#1075]
This seems to be a similar problem as in #765, but this started to happen with the latest release of `psycopg2-binary` (version 2.8.5) in our SLE12SP2 based Gitlab CI pipeline:

```shell
32e5bb9d9c9a:/ # pip3 install psycopg2-binary   
Collecting psycopg2-binary
  Using cached https://files.pythonhosted.org/packages/97/00/ed4c82364741031d745867f83820d4f373aa891098a5785841850491c9ba/psycopg2-binary-2.8.5.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    
    ----------------------------------------
```
Using version 2.8.5 with Python2.7 is no problem, version 2.8.4 is working with Python 3.4 however.

**Comment by dvarrazzo** [comment]
Hello,

it seems the wheel package generation tool has dropped support for Python 3.4: https://github.com/pypa/manylinux/commit/c42f688e0763a0991e15777ce46ce0444af3ca17

I apologise for this: as far as I'm concerned Python 3.4 is supported for the whole 2.8.x series; this is out of my control. We have had more problems with wheel package than I care to remember.

I'm afraid you will have to use `psycopg<2.8.5` in your `requirements.txt` file. You can try opening a bug with pipa/manylinux but they'll likely tell you that Python 3.4 has been EOL'd 1 year ago.

**Comment by dvarrazzo** [comment]
...or to install the required packages and build the package from source. What you need is explained in the docs.

**Comment by crazyscientist** [comment]
Thank you for the quick responses. :)
