### ISSUE TITLE
No new tag under releases

### ISSUE THREAD

**Issue by 0xFF1E071F** [psycopg/psycopg2#1076]
Hello ppl =)
can you please update tags under releases? I am developing packages for pisilinux and i need to download latest version from github. Latest psycopg2 is 2.8.5 under pypi.org but 2.8.4 here on github.
Thank you very much

**Comment by dvarrazzo** [comment]
Yup, sorry! Forgot a `git push --tags`. It should be ok now.

**Comment by blue-devil** [comment]
thanks
now pisi linux user can install via:
`$ sudo pisi it python3-psycopg2`
