### ISSUE TITLE
"server closed the connection unexpectedly" in psycopg2/__init__.py

### ISSUE THREAD

**Issue by robert-kisteleki** [psycopg/psycopg2#1079]
Hi,

(We've seen this issue while using 2.7.3.2, and #829 gave hope that it's fixed. Unfortunately we're still seeing this with 2.8.5 hence this new issue)

While using python 3.6.8 and psycopg2-binary 2.8.5, in a multi-threaded app, we occasionally see:

> server closed the connection unexpectedly
>	This probably means the server terminated abnormally
>	before or while processing the request.

in `python36/lib64/python3.6/site-packages/psycopg2/__init__.py in connect, line 127`

That line is:
```
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
```

This seems to happen under more-than-usual (but not particularly high) load. There's nothing related visible in the server side logs. The connections are using TLS.

Perhaps it's worth mentioning that this is under django (2.2) with a non-zero CONN_MAX_AGE setting, meaning connections are reused where possible. The error is seemingly when making new connections so this is unlikely to be related.

**Comment by dvarrazzo** [comment]
Is that a server on your local network or a cloud of some sort?

**Comment by robert-kisteleki** [comment]
All servers are local, <1ms away from each other.

**Comment by dvarrazzo** [comment]
Could you please try using the normal psycopg rather than psycopg-binary?

**Comment by robert-kisteleki** [comment]
We used to use 2.7.3.2, non-binary. That had the issue already, so in a way yes, we tried that :-) Do you think 2.8.x non-binary is worth trying?

**Comment by dvarrazzo** [comment]
It seems to me that, as the client reports, the server closed the connection. It doesn't seem related to the client. Please look at the server logs and you should see what happened.

**Comment by dvarrazzo** [comment]
Ah, sorry- I reread now your OP and you mention that there is no log in the server. You can try and look at the network traffic with tcpdump to establish who closes the connection, but from the error the libpq believes it's a clear cut on the server side.

**Comment by robert-kisteleki** [comment]
Yeah, did that already :-)

There's nothing that stands out - as in, no TCP level anomalies such as lost SYNs or such. The suspicion is that the client doesn't even try.

**Comment by dvarrazzo** [comment]
Try to do what? To even initiate a connection?

If so the problem must happen inside the libpq (because the error comes from there). I don't think it's related to psycopg code, but you may want and try to use e.g. a libpq from postgres 9.6 to see if there is some problem introduced in newer postgres releases.
