### ISSUE TITLE
psycopg2/_psycopg.so, 2): no suitable image found 

### ISSUE THREAD

**Issue by felipesodre** [psycopg/psycopg2#1083]
When I try to run psycopg2/ getting this error:

### Error:
from psycopg2._psycopg import (         
I**mportError: dlopen(/Users/felipe.sodre/Projects/Scripts/psycopg2/_psycopg.so, 2): no suitable image found.  Did find:
	/Users/felipe.sodre/Projects/Scripts/psycopg2/_psycopg.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/felipe.sodre/Projects/Scripts/psycopg2/_psycopg.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00_**

Getting the error on this spot in the _init_.py

`from psycopg2._psycopg import (                    
    BINARY, NUMBER, STRING, DATETIME, ROWID,
    Binary, Date, Time, Timestamp,
    DateFromTicks, TimeFromTicks, TimestampFromTicks,
    Error, Warning, DataError, DatabaseError, ProgrammingError, IntegrityError,
    InterfaceError, InternalError, NotSupportedError, OperationalError,
    _connect, apilevel, threadsafety, paramstyle,
    __version__, __libpq_version__,
)`

MACOS Catalina 10.15.4

**Local Module psycopg2**
![image](https://user-images.githubusercontent.com/11660828/79141368-3ec5be80-7d94-11ea-8623-5024a852704a.png)

it seems the file _psycopg.so is misinterpreted,

Does anybody have a clue on how to solve this issue?

**Comment by dvarrazzo** [comment]
Did you copy it from another machine?

**Comment by felipesodre** [comment]
I solve it cleaning the cache on intellij. Thanks.
