### ISSUE TITLE
remove ZPL license from setup.py

### ISSUE THREAD

**Issue by bluefish6** [psycopg/psycopg2#1087]
Hi,

It seems that even though [ZPsycopgDA was removed  in 2013](https://github.com/psycopg/psycopg2/commit/e1ff432f4ce49acf13d90c7807bdd01a4bc44ae8), its license remained not removed in setup.py (https://github.com/psycopg/psycopg2/blob/master/setup.py#L60)

```
License :: OSI Approved :: Zope Public License
```

Note that in 2010 ZPsycopgDA already [changed the license model from GPL+ZPL to LGPL](https://github.com/psycopg/psycopg2/commit/611606d53294ec68ab61aea9ba9149d3c6da4750#diff-229ed981ded0795b148d6e213ce76499L10).

I'm asking about this due to the fact that our automatic license analysis tool (https://github.com/pivotal/LicenseFinder)  discovered ZPL, which I couldn't find in LICENSE file.

Could you please remove ZPL classifier from setup.py?

Best

**Comment by dvarrazzo** [comment]
Will do.
