### ISSUE TITLE
Docs: Does execute_batch return in same order as arguments?

### ISSUE THREAD

**Issue by bfelbo** [psycopg/psycopg2#1089]
It's unclear from the [docs](https://www.psycopg.org/docs/extras.html?highlight=range#psycopg2.extras.execute_batch) if the retrieved data from `execute_batch` is guaranteed to be in the same order as the list passed to the function. Is that the case?

If so, it'd be great to add that to the docs!

**Comment by dvarrazzo** [comment]
I guess it does but it's implementation dependent and not the main reason to use that function, so I'm not sure about committing to it

**Comment by bfelbo** [comment]
Okay, that makes sense. It would be great if you could add a comment like that to the docs?

**Comment by dvarrazzo** [comment]
I don't see an useful comment to add there. Can you suggest one?

**Comment by bfelbo** [comment]
Perhaps this?

> The function currently returns the output in the same order as argslist, but that should not be relied on as it may change in the future.

**Comment by dvarrazzo** [comment]
I don't think this comment serves any useful purpose.
