### ISSUE TITLE
psycopg2.errors.SyntaxError: 

### ISSUE THREAD

**Issue by RaghuGangireddy** [psycopg/psycopg2#1091]
psycopg2.errors.SyntaxError: Statement is too large. Statement Size: 46557879 bytes. Maximum Allowed: 16777216 bytes

Is it possible to change the default size and what is the location?
Please help me to resolve the

**Comment by dvarrazzo** [comment]
I don't know where this error is coming from, I don't see it in Postgres source (on master). What database are you connecting to?

**Comment by dvarrazzo** [comment]
@RaghuGangireddy Please let us know what database you are using.

**Comment by RaghuGangireddy** [comment]
We are using AWS - RedShift

**Comment by dvarrazzo** [comment]
This is a limitation in RedShift that doesn't exist in base postgres. You have to hear from them if it is configurable.

Psycopg2 has the problem of passing the data together with the query: maybe (but I'm not sure) passing them separately would work around the issue. This is a feature we are implementing in psycopg3 and there is no plan to backport it in psycopg2. If you are interested in its development please consider supporting the project (see button on top of the page)

Within psycopg2 all you can do is to pass less data to the query.

**Comment by RaghuGangireddy** [comment]
Thank you very much for your support.
