### ISSUE TITLE
Update docs: Add python3-dev to Build prerequisites

### ISSUE THREAD

**Issue by louisgregg** [psycopg/psycopg2#1092]
psycopg2 requires the python.h C header files to prior to installation. It is unclear from docs (and  elsewhere online) that python3-dev is necessary to fulfill this prerequisite when using Python3. This could be fixed by updating the **install.rst** file in the docs folder as below. 
Currently, the documentation states:
>They are usually installed in a package such as **python-dev**.

This would be clearer as:

>They are usually installed in a package such as **python-dev** or **python3-dev** when using Python3.

**Comment by dvarrazzo** [comment]
Right! Will fix, thank you for the report.
