### ISSUE TITLE
python 3.8 support breaks socket connection and setting session variables

### ISSUE THREAD

**Issue by jwickens** [psycopg/psycopg2#1097]
I upgraded from python 3.6 to 3.8. My psycopg2 version stayed the same (2.8.5)

My usage is 

```py
conn = psycopg2.connect("dbname=mydb user=myuser")
cur = self.conn.cursor()
cur.execute("set search_path to myschema")
cur = self.conn.cursor("mycursor")
cur.execute(query)
```

Where I am trying to the search path set to a schema as described in https://github.com/psycopg/psycopg2/issues/596

Immediately I get the following error:

```
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

If I instead connect to localhost over http I can connect.

Once I connect however the session variable search_path is no longer set as my query cannot find the table.

I'm kind of confused why the same version for different python versions would have different behavior. I guess this has to do with the builds.

Thanks for this great library by the way!

**Comment by dvarrazzo** [comment]
Hey hello,

This difference comes from the default directory for the Unix socket, usually defined at libpq build time (build var `DEFAULT_PGSOCKET_DIR`). `/tmp/` is the default in postgres source code, but a common location is `/var/run/postgresql`, which is the location Debian packages use, as well as the default in the `psycopg2-binary` package.

So, what OS are you using? And how did you install it? If you installed it from source code, how did you install the libpq/pg_config? From a package or from source?

Once the error at connection is solved, I suggest you to deal with the `search_path` in a different way than running a query: the best is probably `ALTER USER myuser SET search_path`. You can also use the `PGOPTIONS` end var or the `options` connection parameter.

**Comment by dvarrazzo** [comment]
An answer would be welcome. However, closing as I think we have covered the issue.

**Comment by jwickens** [comment]
The OS is Ubuntu and package manager is conda. Thanks for the reply!
