### ISSUE TITLE
psycopg2 [Import Error] on Windows - ImportError: dynamic module does not define module export function (PyInit__psycopg)

### ISSUE THREAD

**Issue by thayirsaadham** [psycopg/psycopg2#1098]
I'm getting a weird error when I try to import psycopg2.

Using Python 3.7.7 ; pip version: pip 20.1 from C:\Users\blah\AppData\Local\Programs\Python\Python37\lib\site-packages\pip (python 3.7)

Downloaded psycopg2 using pip

$ python -m pip install psycopg2
```
Collecting psycopg2
  Using cached psycopg2-2.8.5-cp37-cp37m-win_amd64.whl (1.1 MB)
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.5
```

> import psycopg2
> if name =="main": print("Hello World!")

Running the code gives me the below error:

```
$ python test2.py Traceback (most recent call last):   File "test2.py", line 1, in <module>
    import psycopg2   
File "C:\Users\blah\AppData\Local\Programs\Python\Python37\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa ImportError: dynamic module does not define module export function (PyInit__psycopg)
```
Have tried installing pscopg2-binary instead. Still getting the same error.

Any idea?

**Comment by dvarrazzo** [comment]
An antivirus messing up with your binary?

**Comment by dvarrazzo** [comment]
Or a virus

**Comment by thayirsaadham** [comment]
> An antivirus messing up with your binary?

@dvarrazzo Thanks for your response. My computer has a proprietary anti-virus program and I cannot turn it off. Having said that, my colleagues having the same software are having no issues.

Is there anything that you'd recommend for me to try?

**Comment by dvarrazzo** [comment]
I have no idea, it seems an issue related to your machine. You can try and unpack the wheel file on another machine (it's a zip) and verify if the checksum of the dll on your installation is what expected and nothing tampered with it.

Apart from this I'm afraid I don't have any suggestion apart from the classic reinstalling stuff or swapping your machine with your colleague's one under the cover of darkness...

**Comment by rosyllniranjanaxavier** [comment]
Hey @dvarrazzo !! Thanks one million. You were right. It works fine after disabling one of the antivirus software. Thanks very much for your response and time.

**Comment by dvarrazzo** [comment]
Cool! That was admittedly a long shot, but your binary appeared corrupted and nobody else had reported a similar problem so it seemed something on your side. How is that your colleagues didn't have the same problem?

Can you disclose what antivirus is and if some particularly aggressive setting was causing it? Maybe it could solve the trouble to someone else.
