### ISSUE TITLE
psycop2 lobject broken with Postgres 12.x?

### ISSUE THREAD

**Issue by cbows** [psycopg/psycopg2#1104]
I have the following code, that works well with Postgres 11.x:

```python
import psycop2

with psycopg2.connect(dsn="postgresql://...") as conn:
  lobj = conn.lobject()
  lobj.write(b"some data")
  loid = lobj.oid # save oid for later
```
```python
with psycopg2.connect(dsn="postgresql://...") as conn:
  lobj = conn.lobject(loid) # raises Error with Postgres 12.x
```

With Postgres 12.x however, the code raises an error and never actually creates an object. The `lobj.oid` is returned and incremented correctly with each new object, but the `pg_largeobject` table does not actually contain any rows with data and trying to read the object with psycopg2 also returns "There is no object with this ID".

**Comment by dvarrazzo** [comment]
Uhm... as far as I can see, [all test pass on pg12](https://travis-ci.org/github/psycopg/psycopg2/jobs/684153004). I am pretty sure that includes some lobject test.

Can you produce a failing test to commit and push in a branch to show the error?

**Comment by cbows** [comment]
I am sorry, this was a false alarm. I was using `psycopg2-binary`. After trying to install `psycopg2` I noticed that I was missing `libpq-dev` on my system. After installing this, I was able to successfully compile `psycopg2` and could not reproduce the error anymore. Problem solved.
