### ISSUE TITLE
Providing context manager for ConnectionPool?

### ISSUE THREAD

**Issue by venthur** [psycopg/psycopg2#1108]
Would it make sense to provide a context manager for the `ConnectionPool` that behaves similar to the `connection` context managers? E.g.

```python
pool = ThreadedConnectionPool(...)

with pool as conn:
    # conn is a new connection
```

this way we avoid mistakes in case a user forgets to call the `putconn`.

**Comment by dvarrazzo** [comment]
It makes sense, but it will not happen in psycopg2. [psycopg3 pool](https://www.psycopg.org/psycopg3/docs/advanced/pool.html) is designed that way though:

```python
with my_pool.connection() as conn:
    conn.execute("what you want")
```
