### ISSUE TITLE
Why doesn't Pycharm know  methods of objects from psycopg2?

### ISSUE THREAD

**Issue by TechniumUnlimited** [psycopg/psycopg2#1109]
Is there something unique about Psycopg2 library that I don't understand that would make it so that Pycharm IDE doesn't know what methods for instance, the connection or cursor objects I built have available to them? I expected to see things like fetchall() and close() methods appear. I know this is probably somewhat offtopic just would make it a lot easier if I could get the ide to recognize the methods of psycopg objects and wondering if I'm doing something wrong in building my application.. It only seems to display default methods for objects

![image](https://user-images.githubusercontent.com/29348969/82839505-78eea980-9e84-11ea-8727-cf9679956244.png)

**Comment by dvarrazzo** [comment]
These are normal objects, although iimplemented in C.
>>> cnn = psycopg2.connect('')
>>> [a for a in dir(cnn) if not a.startswith('_')]
['DataError', 'DatabaseError', ... 'async_', 'autocommit', 'binary_types', 'cancel', ...]

>>> cur = cnn.cursor()
>>> [a for a in dir(cur) if not a.startswith('_')][:15]
['arraysize', 'binary_types', 'callproc', 'cast', 'close', 'closed', ...]
