### ISSUE TITLE
Is there a way to turn an async connection to sync?

### ISSUE THREAD

**Issue by UpGado** [psycopg/psycopg2#1113]
For an application that I am doing, I need only the connection part to be async but the rest of the usage of the connection to be synchronous. Is there a way to do this? Thanks.

**Comment by dvarrazzo** [comment]
No. You should use two connections.

**Comment by dvarrazzo** [comment]
By the way, not as a design choice, but in psycopg3 it is possible. The low level connection is wrapped by an object which can be transplanted across sync/async connections.

**Comment by UpGado** [comment]
Thanks for the info. I was able to do it in psycopg2 by writing a tiny C extension function that changes the `async` field in the connections struct.

**Comment by dvarrazzo** [comment]
If you want to hack it that way (I'm not against it - of course you are responsible of what you do) then let me observe that:

1) you can probably use ctypes too to fiddle with the C structure: see [this hack](https://gist.github.com/dvarrazzo/b7c8f050bbd39dd2c104) for instance.
2) Something psycopg does to async connections is to put the libpq connection in non-blocking mode: you may want to put it back to blocking mode using [`PQsetnonblocking`](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQSETNONBLOCKING) if you want to use it sync afterwards.
