### ISSUE TITLE
Bug: can't set schema.

### ISSUE THREAD

**Issue by heckad** [psycopg/psycopg2#1118]
```
import psycopg2

conn = psycopg2.connect("""
    host=localhost
    port=5432
    dbname=postgres
    user=postgres
    password=<password>
""", options='-c search_path=my_schema')

c = conn.cursor()
c.execute('SHOW search_path;')
print(c.fetchall())
```
Result
```
[('"$user", public',)]
```
Expect
```
[('my_schema',)]
```
On windows works as expected but on Linux not.

**Comment by dvarrazzo** [comment]
It works for me:
```
piro@makkuro:~/dev/psycopg2/build/lib.3.6$ ipython3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type "copyright", "credits" or "license" for more information.

In [1]: import psycopg2
In [2]: cnn = psycopg2.connect("dbname=piro", options="-c search_path=foo")
In [3]: cur = cnn.cursor()
In [4]: cur.execute("show search_path")
In [5]: cur.fetchone()
Out[5]: ('foo',)
```

and it doesn't make sense that works on windows but not on linux: merging connection params is just some python code.

I guess you are connecting to pgbouncer.

**Comment by heckad** [comment]
Why this is not working with pgbouncer? Is it a bug or expected behaviour?

**Comment by dvarrazzo** [comment]
So I guessed alright? It is surprising but expected. pgbouncer uses its own connections pool, doesn't really connect when you require a connection - that's the entire point of it. So it doesn't forward the connection options. I think it has a special case for `appname` but I'm not sure. You should hear from them, my pgbouncer-foo is not very up-to-date.

**Comment by heckad** [comment]
This was [odyssey](https://github.com/yandex/odyssey)

**Comment by dvarrazzo** [comment]
Same. You are asking a connection to something that has a connection already open and it's cheerfully ignoring the details you have requested.

You may want to specify your `search_path` with a `SET` statement, but even that way you should pay attention at not polluting the pool in case the connections returned are not reset. If the pool works at transaction level the best is to issue a `set local search_path` to keep the setting within the transaction. Please refer to the odyssey docs for the details.
