### ISSUE TITLE
Singleton selects

### ISSUE THREAD

**Issue by pgodfrin** [psycopg/psycopg2#1119]
As of 2.8.6, the only way to retrieve data is with a cursor object. There are occasions where the code knows there will be only one row returned, such as a count(*), or insert.

I'd like to request a feature request for singleton selects, with no cursor requirement.

Perl DBI:DBD has the "do" statement
`$rv = $dbh->do($statement);`

**Comment by dvarrazzo** [comment]
you can do `(thing,) = cursor.fetchone()`.

**Comment by pgodfrin** [comment]
OK, but that still requires creating a cursor and executing it.

**Comment by dvarrazzo** [comment]
Correct. The case in which you have a return set of exactly one value is not special enough to require a special interface.

**Comment by pgodfrin** [comment]
Right gotcha. I'm accustomed to a cursor being an entity used for manipulating multiple rows based on a select (for update). Seems to me in this context a cursor is any sql statement. This is more obvious when doing an insert, update or delete. Those actions don't return data per sae, thus no cursor in the classic sense (ANSI?) should be required. I'm new to psycopg2, so I'm just learning the idiosyncrasies. 

For example, why is the commit function at the connection level. If a cursor is any sql statement, shouldn't the commit also be at that level?

**Comment by asqui** [comment]
This is not special to psycopg2 but is actually a general pattern for all database adapters in Python. Check this out: https://www.python.org/dev/peps/pep-0249/

**Comment by pgodfrin** [comment]
I stand corrected on the commit scope. Apologies.
