### ISSUE TITLE
Error convert '0.0000000'::numeric

### ISSUE THREAD

**Issue by xmings** [psycopg/psycopg2#1122]
Maybe it's wrong to convert the '0.0000000'::numeric in database to Decimal('0E-7')

**Comment by dvarrazzo** [comment]
It's python behaviour, not psycopg.

```
$ python -c "from decimal import Decimal; print(Decimal('0.0000000'))"
0E-7
```

You may want to ask Python devs about it.

**Comment by xmings** [comment]
why not use float type instead of Decimal
