### ISSUE TITLE
[WINDOWS/OTHERS ?] psycopg2 not working in embedded zip

### ISSUE THREAD

**Issue by eblaudy** [psycopg/psycopg2#1124]
Hi,
For the project I'm working (WAPT) we want to use psycopg2 in a site-packages zip (because we deploy agents and the deployment can be faster with only one zip than multiple copy of files). Python can't loads DLLs/PYDs directly from the zip so I moved them in a DLLs directory which is in the path (he is declared in a python3X._pth). The problem is that you use relative imports for the PYDs : 
_psycopg.cpXX-X.pyd

If I change them to absolute imports it works (for ex : "from psycopg2._psycopg import ..." --> "from _psycopg import ..."). I think there is the same problem in others platforms :)

Would it be possible to integrate this changes in the next release? I you want I can make a PR

Lines concerned for Windows :
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/__init__.py#L51
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/__init__.py#L77
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/extensions.py#L38
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/extensions.py#L46
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/extensions.py#L53
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/extensions.py#L58
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/_json.py#L33
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/_json.py#L34
https://github.com/psycopg/psycopg2/blob/779a1370ceeac130de07edc0510f2c55846be1bd/lib/_range.py#L30

**Comment by dvarrazzo** [comment]
No, absolute imports are wrong in a package and they lead to serious problems, such as breaking `isinstance()`, so we wouldn't accept the change you propose.

**Comment by dvarrazzo** [comment]
If you have other less invasive workarounds we can consider them. Please let us know.

**Comment by dvarrazzo** [comment]
Closing as no follow-up.
