### ISSUE TITLE
Incorrect Results

### ISSUE THREAD

**Issue by felixphotobox** [psycopg/psycopg2#1132]
Hi,

I am running psycopg2 to retrieve data from a Postgres SQL database. However, the queries being run in Python are returning inconsistent results. 

An example would be query that in my native SQL connection (not using psycopg2) is returning 2385 rows. When run in Python using psycopg2, it has returned anything between 2200-2300 rows, varying every time it is run. 

Is this a known issue? Are there ways to avoid this? I have tried using both .execute and read_sql_query.

Thanks

Felix

**Comment by dvarrazzo** [comment]
It's a bug on your site. You can rest assured we return all the rows of your query.

You are either connecting to the wrong database or forgetting to commit something.
