### ISSUE TITLE
STRING_DATA_RIGHT_TRUNCATION defined twice

### ISSUE THREAD

**Issue by barredterra** [psycopg/psycopg2#1133]
The constant `STRING_DATA_RIGHT_TRUNCATION` is defined twice:

https://github.com/psycopg/psycopg2/blob/cecff195fc17a83d593dd62c239aa188883a844e/lib/errorcodes.py#L109
https://github.com/psycopg/psycopg2/blob/cecff195fc17a83d593dd62c239aa188883a844e/lib/errorcodes.py#L164

So the first value is never gets to see the light.

**Comment by dvarrazzo** [comment]
You are absolutely right. However the first is a warning, so it's never raised.

Have you found other collisions?
