### ISSUE TITLE
Usage documentation inconsistency regarding connection.close()

### ISSUE THREAD

**Issue by UkuLoskit** [psycopg/psycopg2#1135]
According to the Usage documentation, connections implicitly issue a rollback when they are garbage collected or `close()` is called.

These documentation lines date back 8-10 years and seem to be outdated.
https://github.com/psycopg/psycopg2/blame/master/doc/src/usage.rst#L752-L756

However, the docs for `connection.close` itself contradict the usage documentation in
https://www.psycopg.org/docs/connection.html?highlight=close#connection.close

As well as the actual implementation: https://github.com/psycopg/psycopg2/blob/master/psycopg/connection_int.c#L1223-L1231

**Comment by asqui** [comment]
I think you may be misunderstanding the meaning of implicit and explicit here.
- Explicit rollback means that Psycopg explicitly sends a ROLLBACK statement to the server.
- Implicit rollback means that Psycopg closes the connection while a transaction is still in progress, and the Postgres server responds by implicitly rolling back the changes in the open transaction.

Does that make sense?

**Comment by UkuLoskit** [comment]
Thanks for your feedback, @asqui! I understand the difference, but to me it seems that the old usage documentation is suggesting a bad practice of closing a connection without rolling back a transaction (emphasis mine):


_Changed in version 2.2: previously an explicit ROLLBACK was issued by Psycopg on close(). The command could have been sent to the backend at an inappropriate time, so Psycopg currently relies on the backend to implicitly discard uncommitted changes. **Some middleware are known to behave incorrectly though when the connection is closed during a transaction (when status is STATUS_IN_TRANSACTION), e.g. PgBouncer reports an unclean server and discards the connection. To avoid this problem you can ensure to terminate the transaction with a commit()/rollback() before closing.**_



Why not just always suggest either `commit()`-ing or `rollback()`-ing any changes on the client side. This is how the psycopg2 context manager works. It always either commits the transaction or rolls it back (in case any exception occurs). 
Calling it an implicit rollback is confusing as well, as it could also mean "implictly performed by psycopg2"

**Comment by dvarrazzo** [comment]
I think you have given the wrong meaning to:

> Closing the connection using the `~connection.close()` method or destroying the connection object (using `!del` or letting it fall out of scope) will result in an implicit rollback.

Psycopg will not run a rollback: it will just close the connection and the server will roll back a transaction eventually running in that session (which was a change in behaviour from precedent behaviour of trying to run cleanup query in a connection being GC'd, not a solid idea).

So the only inconsistency is between your wrong interpretation of that sentence and the rest of the documentation: 

> Why not just always suggest either commit()-ing or rollback()-ing any changes on the client side

That's exactly what we do.

I'll fix the doc to specify further that if you close the connection halfway during a transaction it is the server that rolls back the transaction, not the client.

**Comment by UkuLoskit** [comment]
@dvarrazzo  thanks for the quick reply.  

> That's exactly what we do.

Yes, but that is only becomes understandable if you read both the documentation of `connection.close()` and the usage  document with special attention to "new after 2.2"

My whole point is that relying solely on the usage document can lead one to believe that it's a solid approach to close a connection without a client-side rollback. 

Again thanks for your time in replying to me and maintaining this project.

**Comment by dvarrazzo** [comment]
@UkuLoskit Please also bear in mind that documentation is:

- an evolving document of a project old enough to get its driving license in most territories. Things that feel not important and obvious now might have been relevant in the past. The change in behaviour in 2.2 was an important change, although very few projects now probably rely on the old behaviour;
- written by "insiders" of the project, for whom things that are obvious might not be so obvious for the average end user;
- written by non-native speakers.

So your input is welcome: as we have clarified which one was your pain point (who is responsible to "rollback", what we were meaning for "implicit") feel free to suggest a change to the docs if you think it would help readability for newcomers.

Thank you very much!
