### ISSUE TITLE
Strange behaviour of fetchone when returning a tuple containing a single None

### ISSUE THREAD

**Issue by marceloslacerda** [psycopg/psycopg2#1137]
If I try to use a `fechone` on a query that would return as single `null` result, psycopg2 returns a `None` instead of a `(None,)`. If I use `fetchall` instead I get `[(None,)]`.

Assuming that's the correct behaviour, shouldn't there be a mention in the documentation?

Example:

Suppose that I have the following table

```
CREATE TABLE a (x INTEGER, y INTEGER);

INSERT INTO a VALUES (1, null);
```

Running the following code reproduces the odd behaviour.

```
cur.execute('SELECT y FROM a WHERE x = 1')
row1 = cur.fetchall()  # [(None,)]
cur.execute('SELECT y FROM a WHERE x = 1')
row2 = cur.fetchone()  # None
assert(row1[0] == row2)
```

**Comment by dvarrazzo** [comment]
That's not what I see.

```
In [1]: import psycopg2
In [2]: cnn = psycopg2.connect("")
In [4]: cur = cnn.cursor()
In [5]: cur.execute('SELECT y FROM a WHERE x = 1')
In [6]: cur.fetchone()
Out[6]: (None,)
```

you are doing something with your query and it's returning no row, that's the only way `fetchone()` returns None.
