### ISSUE TITLE
Creating a connection results in "zombie" ccapiserver.exe processes on Windows

### ISSUE THREAD

**Issue by peetw** [psycopg/psycopg2#1138]
Not sure if this is an issue in`psycopg2`, `libpq` or `krb5`, but if I run the following code (filling in the connection details) a `ccapiserver.exe` process is spawned that persists even after the Python session has ended.

```
import psycopg2
with psycopg2.connect(host='', dbname='', user='', password='') as conn:
    pass
```

If I re-run the code manually, no additional `ccapiserver.exe` process is spawned. However, if the code is run via a scheduled task, it _does_ spawn additional `ccapiserver.exe` processes. This led to a huge number of these "zombie" processes on one of our production servers (resulting in scheduled task failures and system slow-down).

The `ccapiserver.exe` process appears to be the "Kerberos Credentials Cache API Server", although we are not using Kerberos authentication.

Is this a bug, or is there a way to avoid spawning the `ccapiserver.exe` process?

**System Information**
Windows Server 2019
Miniconda3 x64

<details>
  <summary>Python packages</summary>

```
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3=1.14.22=pyh9f0ad1d_0
  - botocore=1.17.22=pyh9f0ad1d_0
  - brotlipy=0.7.0=py36h779f372_1000
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.14.0=py36ha419a9e_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cmreshandler=1.0.0=py36h9f0ad1d_1
  - cryptography=2.9.2=py36hef61171_0
  - docutils=0.15.2=py36_0
  - elasticsearch=7.8.1=pyh9f0ad1d_0
  - idna=2.10=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - krb5=1.17.1=hc04afaa_1
  - libpq=12.3=hd9aa61d_0
  - openssl=1.1.1g=he774522_1
  - pip=20.1.1=py_1
  - psycopg2=2.8.5=py36hef61171_1
  - pycparser=2.20=pyh9f0ad1d_2
  - pyodbc=4.0.30=py36h6538335_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=he025d50_1009_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=pyh9f0ad1d_0
  - requests=2.24.0=pyh9f0ad1d_0
  - s3transfer=0.3.3=py36h9f0ad1d_1
  - setuptools=49.2.0=py36h9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - tk=8.6.10=hfa6e2cd_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py36_0
  - wincertstore=0.2=py36_1003
  - zlib=1.2.11=h2fa13f4_1006
```
</details>

**Comment by dvarrazzo** [comment]
Thank you for posting this. I'd say the problem comes from the Kerberos lib but of course it is relevant to us. I'd be happy to fix it but I have no clue where to start.

We also don't interact directly with the kerberos lib, but everything happens via the libpq. Maybe the libpq can call the kerberos lib in a way to manage the creation of the process. I think the best way to proceed is to escalate this issue to the pgsql-bugs tracker.

**Comment by peetw** [comment]
@dvarrazzo no worries. I've created a bug report over on the pgsql-bugs mailing list here: https://www.postgresql.org/message-id/16576-0f02e224a1c2007b%40postgresql.org

**Comment by dvarrazzo** [comment]
I've seen no answer from the PG mailing list. Maybe the right people to ask are MIT Kerberos maintainers?

**Comment by dvarrazzo** [comment]
Closing as not a problem which can be fixed in psycopg2
