### ISSUE TITLE
Status message and query missing from cursor attributes in COPY-related methods

### ISSUE THREAD

**Issue by edgarrmondragon** [psycopg/psycopg2#1141]
I'm trying to get the status message from a cursor after executing a `COPY` command but it seems like the `cursor.statusmesage` and `cursor.query` are missing. I can still get relevant information through `rowcount` but I was wondering why it's the case that the other attributes are missing.

Thanks.

```python
import io
import psycopg2

URI = ...

def print_cursor_info(cursor):
    print(f"Row count: {cursor.rowcount}\nStatus Message: {cursor.statusmessage}\nQuery: {cursor.query}")

with psycopg2.connect(URI) as conn, conn.cursor() as curs:
    curs.execute("drop table if exists testing")
    curs.execute("create table testing (a text, b text, c int)")
    print_cursor_info(curs)

# Row count: -1
# Status Message: CREATE TABLE
# Query: b'create table testing (a text, b text, c int)'

fo1 = io.StringIO("text\tmore text\t1\ntext\teven more text\t2\n")

with psycopg2.connect(URI) as conn, conn.cursor() as curs:
    curs.copy_from(fo1, "testing", columns=("a", "b", "c"))
    print_cursor_info(curs)

# Row count: 2
# Status Message: 
# Query: None

fo2 = io.StringIO("a,b,c\ncsv,text,3\n")

with psycopg2.connect(URI) as conn, conn.cursor() as curs:
    curs.copy_expert("copy testing from stdin with csv header", fo2)
    print_cursor_info(curs)

# Row count: 1
# Status Message: 
# Query: None
```

**Comment by dvarrazzo** [comment]
Thank you for reporting this. I guess consistency would be good.

**Comment by dvarrazzo** [comment]
I looked into setting statusmessage = COPY and [it should have happened](https://github.com/psycopg/psycopg2/blob/dd1724c44789df3b1ce84e7ae5b6cfe5675c689b/psycopg/pqpath.c#L1739). So it is  [PQcmdStatus](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQCMDSTATUS) that doesn't return a value on copy operation.

Fixing the value of `cursor.query`.
