### ISSUE TITLE
Execute hangs then returns Operational Error 

### ISSUE THREAD

**Issue by ks233ever** [psycopg/psycopg2#1142]
Have been using psycopg2 to unload redshift tables to s3 for the past month. Code is simple like so;

`hostname = 'XXXXX'
username = 'XXXX'
password = 'XXXXX'
database = 'XXX'

con = psycopg2.connect(host=hostname, user=username, password=password, dbname=database)

sql="""UNLOAD ('select * from table') TO 's3://bucket/prefix' \
         credentials 'aws_access_key_id=XXX;aws_secret_access_key=XXX'
         FORMAT PARQUET;"""
       
cur = con.cursor()
cur.execute(sql)`

Historically this table takes 15 mins to unload and there have never been any issues. Today it unloads the file to S3 no problem within the expected 15 mins, but it doesn't get past cur.execute(sql). Continues to run for hours before returning the error:

OperationalError: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request.

I've googled around for a while and played with a few connection params to no avail. Is there a quick fix for this?

version 2.8.5

**Comment by dvarrazzo** [comment]
That's most definitely not a problem with psycopg. You have to check the server.
