### ISSUE TITLE
connection context manager returns wrong server version

### ISSUE THREAD

**Issue by fidelitas** [psycopg/psycopg2#1146]
Hi folks,

I'm encountering an issue I cannot comprehend.
Asking my database server about its version, I get the following:
```bash
$ psql my_db
...
my_db=# select version();
                                                      version
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.4 on x86_64-apple-darwin19.5.0, compiled by Apple clang version 11.0.3 (clang-1103.0.32.62), 64-bit
(1 row)
```
Now connecting to the db with the connection context manager should give me `120400` IMHO.
However, when I try:
```python
>>> import psycopg2
>>> DATABASE_URL = "postgres://localhost/my_db"
>>> with psycopg2.connect(DATABASE_URL) as conn:
        conn.server_version
        conn.info.server_version
120004
120004
```
I get `120004`. Perhaps I'm misunderstanding the `server_version` method or are making a mistake here. Any ideas?

Thank you!

**Comment by dvarrazzo** [comment]
The value returned by the function is correct. Postgres in v10 moved from a major.minor.bugfix versioning to a major.bugfix one: they dropped the "minor" version (the distinction between major and minor version was a matter of opinion).

See [PQserverVersion docs](https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSERVERVERSION) for all the details.

**Comment by fidelitas** [comment]
@dvarrazzo thank you for the explanation!
