### ISSUE TITLE
ELF load command address/offset not properly aligne

### ISSUE THREAD

**Issue by bobfang1992** [psycopg/psycopg2#1149]
Hi I am having this error when trying to use the psycopg2 to connect to our postgres database with sqlalchemy:
```
Python 3.6.3 (default, Mar 20 2018, 13:50:41) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from psycopg2.extensions import AsIs, register_adapter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/some/path/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq-0929ced5.so.5.11: ELF load command address/offset not properly aligned
>>> 
```

This is my `pip list`:

```
pip list | grep psy
psycopg2                 2.7.3         
psycopg2-binary          2.8.6         
```

I understand this might not be easy for you to produce, but could have you ever seen this before? What could lead this issue? Thanks!

**Comment by dvarrazzo** [comment]
Hi,

Never seen before.

Please uninstall both and install only the non-wheels package: the error appears in the wheel libpq.

**Comment by bobfang1992** [comment]
Hi it seems I cannot use the non-wheels version as on my host machine I dont have pg_config installed. My code runs on a host that does not have pg installation and it will connect to a remote pg instance.

**Comment by dvarrazzo** [comment]
I don't know how your machine is setup. Please try to get help from your system administrator.

**Comment by mttsndrs** [comment]
I had a similar problem when I was packaging up the psycopg2-binary artifacts in an RPM using rpmbuild. It was stripping the binaries and modifying the ELF header, causing the error: `ImportError: libpq-0929ced5.so.5.11: ELF load command address/offset not properly aligned` when the RPM was installed.

In my case I fixed it by adding `%define __os_install_post %{nil}` to the top of the RPM spec, which disabled the post-processing steps including the strip commands.
