### ISSUE TITLE
Psycopg2 Yielding Inconsistent Results With Nested Queries

### ISSUE THREAD

**Issue by NazarTrilisky** [psycopg/psycopg2#1154]
The query below (names changed for privacy) returned inconsistent results when executed via Psycopg2 (both 2.8.6 and 2.8.4) and via Postgres command line:

SELECT schema_name.table_name.column_1, schema_name.table_name.column_2, string_agg(schema_name.column_4.column_4_value, ', '), schema_name.table_name.column_3
FROM schema_name.column_2 LEFT JOIN schema_name.column_4 ON schema_name.table_name.id = schema_name.column_4.column_2_id
WHERE schema_name.table_name.solution_id IN (SELECT ID FROM schema_name.solution WHERE columnA = 'SomeValue' AND columnB = 'OtherValue') 
GROUP BY schema_name.table_name.column_1, schema_name.table_name.column_2, schema_name.table_name.column_3;

The difference between command line and Psycopg2 query execution was only for rows where the string_agg column was empty.

**Comment by NazarTrilisky** [comment]
Also, the workaround was to remove the nested query (SELECT ID FROM...) and to put a constant there.

**Comment by NazarTrilisky** [comment]
Also, "The difference between command line and Psycopg2 query execution" was the Psycopg2 was Not returning columns Sometimes where the string_agg column was empty.  Other times result was correct: intermittent bug.

**Comment by dvarrazzo** [comment]
How are you composing the query? I guess you are passing stuff with your own quotes, and the inner query is finding no match. Look at `cursor.query` to see the query effectively passed to the database.

This is most definitely a problem in your program, not in psycopg.

**Comment by NazarTrilisky** [comment]
Appreciate your quick reply.
I am composing the query as a string.
The inner query is finding matches.

I am sure the query is correct because it is returning the correct data most of the time, except right after inserting a new entry into the Postres DB, at which point the query result is intermittently missing some rows.

I ran the identical query directly in Postgres command line and through Psycopg2, with this bug's (1154's) issue only reproducing with the Psycopg2 query.

**Comment by dvarrazzo** [comment]
You may be doing something incorrect with transactions. Maybe you have different processes and you haven't committed after inserts. If the response is answered by the same connection that run the query you find the record, if it's answered from another one it won't find it.

psycopg doesn't parse sub-queries, or any sql construct at all.
