### ISSUE TITLE
callproc documentation

### ISSUE THREAD

**Issue by aklaver** [psycopg/psycopg2#1155]
https://www.psycopg.org/docs/cursor.html?highlight=callproc#cursor.callproc
"Call a stored database procedure with the given name."

I realize the above was written before Postgres got actual stored procedures. Now that it has them the callproc()  documentation probably needs an update.  As the following illustrates:

cur.callproc("up_test", [4])                                                                                                                                              
---------------------------------------------------------------------------
WrongObjectType                           Traceback (most recent call last)
<ipython-input-29-798b9a0d80d9> in <module>
----> 1 cur.callproc("up_test", [4])

WrongObjectType: up_test(integer) is a procedure
LINE 1: SELECT * FROM up_test(4)
                      ^
HINT:  To call a procedure, use CALL.

**Comment by ichbinjakes** [comment]
I think this is a bug in the `curs_callproc()` code:

https://github.com/psycopg/psycopg2/blob/dc007e790a531cd2466f5c0bc1a6c8ee51097b5a/psycopg/cursor_type.c#L1082

Should be something like `sprintf(sql, "CALL %s(", procname); `

**Comment by aklaver** [comment]
Not really. At the time this code written Postgres stored functions where commonly called procedures even though they where not actually stored procedures. See CREATE TRIGGER for example of this. As of Postgres 11 there are stored procedures. At this point a change in the documentation to make it clear what callproc() is doing would be the first step. Then changes to deal with CALL some_procedure.

**Comment by PritamDutt** [comment]
So I think we should probably look at using `cursor.execute` as workaround till a fix is there

**Comment by dvarrazzo** [comment]
@PritamDutt I doubt there will be any fix: we cannot tell whether to use `CALL` or not without inspecting the catalog, and it's totally not worth the extra roundtrip to the server.

I assume `callproc` was designed in the DBAPI with database offering a fast path for it. Postgres is not one of them, and psycopg2 pretty much does only an `execute()` behind the scene.

So by all means use `execute`: it's a much more flexible way of doing things, especially deciding what you want to return, and you won't lose any performance compared to `callproc`.

This ticket stays open only to fix the documentation, not to fix `callproc`.
