### ISSUE TITLE
Does cursor.itersize return one row at a time?

### ISSUE THREAD

**Issue by JakobHenning** [psycopg/psycopg2#1157]
As far as I understand, `row` (see below) should consist of `chunk_size` elements, but `len(row)` is 1 and not 100000. Since I have 500000 rows in the DB I would assume the loop to run 5 times, but `c` runs from 0 to number of rows and not from 0 to 4 as assumed. 

```python
con= psycopg2.connect(
    dbname=database,
    user=user,
    password=pwd,
    host=host,
    port=port
)
chunk_size = 100000 #500000 rows in the DB
cursor =  con.cursor(name='custom_cursor') 
cursor.itersize = chunk_size # chunk size
cursor.execute(query)
c=0
for row in cursor:
    print(c)
    print(f"Len_row: {len(row)}")
    c+=1
```
I'm running psycopg2==2.8.6

**Comment by dvarrazzo** [comment]
No, your understanding is wrong: the driver will ask for a page of 100K rows to the server but will iterate one row at time on the client.

If you want to fetch and have immediately available chunks of a size you decide, use `fetchmany(100000)`.
