### ISSUE TITLE
Column names with '$' leading to errors?

### ISSUE THREAD

**Issue by barankarakus** [psycopg/psycopg2#1158]
I've spotted a strange bug.

Firstly, I'm working with `sqlalchemy` version 1.3.19 and `psycopg2` version 2.8.5 (latest versions of both packages at time of writing).

I have a newly created PostgreSQL table, call it "A", with a single column named "Dividend (HK$)", of type text.

I then run the following code:

````
import pandas as pd
import sqlalchemy as sq

conn_str = # connection string specifying database connection parameters
engine = sq.create_engine(conn_str)
df = pd.DataFrame([['1']], columns=['Dividend (HK$)'])
df.to_sql('A', engine, if_exists='append', index=False)
````

This leads to the exception: `KeyError: 'Dividend (HK$'`.

I've no idea where the closing bracket disappeared...

I've traced the error to line 873 in sqlalchemy/dialects/postgresql/psycopg2.py: `cursor.executemany(statement, parameters)`. Here, the `statement` argument is the string

> INSERT INTO "A" ("Dividend (HK$)") VALUES (%(Dividend (HK$))s)

and the `parameters` argument is a single-element tuple containing the dictionary 

`{'Dividend (HK$)': '1'}`

The `cursor` object is from psycopg2/extensions.py. Quick inspection of this file reveals `cursor` is imported from the psycopg2._psycopg module - written in C. It is at this point that I'm lost: I don't know the Python C API well enough to delve into this module myself and figure out why the `cursor.executemany` function is omitting the closing bracket.

**Comment by dvarrazzo** [comment]
Placeholders cannot contain the `)` character.

**Comment by dvarrazzo** [comment]
Also see #167.

**Comment by barankarakus** [comment]
> Placeholders cannot contain the `)` character.

Ah, I see. Thanks!
