### ISSUE TITLE
 year -1 is out of range

### ISSUE THREAD

**Issue by ynorouzz** [psycopg/psycopg2#1161]
I have a function that recieve a date in string format and run a query in Redshift.

```
def myfun(cur, extraction_date)
    created_at = pd.to_datetime(extraction_date).date()
    cur.execute(rs_query('table-name', conditions + """ AND date(created_at) = (%s)"""), (created_at,))
                                         
    df = pd.DataFrame(cur.fetchall(), columns=config_redshift.table_cols)
```

Recently, whenever I run the script, I got the following error

```
Traceback (most recent call last):
  File "/Users/yaser/opt/anaconda3/envs/Observation/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-ce783bd15f8f>", line 5, in <module>
    booking_core = pd.DataFrame(cur.fetchall(), columns=config_redshift.booking_dpart['bookings'])
ValueError: year -1 is out of range
```

when I replace the date in query with some date in string format, it works for most of the dates. 

```
    cur.execute(rs_query('table-name', conditions + """ AND date(created_at) = '2020-07-10' """))
```

**Comment by dvarrazzo** [comment]
What do you see if you run the same query in psql?

**Comment by ynorouzz** [comment]
The same query runs without a problem.

**Comment by dvarrazzo** [comment]
Split the statement in two:
```
records = cur.fetchall()
booking_core = pd.DataFrame(records, columns=config_redshift.booking_dpart['bookings'])
```
on what line does the error happen?

**Comment by ynorouzz** [comment]
Then the error happens in  `cur.fetchall()`

**Comment by dvarrazzo** [comment]
Please identify the record that makes the error happen and let us know what the equivalent result seen in psql look like

**Comment by ynorouzz** [comment]
In Python, when I run `cur.fetchall()` for second time, and I got the records without any errors, so the solution looks like this
```
    try:
        records = cur.fetchall()
    except:
        try:
            records = cur.fetchall()
        except:
            print('Error in fetching data from Redshift.')

```

**Comment by dvarrazzo** [comment]
That's hardly a solution: I doubt you'll find all the records there. Can you do what requested? Can you identify the malformed date? Otherwise I'll just close this ticket as we don't even support Redshift.

**Comment by ynorouzz** [comment]
Good question. For malformed date (2020-07-10), the number of records in Python (103, 819) is less than number of records in Redshift (148,146).

**Comment by dvarrazzo** [comment]
And what is the malformed date?

**Comment by ynorouzz** [comment]
I found multiple malformed dates such as 2020-07-10, 2020-07-28, etc.

**Comment by dvarrazzo** [comment]
Sorry, why is `2020-07-10` malformed?

**Comment by ynorouzz** [comment]
I compared the records that are missed with the records that are fetched, and I didn't find a meaningful difference. The date field that I do the filtering has the values as bellow:

```
2020-07-28 00:00:52
2020-07-28 23:50:37
```

**Comment by slidesecurity** [comment]
I had this same issue and it was in fact my database record being -1

**Comment by FlavioCorreia** [comment]
> In Python, when I run `cur.fetchall()` for second time, I got the records without any errors. So the solution looks like this
> 
> ```
>     try:
>         records = cur.fetchall()
>     except:
>         try:
>             records = cur.fetchall()
>         except:
>             print('Error in fetching data from Redshift.')
> ```

Dude this worked for me thanks

**Comment by anibal2j** [comment]
I have a table that has a date with this value 29358-08-25. The column is called date_of_birth and it's of type date. psql doesn't complain when I do a select, but psycopg2 is throwing "ValueError: year 29358 is out of range".

**Comment by anibal2j** [comment]
What's even more weird, is that psycopg2 is throwing inconsistently. I just re-run the script and sometimes it throws on certain rows, and others it throws on other rows - all the time throws with errors - but it seems as if it's either throwing on the same row but the select is coming back in different order, or the library is indeed throwing at times but not others (?). I'm kind of stuck. I have thousand of corrupted records. I don't want to do much with them really, but I'd like the script to continue running without throwing. As a matter of fact, even though it's crazy to think about it, but a year of 86820-09-11 (86820) is a correct year. Not sure if we'll have psycopg2 running by the year 86820 but heck, it's not invalid :-)

**Comment by anibal2j** [comment]
What's the workaround then? Is there a quick patch I can apply?

**Comment by anibal2j** [comment]
Just found a workaround:

`update order_tbl set date_of_birth = null where entering_organization = 'CGV' and date_of_birth > '3000-01-01';
`

I basically set all the "invalid" DOB to null. They were garbage anyway so from my data integrity point of view it's OK in my case, and at least my script is completing as it should now. A better workaround would be appreciated.
