### ISSUE TITLE
Lack of cp39 wheels on PyPI

### ISSUE THREAD

**Issue by vermoouth** [psycopg/psycopg2#1162]
Due to python 3.9 release, it'll be great to add cp39 wheels to [PyPI's "Download files" section](https://pypi.org/project/psycopg2/#files).

**Comment by dvarrazzo** [comment]
I've tried

**Comment by dvarrazzo** [comment]
Sorry, I'm wrong: packages have been there all the time: https://pypi.org/project/psycopg2-binary/#files
The only missing ones are on Windows, which will be released when Appveyor will add Python 3.9 support: #1166
