### ISSUE TITLE
Allow CONN_NOTICES_LIMIT to be configured

### ISSUE THREAD

**Issue by randvoorhies** [psycopg/psycopg2#1163]
Currently `CONN_NOTICES_LIMIT` is `#defined` to 50 [here](https://github.com/psycopg/psycopg2/blob/master/psycopg/connection.h#L70) which means there is no way to change this limit.  I use the `RAISE INFO` functionality heavily in my projects and so it would be great if I could control that max size myself.

This seems straightforward to do, so I'm happy to do the work and open a PR if you all are on board.

**Comment by dvarrazzo** [comment]
No, thank you: `CONN_NOTICES_LIMIT` is only a stop-gap measure for an error in the design made 15 years ago. The list is a poor object to implement a queue.

[`connection.notices` is writable](https://www.psycopg.org/docs/connection.html#connection.notices): you can replace it with any object of yours: everything exposing an `append()` method is good. From the docs:

> Changed in version 2.7: The notices attribute is writable: the user may replace it with any Python object exposing an append() method. If appending raises an exception the notice is silently dropped.
>
> To avoid a leak in case excessive notices are generated, only the last 50 messages are kept. This check is only in place if the notices attribute is a list: if any other object is used it will be up to the user to guard from leakage.

An obvious candidate is `collections.deque`, but you can use your own object that uses a callback for `append()` and you can consume notifications any way you like.

The way the notices limit is used internally is:

```c
    /* Remove the oldest item if the queue is getting too long. */
    if (PyList_Check(self->notice_list)) {
        Py_ssize_t nnotices;
        nnotices = PyList_GET_SIZE(self->notice_list);
        if (nnotices > CONN_NOTICES_LIMIT) {
            if (-1 == PySequence_DelSlice(self->notice_list,
                    0, nnotices - CONN_NOTICES_LIMIT)) {
                PyErr_Clear();
            }
        }
    }
```

So, if your object doesn't inherit from `list` the limit will not be imposed.
