### ISSUE TITLE
obligations under the license

### ISSUE THREAD

**Issue by elvisionary** [psycopg/psycopg2#1164]
Hello!

I would like to discuss the use of packages using the LGPL license, in particular: https://pypi.org/project/psycopg2/.
 
We want to use packages with this type of license exclusively in the format where they are used without modifying their code and use them as a package.

is it permissible to use them without disclosing the source code of our software?

**Comment by fogzot** [comment]
On 10/12/20 2:53 PM, elvisionary wrote:
> Hello!
> 
> I would like to discuss the use of packages using the LGPL license, in 
> particular: https://pypi.org/project/psycopg2/.
> 
> We want to use packages with this type of license exclusively in the 
> format where they are used without modifying their code and use them as 
> a package.
> 
> is it permissible to use them without disclosing the source code of our 
> software?

Yes, as long as it is possible to substitute the version of psycopg 
bundled with your software with a new version. That's one of the basic 
requirements of the LGPL.

federico

-- 
Federico Di Gregorio                         federico.digregorio@dndg.it
DNDG srl                                                  http://dndg.it
  The only thing I see is if you are pumping so much data into the
   database all the time when do you expect to look at it?
                                                         -- Charlie Clark

**Comment by fogzot** [comment]
I am not a lawyer. I can tell that one of the prerequisites is what I have written above but if you are not sure about anything else, I suggest you ask a proper lawyer.
