### ISSUE TITLE
ImportError: DLL load failed while importing _psycopg: The specified module could not be found in python 3.9

### ISSUE THREAD

**Issue by lathish2232** [psycopg/psycopg2#1168]
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\CSC\AppData\Local\Programs\Python\Python39\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
>>>

_Originally posted by @lathish2232 in https://github.com/psycopg/psycopg2/issue_comments/709306840_

**Comment by dvarrazzo** [comment]
#1160

**Comment by joseluratm** [comment]
I couldn't get it to work in any of the ways I saw on the internet. In the end, I added to the file __init__.py just in front of the line
```
from psycopg2._psycopg import ( # noqa
```
the following import, leaving this way the file
```
import psycopg2
from psycopg2._psycopg import ( # noqa ...
```
And magically it worked for me. I comment it here, in case someone could use the solution.

**Comment by abhishek-droot** [comment]
Hi ,
Can you explain further , I try it but not works

**Comment by tushar-3549** [comment]
how to solve it? I have same problem. Can't fix. anyone help me to fix it step by step.
