### ISSUE TITLE
Drop table from specific schema not working

### ISSUE THREAD

**Issue by iamtekson** [psycopg/psycopg2#1173]
I tried to drop the table from the schema 'try'. I tried the following code to do this.

```python
cursor = self.conn.cursor()

sql = '''DROP TABLE IF EXISTS "{0}"."{1}" CASCADE;'''.format('try', 'table1')

print(sql)

cursor.execute(query)

self.conn.commit()

cursor.close()
```
Following error is generated when I tried to run this code,
```
the current transaction is aborted, commands ignored until end of transaction block
```
The error is generated from `cursor.execute(query)` line. Please suggest to me how to drop the table inside the schema?

But I tried to run the same query from pgAdmin, there it was working.

**Comment by dvarrazzo** [comment]
The query is alright, but the connection is in a transaction in an error state, It's like if in psql you run:
```
BEGIN;
SELECT whatever_thing_fails
DROP TABLE IF EXIST...
```
so please check your code using `self.conn` before you get into this statement.

**Comment by iamtekson** [comment]
Thank you very much for your reply. I just checked again my problem was, I had another open transaction in my code. Before starting the deletion of the table, I need to close the previous transaction.
