### ISSUE TITLE
ImportError: DLL load failed - Windows - pip install - python 3.9.0

### ISSUE THREAD

**Issue by adjenks** [psycopg/psycopg2#1174]
I'm installing psycopg2 on Windows and I am getting this error.
I have pip 20.2.4
My python is version 3.9.0
I have the latest version of Visual studio installed along with the build tools.
I am not using pycharm. Just `pip install psycopg2`.
I have postgresql installed and all the PATH directories configured.
I built it and it failed to import with the error in a previous issue: https://github.com/psycopg/psycopg2/issues/1006
>ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

**Comment by dvarrazzo** [comment]
#1160

**Comment by adjenks** [comment]
Thank you. I looked and found two other similar issues but not that one for some reason.
