### ISSUE TITLE
InvalidDatetimeFormat for a valid date "7/31/2020"

### ISSUE THREAD

**Issue by hginzel** [psycopg/psycopg2#1175]
Function `copy_from()` returns *InvalidDatetimeFormat* for a [**valid** date](https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-INPUT):
```
cursor.copy_from(f, table)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type date: "7/31/2020"
```
With psql `\copy` command same data are loaded correctly.
Python 3.8.5, psycopg 2.8.4 (dt dec pq3 ext lo64),  PostgreSQL 11.7 (Ubuntu 11.7-2.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**Comment by hginzel** [comment]
Excuse me, bug were somewhere else.

**Comment by dvarrazzo** [comment]
The above might have been because psycopg2 sets the date format to ISO.  In psycopg3 I'm working on accepting other formats too. In psycopg2 the above might have run ok if you had issued as `SET DateFormat` statement before running `cursor.copy_from()`.
