### ISSUE TITLE
zip_safe flag not set during installing psycopg2-2.8.

### ISSUE THREAD

**Issue by kunlk** [psycopg/psycopg2#1178]
Hi Team,

I saw a message below during build & install psycopg2-2.8.  The installation was finished at the end and I did not see any function break, but just want to double check if these message would bring any potential issues?  Thx! 

copying psycopg2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
**zip_safe flag not set; analyzing archive contents...
psycopg2.__pycache__._psycopg.cpython-37: module references __file__**
creating 'dist/psycopg2-2.8-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing psycopg2-2.8-py3.7-linux-x86_64.egg
creating /usr/local/lib/python3.7/site-packages/psycopg2-2.8-py3.7-linux-x86_64.egg
Extracting psycopg2-2.8-py3.7-linux-x86_64.egg to /usr/local/lib/python3.7/site-packages
Adding psycopg2 2.8 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/psycopg2-2.8-py3.7-linux-x86_64.egg
Processing dependencies for psycopg2==2.8
Finished processing dependencies for psycopg2==2.8

**Comment by dvarrazzo** [comment]
I think that message is just pip noise.
