### ISSUE TITLE
OperationalError: received invalid response to GSSAPI negotiation: 

### ISSUE THREAD

**Issue by soumyadatascience** [psycopg/psycopg2#1180]
this issue is coming with psycopg2==2.8.5 and python 3.8 , able to work with psycopg2==2.7.6.1 and python 3.7.*

**Comment by dvarrazzo** [comment]
From which platform? Using psycopg2 or psycopg2-binary package?

**Comment by soumyadatascience** [comment]
Issue observed running from macbook , and aws windows instance.

Running from python env installed by conda

**Comment by dvarrazzo** [comment]
Against the same database server? what version?

**Comment by soumyadatascience** [comment]
PostgreSQL 8.3.23 (Greenplum Database 5.28.0 )

**Comment by dvarrazzo** [comment]
PG 8.3 is long no more supported. Postgres people might have upgraded GSSAPI support in the libpq and the two cannot talk to each other anymore.

You can use ` psycopg2.extensions.libpq_version()` to get the libpq version used by the two libpq versions. Something might have changed across those versions.

**Comment by soumyadatascience** [comment]
I see the versions that is working as - 110002 and psycopg2==2.8.5 version as 120002

**Comment by soumyadatascience** [comment]
@dvarrazzo can you tell me whats the last supported version. i will communicate to the db admins is it 9.5

**Comment by dvarrazzo** [comment]
Greenplum is not officially supported by psycopg. I personally don't know anything about it.

However psycopg doesn't do anything but forwarding the request to the libpq. You should hear from Greenplum to know what is the last libpq version supported, or if there are any parameters to pass to the connection string to circumvent the problem.
