### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by eswarthammana** [psycopg/psycopg2#1181]
Python Version : 3.7.x

`conn = psycopg2.connect(conn_string)
    cur = conn.cursor()
    statement = "SELECT image FROM People WHERE ID = %s;"
    cur.execute(statement, (identity,))
    oid = cur.fetchone()[0]
    data = conn.lobject(oid)
    print("Postgres DB Data : ", data)
    print("Type Postgres DB Data : ", type(data))
    print(data.read())`
With the above code trying to read the image blob data which inserted to postgresDB using spring JPA.
While trying to read the blob data i am facing the exception as  
print(data.read())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Could you please help me to retrieve the data which i will pass to cv2

**Comment by dvarrazzo** [comment]
You should add the large object in binary mode, with `conn.lobject(oid, "rb")`

https://www.psycopg.org/docs/connection.html#connection.lobject

**Comment by eswarthammana** [comment]
Thanks for the quick help @dvarrazzo. Able to store data 👍
