### ISSUE TITLE
Add Python 3.9 support / binaries

### ISSUE THREAD

**Issue by mhindery** [psycopg/psycopg2#1183]

**Comment by mhindery** [comment]
@dvarrazzo this issue was closed (and similarly https://github.com/psycopg/psycopg2/issues/1184), but the page still does not mention Python 3.9 on https://pypi.org/project/psycopg2/.

**Comment by dvarrazzo** [comment]
I cannot change that page until a new release, but the packages are there.

https://pypi.org/project/psycopg2/#files
