### ISSUE TITLE
python3.9 docker error

### ISSUE THREAD

**Issue by domdinicola** [psycopg/psycopg2#1185]
I'm trying to update my docker image switching from python:3.8.2-alpine3.10 to python:3.9.0-alpine3.12, but I'm getting an issue when running django commands SSL_check_private_key: symbol not found.

I'm trying to update my docker image switching from python:3.8.2-alpine3.10 to python:3.9.0-alpine3.12, but I'm getting an issue when running django commands SSL_check_private_key: symbol not found.

I get the following error when running checks:

bash -c "touch /var/donor_reporting_portal/.touch && django-admin check --deploy " /usr/local/lib/python3.9/site-packages/environ/environ.py:628: UserWarning: /usr/local/lib/python3.9/site-packages/donor_reporting_portal/config/.env doesn't exist - if you're not configuring your environment separately, create one. Traceback (most recent call last): File "/usr/local/bin/django-admin", line 8, in sys.exit(execute_from_command_line()) File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 401, in execute_from_command_line File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 377, in execute File "/usr/local/lib/python3.9/site-packages/django/init.py", line 24, in setup File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 116, in create File "/usr/local/lib/python3.9/importlib/init.py", line 127, in import_module File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 790, in exec_module File "", line 228, in _call_with_frames_removed File "/usr/local/lib/python3.9/site-packages/django/contrib/postgres/apps.py", line 1, in File "/usr/local/lib/python3.9/site-packages/psycopg2/init.py", line 51, in ImportError: Error relocating /usr/local/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-x86_64-linux-gnu.so: SSL_check_private_key: symbol not found make[2]: *** [.run] Error 1 make[1]: *** [test] Error 2 make: *** [build] Error 2

I don't get any issue when running this on my machine.

https://stackoverflow.com/questions/64561145/python3-9-django-docker-postgres/64561321#64561321

**Comment by dvarrazzo** [comment]
Could you format the error better?

Can you provide the whole dockerfile?

**Comment by domdinicola** [comment]
Thanks Daniele,
I'm using two docker file (first is the base image)

Docker-base

`FROM python:3.9.0-alpine3.12

ARG PIPENV_ARGS

RUN apk add --no-cache --virtual .fetch-deps \
        curl \
        ca-certificates \
        openssl \
        tar

RUN apk add --no-cache --virtual .build-deps \
        autoconf \
        automake \
        pkgconf \
        g++ \
        json-c-dev \
        libtool \
        libxml2-dev \
        make \
        perl

RUN apk add --no-cache --virtual .build-deps-edge \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        # proj-dev \
        protobuf-c-dev

RUN apk add --no-cache --virtual .postgis-rundeps \
        mailcap \
        json-c \
        libuuid \
        libxml2


RUN apk add --no-cache --virtual .postgis-rundeps-edge \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        binutils \
        gosu \
        libmagic \
        libpq \
        libuuid \
        libxslt \
        libzmq \
        jpeg \
        # proj \
        protobuf-c \
        zlib

RUN apk add --no-cache --virtual .donor_reporting_portal-build-deps \
        freetype-dev \
        fontconfig-dev \
        freetype-dev \
        jpeg-dev \
        lcms2-dev \
        libffi-dev \
        libressl-dev \
        linux-headers \
        musl-dev \
        openjpeg-dev \
        postgresql-dev \
        python3-dev \
        tcl-dev \
        tiff-dev \
        tk-dev \
        zlib-dev

RUN apk add --no-cache --virtual .donor_reporting_portal-run-deps \
        postgresql-libs

RUN apk add --no-cache --virtual .system-run-deps \
        bash

RUN mkdir /code
ADD Pipfile* /code/
RUN pip install pip pipenv --upgrade
RUN cd /code \
    && pipenv install --verbose --system --deploy --ignore-pipfile $PIPENV_ARGS \
    && sha1sum Pipfile.lock > /CHECKSUM

# need to removes some code not py3.9 compliant
RUN rm -fr /usr/local/lib/python3.9/site-packages/psycopg2/tests/* \
           /usr/local/lib/python3.9/site-packages/tornado/test/* \
           /usr/local/lib/python3.9/site-packages/pipenv/patched/yaml2/*

# before compile site-packages
RUN find /usr/local/lib/python3.9/ -name *.pyc | xargs rm -f \
    && python -O -m compileall -fqb /usr/local/lib/python3.9 \
    && find /usr/local/lib/python3.9/ -name *.py | xargs rm -f

RUN apk del .fetch-deps .build-deps .build-deps-edge .donor_reporting_portal-build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -fr /root/.cache/ \
    && rm -fr /usr/include/
`

Docker file (which fails)

`ARG BASE_IMAGE=1.5

FROM <REPO>:${BASE_IMAGE}-base

#ARG BUILD_DATE
#ARG VERSION

#ENV GITHUB_TOKEN=${GITHUB_TOKEN}
#ENV DONOR_REPORTING_PORTAL_VERSION=${VERSION}

RUN mkdir -p /code
COPY . /code
WORKDIR /code

RUN set -ex \
    ls -al /code \
    && sha1sum -c /CHECKSUM \
    && pip3 install . \
    && rm -fr /code


ENV PIPENV_PYPI_MIRROR=${PIPENV_PYPI_MIRROR}, \
    HOME=/root/ \
    PYTHONUNBUFFERED=1 \
    ALLOWED_HOSTS="*" \
    CACHE_URL="redis://127.0.0.1:6379/1" \
    CELERY_AUTOSCALE="5,1" \
    CELERY_BROKER_URL="redis://127.0.0.1:6379/2" \
    CELERY_LOGLEVEL="ERROR" \
    CELERY_RESULT_BACKEND="redis://127.0.0.1:6379/3" \
    CELERY_EXTRA="" \
    CSRF_COOKIE_SECURE=True \
    DATABASE_URL="postgres://postgres:@192.168.66.66:5432/db" \
    DEBUG=0 \
    DJANGO_SETTINGS_MODULE=donor_reporting_portal.config.settings \
    MEDIA_ROOT=/tmp/media \
    STATIC_ROOT=/var/donor_reporting_portal/static/ \
    SECRET_KEY="secret" \
    SECURE_BROWSER_XSS_FILTER=True \
    SECURE_CONTENT_TYPE_NOSNIFF=True \
    SECURE_FRAME_DENY=True \
    SECURE_HSTS_INCLUDE_SUBDOMAINS=True \
    SECURE_HSTS_PRELOAD=True \
    SECURE_HSTS_SECONDS=1 \
    SECURE_SSL_REDIRECT=True \
    SENTRY_DSN="" \
    SESSION_COOKIE_HTTPONLY=True \
    SESSION_COOKIE_SECURE=True

ENV UWSGI_PROTOCOL=http \
    UWSGI_WORKERS=4 \
    UWSGI_AUTO_PROCNAME=true \
    UWSGI_BUFFER_SIZE=32768 \
    UWSGI_DIE_ON_TERM=true \
    UWSGI_DISABLE_LOGGING=false \
    UWSGI_DISABLE_WRITE_EXCEPTION=true \
    UWSGI_FREEBIND=true \
    UWSGI_HARAKIRI=180 \
    UWSGI_HTTP_TIMEOUT=180 \
    UWSGI_IGNORE_SIGPIPE=true \
    UWSGI_IGNORE_WRITE_ERRORS=true \
    UWSGI_LIMIT_POST=20971520 \
    UWSGI_LOG_X_FORWARDED_FOR=false \
    UWSGI_MEMORY_REPORT=true \
    UWSGI_NEED_APP=true \
    UWSGI_POST_BUFFERING=65536 \
    UWSGI_PROCNAME_PREFIX_SPACED="[DonorReportingPortal]" \
    UWSGI_RELOAD_ON_RSS=600 \
    UWSGI_THREADS=4 \
    UWSGI_THUNDER_LOCK=true \
    UWSGI_VACUUM=true \
    UWSGI_MODULE="donor_reporting_portal.config.wsgi:application" \
    UWSGI_HTTP_SOCKET=0.0.0.0:8000 \
    UWSGI_MASTER=true \
    UWSGI_ENABLE_THREADS=true \
    UWSGI_LAZY_APPS=true \
    UWSGI_SINGLE_INTERPRETER=true

EXPOSE 8000

ADD docker/*.sh /usr/local/bin/

#RUN addgroup --gid 1024 donor_reporting_portal \
#    && adduser --disabled-password --ingroup donor_reporting_portal -S donor_reporting_portal

ENTRYPOINT ["entrypoint.sh"]
RUN ["chmod", "+x", "/usr/local/bin/entrypoint.sh"]
WORKDIR /var/donor_reporting_portal

CMD ["donor_reporting_portal"]
`

`
bash -c "touch /var/donor_reporting_portal/.touch && django-admin check --deploy " /usr/local/lib/python3.9/site-packages/environ/environ.py:628:
UserWarning: /usr/local/lib/python3.9/site-packages/donor_reporting_portal/config/.env doesn't exist - if you're not configuring your environment separately, create one.
Traceback (most recent call last):
File "/usr/local/bin/django-admin", line 8,
in sys.exit(execute_from_command_line()) File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 401,
in execute_from_command_line File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 377,
in execute File "/usr/local/lib/python3.9/site-packages/django/init.py", line 24,
in setup File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, 
in populate File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 116, 
in create File "/usr/local/lib/python3.9/importlib/init.py", line 127, 
in import_module File "", line 1030,
in _gcd_import File "", line 1007, 
in _find_and_load File "", line 986, 
in _find_and_load_unlocked File "", line 680,
in _load_unlocked File "", line 790,
in exec_module File "", line 228, 
in _call_with_frames_removed File "/usr/local/lib/python3.9/site-packages/django/contrib/postgres/apps.py", line 1, in File "/usr/local/lib/python3.9/site-packages/psycopg2/init.py", line 51, 
in ImportError: Error relocating /usr/local/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-x86_64-linux-gnu.so: SSL_check_private_key: symbol not found make[2]: *** [.run]
Error 1 make[1]: *** [test]
Error 2 make: ***
[build] Error 2
`

**Comment by domdinicola** [comment]
https://stackoverflow.com/questions/60588431/psycopg2-import-error-ssl-check-private-key-symbol-not-found

**Comment by dvarrazzo** [comment]
It does seem a problem with alpine, yes. Please use a bese image providing all the services required.
