### ISSUE TITLE
python setup.py egg_info - Error with pip installation

### ISSUE THREAD

**Issue by kalkayan** [psycopg/psycopg2#1186]
The first command on the documentation page is running into error.

OS - MacOS Catlina latest
Python - 3.8.5
Pip - 20.2.2

<img width="1165" alt="Screenshot 2020-11-09 at 11 29 24 PM" src="https://user-images.githubusercontent.com/73003119/98578563-85a47400-22e3-11eb-9cda-aee8397cfc19.png">

> works if just download the binary but please lets fix this.

**Comment by dvarrazzo** [comment]
Please install the requirements clearly described in the error message you pasted and in the documentation, or just use the binary.
