### ISSUE TITLE
Empty Select slow performance

### ISSUE THREAD

**Issue by josephcomisi** [psycopg/psycopg2#1187]
Hello,

Not really sure where I should put this. Do not hesitate if it needs to be relocated

I juste encountered the following behaviour when using psycopg2 and timescaledb (almost empty database):

On a basic "SELECT 1 FROM table WHERE key = 'value'" with **fetchone()** 
if the value exists, the query is really fast (0.00075sec)
if the value does not exists, the problem arise (1.2216sec)

However, if I always return something by modifying the query: SELECT CASE WHEN EXISTS(SELECT 1 FROM table WHERE key = 'value') THEN 1 ELSE 0 END
the performance are far much better:
if the value exists: 0.000553
if the value does not exists: 0.00085

I don't know if the issue comes from the database itself or the function fetchone() which would return an error if the query is empty, but I thought it would worth mentioning for further tests

**Comment by dvarrazzo** [comment]
Hello @josephcomisi 

this comes most definitely from the database: you would have the same behaviour in psql. It seems to me that you have a missing index, and the value found comes from a cache.

`fetchone()` doesn't return an error if the query is empty: it would return None.

I think you have to look for the problem in your schema, not in psycopg.

**Comment by josephcomisi** [comment]
Yes it returns None. 

I said error referring to the doc: https://www.psycopg.org/docs/cursor.html
"A ProgrammingError is raised if the previous call to execute*() did not produce any result set or no call was issued yet."

Sorry if I was confusing

**Comment by dvarrazzo** [comment]
That's if the previous execute call doesn't produce a result set, like an ALTER TABLE or an UPDATE without RETURNING.

SELECT does produce a record set, it's just that it can be empty, in which case fetchone() will return None.

**Comment by josephcomisi** [comment]
Yes, fetchone() return None. 

My point is more on the performance issue between 
SELECT 1 FROM table WHERE key = 'value'
SELECT CASE WHEN EXISTS(SELECT 1 FROM table WHERE key = 'value') THEN 1 ELSE 0 END

In the first case, if the value does not exist, the query takes far much time than the second one when I want to retrieve the result with fetchone(). Of course, in the first case, I get None, and in the second case I get 0.

I don't think this issue come from the database as I have similar performance when running these queries via psql

**Comment by fogzot** [comment]
Please, when talking about performance always use `EXPLAIN ANALYZE` on your queries and include the results in the issue. This way we can decide if it is a PostgreSQL or psycopg problem.
