### ISSUE TITLE
restart_lsn is not moving forward

### ISSUE THREAD

**Issue by manerohit388** [psycopg/psycopg2#1189]
We are using AWS Aurora PostgreSQL 10.11 version. We have AWS lambda function which uses psycopg2 to read data from replication slot. We have observed that in case of bulk transaction restart_lsn stops moving forward after we flush lsn using send_feedback(flush_lsn=lsn, reply=True). Here lsn is next_lsn associated with each change object which we get when we read data from replication slot. When I run this query select * from pg_catalog.pg_replication_slots; after processing records. I can see that restart_lsn is same and confirmed_flush_lsn is getting updated. Every time lambda starts reading data from slot it reads the data from restart_lsn onwards and which causes same data to be processed again and again. What could be the reason for restart_lsn not moving forward?  Thanks.

**Comment by qris** [comment]
@manerohit388 restart_lsn will apparently not advance while [any transactions are still running](https://www.postgresql-archive.org/Movement-of-restart-lsn-position-movement-of-logical-replication-slots-is-very-slow-td6167219.html), so you may have to wait until all transactions have finished (that were running at the time that you called `send_feedback`) before restart_lsn will advance. If you have a transaction open forever, that might cause restart_lsn to never move?

> The confirmed_flush_lsn is updated when we get confirmation
from the downstream node about the flush_lsn but restart_lsn is only
incremented based on the LSN required by the oldest in-progress
transaction.

**Comment by dvarrazzo** [comment]
Assuming not an issue
