### ISSUE TITLE
Feature: Automatically close connection or putconn back to the pool when using a with clause

### ISSUE THREAD

**Issue by willemavjc** [psycopg/psycopg2#1194]
This may sound a personal point of view and this may truly be but: 
Based on the experience I got with `cx_Oracle` and others libraries including ones from the very Python core such `OS`, I found that the overall experience and confidence in programming is better when the developer can safely rely on the library to automatically support on some sort of resources liberation.

This can be considered as sugar, true, but this is also part of that new spirit of Python 3 implementations. In my opinion this would also **unify** the experience for developers _accross_ developments involving **differents** databases, so differents libraries.

```
with self.sess.getconn() as connection:
   ... do some stuff
self.sess.putconn(connection) # This would no longer be required as per the shared logic among other libraries
```

```
with self.connect() as connection:
   ... do some stuff
self.close() # This would no longer be required as per the shared logic among other libraries
```

This feature is implemented for cursors. Is there any reason for not doing it for connections?
Thanks in advance for your kind replies.

Documentation reference:
https://www.psycopg.org/docs/usage.html#with-statement

**Comment by willemavjc** [comment]
I found some examples for Oracle to precise the thing if needed:
https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#closing-connections

**Comment by dvarrazzo** [comment]
Hi,

this is a topic that has been discussed. In psycopg2 the connection wraps [a transaction context](https://www.psycopg.org/docs/usage.html#with-statement), and it's equivalent to begin/commit. This was an idea discussed in the DBAPI mailing list, but never hit the specs, and with my 20/20 hindsight now I think it was a good accident. This precludes using the connection in a context manager calling close, or putting it back a connection pool.

psycopg3 connection context works [the way you suggest](https://www.psycopg.org/psycopg3/docs/usage.html#with-connections-and-cursors), but for psycopg2 now would be a non-backward compatible change.

**Comment by willemavjc** [comment]
Oh I did not know psycopg3 existence! (It's nearly referenced nowhere.) Not sure to understand the current stability of this new "branch" though! Your thoughts?

**Comment by dvarrazzo** [comment]
Not released yet, but currently in active development: https://www.psycopg.org/psycopg3/

**Comment by willemavjc** [comment]
Eager to see it live then! :)
