### ISSUE TITLE
Autocommit mode does not work as expected with executing multiple statements

### ISSUE THREAD

**Issue by jannschu** [psycopg/psycopg2#1201]
Hi,

the following fails:
```python
conn = psycopg2.connect(...)
conn.autocommit = True
cur = conn.cursor()
cur.execute("VACUUM FULL; SELECT 1")
# exception: ActiveSqlTransaction: VACUUM cannot run inside a transaction block
```
Changing the last line to the following ones does not result in the error:
```python
cur.execute("VACUUM FULL")  # ok one statement, no transaction
cur.execute("VACUUM FULL;;")  # this is a bit surprising to me
```

After reading the relevant parts of the documentation I would have expected this to work. Is it a bug or maybe a documentation issue? It seems with two statements a transaction is created despite autocommit. There is also an older [StackOverflow question](https://stackoverflow.com/questions/36416405) for this problem.

**Comment by dvarrazzo** [comment]
Probably Postgres  starts a transaction itself around statements run in the same exec. It's not something psycopg2 can change.

Please note that psql does some parsing of the queries and splits on the semicolons: the two "now()" are sent as two queries.
```
piro=# set log_min_duration_statement to 0;
piro=# select now(); select now();
              now              
-------------------------------
 2020-11-27 17:06:34.827396+00
(1 row)

              now              
-------------------------------
 2020-11-27 17:06:34.828081+00
(1 row)
```

In the server:
```
2020-11-27 17:06:34.827 GMT [15600] piro@piro LOG:  duration: 0.193 ms  statement: select now();
2020-11-27 17:06:34.828 GMT [15600] piro@piro LOG:  duration: 0.130 ms  statement: select now();
```

psycopg sends them together, it doesn't parse the statement:

```
In [1]: import psycopg2                                                                                                             
In [2]: cnn = psycopg2.connect("")                                                                                                  
In [3]: cur = cnn.cursor()                                                                                                          
In [4]: cnn.autocommit = 1                                                                                                          
In [5]: cur.execute("set log_min_duration_statement to 0")                                                                          
In [6]: cur.execute("select now(); select now();")                                                                                  
Out[7]: [(datetime.datetime(2020, 11, 27, 17, 9, 29, 151625, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0, name=None)),)]
```

Unfortunately psycopg2 discards all but the last query result. psycopg3 can fetch them thogh:
```
In [1]: import psycopg3
In [2]: cnn = psycopg3.connect()
In [3]: cur = cnn.cursor()
In [4]: cnn.autocommit = True
In [5]: cur.execute("set log_min_duration_statement to 0")
In [6]: cur.execute("select now(); select now();")
In [7]: cur.fetchone()
Out[7]: (datetime.datetime(2020, 11, 27, 17, 13, 55, 962881, tzinfo=datetime.timezone.utc),)
In [8]: cur.nextset()
Out[8]: True
In [9]: cur.fetchone()
Out[9]: (datetime.datetime(2020, 11, 27, 17, 13, 55, 962881, tzinfo=datetime.timezone.utc),)
```
And the timestamp is precisely the same: this means that the server does wrap the two exec in the same transaction.

So it's not something we can change client-side, unless we start parsing the query, which is something we don't want to do.

Postgres is probably good enough at detecting empty statements, that's why the `;;` experiment doesn't trigger the error.

**Comment by jannschu** [comment]
Thanks for this detailed answer :-) 👍

**Comment by tombh** [comment]
Wow, thank you @jannschu and @dvarrazzo, your clear statements of the problem and solution ended hours of search for me. A seemingly unimportant closed issue turned out to be very useful to me, thank you for taking the time in your write ups.

**Comment by james-johnston-thumbtack** [comment]
@dvarrazzo same sentiments as @tombh - the copies of the server logs for both psql and pyscopg2 really helped show the difference!

Here's some relevant PG documentation: https://www.postgresql.org/docs/15/protocol-flow.html#id-1.10.6.7.4

Look under "55.2.2.1. Multiple Statements In A Simple Query"

> When a simple Query message contains more than one SQL statement (separated by semicolons), those statements are executed as a single transaction, unless explicit transaction control commands [BEGIN/END] are included to force a different behavior

The key phrase is _implicit transaction block_
