### ISSUE TITLE
pg_config is deprecated in some distros

### ISSUE THREAD

**Issue by sadko4u** [psycopg/psycopg2#1203]
For some Linux Distributions, **pg_config** tool is deprecated.
Maintainers recommend to use standard **pkg-config** tool instead.
Would be nice if you could add the corresponding workaround.

https://lists.opensuse.org/opensuse-factory/2019-03/msg00299.html

**Comment by dvarrazzo** [comment]
I don't use suse. If you do documentation patch is welcome.

**Comment by sadko4u** [comment]
I don't use Debian-based distros nor FreeBSD. But when necessary, I install a virtual machine:

https://github.com/sadko4u/lsp-plugins/issues/154

Moreover, I'm not a python developer do deeply dig into code and build process of the library.

**Comment by dvarrazzo** [comment]
Duplicate of #1001
