### ISSUE TITLE
Module not found when building from source in multi-stage docker

### ISSUE THREAD

**Issue by BeyondEvil** [psycopg/psycopg2#1204]
I realize this is a hail mary, but I've spent almost 3 hours on this and it's driving me crazy.

I'm getting an issue when trying to use psycopg2 in a docker container using a multi-stage build (see Dockerfile below).

Regardless of what query I run, I get an error:

```python
cur.execute('SELECT version()')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block
```

I figured I would install psycopg2 from source, so that I could enable debug-mode, but I just can't seem to get it to work.

It works in the build-stage (`builder`), but not in the final image (`runtime`). I keep getting:

```python
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'psycopg2'
```

Please save me.

<details>

<summary> Dockerfile </summary>

```Dockerfile
FROM python:3.8-slim AS base

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1

FROM base AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-dev gcc libpq-dev curl && \
    pip --no-cache-dir install --upgrade pip && \
    pip --no-cache-dir install --upgrade pipenv==2018.11.26

COPY Pipfile* ./

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --skip-lock

RUN curl https://files.pythonhosted.org/packages/fd/ae/98cb7a0cbb1d748ee547b058b14604bd0e9bf285a8e0cc5d148f8a8a952e/psycopg2-2.8.6.tar.gz | tar xz -C /.venv && \
    cd /.venv/psycopg2-2.8.6/ && \
    sed -i 's/define =/define = PSYCOPG_DEBUG/g' setup.cfg && \
    python3 setup.py build && \
    python3 setup.py install

FROM base AS runtime

ENV PSYCOPG_DEBUG 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl libpq5

COPY --from=builder /.venv /.venv
COPY --from=builder /usr/local/lib/python3.8/site-packages/psycopg2-2.8.6-py3.8-linux-x86_64.egg /usr/local/lib/python3.8/site-packages/psycopg2-2.8.6-py3.8-linux-x86_64.egg

ENV PATH="/.venv/bin:$PATH"

RUN useradd --create-home blackbox

WORKDIR /home/blackbox

USER blackbox

COPY generate_incident.py encrypted_attr.py ./

ENTRYPOINT [ "python3" ]

CMD ["generate_incident.py"]

```

</details>

**Comment by dvarrazzo** [comment]
> Please save me

ha ha let's try

I think you are entirely on the wrong road. If you are getting `InFailedSqlTransaction` it means that the query before in the same connection had an error, that's it. Why are you not seeing that error? Are you using a pattern like `try: ... except: pass` and swallowing it?

Just look at the database logs and you will find your error there.

Compiling psycopg2 in a docker multi-stage build and debugging your Dockerfile is not really something I'd like to do: for debugging purpose you can just `docker exec bash` and build psycopg interactively, or write the build steps in a bash script. Besides, it's not something that would help you: debug mode is to debug errors inside psycopg2, not errors of your program.

Please look for your application errors in the database log, and figure out why the failing error in python is not displayed: there is an exception you are swallowing somewhere in your program.

**Comment by BeyondEvil** [comment]
> > Please save me
> 
> ha ha let's try

Thanks! 🙏 ❤️ 

> I think you are entirely on the wrong road. If you are getting `InFailedSqlTransaction` it means that the query before in the same connection had an error, that's it. Why are you not seeing that error? Are you using a pattern like `try: ... except: pass` and swallowing it?

That's the thing, I'm not running a python script per se. I'm basically running python from the command line in the container:

```
docker run psycopg2 python3
```

Once in the prompt, I ran: 

```python
import psycopg2 as p
conn = p.connect(host="postgres", dbname="proxyres", user="postgres", password="testthecode")
cur = conn.cursor()
cur.execute('SELECT version()')
print(cur.fetchone()[0])
```

So there weren't really any prior connections that could've failed. 🤷‍♂️ 

> Just look at the database logs and you will find your error there.

Didn't think of that, should've thought of that, will think of that next time. 😆 

> Compiling psycopg2 in a docker multi-stage build and debugging your Dockerfile is not really something I'd like to do: 

Me neither 😝 

> for debugging purpose you can just `docker exec bash` and build psycopg interactively, or write the build steps in a bash script. Besides, it's not something that would help you: debug mode is to debug errors inside psycopg2, not errors of your program.

Right, the problem with that was that I was convinced the problem was with what runtime requirements were available (gcc, libpq etc.), so I wanted the to keep build and runtime separate.

> Please look for your application errors in the database log, and figure out why the failing error in python is not displayed: there is an exception you are swallowing somewhere in your program.

Funny thing is, shortly after writing this issue and before rage quitting, I nuked all the docker stuff and rebuilt and restarted everything. Lo and behold, it now worked. 🤷‍♂️ 

I'll simply have to learn to live with the fact that I'll never know what the issue was.

Big thanks @dvarrazzo for taking the time to respond to my woes, it's greatly appreciated! 🙏
