### ISSUE TITLE
Aarch64 can't find psycopg2_binary.libs

### ISSUE THREAD

**Issue by w345731923** [psycopg/psycopg2#1210]
The environment x86:
I did a test,the system install```yum Install python3-pip```,
then `pip3 install psycopg2-binary`,
 I can see xx/python3.6/site-packages/ 
*psycopg2
*psycopg2_binary 2.8.6.dist-info
*psycopg2_binary. libs
Notice that there is psycopg2_binary. libs folder!
I'm using python3.8 on the relative path, with `./bin/pip3 install psycopg2-binary` , also psycopg2_binary.lib folder,no doubt.

But with AARCH64, I did the same thing with relative paths python3.8 without `psycopg2_binary.lib`,why?

**Comment by dvarrazzo** [comment]
- Aarch64 is not yet supported as binary distribution. There might be a work in progress but it hasn't been deployed yet.

- I don't know what artifact is installed on aarch64, however there might not be a packaged called `psycopg2_binary` because both the `psycopg2` and `psycopg2-binary` distributions create a Python package called `psycopg2`, so it might be that.
-

**Comment by w345731923** [comment]
Oh, my god. I found a solution.

1、Download the version used.--https://pypi.org/project/psycopg2-binary/#files
2、Rename the file to `linux_aarch64`
`mv psycopg2_binary-2.8.6-cp37-cp37m-manylinux1_x86_64.whl psycopg2_binary-2.8.6-cp37-cp37m-linux_aarch64.whl `
3、`pip3 install psycopg2_binary-2.8.6-cp37-cp37m-linux_aarch64.whl `
4、show site-packages
*drwxr-xr-x  3 root root   4096 Dec 16 21:36 psycopg2
*drwxr-xr-x  2 root root   4096 Dec 16 21:36 psycopg2_binary-2.8.6.dist-info
*drwxr-xr-x  2 root root   4096 Dec 16 21:36 psycopg2_binary.libs

This is great.But pip Install isn't perfect.

**Comment by dvarrazzo** [comment]
I'd be surprised if it works

**Comment by w345731923** [comment]
I'm sure.The aarch64 environment, python3.7 and 3.8 both did the same testing and both worked fine.
It's worth noting that it must be `manylinux1_x86_64.whl`,and then the `mv` renames it `linux_aarch64.whl`.
Look,
> drwxr-xr-x  3 root root  4096 Dec 17 09:36 psycopg2
> drwxr-xr-x  2 root root  4096 Dec 17 09:36 psycopg2_binary-2.8.6.dist-info
> drwxr-xr-x  2 root root  4096 Dec 17 09:36 psycopg2_binary.libs

If you execute `manylinux1_x86_64.whl` , it prompts `not a supported`.
`[root@ecs-monintor python381]# ./bin/pip3 install /opt/psycopg2_binary-2.8.6-cp38-cp38-manylinux1_x86_64.whl 
ERROR: psycopg2_binary-2.8.6-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.`

I think this approach can help developers at AARCH64,or update pip Install.
May I help you？

**Comment by w345731923** [comment]
Oh no.
`import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python381/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'`

I think I'll just use the psycopg2_binary.libs folder.
For a layman, it's not going well.

**Comment by w345731923** [comment]
I need to test again

**Comment by w345731923** [comment]
I tried many ways, but failed at last.
Install psycopg2-binary in AARCH64 environment, he will download the source code to compile, I must install the dependency package he needs, instead of automatically compiling the dynamic link library.
I would say that's not perfect.The x86 way is great.
