### ISSUE TITLE
psycopg2 works fil when connecting my django app to a local database, but returning "GSSAPI continuation error: No credentials cache found" when connecting to a remote database server

### ISSUE THREAD

**Issue by FatfoutiMontassar** [psycopg/psycopg2#1212]
Hello, i'm building a website and it's supposed to be connected to a postgresql database, i was cogin on a windows machine and everything was fine.
now we should move the project to a linux (ubuntu 20.04) machine to deploy it.

my problem is when i try to connect the project to the remote database server .. i get this error:

`  File "/home/mfatfouti/Apps/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: GSSAPI continuation error: Unspecified GSS failure.  Minor code may provide more information
GSSAPI continuation error: No credentials cache found
`

here is my database config:
- remote DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_name',
        'USER': 'db_user',
        'PASSWORD': 'db_password',
        'HOST': 'db_host',
        'PORT': '5432',
    }
}

- local DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'db_name',
        'USER': 'db_user',
        'PASSWORD': 'db_password',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

**Comment by dvarrazzo** [comment]
Please write to the mailing list. This is a bug tracker, not a support forum
