### ISSUE TITLE
Unable to cast psycopg2 datetime

### ISSUE THREAD

**Issue by lesreaper** [psycopg/psycopg2#1215]
Pulling a row from the DB that holds a datetime in one column. So, for the entire return call:
```
sql = ''' SELECT * FROM "database_1" WHERE item_id IN (SELECT item_id FROM "database_2" WHERE item_type = %s); '''

try:
    cur = conn.cursor()
    cur.execute(sql, (item_type,))
    return cur.fetchall()
except Exception as e:
    log.error(f"[ERROR]: Fetch items by item type: {e}")
```
And the return item is a list of tuples, with each row being:
```
(21, datetime.datetime(2020, 12, 21, 12, 54, 53, 11652, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-300, name=None)), 0.0, True, True, 5)
```
I need to get the datetime column into a Python datetime object, so I looked at some of the new extensions like:
`psycopg2.extensions.PYDATETIMETZ`

The thing is, there is no documentation that I can find to actually show anyone implementing a datetime conversion like this. How do I do this conversion after I pull the row from the db and am passing it around the app?

The documentation I see doesn't seem to help in this use case:
https://share.getcloudapp.com/nOuDQrym

Can I do this type of conversion when making the original call, even if I'm calling the entire row? I haven't seen that before.

Any help would be great!

**Comment by dvarrazzo** [comment]
I really don't understand your question.

`cur.fetchone()[1]` gives your date as a datetime object.

What else do you need?

**Comment by lesreaper** [comment]
Sorry, I updated with the SQL statement above to be more clear. I'm fetching thousands of records, and am trying to get the datetimes in the return values `[..., (21, datetime.datetime(2020, 12, 21, 12, 54, 53, 11652, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-300, name=None)), 0.0, True, True, 5)
,...] casted into a proper Python date time object, and then converted to a string.

I tried `strftime` with multiple formats, but couldn't one that gives the proper format `2020-10-09T02:07:29.492232Z`

So, in essence, I'm going to need to serialize and deserialize the date objects from PGSQL->Datetime->String and then again from String->Datetime->PGSQL. 

The docs mentioned the extension above `psycopg2.extensions.PYDATETIMETZ` that was recently added to help with this process, but the implementation isn't clear.

**Comment by dvarrazzo** [comment]
> the proper `2020-10-09T02:07:29.492232Z`

Is that because you need an UTC date?

This works well for me

```
In [2]: import psycopg2                                                                                              
In [3]: import datetime                                                                                              

# Coming from your record
In [4]: dt = datetime.datetime(2020, 12, 21, 12, 54, 53, 11652, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-300, name=None)) 

In [6]: dt.astimezone(datetime.timezone.utc)                                                                         
Out[6]: datetime.datetime(2020, 12, 21, 17, 54, 53, 11652, tzinfo=datetime.timezone.utc)

In [10]: dt.astimezone(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")                                      
Out[10]: '2020-12-21T17:54:53.011652Z'
```

> The docs mentioned the extension above psycopg2.extensions.PYDATETIMETZ that was recently added to help with this process, but the implementation isn't clear.

You don't need it directly (psycopg2 is already using it for you).

**Comment by lesreaper** [comment]
Wow, ok, that worked, thank you!

I guess I simply didn't understand how the `datetime` conversion came out of this. Closing the ticket for future reference!
