### ISSUE TITLE
The connection's default encoding is SQLASCII ?

### ISSUE THREAD

**Issue by EasonEdison** [psycopg/psycopg2#1217]
**Environment**:
Ubuntu 18.06
Python 3.8.6 
psycopg2==2.8.6  
pycparser==2.20
**my code**:
```python
connect = psycopg2.connect(database=psql_database, user=psql_username, password=psql_pwd, host=psql_host, port=psql_port);
cursor = connect.cursor()
sql = "SELECT name FROM area WHERE id = {}".format(area_id)
cursor.execute(sql)
connect.commit()
area_name = cursor.fetchall()   # error
```
```
root@pid-html-5b586cb7bb-zk22n:/opt# python main.py --person "1311170666770202624,1276802317403828224"  --start "2020-11-01 00:00:00" --end "2020-11-10"
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    resultList.append(doQuery(person, start_time, end_time));
  File "/opt/utils.py", line 44, in doQuery
    row[-5] = query_psql(row[-5])
  File "/opt/utils.py", line 72, in query_psql
    area_name = cursor.fetchall()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)
```
My `sys.getdefaultencoding()` is `utf-8`
How should I do to resolve it？

-----

Now I found the encoding in PSQL is `UTF-8` (use `\encoding`)，but in Python3 the `conn.encoding` is `SQLASCII`, how to change it to `UTF-8`?

-----

Now I resolve it, use same docker, in cluster the `conn.encoding=SQLASCII` , in my VM the `conn.encoding=UTF8`,  and the databse both are `utf-8`, why it different?

**Comment by EasonEdison** [comment]
and the result of query is chinese

**Comment by dvarrazzo** [comment]
The connection's default is what your database declares.
