### ISSUE TITLE
copy_expert with chunks

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [psycopg/psycopg2#1218]
I would like to export the data in Postgres to CSV with chunks. For example, I have a table with 1million rows. The copy_expert will export the data into a single CSV file.

But is there any way that I can do export a `select * from` results to multiple CSV files? like 10k rows per file?

**Comment by dvarrazzo** [comment]
You have to use `copy (select * from table order by ... limit x offset y)` or something similar (limit-offset is quadratic, better to use an unique index and specify "where field > (the last index you exported) limit x".

Please use the mailing list, not the bug tracker, thank you.
