### ISSUE TITLE
Feature: psycopg2.pool.AbstractConnectionPool "block for X until connection becomes available"

### ISSUE THREAD

**Issue by jcpunk** [psycopg/psycopg2#1220]
It would be helpful if the `psycopg2.pool.AbstractConnectionPool` derived classes had some sort of way to wait for a bit if the pool is exhausted.

For example, if my site is normally under load X, but goes viral had ends up with load X^2, it would be nice if I could easily configure the connection pool to "check for a free connection for a few seconds" (or forever based on what args get set) before returning the exception.

In theory this would make the connection pooling a bit more robust under surprise load and make psycopg2 more closely match the feature set of `DBUtils` connection pooling.

**Comment by dvarrazzo** [comment]
Hey hello,

thank you for the input. I agree that psycopg2 pool is a bit of a neglected area. I am studying a bit what a good pool should do, looking at other implementations (HikariCP seems a great, well thought one). Definitely a saner behaviour would be to block and to have a time out (e.g. respecting the requested connection timeout).

In the next days I will try to put together some ideas in a coherent way. Input is welcome if you think there are other points to take care of :slightly_smiling_face:

**Comment by jcpunk** [comment]
Historically, we've used https://webwareforpython.github.io/DBUtils/main.html but I'm trying to slim down our requirements (and this was a good opportunity to feed practical ideas into the hands of folks looking psycopg3).  We've also looked at https://github.com/pgbouncer/pgbouncer in the past.

**Comment by dvarrazzo** [comment]
What proposed is obviously the right thing to do. However the proposed change wouldn't be easy to be introduced in the psycopg2 pool without extensive rewrite.

The psycopg3 pool does the right thing in this area. If any we would need to backport that pool implementation as an external module.

**Comment by gunar** [comment]
Here you go:

```python
# https://stackoverflow.com/a/53437049
from threading import Semaphore
class ReallyThreadedConnectionPool(psycopg2.pool.ThreadedConnectionPool):
    def __init__(self, minconn, maxconn, *args, **kwargs):
        self._semaphore = Semaphore(maxconn)
        super().__init__(minconn, maxconn, *args, **kwargs)

    def getconn(self, *args, **kwargs):
        self._semaphore.acquire()
        return super().getconn(*args, **kwargs)

    def putconn(self, *args, **kwargs):
        super().putconn(*args, **kwargs)
        self._semaphore.release()
```

**Comment by gunar** [comment]
Here you go:

```python
# https://stackoverflow.com/a/53437049
from threading import Semaphore
class ReallyThreadedConnectionPool(psycopg2.pool.ThreadedConnectionPool):
    def __init__(self, minconn, maxconn, *args, **kwargs):
        self._semaphore = Semaphore(maxconn)
        super().__init__(minconn, maxconn, *args, **kwargs)

    def getconn(self, *args, **kwargs):
        self._semaphore.acquire()
        try:
            conn = super().getconn(*args, **kwargs)
        except:
            self._semaphore.release()
            raise
        return SemaphoreManagedConnection(self, conn)

class SemaphoreManagedConnection:
    def __init__(self, pool, conn):
        self.pool = pool
        self.conn = conn
        self.conn.autocommit = True

    def cursor(self, *args, **kwargs):
        return self.conn.cursor(*args, **kwargs)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        try:
            self.conn.close()
        finally:
            try:
                self.pool.putconn(self.conn)
            finally:
                self.pool._semaphore.release()
```

**Comment by dvarrazzo** [comment]
This "here you go" is growing quickly and hairy. How about you write your own project with there ideas, and mat show, with tests that it works?

Someone wrote [a backport of psycopg 3 pool for psycopg2](https://github.com/bluetech/psycopg-pool-backport). You are much better off using that.
