### ISSUE TITLE
updating data of custom type

### ISSUE THREAD

**Issue by lchunleo** [psycopg/psycopg2#1221]
Hi
 i had create a table which is the follow

CREATE TYPE bagtype AS (
 bag smallint
)

CREATE TABLE student (
  studentid INTEGER PRIMARY KEY,
  studentinfo  bagtype[]
)

my issue is how to perform update in psycog2 and postgres statement? thanks

**Comment by dvarrazzo** [comment]
You can check out the [composite type caster](https://www.psycopg.org/docs/extras.html#composite-types-casting) documentation. Arrays should be supported automatically.

**Comment by lchunleo** [comment]
thanks for the response but the document for the function mentioned is meant to cast a Postgresql type to a python tuple. 

But what if the way round where i get the python tuple and need to update into the column of the table which of custom type?

**Comment by dvarrazzo** [comment]
As docs say:

> Adaptation from Python tuples to composite types is automatic instead and requires no adapter registration.

Your `studentinfo` field is an array of `bagtype`, so you should pass a list of tuples. Something like

```python
my_info = [(10,) (20,), (30,)]
cur.execute("UPDATE student SET studentinfo = %s::bagtype[] WHERE studentid = 1", (my_info,))
```

untested.
