### ISSUE TITLE
Inconsistency result in postresql with datetime comparison.

### ISSUE THREAD

**Issue by kimjj81** [psycopg/psycopg2#1222]
Hi.
I migrated postresql from mariadb some days ago.
I'm using django and  one command occurs an error after migration.
The most funny thing is that the code runs well in 'python manage.py shell' but it has an error in 'python manage.py COMMAND'

The seudo code is below :

Django 2.2.17
Amazon Linux
psycopg2-binary==2.8.6
python 3.7.9

```
from django.utils.timezone import now
from django.db.models import ExpressionWrapper, F, Q

Device :
 check_time = DateTimeField()

Config : 
 device = FKwith(Device)
 check_interval = IntField()

Device.objects.filter(check_time__lt=now()- \
  ExpressionWrapper(F('config__check_interval') * 1.5 * 1000000 * 60, output_field=DurationField()))


```

=> run 'python manage.py COMMAND'

```
django.db.utils.ProgrammingError: operator does not exist: timestamp with time zone - numeric
LINE 1: ...(('2021-01-13T10:56:23.282808+00:00'::timestamptz - (((U1."c...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


in postgresql error log
 (('2021-01-13T10:57:02.825366+00:00'::timestamptz - (((U1."check_interval" * 1.5) * 1000000) * 60)))))))
```

But it runs 'python manage.py shell' no error.

Thanks.

**Comment by dvarrazzo** [comment]
As the error says, there is no - or + operator between a timestamp and a number. What is on the right? Days, seconds, microseconds, or fortnights?

What postgres supports is the +/- operator between timestamps and timedelta objects (datetime.interval objects in Python): you should pass the right object as such. This has to be done at Django/aplication level: psycopg only converts Python objects back and forth in the database format. I think you should hear from some Django person to understand how to make sure that `ExpressionWrapper(F('config__check_interval') * 1.5 * 1000000 * 60, output_field=DurationField()))` passes a datetime.interval to psycopg.

**Comment by kimjj81** [comment]
Dear @dvarrazzo .

The main problem is " how to make sure that ExpressionWrapper(F('config__check_interval') * 1.5 * 1000000 * 60, output_field=DurationField())) passes a datetime.interval to psycopg.", right?

Thank you for your kind answer.

We all now have a hard time due to COVID-19.
I hope everything goes well.

p.s. I will close this issue within 3 days, hoping to another answer. :-)

**Comment by dvarrazzo** [comment]
@kimjj81 I have [asked around](https://twitter.com/psycopg/status/1349316581881425923) if some Djangoista can help you. Hope they can help you, and wish you all the best!
