### ISSUE TITLE
logicalreplication

### ISSUE THREAD

**Issue by apiszcz** [psycopg/psycopg2#1227]
The options format = JSON does not appear to be supported.

a.	cur.start_replication(slot_name = 'pytest', options={'format':'JSON'}, decode = True)

Is there test covering this option?

Thanks.

**Comment by dvarrazzo** [comment]
Psycopg only passes that value to the server. The error

InvalidParameterValue: option "format" = "JSON" is unknown
CONTEXT:  slot "pytest", output plugin "test_decoding", in the startup callback

says that indeed the option reaches the server alright, but the server doesn't know it.
