### ISSUE TITLE
Named variables

### ISSUE THREAD

**Issue by david-shiko** [psycopg/psycopg2#1228]
Hello. Everybody know option to add variableas as writen in the docs.
Sample (`cur.execute('SELECT a FROM b WHERE c = %s', ('sql_injection_secured_var',)`). 
But what about more readable variables? Something like
(`cur.execute('SELECT a FROM b WHERE c = %sql_injection_secured_var', ('sql_injection_secured_var',)`).
There a way to define it, maybe via postres variables?

**Comment by dvarrazzo** [comment]
Please read the manual

**Comment by david-shiko** [comment]
@dargor I found it, sorry for inconvenience
