### ISSUE TITLE
Pgpool-II  load balance invalid 

### ISSUE THREAD

**Issue by 363568233** [psycopg/psycopg2#1229]
pgsql 12
psycopg2 2.8.4
pgpool 3.7.10
pgsql  primare and standby mode

execute('/*NO LOAD BALANCED*/select * from t_test') first
then execute a sql without comment , the sql without comment load balance invalid,
it not a problem with JDBC, I guess it's a bug in psycopg2.

  import psycopg2
  
  conn = psycopg2.connect(dbname="dbtest", user="pgpool", password="pgpool", host=VIP, port="9999")
  
  with conn.cursor() as cur:
  
      for i in range(10):
  
          cur.execute('/*NO LOAD BALANCED*/select * from t_test')
  
          cur.execute("select * from t_test where name = 'qqq{}'".format(i)) # It is always routed to the primary database
  
  conn.close()

**Comment by dvarrazzo** [comment]
I don't know of this feature. Where does it come from?

**Comment by 363568233** [comment]
> I don't know of this feature. Where does it come from?

Pgpool-II  load balanced   https://www.pgpool.net/docs/pgpool-II-3.7.10/en/html/runtime-config-load-balancing.html

In SQLAlchemy with psycopg2 , there are similar problems but some differences
First  test with SQLAlchemy , second test with psycopg2 , last test with JDBC  
Only JDBC is completely correct

**Comment by dvarrazzo** [comment]
That page says

> the query must not be in an explicitly declared transaction (i.e. not in a BEGIN ~ END block) 

This means you will have to use psycopg2 in autocommit
