### ISSUE TITLE
cursor.rowcount attribute limited to max 2147483647

### ISSUE THREAD

**Issue by njesp** [psycopg/psycopg2#1232]
I have som large inserts executed by python 3.9.1 and psycopg2 2.8.5  cursor.execute and cursor.copy_expert, and lately they have reported in the log that have inserted exactly 2147483647 rows, when in fact they inserted a bit more. 

This looks like cursor.rowcount is limited by an 4 byte integer somewhere. I can't tell whether is a psycopg2 limitation or a libpq limitation. DB-API 2.0 in PEP 249 does not mention any limitations on rowcount. 

Either way, perhaps it is appropriate with a footnote in the documentation of cursor.rowcount menitioning the limitation 

Regards Niels Jespersen

**Comment by dvarrazzo** [comment]
It is [documented by the libpq](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQNTUPLES). Psycopg has a larger limit, which would come in use e.g. on executemany, if more than one result contributes to the same rowcount.
