### ISSUE TITLE
importing the psycopg2 module is slow

### ISSUE THREAD

**Issue by gtlawton** [psycopg/psycopg2#1233]
It takes about 30 seconds to import the module.

I wonder if that is normal.  I am using 

Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32

I installed the module using 

python -m pip install psycopg2

Any ideas as to what is missing?

**Comment by dvarrazzo** [comment]
No, it is not normal. But we cannot debug windows. It could be your antivirus as far as I know.

**Comment by gtlawton** [comment]
Strange as I am also using the cx_oracle module which loads immediately.

**Comment by gtlawton** [comment]
I upgraded from 3.7.4 to 3.9.1 and the issue seems to be resolved.  The module loads immediately.
