### ISSUE TITLE
Issue generating Confirmed Flush LSN value : xlog file gets shifted into segments 

### ISSUE THREAD

**Issue by pankajthadani** [psycopg/psycopg2#1237]
We are using logical replication slot to stream values to a flat file.

Assume the segments hex value length is 7 character eg : 2/3F42B70 
While sending the feedback to the cursor passing a decimal value 603204464 which is decimal representation of 23F42B70. But the same gets evaluated as 0/23F42B70 while acknowledging the slot, Due to this malformed generation of HEX value when we reconnect to read pending changes after a time interval we are rewriting the duplicate records onto a flat file.
This happens continuously until segments length is 8 characters, post that acknowledgement works fine.

Attached screenshots for the same.
1. LSN of last record retrievd using peek_logical_changes query

<img width="949" alt="Screenshot 2021-02-12 at 4 16 29 PM" src="https://user-images.githubusercontent.com/21331908/107773854-42cfbd80-6d64-11eb-9326-14f8acf55aa0.png">

2. Malformed replication slot confirmed flush LSN
<img width="915" alt="Screenshot 2021-02-05 at 12 58 55 PM" src="https://user-images.githubusercontent.com/21331908/107773856-42cfbd80-6d64-11eb-89d8-cdb0c4b563cc.png">

**Comment by dvarrazzo** [comment]
Hello @pankajthadani thank you for your report.

I am not entirely familiar with replication, however I believe that you should be passing `2/03F42B70` to mean what you mean:

```
piro=# select '0/23F42B70'::pg_lsn - '0/0'::pg_lsn;
+-----------+
| ?column?  |
+-----------+
| 603204464 |
+-----------+
(1 row)

piro=# select '2/3F42B70'::pg_lsn - '0/0'::pg_lsn;
+------------+
|  ?column?  |
+------------+
| 8656268144 |
+------------+
(1 row)
```

**Comment by dvarrazzo** [comment]
Do I understand correctly that the bug is on your side, as you are passing 603204464 when you should be passing 8656268144, or it is psycopg2 which formats the value wrong?

**Comment by pankajthadani** [comment]
The logic at my end is to remove the / and then convert it to decimal, Lemme try prefixing it with 0 if the segment length is less than 8.
Will try this and get back. 
Thanks @dvarrazzo  for the prompt response

**Comment by pankajthadani** [comment]
@dvarrazzo Thanks i was able to convert to the expected LSN value by adding 0 as prefix in segment section .
