### ISSUE TITLE
Consider limited API abi3 manylinux wheels for Linux

### ISSUE THREAD

**Issue by nanonyme** [psycopg/psycopg2#1238]
Currently Linux consumers either need to install psycopg2 from package manager or install a compiler and PostgreSQL development stack. Have you considered shipping https://www.python.org/dev/peps/pep-3149/ + https://www.python.org/dev/peps/pep-0599/ style wheels? It might not as significantly increase amount of needed wheels now anymore as Python 2  and Python 3.5 (and below are EOL). All one needs is wheel targeting Python 3.6+ ABI.

**Comment by dvarrazzo** [comment]
It would be fine for me to target the `manylinux2014` tag. I won't have a lot of time in my hands to take care of the required changes though: if you or anyone else interested would like to send the relevant changes (probably against the https://github.com/psycopg/psycopg2-wheels repos) I would be happy to accept them.

**Comment by dvarrazzo** [comment]
New packags (psycopg 2.9) will be released as [PEP 600](https://www.python.org/dev/peps/pep-0600/) wheels. If you would like to test them, some are [available here](https://github.com/psycopg/psycopg2/actions/runs/879100172).
