### ISSUE TITLE
Support bit string operators

### ISSUE THREAD

**Issue by hurcy** [psycopg/psycopg2#1239]
Hi,

I have bit(10) column and want to update it using bitwise operator.
e.g. 
```
from sqlalchemy.dialects.postgresql import BIT
Mytable = db.Table(
  db.Column(ColumnLabel.EVENT_TYPE.value, BIT(10), nullable=False)
)

q1 = db.session.query(
    (Mytable.c.event_type | cast(8, BIT(10))
)

q2 = db.session.query(
    or_(Mytable.c.event_type,  cast(8, BIT(10))
)
```

Both queries compiled to `select event_type OR CAST(8 AS BIT(10))`, which is not correct. 
Could you tell me how to compile those queries with `|` operator?

**Comment by dvarrazzo** [comment]
I'm afraid no: you should ask this question to SQLAlchemy. I don't know much about it.
