### ISSUE TITLE
Where is the SQLSTATE diagnostic attribute updated from ?

### ISSUE THREAD

**Issue by mat100payette** [psycopg/psycopg2#1240]
In the C libs, I'm trying to figure out where the SQLSTATE code is updated from (which then maps to Postgresql errors and gives it to python).

If anyone could explain to me where that value comes from initially that'd be really appreciated.

I know that in `pq_raise(...)`, either `pgres` or `curs` should have it, but I can't seem to trace these further.

**Comment by dvarrazzo** [comment]
It comes from `PQresultErrorField`, if I understand correctly your question? It is read from the libpq error here and attached in this function to the `Error` object.

https://github.com/psycopg/psycopg2/blob/f469331af5f7b236f8037b302b69c2bf0df2a096/psycopg/pqpath.c#L118-L124

**Comment by mat100payette** [comment]
Ahh okok so in `PQresultErrorField(*pgres, PG_DIAG_SQLSTATE)` the attribute comes directly from libpq, correct ?

I'm super new to Postgresql so I didn't quite understand where the gap between your lib and theirs was.

**Comment by dvarrazzo** [comment]
Yes, it comes from the libpq. The libpq receives it from the server, [as part of its response](https://www.postgresql.org/docs/current/protocol-error-fields.html). I don't know if there is any error that the libpq generates itself client-side and to which it attached a SQLSTATE code, I've never checked. Psycopg never does it: if a code is exposed there it means it came from the libpq.
