### ISSUE TITLE
psycopg2.connect v slow from 2.85 (Windows 10)

### ISSUE THREAD

**Issue by exrich** [psycopg/psycopg2#1242]
I have a problem with a very slow connection using psycopg2.connect from version 2.85 onwards.

psycopg2.connect() using v 2.84 is instantaneous
psycopg2.connect() using v 2.85 (and 2.86) takes about 4 secs.

I'm running the commands on the same db using the same parameters.  I've checked Python 3.7 and 3.8 using a clean env with just psycopg2 and dependencies installed with the issue persisting.  Installation is on Windows 10 using conda package and connection is to a local Linux machine.

2.85 package list
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py38haa95532_0
krb5                      1.17.1               hc04afaa_0
libpq                     12.2                 h3235a2c_0
openssl                   1.1.1j               h2bbff1b_0
pip                       21.0.1           py38haa95532_0
psycopg2                  2.8.5            py38hcd4344a_1
psycopg2-binary           2.8.5                    pypi_0    pypi
python                    3.8.5                h5fd99cc_1
setuptools                52.0.0           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
tk                        8.6.10               he774522_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4

2.84 package list
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py38haa95532_0
krb5                      1.16.4               hc04afaa_0
libpq                     11.2                 h3235a2c_0
openssl                   1.1.1j               h2bbff1b_0
pip                       21.0.1           py38haa95532_0
psycopg2                  2.8.4            py38h7a1dbc1_0
python                    3.8.5                h5fd99cc_1
setuptools                52.0.0           py38haa95532_0
sqlite                    3.33.0               h2a8f88b_0
tk                        8.6.10               he774522_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4

**Comment by exrich** [comment]
Just tested on a Linux machine and 2.8.5 connects just as quickly so this appears to be Windows specific.

**Comment by dvarrazzo** [comment]
How are you connecting/authenticating? Maybe some difference in kerberos? OpenSSL is the same version.

**Comment by exrich** [comment]
This is my connection string.

psycopg2.connect(database=test, host="10.64.0.7", port="5432", user=test, password=*******)

Not sure if it makes any difference but the PostgreSQL version of the db is 12 and it's just a standard install with the stock defaults.

**Comment by dvarrazzo** [comment]
I don't see anything in the NEWS file and in the git log which might explain the difference.

The main difference I see is the different version of the libpq. I don't know if anything changed from 11.2 to 12.2 which might explain the difference.

**Comment by exrich** [comment]
I've figured out the issue.  Analyzing the packets showed a 4-5 second gap with the last packet sent being a 'gssenc encrypt request' which was rejected by my local server. So what must have happened is the default on gssenc changed from 'disable' to 'prefer'.  Anyway, setting the gssencmode='disable' in my connection options fixed the issue.

I suggest making this the default option for psycopg2

**Comment by dvarrazzo** [comment]
Thank you very much, I appreciate you looking into it :+1: 

This is not a choice psycopg does: it must be a change in behaviour between libpq versions. Maybe it's worth asking on pgsql-general or -hackers what really changed.

Psycopg doesn't inject any value to the parameter string, it only passes the values to the libpq. If the choice they made is unwise it should be changed in the libpq, not in psycopg.

**Comment by yhoiseth** [comment]
I had the same issue, with connection taking 60 secs. Using Django, the solution was to add the following option:
```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # …
        "OPTIONS": {
            'gssencmode': 'disable',
        },
    }
}
```
Thank you for sharing your solution. It probably saved me hours of troubleshooting!
