### ISSUE TITLE
connect() should accept no parameters

### ISSUE THREAD

**Issue by hginzel** [psycopg/psycopg2#1250]
I am reopening issue https://github.com/psycopg/psycopg2/issues/767 – Connect() with environment/defaults and no parameters.
The solution with empty string does not work for [`parse_dsn()`](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.parse_dsn).
The string `postgres://` is vaild uri, see [libpq connect](https://www.postgresql.org/docs/current/libpq-connect.html).

```python
>>> d = psycopg2.connect(**parse_dsn('postgres://'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 124, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters
>>> d = psycopg2.connect(**parse_dsn(''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 124, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters
>>> db = psycopg2.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 124, in connect
    raise TypeError('missing dsn and no parameters')
TypeError: missing dsn and no parameters
```

**Comment by Florents-Tselai** [comment]
I think this should be reopened, as it wasn't included in a release.
https://github.com/psycopg/psycopg2/commit/391386cfb9efb277813bb6b53d727497b642dd97#commitcomment-58984561

For me both `connect("")` and `connect()` fail, even if PG* env vars are set.

 `psycopg2.__version__=='2.9.1 (dt dec pq3 ext lo64)'`

**Comment by dvarrazzo** [comment]
@Florents-Tselai you must be doing something wrong, because most definitely it works.

```python
>>> import psycopg2
>>> psycopg2.connect()
<connection object at 0x7f2c17fad040; dsn: '', closed: 0>
>>> psycopg2.__version__
'2.9.1 (dt dec pq3 ext lo64)'
```

In the form `connect("")` it works since circa 2004.

**Comment by Florents-Tselai** [comment]
You're right, my bad. I'd messed my env vars :)
