### ISSUE TITLE
Official PostgreSQL 13 support?

### ISSUE THREAD

**Issue by dlpgp** [psycopg/psycopg2#1256]
As of 2.8.6, the highest PostgreSQL version supported is 12 according to the prerequisites documentation. Is there a version coming out officially supporting PostgreSQL 13?

Docs: https://www.psycopg.org/docs/install.html#prerequisites

**Comment by dvarrazzo** [comment]
PostgreSQL 13 is supported no problem :slightly_smiling_face:
