### ISSUE TITLE
Unable to Install 2.8.6 on Python 3.6

### ISSUE THREAD

**Issue by alexdavis24** [psycopg/psycopg2#1258]
I need to install Pyscopg2 2.8.6 on a Python 3.6 Miniconda environment. When running `python -m pip install psycopg2
`, pip installs 2.7.7. I tried running `pip install pyscopg2==2.8.6` and received "ERROR: Could not finda version that satisfies the requirement pyscopg2==2.8.6 ERROR: No matching distribution found for psycopg2==2.8.6".

pg_config is installed in ./bin/pg_config. I am running Ubuntu 18.04 and pip 21.0.1.

Is 2.8.6 not compatible with Python 3.6? Is there another issue that I am missing? Apologies if this is something basic.

**Comment by Jeroendevr** [comment]
I think a similar issue occurs when installing with Python 3.9

`ERROR: Command errored out with exit status 1:
     command: /Users/jeroendevries/Programming/LazyBlacksmith/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-install-xw9nlhx2/psycopg2_d7254deed142410596f1f93fae0bcd82/setup.py'"'"'; __file__='"'"'/private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-install-xw9nlhx2/psycopg2_d7254deed142410596f1f93fae0bcd82/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8
         cwd: /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-install-xw9nlhx2/psycopg2_d7254deed142410596f1f93fae0bcd82/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8/psycopg2.egg-info
    writing /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/4t/3kc42sfx7yldm7kqb56xzlc40000gp/T/pip-pip-egg-info-n8em2hf8/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fd/ae/98cb7a0cbb1d748ee547b058b14604bd0e9bf285a8e0cc5d148f8a8a952e/psycopg2-2.8.6.tar.gz#sha256=fb23f6c71107c37fd667cb4ea363ddeb936b348bbd6449278eb92c189699f543 (from https://pypi.org/simple/psycopg2/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2==2.8.6
ERROR: No matching distribution found for psycopg2==2.8.6`

**Comment by Jeroendevr** [comment]
Meanwhile I have the pg_config error fixed by installing postgresql correctly, in my case using Home-brew for Mac. Still not able to install, but I think my current issue is not relevant any more to this issue.

**Comment by dvarrazzo** [comment]
Psycopg 2.8.6 works fine with Python 3.6-3.9. No idea what miniconda does. You should ask them I guess.
