### ISSUE TITLE
Psycopg2 cannot be installed in the Windows virtualenv but can install through terminal

### ISSUE THREAD

**Issue by RENJITHVS** [psycopg/psycopg2#1260]
I tried to install Psycopg2-binary in my VirtualEnv. Initially, I encountered an error and could not find pg_config.exe. I solved it by adding the full path to the PATH.

However, an error occurred subsequently, and Microsoft Visual C++ 14.0 was required. To delete this file, I have installed VC_redist.x64 VC_redist.x86.

I also installed the C++ development module in the VS community. But it still shows this error and
I also downloaded and installed the VS build tool 

Terminal shows
> build\lib.win32-3.8\psycopg2\_psycopg.cp38-win32.pyd : fatal error LNK1120: 83 unresolved externals error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120

    ----------------------------------------

>Command ""C:\Users\user\Desktop\C R M\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-zugo63lv\\psycopg2-binary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-record-1zny7pcb\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\user\Desktop\C R M\venv\include\site\python3.8\psycopg2-binary"" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-zugo63lv\psycopg2-binary\

**Comment by dvarrazzo** [comment]
Why are you compiling psycopg for windows? There are binary packages.

**Comment by RENJITHVS** [comment]
I  use psycopg-binary as an adapter to connect my Django with the PostgreSQL database.

**Comment by dvarrazzo** [comment]
Sure, and it works too. I cannot debug your virtualenv though. Try recreating it from scratch, make sure that pip is up-to-date, and reinstall it.

**Comment by RENJITHVS** [comment]
Anyway it works after system restart. Thnks
