### ISSUE TITLE
Package psycopg2 version 2.8.6 install unusable on macOS BigSur 11.2.3 (Intel) Python 3.8.9 AND 3.9.0

### ISSUE THREAD

**Issue by dcs3spp** [psycopg/psycopg2#1261]
Following the recommendation from the documentation I am specifying psycopg2 dependency instead of psycopg2-binary, for use in production.

I am running on the following environment:
OS: MacOS: BigSur 11.2.3 (Intel)
Python Version: 3.9.0

I have installed psycopg2 dependency in Python 3.9.0 virtual environment. 
Before installing I have the following environment variables set:
LD_LIBRARY_PATH=/Library/PostgreSQL/9.6/lib
PATH includes /Library/PostgreSQL/9.6/bin

I install from the requirements.txt file below, e.g. ```pip install --no-cache-dir -r requirements.txt```
The install is successful, however it is unusable, e.g. ```python -c "import psycopg2" yields....

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/simon/Development/python-virt-envs/flasker/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/simon/Development/python-virt-envs/flasker/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 2): Library not loaded: libpq.5.dylib
  Referenced from: /Users/simon/Development/python-virt-envs/flasker/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so
  Reason: image not found
```

The documentation states that supported Python versions are from 3.4 to 3.8.  Presumably Python 9 is currently incompatible with psycopg2 on MacOS?

I have installed Python 3.8.9 via pyenv and installed the same packages (see below) and received the same message.

```console
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/simon/.pyenv/versions/flasker/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/simon/.pyenv/versions/flasker/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 2): Library not loaded: libpq.5.dylib
  Referenced from: /Users/simon/.pyenv/versions/flasker/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so
  Reason: image not found
```

Has anyone managed to get a stable setup working for psycopg2 working on macOS BigSur 11.2.3 Intel?

I am currently in the process of trying it out on macOS Catalina....

**requirements.txt**
```console
attrs==20.3.0
    # via jsonschema
click==7.1.2
    # via flask
flasgger==0.9.5
    # via -r requirements.in
flask-sqlalchemy-session==1.1
    # via -r requirements.in
flask==1.1.2
    # via
    #   -r requirements.in
    #   flasgger
    #   flask-sqlalchemy-session
greenlet==1.0.0
    # via sqlalchemy
itsdangerous==1.1.0
    # via flask
jinja2==2.11.3
    # via flask
jsonschema==3.2.0
    # via flasgger
markupsafe==1.1.1
    # via jinja2
marshmallow-jsonapi==0.24.0
    # via -r requirements.in
marshmallow-sqlalchemy==0.24.2
    # via -r requirements.in
marshmallow==3.11.1
    # via
    #   marshmallow-jsonapi
    #   marshmallow-sqlalchemy
mistune==0.8.4
    # via flasgger
psycopg2==2.8.6
    # via -r requirements.in
pyrsistent==0.17.3
    # via jsonschema
pyyaml==5.4.1
    # via flasgger
six==1.15.0
    # via
    #   flasgger
    #   jsonschema
sqlalchemy==1.4.7
    # via
    #   flask-sqlalchemy-session
    #   marshmallow-sqlalchemy
werkzeug==1.0.1
    # via
    #   flask
    #   flask-sqlalchemy-session
```

**Comment by dvarrazzo** [comment]
See #1200

**Comment by dcs3spp** [comment]
@dvarrazzo After reading [#1200](https://github.com/psycopg/psycopg2/issues/1200), that is for ARM M1 and seems to recommend psycopg2-binary. I am using macOS BigSur Intel and psycopg2, as recommended by the psycopg2 docs for production environment.
