### ISSUE TITLE
psycopg2 2.8.6 installs and fails on macOS Catalina 10.15.7 with Postgres.App v10.1 installed

### ISSUE THREAD

**Issue by dcs3spp** [psycopg/psycopg2#1262]
Hi,

I have read [issues](https://github.com/psycopg/psycopg2/issues/1200) encountered with developers struggling to get psycopg2 working on macOS BigSur ARM environments. I updated to the laptop to BigSur and also encountered problems. However, luckily I did not upgrade the desktop running Catalina 10.15.7. However, I am still encountering issues. Previously I had psycopg2-**binary** 2.8.1 working in this environment with Python 3.6.
 
However, reading the psycopg2 documentation, psycopg2-binary does not appear to be recommended for production, so tried installing **psycopg2**....

Using with a pyenv virtual environment for Python 3.8.2.
PostgreSQL 10.1 client and server installed.
Receive Symbol not found: "_P    QencryptPasswordConn" because it is expecting libq.5 to be installed at /usr/lib/libpq.5.dylib.

How do I instruct pip install build of psycopg2 to use the LIB DIR listed in pip_config? Does psycopg2 not do this automatically?

N.B before installing.... pg_config is accessible from path
```console
$ pg_config

BINDIR = /Library/PostgreSQL/10/bin
DOCDIR = /Library/PostgreSQL/10/doc/postgresql
HTMLDIR = /Library/PostgreSQL/10/doc/postgresql
INCLUDEDIR = /Library/PostgreSQL/10/include
PKGINCLUDEDIR = /Library/PostgreSQL/10/include/postgresql
INCLUDEDIR-SERVER = /Library/PostgreSQL/10/include/postgresql/server
LIBDIR = /Library/PostgreSQL/10/lib
PKGLIBDIR = /Library/PostgreSQL/10/lib/postgresql
LOCALEDIR = /Library/PostgreSQL/10/share/locale
MANDIR = /Library/PostgreSQL/10/share/man
SHAREDIR = /Library/PostgreSQL/10/share/postgresql
SYSCONFDIR = /Library/PostgreSQL/10/etc/postgresql
PGXS = /Library/PostgreSQL/10/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-icu' '--prefix=/mnt/hgfs/pginstaller.auto/server/staging_cache/osx.build' '--with-ldap' '--with-openssl' '--with-perl' '--with-python' '--with-tcl' '--with-bonjour' '--with-pam' '--enable-thread-safety' '--with-libxml' '--with-uuid=e2fs' '--with-includes=/opt/local/Current/include/libxml2:/opt/local/Current/include:/opt/local/Current/include/security' '--docdir=/mnt/hgfs/pginstaller.auto/server/staging_cache/osx.build/doc/postgresql' '--with-libxslt' '--with-libedit-preferred' '--with-gssapi' 'CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8 -arch i386 -arch x86_64 -O2' 'LDFLAGS=-L/opt/local/Current/lib' 'ICU_CFLAGS=-I/opt/local/Current/include' 'ICU_LIBS=-L/opt/local/Current/lib -licuuc -licudata -licui18n'
CC = gcc
CPPFLAGS = -DFRONTEND -I/opt/local/Current/include -I/opt/local/20151229/include/libxml2 -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8 -arch i386 -arch x86_64 -O2
CFLAGS_SL =
LDFLAGS = -L../../src/common -L/opt/local/Current/lib -L/opt/local/20151229/lib -Wl,-dead_strip_dylibs
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lm
VERSION = PostgreSQL 10.1
```

I have included the installation steps below

**pip install --no-cache-dir psycopg2 output**
```console
$ pyenv activate flaskapp
$ pip list

Package    Version
---------- -------
pip        21.0.1
setuptools 56.0.0
wheel      0.34.2

$ pip install --no-cache-dir psycopg2

Collecting psycopg2
  Downloading psycopg2-2.8.6.tar.gz (383 kB)
     |████████████████████████████████| 383 kB 2.8 MB/s 
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.8.6-cp38-cp38-macosx_10_15_x86_64.whl size=136410 sha256=b82d3feabdc691dbaaca43088529fe3fc9443592222989de8effdf56f9e1ac80
  Stored in directory: /private/var/folders/h5/k56b8xzj3cbbx4b3_rnmq2_00000gn/T/pip-ephem-wheel-cache-cyha2uws/wheels/70/5e/69/8a020d78c09043156a7df0b64529e460fbd922ca065c4b795c
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.8.6
```

**Library dependencies of pyscopg.so**
```console
otool -L  _psycopg.cpython-38-darwin.so:

_psycopg.cpython-38-darwin.so:
	libpq.5.dylib (compatibility version 5.0.0, current version 5.10.0)
	libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

```

**Log output when import psycopg2 library**
```console
$ export DYLD_LIBRARY_PATH=/Library/PostgreSQL/10/lib
$ export LD_LIBRARY_PATH=/Library/PostgreSQL/10/lib
$ python -c "import psycopg2"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 2): Symbol not found: _PQencryptPasswordConn
  Referenced from: /Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so
  Expected in: /usr/lib/libpq.5.dylib
```

Looking at the installation log after installation of psycopg2 (with pg_config accessible from the path as shown above) it looks as psycopg2 expects the libraries at a fixed location of /usr/lib/libpq.5.dylib. 

I also tried using pip option ```--global-option=build_ext``` to try and set the library location during installation as follows:

```console
pip install --no-cache-dir --global-option=build_ext \
--global-option="-L/Library/PostgreSQL/10/lib" psycopg2==2.8.6
/Users/simon/.pyenv/versions/3.8.2/envs/flaskapp/lib/python3.8/site-packages/pip/_internal/commands/install.py:230: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting psycopg2==2.8.6
  Downloading psycopg2-2.8.6.tar.gz (383 kB)
     |████████████████████████████████| 383 kB 2.9 MB/s 
Skipping wheel build for psycopg2, due to binaries being disabled for it.
Installing collected packages: psycopg2
    Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.8.6

$ python -c "import psycopg2"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 2): Symbol not found: _PQencryptPasswordConn
  Referenced from: /Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so
  Expected in: /usr/lib/libpq.5.dylib
 in /Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so
```

How do I instruct pip install build of psycopg2 to use the LIBDIR listed in pg_config? Does psycopg2 not inspect LIBDIR during build and installation?

**Comment by dvarrazzo** [comment]
It seems you have a mishmash of libraries and header files for the postgres library.

I cannot provide advice on M1: it is an OS I don't own and too much of an unstable environment to make prediction, combined with all the different ways to install Python and Postgres and all the inconsistent places where li8braries can go.

This software is provided as it is. The source works at the best of our knowledge. It employs standard methods to find its build and runtime dependencies: if you platform breaks these methods, it is your provider's responsibility to fix the problem.

You can try and use psycopg3 in pure Python mode, provided the libpq library in installed in a way that ctypes can find.

**Comment by dcs3spp** [comment]
Hi @dvarrazzo, thanks for responding.

This install is on macOS Catalina Intel, not M1.
I previously tried on laptop running macOS BigSur (Intel) which is running PostgreSQL 9.6
 
This install is on macOS Catalina Intel running PostgreSQL 10.1. No other postgreSQL database is installed in this environment.

My question is...
Does the build and install of psycopg2 use LIBDIR of pg_config to search for libq library location?

The issue seems to be that no matter how I try to pip install psycopg2 once it has built it seems to look for libpq library at /usr/lib. On this environment libq library is at a different location /Library/PostgreSQL/10/lib.

So....how do I instruct psycopg2 build to /Library/PostgreSQL/10/lib instead of the fixed location of /usr/lib. The answer to that question will likely fix the issue. It may also help others encountering similar issue, possibly solving some of the issues logged with M1 when building from source???

**Comment by dvarrazzo** [comment]
Psycopg uses pg_config to find the libraries at build time, then it uses whatever the OS knows to find the library at runtime. If the two versions don't agree you have a misconfiguration on your machine which I cannot solve.

**Comment by dcs3spp** [comment]
Ok cheers @dvarrazzo, appreciated...

hmmmm so yep I can see it must be picking up [LIBDIR](https://github.com/psycopg/psycopg2/blob/f469331af5f7b236f8037b302b69c2bf0df2a096/setup.py#L411) to be able to do a build successfully....

So somehow, somewhere it is changing it to /usr/lib/libpq.5.so due to something that it is inspecting from the OS during an import at rune.... ```pg_config``` output above has ```LIBDIR``` set to ```/Library/PostgreSQL/10/lib``` but that is only inspected at buildtime...

When I do an import at runtime it changes to /usr/libpq.5.so...

> then it uses whatever the OS knows to find the library at runtime

By whatever the OS knows...do you mean that it inspects environment variables such as LD_LIBRARY_CONFIG, DYLD_FALLBACK_LIBRARY_PATH?? 

If I can figure how to make OS report /Library/PostgreSQL/10/lib instead of /usr/lib that would hopefully solve the issue......

**Comment by dcs3spp** [comment]
Yes!!!! @dvarrazzo, I think I have it sorted.....

````sudo install_name_tool -change libpq.5.dylib  /Library/PostgreSQL/10/lib/libpq.5.dylib /Users/simon/.pyenv/versions/flaskapp/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so``` 

On macOS Catalina ```install_name_tool``` can be used to change location of a dynamic library. It used to be that this was done using env vars ```LD_LIBRARY_CONFIG```, ```DYLD_LIBRARY_PATH``` or ```DYLD_FALLBACK_LIBRARY_PATH```. I was setting these and still receiving the same issue....

Now when I do ```python -c import psycopg2``` it is successful......

Not sure if this might help anyone installing and building pyscopg2 on macOS M1 bigSur.....but after doing this  it got me up and running....

This method means that if I install psycopg2 in another virtual environment it would have to be updated again to with install_name_tool....not sure if there is a better way?

N.B on doing an ```ls /usr/lib``` I see that there is  libpq.5.6.dylib* and libpq.5.dylib@. Not sure what is using them but I'm leaving them there untouched!!!!

**Comment by dcs3spp** [comment]
Ok, think I have solved it and summarising in the hope that it helps others encountering issues while importing ```psycopg2``` package on macOS and receiving *symbol not found* errors for *libpq*.
 
```pscycopg2``` uses the ```pg_conf``` tool at build time to inspect the *LIBDIR* environment variable for the location of the *libpq* library for linking during the build process.

Now, on my macOS Catalina environment there are unfortunately 2 versions of ```libpq``` installed:

/Library/PostgreSQL/10/lib/libpq.5.dylib -> links to /Library/PostgreSQL/10/lib/libpq.5.10.dylib
/usr/lib/libpq.5.dylib -> links to /usr/lib/libpq.5.6.dylib

I suspect that /usr/lib/5.6.dylib was left over from an old previous PostgreSQL 9 installation?? 

The error described in this issue was occurring when importing ``psycopg2```. This is because at runtime it was linking to ```/usr/lib/libpq.5.6.dylib```. This is an older library than the one that ```pyscopg2``` was built with, i.e.  /Library/PostgreSQL/10/lib/libpq.5.10.dylib. During the python import of ```psycopg2``` the OS was inspected to determine the locations of shared libraries required by the psycopg2 library, ```_psycopg.cpython-38-darwin.so```:

```console
_psycopg.cpython-38-darwin.so:
	libpq.5.dylib (compatibility version 5.0.0, current version 5.10.0)
	libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
``` 

The OS was inspected for the locations of shared libraries and correctly identified and discovered /usr/lib/libq.5.dylib in the standard location of /usr/lib.

New versions of macOS enable system integrity protection per default. This means that setting the environment variables ```DYLD_LIBRARY_PATH``` and ```LD_LIBRARY_PATH``` with paths of additional shared libraries will have no effects.
Furthermore, in macOS Catalina I cannot easily alter files in /usr/lib, receiving ```operation not permitted```.
 
So......the ```install_name_tool``` can be used to change location of dynamic libraries referenced by a library or executable, as described above. However, I could only get this working as a temporary measure. If I am developing within a virtual environment and refresh dependencies in dev.txt / requirements.txt etc. I have to repeat the process of using ```install_name_tool``` again, every time.

Therefore, the next step was to add a symlink in ```/usr/local/lib/libpq.5.dylib``` to the library in ```/Library/PostgreSQL/10/lib```. Now, I can remove and reinstall ```psycopg2``` in the virtual environment as many times as I want while developing and there is no need to keep using ```install_name_tool```. I am also going to try and figure out how to remove the ```libpq``` from /usr/lib.....

When ```psycopg``` inspects the OS to find the shared libraries it needs, it now picks up the ```libpq``` in /usr/local/lib that matches the version that it was built with. See [here](https://github.com/psycopg/psycopg2/issues/671#issuecomment-363060483) for more information.

Looking though previous issues I discovered another method for reading a discussion with another developer who had experienced something [similar](https://github.com/psycopg/psycopg2/issues/378). It is possible to specify build flags, (including *rpath*) for a python library as mentioned [here](https://github.com/psycopg/psycopg2/issues/378#issuecomment-161922107). 

With ```pip``` this can be specified using ```build_ext``` global options as mentioned [here](https://izziswift.com/python-pip-specify-a-library-directory-and-an-include-directory/). I am not sure if this would work with using pip to install a list of dependencies in requirements.txt, I have not tried yet. Anyway, essentially, a Python library can be built with an ```rpath``` option that specifies the location of dependencies for use and inspection at runtime. This way ```psycopg2``` will link to the same ```libpq``` library that it used during the build process, avoiding symbol not found errors.....

Not sure if this could be done in future versions of psycopg2 library? or is it safer to be done by the developers that are installing ```psycopg2``` library?
