### ISSUE TITLE
psycopg2-binary requires full PostgreSQL Server install on Windows to run egg_info

### ISSUE THREAD

**Issue by TravisDart** [psycopg/psycopg2#1264]
I have a project on Windows that uses psycopg2-binary, and I was getting an error when installing psycopg2-binary using pipenv:
`pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1`

I downloaded the psycopg2-binary 2.8.6 source code and ran `egg_info` but got this error:

```
> python setup.py egg_info
running egg_info
writing psycopg2.egg-info\PKG-INFO
writing dependency_links to psycopg2.egg-info\dependency_links.txt
writing top-level names to psycopg2.egg-info\top_level.txt
error: [WinError 2] The system cannot find the file specified
```

The package itself installs without issue using pip. It's just `egg_info` that causes an error and causes pipenv to be unable to install the package.

I had only the PostgreSQL command-line tools installed when I got this error. However, when I installed the PostgreSQL server, the command ran successfully. I can install with pipenv and run `python setup.py egg_info` without issue.

It's my understanding that the point of the binary release was so additional libraries didn't have to be installed, so ideally it shouldn't be a requirement that the PostgreSQL server be installed for the psycopg2-binary package to fully function. - At a minimum, the error should be handled more gracefully. The error message is pretty opaque.

I'm not 100% sure what is causing this error. From a cursory look through the psycopg2 source code, I see it looks for `pg_config`, and I can confirm that `pg_config` was not installed on my system until I installed the full PostgreSQL server. Again, I didn't take a close look, but wanted to report the bug.

Hope that helps.

**Comment by dvarrazzo** [comment]
Psycopg is designed and tested to be installed with pip. If pipenv doesn't work I think it is a problem on their part.

The code of the setup.py is shared between both the psycopg2 and the psycopg2-binary packages. There are also valid reasons why installing from source (requiring to have the preconditions met) is a valid thing for psycopg2-binary. However this is never the case on windows: we don't assume windows users to have the requirements on their machines to build psycopg2. On windows, both the packages install without needing building and prerequisites: you should check with the pipenv developers why their project fails to do so.

**Comment by TravisDart** [comment]
Thanks for reviewing this issue so quickly.

I agree that pip is the standard way to install, but issue isn't with pipenv, per se. The issue is the `python setup.py egg_info` command, which I would think would also fall under the umbrella of standard functionality.

If setup.py is shared between both projects, perhaps it could throw a less-puzzling error when the PostgreSQL server isn't installed.
