### ISSUE TITLE
2.8.6: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [psycopg/psycopg2#1271]
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, cov-2.11.1, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, flaky-3.7.0, mock-3.6.0, hypothesis-6.12.0, asyncio-0.15.1, toolbox-0.5
collected 791 items / 1 error / 790 selected

================================================================================== ERRORS ==================================================================================
_______________________________________________________________ ERROR collecting tests/test_async_keyword.py _______________________________________________________________
/usr/lib/python3.8/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
/usr/lib/python3.8/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:161: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:354: in _rewrite_test
    tree = ast.parse(source, filename=fn_)
/usr/lib64/python3.8/ast.py:47: in parse
    return compile(source, filename, mode, flags,
E     File "/home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6/tests/test_async_keyword.py", line 46
E       self.conn = self.connect(async=True)
E                                ^
E   SyntaxError: invalid syntax
========================================================================= short test summary info ==========================================================================
ERROR tests/test_async_keyword.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 1.00s =============================================================================
```

**Comment by kloczek** [comment]
OK . Thx

**Comment by kloczek** [comment]
May I ask for some help?
Looks like something is missing in my env 🤔 
```console
[tkloczko@ss-desktop psycopg2-binary-2.8.6]$ make check
PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6/build/lib.3.8 python -c "import tests; tests.unittest.main(defaultTest='tests.test_suite')" --verbose
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6/tests/__init__.py", line 35, in <module>
    from . import test_async
  File "/home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6/tests/test_async.py", line 36, in <module>
    from .testutils import (ConnectingTestCase, StringIO, skip_before_postgres,
  File "/home/tkloczko/rpmbuild/BUILD/psycopg2-binary-2.8.6/tests/testutils.py", line 41, in <module>
    from psycopg2.compat import PY2, PY3, string_types, text_type
ModuleNotFoundError: No module named 'psycopg2.compat'
make: *** [Makefile:66: check] Error 1
```
I cannot find psycopg2.compat in `psycopg2` and on pypi I don't see anything like that.

**Comment by dvarrazzo** [comment]
In 2.8.6 there was a `lib/compat.py` module. It was dropped in 2.9 as we dropped Python 2.7 compatibility. After building with `make` you should find it in the `psycopg2` package built inside your `psycopg2-binary-2.8.6/build/lib.3.8` directory. I'm not sure about why it doesn't happen on your machine: if it's there and not found or if there is a mismatch of versions somewhere.

**Comment by kloczek** [comment]
Python 2.x support is already EOSed .. 🤔 
is it possible to update `psycopg2-binary` for latest `psycopg2`?

**Comment by dvarrazzo** [comment]
I don't know what you are asking, sorry.

**Comment by kloczek** [comment]
Thing is that (as you wrote) current test suite cannot be used with latest `psycopg2` because missing lib/compat.py which is for python 2.x.
This is why I wrote that it would be good to update `psycopg2-binary` for latest `psycopg2`😄

**Comment by dvarrazzo** [comment]
Psycopg2-binary for the last psycopg2 version is here: https://pypi.org/project/psycopg2-binary/ Sono don't quite understand what you would like to do

**Comment by kloczek** [comment]
Just found what is going on.
Looks like there are two modules which provides exactly the same content `psycopg2` and `psycopg2-binary`, I've packaged both to only find ion install time that both are providing exactly the same content.
Some modules requires `psycopg2` and some `psycopg2-binary` (for example `aiopg`) so I've started fixing that to have only packaged `psycopg2` and patch all modules which require `psycopg2-binary`  to use in install time dependencies only `psycopg2`.

**Comment by dvarrazzo** [comment]
I understand. We have advised to avoid to use psycopg2-binary precisely for this reason, unfortunately not every project does the same and python packaged metadata don't allow to declare that two distribution packages both provide the same module, or that a package depends on either A or B.

It would be useful if you could report the problem upstream and discourage packages to depend on -binary. It would be actually better if they didn't depend on either and let e.g. the package depending on aiopg to choose if they depend on source or binary psycopg2.

Going forward, psycopg3 shouldn't have the same problem, but I don't see a way to fix it in psycopg2 within the current packaging framework.

**Comment by kloczek** [comment]
> I understand. We have advised to avoid to use psycopg2-binary precisely for this reason, unfortunately not every project does the same and python packaged metadata don't allow to declare that two distribution packages both provide the same module, or that a package depends on either A or B.

OK so I'll try to use what you just wrote to add corrections s/psycopg2-binary/psycopg2/😄
Thank you.
