### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [psycopg/psycopg2#1275]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine scripts/make_errorcodes.py, scripts/make_errors.py and observe `publically`, however expect to see `publicly`.
- Examine tests/test_connection.py and observe `uniconde`, however expect to see `unicode`.
- Examine doc/src/faq.rst and observe `suppsed`, however expect to see `supposed`.
- Examine psycopg/xid_type.c and observe `somenthing`, however expect to see `something`.
- Examine tests/dbapi20.py and observe `portible`, however expect to see `portable`.
- Examine psycopg/cursor_type.c and observe `exausted`, however expect to see `exhausted`.
- Examine tests/dbapi20.py and observe `compiliance`, however expect to see `compliance`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR.

https://github.com/timgates42/psycopg2/pull/new/bugfix_typos

Thanks.

**Comment by dvarrazzo** [comment]
Cherrypicked, thank you
