### ISSUE TITLE
aarch64 wheels not published to pypi

### ISSUE THREAD

**Issue by AWSjswinney** [psycopg/psycopg2#1287]
Builds for Arm (aarch64) are [completing successfully](https://github.com/psycopg/psycopg2/actions/runs/900986065) in GitHub Actions. However, these builds have not been published to [pypi](https://pypi.org/project/psycopg2/2.8.6/#files). It's not clear how that publish step occurs or if it is automated. Can these wheels be published?

Thanks!

**Comment by dvarrazzo** [comment]
They will be published with release 2.9, which is something I will start working again at today.

**Comment by AWSjswinney** [comment]
Thank you!
