### ISSUE TITLE
AWS Glue --additional-python-modules import psycopg2-binary broken

### ISSUE THREAD

**Issue by johnhill2424** [psycopg/psycopg2#1289]
I had been using the psycopg2-binary module to do some custom logging from my AWS Glue job (written in PySpark). In my script I am importing psycopg2 but now it's saying the module is not found. I reverted back to version 2.8.6 and it seems to work fine. Is this expected behavior with the latest version? 

Thanks!

**Comment by dvarrazzo** [comment]
We just release Python 2.9, which uses manylinux2014 packages. Maybe you have an outdated version of pip? What does `pip install -v psycopg2-binary` say?

**Comment by johnhill2424** [comment]
Unfortunately I'm using a managed AWS service (Glue) so I don't have access to update pip.

**Comment by dvarrazzo** [comment]
In this case you should install psycopg-binary < 2.9.
