### ISSUE TITLE
Placeholder does not add trailing "s" for named placeholders using 2.9

### ISSUE THREAD

**Issue by wsb252** [psycopg/psycopg2#1291]
If I run statement.as_query(conn) with the new version, the named placeholder fields are missing a trailing 's' which is required.  The prior version (2.8.6) correctly puts the trailing "%(name)s" format

sql.Placeholder(name=location)

2.9 yields:
VALUES (%(location)) 

2.8.6 yields:
VALUES (%(location)s) 

The syntax for 2.9 causes the subsequent .execute( ) command to fail

**Comment by dvarrazzo** [comment]
oops. Fixing and releasing immediately.

**Comment by dvarrazzo** [comment]
Turns out that there was a regression test for it, but it was spelled:

```python
self.assert_(sql.Placeholder('foo').as_string(self.conn), '%(foo)s')
```

which always passed. It should have been `self.assertEqual`...
