### ISSUE TITLE
cursor.copy_from command gives psycopg2.errors.UndefinedTable: relation "<table_name>" does not exist error

### ISSUE THREAD

**Issue by superoverflow** [psycopg/psycopg2#1295]
After upgrade to 2.9.1, calling `cursor.copy_from` gives below error:
`psycopg2.errors.UndefinedTable: relation "TABLE_NAME" does not exist`

`cursor.query` shows
`b'COPY "TABLE_NAME" FROM stdin WITH DELIMITER AS \'^\' NULL AS \'\\N\''`

tested 2.8.6, the functions called fine and `cursor.query` shows
`b"COPY TABLE_NAME FROM stdin WITH DELIMITER AS '^' NULL AS '\\N'"`

It appears the extra double quote is introduced and caused the error.

According to the document https://www.psycopg.org/docs/cursor.html#cursor.copy_from

> the name of the table is not quoted

It seems the change in 2.9.1 is not intended

Could you please help to look into it? thanks!

**Comment by dvarrazzo** [comment]
Yes, the change is intended. See #1294.

I need to fix the documentation: thank you for pointing it out.
