### ISSUE TITLE
Connection to DB closes with Operational Error if Pyscopg2 is installed from a Conda Channel

### ISSUE THREAD

**Issue by mdw1715** [psycopg/psycopg2#1297]
I spent 2 weeks trying to connect to a PG database with python with the same operational error. Finally discovered the fix was to uninstall the package that came from Conda or Conda-forge, and used PIP instead. 

Issue seems to persist in the new 2.9 version of Psycopg2

**Comment by dvarrazzo** [comment]
This ticket is not helpful. Whatever is your problem with conda you should open a bug with conda. Whatever is your problem with psycopg 2.9 you are not describing it.
