### ISSUE TITLE
psycopg2 2.9+ is throwing a lot of unexpected UndefinedTable errors

### ISSUE THREAD

**Issue by pvieito** [psycopg/psycopg2#1298]
Hi! Our CIs started to fail 2 days ago for `UndefinedTable` errors when sending queries to a PostgreSQL 10.14 database. We have found that the source of the problem is the `psycopg2` package 2.9 update, downgrading to 2.8.6 fixes the issue. The errors have the following format:

```
UndefinedTable('relation "example_schema_name.example_table_name" does not exist\n') 
```

All the errors are from tables that do indeed exist in the database.

**Comment by dvarrazzo** [comment]
See #1294

**Comment by pvieito** [comment]
Oh, thanks! 👍🏻
