### ISSUE TITLE
cursor.copy_from unable to detect table while insert in the PostgreSQL

### ISSUE THREAD

**Issue by milan-15697** [psycopg/psycopg2#1299]
The latest version: 2.9.1 is unable to execute cursor.copy_from for bulk inserts in PostgreSQL and throwing psycopg2.errors.UndefinedTable

Temporary Workaround:
I reverted to Psycopg 2.8.6 then it got fixed automatically and started working like a charm.
Please fix!!!

**Comment by superoverflow** [comment]
There is a discussion about this here https://github.com/psycopg/psycopg2/issues/1294

**Comment by milan-15697** [comment]
> There is a discussion about this here #1294

Thank you
