### ISSUE TITLE
relation xy doesn't exist using 2.9.1

### ISSUE THREAD

**Issue by mds111** [psycopg/psycopg2#1300]
Hello,

I used 2.8.6 and copy_from() and callproc() without any problems.
After updating to 2.9.1 callproc() is still working, but copy_from() throws an error 'relation .... doesn't exist' with all relations in every database and schema I have. Using pg8000 or any other program I use doesn't have any problem using these relations.
Downgrading to 2.8.6 and everything works again.

**Comment by dvarrazzo** [comment]
See #1294

**Comment by mds111** [comment]
Thank You very much indeed !
Sorry I coudn't find #1294
