### ISSUE TITLE
COPY_FROM failing  UndefinedTable: relation "<schema name>.<table name>" does not exist, post 2.9.1 release

### ISSUE THREAD

**Issue by vtiwary** [psycopg/psycopg2#1302]
Post release of psycopg2==2.9.1, Copy_from functionality is failing with error 
COPY_FROM throws error UndefinedTable: relation "<schema name>.<table name>" does not exist
below is the code
cursor.copy_from(sio, table='TestSchema.TestTable', columns=list(df.columns), sep=',')
It works fine with psycopg2==2.8.6

**Comment by dvarrazzo** [comment]
See #1294

**Comment by vtiwary** [comment]
Many thanks. Incase someone has already extensively used Copy_From (like me), I believe adding below will help avoid making lots of code changes
cursor.execute("SET search_path = Schema_Name")

**Comment by QiwenZheng1234** [comment]
@vtiwary I'm not familiar with these, but did you mean adding cursor.execute("SET search_path = Schema_Name") before or after cursor.copy_from(...)? Thanks.
