### ISSUE TITLE
Unable to create tablespace 'psycopg2.errors.ActiveSqlTransaction: CREATE TABLESPACE cannot run inside a transaction block'

### ISSUE THREAD

**Issue by sarng11** [psycopg/psycopg2#1305]
Unable to create tablespace getting this error  'psycopg2.errors.ActiveSqlTransaction: CREATE TABLESPACE cannot run inside a transaction block'

Version: psycopg2==2.9.1

Workaround: pip3 install psycopg2-binary==2.8.6

**Comment by dvarrazzo** [comment]
You are using `with connection`, which is [documented as starting a transaction](https://www.psycopg.org/docs/usage.html#with-statement). However no transaction was started for autocommit transaction: this was an unspecified behaviour. In psycopg 2.9 `with` starts a transaction in autocommit mode too.

If you need to run a statement outside a transaction don't run it under `with`.

**Comment by dvarrazzo** [comment]
See #941 for reference.

**Comment by Hcreak** [comment]
This is rubbish!
