### ISSUE TITLE
psycopg2-binary seems to build from source in pip3 install

### ISSUE THREAD

**Issue by HomeBrewCards** [psycopg/psycopg2#1306]
When requiring psycopg2-binary for projects I have recently, from psycopg2-binary 2.9 and newer, there is a new build failure - requiring installation of libpq-dev
 
Error log attached:

```
Collecting psycopg2-binary (from -r /app/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/39/55/54778407e306de1acd3c616dc6a04e3821effa52c21d6c688d4947878658/psycopg2-binary-2.9.tar.gz (379kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    Error: pg_config executable not found.
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    or with the pg_config option in 'setup.cfg'.
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>). 
```

>    If you prefer to avoid building psycopg2 from source, please install the PyPI  'psycopg2-binary' package instead.

Great idea, I'd love to do that :)

Thanks,
Nathan

**Comment by dvarrazzo** [comment]
Have you upgraded pip as documented?

**Comment by exhaustedbrit** [comment]
I'm having the same issue.

> Have you upgraded pip as documented?

Though I can't find where this is documented, which version of pip is required?

**Comment by synerjay** [comment]
I'm having the same issue. 
I have the same error when running pip install psychopg2

`It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
`
I have installed psycopg2-binary and the latest version of pip... and I'm still having this issue... Can anyone help me out?

**Comment by dvarrazzo** [comment]
@synerjay on which platform?

**Comment by dvarrazzo** [comment]
Closing this issue anyway because binary packages work as expected using an up-to-date version of pip.

**Comment by boxed** [comment]
Shouldn't the binary package fail itself, instead of fail because it can't build from source?

**Comment by dvarrazzo** [comment]
It should, but ten thousands lost souls who had put psycopg2-binary in their requirements.txt files needed to be saved when their system failed to install in docker.

I know it's not pretty. Use psycopg 3 and there won't be this problem.
