### ISSUE TITLE
Year greater than 9999 does not throw in SELECT

### ISSUE THREAD

**Issue by srknzl** [psycopg/psycopg2#1307]
Python year range is 1-9999, whereas posgres's range is larger. I expect python client to throw if overflow happens but it does not throw for year greater than 9999. Instead, it gives 9999. 

Reproducer:

```sql
CREATE TABLE "a" (
  "b" date NOT NULL
);
```

```sql
INSERT INTO "a" ("b")
VALUES ('10000-06-23');
```

```python3
import psycopg2

conn = psycopg2.connect(dbname="postgres", user="postgres", password="example", host="localhost", port="5432")

cur = conn.cursor()

cur.execute("SELECT * FROM a;")

print(cur.fetchone())
```

prints
```
➜  python3 a.py 
(datetime.date(9999, 6, 23),)
```

where I expect it to throw since the data is not correct. When I update year to be `1000-06-23 BC` it throws:

```
➜  python3 a.py 
Traceback (most recent call last):
  File "a.py", line 9, in <module>
    print(cur.fetchone())
ValueError: year -1000 is out of range
```

**Comment by dvarrazzo** [comment]
I see. That's pretty poor. It is that way since 2007 apparently (d061b384d941d544de4d989c0496e7415e4d4201).
