### ISSUE TITLE
LNK2001 errors on build for Python3.8 in Windows 10

### ISSUE THREAD

**Issue by benjdod** [psycopg/psycopg2#1308]
While trying to install psycopg2 at 2.9.1 (most recent as of 6/23/2021), I get several linking errors. 

From prior issues, it seems that a missing `libpq.dll` due to some funky path configuration can be the culprit, but I have Postgres 12 installed on my machine with `.../PostgreSQL/12/bin` containing the needed library in my path. Additionally, I haven't seen any error concerning a missing `pg_config` while trying to get off the ground. 

Although mentioned as a fix in previous issues (#399)  I've been shying away from using win-psycopg due to its age. Maybe I should dive deeper but I'm really hoping there's a simpler fix 😬...

**Current Environment Info:**
Python 3.8, Windows 10, Postgres 12, VS build tools 2019 are installed. 

**Relevant error output:**
```
PS X:\some\python\project> pip install --no-binary :all: psycopg2==2.9.1

    ...
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQfreemem
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQencryptPasswordConn
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQencryptPassword
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQinitOpenSSL
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQconninfoParse
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQerrorMessage
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQlibVersion
    psycopgmodule.obj : error LNK2001: unresolved external symbol _PQconninfoFree
    green.obj : error LNK2001: unresolved external symbol _PQclear
    pqpath.obj : error LNK2001: unresolved external symbol _PQbinaryTuples
    pqpath.obj : error LNK2001: unresolved external symbol _PQsetnonblocking
    pqpath.obj : error LNK2001: unresolved external symbol _PQgetvalue
    pqpath.obj : error LNK2001: unresolved external symbol _PQresultStatus
    pqpath.obj : error LNK2001: unresolved external symbol _PQoidValue
    pqpath.obj : error LNK2001: unresolved external symbol _PQcmdStatus
    pqpath.obj : error LNK2001: unresolved external symbol _PQsocket
    pqpath.obj : error LNK2001: unresolved external symbol _PQftablecol
    pqpath.obj : error LNK2001: unresolved external symbol _PQputCopyData
    pqpath.obj : error LNK2001: unresolved external symbol _PQstatus
    pqpath.obj : error LNK2001: unresolved external symbol _PQisBusy
    pqpath.obj : error LNK2001: unresolved external symbol _PQconsumeInput
    pqpath.obj : error LNK2001: unresolved external symbol _PQresultErrorField
    pqpath.obj : error LNK2001: unresolved external symbol _PQfsize
    pqpath.obj : error LNK2001: unresolved external symbol _PQfname
    pqpath.obj : error LNK2001: unresolved external symbol _PQsendQuery
    pqpath.obj : error LNK2001: unresolved external symbol _PQgetCopyData
    pqpath.obj : error LNK2001: unresolved external symbol _PQftable
    pqpath.obj : error LNK2001: unresolved external symbol _PQflush
    pqpath.obj : error LNK2001: unresolved external symbol _PQftype
    pqpath.obj : error LNK2001: unresolved external symbol _PQnfields
    pqpath.obj : error LNK2001: unresolved external symbol _PQresultErrorMessage
    pqpath.obj : error LNK2001: unresolved external symbol _PQexec
    pqpath.obj : error LNK2001: unresolved external symbol _PQfmod
    pqpath.obj : error LNK2001: unresolved external symbol _PQcmdTuples
    pqpath.obj : error LNK2001: unresolved external symbol _PQntuples
    pqpath.obj : error LNK2001: unresolved external symbol _PQresStatus
    pqpath.obj : error LNK2001: unresolved external symbol _PQputCopyEnd
    pqpath.obj : error LNK2001: unresolved external symbol _PQgetResult
    utils.obj : error LNK2001: unresolved external symbol _PQescapeString
    utils.obj : error LNK2001: unresolved external symbol _PQescapeStringConn
    utils.obj : error LNK2001: unresolved external symbol _PQescapeIdentifier
    connection_int.obj : error LNK2001: unresolved external symbol _PQconnectPoll
    connection_int.obj : error LNK2001: unresolved external symbol _PQserverVersion
    connection_int.obj : error LNK2001: unresolved external symbol _PQnotifies
    connection_int.obj : error LNK2001: unresolved external symbol _PQsetNoticeProcessor
    connection_int.obj : error LNK2001: unresolved external symbol _PQgetCancel
    connection_int.obj : error LNK2001: unresolved external symbol _PQfinish
    connection_int.obj : error LNK2001: unresolved external symbol _PQprotocolVersion
    connection_int.obj : error LNK2001: unresolved external symbol _PQfreeCancel
    connection_int.obj : error LNK2001: unresolved external symbol _PQconnectdb
    connection_int.obj : error LNK2001: unresolved external symbol _PQconnectStart
    connection_int.obj : error LNK2001: unresolved external symbol _PQparameterStatus
    connection_type.obj : error LNK2001: unresolved external symbol _PQcancel
    connection_type.obj : error LNK2001: unresolved external symbol _PQtransactionStatus
    connection_type.obj : error LNK2001: unresolved external symbol _PQbackendPID
    connection_type.obj : error LNK2001: unresolved external symbol _PQconninfo
    cursor_type.obj : error LNK2001: unresolved external symbol _PQgetisnull
    cursor_type.obj : error LNK2001: unresolved external symbol _PQgetlength
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQsslInUse
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQconnectionNeedsPassword
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQpass
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQdb
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQsslAttribute
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQport
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQoptions
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQconnectionUsedPassword
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQsslAttributeNames
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQuser
    conninfo_type.obj : error LNK2001: unresolved external symbol _PQhost
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_truncate
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_write
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_import
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_creat
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_read
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_tell
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_create
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_lseek
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_unlink
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_open
    lobject_int.obj : error LNK2001: unresolved external symbol _lo_close
    adapter_binary.obj : error LNK2001: unresolved external symbol _PQescapeByteaConn
    build\lib.win32-3.8\psycopg2\_psycopg.cp38-win32.pyd : fatal error LNK1120: 83 unresolved externals
    ...

```

**Comment by jerickso** [comment]
@benjdod, out of curiosity, why are you trying to build from source?  On Windows, the recommended way is to use pip to install the binaries from PyPi, ie:
`pip install psycopg2==2.9.1`

If you are still interested in building from source, the ideal way would be to build Postgres from source and the openssl/zip libraries from source (if you want that functionality), too.  Could you build psycopg2 with the Postgres binary distribution?  Maybe, I haven't looked at that in awhile.  When I did, there were a few quirks that would cause potential support headaches and decided not to pursue it further.

And yes, I would not recommend using the old binary packages at my site, as I haven't updated it in years.  After we started building the Windows binaries for PyPi, it didn't make any sense for me to keep updating that page.  I'll change the site and note the updated installation method.

**Comment by dvarrazzo** [comment]
@jerickso appveyor is currently also building the `.exe`, which you used to distribute in your page, but they are not used otherwise (they are not uploaded on PyPI). Can we stop building them?

**Comment by dvarrazzo** [comment]
@benjdod the only way tested to build psycopg on windows is what implemented in [appveyor.py](https://github.com/psycopg/psycopg2/blob/master/scripts/build/appveyor.py), whose entry points are called by [the appveyor workflows](https://github.com/psycopg/psycopg2/tree/master/.appveyor). If you want to do something different we don't have so much helpful info to provide. Although I would be interested in the result.

In the past, building the libpq and openssl was mandatory because the mix and match of compilers was prone to segfaults. But maybe now there isn't the same problem anymore? @jerickso do you think it is possible to start packaging the postgres-shipped libpq?

**Comment by benjdod** [comment]
Update: I removed the `--no-binary` flag and it built successfully. I guess I took the documentation's warnings that the binary package should not be used in production without looking deep enough. 

Just to be clear, installing any version of psycopg2 >= 2.8 does not require `--no-binary`, only versions  2.7.x as per the [install doc](https://www.psycopg.org/docs/install.html#change-in-binary-packages-between-psycopg-2-7-and-2-8)?

**Comment by dvarrazzo** [comment]
@benjaminp on windows, binaries are shipped anyway and you are not expected to build from sources.

**Comment by jerickso** [comment]
@dvarrazzo yes, we can stop building the `.exe`.  I liked the `.exe`, but since we integrated the windows binaries into PyPi I honestly haven't used them.  The simplicity of installing via pip and the flexibility of installing in a venv has made me move away from them and I think for support it is better with people getting them from PyPi.

The one issue I remember with the Postgres shipped binaries was that they did not include the static linked `libpq.lib` library.  The `libpq.lib` that is included is the DLL import library, which requires `libpq.dll` to be located on the path.  I could investigate it again. For the distribution I think building the components and statically linking is better and, like you said, it minimizes the multiple complier issues we've seen before.
