### ISSUE TITLE
macOS wheels

### ISSUE THREAD

**Issue by chingc** [psycopg/psycopg2#1314]
I've noticed in the 2.9 [Release Notes](https://www.psycopg.org/docs/news.html#release-notes) that wheels are included for various linux platforms.

Are there plans to include macOS wheels as well?

Sorry if this is the wrong place to ask.

**Comment by dvarrazzo** [comment]
[They are](https://pypi.org/project/psycopg2-binary/#files).

Apple M1 in ARM mode is not supported yet because the GitHub Runner is not available to build them. Other mac should work.

For more info look for the issues in this tracker and the install docs.
