### ISSUE TITLE
Not able to connect to my Aurora RDS serverless cluster using pyscopg2

### ISSUE THREAD

**Issue by darshitpandya18** [psycopg/psycopg2#1319]
Hi!

I am not able to connect to my AWS Aurora Serverless RDS Cluster using psycopg2. The server get's terminated before connection. Looks like it is looking for a standalone RDS instance url to connect. But, as I am usign Aurora Serverless, we don't have any standalone instances. I am able to connect to Aurora RDS standalone instances though.

Thanks!

**Comment by dvarrazzo** [comment]
This is a PostgreSQL driver. If you use a different database implementation you should ask your vendor about how to use psycopg.
