### ISSUE TITLE
Proposal to add GPL Classpath Exception to License

### ISSUE THREAD

**Issue by penrods** [psycopg/psycopg2#1328]
I know there have been several Issues raised over the years regarding the psycopg2 license, including requests to change to MIT, BSD, Apache or other licenses.  This is not another one of those.

I arrived here because of some questions I have about the license and usage of psychpg2 within Django.  I've read all of the past discourse from other license-related posts and the intentions voiced by @fogzot.  Based on what I've gleaned from those exchanges, I'd like to suggest considering the addition of a GPL mechanism known as the Classpath Exception to make the written words of the license clearly align with the intention.

Basically, the (Classpath Exception clause](https://www.gnu.org/software/classpath/license.html) was introduced about a decade ago to when a GNU project needed to adjust the license to support usage of a library with Java and virtual machines.  Similar things had been done with libgcc previously, and I think this exception similarly fits psycopg2 usage such as by Django and Python.  In essence, the exception clarifies that the given library is GPLed, but anything which __uses__ the library can be licensed in any way.  This is clearer and cleaner than the LGPL license and eliminates the issues which I (and others) [believe could cause legal issues](https://softwareengineering.stackexchange.com/questions/119436/what-does-gpl-with-classpath-exception-mean-in-practice/326325#326325) in several situations, including mixing with languages like Python.

Most importantly, this change would retain the GPL license and ethos already used by this project.  And it legally makes it crystal clear that the Django usage of psycopg2 is legitimate.

I appreciate your time and efforts and would be happy to discuss further and assist if there is a desire to implement this license clarification.

P.S.  I also mentioned this in a [reply to a mailing list question from back in February](https://www.postgresql-archive.org/License-LPGL-and-commercialization-td6184424.html#a6205453), but I wanted to make sure it doesn't get lost in the comments and spam.

**Comment by dvarrazzo** [comment]
The LGPL is a well understood license. I believe your lawyer is not working in your best interest and I suggest to replace your lawyer with one compatible with the LGPL.
