### ISSUE TITLE
read_message() always returns 0 messages from Postgres10 RDS instance w/wal2json decoder

### ISSUE THREAD

**Issue by Nogginboink** [psycopg/psycopg2#1329]
I am trying to replicate an AWS RDS Postgres 10.15 instance to a target outside of RDS and have settled on logical replication using psycopg2 as the reader. I have a loop that calls read_message() that works beautifully with the Postgres test_decoding decoder but gets zero messages with the wal2json decoder.

I can get data from either decoder if I use consume_stream() instead of read_message(). Unfortunately, my application's needs would be best served using wal2json and the asynchronous mode. This is the only combination of the 4 that doesn't seem to work on AWS RDS Postgres 10.15.

Has anyone seen this before, or know of a solution?

**Comment by dvarrazzo** [comment]
Amazon RDS has never been tested, as it's not a free or open product.
