### ISSUE TITLE
OperationalError SSL SYSCALL error: Success

### ISSUE THREAD

**Issue by dan-ilin** [psycopg/psycopg2#1330]
- OS: AWS Lambda
- Python version: 3.8
- PostgreSQL version: 10.15
- pip version:  21.0

**Describe the bug**
Please let us know: 

The lambda randomly gets an OperationalError with the following message: `SSL SYSCALL error: Success`
This happens upon attempting to open a connection. Most of the time, the lambda is able to successfully open a connection. But occasionally, this error occurs. I have not been able to figure out how to recreate the error.

**Comment by dvarrazzo** [comment]
I don't think we can do anything about it. You should ask Amazon.

**Comment by akamath46297** [comment]
@dan-ilin - Were you able to resolve this issue ? If so could you share any details ?

**Comment by toabi** [comment]
We also have this issue but cannot figure out what causes it (not on AWS Lambda but in a python/django app). Did anybody find out more?

**Comment by sjmiller609** [comment]
I have this error message and I think in my case that psycopg2 is not including server name indication (SNI) in the Client Hello of the TLS handshake. My postgres server is requiring SNI to route requests.
