### ISSUE TITLE
ERROR: Failed building wheel for psycopg2  (macOS Big Sur)

### ISSUE THREAD

**Issue by Patrick-Chong** [psycopg/psycopg2#1331]
**Please complete the following information:**
- OS: macOS Big Sur
- Python version:3.8.8
- PostgreSQL version:13.3
- pip version: 21.0.1

I have tried everything under the sun, but every time I try to deploy my app, I get the "ERROR: Failed building wheel for psycopg2"

Here are 3 batches of the error code:
```
remote:          Building wheel for psycopg2 (setup.py): started
remote:          Building wheel for psycopg2 (setup.py): finished with status 'error'
remote:          ERROR: Command errored out with exit status 1:
remote:           command: /app/.heroku/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g879w4wh
remote:               cwd: /tmp/pip-install-0gu332e6/psycopg2/
```

```
 psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
remote:          psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
remote:            685 |     while (interp->next)
remote:                |                  ^~
remote:          error: command '/usr/bin/gcc' failed with exit code 1
remote:          ----------------------------------------
remote:          ERROR: Failed building wheel for psycopg2
remote:          Running setup.py clean for psycopg2
remote:        Successfully built alembic blinker dominate Flask-Bootstrap Flask-Mail guess-language-spirit itsdangerous Mako python-editor visitor WTForms
remote:        Failed to build psycopg2
remote:        Installing collected packages: SQLAlchemy, MarkupSafe, Mako, python-editor, six, python-dateutil, alembic, pytz, Babel, blinker, certifi, chardet, click, dnspython, dominate, urllib3, elasticsearch, idna, email-validator, Jinja2, itsdangerous, Werkzeug, Flask, Flask-Babel, visitor, Flask-Bootstrap, Flask-Login, Flask-Mail, Flask-SQLAlchemy, Flask-Migrate, Flask-Moment, WTForms, Flask-WTF, guess-language-spirit, PyJWT, python-dotenv, requests, psycopg2, gunicorn
remote:            Running setup.py install for psycopg2: started
remote:            Running setup.py install for psycopg2: finished with status 'error'
remote:            ERROR: Command errored out with exit status 1:
remote:             command: /app/.heroku/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_dp69x_d/install-record.txt --single-version-externally-managed --compile --install-headers /app/.heroku/python/include/python3.9/psycopg2
remote:                 cwd: /tmp/pip-install-0gu332e6/psycopg2/
```

```
psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:
remote:            psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
remote:              685 |     while (interp->next)
remote:                  |                  ^~
remote:            error: command '/usr/bin/gcc' failed with exit code 1
remote:            ----------------------------------------
remote:        ERROR: Command errored out with exit status 1: /app/.heroku/python/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0gu332e6/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_dp69x_d/install-record.txt --single-version-externally-managed --compile --install-headers /app/.heroku/python/include/python3.9/psycopg2 Check the logs for full command output.
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
```

**Comment by dvarrazzo** [comment]
What version of psycopg2 is it? I assume something old, released before Python 2.8.

**Comment by Patrick-Chong** [comment]
Hi dvarrazzo, no in fact it is 2.9.1! I believe this is the latest?

**Comment by Patrick-Chong** [comment]
I've spent week and weeks trying to figure this out, and nothing seems to fix it.

**Comment by dvarrazzo** [comment]
Hi @Patrick-Chong, looking at

```
remote:          psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
remote:            685 |     while (interp->next)
remote:                |                  ^~
remote:          error: command '/usr/bin/gcc' failed with exit code 1
```

I don't think you are building 2.9.1, because any reference from `PyInterpreterState` was dropped from `psycopgmodule.c` in  7a1fb9a2e47227c0cc130ef62142d90dd71999ee, back in 2019. The last time that `while (interp->next)` was at line 685 was in [release 2.7.4](https://github.com/psycopg/psycopg2/blob/5afb2ce803debea9533e293eef73c92ffce95bcd/psycopg/psycopgmodule.c#L685).

Please review your build chain. Python >= 2.8 support was added in psycopg 2.8 I think.

**Comment by dvarrazzo** [comment]
#854 has more details

**Comment by Patrick-Chong** [comment]
Hi dvarrazzo, thanks for the reply again. I don't quite follow- how can I fix this issue? I did come across #854, but I don't quite know what to do in terms of next steps? Do I uninstall psycopg2.9.1 and install a different version?

**Comment by Patrick-Chong** [comment]
I did see you mention to review the build chain, but apologies but I am not that advance with this yet, so I would not quite know what to do with this.

**Comment by Patrick-Chong** [comment]
I have uninstalled psycopy2.9.1 and installed psycopg2.8.0, but the exact same error is still there..

**Comment by dvarrazzo** [comment]
@Patrick-Chong what I mean is that you *think* that you are 2.9.1, but, for some reason, you are installing 2.7.4 or previous.

`pip install -U "psycopg2>=2.9.1"` normally works. Please read the pip documentation or ask someone about pip if it doesn't.

**Comment by dwmedina** [comment]
@Patrick-Chong 

Here is how I solved the issue on WSL 2 using Ubuntu-20.04.

1.  I installed the following dependencies:  `python-dev` , `python3-dev`.
2.  I installed wheels using  `pip3 install wheel` .  
3.  I isntalled `python[your version]-dev`.

The root cause of the problem was that psycopg2 was looking for headers for Python 3.8.5.  Since I am using Python 3.9.5, the headers could not be located and psycopg2 could not install.  After installing `python3.9-dev` , psycopg2 successfully installed on my system.

Additional references:  

[SO - Invalid command bdist wheel on Travis CI](https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci)
[SO - How to fix `error: invalid command 'bdist_wheel'`](https://stackoverflow.com/questions/65273035/how-to-fix-error-invalid-command-bdist-wheel)

**Comment by Patrick-Chong** [comment]
Thanks dwmedina, how did you install python-dev and python3-dev. I can't use 'pip install' as I get the following error: 

ERROR: Could not find a version that satisfies the requirement python3-dev (from versions: none)
ERROR: No matching distribution found for python3-dev

**Comment by Patrick-Chong** [comment]
Thanks dwmedina, I am struck on point 3. So my python version is 3.8.8. So when I do `pip3 install python3.8.8` I get the error: 

ERROR: Could not find a version that satisfies the requirement python3.8.8-dev (from versions: none)
ERROR: No matching distribution found for python3.8.8-dev

**Comment by dwmedina** [comment]
Python[your version]-dev is a Linux package.  It can't be found with Pip.  I think for macOS that you will need to get the install the headers directly.  I found this older SO post on how to do so:  [How to install the Python development headers on macOS](https://stackoverflow.com/questions/15931331/how-to-install-the-python-development-headers-on-mac-os-x) .
