### ISSUE TITLE
Having issue installing on latest

### ISSUE THREAD

**Issue by arvobrendon** [psycopg/psycopg2#1333]
**Please complete the following information:**
- OS: Mac
- Psycopg version: 2.9.1
- Python version: 3.9.6
- pip version 21.1.3

    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-install-gmw0hhht/psycopg2_3f555300555d4742ba95a1b93ef1a6da/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-install-gmw0hhht/psycopg2_3f555300555d4742ba95a1b93ef1a6da/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4
         cwd: /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-install-gmw0hhht/psycopg2_3f555300555d4742ba95a1b93ef1a6da/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4/psycopg2.egg-info
    writing /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/y0/qwms1cw15dz5hd87c7xgd1w40000gn/T/pip-pip-egg-info-74m7eaa4/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fd/ae/98cb7a0cbb1d748ee547b058b14604bd0e9bf285a8e0cc5d148f8a8a952e/psycopg2-2.8.6.tar.gz#sha256=fb23f6c71107c37fd667cb4ea363ddeb936b348bbd6449278eb92c189699f543 (from https://pypi.org/simple/psycopg2/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2==2.8.6 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1)
ERROR: No matching distribution found for psycopg2==2.8.6

**Comment by dvarrazzo** [comment]
First, you are not asking for the latest, you are asking for 2.8.6. As reported in:
 
>  ERROR: No matching distribution found for psycopg2==2.8.6

Second, you are asking to install from source: as such you should set up your dev tools as documented in https://www.psycopg.org/docs/install.html

There is a bug in psycopg < 2.9 that makes installing on Mac more difficult. If you try and install **really** 2.9.1 it should work, provided you have what described in the docs.

**Comment by arvobrendon** [comment]
ERROR: Could not find a version that satisfies the requirement psycopg2==2.9.1 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1)
ERROR: No matching distribution found for psycopg2==2.9.1

**Comment by dvarrazzo** [comment]
>    Error: pg_config executable not found.

solve this. Thank you.

**Comment by Mosh2018** [comment]
psycopg2==2.9.1 works fine in python:3.9-alpine

**Comment by CarlDownsOracle** [comment]
Alpine is the problem.  

I had this:
FROM python:3.7.3-alpine

Changing to this fixed it:
FROM python:3.7
