### ISSUE TITLE
"relation does not exist" when using copy_from method

### ISSUE THREAD

**Issue by Di-m-ka** [psycopg/psycopg2#1334]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Debian 10
- Psycopg version: 2.9.1
- Python version: 3.7
- PostgreSQL version: 11.5
- pip version 19.2.3

**Describe the bug**
Please let us know: I'm facing an error message "relation <my_schema.my_tabe> does not exist" when i'm using copy_from method (2.9.1) but on 2.8.1 all is ok

**Comment by dvarrazzo** [comment]
#1294
