### ISSUE TITLE
Typo on Psycopg2 Installation Page

### ISSUE THREAD

**Issue by vincetran96** [psycopg/psycopg2#1336]
To maintainers,

I believe there is a a typo on the installation page, under the [Quick Install](https://www.psycopg.org/docs/install.html#quick-install) header:

> This will install a pre-compiled binary version of the module which does not require the build or runtime prerequisites described below. Make sure to use an **up-date-date** version of pip (you can upgrade it using something like pip install -U pip).

Unless "up-date-date" is a proper word, it should be up-to-date. Thank you!

**Comment by dvarrazzo** [comment]
up-date-date is a nice word and should totally exist :smile:  But yes, I think it's not out task to make it up. 

Will fix, thank you for the report.
