### ISSUE TITLE
psycopg2.errors.ActiveSqlTransaction: VACUUM cannot run inside a transaction block

### ISSUE THREAD

**Issue by ICE-FA** [psycopg/psycopg2#1337]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:
- Psycopg version:
- Python version:
- PostgreSQL version:
- pip version

**Describe the bug**
Please let us know:

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.
scripts/get-external-data.py
INFO:root:Checking table simplified_water_polygons
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 108, in index
    cur.execute('''VACUUM ANALYZE "{temp_schema}"."{name}";'''
psycopg2.errors.ActiveSqlTransaction: VACUUM cannot run inside a transaction block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/get-external-data.py", line 294, in <module>
    main()
  File "scripts/get-external-data.py", line 284, in main
    this_table.index()
  File "scripts/get-external-data.py", line 111, in index
    self._conn.autocommit = old_autocommit
psycopg2.ProgrammingError: set_session cannot be used inside a transaction
![Screenshot from 2021-08-13 07-28-10](https://user-images.githubusercontent.com/88532371/129393317-9859b6b6-7ecd-480e-ae76-eab8a91f877f.png)

**Comment by dvarrazzo** [comment]
The documentation explains how to run commands outside a transaction
