### ISSUE TITLE
Incorrect python type for XID

### ISSUE THREAD

**Issue by kvesteri** [psycopg/psycopg2#1343]
- OS: Mac OS
- Psycopg version: 2.9.1
- Python version: 3.8.5
- PostgreSQL version: 12
- pip version

**Describe the bug**

Psycopg2 incorrectly returns xid datatype as an integer in python. This represents a problem when using the returned value as a comparison for xid typed xmin column. Common scenario is for example [server side version counters](https://docs.sqlalchemy.org/en/14/orm/versioning.html#server-side-version-counters).

Passing the returned integer for the equality comparison works when the integer is smaller than or equal to the maximum `int4` value of PostgreSQL (2147483647). However the largest `xid` value (2864038835) is larger than the largest int4 value. Thus an error can occur when giving larger value than 2147483647 to the where condition. 

I think a sane default would be that psycopg2 returned the xid values always as a string. Otherwise the enduser needs to remember to cast these values as strings manually on the python side OR remember to use type casting extension of psycopg2.

Script to reproduce. Consider table `a` with row `id=1` having `xmin` as `2788713511`

```python
cursor = conn.cursor()

cursor.execute('SELECT xmin FROM a WHERE id = 1')

xmin = cursor.fetchone()[0]  # 2788713511

cursor.execute('SELECT xmin FROM a WHERE id = 1 AND xmin = %s', (xmin,))
```
Throws exception:
```
UndefinedFunction: operator does not exist: xid = bigint
LINE 1: SELECT xmin FROM a WHERE id = 1 AND xmin = 2788713511

HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

```

**Comment by dvarrazzo** [comment]
> Psycopg2 incorrectly returns xid datatype as an integer in python.

Does it?

```pyhon
import psycopg2

cnn = psycopg2.connect()
cur = cnn.cursor()
cur.execute("select '123'::xid")
cur.fetchone()
('123',)
```

**Comment by kvesteri** [comment]
Sorry for the trouble. There was a mistake in my code.

**Comment by dvarrazzo** [comment]
No worries :slightly_smiling_face:
