### ISSUE TITLE
TO_DATE cursor.fetchmany got ValueError: year 0 is out of range

### ISSUE THREAD

**Issue by hcheng2002cn** [psycopg/psycopg2#1345]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: linux 
- Psycopg version: 2.8.6
- Python version: 3.8.6
- PostgreSQL version: 12
- pip version: 21.2.3 

**Describe the bug**
Please let us know:

1: what you did
query:
SELECT TO_DATE('10/10/2019','MM/DD');
2: what you expected to happen
return 10/10
3: what happened instead
when using cursor.fetchmany, we got ValueError: year 0 is out of range
run on psql:
```
SELECT TO_DATE('10/10/2019','MM/DD');
    to_date    
---------------
 0001-10-10 BC
(1 row)
```

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
Python doesn't support year 0 or BC, so that date cannot be converted into a python object.

What do you want it to return? You can write a custom adapter for it.

**Comment by hcheng2002cn** [comment]
Thanks for response.
