### ISSUE TITLE
invalid transaction termination - CONTEXT:  PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 43 at COMMIT

### ISSUE THREAD

**Issue by tomahim** [psycopg/psycopg2#1349]
Hi,

I'm trying to call a procedure with psycopg2 (from [pg_partman run_maintenance_proc()](https://github.com/pgpartman/pg_partman/blob/f0c1b58bdc47a17306a1b1d90e35bc098e833966/sql/procedures/run_maintenance_proc.sql)).

I'm able to do a simple `CALL partman.run_maintenance_proc();` from psql command line. But when I attempt to do the same with psycopg2 I run into this error: 

```
psycopg2.errors.InvalidTransactionTermination: invalid transaction termination
CONTEXT:  PL/pgSQL function partman.run_maintenance_proc(integer,boolean,boolean) line 43 at COMMIT
``` 

Here is my code :

```
dbconn = psycopg2.connect(t_dsn)
cursor = dbconn.cursor()
cursor.execute('CALL partman.run_maintenance_proc()')
results = cursor.fetchone()
cursor.close()
dbconn.close()
```

Do you have an idea what might be wrong ?

Note: I noticed there is a `cursor.callproc` method but it seems to execute a `SELECT`. The error I have `HINT:  To call a procedure, use CALL.`

Database : postgres 12.5
Psycopg2 version:  2.9.1

**Comment by dvarrazzo** [comment]
You should probably use an autocommit transaction to use CALL.
