### ISSUE TITLE
Working with broken encodings

### ISSUE THREAD

**Issue by devl00p** [psycopg/psycopg2#1350]
Hello,

I trying to extract some records from a postgresql server unfortunately the table has text with broken encoding inside (looks like mixed encoding) and I can't find a way to fetch it without raising a UnicodeDecodeError:.

The code is pretty simple:

```python
import psycopg2

conn = psycopg2.connect(host="anonymised", dbname="anonymised", user="postgres")
# conn.set_client_encoding("utf-8")
cur = conn.cursor()

cur.execute("SELECT * FROM public.anonymised;")
cur.fetchone()  # error happens here

cur.close()
conn.close()
```

I get the following error:
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 0: ordinal not in range(128)```

and if I set the encoding to UTF-8 I get:
```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte```

Is there any way I can get the data with the invalid characters replaced for exemple ? (like what Python does with `errors="replace"`) 

The server is not mine so I can't fix the records are modify the encoding on the server but my code should be able to get the content whatever the possible errors in the text.

Versions used:

- OS: Ubuntu 18.04.5 LTS
- Psycopg version: 2.9.1
- Python version: 3.7.3
- PostgreSQL version: 10.18

**Comment by dvarrazzo** [comment]
Look for ways of receiving strings as bytes, using the [BYTES typecaster](
