### ISSUE TITLE
High Connection time azure function

### ISSUE THREAD

**Issue by tech7857** [psycopg/psycopg2#1351]
Hi 

we are writing a python(3.9) azure function hosted on linux which is connecting to azure postgresql 11. We are using psycopg2 to connect the azure function to postgresql.

we are noticing the connection establishment is taking around 200-300 ms. Below is the statment.

conn=psycopg2.connect(conn_string)

The connection establishment time is very high as our functions are written to be very high performance.

can you please let us know if there is something we should be doing to reduce the connection establishment time.

Thanks

**Comment by dvarrazzo** [comment]
Hello,

This is probably the libpq trying to use some service you don't need, such as Kerberos, or it might be even the dns. Probably using strace during connection might point you to the cause of the slowness and you should be able to add connection string parameters to bypass it. For more information you should ask a postgres mailing list: they might know the problem already.

If you have needs for low latency you should consider to use a pool. Paycopg2 has one but it's not the greatest thing: you might want to check out psycopg 3 instead.
