### ISSUE TITLE
Bug with installation in "ldflags"

### ISSUE THREAD

**Issue by KonstantenKomkov** [psycopg/psycopg2#1369]
Hello!

I'm trying to install next config:
Windows 11
Python 3.10
pip 21.2.4
psycopg2 2.9.1

Installation process crashed with next error:
(venv) PS D:\Work\Python\pythonProject\venv\Scripts> pip install psycopg2
Collecting psycopg2
  Using cached psycopg2-2.9.1.tar.gz (379 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Work\Python\pythonProject\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokeni
ze; sys.argv[0] = '"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-401k868r\\psycopg2_0aa926da7bd4
45ab9f8417b2e147ff74\\setup.py'"'"'; __file__='"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-401
k868r\\psycopg2_0aa926da7bd445ab9f8417b2e147ff74\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__f
ile__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info -
-egg-base 'C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7'
         cwd: C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_0aa926da7bd445ab9f8417b2e147
ff74\
    Complete output (39 lines):
    running egg_info
    creating C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7\psycopg2.egg-info
    writing C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7\psycopg2.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7\psycopg2.egg-i
nfo\dependency_links.txt
    writing top-level names to C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7\psycopg2.egg-in
fo\top_level.txt
    writing manifest file 'C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-v21pcia7\psycopg2.egg-info\S
OURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_0aa926da7bd445ab9f8417b2e147ff
74\setup.py", line 548, in <module>
        setup(name="psycopg2",
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 299, in r
un
        self.find_sources()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 306, in f
ind_sources
        mm.run()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 541, in r
un
        self.add_defaults()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 578, in a
dd_defaults
        sdist.add_defaults(self)
      File "C:\Python\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Python\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Python\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_0aa926da7bd445ab9f8417b2e147ff
74\setup.py", line 380, in finalize_options
        for token in pg_config_helper.query("ldflags").split():
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_0aa926da7bd445ab9f8417b2e147ff
74\setup.py", line 123, in query
        result = result.decode('ascii')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 0: ordinal not in range(128)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/aa/8a/7c80e7e44fb1b4277e89bd9ca509aefdd4dd1b2c547c6
f293afe9f7ffd04/psycopg2-2.9.1.tar.gz#sha256=de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c (
from https://pypi.org/simple/psycopg2/) (requires-python:>=3.6). Command errored out with exit status 1: python
 setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-2.9.tar.gz (379 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Work\Python\pythonProject\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokeni
ze; sys.argv[0] = '"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-401k868r\\psycopg2_5ac59a01802c
444cbbb6c8b6c8f6cb08\\setup.py'"'"'; __file__='"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-401
k868r\\psycopg2_5ac59a01802c444cbbb6c8b6c8f6cb08\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__f
ile__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info -
-egg-base 'C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n'
         cwd: C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_5ac59a01802c444cbbb6c8b6c8f6
cb08\
    Complete output (39 lines):
    running egg_info
    creating C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n\psycopg2.egg-info
    writing C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n\psycopg2.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n\psycopg2.egg-i
nfo\dependency_links.txt
    writing top-level names to C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n\psycopg2.egg-in
fo\top_level.txt
    writing manifest file 'C:\Users\Konstanten\AppData\Local\Temp\pip-pip-egg-info-s2wjzz3n\psycopg2.egg-info\S
OURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_5ac59a01802c444cbbb6c8b6c8f6cb
08\setup.py", line 548, in <module>
        setup(name="psycopg2",
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 299, in r
un
        self.find_sources()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 306, in f
ind_sources
        mm.run()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 541, in r
un
        self.add_defaults()
      File "D:\Work\Python\pythonProject\venv\lib\site-packages\setuptools\command\egg_info.py", line 578, in a
dd_defaults
        sdist.add_defaults(self)
      File "C:\Python\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Python\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Python\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_5ac59a01802c444cbbb6c8b6c8f6cb
08\setup.py", line 380, in finalize_options
        for token in pg_config_helper.query("ldflags").split():
      File "C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_5ac59a01802c444cbbb6c8b6c8f6cb
08\setup.py", line 123, in query
        result = result.decode('ascii')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 0: ordinal not in range(128)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6c/79/6df8af2405e2aa60732c47757453fc7fa4af5c90a1796
b3392ef892d3a52/psycopg2-2.9.tar.gz#sha256=b12073fdf2002e828e5921be2c39ff9c6eab361c5c0bd6c529619fc23677accc (fr
om https://pypi.org/simple/psycopg2/) (requires-python:>=3.6). Command errored out with exit status 1: python s
etup.py egg_info Check the logs for full command output.
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
Installing collected packages: psycopg2
    Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Work\Python\pythonProject\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tok
enize; sys.argv[0] = '"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-401k868r\\psycopg2_e53cceb74
ecc4ebfac629b3112954ae9\\setup.py'"'"'; __file__='"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-install-
401k868r\\psycopg2_e53cceb74ecc4ebfac629b3112954ae9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(
__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code =
f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install
 --record 'C:\Users\Konstanten\AppData\Local\Temp\pip-record-infcnc4v\install-record.txt' --single-version-exte
rnally-managed --compile --install-headers 'D:\Work\Python\pythonProject\venv\include\site\python3.10\psycopg2'

         cwd: C:\Users\Konstanten\AppData\Local\Temp\pip-install-401k868r\psycopg2_e53cceb74ecc4ebfac629b311295
4ae9\
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\psycopg2
    copying lib\compat.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\errorcodes.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\errors.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\extensions.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\extras.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\pool.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\sql.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\tz.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\_ipaddress.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\_json.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\_lru_cache.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\_range.py -> build\lib.win-amd64-3.10\psycopg2
    copying lib\__init__.py -> build\lib.win-amd64-3.10\psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://v
isualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Work\Python\pythonProject\venv\Scripts\python.exe' -u -c 'im
port io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Konstanten\\AppData\\Local\\Temp\\pip-ins
tall-401k868r\\psycopg2_e53cceb74ecc4ebfac629b3112954ae9\\setup.py'"'"'; __file__='"'"'C:\\Users\\Konstanten\\A
ppData\\Local\\Temp\\pip-install-401k868r\\psycopg2_e53cceb74ecc4ebfac629b3112954ae9\\setup.py'"'"';f = getattr
(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools im
port setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __
file__, '"'"'exec'"'"'))' install --record 'C:\Users\Konstanten\AppData\Local\Temp\pip-record-infcnc4v\install-
record.txt' --single-version-externally-managed --compile --install-headers 'D:\Work\Python\pythonProject\venv\
include\site\python3.10\psycopg2' Check the logs for full command output.

**Comment by dvarrazzo** [comment]
Python 3.10 binary packages are not available yet.
