### ISSUE TITLE
Cannot install psycopg2-binary on Python 3.10.0

### ISSUE THREAD

**Issue by christophelec** [psycopg/psycopg2#1371]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [X] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [X] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [X] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [X] I am not trying to install `psycopg2-binary` in an Alpine Linux Docker image
- [ ] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error. > Not applicable as I'm installing psycopg2-binary, not psycopg2

**Please complete the following information:**
- OS: Ubuntu 20.04
- Psycopg version: All
- Python version: 3.10.0
- PostgreSQL version: Any
- pip version : 21.3

Hello,

I cannot install psycopg2-binary on Python 3.10.0.

Installing psycopg2-binary works with no issue on Python 3.9.7.

I suspect that binary packages are not available yet for Python 3.10.0.

Here are the error logs :
[error.log](https://github.com/psycopg/psycopg2/files/7325025/error.log)

Is there anything I can do to help about this ?

**Comment by dvarrazzo** [comment]
Yes, binary packages aren't ready but I've just checked that Github workflows now have Python 3.10 runners so probably they shoudl be ready by tomorrow.

Windows packages will have to wait more because they are produced by Appveyor and they don't have Python 3.10 support yet.

**Comment by AstroFloof** [comment]
I'm not sure I understand what you mean

**Comment by dvarrazzo** [comment]
Any estimate when appveyor will support python 3.10?

**Comment by dvarrazzo** [comment]
Thank you @GriceTurrble, following that ticket.

**Comment by hugovk** [comment]
3.10 is now available on AppVeyor: https://github.com/appveyor/ci/issues/3741#issuecomment-958837889

**Comment by dvarrazzo** [comment]
On it: https://ci.appveyor.com/project/psycopg/psycopg2

**Comment by dvarrazzo** [comment]
Psycopg 2.9.1 packages for Python 3.10 released: https://pypi.org/project/psycopg2/2.9.1/#files

**Comment by Borks** [comment]
Will older versions be packaged too? @dvarrazzo

**Comment by stephyswe** [comment]
cannot connect to database. 

Django==3.0.7
psycopg2==2.9.1
psycopg2-binary==2.9.1
...
Postgres version 14.

**Comment by dvarrazzo** [comment]
@stephyswe does this look like a ticket related to your question?
