### ISSUE TITLE
Odd behaviour of "LISTEN" when using "with psycopg2.connect(...) as ..."

### ISSUE THREAD

**Issue by royrwood** [psycopg/psycopg2#1373]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Linux 5.11.0-37-generic
- Psycopg version: 2.9.1
- Python version: 3.9.5
- PostgreSQL version: 10.6
- pip version: 21.3

**Describe the bug**

I'm trying to use the Postgresql LISTEN/NOTIFY as described in the psycopg documentation.  The code example in the documentation works as expected.  

My example does not work, and the difference is that I'm trying to use the psycopg connection as a context manager via "`with psycopg2.connect( ... ) as pg_conn:`".  To make things work, I need to issue a `pg_conn.commit( )` call, even though I have taken care to set the connection to auto-commit, as clearly described in the documentation.  Code follows:

```
import select
import psycopg2.extensions
import psycopg2.extras


USERID = 'myusername'
PASSWORD = 'mypasword'
DATABASE = 'mydb'
HOSTNAME = '127.0.0.1'
PORT = 5432
DBURI = 'postgresql://{}:{}@{}:{}/{}'.format(USERID, PASSWORD, HOSTNAME, PORT, DATABASE)


with psycopg2.connect(DBURI) as pg_conn:
    pg_conn.autocommit = True
    pg_conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)

    with pg_conn.cursor() as pg_cursor:
        pg_cursor.execute("""LISTEN test ;""")
        pg_conn.commit()  # Weird-- since we opened the connection using a "with ..." statement, we have to issue a commit or the LISTEN doesn't work

    print("Waiting for notifications on channel 'test'")

    select_poller = select.poll()
    select_poller.register(pg_conn, select.POLLIN)

    while True:
        poll_events = select_poller.poll(5 * 1000)
        print("Completed poll")

        if not poll_events:
            print("No poll events returned")
            continue

        for fileno, flags in poll_events:
            if fileno == pg_conn.fileno() and flags & select.POLLIN != 0:
                print("pg_conn ready for reading")
                pg_conn.poll()
                while pg_conn.notifies:
                    notify = pg_conn.notifies.pop(0)
                    print("Got NOTIFY:", notify.pid, notify.channel, notify.payload)
            else:
                print("Timeout")
```

The `commit( )` work-around is effective, but it's odd.

As mentioned, using the sample from the documentation works fine.  See below:

```
import select
import psycopg2.extensions
import psycopg2.extras


USERID = 'myusername'
PASSWORD = 'mypasword'
DATABASE = 'mydb'
HOSTNAME = '127.0.0.1'
PORT = 5432
DBURI = 'postgresql://{}:{}@{}:{}/{}'.format(USERID, PASSWORD, HOSTNAME, PORT, DATABASE)

pg_conn = psycopg2.connect(DBURI)
pg_conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
pg_conn.autocommit = True

with pg_conn.cursor() as pg_cursor:
    pg_cursor.execute("""LISTEN test ;""")

    print("Waiting for notifications on channel 'test'")

    select_poller = select.poll()
    select_poller.register(pg_conn, select.POLLIN)

    while True:
        poll_events = select_poller.poll(5 * 1000)
        print("Completed poll")

        if not poll_events:
            print("No poll events returned")
            continue

        for fileno, flags in poll_events:
            if fileno == pg_conn.fileno() and flags & select.POLLIN != 0:
                print("pg_conn ready for reading")
                pg_conn.poll()
                while pg_conn.notifies:
                    notify = pg_conn.notifies.pop(0)
                    print("Got NOTIFY:", notify.pid, notify.channel, notify.payload)
            else:
                print("Timeout")
```

**Comment by dvarrazzo** [comment]
`with connection` starts a transaction, doesn't close the connection at the end. I know that this behaviours is surprising: it had been changed in Psycopg 3 to a more normal "the context closes the connection at the end"

If you want to handle notifications you should be outside a transaction, using `with` goes against that. There are workarounds as you have seen, but not using it in first place is better.

Note that Psycopg 3 also makes much easier to use notifications: https://www.psycopg.org/psycopg3/docs/advanced/async.html#asynchronous-notifications
