### ISSUE TITLE
Create a mogrify function for use with the execute_values function

### ISSUE THREAD

**Issue by ryanhennig** [psycopg/psycopg2#1379]
The mogrify function is useful for seeing the actual query being sent to the DB for the execute function.  However it doesn't work for queries being sent to execute_values.  

I am opening this issue because I intend to solve this by extracting most of the logic from the execute_values function into a new mogrify_values function

**Comment by ryanhennig** [comment]
Yes, I modified execute_values to have 2 phases: prepare the literal sql and then execute it.  And then I extracted the part before the execution into a separate method.  I will submit a PR after I do some testing, get tox to run on my machine, etc

**Comment by dvarrazzo** [comment]
Closing: not interested in developing this feature.

**Comment by ReeceMcMillin** [comment]
Sorry for commenting on a closed issue, but to clarify - @dvarrazzo, is this an issue you're not interested in developing yourself or not interested in including in the library overall? I put together a minimal implementation for this at work yesterday and would like to upstream a proper version, but I'd understand if you're not interested in adding to the v2 feature maintenance burden.

If the feature as described in November is acceptable, I'll move to open the PR.

**Comment by dvarrazzo** [comment]
@ReeceMcMillin the feature is trivial to implement with a for loop and the features already exposed by psycopg, such as mogrify() or the entire SQL module. 

My preferemcr is to leave composing the two parts, looping and adapting, to the user: all the building blocks are there.
