### ISSUE TITLE
Update does not successfully done without error

### ISSUE THREAD

**Issue by mohammad5305** [psycopg/psycopg2#1380]
- arch i386
- Psycopg version: 2.9.1
- Python 3.9.6
- PostgreSQL 13.4
- pip 20.3.4

I want to update a column (sub_item col ) in every row and his data type is Text array  I write sql and it work in psql util correctly but when I try it with psycopg2 it not put everything after "YES" I try different formatting but nothing change like f-string, %s , ....

![image](https://user-images.githubusercontent.com/71145952/139688319-59ea14b5-945a-4421-acea-c89dcdf3de52.png)

I expect this :
```
SELECT sub_item FROM navbar WHERE id=7;
>> {"YES", "sub-item1", "sub_item2", "sub_item3", "....."}
```
but I get  this : 
```
>> {"YES"}
```

and I write a little script to show this issuse (btw don't say swear to me for line 26 :) )
sql : https://termbin.com/f0b0
python : https://termbin.com/f9slg
```
$ curl https://termbin.com/f0b0 | psql
$ curl https://termbin.com/f9slg | python
```

**Comment by dvarrazzo** [comment]
Please read the documentation about how to pass parameters to a query. It's like the first page.

**Comment by mohammad5305** [comment]
I use you recommendation in doc but nothing change man 
```
        query = "UPDATE psycopg_issuse SET data=%s WHERE id=%s"
        print(cur.mogrify(query, (item, id))) 
        # >> b"UPDATE psycopg_issuse SET data=ARRAY['YES','courses.html','acknowledgements.html','qualifications.html'] WHERE id=7"

        cur.execute(query, (item, id,))
```

**Comment by dvarrazzo** [comment]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.
