### ISSUE TITLE
copy_expert not able to copy into a specific schema

### ISSUE THREAD

**Issue by frafra** [psycopg/psycopg2#1383]
- OS: Ubuntu 18.04
- Psycopg version: 2.9.1
- Python version: 3.10
- PostgreSQL version: 9.6

**Describe the bug**

```python3
query = sql.SQL(
    """
    copy {table} ({columns})
    from stdin
    with (format csv)
"""
).format(
    table=sql.Identifier("schema.table"),
    columns=sql.SQL(", ").join(
        [sql.Identifier(c) for c in ["col1", "col2"]]
    ),
    options=sql.SQL(", ").join(options),
)
cur.copy_expert(query, sys.stdin)
```

Error: `psycopg2.errors.UndefinedTable: relation "schema.table" does not exist`.

It works just well if I do not specify any schema, but `table_name` can have schema:
>     The name (optionally schema-qualified) of an existing table.
-- https://www.postgresql.org/docs/14/sql-copy.html

**Comment by dvarrazzo** [comment]
You must use `sql.Identifier("schema", "table")`

**Comment by frafra** [comment]
Even if I do that, it does not work.
If I mistype the schema, I get an `psycopg2.errors.InvalidSchemaName`, but no matter if I use an existing or non-existing table, I still get a `psycopg2.errors.UndefinedTable` error.

**Comment by dvarrazzo** [comment]
Use or [`query.as_string()`](https://www.psycopg.org/docs/sql.html#psycopg2.sql.Composable.as_string) to validate what statement is generated by `sql.SQL` and validate it, e.g. using psql.

**Comment by frafra** [comment]
I can confirm that the solution given before worked. Thanks! :)
