### ISSUE TITLE
python manage.py makemigrations (Django 3.2.9 with python 3.10) raise ImproperlyConfigured

### ISSUE THREAD

**Issue by rngallen** [psycopg/psycopg2#1384]
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified module could not be found.

**Comment by dvarrazzo** [comment]
If it's windows, Python 3.10 support is being added now.

Use Python 3.9.

The next bug you add don't delete the information we asked. We ask them for reasons.
