### ISSUE TITLE
windows下更改psycopg2使用的libpq

### ISSUE THREAD

**Issue by yfdxzy2010** [psycopg/psycopg2#1387]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:
- Psycopg version:
- Python version:
- PostgreSQL version:
- pip version

**Describe the bug**
Please let us know:

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.

python3.8
windows10
pg12.7
在windows平台下，我想使用我自己编译的libpq.dll，怎么去指定？

**Comment by dvarrazzo** [comment]
Translation:

> python3.8
> windows10
> pg12.7
> Under the windows platform, I want to use libpq.dll compiled by myself, how do I specify it? 

Look at what the appveyor pipeline does, in the files:
- [`.appveyor/packages.yml`](https://github.com/psycopg/psycopg2/blob/master/.appveyor/packages.yml)
- [`scripts/build/appveyor.py`](https://github.com/psycopg/psycopg2/blob/master/scripts/build/appveyor.py)

And try to reproduce similar steps.
