### ISSUE TITLE
"Microsoft Visual C++ 14.0 or greater is required" issue with 2.9.2

### ISSUE THREAD

**Issue by vitaliyterziev** [psycopg/psycopg2#1389]
- OS: Windows 10
- Psycopg version: 2.9.2
- Python version: 3.9.7 64 bit
- PostgreSQL version: 14
- pip version: 21.3.1

2.9.1 is installing fine (tested it again) but latest version  seems to be breaking the pip installer and gives misleading message.

"building 'psycopg2._psycopg' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.c
om/visual-cpp-build-tools/"

**Comment by dvarrazzo** [comment]
Uhm, it's missing the binary files for windows indeed. Looking into why they weren't produced.

**Comment by dvarrazzo** [comment]
Got it. Appveyor doesn't allow to download artifacts from any job except the latest.

It shoud be fixed now.
