### ISSUE TITLE
Installation Error of Psycopg2 on windows 7

### ISSUE THREAD

**Issue by psycoteam** [psycopg/psycopg2#139]
Originally submitted by: chandramouli

I was trying to iinstall Psycopg2 on win 7 (64 - bit, installed python2.7 32 bit)
from http://www.stickpeople.com/projects/python/win-psycopg/ 
1. Installtion stops saying Python is not found in registry.
2. Have tried giving .Zip and extracted all files, placed in C:/Python27/ 
   getting error "%1 is not a standard win32 command" on invoking psycopg2

any help would be highly appreciated as am stuck on this for a while.

**Comment by fpietka** [comment]
@dvarrazzo although this issue is closed, I think it would be a good idea to remove the comment with spam

**Comment by dvarrazzo** [comment]
@fpietka never noticed it... thank you
