### ISSUE TITLE
Query parameter that is an empty tuple creates a query with a syntax error 

### ISSUE THREAD

**Issue by jftsang** [psycopg/psycopg2#1390]
**Please complete the following information:**
- OS: Linux
- Psycopg version: 2.8.6
- Python version: 3.7.4
- PostgreSQL version: unknown
- pip version: 21.2.3

**Describe the bug**
```
conn = ...
cur = con.cursor()
cur.execute(
    'select foo, bar from mytable where foo in %(foos)s',
    {'foos': tuple()}
)
```
I would have expected to get back an empty list of results. Instead, one gets:
```
SyntaxError: syntax error at or near ")"
LINE 1: ...ect uuid, named_data_set_name from metadata where uuid in ()
```
(Is this an issue with psycopg2 or with postgresql?)

**Comment by fogzot** [comment]
This is an issue in PostgreSQL: `()` is not a valid "empty" set. If you want to work with possibly empty sets use `= ANY(array here...)`.
