### ISSUE TITLE
Cannot use RDS IAM token as password when using LogicalReplicationConnection

### ISSUE THREAD

**Issue by deanmorin** [psycopg/psycopg2#1391]
- OS: MacOS 11.6
- Psycopg version: 2.9.2
- Python version: 3.9.7
- PostgreSQL version: 13.3
- pip version: 21.3.1

I also encountered this running our app in a Docker container with slightly different versions for everything.

I'm using RDS IAM (AWS) authentication when connecting to postgres. I use the AWS API to get a temporary token which can then just be used just like a regular password. The full token looks something like:

```
dbname.accountrdsid.us-west-1.rds.amazonaws.com:5432/?Action=connect&DBUser=myuser&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1234%2Fus-west-1%2Frds-db%2Faws4_request&X-Amz-Date=20211116T171155Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Security-Token=very_long_urlencoded_token&X-Amz-Signature=0000000000000000000000000000000000000000000000000000000000000000
```

I can successfully connect using this _unless_ I try to set `connection_factory=psycopg2.extras.LogicalReplicationConnection` when calling `pyscopg2.connect`. When I use that connection factory I get a password authentication error.

It's easy to come up with a script to reproduce this, but it requires that you have an RDS instance with IAM auth set up. 

I tried just running it against a local db with the user's password set to one of these tokens, but wasn't able to reproduce the issue. I tried both with the password set to the token exactly, as well as a url decoded version of the token. In both cases I was able to authenticate as long as I matched the password exactly.

Test script:
```python
import os
import psycopg2
import psycopg2.extras

params = {
    'host': os.environ['TEST_HOST'],
    'dbname': os.environ['TEST_DBNAME'],
    'user': os.environ['TEST_USER'],
    'password': os.environ['TEST_PASSWORD'],
}

psycopg2.connect(**params)
print('This works')

params['connection_factory'] = psycopg2.extras.LogicalReplicationConnection
psycopg2.connect(**params)
print("Won't get here, the above call to connect throws an exception")
```

Output:
```
This works
Traceback (most recent call last):
  File "/project/path/test.py", line 16, in <module>
    psycopg2.connect(**params)
  File "/usr/local/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/usr/local/opt/pyenv/versions/3.9.7/lib/python3.9/site-packages/psycopg2/extras.py", line 504, in __init__
    super().__init__(*args, **kwargs)
psycopg2.OperationalError: connection to server at "dbname.accountrdsid.us-west-1.rds.amazonaws.com" (10.0.0.100), port 5432 failed: FATAL:  password authentication failed for user "myuser"
connection to server at "dbname.accountrdsid.us-west-1.rds.amazonaws.com" (10.0.0.100), port 5432 failed: FATAL:  password authentication failed for user "myuser"
```

**Comment by dvarrazzo** [comment]
Psycopg is a driver for PostgreSQL, Amazon RDS is a proprietary database. We don't have RDS accounts available for testing and we can only only provide paid support for it.

**Comment by deanmorin** [comment]
You right, the more I think about it, the more it seems that this would be an issue on the RDS side of things. I'll open a ticket with them, please feel free to close this one
