### ISSUE TITLE
Running COPY_FROM for an empty table for multiple datasets in a loop will copy only the last entry

### ISSUE THREAD

**Issue by blendicavlad** [psycopg/psycopg2#1395]
- OS: MacOS 11.6 (20G165), Running psycopg2 from Docker 3.6.0
- Psycopg version: psycopg2 2.9.2
- Python version: 3.9
- PostgreSQL version: 14.0-1.pgdg110+1
- pip version: 21.2.4

1: what did I do:
Using copy_from to insert different datasets on an empty table (same table for all datasets), in a loop. 

2: what I expected to happen
Inserting every dataset in the table

3: what happened instead
Only the last entry of the loop is inserted (same result if i change the ordering of the elements from the loop). 

Description & steps to reproduce.
Have multiple datasets with no conflicting primary keys or constraints, then run copy_from in a loop for every dataset to add them in the same table (the table must be empty). Only the last dataset from the loop will be inserted.

Important note: This can be reproduced only if the table for witch is run is empty. If the table has even a single row, all the datasets will be inserted normally.

Note: For my use-case, I need to run multiple copy_from on the same table because I need to process the datasets independently on different subprocesses, running a single copy_from for all the merged datasets won't be a solution due to design considerations.

```
for df, client in clients_data:
    with conn:
          with conn.cursor() as cursor:
              for chunk in df:
                  df = pipeline.clean_df(chunk, cursor)
                  copy_from_df(chunk, 'mytable', cursor, chunksize=50000, with_commit=False)
      conn.close()
        
def copy_from_df(df: DataFrame,
                 table: str,
                 cursor,
                 chunk_size: int = __chunksize,
                 with_commit: bool = False
                 ):
    try:
        for i in range(0, df.shape[0], chunk_size):
            buffer = StringIO()
            chunk = df.iloc[i:(i + chunk_size)]
            chunk.to_csv(buffer, index=False, header=False, sep='\t', na_rep='\\N', quoting=None)
            buffer.seek(0)
            cursor.execute(f'SET search_path TO {SCHEMA}')
            cursor.copy_from(buffer, table, columns=list(df.columns))
        if with_commit:
            cursor.commit()
    except psycopg2.Error as e:
        logger.error('COPY FROM Error: ' + str(e))
        if with_commit:
            cursor.rollback()

    if with_commit:
        cursor.close()
```

**Comment by dvarrazzo** [comment]
I assume that if this was a bug in psycopg2 it would have been found already. So I'd say I'll close this. Please ask the question "why this code of mine doesn't work" on the mailing list or on stackoverflow.

**Comment by blendicavlad** [comment]
Well, I have tried everything since yesterday. Posted on stackoverflow/reddit (no answers). Postgresql doesnt have a public issue tracker so I can’t know if there is a problem on their side. If you say there is a problem with my code, can you please point me at it? There is no info in the psycopg/postgres docs about any limitation about runing multiple copy_from on the same table in a loop (I also tried to run in a single and multiple transactions), postgres logs are not showing anything, no exception, no nothing.

**Comment by dvarrazzo** [comment]
No, I don't review non-trivial code for free, you have misplaced expectations. As I said, psycopg has a mailing list and you might find, or maybe not, people to answer there. The contacts on the mailing list are on our website.

**Comment by blendicavlad** [comment]
Well, I certainly didn't expect you to review my code, I asked because your first comment made it seem like I had some obvious flaw in the snippet I posted in the Issue, or that you, as a developer who writes code closer to the database are aware of some hidden COPY FROM limitation. Ok then, thank you anyway for your time!
