### ISSUE TITLE
Can I use extended query protocol when connecting to the server with psycopg2?

### ISSUE THREAD

**Issue by HoLo-Debris** [psycopg/psycopg2#1401]
**This is a question**

Can I use extended query protocol when connecting to the server with psycopg2? If yes, how can I choose the extended query protocol? I found that the default protocol is simple query.

**Please complete the following information:**
- OS: CentOS 7.6
- Psycopg version: 2.7.7
- Python version:  3.6.8
- PostgreSQL version: 9.4
- pip version: 21.3.1

**Comment by dvarrazzo** [comment]
No, you can't. Psycopg2 is completely built around client side binding and simple query protocol.

Using the extended query protocol is a breaking change and pretty much a complete redesign. This is what happened in Psycopg 3.

https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding

**Comment by HoLo-Debris** [comment]
I got it, thank you so much for your answer.
