### ISSUE TITLE
Facing problem when importing psycopg2 on Mac OS 12.0.1(Monterey)

### ISSUE THREAD

**Issue by aalekhpyx** [psycopg/psycopg2#1404]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [YES] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [YES] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [YES] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [YES ] I am not trying to install `psycopg2-binary` in an Alpine Linux Docker image
- [ YES] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: mac os monterey 12.0.1
- Psycopg version: 2.9.2
- Python version: 3.9.7
- PostgreSQL version: 14.0
- pip version: 21.3.1

I had successfully installing psycopg2 using `pip install psycopg2`, and then upon using `import psycopg2` I faced following issue:  

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aalekh/Documents/performance_development/gitjob/dec_17/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/aalekh/Documents/performance_development/gitjob/dec_17/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): tried: '/Users/aalekh/Documents/performance_development/gitjob/dec_17/venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_psycopg.cpython-39-darwin.so' (no such file), '/usr/lib/_psycopg.cpython-39-darwin.so' (no such file)`

PS: Earlier i had been using psycopg2 on this very same system(without the recent OS upgrade) without any problem.

**Comment by dvarrazzo** [comment]
I'm afraid we can't help with your OS upgrade. You should ask Apple supportl

**Comment by mralexosborn** [comment]
@dvarrazzo I am experiencing the same problem as above but on a new M1 Mac. Any recommendations?

**Comment by dvarrazzo** [comment]
@mralexosborn my recommendation is that you could ask the Apple customer support, and report back the solution they will give you, which will be helpful to everyone experiencing the same problem.
