### ISSUE TITLE
AssertionError: database connection isn't set to UTC

### ISSUE THREAD

**Issue by Infoidic** [psycopg/psycopg2#1405]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Windows
- Psycopg version:2.9.2
- Python version:3.10.1
- PostgreSQL version:14.1
- pip version:

**Describe the bug**
Please let us know:

1: what you did: I activated the virtual en using "python manage.py runserver"
2: what you expected to happen: The server never run 
3: what happened instead: AssertionError: database connection isn't set to UTC
![Captura](https://user-images.githubusercontent.com/74676749/146982488-650824e4-1024-47c5-b17a-bc1fe2f095e3.PNG)
4. I tryied to downgrade but did not work.

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
This is a known incompatibility between psycopg 2.9 and Django 2.2. See #1293.

Downgrade psycopg to 2.8.x, or upgrade Django.
