### ISSUE TITLE
AutoCommit flag broken since 2.9 release 

### ISSUE THREAD

**Issue by Svet3** [psycopg/psycopg2#1406]
```
import psycopg2

with psycopg2.connect("host=localhost port=5432 user=postgres password=postgres dbname=postgres") as connection:
    connection.set_session(autocommit=True)
    with connection.cursor() as cursor:
        cursor.execute("CREATE DATABASE bug_repro")
```

Produces the following error with release 2.9 and later:
`psycopg2.errors.ActiveSqlTransaction: CREATE DATABASE cannot run inside a transaction block`

Snippet works fine with release 2.8.6. I also tried various other ways of setting the autocommit flag and also changing transaction isolation settings, could not get it to work in 2.9

**Comment by dvarrazzo** [comment]
Don't use `with psycopg2.connect()`, use just `connection = psycopg2.connect()`. `with connect` has been documented forever to *open a transaction*. It *doesn't close* the connection at the end.

**Comment by Svet3** [comment]
Why would you use "with" to create a transaction and manage its lifecycle instead of managing the lifecycle of the connection?

With your suggestion the code becomes:
```
import psycopg2

connection = psycopg2.connect("host=localhost port=5432 user=postgres password=postgres dbname=postgres")
try:
    connection.set_session(autocommit=True)
    with connection.cursor() as cursor:
        cursor.execute("CREATE DATABASE bug_repro")
finally:
    connection.close()
```
which is exactly the code pattern the "with" keyword is supposed to enforce. 

However I can confirm your suggestion fixes the original issue I raised when using release 2.9.

**Comment by dvarrazzo** [comment]
@Svet3 using `with` to manage transactions is an idea discussed in the DB-SIG several years ago. Back then, it looked like a good idea. Years of people expecting tthat `with` closed the connection teached that this wasn't the case.

In psycopg 3 [the behaviour is less surprising](https://www.psycopg.org/psycopg3/docs/basic/usage.html#connection-context), but it is a non-backward compatible change, so psycopg 2 will stay as it is.

**Comment by Svet3** [comment]
Thank you for the explanation. 

Also thank you for drawing to my attention to the fact that there is a psycopg 3 now.
