### ISSUE TITLE
Need string quoting function for DDL commands

### ISSUE THREAD

**Issue by nagylzs** [psycopg/psycopg2#1409]
Example:

```
connection.execute("ALTER USER postgres WITH PASSWORD %s", [ "some_password" ])
```

The above statement produces this error **on the PostgreSQL server**:

```
2022-01-05 17:35:25.831 CET [58] ERROR:  syntax error at or near "$1" at character 35
2022-01-05 17:35:25.831 CET [58] STATEMENT:  ALTER USER postgres WITH PASSWORD $1
```

The problem is that some DDL commands don't accept parameters. The only possible solution is to quote these values on the client side, and send the command to the server as a single string, without parameters.

Since psycopg3 does not provide a function to quote strings safely, every user needs to implement his/her own version of string quoting. Some of them might contain errors and lead to program crash or even SQL injection. I think that it would be better if psycopg3 provided its own quoting function (at least for strings).

**Comment by dvarrazzo** [comment]
This is a psycopg 3 related ticket, not psycopg2.

> The problem is that some DDL commands don't accept parameters. The only possible solution is to quote these values on the client side, and send the command to the server as a single string, without parameters.

The issue is know and the workarounds [documented](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#server-side-binding).

> Since psycopg3 does not provide a function to quote strings safely, every user needs to implement his/her own version of string quoting. Some of them might contain errors and lead to program crash or even SQL injection. I think that it would be better if psycopg3 provided its own quoting function (at least for strings).

Psycopg 3 (and 2) provide an entire framework to do client-side dynamic SQL composition: https://www.psycopg.org/psycopg3/docs/api/sql.html
