### ISSUE TITLE
cannot import name 'encodings' from psycopg2._psycopg

### ISSUE THREAD

**Issue by rhl-it** [psycopg/psycopg2#1414]
Import Error: cannot import name 'encodings' from 'psycopg2._psycopg' ... file path ... /psycopg2/_psycopg.cpython-39-x86_64-linux-gnu.so

I am experiencing this error on:
Debian 11 Bullseye with apache2 (2.4.52), mod_wsgi (4.9.0) (installed with pip into a virtual environment), psycopg2-binary (2.9.2 & 2.9.3) (installed with pip into a virtual environment), python 3.9, Django 4.0
This only causes an error while hosting 2 sites;  each site loads correctly and behaves correctly independently, when I try to access the other site, this error shows up in the logs and the website has the 500 internal server error returned.

I have temporarily avoided this error by commenting out the code requiring the encodings import in the extensions.py file.  I haven't tested this "solution" with 2.9.3 as it's not really preferable.

**Comment by dvarrazzo** [comment]
Please report the issue to mod_wsgi: they might be able to explain how to avoid the problem.

Psycopg is not doing anything wrong here.

**Comment by GMaxera** [comment]
@rhl-it Did you find a workaround? I'm hitting the same issue

**Comment by rhl-it** [comment]
Yeah, I contacted Graham from mod_wsgi.  The solution was to change my configuration in apache.

WSGIDaemonProcess <process name> python-home=<python path> python-path=<wsgi.py path>
WSGIScriptAlias <site path> <wsgi.py path> process-group=<process name> application-group=%{GLOBAL}

Use the above 2 lines for each site / project you need to run on the webserver.  These go in your virtual host configuration in apache.

**Comment by rhl-it** [comment]
The thread over at mod_wsgi is here: https://github.com/GrahamDumpleton/mod_wsgi/issues/753
