### ISSUE TITLE
problem when launching a query

### ISSUE THREAD

**Issue by ydarmon** [psycopg/psycopg2#1415]
**Please complete the following information:**
- OS: centos
- Psycopg version: 2.7.4
- Python version:3.7.5
- PostgreSQL version: 14
- pip version: 9.0.3
The installation was `pip install psycopg2-binary`

**Describe the bug**
Hello
I use psycopg2 to launch a query which contain inner join ... on a table. The query is working when the table contain 81865 rows but with 81866 rows the query runs but doesn't finish.
The query is correct and has indexes , so the problem is not the query.

Is there something in this library that causing this problem?

**Comment by dvarrazzo** [comment]
No, it is surely not a psycopg problem. Verify the same query on the same database with psql.

**Comment by ydarmon** [comment]
The same query is working with psql
