### ISSUE TITLE
Vague specification of "with statement" leading to CockroachDB anomalies

### ISSUE THREAD

**Issue by 20211202na** [psycopg/psycopg2#1424]
We, as well as the CockroachDB collaborator, found vague informal specification of "with statement", which had resulted in CockroachDB isolation level anomalies. 

The confusion stemmed from the following claim (snapshot taken from https://www.psycopg.org/docs/usage.html#transactions-control):

![image](https://user-images.githubusercontent.com/96566054/153858257-36dbb037-4f50-4b1d-ad6b-126902b76679.png)

In particular, when it says "the transaction IS committed", how would one know that it actually means "trying to commit"? One would naturally thought that some mechanisms like retrying, implemented under the hood, have taken care of any conflict. After further investigation on CockroachDB's use of psycopg2, it became clear that a user must (i) explicitly use the "commit" op for each "with" block in the above example, and (ii) explicitly deal with different kinds of exceptions, not just at the (conflicting) transactional operation level. See https://github.com/cockroachdb/cockroach/issues/76436#issue-1132783748 for the issue and discussion.

To make any psycopg2er's life easier, it would be great to improve the informal spec and illustrating example w.r.t. e.g., multi-with-statements within a connection, and to make it explicit for catching different types of exceptions.

**Comment by dvarrazzo** [comment]
No.

First, psycopg is a Postgres driver. CockroachDB happens to have the same line protocol but we don't support it in any special way.

Second: *the transaction IS committed" means that Psycopg runs a COMMIT. If there is an exception it is correctly propagated.

```
create table willerror(id integer primary key, ref integer references willerror(id) deferrable initially deferred);
```

```python
>>> with psycopg2.connect("") as conn:
...     cur = conn.cursor()
...     cur.execute("insert into willerror values (1, 2)") 
...     print("executed") 
... 
executed
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
psycopg2.errors.ForeignKeyViolation: insert or update on table "willerror" violates foreign key constraint "willerror_ref_fkey"
DETAIL:  Key (ref)=(2) is not present in table "willerror".
```

So, if there is an error on commit, you receive it.

> One would naturally thought that some mechanisms like retrying, implemented under the hood, have taken care of any conflict.

Do you really believe in this sentence you wrote here or did you write it just to vent? Why should psycopg - a driver for postgres - have some special logic to conflict to what the server is doing?

Psycopg is a client library: **OF COURSE** when it says "it does an operation" it means that "it will try to do an operation". If the server gives an error, its role is to report it back in the form of an exception. If we are missing to do it somewhere, that's a bug we will address. The documentation of `execute()` is "it runs a query in the server": does it have to be "it tries to run a query in the server but that query might fail too"? It is clear that a client has only the power of sending operation to the server and what the server will do of them is not under its control: any different expectation is misplaced.

**Comment by 20211202na** [comment]
> Do you really believe in this sentence you wrote here or did you write it just to vent? Why should psycopg - a driver for postgres - have some special logic to conflict to what the server is doing?
> 
You are right. I though of psycopg and crdb as a whole when I said that. Thanks!
