### ISSUE TITLE
Closing as the issue is long fixed and is attracting unrelated search results.

### ISSUE THREAD

**Issue by jha7it** [psycopg/psycopg2#1429]
This is actually not yet resolved, it is still creating an issue in python 3.10. Please suggest.
DLL load failed while importing _psycopg: The specified module could not be found.

**Comment by dvarrazzo** [comment]
The issue you refer to is about Python 3.9.

I closed the issue because the issue is closed. Python 3.10 works if your Python installation is not broken.

I am not under obligation to fix your computer for free. If you open another ticket on this tone I will block you from the project.
