### ISSUE TITLE
Different result using psycopg2 vs jdbc with extra_float_digits on Redshift

### ISSUE THREAD

**Issue by MasterOdin** [psycopg/psycopg2#1430]
**Please complete the following information:**
- OS: macos 12.2.1
- Psycopg version: 2.9.3
- Python version: 3.9.10
- PostgreSQL version: 8.0.2 (Redshift)
- pip version: 21.3.1

**Describe the bug**

I created a table in Redshift using the following:
```
CREATE TABLE real1 ( realcol real );

INSERT INTO real1 VALUES (12345.123);
INSERT INTO real1 VALUES (123456.12);
```

I then issue the following queries using psycopg2 and jdbc:
```
SET extra_float_digits = 0;
SELECT * FROM real1;
SET extra_float_digits = 2;
SELECT * FROM real1;
```

From the first select, I expect to get back:
```
+-----------+
|  realcol  |
+-----------+
| 12345.1   |
| 123456.0  |
+-----------+
```

With the second select, I expect to get back:
```
+--------------+
|   realcol    |
+--------------+
| 12345.123    |
| 123456.12    |
+--------------+
```

This happens when using the postgresql JDBC connector, but not when using psycopg2, which just returns that first table twice. If I do `SELECT 123456.1::real`, then I do get back `123456.1` from psycopg2 with `extra_float_digits = 2` so the setting is being properly detected, it's just seemingly not getting the right data out of the table compared to JDBC.

**Comment by dvarrazzo** [comment]
It seems working as expected, using PostgreSQL:

```
In [1]: import psycopg2                                                                                              
In [2]: cnn = psycopg2.connect()                                                                                     
In [3]: cur = cnn.cursor()                                                                                           

In [4]: cur.execute("SET extra_float_digits = 0;")                                                                   
In [5]: cur.execute("SELECT * FROM real1;")                                                                          
In [6]: cur.fetchall()                                                                                               
Out[6]: [(12345.1,), (123456.0,)]

In [7]: cur.execute("SET extra_float_digits = 2;")                                                                   
In [8]: cur.execute("SELECT * FROM real1;")                                                                          
In [9]: cur.fetchall()                                                                                               
Out[9]: [(12345.123,), (123456.12,)]
```

Psycopg is a PostgreSQL driver, Redshift is a proprietary database that is only accidentally partially supported because it uses the same line protocol. I personally think that you have made some mistakes in your test, but this is as far as I can go.

We don't offer Redshift support for free. If you need anything more specific for that database it will have to be a paid collaboration.
