### ISSUE TITLE
conn.notices not displaying fully

### ISSUE THREAD

**Issue by Kayden-lolasery** [psycopg/psycopg2#1437]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: macOS monterey v12.1
- Psycopg version: 2.9.3
- Python version: 3.9.10
- PostgreSQL version: PostgreSQL 12.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
- pip version: pip 21.3.1

**Describe the bug**
the NOTICE is psycogpg for dropping non-existent tables is incomplete

1: what you did:
- Dropped a non-existent table (e.g. table name doesn't exist)

2: what you expected to happen:
- The full print statement to occur:
- std output: NOTICE:  table "table_name" does not exist, skipping **DROP TABLE**

3: what happened instead:
- a partial print occured:
- std output: NOTICE:  table "table_name" does not exist, skipping

If possible, provide a script reproducing the issue.
```
import psycopg2
conn = psycopg2.connect("user details")
cur = conn.cursor()
cur.execute(f'''DROP TABLE IF EXISTS "{schema}".{table}''')
conn.commit()
for notice in conn.notices:
    print(notice)
cur.close()
conn.close()
```

**Comment by dvarrazzo** [comment]
DROP TABLE is not part of the notice: you will find it in [`cur.statusmessage`](https://www.psycopg.org/docs/cursor.html#cursor.statusmessage).

psql prints both to stdout: if you drop an existing table you will see DROP TABLE but not the notice.

**Comment by Kayden-lolasery** [comment]
@dvarrazzo Thank you!
