### ISSUE TITLE
insert vs copy

### ISSUE THREAD

**Issue by cxin-william** [psycopg/psycopg2#1446]
Why is insert faster than copy when I use copy and INSERT?
300,000 pieces of data need_time：0:00:46.924713 copy
200,000 pieces of data need_time：0:00:49.978406 insert

2 million pieces of data need_time：0:09:34.036849 copy
2 million pieces of data need_time：0:08:26.001075 insert

`def write_to_table(df, schema, table_name, if_exists='append'): import io import pandas as pd from utils_all import create_connection db_engine = create_connection(**************************) string_data_io = io.StringIO() df.to_csv(string_data_io, sep='|', index=False) pd_sql_engine = pd.io.sql.pandasSQL_builder(db_engine) table = pd.io.sql.SQLTable(table_name, pd_sql_engine, frame=df, index=False, if_exists=if_exists, schema=f'{schema}') table.create() string_data_io.seek(0) string_data_io.readline() # remove header with db_engine.connect() as connection: with connection.connection.cursor() as cursor: copy_cmd = f"COPY {schema}.%s FROM STDIN HEADER DELIMITER '|' CSV" % table_name cursor.copy_expert(copy_cmd, string_data_io) connection.connection.commit()`

**Comment by dvarrazzo** [comment]
I don't know, but it's not a bug.

Your code is unreadable by the way.

**Comment by cxin-william** [comment]
Can you give me the fastest way to insert pg? My idol



> I don't know, but it's not a bug.
> 
> Your code is unreadable by the way.

**Comment by cxin-william** [comment]
> Can you give me the fastest way to insert pg? My idol
> 
> > I don't know, but it's not a bug.
> > Your code is unreadable by the way.
i am sorry
`def write_to_table(df, schema, table_name, if_exists='append'):
    import io
    import pandas as pd
    from utils_all import create_connection
    db_engine = create_connection(**********)
    string_data_io = io.StringIO()
    df.to_csv(string_data_io, sep='|', index=False)
    pd_sql_engine = pd.io.sql.pandasSQL_builder(db_engine)
    table = pd.io.sql.SQLTable(table_name, pd_sql_engine, frame=df,
                               index=False, if_exists=if_exists, schema=f'{schema}')
    table.create()
    string_data_io.seek(0)
    string_data_io.readline()  # remove header
    with db_engine.connect() as connection:
        with connection.connection.cursor() as cursor:
            copy_cmd = f"COPY {schema}.%s FROM STDIN HEADER DELIMITER '|' CSV" % table_name
            cursor.copy_expert(copy_cmd, string_data_io)
        connection.connection.commit()`

**Comment by dvarrazzo** [comment]
I don't see anything bad in that example. Maybe you should increase postgres resources. Please write to the pgsql-ganaral mailing list to ask for advice.

**Comment by cxin-william** [comment]
> I don't see anything bad in that example. Maybe you should increase postgres resources. Please write to the pgsql-ganaral mailing list to ask for advice.

ok thanks
