### ISSUE TITLE
psycopg2-binary on Windows requires pg_config

### ISSUE THREAD

**Issue by ianjevans** [psycopg/psycopg2#1448]
**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [ ] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

I'm using this with CockroachDB, specifically a CockroachDB Serverless cluster, so my client shouldn't require `pg_config`.

**Please complete the following information:**
- OS: Windows Server 2016 Datacenter
- Psycopg version: 2.8.6
- Python version: 3.10
- PostgreSQL version: n/a
- pip version 22.0.4

I'm testing the Python sample of the CockroachDB Quickstart samples: https://github.com/cockroachdb/quickstart-code-samples

We use `psycopg2-binary` to avoid requiring PostgreSQL artifacts. In this case, I'm connecting to a remote Serverless instance of CockroachDB. But I'm getting this error when installing `psycopg2-binary`:

~~~
pip install -r requirements.txt
Collecting psycopg2-binary==2.8.6
  Using cached psycopg2-binary-2.8.6.tar.gz (384 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating D:\Users\ian\AppData\Local\Temp\1\pip-pip-egg-info-5j0goneb\psycopg2_binary.egg-info
      writing D:\Users\ian\AppData\Local\Temp\1\pip-pip-egg-info-5j0goneb\psycopg2_binary.egg-info\PKG-INFO
      writing dependency_links to D:\Users\ian\AppData\Local\Temp\1\pip-pip-egg-info-5j0goneb\psycopg2_binary.egg-info\dependency_links.txt
      writing top-level names to D:\Users\ian\AppData\Local\Temp\1\pip-pip-egg-info-5j0goneb\psycopg2_binary.egg-info\top_level.txt
      writing manifest file 'D:\Users\ian\AppData\Local\Temp\1\pip-pip-egg-info-5j0goneb\psycopg2_binary.egg-info\SOURCES.txt'

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~~~

According to your install docs, using `psycopg2-binary` should mean that I don't have the build or runtime requirements of the source packge. We use `psycopg2-binary` for our samples on Linux and Mac without issues.

**Comment by dvarrazzo** [comment]
Psycopg 2.8.6 predates Python 3.10. As far as I see on PyPI, Psycopg 2.9.1 is the first version for which wheel packages were released.
