### ISSUE TITLE
Why is there a time difference between the two installation methods pip install and conda install?

### ISSUE THREAD

**Issue by Yoosangcheol3730** [psycopg/psycopg2#1453]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: windows 10 pro 64-bit
- Psycopg version: 2.9.3
- Python version: 3.9.12
- PostgreSQL version: PostgreSQL 14.0
- pip version: 22.0.4

**Describe the bug**
Please let us know:

1: what you did
I'm using psycopg2 package to connect with my PostgreSQL DB. So I installed the psycopg2 package with conda install. But, when I using the psycopg2, I thought even a simple select implementation took too long. So, I checked the implementation time about db connection and cursor execution. DB connection took about 4.5 sec and execution took about 6 sec. I thought the DB connection time is too long. So, I compared the DB connection time to my coworker. My coworker has same environment like me. But my coworker's DB connection time took just 0.02 sec. I found that my coworker installed the psycopg2 package using pip. The only difference is install method.

**Why is there a time difference between the two installation methods pip install and conda install?**

If possible, provide a script reproducing the issue.
![image](https://user-images.githubusercontent.com/42920902/167977822-979272c6-8498-4a02-b0ee-6b4c6218629a.png)
![image](https://user-images.githubusercontent.com/42920902/167977743-4b490be8-b44b-4c3e-b631-bc5ce6b99c5b.png)

**Comment by dvarrazzo** [comment]
Conda is not supported by psycopg2. I have never used conda once in my life.

If Conda claims to support psycopg2, please open a ticket with them.

**Comment by Yoosangcheol3730** [comment]
@dvarrazzo 
I'm sorry, what does the ticket mean?

**Comment by dvarrazzo** [comment]
That we cannot give you an answer because we don't manage conda. Ask conda.
