### ISSUE TITLE
psycopg2==2.8.6,<3.0 is not satisfied

### ISSUE THREAD

**Issue by Shawty97** [psycopg/psycopg2#1454]
I failed to install "psycopg2==2.8.6,<3.0 "
I tried so much with pycharm, with the terminal and so on...
Everything what they wanted from me in pycharm.

the error was like :  

*
**### C:\Users\Admin\focalevents>pip install psycopg2-binary
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.3-cp310-cp310-win_amd64.whl (1.2 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.3

C:\Users\Admin\focalevents>pip install -U pip
Requirement already satisfied: pip in c:\users\admin\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (22.1)

C:\Users\Admin\focalevents>pip install --no-binary :all: psycopg2
Collecting psycopg2
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ---------------------------------------- 380.6/380.6 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-ibvtwsun\psycopg2.egg-info
      writing C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-ibvtwsun\psycopg2.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-ibvtwsun\psycopg2.egg-info\dependency_links.txt
      writing top-level names to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-ibvtwsun\psycopg2.egg-info\top_level.txt
      writing manifest file 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-ibvtwsun\psycopg2.egg-info\SOURCES.txt'
     
      Error: pg_config executable not found.
     
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
     
          python setup.py build_ext --pg-config /path/to/pg_config build ...
     
      or with the pg_config option in 'setup.cfg'.
     
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
     
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Admin\focalevents>pip install --no-binary psycopg2
ERROR: You must give at least one requirement to install (see "pip help install")

C:\Users\Admin\focalevents>psycopg2>=2.7,<2.8 --no-binary psycopg2
Das System kann die angegebene Datei nicht finden.

C:\Users\Admin\focalevents>brew install postgresql
Der Befehl "brew" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\Admin\focalevents>pip install psycopg2-binary==2.8.6
Collecting psycopg2-binary==2.8.6
  Downloading psycopg2-binary-2.8.6.tar.gz (384 kB)
     ---------------------------------------- 384.7/384.7 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-sz6xet2s\psycopg2_binary.egg-info
      writing C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-sz6xet2s\psycopg2_binary.egg-info\PKG-INFO
      writing dependency_links to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-sz6xet2s\psycopg2_binary.egg-info\dependency_links.txt
      writing top-level names to C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-sz6xet2s\psycopg2_binary.egg-info\top_level.txt
      writing manifest file 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-sz6xet2s\psycopg2_binary.egg-info\SOURCES.txt'
     
      Error: pg_config executable not found.
     
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
     
          python setup.py build_ext --pg-config /path/to/pg_config build ...
     
      or with the pg_config option in 'setup.cfg'.
     
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
     
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**

*

THIS is a problem which I spent over 4 hours , where I wanted to solve this one but solved other probs :D 
I do not know how to do the next steps.
I hope some one can help me! 

See ya tomorrow

- OS: Windows 10
- Psycopg version: 2.8.6
- Python version: 3.10.4

**Comment by dvarrazzo** [comment]
Psycopg 2.8.6 is not available for Python 3.10, binary packages are not on pypi: https://pypi.org/project/psycopg2/2.8.6/#files

It seems that the first version supporting Python 3.10 was 2.9.1.
