### ISSUE TITLE
Inserting multiple rows into tables

### ISSUE THREAD

**Issue by Borra4300** [psycopg/psycopg2#1455]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Ubuntu 20.04
- Psycopg version: 2.9.3
- Python version: 3.9
- PostgreSQL version: 12.10
- pip version : 20.0.2

**Describe the bug**
Please let us know:

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.
Traceback (most recent call last):
  File "/home/mohan4300/PycharmProjects/Mongo2Postgre/replacements.py", line 39, in <module>
    result = db_cursor.execute(insert_query)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(25)

while inserting multiple rows into tables via psycopg package, i am getting this error. I haven't given any limit. I gave text as a datatype. I can able to insert multiple rows at a time in console. 

insert_query = 'INSERT INTO replacements ' + '(acid, afcenter, asin, brid, chsku, cid, moid, rafcenter, reprecode, rmoid, shipdt, chid, endt, flgdone, qty)' + ' VALUES ' + (
    args)
result = db_cursor.execute(insert_query)

**Comment by dvarrazzo** [comment]
The error says clearly that the data type is `varchar(25)`. You can verify it in psql using `\d TABLENAME`. You should fix your schema.

**Comment by dvarrazzo** [comment]
In this case you are connecting to the wrong database. The error message "value too long for type character varying(25)" is not made up by psycopg: it comes from a server error.

**Comment by Borra4300** [comment]
no bro. I am connecting to same database only

**Comment by dvarrazzo** [comment]
Damn bro, you got us. We make up error messages. Our evil plan to rule the world has been defeated.

**Comment by Borra4300** [comment]
sorry bro, without complete knowledge i have raised an issue. I will correct myself. Sorry for wasting your time.
