### ISSUE TITLE
"column does not exist error" when there should be a type error

### ISSUE THREAD

**Issue by oconnoob** [psycopg/psycopg2#1461]
**Please complete the following information:**
- OS: Win11
- Psycopg version: 2.9.3
- Python version: 3.10
- PostgreSQL version: 14
- pip version: 22.1

**Describe the bug**
When inserting into a table, if an erroneous datatype is used, the error thrown says that the column does not exist.

1: what you did
Given a table "t" with columns "c1", "c2", and "c3", all of type integer, when I use a cursor object `cur` to execute `cur.execute("INSERT INTO t (c1,c2) VALUES (1,string),(2,4);", the error thrown indicates that the column "string" does not exist. I believe this is a type error instead, so it would be good to have the error indicate that.

2: what you expected to happen
I expected the error thrown to indicate that there was a type error

3: what happened instead
The error thrown indicated a column does not exist error instead

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
As far as I can see it is not a TypeError, it is a NameError. That's what Python would do if a name is not defined. Your error is not about a wrong data type but about an undefined name.

```
$ python -c hello
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'hello' is not defined
```

However, the DBAPI suggests a separate errors hierarchy for errors originating from the database: you can [find it here](https://peps.python.org/pep-0249/#exceptions). One of these is:

> [ProgrammingError](https://peps.python.org/pep-0249/#programmingerror)
>     Exception raised for programming errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified, etc. It must be a subclass of [DatabaseError](https://peps.python.org/pep-0249/#databaseerror).

Which is pretty clearly the case. Psycopg maps the errors generated from the server on subclasses of the DBAPI exception: it takes the SQLSTATE - a code associated to most database exceptions:

```
piro=# select hello;
ERROR:  column "hello" does not exist
LINE 1: select hello;
               ^
piro=# \errverbose
ERROR:  42703: column "hello" does not exist
LINE 1: select hello;
               ^
LOCATION:  errorMissingColumn, parse_relation.c:3349
```
...and maps the code 42703 to a [ProgrammingError subclass](https://github.com/psycopg/psycopg/blob/3acc1d2136a7a7b0276c53c23d789cc3a0b8dd6f/psycopg/psycopg/errors.py#L1095-L1097).

Changing it to a different exception would be a backward-incompatible change. If we had a reason to do it we would do it in psycopg 4 now. However it would be a violation of the DBAPI, so I don't think it will happen.
