### ISSUE TITLE
Why is fetcchall returning [None] when documentation says it shold return []?

### ISSUE THREAD

**Issue by Yasen6275** [psycopg/psycopg2#1463]
- OS:Devuan GNU/Linux 3 (beowulf)
- Psycopg version: 2.8.6 (from OS repo)
- Python version: 3.7.3
- PostgreSQL version: 13.6-1.pgdg100+1
- pip version (N/A)

According to documentation when database returns no results, fetchall should return empty list. For me empty list is [] but I  get [None]. Is this a bug or incorrect documentations?

**Comment by dvarrazzo** [comment]
Can you show an example?

**Comment by dvarrazzo** [comment]
No worries 👍
