### ISSUE TITLE
sudo apt-get install python-psycopg2

### ISSUE THREAD

**Issue by JonhSilver** [psycopg/psycopg2#1464]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS:
Ubuntu 12.11-0ubuntu0.20.04.1
- Psycopg version:
psycopg2-2.8.6
- Python version:
Python 2.7.18
- PostgreSQL version:
psql (PostgreSQL) 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
- pip version 
pip 20.3.4 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

sudo apt-get install python-psycopg2

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-psycopg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-psycopg2' has no installation candidate

**Comment by dvarrazzo** [comment]
`python3-psycopg2`.

**Comment by iamlauriano** [comment]
Tip:
Use sudo apt install python3-psycopg2
