### ISSUE TITLE
ImportError: No module named psycopg1

### ISSUE THREAD

**Issue by JonhSilver** [psycopg/psycopg2#1465]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
OS:
Ubuntu 12.11-0ubuntu0.20.04.1
Psycopg version:
psycopg2-2.8.6
Python version:
Python 2.7.18
PostgreSQL version:
psql (PostgreSQL) 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
pip version
pip 20.3.4 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

**Describe the bug**
Please let us know: ImportError: No module named psycopg1

1: what you did 
pip install psycopg2-binary
Successfully installed psycopg2-binary-2.8.6
2: what you expected to happen
no error
3: what happened instead
    from psycopg2.psycopg1 import cursor as psycopg1cursor
ImportError: No module named psycopg1

If possible, provide a script reproducing the issue.

https://nightly.odoo.com/old/openerp-6.0/6.0.4-last-nightly/openerp-server-6.0.4.tar.gz
/bin/sql_db.py

**Comment by dvarrazzo** [comment]
The module psycopg1 was dropped in 2.8.

Psycopg 1 has been deprecated for the good part of 16 years...
