### ISSUE TITLE
Problem with install on M1 Pro chip and Python 3.10.5

### ISSUE THREAD

**Issue by lozik4** [psycopg/psycopg2#1470]
**This is a bug tracker**
If I install psycopg2-binary I have this error:

```
mp.macosx-10.9-universal2-3.10/psycopg/utils.o build/temp.macosx-10.9-universal2-3.10/psycopg/win32_support.o build/temp.macosx-10.9-universal2-3.10/psycopg/xid_type.o -L/opt/homebrew/opt/libpq/lib -lpq -lssl -lcrypto -o build/lib.macosx-10.9-universal2-3.10/psycopg2/_psycopg.cpython-310-darwin.so
      ld: library not found for -lssl
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psycopg2-binary

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] I am not trying to install `psycopg2-binary` on an Apple M1, for which [binary packages are not supported](https://github.com/psycopg/psycopg2/issues/1286)
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: MacOS Chip M1 Pro
- Psycopg version: 2.9.3
- Python version: 3.10.5
- PostgreSQL version: 14.4
- pip version: 22.1.2

**Comment by dvarrazzo** [comment]
Binary packages are not supported yet on M1. Support should be added this summer, but it's not a priority as using M1 runner in workflows doesn't come for free (thanks to Apple policies) and I haven't received funding for this work.

Closing the ticket as there is already another open.
