### ISSUE TITLE
Documentation for ext.quote_ident

### ISSUE THREAD

**Issue by aklaver** [psycopg/psycopg2#1481]
psycopg2.__version__                                                                                                                                                      
 '2.9.3 (dt dec pq3 ext lo64)'

 The docs from here [sql](https://www.psycopg.org/docs/sql.html) show:

```
table_name = 'my_table'
cur.execute(
    "insert into %s values (%%s, %%s)" % ext.quote_ident(table_name),
    [10, 20])
```

But when I try:

```
table = 'animals'
cur.execute("select * from %s"  % ext.quote_ident(table))

TypeError                                 Traceback (most recent call last)
<ipython-input-12-579b48b71577> in <module>
----> 1 cur.execute("select * from %s"  % ext.quote_ident(table))

TypeError: function missing required argument 'scope' (pos 2)
```

This works:

`cur.execute("select * from %s"  % ext.quote_ident(table, cur))`

which matches from here [quote_ident](https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.quote_ident):

` psycopg2.extensions.quote_ident(str, scope)`

So I'm thinking the example should read?:

`% ext.quote_ident(table_name, cur)`

**Comment by dvarrazzo** [comment]
You are right, good catch :) fixing it...
