### ISSUE TITLE
Feature Request: MultiRange types

### ISSUE THREAD

**Issue by saosebastiao** [psycopg/psycopg2#1485]
**Please complete the following information:**

- PostgreSQL version: 14+

Postgres has released a new MultiRange type which has some useful benefits over the traditional range types for certain arithmetic operations (such as range differences), as well as any situation that requires non-contiguous ranges. 

Internally, Postgres represents these as an array of ranges, so I think any implementation in psycopg2 could be similar, but it would be helpful to have an idiomatic way of working with them like we do with the range types.

**Comment by dvarrazzo** [comment]
Multiranges are [already implemented in psycopg 3](https://www.psycopg.org/psycopg3/docs/basic/pgtypes.html#multirange-adaptation).

I'm not planning to backport the feature in psycopg2, unless there is financial support for its development.
