### ISSUE TITLE
authentication fails intermittently

### ISSUE THREAD

**Issue by cheradenine** [psycopg/psycopg2#1486]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Docker running on Debian 11, psql in alpine, python on debian 10 (python-slim-buster)
- Psycopg version: '2.9.3 (dt dec pq3 ext lo64)'
- Python version: 3.10.5
- PostgreSQL version: 13.3
- pip version 22.04

**Describe the bug**
Please let us know:

1: what you did

Docker setup:
Configured Django app server in one container running python 3.10.5-slim-buster. Installs psycopg2-binary==2.9.3
Configured postgres container postgres:13.3-alpine3.14
Database, user and passwords are set via config variables in a .env file

2: what you expected to happen

Connection between Django and postgres works reliably

3: what happened instead

Intermittent failure to authenticate. Sometimes the connection is made and requests are fine, then the connection fails with the same dsn. The error message is failure to authentication (as reported via postgres):
`FATAL:  password authentication failed for user "my_user"`

If possible, provide a script reproducing the issue.

A script might be possible - would have to duplicate the dockerfile, docker-compose and configs. Here is an interactive session showing the problem. As you can see, a connection succeeds, then fails. What I'm seeing in my web server is similar. Sometimes the connection is fine, other times it fails.

```
>>> psycopg2.__version__
'2.9.3 (dt dec pq3 ext lo64)'
>>> c = psycopg2.connect("dbname=my_db user=my_user host=db password=MyPassword port=5432")
>>> c
<connection object at 0x7f02b8275e40; dsn: 'user=my_user password=xxx dbname=my_db host=db port=5432', closed: 0>
>>> c.close()
>>> c
<connection object at 0x7f02b8275e40; dsn: 'user=my_user password=xxx dbname=my_db host=db port=5432', closed: 1>
>>> c = psycopg2.connect("dbname=my_db user=my_user host=db password=MyPassword port=5432")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "db" (172.18.0.4), port 5432 failed: FATAL:  password authentication failed for user "my_user"
```

**Comment by cheradenine** [comment]
I just rebuilt my Django/psycopg2 image using `python:3.10.5-slim-bullseye`
And also upgraded postgres to 14 `postgres:14.5-alpine3.16`

Same issue - connection works sometimes and other times fails with an authentication error. I don't see any deterministic way to make it succeed or fail. If I run interactive and try `psycopg2.connect` multiple times (same dsn), it randomly fails some of the time.

postgres logs don't show anything - maybe there is a way I can enable more logging there?

**Comment by dvarrazzo** [comment]
The error you are receiving is an error from a server. Authentication failed usually leaves an entry in the logs. For me it means that in your network setup, every now and then your request goes to a database you don't expect. I don't know if it's the DNS acting up or docker networking, however it doesn't seem a problem on the client.

**Comment by cheradenine** [comment]
Thank you! Gave me a pointer of where to look and yes, another service with the same name on the same docker network was causing this.
