### ISSUE TITLE
The function psycopg2.extras.register_composite doesn't regard the search path

### ISSUE THREAD

**Issue by papel** [psycopg/psycopg2#1487]
**Please complete the following information:**
- OS: Linux 5.10.0-13-amd64
- Psycopg version: 2.9.3
- Python version: 3.9.2
- PostgreSQL version: 13.7
- pip version: 20.3.4

**Describe the bug**
I am trying to use psycopg2.extras.register_composite using the search path.

I use the following connection to use the schema appdata instead of public without having to put the prefix with the name of the schema. It works for queries and the tables don't need the prefix, but the function register_composite isn't affected by it.
```
	psycopg2.connect(
		host="localhost",
		port="5432",
		user="myuser",
		database= ...,
		password=...,
		options=f'-c search_path="appdata"',
		cursor_factory=psycopg2.extras.NamedTupleCursor
	)

	#Error: PostgreSQL type 'bivalue' not found
	psycopg2.extras.register_composite('bivalue', cur);

	#This works
	psycopg2.extras.register_composite('appdata.bivalue', cur);
```

I want to avoid the name of the schema repeated in many places in the app. It should be set only in one place.

**Comment by dvarrazzo** [comment]
You are right: this function has a pretty old and has a weak and broken resolution of the type name. I am surprised nobody found this problem earlier.

https://github.com/psycopg/psycopg2/blob/3e7bb8d1aa631320234f9e05ef940a1d1e9a627f/lib/extras.py#L1078-L1097

The consensus, when a procedure needs a database object as input, is to specify it in a way that `regtype` understands: `foo` is looked for in the `search_path`, `foo.bar` is interpreted as schema-qualified object, `"foo.bar"`, including the quotes, is a name with a dot to be found in the `search_path`, `"foo-bar"."qux.quux"`... you get the idea. This is what postgres tools such as pgdump do to disambiguate input objects passed as parameters. 

An implementation along this line [can be found in psycopg 3](https://github.com/psycopg/psycopg/blob/5d18c8a6ccbd37821af5a060d0a4086a8bf95d20/psycopg/psycopg/_typeinfo.py#L265-L293
): see the `where t.oid = %(name)s::regtype`.

So yes: I agree that this function should be fixed. However here we are in Hyrum realm: this function has been broken for 12 years and I'm sure (by the fallout of changing the way copy takes tables names see - #1294) that someone is relying on its current behaviour just as it is. So I would:

- look for the type using the current algorithm
- if not found, look for the type using the `regtype` algorithm

Does it sound ok?
