### ISSUE TITLE
Cannot connect with my Database on same network.

### ISSUE THREAD

**Issue by starboyvarun** [psycopg/psycopg2#1491]
When I  am try connecting with my database using SSH. It's working fine.

![1](https://user-images.githubusercontent.com/26819449/187417561-1f02dd78-b17e-448b-84ec-78b4ec2352bb.JPG)

But when i try doing it with python using psycopg2.

![2](https://user-images.githubusercontent.com/26819449/187417669-93d5dcef-f5f3-43d7-ab0b-1afce78d45b2.JPG)
It throwing error.

![3](https://user-images.githubusercontent.com/26819449/187417682-3ac53b73-bbc8-47ff-9443-bbcd4313f55d.JPG)

Can you tell me where I am going wrong or its a bug?
Thanks.

**Comment by dvarrazzo** [comment]
In the error message your are not connecting to localhost
