### ISSUE TITLE
psycopg2-binary fails after changes in `postgres` formula in `brew`

### ISSUE THREAD

**Issue by jaklan** [psycopg/psycopg2#1492]
`brew` formula for `postgres` was recently changed in a significant way: https://github.com/Homebrew/homebrew-core/pull/107726  
Currently, it always includes the version in its name, e.g. `postgres@14`. That change impacted `psycopg2-binary` in a way it's not able to find `libpq.5.dylib` anymore:
```
  Reason: tried: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file), '/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```
because the new location is `/opt/homebrew/opt/postgresql@14/lib/postgresql@14` (or symlink: `/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/postgresql@14`), which is not on the path list.

What's interesting - when using pure `psycopg2`, the issue seems to be easy to resolve - it's just enough to reinstall the package. But reinstalling the `psycopg2-binary` doesn't work. 

I use `dbt` with `dbt-redshift` adapter based on `dbt-postgres`, which has a dependency on [`psycopg2-binary`, not on `psycopg2`](https://github.com/dbt-labs/dbt-core/blob/1df713fee986741289568f553befdd4e38a51122/plugins/postgres/setup.py#L32-L40). I have both `pipx` and `pre-commit` environments with `dbt` and to fix it - I had to manually install `psycopg2`, which seems to have a priority over `psycopg2-binary` when both are installed. And it was fine to fix the `pipx` setup, but it's not fine for the `pre-commit` one, because specifying `psycopg2` as an additional dependency would affect all the monorepo users.

I don't know what's exactly the difference in lib discoverability between `psycopg2` and `psycopg2-binary`, but I wish we can solve the issue in a way both packages would be able to successfully find the libs.

**Please complete the following information:**
- OS: macOS Monterey 12.5.1
- Psycopg version: 2.9.3
- Python version: 3.9
- PostgreSQL version: 14.5
- pip version: 22.2.2

**Comment by dvarrazzo** [comment]
> That change impacted psycopg2-binary in a way it's not able to find libpq.5.dylib anymore

This doesn't make a lot of sense. psycopg-binary packages its own libpq and shouldn't even need brew.

The fact that reinstalling psycopg2 after a change in the library is necessary and fixes things makes sense instead, it's how it should be.

> I had to manually install psycopg2, which seems to have a priority over psycopg2-binary when both are installed.

the two packages simply cannot be installed in the same environment. Which takes precedence is undefined.

I am not sure 100% that you are running your tests with psycopg2-binary. Can you show me that?

**Comment by dvarrazzo** [comment]
> OS: macOS Monterey 12.5.1

I assume this is M1 hardware. As such you are not using binary packages, you are installing from source.

**Comment by jaklan** [comment]
@dvarrazzo here's a detailed flow:
1. Create & activate a new venv
2. `pip install dbt-redshift`
3. `dbt compile`

At that moment it fails due to:
```
Reason: tried: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file), '/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```

So let's continue:
4. `pip uninstall psycopg2-binary`
5. `pip install --no-cache-dir psycopg2-binary`

     Collecting psycopg2-binary
     Downloading psycopg2-binary-2.9.3.tar.gz (380 kB)

6. `dbt compile`

Now it works!

But...
7. `pip uninstall psycopg2-binary`
8. `pip install psycopg2-binary` (so without `--no-cache-dir` this time)

     Collecting psycopg2-binary
     Using cached psycopg2_binary-2.9.3-cp39-cp39-macosx_12_0_arm64.whl

9. `dbt compile`

And... it fails again:
```
Reason: tried: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file), '/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```

So for any reason - it fails each time when using cached wheel, even if it's a fresh one...

**Comment by jaklan** [comment]
Finally got it - the issue was with `pip cache remove` command - I had to run `pip cache remove psycopg2_binary` instead of `pip cache remove psycopg2-binary`, only then the cache was correctly deleted. Now each time when I run `pip install psycopg2-binary` I get:
```
Collecting psycopg2-binary
  Using cached psycopg2-binary-2.9.3.tar.gz (380 kB)
```
so that's fine.

Btw, one question @dvarrazzo - the naming shouldn't be actually aligned?
- dash: `psycopg2-binary-2.9.3.tar.gz`
- underscore: `psycopg2_binary-2.9.3-cp39-cp39-macosx_12_0_arm64.whl`

**Comment by dvarrazzo** [comment]
Tne name is what is produced by the wheel package from the metadata of the package.
