### ISSUE TITLE
Occured an error when import Json data with copy_from method

### ISSUE THREAD

**Issue by JinXia77** [psycopg/psycopg2#1493]
- OS:ubuntu20.04
- Psycopg version:psycopg2-binary==2.9.3
- Python version:3.9.12
- PostgreSQL version:14.1
- pip version: 22.1.2

**Describe the bug**
I want to insert the json data into my postgre database by using psycopg2. But an error occured when I insert data by using copy_from function, the error shows below. And the code for inserting data is shown below. So I want to know how to solve this problem, how can I insert the json data in to postgre database by using copy_from function?

```python
import psycopg2
from psycopg2.extras import Json
from io import StringIO
import datetime
import fields

id = '12'
words = [{'wd': 'bee', 'wt': 3}, {'wd': 'boat', 'wt': 3}]
keyword_type = 'semantic'
json_words = Json(words)
# send_words = fields.JSONField.to_python(None, json_words)
insert_date = datetime.date(2022,9,6)
company = 'company'
f = ''
for i in range(5):
    f += "{}\t{}\t{}\t{}\t{}\n".format(id, json_words, company, keyword_type, insert_date)

conn = psycopg2.connect(database='postgres', user='postgres', password='***',
                        host='**',
                        port='**')
cur = conn.cursor()
cur.execute('SET search_path TO keywords, public')
cur.copy_from(StringIO(f), "test", columns=('id', 'keywords', 'company', 'mode', 'keyword_date'))
conn.commit()
cur.close()
conn.close()
```
![image](https://user-images.githubusercontent.com/110447054/188811819-910c5782-080b-4c98-a4c3-9a6279d54a54.png)

**Comment by dvarrazzo** [comment]
You should escape the json values in a way compatible with the COPY format. Using string composition won't do.

Please use [psycopg 3 copy](https://www.psycopg.org/psycopg3/docs/basic/copy.html), which does exactly what you want.
