### ISSUE TITLE
`copy_expert` doesn't capture output on STDOUT

### ISSUE THREAD

**Issue by tobwen** [psycopg/psycopg2#1494]
**Please complete the following information:**
- OS: Debian Linux
- Psycopg version: 2.9.3
- Python version: 3.10.6
- PostgreSQL version: 12, 14, 15
- pip version: 22.2.2

**Describe the bug**
Please let us know: Although the output of a program is send to STDOUT via `COPY (...) TO PROGAM`, the output isn't captured by `copy_expert`.

1: what you did: Use `TO PROGRAM` with `copy_expert`
2: what you expected to happen: Content of `/tmp/a` should be `a,b`
3: what happened instead: Content of `/tmp/a` is empty.

If possible, provide a script reproducing the issue.
``` python
import psycopg2
conn = psycopg2.connect("dbname='tobwen' user='tobwen' host='localhost'")
cur = conn.cursor()
cmd = '/usr/bin/sed "s|\\.|,|g"'
with open('/tmp/a', "w", newline='\r\n') as f:
    cur.copy_expert(f"COPY (SELECT 'a.b') TO PROGRAM '{cmd}'", f)
conn.close()

```

**Comment by dvarrazzo** [comment]
`copy_expert` just works with STDIN and STDOUT, not PROGRAM. PROGRAM is run by the server and no data is sent to the client.

You will find `/tmp/a/` on your server machine, not on your client.
