### ISSUE TITLE
Cannot install psycopg2 from poetry in Mac M1&M2 

### ISSUE THREAD

**Issue by Shayan-Shabanzadeh** [psycopg/psycopg2#1495]
it appears that there is a problem in installing psycopg2 from poetry in mac M2 but the weirdest thing about it is that pyscopg2 is available from pip and it works perfectly but for some reason is not available from Poetry. 

my system is MacBook Pro 2022 M2 processor and my pip version is pip (python 3.10).

**Comment by dvarrazzo** [comment]
If paycopg works with pip, open a bug to poetry.
