### ISSUE TITLE
The rowcount seems always equal -1 after execute('merge sql'), is it the right result?

### ISSUE THREAD

**Issue by qwertyue** [psycopg/psycopg2#1497]
The SQL I run is something like this:

    merge into schema.table T
    using (select id, city, name) S 
    on(T.id = S.id) 
    WHEN MATCHED THEN UPDATE SET T.city=S.city,T.name=S.name 
    WHEN NOT MATCHED THEN insert(T.city,T.id,T.name) VALUES( S.city,S.id,S.name)

My code is as follows:

    cur = conn.cursor()
    cur.execute(sql)
    conn.commit()
    print('rowcount= ', cur.rowcount)  //always -1

**Comment by dvarrazzo** [comment]
It's what the server passes us. If you don't think it's the right value you should open a bug to pgsql-bugs@postgresql.org.

**Comment by qwertyue** [comment]
> It's what the server passes us. If you don't think it's the right value you should open a bug to [pgsql-bugs@postgresql.org](mailto:pgsql-bugs@postgresql.org).

After the upgrade to PG15, the execution result of the Merge statement can be obtained correctly, but the psycopg still does not support this function.

link: https://www.postgresql.org/docs/15/sql-merge.html

**Comment by dvarrazzo** [comment]
I don't know what you are talking about.
```
In [1]: import psycopg2

In [2]: cnn = psycopg2.connect(port=54315)

In [3]: cnn.autocommit = True

In [4]: cur = cnn.cursor()

In [5]: cur.execute("merge into dst using src on src.id = dst.id when matched then update set data = src.data when not matched then 
   ...: insert (id, data) values (src.id, src.data)")

In [6]: cur.statusmessage
Out[6]: 'MERGE 3'

In [7]: cur.rowcount
Out[7]: 3
```

**Comment by qwertyue** [comment]
> I don't know what you are talking about.
> 
> ```
> In [1]: import psycopg2
> 
> In [2]: cnn = psycopg2.connect(port=54315)
> 
> In [3]: cnn.autocommit = True
> 
> In [4]: cur = cnn.cursor()
> 
> In [5]: cur.execute("merge into dst using src on src.id = dst.id when matched then update set data = src.data when not matched then 
>    ...: insert (id, data) values (src.id, src.data)")
> 
> In [6]: cur.statusmessage
> Out[6]: 'MERGE 3'
> 
> In [7]: cur.rowcount
> Out[7]: 3
> ```

Do you use the latest postgres version (15) ？

**Comment by qwertyue** [comment]
My system environment is as follows:

OS Version : win 10 21H2
Python version: 3.10.7
psycopg2 version:  2.9.4
Postgres SQL version: PostgreSQL 15.0, compiled by Visual C++ build 1914, 64-bit

my code as follow:
```
    conn = pg.connect(
        dbname='postgres',
        user='postgres',
        password='password',
        host='localhost',
        port=5432,
    )
    sql = '''
        merge into test.yue_test T 
        using (select 'sz' as city, 'myname' as name, 2 as id) S 
        on(T.id = S.id) 
        WHEN MATCHED THEN UPDATE SET city=S.city, name=S.name 
        WHEN NOT MATCHED THEN insert(city, id, name) VALUES( S.city,S.id,S.name)
        '''
    conn.autocommit = True
    cur = conn.cursor()
    cur.execute(sql)
    print('rowcount = ', cur.rowcount)

```

create sql script:
```
CREATE SCHEMA IF NOT EXISTS test
    AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS test.yue_test
(
    city character varying(20) COLLATE pg_catalog."default",
    id numeric,
    name character(16) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS test.yue_test
    OWNER to postgres;
```

the output:
rowcount =  -1

But new data has been inserted into my database.

**Comment by dvarrazzo** [comment]
Uhm... there is something there. I have repeated the test and got a rowcount = -1 too. That's strange.

I run further tests and it seems that psycopg2 binary 2.9.4, which ships with libpq 14.4, returns rowcount -1, whereas locally, where I have 14.5 (as well as 13.8, 15.0) return 3 (in my test).

So maybe something was changed between 14.4 and 14.5 in the libpq to allow messages from MERGE to be handled correctly. Checking...

**Comment by dvarrazzo** [comment]
My test with 14.5 must have been wrong: there is explicit support for MERGE only in libpq 15. Before that, the libpq doesn't parse the statusmessage correctly.

I should release binary package wrapping libpq 15 in the near future. In the meantime you can parse the statusmessage instead (which is actually what the libpq does internally, I thought there was an explicit message from the server sending the number of tuples affected).

```python
tmp = (cur.statusmessage or "").split()[-1]
rowcount = int(tmp) if tmp.isdigit() else -1
```

building psycopg from source, the problem is avoided by installing libpq 15, which is now packaged by default by most OS. The option is not easily available on Windows anyway.

**Comment by qwertyue** [comment]
Cool, thanks @dvarrazzo 

Now i will get the results by parsing statusmessage, and wait for the release of your new version.
