### ISSUE TITLE
the 'S' character is not set when generating (psycopg2-binary)

### ISSUE THREAD

**Issue by cement-hools** [psycopg/psycopg2#1498]
https://github.com/psycopg/psycopg2/blob/3e7bb8d1aa631320234f9e05ef940a1d1e9a627f/lib/sql.py#L448

```
    def as_string(self, context):
        if self._wrapped is not None:
            return f"%({self._wrapped})"
        else:
            return "%s"
```

`return f"%({self._wrapped})"`

must be

`return f"%({self._wrapped})s"`

**Comment by dvarrazzo** [comment]
I don't know what you are seeing, the `s` is there. That bug has been long fixed, since psycopg 2.9.1. It affected 2.9.0 only.
