### ISSUE TITLE
Support for IAM authentication for AWS RDS databases

### ISSUE THREAD

**Issue by gforien** [psycopg/psycopg2#1501]
Does psycopg support [IAM authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) for AWS RDS databases ?

This allows to connect to a postgreSQL database with a role ARN and a session token (regularly refreshed), instead of using credentials

This would be great 🙏 thank you !

**Comment by dvarrazzo** [comment]
Can you connect with psql?

**Comment by bluetech** [comment]
From experience I can attest that psycopg2 has no problem with using IAM authentication. It's just a long username/password as far as the driver is concerned. Just make sure to refresh the user/pass at least every 15 minutes.

**Comment by dvarrazzo** [comment]
I think this can be closed. Thank you, @bluetech.
