### ISSUE TITLE
Doubling the percent sign for parameter in sql statement

### ISSUE THREAD

**Issue by alexandr01987** [psycopg/psycopg2#1505]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Kubuntu  22.04.1 LTS
- Psycopg version: 2.9.3
- Python version:  3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
- PostgreSQL version: PostgreSQL 10.20 (Ubuntu 10.20-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
- pip version  22.2.2

**Describe the bug**
Problem in double percent sign in parameter parsing statement, but origin statement has correct one sign. 

Please let us know:

1: execute raw query with parameter as tuple for contains (in) statement

       inserted_id_tuple = ('313b3cd4-ca42-4def-9833-c63885533883', 'cf5ed73c-3973-4153-be1e-fb2fb9db7e9e')
        SELECT 
            id, 
            id as id_,
            "__name", 
            tplnr, 
            pltxt, 
            (select ttp.id from type_tech_place ttp where ttp.eqart = tp.eqart limit 1) as eqart, 
            invnr, 
            datab, 
            sysstat, 
            swerk, 
            (select plt.id from place_location_toro plt where plt.stort = stort limit 1) as stort, 
            bukrs, 
            iwerk, 
            (select gpt.id from group_plan_toro gpt where gpt.ingrp = tp.ingrp limit 1) as ingrp, 
            (select cct.id from catalog_codes_toro cct where cct.rbnr = tp.rbnr limit 1) as rbnr, 
            (select tp2.id from technical_place tp2 where tp2.tplnr = tp.tplma limit 1) tplma, 
            zzdispname
        FROM public.technical_place tp
        WHERE tp.id = ANY(%(id_tuple)s)
        result = session.execute(sql_query,
                                 {'id_tuple': inserted_id_tuple})

2: execution sql query for select result
3: raised programming error:

      sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "%"
      LINE 21:             WHERE tp.id = ANY(%(id_tuple)s)
                                                 ^
      [SQL: 
                  SELECT 
                      id, 
                      id as id_,
                      "__name", 
                      tplnr, 
                      pltxt, 
                      (select ttp.id from type_tech_place ttp where ttp.eqart = tp.eqart limit 1) as eqart, 
                      invnr, 
                      datab, 
                      sysstat, 
                      swerk, 
                      (select plt.id from place_location_toro plt where plt.stort = stort limit 1) as stort, 
                      bukrs, 
                      iwerk, 
                      (select gpt.id from group_plan_toro gpt where gpt.ingrp = tp.ingrp limit 1) as ingrp, 
                      (select cct.id from catalog_codes_toro cct where cct.rbnr = tp.rbnr limit 1) as rbnr, 
                      (select tp2.id from technical_place tp2 where tp2.tplnr = tp.tplma limit 1) tplma, 
                      zzdispname
                  FROM public.technical_place tp
                  WHERE tp.id = ANY(%%(id_tuple)s)
              ]

**Comment by dvarrazzo** [comment]
If you want to pass something to an ANY() operator, it should be a list, not a tuple.

If you are experiencing things like passing a `%s` to a function and receiving a `%%s` in psycopg, that's a transformation operated by whatever middleware you are using, not a psycopg bug. Try first passing a list to your query, then try to hear from sqlalchemy.
