### ISSUE TITLE
None arrays wrapped inside ARRAY[%s] fail

### ISSUE THREAD

**Issue by yetanotherion** [psycopg/psycopg2#1507]
**Please complete the following information:**
- OS: macOS 12.6
- Psycopg version: 2.9.3
- Python version: 3.8.6
- PostgreSQL version: 14.2
- pip version: 22.1.2

**Describe the bug**
```python
def test_psycopg2_nested_none_in_array(self):
    with connection.cursor() as cursor:
        cursor.execute("SELECT ARRAY[%s]::integer[][]", ([None, None],))
```

fails with
```
invalid input syntax for type integer: "{NULL,NULL}"
               LINE 1: SELECT ARRAY['{NULL,NULL}']::integer[][]
```
As suggested by [Mariusz Felisiak](https://code.djangoproject.com/ticket/34080#comment:1) it seems to be related to https://github.com/psycopg/psycopg2/issues/325.

The original bug in Django can be found at https://code.djangoproject.com/ticket/34080

N.B:
```python
def test_psycopg2_nested_none(self):
    with connection.cursor() as cursor:
        cursor.execute("SELECT %s::integer[][]", ([[None, None]],))
```
succeeds, most probably thanks to the fix at https://github.com/psycopg/psycopg2/issues/325.

**Comment by dvarrazzo** [comment]
Hello,

Breaking backwards compatibility is not an option. And I am aware of the limitations of the `ARRAY[]` construct (not all of them: `ARRAY[]` is an entertaining booby trap).

Does
```python
cursor.execute("SELECT ARRAY[%s::integer[]]", ([None, None],))
```
work?

**Comment by yetanotherion** [comment]
> the `ARRAY[]` construct (not all of them: `ARRAY[]` is an always entertaining booby trap).
:)
 
> Does
> 
> ```python
> cursor.execute("SELECT ARRAY[%s::integer[]]", ([None, None],))
> ```
> 
> work?
It does!
https://github.com/psycopg/psycopg2/pull/1510

Would you be ok to merge that PR so that this feature is kept in future releases?
(I'd try to use this feature to fix https://code.djangoproject.com/ticket/34080 in Django).

**Comment by dvarrazzo** [comment]
Sure, will merge #1510, but won't merge #1509, which is a regression. It undoes work needed to fix other more useful use cases, and it will not be accepted.

Psycopg 2 generates a SQL snippet (a literal, or a SQL construct), making its best to make it accepted by postgres, and, if the type is not the one desired by the user, they have the possibility to use the `::` cast to adjust it. In your request `ARRAY[%s]::int[][]` this is not what is happening, whereas `%s::int[]` creates an expression that postgres can work on.

The future direction, implemented in psycopg 3, is to use only literals (no `ARRAY[]`) with added type info (as oid or cast on the literal, according to the argument passing style).

**Comment by yetanotherion** [comment]
> Sure, will merge #1510, but won't merge #1509, which is a regression. It undoes work needed to fix other more useful use cases, and it will not be accepted.
> 
> Psycopg 2 generates a SQL snippet (a literal, or a SQL construct), making its best to make it accepted by postgres, and, if the type is not the one desired by the user, they have the possibility to use the `::` cast to adjust it. In your request `ARRAY[%s]::int[][]` this is not what is happening, whereas `%s::int[]` creates an expression that postgres can work on.
> 
> The future direction, implemented in psycopg 3, is to use only literals (no `ARRAY[]`) with added type info (as oid or cast on the literal, according to the argument passing style).

Crystal clear and makes a lot of sense, thanks again @dvarrazzo!
