### ISSUE TITLE
Status of psycopg2 2.9.5 release, with support for Python 3.11

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#1514]
Most packages [have been published already](https://pypi.org/project/psycopg2-binary/2.9.5/#files).

- Linux Packages for Python 3.6--3.11
- macOS arm64 Packages for Python 3.8--3.11
- macOS x86_64 Packages Python 3.6--3.10

Still missing:

- [x] ~windows packages Python 3.6--3.10: status; [building on appveyor](https://ci.appveyor.com/project/psycopg/psycopg2/builds/45174669)~ done
- [x] windows packages Python 3.11: waiting for [appveyor/ci#3844](https://github.com/appveyor/ci/issues/3844) usually it takes a few weeks (close #1499).
- [x] ~macOS x86_64 packages for Python 3.11: waiting for `python-3.11.0-darwin-x64.tar.gz` package in [this resources list](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)~ done

**Comment by scuml** [comment]
python-3.11.0-darwin-x64 is ready in the resource list. Thanks for your work on this.

**Comment by dvarrazzo** [comment]
@scuml thank you for the heads up! Builders' gonna build!

**Comment by dvarrazzo** [comment]
macOS x86_64 package for Python 3.11 now available on PyPI!

**Comment by scuml** [comment]
Thanks @dvarrazzo - works great.

**Comment by rubiodamian** [comment]
still not working on docker.
tested on python:3-alpine

**Comment by dvarrazzo** [comment]
@rubiodamian musllinux packages have been released: see [the list of files in release 2.9.5](https://pypi.org/project/psycopg2-binary/2.9.5/#files). `cp311-musllinux` packages are available there.

```
$ docker run -ti --rm  --name py311 python:3.11-alpine sh
/ # pip install psycopg2-binary
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.5-cp311-cp311-musllinux_1_1_x86_64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 7.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.5
```

**Comment by fmpfeifer** [comment]
https://github.com/appveyor/ci/issues/3844 already closed

**Comment by dvarrazzo** [comment]
@fmpfeifer already testing, thank you :)

**Comment by dvarrazzo** [comment]
Packages for Python© 3.11® for Workgroup™ released.
