### ISSUE TITLE
Django 4.1.3 doesn't work with psycopg2 2.9.5 with Python 3.11.0

### ISSUE THREAD

**Issue by uri-rodberg** [psycopg/psycopg2#1519]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:Windows
- Psycopg version:2.9.5
- Python version:3.11.0
- PostgreSQL version:13
- pip version:22.3

**Describe the bug**
If I run tests or `makemigrations` with Django 4.1.3 and psycopg2 2.9.5 with Python 3.11.0 on Windows, I get this error message:
```
  File ".venv_3.11\Lib\site-packages\django\db\backends\postgresql\base.py", line 24, in <module>
    import psycopg2 as Database
  File ".venv_3.11\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

During handling of the above exception, another exception occurred:

django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified module could not be found.
```

1: what you did
I upgraded Python to 3.11.0, Django to 4.1.3 and psycopg2 to 2.9.5 locally on Speedy Net

2: what you expected to happen
`makemigrations` and tests should work

3: what happened instead
They don't work

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
#1514

**Comment by oniflix** [comment]
J'ai le même problème que vous.

Mais cette fois avec pypy et j'obtient la même chose.

est ce qu'une personne à une solutions pour palier ce problème.

**Comment by mattip** [comment]
@oniflix please open a new issue and reference me (@mattip) on it. What version of PyPy are you using, where did you get it,  and what error are you getting?
