### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by PierreNAPOLETANO** [psycopg/psycopg2#1520]
- OS: Windows 11 Family
- Psycopg version: 2.9.5
- Python version: 3.11
- PostgreSQL version: 6.14
- pip version: 22.3.1

![Psycopg2 issue](https://user-images.githubusercontent.com/56818795/200398793-999ff661-4b22-4687-8630-50a01ba75f09.png)

**Comment by dvarrazzo** [comment]
#1514
