### ISSUE TITLE
Psycopg2 (2.8.6) error when on python 3.11

### ISSUE THREAD

**Issue by radzhome** [psycopg/psycopg2#1522]
psycopg2-binary==2.8.6 no longer works for me on python 3.11 and since I'm on django 2.2.28 I got the infamous "database connection isn't set to UTC" assertion error after using `psycopg2-binary==2.9.5`

Not sure why django didn't release a patch for this in 2.22.. going to 3.2 is not an option either. So unless 2.8.6 works on python3.11 I am using 2.9.5 with this workaround (patch at top of my settings.py file)

```
# Monkey patching django db utils to fix TZ for psycopg2 2.9+ for py3.11  TODO: Drop after django 3.2
from django.utils.timezone import utc
from django.db.backends.postgresql.utils import utc_tzinfo_factory
from django.db.backends.postgresql import utils


def _utc_tzinfo_factory(offset):
    if str(offset) not in ('0', '0:00:00'):  # timedelta(hours=0)
        raise AssertionError("database connection isn't set to UTC (monkey patch)")
    return utc


utils.utc_tzinfo_factory = _utc_tzinfo_factory
# End of patch
```

This might help others that can't upgrade to django 3.2 just yet.

**Comment by dvarrazzo** [comment]
I sympathize.

I think that this bit of documentation doesn't belong to psycopg bugs tracker: it is not searchable here. This is a problem between a Django old version and a psycopg new version. If any it should be documented somewhere in Django.

@apollo13, @pauloxnet: would you have a better place to put this but of info?

As for the problem itself, it can be solved in a couple of ways:

- Releasing a Python package with a backport psycopg2 backend for the old Django

- Releasing psycopg 2.8.7 with support for newer Python.

None of them I would do for free, but I'm ok to do them as a paid project.

**Comment by apollo13** [comment]
Hi Daniele, no Django doesn't have any place to put this. The reporter is using an EOL version of Django, it is neither on us nor on you to document or patch anything here. The only viable path is an upgrade of Django.

**Comment by pauloxnet** [comment]
I agree with @apollo13 
Django 2.2 is EOL and it support Python up to 3.9
Only Django 4.1.3 support Python 3.11 at the moment.
