### ISSUE TITLE
dlopen failed: cannot locate symbol "round" referenced by "_psycopg.cpython-38.so"

### ISSUE THREAD

**Issue by art435** [psycopg/psycopg2#1523]
**Please complete the following information:**
- OS: Android 5 (Termux)
- Psycopg version: 2.9.5
- Python version: 3.8
- PostgreSQL version: 11.5
- pip version: 22.3.1

**Describe the bug**
I tried to run a python script, and it gives me this error
`ImportError: dlopen failed: cannot locate symbol "round" referenced by "_psycopg.cpython-38.so"
`

1: what you did
I tried to run a python script that has as dependencies postgresql, sqlalchemy and psycopg2-binary. I created a venv and installed all the dependencies from requirements. All installed fine, no errors, I started the postgresql server and created the database, again no errors. And finally, when I tried to run the script, it gives me the error above. The full log

https://pst.klgrth.io/paste/b8xsb

2: what you expected to happen
The script should run fine without any errors

3: what happened instead
The error above

**Comment by dvarrazzo** [comment]
I don't think android is a platform supported by the binary distribution.

Please follow the docs to build psycopg from source.

**Comment by art435** [comment]
I build it from source, but it still gives the same error. But I have successfully run the script on another phone with Android 11 and Python 3.11.  Maybe there is a compatibility issue with one of this two. If anyone has any idea how to solve this error, let me know.
