### ISSUE TITLE
The connection cannot be closed normally due to network disconnection

### ISSUE THREAD

**Issue by ghhhgfgh** [psycopg/psycopg2#1524]
Hello, here is a problem I met.
First, I use the following command to open a connection with Postgres. (I am in ip: 192.168.50.6 and the db in 192.168.50.88)

**d = psycopg2.connect(database = "test", user = "db_user", password = "123456", host = "192.168.50.88", port = "5432")**

Then, the network is disconnected between 50.80 and 50.6 caused of some reason. When the script is running some commands such as:

**d_cursor = d.cursor()
d_cursor.execute(sql_str)
d.commit()**

The error is appeared as follows:
**psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.**

and I print the **d** to  see the connection status, it shows as follows:
**<connection object at 0x00000218848A0160; dsn: 'user=db_user password=xxx dbname=testdb host=192.168.50.88 port=5432', closed: 2>**

The closed flag is 2(Actually I cannot find the meaning of 2). Then I want to reconnect to Postgres, so I first use **d.close()** to disconnect then I can see the connection status of d is :
**<connection object at 0x00000218848A0160; dsn: 'user=db_user password=xxx dbname=testdb host=192.168.50.88 port=5432', closed: 1>**

So I think it is disconnected from the Postgres. But unfortunately, things don't turn out the way I want. I directly use SQL command to check the client list using following commands:

**'SELECT usesysid, usename FROM pg_stat_activity;'**

And I can still see the connection. it means I didn't close it correctly. But there are not other ways to disconnect and close the connection. So I wonder to know how I can disconnect in this situation.

**Comment by dvarrazzo** [comment]
> Actually I cannot find the meaning of 2

probably it means broken, but it's an internal value, not public interface.

> Then I want to reconnect to Postgres, so I first use d.close() to disconnect

That won't do anything to the server, will only change the flag in the client structure. The connection is lost, it can't be recovered.

> And I can still see the connection. it means I didn't close it correctly. But there are not other ways to disconnect and close the connection. So I wonder to know how I can disconnect in this situation.

If the network went down, and the customer finds itself disconnected, I assume the server also gets a disconnection. So I'm not 100% sure you are seeing what you think you are seeing in that table - that the entry you see is the disconnected one. You might verify it by setting an appname maybe.

If a session is stuck there in the server, I think it will be eventually cleaned out by TCP timeouts. You might force its hand using `pg_terminate_session()`. But you cannot use a broken connection to operate on the server anymore.

**Comment by ghhhgfgh** [comment]
> If the network went down, and the customer finds itself disconnected, I assume the server also gets a disconnection. So I'm not 100% sure you are seeing what you think you are seeing in that table - that the entry you see is the disconnected one. You might verify it by setting an appname maybe.

I use the following way to verify.
First, I use wifi as IP 192.168.50.6 to connect to Postgres. Then I manually disconnect wifi from the network( and wait until the "closed" flag becomes to 2). Then I go to check the db in 192.168.50.88(it doesn't disconnect), I can check and can that see the client still connects.

> That won't do anything to the server, will only change the flag in the client structure. The connection is lost, it can't be recovered.

So, it means that I can just create another instance to reconnect to the db. The  old broken one will become "orphan" which I cannot use and cannot close it

**Comment by dvarrazzo** [comment]
> So, it means that I can just create another instance to reconnect to the db. The old broken one will become "orphan" which I cannot use and cannot close it

You could hear from the pgsql-general mailing list, maybe, what are the timeous before a connection closes, and maybe you can tweak the TCP timeouts involved in it, in the server. If you want to close those sessions proactively, if you have a way to find them, you can use a separate connection and terminate the session using the function suggested.
