### ISSUE TITLE
Allow `float` and `double precision` types in `round(...)` function

### ISSUE THREAD

**Issue by ali-sajjad-rizavi** [psycopg/psycopg2#1525]
Let's say we want to round a number to 2 decimal places, we have to do this;
```
select round(sales::numeric, 2)
```

But ideally, we'd have to do this;
```
select round(sales, 2)
```

**Comment by ali-sajjad-rizavi** [comment]
@dvarrazzo If that's feasible, I'll be excited to work on it!

**Comment by dvarrazzo** [comment]
@ali-sajjad-rizavi It is feasible, but it's something that must be tweaked in the server, not in psycopg.

You can do it already, in your server, by creating a function in your database:

```
postgres=# create function round(x double precision, scale int) returns numeric language sql immutable strict as 'select round(x::numeric, scale)';
CREATE FUNCTION

postgres=# select round(3.1415926::float4, 2);
 round 
-------
  3.14
(1 row)

postgres=# select round(3.1415926::float8, 2);
 round 
-------
  3.14
(1 row)
```

You should hear from the PostgreSQL people if they would be interested in providing this function signature out of the box.
