### ISSUE TITLE
How not to escape a separator with copy_to method

### ISSUE THREAD

**Issue by swood** [psycopg/psycopg2#1527]
Hello, I am trying to dump a table with the next code:
`cursor.copy_to(output, partition if len(partition) > 0 else table, sep=",", null="")`

It works fine unless in a situation when one of the columns contains the same symbol as a separator.
So instead of this:
`1,20,"hello, world",125`
I am getting this:
`1,20,hello\, world,125`

Does anyone came across same problem and what might be a solution?

**Comment by dvarrazzo** [comment]
- You can use the tab as separator, assuming that you don't have tabs in your data.
- You can use the csv format, or any other feature that the [postgresql COPY command](https://www.postgresql.org/docs/current/sql-copy.html) offers.
- You can use psycopg 3 and use [copy based on python objects](https://www.psycopg.org/psycopg3/docs/basic/copy.html#writing-data-row-by-row).
