### ISSUE TITLE
Incorrect SQL operation with cursor.callproc()

### ISSUE THREAD

**Issue by jimmymcheung** [psycopg/psycopg2#1532]
**Version Info**
- OS: macOS 12.6.2 / Windows 11
- Psycopg version: 2.9.5 (dt dec pq3 ext lo64)
- Python version: 3.10.7
- PostgreSQL version: 14.5 (x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit)
- pip version: 22.3.1

**Bug**
In python, when I ran the following code:
 ```python
import psycopg2
conn = psycopg2.connect("dsn string")
cur = conn.cursor()
cur.callproc('proc_name', ['1000'])
# also tried:
cur.callproc('proc_name', ('1000',))
```
I get the following error: 
```
psycopg2.errors.WrongObjectType: proc_name(unknown) is a procedure
LINE 1: SELECT * FROM proc_name('1000')
```
I notice that instead of `CALL` the `callproc()` use `SELECT` to handle the request. 

The procedure `proc_name` is defined as:
```sql
begin

-- PREPARE RSID_LINK_INSERT (VARCHAR(100)) AS
-- INSERT INTO id_search(search_rsid, date) VALUES($1, current_date) 
-- ON CONFLICT (search_rsid) DO UPDATE
-- SET date = current_date;
	
-- EXECUTE RSID_LINK_INSERT(RSID);

INSERT INTO id_search(search_rsid, date) 
VALUES(RSID, current_date);
-- ON CONFLICT (search_rsid) DO UPDATE
-- SET date = current_date;
Commit;

end;
```
The table `id_search` has two columns, where the first one is string with max 11 chars, the second column is date.

The documentation of `callproc` states `callproc(procname, parameters=None) -- Execute stored procedure.`, while the online documentation says function instead of procedure should be executed with `callproc`. I think either the documentation should be updated, or the behaviour of `callproc` itself should be corrected.

**Comment by dvarrazzo** [comment]
Callproc doesn't use CALL. Please use execute().
