### ISSUE TITLE
Getting error "year 23848 is out of range" from call to fetchall()

### ISSUE THREAD

**Issue by anibal2j** [psycopg/psycopg2#1533]
**Please complete the following information:**
- OS: Mac 13.1 (22C65) (on Apple Silicon)
- Psycopg version: 2.9.3
- Python version: 3.9
- PostgreSQL version: 11.12
- pip version: 22.3.1

**Describe the bug**
I am executing this query and as soon as I call fetchall() it throws:

ValueError "year 23848 is out of range"

I can't find the data that's causing the problem. If I execute the same query in psql it works and it returns all rows, but fetchall() is throwing and not returning anything at all. I tried putting a LIMIT <X> to see if I can identify the root cause data that's causing the issue, but I can't. I tried LIMIT 4500 and it works, but somewhere between LIMIT 4500 and LIMIT 5000 it fails. It'd be tedious to try to find the exact row that's throwing. 

Is there any way that I can find the row that's causing an issue for psycopg2?

SQL Query is:

`    SELECT rt.filler_ordnum, rt.test_desc, rt.modality, ot.priority, rt.entering_organization, rt.req_datetime, 
           rt.observer_fname, rt.observer_lname, rt.dictation_datetime, ot.cpt_code,
           rt.obs_value, rt.obs_end_datetime, rt.date_of_birth
    FROM report_tbl rt
    LEFT JOIN order_tbl ot 
    ON rt.filler_ordnum = ot.filler_ordnum
    WHERE rt.dictation_datetime BETWEEN '{from_date}' AND '{to_date}'
    AND rt.observer_fname = '{rad_first_name}'
    AND rt.observer_lname = '{rad_last_name}'
    GROUP BY rt.filler_ordnum, rt.test_desc, rt.modality, ot.priority, rt.entering_organization,
             rt.req_datetime, rt.observer_lname, rt.observer_fname, rt.dictation_datetime, ot.cpt_code,
             rt.obs_value, rt.obs_end_datetime, rt.date_of_birth
    ORDER BY rt.req_datetime DESC
`

The from_date is 2020-01-01 while the to_date is 2022-12-22 and the rad_first_name is Robert and rad_last_name is Walker. Nothing too fancy. Help please. I'm pretty sure there's a record in there that must have an invalid date or something like that, but I need help identifying it.

**Comment by dvarrazzo** [comment]
I can see you are not using placeholders for queries. You query will break as soon as `rad_first_name` contains an apostrophe. However, that's a separate matter you can [read docs about](https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries).

You can convert your dates to text, for instance `rt.date_of_birth::text`, and then look at the strings in Python to find the bad results. A bit more advanced is to [customize the date typecaster](https://www.psycopg.org/docs/advanced.html#type-casting-of-sql-types-into-python-objects) and write an object to help you either discover the bad value or filter it out.
