### ISSUE TITLE
Connection fails with psycopg2-binary v. 2.9.5 and ssl required

### ISSUE THREAD

**Issue by 21adrian1996** [psycopg/psycopg2#1535]
When using django and psycopg2-binary 2.9.5 to connect to a postgres database with ssl=required the following error is thrown:

`connection to server at [...] failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied`

With 2.9.4 this seems to just run fine.

Tested with python 3.8.

**Comment by dvarrazzo** [comment]
I'll look into it. Probably a change caused by a different build procedure.

What platform is this? More precisely, when you run `pip install psycopg2-binary`, what is the name of the `.whl` package that gets installed?

**Comment by 21adrian1996** [comment]
Using psycopg2_binary-2.9.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by dvarrazzo** [comment]
Thank you, will take a look and address for 2.9.6. In the meantime please use 2.9.4 or a source installation.

**Comment by Habbie** [comment]
I just got https://gitlab.alpinelinux.org/alpine/aports/-/issues/14565 - same problem, but no psycopg in sight. However, the user suspects that a libpq upgrade caused this.

I see 2.9.5 bumped libpq from 14.4 to 15, so I suspect that caused your problem to appear.

The linked ticket suggests setting PGSSLCERT (or, of course, the sslcert connection parameter) to something harmless as a workaround.

**Comment by Habbie** [comment]
> The linked ticket suggests setting PGSSLCERT (or, of course, the sslcert connection parameter) to something harmless as a workaround.

or, of course, make sure $HOME does not point to /root if you are not root

**Comment by Habbie** [comment]
https://why-upgrade.depesz.com/show?from=14.6&to=15.1&keywords=libpq

**Comment by dvarrazzo** [comment]
I don't think this issue is on psycopg side, because the value for `USER_CERT_FILE` is not customized by the stardard distributed libpq.
