### ISSUE TITLE
No support for UNICODE codex

### ISSUE THREAD

**Issue by carpenterd777** [psycopg/psycopg2#1539]
**System info**
- OS: Ubuntu 22.04.1 LTS
- Psycopg version: 3.0.14
- Python version: 3.10
- PostgreSQL version: 15.1
- pip version 22.0.2

**Describe the bug**
I attempted connected to a remote AWS database using AWS SSM. I expected to successfully connect, but instead received the following error:

```
psycopg.NotSupportedError: codec not available in Python 'UNICODE'
```

After I added the key/value pair `"UNICODE": "utf-8"` to `_py_codecs` in `_encodings.py` everything worked as expected, so I suspect this may be a potential bug fix. Please let me know if the `UNICODE` codex is actually distinct from UTF-8.

**Comment by dvarrazzo** [comment]
We don't have plan to support AWS for free. 

The error reported is for psycopg 3: already reported as https://github.com/psycopg/psycopg/issues/122

**Comment by carpenterd777** [comment]
understandable, thanks for the swift reply!
