### ISSUE TITLE
InterfaceError: cursor already closed

### ISSUE THREAD

**Issue by emilyhoover** [psycopg/psycopg2#1540]
- OS: 
- Psycopg version: 2.9.5 & 2.9.3
- Python version: 3.11
- PostgreSQL version: 12.11

**Describe the bug**
Since upgrading from Python 3.10->3.11 and Psycopg2 from 2.8.6->2.9.3/5 we've been getting random InterfaceError: cursor already closed errors on random parts of our codebase. Rarely the same line twice. Just kind of happens once every 5-10k runs. So it feels pretty rare, but does keep happening a few times every day. This is part of a Django 4.0.4 website.

**Comment by dvarrazzo** [comment]
I don't think it relates to the client. What do server logs say when there are disconnections?

**Comment by vladtsap** [comment]
The same here

**Comment by dvarrazzo** [comment]
Well, same answer for you. The server logs are useful.

**Comment by dvarrazzo** [comment]
Closing as no meaningful interaction
