### ISSUE TITLE
COPY FROM schema support

### ISSUE THREAD

**Issue by davies-a** [psycopg/psycopg2#1553]
- OS: ubuntu
- Psycopg version: as of 2.9.1, presently 2.9.3 installed
- Python version: 3.10.6
- PostgreSQL version:  14
- pip version: 23

Hello!
Many thanks for the project, it's a real backbone of psql usage in python and your support is much appreciated!

This is objectively a duplicate of #1294 - but I wanted to open an issue before presenting a PR that was inappropriate. Please feel happy to close the issue and direct me to a more appropriate place.

TL;DR of that issue, for context: as of v2.9.1 of psycopg2, `copy_from` does not support schema names - instead, standard advice is to use `copy_expert`.

However, `copy_expert` is more difficult to use, not supporting column names etc, and python users end up looking into the C source in order to come up with valid boilerplate for an insert query. Also from a security perspective the good motivation (to escape and thereby prevent SQL injection) ends up driving users to hand-rolled queries if they have schemas - which possibly defeats the motivation of 'safe defaults'.

I'd like to suggest adding an optional string kwarg `schema` to the `copy_from` method, which would default to `None`. If this is set, this would be escaped and passed to the command [here](https://github.com/psycopg/psycopg2/blob/63947e25526f6cfe2f134c51b88c167d028c5c65/psycopg/cursor_type.c#L1407), so that we end up with `COPY schema.table(col1, col2) FROM stdin WITH DELIMITER AS...`. I considered setting the default to 'public' and always including, but this would not respect a search_path set on the cursor and would be a breaking change.

If this is a valid route you'd be open to, I'd be keen to open a PR for review. 

Thanks!

**Comment by dvarrazzo** [comment]
> However, copy_expert is more difficult to use, not supporting column names etc, and python users end up looking into the C source in order to come up with valid boilerplate for an insert query.

This is not true. `copy_expert` supports any feature supported by the server, and as such it supports column names. You don't need to read the C source: you only need to read the [PostgreSQL documentation about COPY](https://www.postgresql.org/docs/current/sql-copy.html) to come up with a valid COPY statement, the same way you need to know the SELECT or INSERT syntax in order to use `execute()`.

> Also from a security perspective the good motivation (to escape and thereby prevent SQL injection) ends up driving users to hand-rolled queries if they have schemas - which possibly defeats the motivation of 'safe defaults'.

If someone needs to hand-roll a query by generating a dynamic COPY statement, they can use the [`sql` module](https://www.psycopg.org/docs/sql.html) facilities, which take care of escaping both values and identifiers.

> I'd like to suggest adding an optional string kwarg schema to the copy_from method, which would default to None. If this is set, this would be escaped and passed to the command [here](https://github.com/psycopg/psycopg2/blob/63947e25526f6cfe2f134c51b88c167d028c5c65/psycopg/cursor_type.c#L1407), so that we end up with COPY schema.table(col1, col2) FROM stdin WITH DELIMITER AS.... I considered setting the default to 'public' and always including, but this would not respect a search_path set on the cursor and would be a breaking change.

From a design point of view, `default` would be the wrong default. The right deafult would be `None`, which would generate no schema in the SQL, and would communicate the database to trust the `search_path`.

---

It is actually trivial to re-implement copy_from by using `cursor.copy_expert` + `psycopg2.sql`. You can also add other features you might want to wrap: if you have a play with the top links in the [copy docs page](https://www.postgresql.org/docs/current/sql-copy.html), you will notice that the features supported by these methods are only limited to what COPY offered back in PostgreSQL 7.4!

`cursor.copy_from()` and `copy_to()` are relics of the very first implementation of psycopg2 and have really no reason to exist anymore. I appreciate your offer to open a MR but I don't wish to add new features to these methods.

**Comment by davies-a** [comment]
Hey @dvarrazzo, thanks for the quick reply and for taking the time on this one!

Appreciate a lot of what you're saying about the legacy of `copy_from`/`copy_to` - and possibly this is why the issue arose in the first place. As I imagine is somewhat common, we normally use `psycopg2` through `sqlalchemy`, and only hit the need to jump into a deep dive because of the slow performance and memory overheads of `.execute()` and the like for large volumes. We wanted to jump into the adapter to get some improvements from `COPY FROM`, especially where libraries from other languages like `pgx` in go do this routinely.

Re: `copy_expert`, maybe I'm mistaken but it doesn't appear to support many of the kwargs available in `copy_from` - e.g. `table`, `sep`, `null` or `columns`, or to provide sql-injection protection out of the box. It receives only `sql`, `file` and `size`. In that way, it really does appear to be 'expert', and the other legacy functions appear 'easier and safer' interfaces.

Would an alternative, more helpful suggestion from your point of view, be to refactor `copy_from`/`copy_to` to call into `copy_expert` appropriately? This would allow you to remove the maintenance headache, but give non-'expert' users a less `.execute()` entrypoint for more simple scenarios? Then were there to be a desire, adding the other post-7.4 features would be a less burdensome task.

Again very happy to put in the work and PR as appropriate.

Thanks!

**Comment by dvarrazzo** [comment]
> Re: copy_expert, maybe I'm mistaken but it doesn't appear to support many of the kwargs available in copy_from - e.g. table, sep, null or columns, or to provide sql-injection protection out of the box.

`copy_expert()` takes a free-form string. This string can include any of the feature supported by the server and new features are regularly added to each new Postgres version. As such, you can see how the idea of wrapping every Postgres feature with a Python parameter is short-sighted: it would take new features every year, when a new server version is released. It would be similar to requesting the cursor to expose methods such as `select()`, `insert()`... and to add new parameters at every new feature added by the server. If there is a place for this piece of software, this is the task of an ORM, or something built on top of psycopg; in psycopg it would be misplaced (policy vs. mechanism).

If you have a fixed table name of fixed sequence of columns to copy, you can use copy_expert with a normal string:

```python
# ALL CODE UNTESTED
cur.copy_expert("COPY myschema.mytable (col1, col2, col3) FROM STDIN WITH DELIMITER '|'", file)
```

If your schema, table, columns, delimiter are to be decided dynamically, you can use `psycopg.sql`:

```python
from psycopg import sql

stmt = sql.SQL(
    "COPY {schema}.{table} ({columns}) FROM STDIN WITH DELIMITER {sep}"
).format(
    schema=sql.Identifier("myschema"),
    table=sql.Identifier("mytable"),
    columns=sql.SQL(",").join(sql.Identifier(c) for c in ["col1", "col2", "col3"]),
    sep=sql.Literal("|")
)
cur.copy_expert(stmt, file)
```

So it's pretty easy to add a function to your code to generate such statement:

```python
def my_copy_from(cur, table, file, schema=None, columns=None, sep=None, ...):
    stmt = sql.SQL("...").format(...)
    cur.copy_expert(stmt, file)
```

whose body is pretty much as above, using parameter names, and some ifs and `sql.SQL()` here and there to take into account default values. For instance, if you don't specify columns:

```python
    if columns:
        sql_cols = sql.SQL("({})").format(sql.SQL(",").join(sql.Identifier(c) for c in columns))
    else:
        sql_cols = ""

    stmt = sql.SQL("COPY {schema}.{table} {sql_cols} FROM STDIN").format(sql_cols=sql_cols, ...)
    cur.copy_expert(stmt, file)
```

So, again, thank you very much for your offer, it's really appreciated, but copy_from/copy_to are fundamentally obsolete.

If your perspective is different, and you think that a Python function wrapping every argument of COPY would be helpful for a large group of people, I invite you to put together an helper package with a re-implementation of copy_from/to using the composition methods illustrated above, which would be the policy layer on top of the mechanism layer implemented by psycopg2, and it would be easy to make it compatible with psycopg 3 too.

Note: `copy_expert()` as a name is also misleading: it should be `copy_basic()`, really. In psycopg 3, the homologous method is called just [`copy()`](https://www.psycopg.org/psycopg3/docs/basic/copy.html).

**Comment by davies-a** [comment]
I see, appreciate the distinction being made re: policy vs mechanism, and why you're keen to exclude the copy_from/to methods getting bloated - for now I'll implement downstream, but if anyone stumbles on this thread I'd be happy to work on this as a more generic library if it gains traction. Thanks for your time!
