### ISSUE TITLE
how to compile psycopg2 as a static library?

### ISSUE THREAD

**Issue by blatwo** [psycopg/psycopg2#1557]
I want to compile psycopg2 as a static library.
`python setup.py build build_ext --static-libpq install`
but when use it, error came up:

[root@Node02 ~]# python test.py 
Traceback (most recent call last):
  File "/root/test.py", line 3, in <module>
    import psycopg2
  File "/usr/local/lib/python3.11/site-packages/psycopg2-2.9.5-py3.11-linux-x86_64.egg/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/local/lib/python3.11/site-packages/psycopg2-2.9.5-py3.11-linux-x86_64.egg/psycopg2/_psycopg.cpython-311-x86_64-linux-gnu.so: undefined symbol: GENERAL_NAME_free
[root@Node02 ~]# 

**Please complete the following information:**
- OS: Centos7.x
- Psycopg version: 2.9.5
- Python version: 3.11.2
- PostgreSQL version: pg12.7
- pip version

**Comment by dvarrazzo** [comment]
Static build has not been tested in a long time and is not currently supported.

Some quick googling suggests that there is a problem with two different versions of openssl in use (the libpq one, the Python one).
