### ISSUE TITLE
macOS packages currently broken

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#1558]
See build https://github.com/psycopg/psycopg2/actions/runs/4525821909

Probably related to https://github.com/matthew-brett/delocate/issues/175

**Comment by AmirBitaraf** [comment]
As an update, pinning `delocate` to [0.10.3](https://github.com/AmirBitaraf/psycopg2/actions/runs/4533898431/jobs/7987340573) and [0.10.2](https://github.com/AmirBitaraf/psycopg2/actions/runs/4533940481/jobs/7987439896) didn't work out of the box.
