### ISSUE TITLE
Problems with psycopg2-binary installation on OpenSuse 14.4

### ISSUE THREAD

**Issue by fransuar** [psycopg/psycopg2#1559]
**Before opening this ticket, please confirm that:**
- [x ] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [ x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [ x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.
That it is not installed

**Please complete the following information:**
- OS: OpenSuse Leap 15.4
- Psycopg version: 2.9.6
- Python version:  3.6.15
- PostgreSQL version: 14
- pip version: pip-21.3.1

Hi,
   I had the following error doing pip install --user psycopg2-binary
 ERROR: Command errored out with exit status 1:
    command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7gpr0g3h/psycopg2-binary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7gpr0g3h/psycopg2-bi
nary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-b
ase /tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info
        cwd: /tmp/pip-install-7gpr0g3h/psycopg2-binary/
   Complete output (23 lines):
   running egg_info
   creating /tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info
   writing /tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
   writing dependency_links to /tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
   writing top-level names to /tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/top_level.txt
   writing manifest file '/tmp/pip-install-7gpr0g3h/psycopg2-binary/pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    
   Error: pg_config executable not found.
    
   pg_config is required to build psycopg2 from source.  Please add the directory
   containing pg_config to the $PATH or specify the full executable path with the
   option:
    
       python setup.py build_ext --pg-config /path/to/pg_config build ...
    
   or with the pg_config option in 'setup.cfg'.
    
   If you prefer to avoid building psycopg2 from source, please install the PyPI
   'psycopg2-binary' package instead.
    
   For further information please check the 'doc/src/install.rst' file (also at
   <https://www.psycopg.org/docs/install.html>).
    
   ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I could solve it using 
$ pip install --user "psycopg2-binary"
That command install psycopg2-binary == 2.9.5 (previous subversion)

Regards
    Francisco

**Comment by dvarrazzo** [comment]
The list of released binary packages [is here](https://pypi.org/project/psycopg2-binary/#files).

You have to figure out yourself which one should be installed, according to your platform, and why it's not picked by pip.

Alternatively, follow the installation instruction linked above to install from source.
