### ISSUE TITLE
Unable to build on AIX 7.2 - empty byte string

### ISSUE THREAD

**Issue by nkgilley** [psycopg/psycopg2#1561]
**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.
 

**Please complete the following information:**
- OS: AIX 7.2
- Psycopg version: 2.9.6
- Python version: 3.7.15-2
- PostgreSQL version: 13.10
- pip version: 23.1

I'm having trouble building psycopg2 on AIX 7.2.  I have PostgreSQL 13.10 installed from source and have added /usr/local/pgsql/bin to my path.

pg_config output:
```
pg_config
BINDIR = /usr/local/pgsql/bin
DOCDIR = /usr/local/pgsql/share/doc
HTMLDIR = /usr/local/pgsql/share/doc
INCLUDEDIR = /usr/local/pgsql/include
PKGINCLUDEDIR = /usr/local/pgsql/include
INCLUDEDIR-SERVER = /usr/local/pgsql/include/server
LIBDIR = /usr/local/pgsql/lib
PKGLIBDIR = /usr/local/pgsql/lib
LOCALEDIR = /usr/local/pgsql/share/locale
MANDIR = /usr/local/pgsql/share/man
SHAREDIR = /usr/local/pgsql/share
SYSCONFDIR = /usr/local/pgsql/etc
PGXS = /usr/local/pgsql/lib/pgxs/src/makefiles/[pgxs.mk](http://pgxs.mk/)
CONFIGURE =  '--without-readline' '--without-zlib'
CC = gcc
CPPFLAGS =
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2
CFLAGS_SL =
LDFLAGS = -Wl,-blibpath:'/usr/local/pgsql/lib:/usr/lib:/lib'
LDFLAGS_EX =
LDFLAGS_SL =  -Wl,-bnoentry -Wl,-H512 -Wl,-bM:SRE
LIBS = -lpgcommon -lpgport -lm
VERSION = PostgreSQL 13.10
```

During the build I get an empty byte string error b'':
```
python3 -v setup.py build
...
running build_ext
# /opt/freeware/lib64/python3.7/__pycache__/_sysconfigdata_m_aix7_.cpython-37.pyc matches /opt/freeware/lib64/python3.7/_sysconfigdata_m_aix7_.py
# code object from '/opt/freeware/lib64/python3.7/__pycache__/_sysconfigdata_m_aix7_.cpython-37.pyc'
import '_sysconfigdata_m_aix7_' # <_frozen_importlib_external.SourceFileLoader object at 0xa000000008b7f08>
Error: b''
```

FWIW, I can install psycopg2 if I use the postgres 11 rpms from IBM's AIX Toolbox.  I'd rather not go that route though.

**Comment by nkgilley** [comment]
Figured it out...I was running an older version of python 3.7.6 built for AIX6.  After updating to python 3.7.15-2 for AIX7, I'm good to go.

**Comment by dvarrazzo** [comment]
AIX is not tested and therefore not officially supported.
