### ISSUE TITLE
SyntaxError when executing psycopg2 UPDATE statement with NoneType null in the WHERE clause

### ISSUE THREAD

**Issue by NucleaPeon** [psycopg/psycopg2#1562]
The issue I am facing is that I am unable to successfully update a row by including a `null` value in the `WHERE` clause on a column that allows for nulls.

**Psycopg2 Pip Version Packages**
```
psycopg                  3.1.8
psycopg-pool             3.1.6
psycopg2-binary          2.9.2
```

**OS**
`Linux hostname 5.19.0-0.deb11.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1~bpo11+1 (2022-10-03) x86_64 GNU/Linux`

I created a brief example. I'm using the async mode of psycopg2:

```
create table testtable (value varchar(10));
INSERT INTO testtable (value) VALUES ('hello'), ('world'), (null);
```

Now using the psycopg2 cursor, I execute this statement:

```
await cursor.execute("""UPDATE testtable SET value = 'foo' WHERE value is %s""", (None,))
```

This results in 
```
psycopg.errors.SyntaxError: syntax error at or near "$1"
LINE 1: UPDATE testtable SET value = 'foobar' WHERE value is $1
```

This is an odd issue to me since I can use interpolation in `SET value = %s` without issue.

```
await cursor.execute("""UPDATE testtable SET value = %s WHERE value = 'hello'""", (None,))
```

**Comment by dvarrazzo** [comment]
This ticket should have been open to https://github.com/psycopg/psycopg/issues/

Anyway, it looks like for PostgreSQL `IS NULL` and `IS NOT NULL` are not expressions that can be parametrized. After all you cannot pass anything else to `IS`, only `NULL`, so a parameter has limited utility.

If you still want to use a parameter you can use the expression `WHERE value IS NOT DISTINCT FROM %s`, which accepts nulls as well as any other value. See [DISTINCT predicate documentation](https://www.postgresql.org/docs/current/functions-comparison.html).

**Comment by NucleaPeon** [comment]
Thank you, that is exactly what I was looking for.
