### ISSUE TITLE
how to re-connect database when old connect dose not work ? 

### ISSUE THREAD

**Issue by allwell997** [psycopg/psycopg2#1576]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: WIN10
- Psycopg version: 2.9
- Python version: 3.7.9 
- PostgreSQL version: 14.3
- pip version 22

**Describe the bug**
Please let us know:

1: what you did
      for example ,  I have created a good connection to database server , but the system cannot connect the server when some error happens.
2: what you expected to happen
      The psycopy2 can repaire the connection when it disconnects.
3: what happened instead

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
You can call `connection.reset()`, or you can make your own connection, but it will not reconnect itself.
