### ISSUE TITLE
The copy_from function does not accept uppercase names

### ISSUE THREAD

**Issue by glp1002** [psycopg/psycopg2#1581]
**Information**

- OS: Windows 10
- Psycopg version: 2.9.5
- Python version: 3.11.1
- PostgreSQL version:  15.3
- pip version: 23.1.2

**Bug description**
I have found (using the "copy_from" function, as documented [here](https://www.psycopg.org/docs/cursor.html#cursor.copy_from) that psycopg2 does not support uppercase column names, which is incompatible with PostgreSQL notation.

Here you have a simple example:
`  cur.copy_from('file.csv', 'table_name', ('column1', 'COLUMN2'))`

<br>

The error would be:  _The column "COLUMN2" does not exist in the "table_name" relation._

In PostgreSQL [documentation](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) is written that "Key words and unquoted identifiers are case insensitive".

**Comment by dvarrazzo** [comment]
Yes, but that's not a key word. It's an identifier. Identifiers in uppercase require to be double quoted.

I don't know how copy_from behaves. Maybe you can specify `'"COLUMN2"'` as Python string.

However, I discourage you to use `copy_from()`. Use `copy_expert()` and create a SQL string that works in for you in psql.
