### ISSUE TITLE
DLL load failed while importing _psycopg:

### ISSUE THREAD

**Issue by TDavid2509** [psycopg/psycopg2#1585]
**This is a bug tracker**
I modify a little code to adapt my company postgre database, so I need package them on different OS. I execute cmd "python setup.py sdist bdist_wheel" and It works well on linux and mac. When I package code on windows and execute install cmd ">pip install dist\psycopg2-2.9.6-cp310-cp310-win_amd64.whl", it installed successfully, and then I import psycopg2, it report "DDL load failed" error. Is there any doc teaching us to package psycopg2 on Windows system?

**Please complete the following information:**
- OS: windows server 2016
- Psycopg version: 2.9.6
- Python version: 3.10.11
- PostgreSQL version: 12
- pip version

**Comment by dvarrazzo** [comment]
There are no docs, no.

In his project there is the script to package the library in Appveyor and
in psycopg 3 project there is a similar one to package it in GitHub. I
think they are a good starting point, but you you are on your own about the
software to install (I have no experience about installing and configuring
VS).
