### ISSUE TITLE
Documentation sidebar width

### ISSUE THREAD

**Issue by harbulot** [psycopg/psycopg2#1587]
This is not a problem with psycopg2 itself, but just a minor issue with the documentation on the website.

The text of the sidebar on some pages is too wide and overlaid on top of the main text, at least on https://www.psycopg.org/docs/extras.html
This makes it hard to read.

Would it be possible to make the sidebar wider?

(I'm not entirely sure how the documentation is generated, but it could be a matter of setting the [`sidebarwidth` option](https://www.sphinx-doc.org/en/master/usage/theming.html) in Sphinx.)

Here is an example:

![image](https://github.com/psycopg/psycopg2/assets/80994/9bce87ed-c917-42e9-abe0-e378fa58839d)

**Comment by dvarrazzo** [comment]
Woah, that sucks, it didn't use to be that way.

I would rather not have every single method listed there, otherwise the sidebar would take half the content.

The page is also pretty narrow, I'm sure it can be made wider.
