### ISSUE TITLE
Documentation issue on warning regarding SQL injection

### ISSUE THREAD

**Issue by rolf-d2i** [psycopg/psycopg2#1589]
The documentation for Psycopg2 on page "https://www.psycopg.org/docs/usage.html#passing-parameters-to-sql-queries" has a warning about SQL injections which ends with "Not even at gunpoint.". This warning is not documenting the reason to why using python format is a bad for passing variables to SQL. Warnings without any kind of reasons should and must be ignored when developing code as modern are numerous enough that arbitrary warnings cannot be followed.
It would be good if this text was amended to include references to SQL injections risks as the reason to avoid using python format.
I do believe that documentation was produced from your git repositiory.

**Comment by dvarrazzo** [comment]
There are warning spewed throughout the entire pages and links, from the wikipedia page article to the little bobby table comic. I don't think there is anything to add there.
