### ISSUE TITLE
pycopg fails to compile at mingw compile time for win32

### ISSUE THREAD

**Issue by ThomasCui** [psycopg/psycopg2#1590]
In win32's mingw, compile pycopg

**Please complete the following information:**
- OS: Windows + mingw
- Psycopg version: tag 2.9.6
- Python version:

**Describe the bug**
Please let us know:
I expect it to compile properly, but the following error occurred
1. psycopg/win32_support.h:43:6: error: #elif with no expression
2. psycopg/pqpath.o:pqpath.c:(.text+0x184f): undefined reference to `timeradd'

I expect the following modifications
1. Delete #elif in line 43 of the win32_support.c file
2. Move the timeradd function from the win32_support.c file outside #endif

**Comment by dvarrazzo** [comment]
Your expectations are cute, but out of place and pretty impolite. I am going to attribute this to linguistic differences, but you should replace "I expect to" with "Can you please / It would be great if / Thank you very much for your work I am using for free".

Mingw is not supported. If you would like to have it supported:

- provide a merge request with the changes required
- create a Github Action job to build the package and test that it works.

You can expect this ticket to be closed at or after the 2023-06-30 if you don't provide this work yourself.

**Comment by ThomasCui** [comment]
You are absolutely right. I apologize for my rude tone and will make sure to use more polite language in the future. Thank you for bringing this to my attention.
