### ISSUE TITLE
copy_expert: io buffer and/or decoding/encoding is a bottleneck

### ISSUE THREAD

**Issue by hottwaj** [psycopg/psycopg2#1592]
**Please complete the following information:**
- OS: Ubuntu 20.04
- Psycopg version: 2.9.5
- Python version: 3.10.2
- PostgreSQL version: 12
- pip version 23.0.1

**Describe the bug**
I've been using copy_expert via django to try and bulk insert ~10M rows of data into a table as fast as possible.

Destination table has no constraints or indexes (except PK)

When I run COPY via PSQL, a file of 1M rows can be written in ~2.5s

When I switch to python and run copy_expert, only about 10k rows are written per second.  I am writing the data in chunks and have varied chunksize from 10k to 1M rows with no improvement on write rate.  When using copy_expert I am writing each chunk of e.g. 10k rows via a separate call to copy_expert.

I noticed that CPU usage is around 90% python, 10% postgres.  My suspicion is that majority of time is spent encoding/decoding bytes of the CSV file on a line by line basis in python so that they can be sent to the server's STDIN, so postgres is mostly waiting for additional lines to be written rather than doing useful work.

I have also tried passing different "file-like" objects to copy_expert: i) a path to a csv file e.g. "\tmp\foo.csv" ii) an instance of BytesIO and ii) and instance of StringIO.  These do not make a difference

Is there a variation of some file-like object that I could pass that would avoid the encoding/decoding step?  This should be avoidable so that data can be pushed through to STDIN faster.

Thanks!

**Comment by dvarrazzo** [comment]
If you open the file in binary mode there will be no encoding/decoding. No other operation should be performed by psycopg 2 (or by psycopg 3 in block mode copy).

I don't know how you are comparing psycopg with psql: if you are running `COPY ... FROM 'filename'` then the file is already on the server and it will surely be faster. psycopg does the equivalent of `cat filename | psql -c "COPY ... FROM STDIN"`. If you can copy the file on the server, you can run the first statement via psycopg.

**Comment by hottwaj** [comment]
Thanks, in this case I was running psql, python and postgres on same machine so connection to server is not a factor. I profiled the python code and ~99% time was spent in copy expert so I know that other code is not the culprit...
Will do some more testing and compare to using cat/pipe then will come back with any findings. Thanks

**Comment by hottwaj** [comment]
Have investigated further and now have come back to correct myself: I was not profiling in a granular enough way and so had misdiagnosed.  psycopg is not the cause - all my fault :) 

Thanks!
