### ISSUE TITLE
psycopg2-binary 2.9.6 breaks celery worker on Apple silicon

### ISSUE THREAD

**Issue by richardbrockie** [psycopg/psycopg2#1593]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: MacOS Ventura (Apple silicon & Intel) and Big Sur (Apple silicon) 
- Psycopg version: psycopg2-binary v2.9.6
- Python version: 3.10.9
- PostgreSQL version: 120015
- pip version: 23.1.2

**Describe the bug**
Please let us know:

1: I deploy to Heroku which requires psycopg2-binary rather than psycopg2, so I use the binary in development. My Django app has a celery task queue using rabbitmq. I rolled psycopg2-binary forward from 2.9.5 to 2.9.6 to test out the latest version. I have 2 Apple silicon and one Intel MacOS test machines.

2: what you expected to happen - celery workers would still be able to access the database using the Django ORM.

3: what happened instead - on the Apple silicon computers only (no error on the Intel machine), I get the following ERROR at the first database interaction:

```
[2023-06-22 22:06:38,273: INFO/MainProcess] Task racereg.tasks.test_database_access[3a06732e-3e86-451b-a762-43854efb0198] received
[2023-06-22 22:06:38,376: INFO/ForkPoolWorker-1] racereg.tasks.test_database_access[3a06732e-3e86-451b-a762-43854efb0198]: settings.DEV_HOST: True
[2023-06-22 22:06:38,377: INFO/ForkPoolWorker-1] racereg.tasks.test_database_access[3a06732e-3e86-451b-a762-43854efb0198]: celery: 5.2.7 (dawn-chorus)
[2023-06-22 22:06:38,377: INFO/ForkPoolWorker-1] racereg.tasks.test_database_access[3a06732e-3e86-451b-a762-43854efb0198]: psycopg2: 2.9.6 (dt dec pq3 ext lo64)
objc[19744]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[19744]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2023-06-22 22:06:38,382: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:19744 exited with 'signal 6 (SIGABRT)'
[2023-06-22 22:06:38,394: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT) Job: 0.')
Traceback (most recent call last):
  File "/Users/richard/VirtualEnvs/ontheday_heroku_3.10.9/lib/python3.10/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 0.

```

If possible, provide a script reproducing the issue.

Here's my simple celery task that triggers the error:

```
@shared_task()
def test_database_access():
    from .models import RaceDay

    import psycopg2

    celery_logger.info(f"settings.DEV_HOST: {settings.DEV_HOST}")
    celery_logger.info(f"celery: {celery.VERSION_BANNER}")
    celery_logger.info(f"psycopg2: {psycopg2.__version__}")

    test_race = RaceDay.objects.order_by('date').last()
    celery_logger.info(test_race)

    return True

```

An interesting note - using psycopg2 rather than psycopg2-binary on Apple silicon DOES NOT trigger the error. This suggests to me that the problem is restricted to just the Apple silicon binary, and not the psycopg2 v2.9.6 in general.

Keeping pscopg2-binary at v2.9.5 avoids the problem.

**Comment by dvarrazzo** [comment]
macOS binary and forking have a surprising and evolving behaviour. It is a type of problem that you might want to look in conjunction with Celery people, so that you can establish a safe forking policy respectful of macOS whims.

Unfortunately it's totally outside our control.

**Comment by richardbrockie** [comment]
> macOS binary and forking have a surprising and evolving behaviour. It is a type of problem that you might want to look in conjunction with Celery people, so that you can establish a safe forking policy respectful of macOS whims.
> 
> Unfortunately it's totally outside our control.

Thanks for the reply. Out of interest, when I use psycopg2 rather then psycopg2-binare in my requirements, I specify "/opt/homebrew/opt/postgresql@12/bin" as part of my $PATH. Does it matter which version of postgres is assumed when the binary is generated?

I'll report the problem in the celery issue tracker.
Best wishes,
Richard Brockie
