### ISSUE TITLE
Wrong parse of psycopg2 named placeholders

### ISSUE THREAD

**Issue by ritka-admin** [psycopg/psycopg2#1597]
Hi! I'm trying to compose a query using named placeholders, but after putting a named placeholder reference into the query I get this error: `ValueError: unsupported format character: '('`. The code:

```python
with create_connection() as conn: 
    with conn.cursor() as cursor:
        values = sql.SQL(',').join(map(sql.Placeholder, ['reply', 'post_id', 'comment_id']))
        values_template = sql.SQL('(') + values + sql.SQL(')')
        print(values_template.as_string(conn))
        # (%(reply)s,%(post_id)s,%(comment_id)s)

        execute_values(
            cursor,
            '''
            update table.comment
            set reply_to_comment = (
                with comp as (
                    select id from table.comment 
                    where reply_to_comment = %(reply)s
                )
                select id from comp
            ) 
            where table_post_id = %(post_id)s and table_comment_id = %(comment_id)s
            ''',
            [{'reply': comment.reply_to_comment,
              'post_id': comment.table_post_id,
              'comment_id': comment.table_comment_id}
            for comment in comments],
            template=values_template
        )
```
I'm getting the same error without using the dictionary snippet (`template` argument).

During the debug I've noticed that '_split_sql' method splits `%(reply)s` as `%(` and the rest.

May be I've made a mistake somewhere?

**Comment by dvarrazzo** [comment]
>
> May be I've made a mistake somewhere?
>
Yes, read the sql parameter in the function documentation.

**Comment by ritka-admin** [comment]
> May be I've made a mistake somewhere?
> Yes, read the sql parameter in the function documentation.

Thank you, worked for me!
