### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [psycopg/psycopg2#1609]
Is it possible next time on release new version make the github release to have entry on https://github.com/psycopg/psycopg2/releases entries? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by dvarrazzo** [comment]
No, I don't wish to receive more bureaucratic burden, or ambiguity about what has been release.

A release happens on pypi only. Should there be any misalignment between pypi and github it would be a problem.

Some quick googling suggests that there are services you can subscribe to notify for new releases in pypi, or maybe you can watch for github tags.

**Comment by kloczek** [comment]
If you have no set watch->release you will not receive anything.
This RFE id not about where is made release but about SPREAD email notifications ONLY.
Please please have look one more time on the documentation about what it is.
