### ISSUE TITLE
error when migration : django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module:, Reason: no suitable image found

### ISSUE THREAD

**Issue by dsin** [psycopg/psycopg2#1617]
- OS: MacOS
- Psycopg version: 2.9.7
- Python version: 3.9.16
- PostgreSQL version: 
- pip version: 23.1.2

**Describe the bug**
1: what you did
I follow [this tutorial](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-django) and got error at step 5, when execute the command
`python manage.py makemigrations cockroach_example`

2: what you expected to happen
successfully migrate

3: what happened instead
got error:
`...
File "/Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 28, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libpq.5.14.dylib
  Referenced from: /Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
	/Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/psycopg2/.dylibs/libpq.5.14.dylib: cannot load 'libpq.5.14.dylib' (load command 0x80000034 is unknown)
	/Users/myusername/Documents/gae/cockroachlabs-example-app-python-django/env/lib/python3.9/site-packages/psycopg2/.dylibs/libpq.5.14.dylib: cannot load 'libpq.5.14.dylib' (load command 0x80000034 is unknown)`

NOTE: This error does not happened in psycopg2-binary==2.8.6.

**Comment by dvarrazzo** [comment]
Sorry but we cannot debug what is installed on you macOS.
