### ISSUE TITLE
Changing psycopg2-binary to 2.9.7 causes an issue

### ISSUE THREAD

**Issue by gebu5** [psycopg/psycopg2#1623]
- OS: OSX
- Psycopg version:  2.9.7
- Python version: 3.11
- PostgreSQL version: 14.8
- pip version : 23.2.1

I am starting a django app but it freezes while trying to connect to DB. 
version 2.9.6 works fine.
Is the  issue with psycopg2 or Django?

**Comment by dvarrazzo** [comment]
No idea. Not enough to say.
