### ISSUE TITLE
Psycopg2.connect(...) causes segmentation fault: 11

### ISSUE THREAD

**Issue by andhim** [psycopg/psycopg2#1626]
Hi,

I am working on my project where I have a backend service and local DB.
Local DB is running on Docker but accessible via a certain port with localhost domain. 

I am running the server in virtualenv and talk to this DB with `psycopg2.connect(...)` but am getting `segmentation fault`.
It works fine when I am running the server in docker but it is causing another issue which I foresee big changes so I cannot go with this approach.

FYI, I've tried with Python version3.11.5 and 3.9.5 and psycopg2's version is 2.9.7.
Any help would be appreciated!

**Comment by dvarrazzo** [comment]
I am sorry but there is too little information to help in your report. It is most likely a problem with the libraries installed on your machine, for which we cannot help.

We would be able to help if you can set up a docker image to reproduce the issue.
