### ISSUE TITLE
ImportError: DLL load failed while importing _psycopg

### ISSUE THREAD

**Issue by yonaiker95** [psycopg/psycopg2#1636]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: windows
- Psycopg version: 2.9.9
- Python version: 3.12
- PostgreSQL version: 16
- pip version 23.2.1

**Describe the bug**
Please let us know:

Traceback (most recent call last):
  File "C:\Users\CODIGODEV\Desktop\Proyectos\Bot_CryptobotX\mongoData.py", line 2, in <module>       
    import psycopg2
  File "C:\Users\CODIGODEV\.virtualenvs\Bot_CryptobotX\Lib\site-packages\psycopg2\__init__.py", line 
51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: No se puede encontrar el módulo especificado.

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
#1628
