### ISSUE TITLE
the cursor make data be confused.

### ISSUE THREAD

**Issue by allwell997** [psycopg/psycopg2#1647]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:
- Psycopg version: 2
- Python version: 3.10.11
- PostgreSQL version: 14.4
- pip version 23.3.1

**Describe the bug**
Please let us know:

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.

I start many threadings in the same time and I create a connection and cursor , then I named them the diffrent variant name in every threading. But I found the data is confused. one in there get the data which is in another data.  so I dont know to solve this problem. 
my email is allwell997@163.com

**Comment by dvarrazzo** [comment]
Please write to the mailing list.
