### ISSUE TITLE
Connection.execute getting stuck on the create table step

### ISSUE THREAD

**Issue by ksmiley92** [psycopg/psycopg2#1656]
**Please complete the following information:**
- OS: Windows
- Psycopg version: 2.9.8
- Python version: 3.6
- PostgreSQL version:  16.x
- pip version  21.2.2

Hello,

I'm attempting to create a table a geometry using a postGIS library and insert into a postgreSQL db

after isolating some of the code I found that it gets stuck indefinitely on the execute create table step, or it gives
me an error saying access violation!

I also tried adding the close command

here is the code:
 
# create polygon table
import psycopg2
from shapely.geometry import Polygon

connection = psycopg2.connect(database="pythonspatial",user="postgres",password="postgres")
cursor= connection.cursor()
cursor.execute("CREATE TABLE poly (id SERIAL PRIMARY KEY, location GEOMETRY)")
a=Polygon([(-106.936763,35.958191),(-106.944385,35.239293),(-106.452396,35.281908),(-106.407844,35.948708)])
cursor.execute("INSERT INTO poly (location) VALUES (ST_GeomFromText('{}'))".format(a.wkt))
connection.commit()

**Comment by dvarrazzo** [comment]
This is an issue with your server, it has nothing to do with psycopg.
