### ISSUE TITLE
Django and LGPL

### ISSUE THREAD

**Issue by lucoder89** [psycopg/psycopg2#1663]
I know that there were several questions about LGPL licensing, but I want to be certain here.

We want to use psycopg2 in our commercial project with closed source code. Project is based on Django, psycopg2 is installed using pip.

psycopg2 isn't modified, it's just used as Django's database default engine. I assume that using psycopg2 that way, doesn't affect our code licensing and we can use it commercially without releasing the code?

Best regards!

**Comment by dvarrazzo** [comment]
Yes, that's perfect. By the LGPL terms, you can use the library in a commercial, closed-source project no problem.

I wish you the best of luck with your project!
