### ISSUE TITLE
psycopg2.ProgrammingError: no results to fetch

### ISSUE THREAD

**Issue by LinChiaWei** [psycopg/psycopg2#1675]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:Windows11
- Psycopg version:2.9.3
- Python version:3.8.7
- PostgreSQL version:13.13
- pip version:20.2.3

**Describe the bug**
Please let us know: no results to fetch after using"INSERT.... RETURNING"

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.

```
import psycopg2

song_detail` = [['僕...', 'あたらよ', 'https://i.scdn.co/image/ab67616d00001e029efd9858adaf5e9af4c817c9', '2024-02-17 15:54:16']]
connection = psycopg2.connect(database="postgres",user="postgres",password="postgres",host="127.0.0.1",port='5432')
cursor = connection.cursor()
cursor.executemany("INSERT INTO listened_list (song_name, artist, image_url, timestamp_column) VALUES(%s, %s, %s, %s) RETURNING song_id", song_detail)
print(cursor.fetchone()[0])
connection.commit()
connection.close()
```
ProgrammingError: no results to fetch

**Comment by dvarrazzo** [comment]
Executemany doesn't return.

**Comment by dvarrazzo** [comment]
Note: in psycopg 3 you can use `executemany(returning=True)` instead. [Docs here](https://www.psycopg.org/psycopg3/docs/api/cursors.html#psycopg.Cursor.executemany).

**Comment by LinChiaWei** [comment]
Solved it. Thanks a lot!
