### ISSUE TITLE
Relistening to PostgreSQL notifications fails after PostgreSQL restarts

### ISSUE THREAD

**Issue by olof-dev** [psycopg/psycopg2#1679]
Thank you so much for this package!

- OS: Ubuntu Linux
- Psycopg version: 2.9.9
- Python version: 3.10
- PostgreSQL version: 14
- pip version: 24.0

Below is a script that demonstrates the problem. It `LISTEN`s to notifications on a channel `test_update`, and prints them when they arrive. It also reconnects and re-listens after a few seconds if the PostgreSQL server is restarted. For some reason `NOTIFY`s no longer come through after the reconnect + re-`LISTEN` (but the connection works otherwise).

```python
# test_reader.py
import asyncio
import psycopg2
import signal
import time

db_name = 'dbname'
db_user = 'dbuser'

conn: psycopg2.extensions.connection
loop: asyncio.AbstractEventLoop

def connect_to_db_and_listen():
    global conn
    conn = psycopg2.connect(f"dbname={db_name} user={db_user}")
    conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
    cursor = conn.cursor()
    cursor.execute("LISTEN test_update;")
    loop.add_reader(conn, handle_notify)
    print("Listening for notifications on channel 'test_update'.")

def handle_notify():
    print("handle_notify()")
    try:
        conn.poll()
    except psycopg2.OperationalError as e:
        # Probably the postgresql server is restarting
        print(f"Caught an OperationalError: {e}")
        print("Attempting to reconnect to the database in 5 seconds.")
        time.sleep(5)
        connect_to_db_and_listen()
        return
    while conn.notifies:
        notify = conn.notifies.pop(0)
        print(f"Got NOTIFY: {notify.pid}, {notify.channel}.")

async def main():
    global loop
    loop = asyncio.get_running_loop()
    stop = loop.create_future()
    loop.add_signal_handler(signal.SIGTERM, stop.set_result, None)
    loop.add_signal_handler(signal.SIGINT, stop.set_result, None)
    connect_to_db_and_listen()
    await stop

asyncio.run(main())
```

To test:

```
python3 test_reader.py
```

In psql: `NOTIFY test_update;` results in the Python script printing:

```
Listening for notifications on channel 'test_update'.
handle_notify()
Got NOTIFY: 131981, test_update.
```

To restart PostgreSQL: `sudo systemctl restart postgresql`

The Python script then outputs:

```
Caught an OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

Attempting to reconnect to the database in 5 seconds.
Listening for notifications on channel 'test_update'.
```

So far, so good. I can confirm that the reconnection works (e.g. by issuing a `SELECT 1+1;` and fetching the result). But now issuing `NOTIFY test_update;` in psql yields no result in the Python script.

What's even stranger is that if I create another connection (creating a copy of  `conn` called `conn2` and a corresponding `handle_notify2`), then:
- Before restarting PostgreSQL, I see the notifications twice, as expected, but
- After restarting PostgreSQL, notifications come through on the (new) second connection, but not on the (new) first connection.

**Comment by olof-dev** [comment]
Thank you very much! That works great in psycopg 3 - I am going to try migrating the project over.

Btw, `signal` is just there to handle quitting with CTRL-C etc, and the global variables are there just to avoid having to create wrappers around the callbacks,just for this MWE. In the actual code (where the problem  was found), global variables aren't used. But yes, maybe the issue is with asyncio or postgresql rather than psycopg2. In any case, onwards to psycopg 3!

**Comment by dvarrazzo** [comment]
In order to handle a ctrl-c and a graceful exit you can use normal Python exceptions:

```python
import asyncio
import psycopg

db_name = "piro"
db_user = "piro"

async def connect_to_db_and_listen() -> None:
    conn = await psycopg.AsyncConnection.connect(
        f"dbname={db_name} user={db_user}", autocommit=True
    )
    await conn.execute("LISTEN test_update")
    print("Listening for notifications on channel 'test_update'.")
    async for notify in conn.notifies():
        print(f"Got NOTIFY: {notify.pid}, {notify.channel}.")

async def main() -> None:
    while True:
        try:
            await connect_to_db_and_listen()
        except psycopg.OperationalError as e:
            print(f"Caught {type(e)}: {e}")
            print("Attempting to reconnect to the database in 5 seconds.")
            await asyncio.sleep(5)
        except asyncio.CancelledError as e:
            print(f"Caught {type(e)}")
            break

try:
    asyncio.run(main())
except KeyboardInterrupt as e:
    print(f"Caught {type(e)}")
```

**Comment by dvarrazzo** [comment]
And, instead of having your own retry loop, you can use a pool with one connection and rely on it to handle the reconnection, which would use some backoff itself to wait for the server restart. You can check the pool behaviour from the logging messages:

```python
import asyncio
import logging
import psycopg
from psycopg_pool import AsyncConnectionPool

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logging.getLogger("psycopg").setLevel(logging.INFO)

db_name = "piro"
db_user = "piro"

pool = AsyncConnectionPool(
    f"dbname={db_name} user={db_user}",
    kwargs={"autocommit": True},
    min_size=1,
    open=False,
)

async def connect_to_db_and_listen() -> None:
    async with pool.connection() as conn:
        await conn.execute("LISTEN test_update")
        print("Listening for notifications on channel 'test_update'.")
        async for notify in conn.notifies():
            print(f"Got NOTIFY: {notify.pid}, {notify.channel}.")

async def main() -> None:
    await pool.open(wait=True)
    while True:
        try:
            await connect_to_db_and_listen()
        except psycopg.OperationalError as e:
            print(f"Caught {type(e)}: {e}")

try:
    asyncio.run(main())
except KeyboardInterrupt as e:
    print(f"Caught {type(e)}")
```

**Comment by olof-dev** [comment]
Fantastic - using a connection pool like that seems to provide a great separation of concerns. I'll try to set that up in the migration. Thanks!

**Comment by olof-dev** [comment]
I noticed one functional difference between the original code and the new one, to do with 'packets' of notifications. In the original code I would sometimes get a list of notifications all in one go (in 'one packet') in the handler, whereas with the `async for notify in conn.notifies()` method I think I always just get one at a time.

With the former method I could then batch-process the `NOTIFY`s and just perform one db-query to get all the required updated data. With the new method it looks like I will have to query the database separately for each notification, to pull in the updated data, even if they actually arrived in the same batch/from the same transaction.

I'm loving the async features of psycopg 3. Is there a way to maintain the old behaviour (of processing 'packets' of `NOTIFY`s all in one go) with it?
