### ISSUE TITLE
Fails to execute in an Azure Function

### ISSUE THREAD

**Issue by DomRoberts** [psycopg/psycopg2#1683]
- [X] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [X] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [X] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Azure Function Debian Linux
- Psycopg version: 2.8.4
- Python version: 3.8
- pip version: 24.0

I build my application on Github Actions and then deploy it to a Function app in Azure. When I execute the code that imports psycopg2.sql then an exception is thrown
ImportError: libpq.so.5: cannot open shared object file: No such file or directory.

Having investigated this online I have installed psycopg2-binary and removed psyopg2. When that happens I get a more immediate error of psycopg2 module not found error.
I have tried it with and without Psycopg2 installed and always the same result.
Psycopg2 doesn't seem to work correctly when installed on an Azure Function

**Comment by dvarrazzo** [comment]
I don't know about Azure functions. They are not free software, so I cannot spend time looking for a solution for free. Feel free to reach out for a private consultancy.
