### ISSUE TITLE
copy_expert raises invalid socket error without any debug'able traceback.

### ISSUE THREAD

**Issue by Krishnasai3cks** [psycopg/psycopg2#1689]
Specs:
- OS: Ubuntu
- Psycopg version:2.9.9
- Python version: 3.8.13
- PostgreSQL version: 14
- pip version: 24.0

I'm getting 
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[5], line 25
     23     curr_file = output_file.read()
     24     output_file.seek(0)
---> 25     cursor.copy_expert(query, output_file)
     26 conn.commit()
     27 conn.close()

OperationalError: invalid socket
```
This is only happening on my production database.
It just says invalid socket and the traceback ends. I'm unable to figure out the root cause of this issue.
I've tried to search online for any leads but there aren't any.

I try the same commands in my local system and it doesn't fail.
My Local System Specs:
- OS: Mac OS M1
- psycopg2 version: 2.9.9
- Python version: 3.9.5
- PostgreSQL version: 16
- pip version: 23.3.2

Just some leads why this error might occur would be of great help.

**Comment by dvarrazzo** [comment]
I think you should look at your server logs.
