### ISSUE TITLE
errors to compilation

### ISSUE THREAD

**Issue by marianoggg** [psycopg/psycopg2#1693]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Before opening this ticket, please confirm that:**
- [x] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [x] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [x] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

**Please complete the following information:**
- OS: Linux Debian Bullseye
- Psycopg version: Source distribution
- Python version: 3.12.2
- PostgreSQL version: 16.2 
- pip version: 23.3.1

Hello good! I'm trying to install psycopg2 from a conda virtual environment, on a Bullseye debian linux.
I'm getting a compilation error from the library source. Please allow me to share them with you so that you can help me. Thank you so much!

![image](https://github.com/psycopg/psycopg2/assets/97843377/5e23ef10-f68d-4e38-89c4-8fa07bc4c9a9)

![image](https://github.com/psycopg/psycopg2/assets/97843377/cbde650b-8d34-4f4b-9ba4-1bdbf419e071)

**Comment by dvarrazzo** [comment]
Read the docs.

**Comment by marianoggg** [comment]
Wow! I already did! Sorry, I thought this was a place to get help. Thank you!
