### ISSUE TITLE
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

### ISSUE THREAD

**Issue by pd-25** [psycopg/psycopg2#1703]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: windows 11
- Psycopg version: 2.9.6
- Python version: 3.12.1
- PostgreSQL version:16
- pip version: 24.0

**config.py**:
import os
from dotenv import load_dotenv

# as config is not where main.py, so we have to declaer the path
from pathlib import Path

env_path = Path(".") / ".env"
# print(env_path)
load_dotenv(dotenv_path=env_path)

class Setting:
    PROJECT_TITLE: str = "Pradipta Blog Apis"
    PROJECT_VERSION: str = "0.1.0"

    POSTGRES_USER: str = os.getenv("POSTGRES_USER")
    POSTGRES_PASSWORD: str = os.getenv("POSTGRES_PASSWORD")
    POSTGRES_SERVER: str = os.getenv("POSTGRES_SERVER")
    POSTGRES_PORT: str = os.getenv("POSTGRES_PORT")
    POSTGRES_DB: str = os.getenv("POSTGRES_DB")
    DATABASE_URL: str = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}"

settings = Setting()

-------------------------
**session.py**:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from core.config import settings
from typing import Generator

SQLALCHEMY_DATABASE_URL = settings.DATABASE_URL
print("Database url is ", SQLALCHEMY_DATABASE_URL)
engine = create_engine(SQLALCHEMY_DATABASE_URL)
print("Database url is-------- ", SQLALCHEMY_DATABASE_URL)
SESSIONLOCAL = sessionmaker(autoflush=False, autocommit=False, bind=engine)

def get_db() -> Generator:
    try:
        db = SESSIONLOCAL()
        yield db
    finally:
        db.close()

----------------------------
**requirements.txt**:
fastapi==0.100.0
uvicorn==0.22.0

SQLAlchemy==2.0.13
psycopg2==2.9.6 

python-dotenv==1.0.0

alembic==1.11.1

pydantic[email]

passlib[bcrypt]
--------------------------
all are installed and virtualenv activated..
**--------------Error----------------**
When Running **unvicorn main:app --reload**  getting this error
------
<img width="547" alt="vn" src="https://github.com/psycopg/psycopg2/assets/85426060/8e02726b-9e11-4288-b1ed-abfd64e8bf48">

**Comment by dvarrazzo** [comment]
This is an installation error and I cannot debug it.

**Comment by pd-25** [comment]
@dvarrazzo  Yes It is some version issue. The versions I was installing was not compatible with environment.  I installed the latest it worked for me.
