### ISSUE TITLE
psycopg2==2.9.9 won't be recognized on Python 3.12.4 (Windows 10)

### ISSUE THREAD

**Issue by codingPineAppl3** [psycopg/psycopg2#1709]
**Please complete the following information:**
- OS: Windows 10
- Psycopg version: 2.9.9
- Python version: 3.12.4
- PostgreSQL version: 16.3
- pip version: 24.1.1

**Describe the bug**
I get "ModuleNotFoundError: No module named 'psycopg'" even though psycopg2==2.9.9 is installed. I work with venv. But I also tried to install it globally and still got the same error. I also tried to install the binary version as suggested in this [StackOverflow page](https://stackoverflow.com/questions/59985554/modulenotfounderror-no-module-named-psycopg2-but-it-is-installed). I am out of ideas.
![Capture](https://github.com/psycopg/psycopg2/assets/51518928/1b35b0cc-150f-4d8b-b916-2e315b653a96)

**Comment by dvarrazzo** [comment]
You have install `psycopg2` but the import error reports `psycopg` which is Psycopg 3.

**Comment by codingPineAppl3** [comment]
> You have install `psycopg2` but the import error reports `psycopg` which is Psycopg 3.

It doesn't matter if I install psycopg2 or psycopg. Even If I install both, I still get this error.

**Comment by dvarrazzo** [comment]
You must be installing them the wrong place. The error says that the module is not found. You are probably using pip from one environment and python from another.
