### ISSUE TITLE
Using psycopg2 module created ccapiserver.exe processes on Windows

### ISSUE THREAD

**Issue by sowndarya2701** [psycopg/psycopg2#1720]
Hi,

This issue still occurs whenever we use psycopg2 module --> https://github.com/psycopg/psycopg2/issues/1138
Do you have some explanation for this ?

Thnx.

**Comment by dvarrazzo** [comment]
My guess is that it's a support process for GSSAPI. Try to disable GSS connection using the right [libpq options](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS), for instance `gssencmode=disable`.

As per #1138, it's not psycopg directly to fork a new process; probably it's something coming from the libpq, and you can have better details from libpq windows developer.
