### ISSUE TITLE
When I used GitHub's CI feature, this issue occurred

### ISSUE THREAD

**Issue by whilefoxfox** [psycopg/psycopg2#1721]
**Please complete the following information:**
- OS: macos
- Psycopg version:  2.9.9
- Python version: 3.9.6
- PostgreSQL version: 16.4 
- Poetry version 1.8.3

**Describe the bug**
When I used GitHub's CI feature, this issue occurred：
This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "psycopg2 (==2.9.9)"'.

**Comment by dvarrazzo** [comment]
I don't know what it means. It seems an unsupported feature. You might try with psycopg 3.
