### ISSUE TITLE
cursor.fetchall() returning  ValueError: year -1 is out of range

### ISSUE THREAD

**Issue by nikhilkudavemnh** [psycopg/psycopg2#1726]
the query is failing with ValueError: year -1 is out of range, in cursor.fetchall()
but in the database its working.

**Please complete the following information:**
- OS: Ubuntu 22.04
- Psycopg version: unknown since not defined picking it automatically
- Python version:3.10
- PostgreSQL version:15
- pip version:22.3.1 

**Describe the bug**
Please let us know:
Query consists of 
select
to_char((appln.created_date AT time ZONE 'utc' AT time ZONE 'Asia/Calcutta'),'dd-mm-yyyy hh24:mi'),
to_char((appln.last_status_change_date AT time ZONE 'utc' AT time ZONE 'Asia/Calcutta'),'dd-mm-yyyy hh24:mi') AS "stateEnteredDate"
from application appln
where appln.created_date between '2020-08-01T00:00:00.000Z' AND '2024-08-31T23:59:59.999Z' 

date filter got replaced here by string replace

**Comment by dvarrazzo** [comment]
Can you find, in your dataset, the value that causes the problem?

**Comment by nikhilkudavemnh** [comment]
no, I have checked the invalid values in the database by this query
SELECT * FROM your_table WHERE date_column IS NOT NULL AND EXTRACT(YEAR FROM date_column) < 1;
but still not getting anything.

**Comment by nikhilkudavemnh** [comment]
It is fixed, this query has a date of birth columns which has '0001-12-31' dates, which is causing problem

**Comment by dvarrazzo** [comment]
Thank you for checking! I wish you a good day!
