### ISSUE TITLE
Issues with Python 3.13: undefined symbol: _PyInterpreterState_Get

### ISSUE THREAD

**Issue by cedricbonhomme** [psycopg/psycopg2#1734]
Hello,

It seems that psycopg2(-binary) is not working yet with Python 3.13. I have found and read other issues related to this problem, like for example [this one](https://github.com/psycopg/psycopg2). So I thought that the issue with Python 3.13 is fixed and decided to git it a try. But it seems that no. See here:

```python
$ python
Python 3.13.0 (main, Oct 10 2024, 07:28:38) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import psycopg2
  File "/home/cedric/.cache/pypoetry/virtualenvs/vulnerabilitylookup-6JZjMWql-py3.13/lib/python3.13/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
    ...<10 lines>...
    )
ImportError: /home/cedric/.cache/pypoetry/virtualenvs/vulnerabilitylookup-6JZjMWql-py3.13/lib/python3.13/site-packages/psycopg2/_psycopg.cpython-313-x86_64-linux-gnu.so: undefined symbol: _PyInterpreterState_Get
>>> 
```

I an wondering if the latest version of psycopg2 has been pushed on Pypi ? Especially because 'Python 3.13' is not listed in the list 'Programming language', here: https://pypi.org/project/psycopg2-binary/

I see that Python 3.13 is here: https://github.com/psycopg/psycopg2/blob/master/setup.py#L61
but for psycopg version 2.9.10.dev1.

Thank you !

**Before opening this ticket, please confirm that:**
- [X] I am running the latest version of pip, i.e. typing ``pip --version`` you get [this version](https://pypi.org/project/pip/).
- [X] I have read the [installation documentation](https://www.psycopg.org/docs/install.html) and the [frequently asked questions](https://www.psycopg.org/docs/faq.html)
- [X] If install failed, I typed `pg_config` on the command line and I obtained an output instead of an error.

I am using psycopg since several years now.

**Please complete the following information:**
- OS: Debian latest
- Psycopg version: 2.9.9
- Python version: 3.13
- PostgreSQL version: Debian 15.8-0+deb12u1
- pip version: 24.2

**Comment by dvarrazzo** [comment]
#1692.
