### ISSUE TITLE
Avoid parsing a UUIDField

### ISSUE THREAD

**Issue by seagrine** [psycopg/psycopg2#1746]
Hello! We have a use case where we are reading an absolute ton of UUIDs. Having psycopg calling `uuid.UUID(data)` [on all of them](https://github.com/psycopg/psycopg2/blob/a805acf59f402f554e95624b5e27518169ca7715/lib/extras.py#L669) is actually a major bottleneck in our system performance. Is there a way to avoid the UUID constructor and simply work with the raw data string/value returned from postgres? Normally we want the UUID type but in this one case we need to make an exception for performance reasons, but we're not sure how to do that.

**Comment by dvarrazzo** [comment]
You can either return `your_field::text` to return text instead of an uuid or you can register the text adapter  for the UUID type. There are a few information [in the faq](https://www.psycopg.org/docs/faq.html#problems-with-type-conversions).
