### ISSUE TITLE
is it normal to allow to use ssl key parameter in the options

### ISSUE THREAD

**Issue by johncooler** [psycopg/psycopg2#1748]
I see this config in bunch of projects
```
'OPTIONS': {
    'sslmode': 'require',
    'sslcert': '/path/to/file',
    'sslkey': '/path/to/file',
    'sslrootcert': '/path/to/file',
},
```
but SSL key should be only on a server side and nowhere else in security considerations
explain please

**Comment by dvarrazzo** [comment]
Not for us to explain.

**Comment by johncooler** [comment]
one more tool in the blacklist, thanks
