### ISSUE TITLE
Update psycopg2-binary 2.9.10 error

### ISSUE THREAD

**Issue by tranvannhat** [psycopg/psycopg2#1756]
- OS: macOS 15.1.1
- Psycopg version: 2.9.10
- Python version: 3.9.9
- PostgreSQL version: 16.1
- pip version: 23.3.2
- poetry version: 1.8.4
I updated psycopg2-binary version from 2.9.9 to 2.9.10 using poetry and I got the following error:

 ld: library 'ssl' not found
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/gcc' failed with exit code 1
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2-binary (2.9.10) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "psycopg2-binary (==2.9.10)"'.

**Comment by dvarrazzo** [comment]
Hello,

this is probably just a manifestation of the problem reported in #1753.

You can specify psycopg != 2.9.10 (in the assumption that we will merge #1755 and fix the problem in the next version), or upgrade your OS. Psycopg 3 has likely the same problem and should receive a similar fix.
