### ISSUE TITLE
builtin_function_or_method' object has no attribute 'lo_open',how can i use it?

### ISSUE THREAD

**Issue by CrawZhou** [psycopg/psycopg2#1757]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:
- Psycopg version:
- Python version:
- PostgreSQL version:
- pip version

**Describe the bug**
Please let us know:

1: what you did
2: what you expected to happen
3: what happened instead

If possible, provide a script reproducing the issue.

**Comment by dvarrazzo** [comment]
No details.
