### ISSUE TITLE
psycopg2.OperationalError: authentication method 13 not supported

### ISSUE THREAD

**Issue by Myxg** [psycopg/psycopg2#1758]
>>> conn=psycopg2.connect(dbname="cmbp", user="sysdba", password="123456", host="127.0.0.1", port=5866)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: authentication method 13 not supported

**Comment by dvarrazzo** [comment]
In `src/include/libpq/protocol.h` it seems that as of PostgreSQL 17 there is no auth method 13. So you are using an unsupported database.

https://github.com/postgres/postgres/blob/REL_17_0/src/include/libpq/protocol.h#L87
