### ISSUE TITLE
DLL ISSUE

### ISSUE THREAD

**Issue by saag7** [psycopg/psycopg2#1761]
- OS: windows 11
- Psycopg version: 2.9.X
- Python version: 3.13
- PostgreSQL version: 17
- pip version : 24.3.1

**Describe the bug**
Please let us know:

1: I tried to run it with postgresql
2: did not execute
3: display some dll error

Please I need help on how to make it run. I've installed the binary and the normal one but still.

**Comment by dvarrazzo** [comment]
#1736. Use Python 3.12.
