### ISSUE TITLE
Support postgesql ver 17.1

### ISSUE THREAD

**Issue by linaheba** [psycopg/psycopg2#1763]
Hello!

I encountered a problem. 
psycopg2 does not want to work with Postgresql version 17.1. 
For all requests it returns psycopg2.operationalerror without any additional information.

With Postgresql versions below 17 everything works fine.

- OS: windows 10
- Psycopg version: 2.9.10
- Python version: 3.9
- PostgreSQL version: 17.1
- pip version: 23.2.1

**Comment by dvarrazzo** [comment]
On the basis that Postgres 17.1 was released one month ago, and that there is no mob with pitchfork at my door, I feel confident to say that this is not a psycopg issue. 

It is much more likely that there is a problem with your database.
