### ISSUE TITLE
Failed to build installable wheels

### ISSUE THREAD

**Issue by 91ahmed** [psycopg/psycopg2#1766]
I got this error while trying to install the library:
`ERROR: Failed to build installable wheels for some pyproject.toml based projects (psycopg2)`

I tried different ways, like installing an old version of psycopg and using the psycopg2-binary instead of psycopg2, but I still get the same error.

**Information:**
- Python version: 3.13.0
- PIP version: 24.3.1
- Windows 10 (32bit)

**Comment by dvarrazzo** [comment]
#1736
