### ISSUE TITLE
Problem importing library psycopg2

### ISSUE THREAD

**Issue by MishaFromNowhere-cmd** [psycopg/psycopg2#1768]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS: Windows 10 Home
- Psycopg version: 2.9.10
- Python version: 3.13
- PostgreSQL version: 17.2
- pip version: 24.3.1

**Describe the bug**
Please let us know: I'm just starting to learn how to work with PostgresQL.

1: what you did    --   I just wrote import psycopg2
2: what you expected to happen   --  nothing
3: what happened instead --  ImportError: DLL load failed while importing _psycopg: The specified module was not found.

If possible, provide a script reproducing the issue.
import psycopg2

**Comment by MishaFromNowhere-cmd** [comment]
Maybe I missed something, forgive me in advance and thank you for your attention

**Comment by MishaFromNowhere-cmd** [comment]
`Traceback (most recent call last):
  File "C:\Users\misha\PycharmProjects\PythonProject\main.py", line 1, in <module>
    import psycopg2
  File "C:\Users\misha\PycharmProjects\PythonProject\.venv\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
    ...<10 lines>...
    )
ImportError: DLL load failed while importing _psycopg: The specified module was not found.`

**Comment by MishaFromNowhere-cmd** [comment]
Traceback (most recent call last):
  File "C:\Users\misha\PycharmProjects\PythonProject\main.py", line 1, in <module>
    import psycopg2
  File "C:\Users\misha\PycharmProjects\PythonProject\.venv\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
    ...<10 lines>...
    )
ImportError: DLL load failed while importing _psycopg: The specified module was not found.

**Comment by dvarrazzo** [comment]
#1736
