### ISSUE TITLE
Return number of rows for copy operations

### ISSUE THREAD

**Issue by fogzot** [psycopg/psycopg2#180]
As asked by Ryan Kelly on the ML:

I'm wondering if it's possible to get the number of rows copied when
using copy_from? I would've thought the .rowcount attribute of the cursor
would have this value, but that doesn't seem to be the case.

**Comment by dvarrazzo** [comment]
Here is a [funny hack](http://www.postgresql.org/message-id/CA+mi_8aKJGZeebAZtddK4ueMSHYBdxsWpDYvhbjJC=YSgd=1Yg@mail.gmail.com) proposed on the ML to access rowcount after copy on psycopg versions.
