### ISSUE TITLE
NamedTupleCursor should support invalid chars in the fields name

### ISSUE THREAD

**Issue by psycoteam** [psycopg/psycopg2#211]
Originally submitted by: jagt

Greetings. As the title suggested, NamedTupleCursor doesn't work well when passing into connect(). Here's a test case:

```
import psycopg2
from psycopg2.extras import NamedTupleCursor

conn = psycopg2.connect("dbname=collective user=collective", cursor_factory=NamedTupleCursor)
cur = conn.cursor()
cur.execute("SELECT 'ok';")
print(cur.fetchone())
```

I'm on Python3.4, psycopg2==2.5.2. Thanks in advance!

**Comment by jmehnle** [comment]
This is a legitimate concern, though, as the extension interface of recent PostgreSQL versions namespaces extension parameters by the extension name, e.g., `citus.shard_max_size` for a [Citus](https://github.com/citusdata/citus) parameter.

Now if I want to query that via `cur.execute("SHOW citus.shard_max_size")` on a connection that's initialized with a `NamedTupleCursor` factory, then that will blow up. Can you perhaps replace unallowed characters with underscores?

**Comment by dvarrazzo** [comment]
Mmm... Good point. I'll give it a think.

**Comment by jmehnle** [comment]
Yay, thank you for fixing this!

**Comment by Jolbas** [comment]
The fix seems to break the ability to use non english characters in identifiers in combination with NamedTupleCursor.

**Comment by Jolbas** [comment]
Is it possible to just replace the characters in question.
Maybe replace:
    s = _re.sub('[^a-zA-Z0-9_]', '_', s)
    if _re.match('^[0-9_]', s):
        s = 'f' + s
    return s
in `lib/extras.py` with:
    return s.strip('?').replace('.','_')

**Comment by dvarrazzo** [comment]
Thank you for reporting the regression. I'll make sure unicode identifiers are handled correctly.

**Comment by dvarrazzo** [comment]
Fixed by blacklisting all the ascii not-alnum chars (replacing them with underscore) and letting Python do what it feels with the remaining (meaning that in Python 3 `åhé` would be valid, in Python 2 would throw an exception).
