### ISSUE TITLE
copy_*() methods swallow exceptions raised in read()

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#270]
If read() raises an exception, copy_from() fails but it reports a generic "error in read()". We should re-raise the original exception instead.

**Comment by dvarrazzo** [comment]
It seems it's not easy to propagate the error, but now at least now we propagate the error message.

Because the interface is not changed (the error class raised is the same) we can backport the fix to psycopg 2.5

**Comment by f0rk** [comment]
@dvarrazzo is there any way this might be enhanced to report more information, such as the stack trace?

**Comment by dvarrazzo** [comment]
Whatever you are asking, which is not clear, is not related to this ticket closed 7 years ago.

**Comment by f0rk** [comment]
currently, only the message associated with the exception is displayed. For example if somewhere inside .read() an exception like decimal.InvalidOperation is raised, all you will see is "InvalidOperation" and the entire traceback, where the exception originated, etc. will be gone.

**Comment by dvarrazzo** [comment]
The question is why do you write into a totally unrelated issue that was closed 7 years ago? You are even saying a reasonable thing, but it won't be taken in consideration until you open a proper ticket.

**Comment by f0rk** [comment]
this isn't unrelated at all. it's an extension of what this ticket did.

**Comment by dvarrazzo** [comment]
The exception traceback and other details is gone because, when we have an error in Python, we need to notify Postgres that we have to interrupt the copy operation. We do it calling `PQputCopyEnd` with a message. The result is that Postgres returns a `QueryCanceled` error.

There is a thing that we should try to do, which is...

I'm not going to explain it here because this is a different bug, which will be fixed in a different release than 2.5.5 and I don't like wasting my time writing things where it's hard to look them up.
