### ISSUE TITLE
Query result set cached even after cursor closed

### ISSUE THREAD

**Issue by mikehwang** [psycopg/psycopg2#280]
Hi

I'm using psycopg2 to connect to and to query AWS Redshift.  I repeatedly execute certain read queries and am noticing that the returned result set does not change when they should be changing.  I am following the advice of the [recommended best practice](http://initd.org/psycopg/docs/faq.html) and closing the cursor after every read query.  I am reusing a single connection and my application is single threaded.  When I create a new connection per execution of the read query, the query result set looks good.

Am I missing something or is this a bug?

I am using the default cursor factory and default cursor creation which I think should be ok.
I'm using python3.4 with psycopg2 version 2.5.4.

Thank you

MIke

**Comment by dvarrazzo** [comment]
A transaction is started at the first query and it is not closed when the cursor is closed. Probably this makes following queries to be executed in the same snapshot. Try putting the connection in autocommit mode or to issuing a `connection.rollback()` between each query.
