### ISSUE TITLE
Unicode Handling Inconsistency in Python 2

### ISSUE THREAD

**Issue by amjith** [psycopg/psycopg2#282]
This script is executed using Python 2.7.9 on OS X (10.9.5). 

I would expect the following script to produce Unicode in the results  and not Str, since I have global type-caster registered. 

```
# -*- coding: utf-8 -*-
from __future__ import print_function

import psycopg2
import psycopg2.extensions
psycopg2.extensions.register_type(psycopg2.extensions.UNICODE)
psycopg2.extensions.register_type(psycopg2.extensions.UNICODEARRAY)

conn = psycopg2.connect(database='postgres')
cur = conn.cursor()
cur.execute("SELECT '日本語' AS japanese")
a = cur.fetchone()[0]
print (a, type(a), repr(a))
```

Results: 

```
$ python ~/test.py   
日本語 <type 'str'> '\xe6\x97\xa5\xe6\x9c\xac\xe8\xaa\x9e'
```

The type should be `unicode` and repr should be `u'\u65e5\u672c\u8a9e'`.

**Comment by amjith** [comment]
I tried this on psycopg2==2.5.4. 

Also I forgot to mention that queries that actually retrieve data from the database such as `select * from abc` will return the values as unicode.

**Comment by dvarrazzo** [comment]
That is because the Postgres type you are returned with an uncast literal is of the type "unknown", not a text type:

    >>> cur.description[0].type_code
    705

    >>> cur.execute("select typname from pg_type where oid = 705")
    >>> cur.fetchone()[0]
    u'unknown'

You must tell Postgres to return a text type to allow psycopg to cast it to unicode:

    >>> cur.execute("SELECT '日本語'::text AS japanese")
    >>> a = cur.fetchone()[0]
    >>> print a, type(a), repr(a)
    日本語 <type 'unicode'> u'\u65e5\u672c\u8a9e'

This is only if you include the text as literal as a string, it is automatic if the text is returned from a table, a function or anything else that gives Postgres a type for it.

**Comment by amjith** [comment]
I understand why this happens. Is there a way to make psycopg2 cast 'unknow' type to unicode? 

Right now it seems like the 'unknown' type is casted into a utf-8 encoded str in Python 2. I'd really like to keep all of that unicode if possible.

**Comment by dvarrazzo** [comment]
You can register the unicode typecaster on the unknown type oid (705, it is constant). Take a look at the [docs about registering new typecasters](http://initd.org/psycopg/docs/advanced.html#type-casting-of-sql-types-into-python-objects). Something like (untested):

    import psycopg2.extensions as ext
    ext.register_type(ext.new_type((705,), "UNKNOWN", ext.UNICODE))

**Comment by amjith** [comment]
Thank you! 

That worked for the 'unknown' case. But then I discovered that hstore doesn't get unicode. 

So instead of adding unicode casting for every datatype that postgres supports, I'm wondering if there is a way to override psycopg2's default behavior where it converts unhandled types to utf-8 encoded strings. Instead if I can get it to return unicode, that would solve my issue.

**Comment by dvarrazzo** [comment]
Yes it does: use `register_hstore(unicode=True)`. Maybe you should read the manual instead of opening a bug: this stuff is pretty documented.

**Comment by amjith** [comment]
My question was not how to make hstore unicode. Because I did read about `register_hstore` on the docs (which are pretty awesome, Thank you!). I'm going to come across a bunch of datatypes supported by Postgres (say Jsonb or uuid etc). Some of them might get converted to utf-8 encoded `str` by psycopg2, because that is default behavior when an equivalent datatype doesn't exist in Python 2. 

My question is how do I change this default behavior to always emit the result as `unicode` instead of `str`. Otherwise I'll have to end up registering handers for a ton of datatypes. 

I'm sorry this questions wasn't clear in my pervious correspondence.

**Comment by dvarrazzo** [comment]
Yes, unfortunately you will have to register an unicode handler for every type you need, but I don't believe there are so many of them. There is no "use unicode globally function". There is rather the plan to just use unicode everywhere, but that's a pretty serious incompatible change so it would only happen in psycopg3.
