### ISSUE TITLE
json / simplejson module selection

### ISSUE THREAD

**Issue by agroszer** [psycopg/psycopg2#284]
I'm not sure whether _json.py does the right thing.

```python
# import the best json implementation available
if sys.version_info[:2] >= (2,6):
    import json
else:
    try:
        import simplejson as json
    except ImportError:
        json = None
```
What's the best implementation?
According to our tests on py 2.7 ( https://github.com/Shoobx/pjpersist/blob/master/src/pjpersist/tests/json_speed_test.py ) and other tests floating on the internet ujson is the fastest, followed by simplejson.

**Comment by dvarrazzo** [comment]
The rationale is: psycopg doesn't have any external dependency and it uses the stdlib json by default for any python version that provides it. The simplejson fallback is only relevant for Py 2.4/2.5 which I don't think you care of; the point is: we use the standard library.

Psycopg provides all the hooks required to customize the json adapter according to your needs, both to tweak the way objects are serialized/deserialized (float vs. Decimal etc) and to allow you the use of the serialization library of your choice: please read the documentation about the Json adapter to learn how.

In a base library such as psycopg our choice is the most rational one: we don't need external dependencies and we allow people to use a different solution if they reckon that's a better choice. You may want to use a parser that is blazing fast but it requires a C++2075 compiler, you may want to use a light-speed library but it crashes with recursive structure... There are tradeoffs that have surely been widely discussed when a Json library has been chosen for inclusion in the stdlib: our project trusts that choice and piggybacks it, while giving you the hooks to choose something different if your needs are more specific.

So, yes: I am pretty sure we do the right thing here.
