### ISSUE TITLE
OSX - ImproperlyConfigured exception -  Symbol not found: _PyBytes_Type occurs when loading Django site after Apache restart

### ISSUE THREAD

**Issue by daredevil82** [psycopg/psycopg2#286]
I'm working on a Django site with Postgres for the first time.  All my previous Django db experience is with MySQL.  For reference, I have a pastebin with the stacktrace exception at http://pastebin.com/TJZ0vXCf

In addition, the compile output from `pip install` is at http://pastebin.com/tR3VCKYB

Machine is running OSX 10.10.2, Apache 2.4, Postgresql 9.4.0, Python 3.4 with mod_wsgi3 configured and added to the Apache configuration.

I have a virtualenvwrapper configured with the following local packages:

Django==1.7
djangorestframework==3.0.4
GDAL==1.11.1
gnureadline==6.3.3
ipython==2.4.0
psycopg2==2.5.4

Note that the virtualenv has been configured with

    mkvirtualenv --python=/usr/local/bin/python3 geocode_env --no-site-packages 

I have a virtualhosts file configured and hosts configured to have dev.geocode.com point to the django application.  In short, this configuration is pretty much identical to what a regular Linux/Apache/Python deployment would work.

After restarting Apache, I consistently get the stacktrace exception linked above, but the interesting part is 

    ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/jason/.virtualenvs/geocode_env/lib/python3.4/site-packages/psycopg2/_psycopg.so, 2): Symbol not found: _PyBytes_Type

I asked this question on StackOverflow, and one of the comments pointed me to this bug report: http://bugs.python.org/issue21122, but the main focus of that error was _Py_NoneStruct during the build process.  This one is tripping up on _PyBytes_Type and is a runtime error.

Finall, note that `pg_config` is in the path, as pg_c<TAB> returns
    pg_config       pg_controldata  pg_ctl

**Comment by dvarrazzo** [comment]
My guess  is that mod_wsgi3 is running with a different python version or libraries than your virtualenv.

**Comment by dvarrazzo** [comment]
Closing the issue as not relevant for psycopg. It's a library mess due to external causes, nothing psycopg can fix. Help would be better asked to mod_wsgi guys.
