### ISSUE TITLE
Document how to cause psycopg2 to use Arrow or Delorean objects for dates

### ISSUE THREAD

**Issue by thedrow** [psycopg/psycopg2#287]
These libraries make handling dates and times much easier and it would be nice if the user could choose to map the date(time) fields to those objects instead of using Python's.
I'm sure there is a hook that will allow me to map pg's date types to those classes but I'm not sure which one is it.

**Comment by dvarrazzo** [comment]
Please read [how to customize adapters and type casters](http://initd.org/psycopg/docs/advanced.html#adapting-new-python-types-to-sql-syntax).
