### ISSUE TITLE
Cannot import Json module from psycopg2.extras.

### ISSUE THREAD

**Issue by Dengjianping** [psycopg/psycopg2#288]
I got an error when I import Json module, code "from psycopg2.extras import Json",
error code:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Json

OS: ubuntu 14.04 32bit
Psycopg version: 2.5.4
Postgresql: 9.4
Python: 2.7.6
PS: But I can import this module successfully on Windows.

**Comment by dvarrazzo** [comment]
I'm relatively sure that you are importing the system psycopg and not the version you think you have installed. Please `print psycopg2.__version__` right after the failed import.

**Comment by Dengjianping** [comment]
I'm very sorry about this, you're right, I thought I installed the latest psycopg, but actually that's 2.4.5, and after the upgrade, everything is ok now.
