### ISSUE TITLE
"like" doesn't work on json transtyped table

### ISSUE THREAD

**Issue by dascritch** [psycopg/psycopg2#289]
Having a table with `metadata` json column, i want to extract any line having a `"fail_on"` key in its metadata.

I'm waiting the `?` operator, so 'im using a `like` command. But unexpectedly psycopg2 doesn't like my ` where ( "metadata"::text like '%"fail_on":%' ) `, which is working directly in psql.

I'm actually using ` ( "metadata"::text != '[]' ) `, running fine but not really futureproof friendly..

Versions :
(packages installed from ubuntu 14.10)

- python 2.7.6
- postgresql 9.3.6
- psycopg2 version 2.5.4

**Comment by dascritch** [comment]
Snip from the error message : 
```
  File "[…]/base.py", line 120, in fetch
    self.cursor.execute(request, params)
  File "[…]/site-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
IndexError: list index out of range

```

**Comment by fogzot** [comment]
You should quote your '%'s, else psycopg will try to use them to bind variables.

**Comment by dascritch** [comment]
` ( "metadata"::text like \'%%\"fail_on\":%%\' )`
yep it worked.
I didn't try to quote % by double it.
facepalm.
