### ISSUE TITLE
2.6 tarball lacks doc/Makefile

### ISSUE THREAD

**Issue by gagern** [psycopg/psycopg2#291]
The http://initd.org/psycopg/tarballs/PSYCOPG-2-6/psycopg2-2.6.tar.gz tarball doesn't contain [doc/Makefile](https://github.com/psycopg/psycopg2/blob/f7ee006bef9eb1f0d515dd810d32e30fca1efc52/doc/Makefile) so a `cd doc` followed by `make`, as described by the [doc/README](https://github.com/psycopg/psycopg2/blob/b744c92f58ab3dfc65d51dfe61acc11427a192dd/doc/README) file, will not work. And if the Makefile were bundled with the tarball, then I guess the README would need some adjustments because the makefile apparently should take care of creating the virtual environment.

**Comment by dvarrazzo** [comment]
You are right: both the `Makefile` and the `requirements.txt` are missing from the sdist. Furthermore the `README` is a bit out of date: it still refers to `easy_install` and doesn't mention the requirements file, which is instead used by the `Makefile`. The `docs` `Makefile` can also be improved by taking care of the `PYTHONPATH` dance required to find the right psycopg module and not one randomly found in the system.
