### ISSUE TITLE
copy_from does not preserve case in table name

### ISSUE THREAD

**Issue by jrenner** [psycopg/psycopg2#296]
psycopg2 version 2.6

```
table name for csv copy: COMBINED_1930_TR
    main()
  File "/home/jrenner/mpc/access-to-postgres-migration/src/migrate-access-to-postgres.py", line 231, in main
    import_data_from_exported_csv(access_db_filename, table, cur)
  File "/home/jrenner/mpc/access-to-postgres-migration/src/migrate-access-to-postgres.py", line 162, in import_data_from_exported_csv
    cur.copy_from(csv_file, table_name)
psycopg2.ProgrammingError: relation "combined_1930_tr" does not exist
```

**Comment by dvarrazzo** [comment]
Thank you. Although we may fix the issue adding double-quotes around the table name this would break immediately 1) all the copy_from with a schema in the table name (`cur.copy_from("foo.bar", file)`) and 2) everybody who has already noticed the problem and quoted the table themselves (`cur.copy_from('"TABLE"', file)`). 1) is especially worrying so I'd say we won't do anything about the issue and rather document the need of quotes.

**Comment by jrenner** [comment]
I understand

**Comment by dvarrazzo** [comment]
Docs to be improved.

**Comment by dvarrazzo** [comment]
Done in https://github.com/psycopg/psycopg2/commit/1d006ccbe9960ecb2c91d50210229b9afaa5c534
