### ISSUE TITLE
Install with pip can fail with multiple pg_config.exe files on Windows

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [psycopg/psycopg2#298]
When pg_config.exe is run to determine the possible location of libpq/libpq-fs.h (and perhaps some other files?) it doesn't check to see if the files actually exist in the folder that it finds, and the install fails if they don't.

On Windows my install of Strawberry Perl has a copy of pg_config that when run gives a location for INCLUDEDIR-SERVER that doesn't even exist and since it was installed before postgresql it was the one found first on the path and an invalid include path was passed to cl.exe causing he install to fail.

**Comment by dvarrazzo** [comment]
Excuse me, and what are we supposed to do? We use pg_config assuming that it returns a meaningful answer. If "Strawberry Perl" screwed up your system installing a pg_config that tells lies it's your problem, not ours.

FYI you can specify the pg_config location using

     python setup.py build_ext --pg-config /path/to/whatever build

to point it to a working version of pg_config.
