### ISSUE TITLE
psycopg2 fails under mod_wsgi

### ISSUE THREAD

**Issue by robertdcurrier** [psycopg/psycopg2#299]
CentOS7 server on Digital Ocean. Python 2.7.5. Psycopg2 installed. Works fine with command line scripts, and under Flask running the app directly, but when run via mod_wsgi fails with:
[Thu Mar 12 15:25:12.456017 2015] [:error] [pid 2395] [remote 71.226.81.79:2800]   File "/var/www/wsgi/gcoos_itag/app/iTAG.py", line 75, in home
[Thu Mar 12 15:25:12.456106 2015] [:error] [pid 2395] [remote 71.226.81.79:2800]     conn = psycopg2.connect("dbname=itag user=postgres")
[Thu Mar 12 15:25:12.456124 2015] [:error] [pid 2395] [remote 71.226.81.79:2800]   File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
[Thu Mar 12 15:25:12.456207 2015] [:error] [pid 2395] [remote 71.226.81.79:2800]     conn = _connect(dsn, connection_factory=connection_factory, async=async)
[Thu Mar 12 15:25:12.456234 2015] [:error] [pid 2395] [remote 71.226.81.79:2800] OperationalError: could not connect to server: No such file or directory
[Thu Mar 12 15:25:12.456242 2015] [:error] [pid 2395] [remote 71.226.81.79:2800] \tIs the server running locally and accepting
[Thu Mar 12 15:25:12.456246 2015] [:error] [pid 2395] [remote 71.226.81.79:2800] \tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[Thu Mar 12 15:25:12.456251 2015] [:error] [pid 2395] [remote 71.226.81.79:2800] 

Since everything works outside of mod_wsgi, AND the exact same config works PERFECTLY on my Mac OS X box, I'm assuming it is a weird mod_wsgi thing on CentOS. Any thoughts? Pulling my hair out...

**Comment by dvarrazzo** [comment]
Don't know what unix user is the mod_wsgi process running, if it's running stand-alone or as the apache user. Does the `/tmp/.s.PGSQL.5432` socket file exist? Can you try connecting via network instead?

You may get better information writing to the mod_wsgi guys though.

**Comment by robertdcurrier** [comment]
Yep, the /tmp file exists. I've tried changing the mod_wsgi user to no
avail. Driving me crazy as this works perfectly on other systems. I'll
catch up with the mod_wsgi guys and see if they have an answer.

Thanks,

Bob Currier

On Thu, Mar 12, 2015 at 4:18 PM, Daniele Varrazzo <notifications@github.com>
wrote:

> Don't know what unix user is the mod_wsgi process running, if it's running
> stand-alone or as the apache user. Does the /tmp/.s.PGSQL.5432 socket
> file exist? Can you try connecting via network instead?
>
> You may get better information writing to the mod_wsgi guys though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psycopg/psycopg2/issues/299#issuecomment-78598867>.
>



-- 
Bob Currier, WD4EWZ
Research Specialist
Department of Oceanography
Texas A&M University
(941) 893-7593
===================================================
“I love being an oceanographer. I see the ocean as my playground,
and gliders, sensors, and filters as my toys. My play buddies are
some of the smartest people in the world.”
  --Ivona Cetinic
===================================================

**Comment by dvarrazzo** [comment]
Closing as likely not psycopg problem, unless shown otherwise.

**Comment by robertdcurrier** [comment]
Found the problem -- under CentOS 7 on DigitalOcean I needed to specify
'host' in the connection string if, and only if, I was using mod_wsgi.  An
implied localhost didn't work, but specifically stating 'host=localhost
dbname=dn_name...' corrected the problem.  On other platforms leaving out
'host=localhost' did not create any problems. <shrug>

Thanks for the help,

Bob Currier

On Tue, Mar 31, 2015 at 5:31 AM, Daniele Varrazzo <notifications@github.com>
wrote:

> Closing as likely not psycopg problem, unless shown otherwise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psycopg/psycopg2/issues/299#issuecomment-88013846>.
>



-- 
Bob Currier, WD4EWZ
Research Specialist
Department of Oceanography
Texas A&M University
(941) 893-7593
===================================================
“I love being an oceanographer. I see the ocean as my playground,
and gliders, sensors, and filters as my toys. My play buddies are
some of the smartest people in the world.”
  --Ivona Cetinic
===================================================

**Comment by dvarrazzo** [comment]
Thank you for letting us know, it may be helpful to someone else
