### ISSUE TITLE
Warning exceptions not thrown as stated in documentation

### ISSUE THREAD

**Issue by kwauchope** [psycopg/psycopg2#302]
psycopg2.Warning exceptions are never raised as stated in documentation. Could be a hangover from when data truncations used to be a warning in postgresql pre 7.2

**Possible resolutions:**

* Add a note in the documentation saying data truncation is an error in postgresql since v7.2 to avoid confusion.

* Change the Warning definition to help avoid confusion (though it then won't be a CC of the PEP 249 definition)

**Comment by dvarrazzo** [comment]
The op edited this bug report and then added #304 with pretty much the same content as before so I guess we can close this.
