### ISSUE TITLE
Documentation error under Basic Module Usage

### ISSUE THREAD

**Issue by nancyorgan** [psycopg/psycopg2#303]
There is a small but potentially confusing error on this page: 
http://initd.org/psycopg/docs/usage.html

The current state is this:

Connect to an existing database
```conn = psycopg2.connect("dbname=test user=postgres")```

However, the quotations are throw errors. Should it be this?
```conn = psycopg2.connect(dbname="test",  user="postgres") ```

**Comment by fogzot** [comment]
It is not an error. psycopg accepts both `dict`-style parameters or a single string with all the parameters specified as `key=value` without quotes.
