### ISSUE TITLE
pgAdmin III query returns different result than psycopg2 query

### ISSUE THREAD

**Issue by JohnNevius** [psycopg/psycopg2#314]
I'm hitting a very odd bug with psycopg2 (psycopg2-2.6.0.win32-py2.7-pg9.4.1-release.exe) 
Running  under Windows32 and Python 2.7.(r27:82525))

The following trivial query returns the expected results when run from the pgAdminIII query window:

SELECT baseinformation_directorynumber FROM meta_subscriber WHERE baseinformation_directorynumber ILIKE ('8634961601');

When I try the same trivial query under Python 2.7:

import sys
import psycopg2

ip = "192.168.200.50"
DB_STRING = "dbname='shadow_config_db' user='shadowconfigread' host='%s' password='TgOiNn1C'"%ip
try:
    db = psycopg2.connect(DB_STRING)
except:
    print "BRAAP, try again sucker. . ."
    sys.exit()
cursor = db.cursor()
#
sqlString = "SELECT baseinformation_directorynumber FROM meta_subscriber \
            WHERE baseinformation_directorynumber ILIKE ('8634961601');"
cursor.execute(sqlString)    
switch_lines = cursor.fetchall()
print switch_lines

I get an empty set returned.

Suggestions are most appreciated

**Comment by fogzot** [comment]
I don't know if pgAdmin does anything special but the `ILIKE` in your query will match only the number '8634961601' and nothing else (because you don't have any `%` and numbers don't have upper/lower case variants).  So, are you sure your query is right?

**Comment by JohnNevius** [comment]
Same query between pgAdmin III console and Python

One returns the expected value, one does not

**Comment by JohnNevius** [comment]
Massive apologies all.  I was using two different target systems to launch the SQL query against.

Complete and total f**kup on my part.
