### ISSUE TITLE
Not a bug but a doc request

### ISSUE THREAD

**Issue by skatastic** [psycopg/psycopg2#315]
It'd be nice if the documentation for copy_from and copy_expert gave a warning to move the position of their stringio object back to 0.  I spent a bunch of time banging my head against the wall trying to figure out why no data was going in my table.  

It'd also be nice if the copy command gave a warning (output) that the stringio object is bigger than the data moved to the table.

**Comment by dvarrazzo** [comment]
The first is not a psycopg bug: it's how you use files, whether real or StringIO.

For the second point, no: StringIO is not different from other files and we don't assume them seekable nor of known size.
