### ISSUE TITLE
Clarification needed in documentation regarding cursor per query

### ISSUE THREAD

**Issue by ilrico** [psycopg/psycopg2#316]
Hello, 

1)
in "Best Pratices" there's an advice to close cursor after each query when data has be fetched.
it's unclear what are the consequences if not doing so (before reading this, i ran my application using same cursor for many different queries (different in query schema not just arguments, ie some INSERT, some UPDATE...)).
i only ran into problem days after, when testing under heavy charge the application: fetching errors occured, etc... i know from stackoverflow that other users made similar mistake, and that RTFM rule should be observed, but it only appears in the FAQ, and before running into problems, people tend to ignore FAQs. Maybe would be good to mention it in "Cursor" section.

2)
In addition, documentation on "Cursor" states "Cursors created from the same connection are not isolated", assuming that cursor may be long-lived objects (many per connection, constrasting with the advice to close() after data fetching).
Also, does it mean that it's good to keep cursor open if we execute many similar queries, only changing arguments (ie. just x changes in a SELECT * FROM table WHERE id=x) ?

3)
Also I read different and contradictory advices regarding performance between
- for rows in cursor.fetchall():
- for rows in list(cursor):
- for rows in cursor:   
a detailled explanation would be great, on when to (not) use them 

4)
Last point, thank you for this great lib,  (prepared statements implementation wud be great ;-) )

**Comment by dvarrazzo** [comment]
I'm sorry but this is not a meaningful "bug". 1) what you do is pretty generic and *does* work. Heavy charge on a cursor is not a problem. If you are using a cursor from many thread that's a problem. There's no improvement we can do to the manual if you admittedly don't read it so I won't bother. 2) there is no contrast here that I see, and you can use the cursor the way you prefer. 3) there's no meaningful performance problem. Of course if you do list(cur) you create a copies of objects but that's obvious in general Python.

Please, if you have found ONE problem open ONE bug. For more general discussions use the mailing list.

**Comment by ilrico** [comment]
i really appreciate that you replied even if it wasn't a bug, but i still
believe it's a documentation issue, so an issue.

i didn't say i never read the documentation, i said that some stuff is
related to cursor can only be found in FAQ, and people usually read FAQ
only when they have a problem.

i use psycopg2 since 2013, so i read many many times the documentations,
stackoverflow, and all what i could find.
that's only when developping a web application that i have to stress the
server and found errors, for i was wondering if it can from cursors and
found documentation unclear.

i couldn't find the answers to all those problems after hours of search
both on documentation and googling (your answer 1- is never that clear in
doc, it's almost the contrary that is understood, for non-threaded world)

anyway thanks again, you answer did added value regarding documentation !



On Sat, May 16, 2015 at 10:32 AM, Daniele Varrazzo <notifications@github.com

**Comment by ilrico** [comment]
i couldn't find the answers to all those problems after hours of search both on documentation and googling (your answer 1- is never that clear in doc, it's almost the contrary that is understood, for non-threaded world)

anyway thanks again, you answer did added value regarding documentation !
