### ISSUE TITLE
inet and cidr adaptation

### ISSUE THREAD

**Issue by philtay** [psycopg/psycopg2#317]
The new [ipaddress](https://docs.python.org/3/library/ipaddress.html) stdlib module is a perfect match for [inet and cidr](http://www.postgresql.org/docs/current/static/datatype-net-types.html) data types. This adaptation should really be implemented for Python 3.3+ users.

**Comment by dvarrazzo** [comment]
Also note that [ipaddress is available in PyPI](https://pypi.python.org/pypi/ipaddress) for Python >= 2.6.

**Comment by dvarrazzo** [comment]
Closed by 643ba70bad0f19a68c06ec95de2691c28e060e48 (wrong bug number in the commit message)
