### ISSUE TITLE
Make a psycopg2 2.6.1 release to pypi

### ISSUE THREAD

**Issue by peterbe** [psycopg/psycopg2#324]
Sorry if this is not the right protocol for asking for this but we're currently depending on the [last commit on master](https://github.com/psycopg/psycopg2/commit/a59704cf93e8594dfe59cf12d416e82a816953a4) for production and really eager to depend on pypi for this instead of a github.com sha.

**Comment by peterbe** [comment]
cc @rhelmer

**Comment by dvarrazzo** [comment]
It may be not "the right protocol", but yes, got the message :) I'll try to make a release within days.

**Comment by peterbe** [comment]
Ok. Appreciate it. We're [blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1164465) on this release coming out because at the moment we have had to install a version with the word "dev0" in it and that breaks Django. (We use our psycopg2 driver for django and a regular full python framework of our own).

**Comment by dvarrazzo** [comment]
Done. Thank you for the patience.

**Comment by peterbe** [comment]
Thank you!
