### ISSUE TITLE
Hstore should replace escape chars inside the for loop

### ISSUE THREAD

**Issue by mcclurem** [psycopg/psycopg2#330]
around line 682 in "extras.py" the parse method for hstore repeatedly calls _bsdec.sub on all values and keys.
Unless I misunderstand this, this behavior is identical to calling it once on the whole string (variable s).
Is there some edge-case interaction with the _re_hstore regex that requires nesting the replace? I've changed the order and it makes runtime for large hstore columns MUCH faster. I can provide a pull request if there's not some problem I'm not aware of. Here is my relevant changes with the old stuff still inline but commented:
```
    @classmethod
    def parse(self, s, cur, _bsdec=_re.compile(r"\\(.)")):
        """Parse an hstore representation in a Python string.

        The hstore is represented as something like::

            "a"=>"1", "b"=>"2"

        with backslash-escaped strings.
        """
        if s is None:
            return None
        s = _bsdec.sub(r'\1', s)
        rv = {}
        start = 0
        for m in self._re_hstore.finditer(s):
            if m is None or m.start() != start:
                raise psycopg2.InterfaceError(
                    "error parsing hstore pair at char %d" % start)
            #k = _bsdec.sub(r'\1', m.group(1))
            k = m.group(1)
            v = m.group(2)
            #if v is not None:
            #    v = _bsdec.sub(r'\1', v)

            rv[k] = v
            start = m.end()

        if start < len(s):
            raise psycopg2.InterfaceError(
                "error parsing hstore: unparsed data after char %d" % start)

        return rv
```

**Comment by dvarrazzo** [comment]
Can you try running the test suite? It is quite extensive on hstore: if it passes then yours was a great idea ;)

If it is all fine please submit a pull request so the commit attribution will be yours. Thank you.

**Comment by mcclurem** [comment]
And thank goodness for your test suite! - my suggestion breaks the code and has shown me why it can't be changed.
