### ISSUE TITLE
implement __len__ on cursor for select statements

### ISSUE THREAD

**Issue by AndreasMadsen** [psycopg/psycopg2#335]
I'm using the cursor object as an iterator, but the consumer API requires `__len__` to be defined.

I could write another iterator class around the `cursor` object, but it would be much easier if the cursor object just defined __len__ to return `self.rowcount` for the meaningful cases and raise an `AttributeError` otherwise.

I can write the pull request myself if necessary. But I'm not very familiar with `postgresql` and unsure if there are other statements than `select` for which `self.rowcount` should be returned, or if there are any edge cases I haven't considered.

**Comment by dvarrazzo** [comment]
The cursor is an iterable object, and as such doesn't require a `__len__`. Your consumer wants another thing, not an iterable.

`rowcount` is not always an adequate substitute. Please write a cursor subclass implementing `__len__` and use it with `cursor_factory`. Don't send a pull request though: it would be rejected. We don't want to implement a list or container interface for cursors.
