### ISSUE TITLE
copy_from error when one column specified

### ISSUE THREAD

**Issue by manutor1** [psycopg/psycopg2#337]
Hi everyone,

When using copy_from instruction, it doesn't work if I use only one column as importing columns.
Here is the example : 
PYTHON : cur.copy_from(f_io, 'import_table', sep = ',', columns = 'fullxml' )
TRADUCED ON POSTGRE SERVER : COPY import_table(f,u,l,l,x,m,l) FROM stdin WITH DELIMITER AS ',' NULL AS '\N'

I haven't found any trick to avoid this problem and would have to run the instruction using copy_expert ...
Anyone found some other solution ?

**Comment by dvarrazzo** [comment]
"a trick"??? Columns must be a list of names, that's it.

    cur.copy_from(f_io, 'import_table', sep = ',', columns = ['fullxml'])

**Comment by manutor1** [comment]
Thank you.
I call it a "trick" this as the copy_from documentation (http://initd.org/psycopg/docs/cursor.html?highlight=copy_from#cursor.copy_from ) may let us think the <columns> argument is a tupple : 
cur.copy_from(f, 'test', columns=('num', 'data'))

Am I wrong ?

**Comment by dvarrazzo** [comment]
Yes you are: the docs say about the "columns" argument: "iterable with name of the columns to import". A list is. A tuple is. The string "fullxml" is an iterable containing 7 items, each one a character, as your output "import_table(f,u,l,l,x,m,l)" suggests.

**Comment by manutor1** [comment]
Thank you for this update. I didn't mention it in the first issue text but the command
cur.copy_from(f_io, 'import_table', sep = ',', columns = ('fullxml'))
does not work (column understood as f,u,l,l,x,m,l) ... but : 
cur.copy_from(f_io, 'import_table', sep = ',', columns = ['fullxml'])
works fine (column understood  fullxml)!

**Comment by dvarrazzo** [comment]
`('fullxml')` is not a tuple: it is a string in parenthesis. A tuple of one element in Python is `('fullxml',)`. It's the commas that make tuples, not the parenthesis.

**Comment by manutor1** [comment]
Perfect ! That was the part of tupple definition I missed.
Best regards,
