### ISSUE TITLE
Use PQsetSingleRowMode for iteration?

### ISSUE THREAD

**Issue by xmo-odoo** [psycopg/psycopg2#338]
I was looking at the [cursor iteration stuff](http://initd.org/psycopg/docs/cursor.html#cursor-iterable) and it notes that it uses the (configurable) `itersize` setting to buffer rows fetching when iterating[0].

In 9.2, libpq introduced [a single-row mode](http://www.postgresql.org/docs/current/static/libpq-single-row-mode.html) which seems to exist specifically to provide fast yet low-memory iteration on query results, and doesn't seem to be used in psycopg2 (grepping the source for both `PQsetSingleRowMode` and `PGRES_SINGLE_TUPLE` finds no match). That might be an interesting opt-in extension for postgres iteration (maybe connection-wise though the setting is actually query-wise, applying to the query just sent)

[0] for named cursors, it's not clear what is used to define anonymous cursor buffering

**Comment by dvarrazzo** [comment]
No, it's not used indeed. At a quick glance it doesn't seem it can support all the features needed to provide the full DBAPI interface or to maintain backward compatibility. One first example I have in mind is scrolling backwards, unless we keep a buffer of our own on the client side, which cancels the entire point of iterating single-row.

As for your note [0], `itersize` is not used by the client-side (unnamed) cursors because the entire dataset is transferred on the client in one go and there is no further server roundtrip.

I think the single-row mode is best used by specific programs that know how to iterate on a dataset: this is not psycopg use case, which is a generic library.

**Comment by xmo-odoo** [comment]
> At a quick glance it doesn't seem it can support all the features needed to provide the full DBAPI interface or to maintain backward compatibility. One first example I have in mind is scrolling backwards, unless we keep a buffer of our own on the client side, which cancels the entire point of iterating single-row.

I would assume most applications have no need to scroll backwards, they just iterate on the results, do whatever is needed with them then discard the whole thing, or they use fetchall (or collect everything in an array) to access arbitrary results.

But ignoring that, I'm suggesting the possibility for applications to opt into single-row mode (it's necessarily optional anyway given it's only supported on pg >= 9.2 and psycopg supports older pg versions), not that it be the default (as that would indeed break BC) (I don't know that it would break PEP 249 compatibility, it's not exactly clear about the interaction between iterating and using `fetch*` methods on the same cursor)

> I think the single-row mode is best used by specific programs

Sure hence the suggestion to make it optional as a cursor or connection setting (or even a special iterator on cursors, though that might be too late?), application would explicitly opt into that behaviour.

>  that know how to iterate on a dataset: this is not psycopg use case, which is a generic library.

Well psycopg is a generic postgres library, that's a generic postgres feature, since it requires a C call on the connection between `PQsendQuery` and `PQgetResult` and then handling a new `PGresult` status code, implementing that feature in the application without psycopg support would (so far as I can see) require forking or reimplementing much of psycopg.

**Comment by dvarrazzo** [comment]
>>  that know how to iterate on a dataset: this is not psycopg use case, which is a generic library.

> Well psycopg is a generic postgres library, that's a generic postgres feature, since it requires a C call on the connection between `PQsendQuery` and `PQgetResult` and then handling a new `PGresult` status code,

The aim of psycopg is not to wrap every single C call in the libpq but provide a DBAPI interface, you are having it backwards.

> implementing that feature in the application without psycopg support would (so far as I can see) require forking or reimplementing much of psycopg.

That's not a feature: it's an optimization, and not yet proven to be useful for psycopg use case. Currently psycopg fetches the entire recordset in a single gulp, so the entire `execute()/fetch*()` communication consts of a single roundtrip. If the datatset is too big to fit on the client people can use server-side cursors, where `execute()` makes a roundtrip and each `fetch*()` makes another one (iterating makes one per `itersize` records). What would be the number of roundtrip using single-row mode? Where is the memory occupied for large datasets? Would it be better than currently is? What should be the semantics in case of error as in the **caution** block in the libpq docs?

Of course you are totally free to implement the feature and propose a pull request: if it provide any benefit for the users I'd be happy to include it. I won't personally work on it.

**Comment by xmo-odoo** [comment]
> The aim of psycopg is not to wrap every single C call in the libpq but provide a DBAPI interface

It does provide a number of postgres-specific extensions over dbapi though, doesn't it?

> What would be the number of roundtrip using single-row mode? 

From what I understand reading the documentation, 1, the response being a stream of individual tuples rather than a big list of result tuples.

> What should be the semantics in case of error as in the caution block in the libpq docs?

Same as any other lazy iterator faulting I would think, it'd raise an exception at that point.

> Of course you are totally free to implement the feature and propose a pull request: if it provide any benefit for the users I'd be happy to include it. I won't personally work on it.

Got it.

**Comment by dvarrazzo** [comment]
>> The aim of psycopg is not to wrap every single C call in the libpq but provide a DBAPI interface

> It does provide a number of postgres-specific extensions over dbapi though, doesn't it?

Yes, because they are useful and the same things can't be done without, or with difficulties, or everybody would wrap them in a different way. You are only asking to wrap some more library calls that people may ask on request to be able to do exactly (hopefully) the same things following a different code path, not providing any new feature.

>> What would be the number of roundtrip using single-row mode? 

> From what I understand reading the documentation, 1, the response being a stream of individual tuples rather than a big list of result tuples.

So it is effectively a client-side cursor, all the dataset goes on the client. In what respect would it be better from the current implementation?

**Comment by xmo-odoo** [comment]
> You are only asking to wrap some more library calls that people may ask on request to be able to do exactly (hopefully) the same things following a different code path

I don't understand this sentence.

> not providing any new feature.

Fair enough.

> So it is effectively a client-side cursor, all the dataset goes on the client. In what respect would it be better from the current implementation?

It's the difference between a list and an iterator, so lower time to first tuple and little to no implicit buffering on either side, the server sends tuples down the connection as soon as it generates them (hence the possibility of errors arising mid-stream), the client consumes those same tuples as they get fetched (one question might be whether it's possible to just stop iterating and have postgres discard any further work)

**Comment by marco44** [comment]
Sorry to raise the dead here, I just wanted to point out one use case: when you can't use cursors because you're using pgbouncer in transaction mode. Don't know if this is still pertinent though.
