### ISSUE TITLE
Add __eq__ to extensions.AsIs

### ISSUE THREAD

**Issue by stub42** [psycopg/psycopg2#339]
Writing tests would be easier if extensions.AsIs defined a valid equality operator.

eg. with a MagicMock connection, the following always fails as two AsIs instances are never equal:

con.cursor().execute.assert_called_once_with('SELECT * FROM %s', (AsIs('aTable'),))

**Comment by dvarrazzo** [comment]
I prefer not to add the eq operator to AsIs because it is not useful for normal psycopg usage. Please spend two line more in your test and check that the returned class is AsIs and the contents are the same.

**Comment by stub42** [comment]
I find AsIs useful for including prequoted identifiers such as usernames in statements like 'ALTER USER', similarly table names and schema names in other statements. Its cleaner to include them with the other bound variables.

I'm fine if you don't want to add it though - I'm using a custom version of AsIs for now.
