### ISSUE TITLE
Wrapped types do not compare by value

### ISSUE THREAD

**Issue by ChloeTigre** [psycopg/psycopg2#342]
Hello,

This is quite unexpected.

from psycopg2.extras import Inet
a = Inet('10.0.0.1')
b = Inet('10.0.0.1')
assert(a==b) # False
b = a
assert(a==b) # True

It would be quite relevant to add an __eq__ method comparing the dicts.

**Comment by dvarrazzo** [comment]
You are right. OTOH I don't even know why that class exists. I don't think it adds anything to just using strings.

See #205: I don't really want to add features to a class that doesn't do anything useful.

**Comment by ChloeTigre** [comment]
So register_inet should be considered deprecated ?

**Comment by dvarrazzo** [comment]
Maybe we should, yes. I've just been ignoring that thing and only considered it a sort of adaptation example without any quality.

**Comment by dvarrazzo** [comment]
Also see #317 for a better choice in Inet adaptation.
