### ISSUE TITLE
`execute()` uses too much memory.

### ISSUE THREAD

**Issue by skorokithakis** [psycopg/psycopg2#345]
I connect to my database and do:

```
In [8]: cur.execute("select * from broker_storedfile")
```

That table has around 10m rows, and this execute call never returns, as it runs out of memory (uses about 7 GB) and the OOM killer kills it. Should the `execute()` call be taking up so much memory? What causes this?

**Comment by skorokithakis** [comment]
Actually, trying it again, it doesn't crash any more. It just uses the 7 GB, but the machine has enough memory to keep the process alive. Still, the question exists, why is this using so much memory?

**Comment by depaolim** [comment]
2015-09-01 15:55 GMT+02:00 Stavros Korokithakis <notifications@github.com>:

> Actually, trying it again, it doesn't crash any more. It just uses the 7
> GB, but the machine has enough memory to keep the process alive. Still, the
> question exists, why is this using so much memory?
>

"When a database query is executed, the Psycopg cursor
<http://initd.org/psycopg/docs/cursor.html#cursor> usually fetches all the
records returned by the backend, transferring them to the client process.
If the query returned an huge amount of data, a proportionally large amount
of memory will be allocated by the client.

If the dataset is too large to be practically handled on the client side,
it is possible to create a *server side* cursor."
http://initd.org/psycopg/docs/usage.html#server-side-cursors

bye,
Marco

**Comment by dvarrazzo** [comment]
Thank you Marco. Stavros, read the docs about server-side cursors.
