### ISSUE TITLE
PersistentConnectionPool broken on python3

### ISSUE THREAD

**Issue by munetic** [psycopg/psycopg2#348]
I'm not sure if this is bug in psycopg2, pip3, 2to3 or sowhere else, but it can be fixed in psycopg2.

PersistentConnectionPool uses module thread, which is in python2 renamed to _thread. 2to3 tries to fix that during installation by appending underscore, but fails to do it correctly. As result, we get exception 
NameError(name 'thread' is not defined)

It can be fixed by replacing thread.get_ident() method with threading.current_thread().ident, however, Thread.ident is introduced in python 2.6, we loose support for 2.5 with this solution.

**Comment by dvarrazzo** [comment]
FIxed, thank you for the report.

**Comment by dpasqualin** [comment]
I'm sorry but this fix doesn't seem to be on python3-psycopg package on debian jessie. Is there an estimate for when it's gonna be?
