### ISSUE TITLE
Support COPY BOTH (replication protocol) mode for logical decoding etc

### ISSUE THREAD

**Issue by ringerc** [psycopg/psycopg2#351]
Now that PostgreSQL's replication protocol has been extended to support [logical decoding](http://www.postgresql.org/docs/current/static/logicaldecoding-explanation.html) it makes sense to be able to consume the PostgreSQL [streaming replication protocol](http://www.postgresql.org/docs/current/static/protocol-replication.html) in clients other than `libpq`, so that apps written in other languages can consume change streams.

`psycopg2` already has much of what's required since it's a wrapper around `libpq` and already has at least some `COPY` support. The replication protocol is based on the `COPY` protocol, in a special "COPY BOTH" mode that's not accessible via the regular protocol.

It's already possible to make a replication protocol connection and send replication protocol messages like `CREATE_`REPLICATION_SLOT`. All you have to do is:

* Append ` replication=on` or (9.4+, logical replication mode) ` replication=database` to your connection string; and
* Set `conn.autocommit = False` to prevent `psycopg2` from sending `BEGIN`, which isn't legal on the walsender protocol.

However, psycopg2 chokes as soon as you run any command that enters `COPY BOTH` mode, because it doesn't recognise the PostgreSQL command result status `PGRES_COPY_BOTH` and treats it as an error, then (per #82) raises:

    DatabaseError: error with no message from the libpq

Even if it recognised copy both mode, the current API won't be especially useful because COPY BOTH mode remains active until one end or the other ends it - usually by closing the connection. There's no end to the copy operation. Using the result would require running a different thread to read from the file-like object, and that could run into GIL issues unless psycopg2 is very careful to release and acquire the GIL during the COPY.

I'm going to test out doing just that, but I think it'd make sense for psycopg2 to natively support COPY BOTH mode via an API where:

* The stream may be read from like a generator to fetch the contents of discrete `CopyData` messages via [`libpq`'s `PQgetCopyData`](http://www.postgresql.org/docs/current/static/libpq-copy.html) function, each returned as a byte string;

* The client application may also send `CopyData` messages via wrapped `PQputCopyData` calls, for cases where two-way messaging is accepted.

In future it'd ideally makes sense to expose ways to send primary keepalive messages and standby status update messages from the walsender protocol. Status updates are important when replicating from a slot to ensure the slot advances and old WAL is discarded.

Most of what's needed is already there. I suspect the COPY BOTH support should be exposed via an extension connection factory and cursor factory that return a connection preconfigured for replication and a cursor that has some extra functions for the walsender protocol messages, but the generator-style reading of COPY data should be added to the base cursor class as an alternative to `copy_expert`, since it'll be *really* useful for writing efficient COPY-handling client code for normal `COPY ... TO ...` as well.

**Comment by ringerc** [comment]
It looks like much of this has already been done as part of #322 which I somehow managed not to find before doing all this looking around.

**Comment by dvarrazzo** [comment]
Closing as COPY BOTH is now supported, as part of #322.
