### ISSUE TITLE
psycopg2 treats PGRES_COPY_BOTH as an error

### ISSUE THREAD

**Issue by ringerc** [psycopg/psycopg2#352]
psycopg2 treats the return code `PGRES_COPY_BOTH` as a `DatabaseError`, per #351:

    DatabaseError: error with no message from the libpq

It should probably instead raise `NotImplementedError`, or at least a `ProgammingError` with error message `psycopg2 does not support COPY_BOTH replication mode`

**Comment by dvarrazzo** [comment]
Hi Craig, thank you very much, and thank you for the thorough review of the streaming replication protocol branch.

I've included your change proposed in #353 but only for errors (as we have "error with no message from the libpq" in other cases, probably related to connection losses). With this changeset COPY_BOTH will raise `NotSupportedError` instead.

I have added a `repl_connect()` method for the unit test: you may want to use it in replication-related test cases.
