### ISSUE TITLE
Error installing psycopg2 even after installing the postgresql-devel package

### ISSUE THREAD

**Issue by d3prof3t** [psycopg/psycopg2#357]
Have a look at this:
https://gist.github.com/d3prof3t/81542e34f50d5c8e0929

**Comment by d3prof3t** [comment]
I am setting up a fedora 22 server and was installing the psycopg2 via pip in my virtualenv and I am still facing issues.
Any suggestions?

**Comment by dvarrazzo** [comment]
What part of

    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.

you don't understand?

Don't open this bug report again. This is not a bug.

**Comment by d3prof3t** [comment]
Okkay

**Comment by d3prof3t** [comment]
Okkay
