### ISSUE TITLE
Segfault when doing a repr(self) on a not-yet initialized connection object

### ISSUE THREAD

**Issue by a1exsh** [psycopg/psycopg2#361]
The following code segfaults on `connection_repr()`, because `self->dsn` is not set yet:

```py
class conn2(psycopg2.extensions.connection):
    def __init__(conn, *args, **kwargs):
        print(repr(conn))
        super(psycopg2.extensions.connection, conn).__init__(*args, **kwargs)
psycopg2.connect('', connection_factory=conn2)
```

Do we want to fix this?  Just add a check like `self->dsn ? self->dsn : "None"`?

**Comment by dvarrazzo** [comment]
Yes, although I wouldn't be surprised if we found similar bugs somewhere else.

**Comment by dvarrazzo** [comment]
Are you going to fix it? If you do could you please also update the NEWS file and cherry-pick it into the maint_2_6 branch? Thank you.

**Comment by a1exsh** [comment]
Will do.

**Comment by dvarrazzo** [comment]
<3

**Comment by a1exsh** [comment]
Hm, but it's a bit more complex than that, due to the quotes in format string.  I'd also try to see if other similar places could be worked around and if it really makes sense to do that vs. the added complexity.  That said, it won't happen until tomorrow.
