### ISSUE TITLE
Add way to adapt byte string into a TEXT field

### ISSUE THREAD

**Issue by zackw** [psycopg/psycopg2#365]
Suppose I'm doing bulk INSERTs or UPDATEs into a TEXT field, using psycopg2 with Python 3.  The values to insert come to my program in the form of UTF-8-coded byte strings, and I know by construction that the database encoding is UTF-8.  Right now, in order to use the normal `cur.execute(query, params)` construct, I have to decode the byte strings to Unicode strings ... and then psycopg2 has to encode them back to UTF-8 again, in order to construct the actual query passed to the database.

It would be more efficient if there were a way to tell cur.execute to adapt a byte string into a TEXT field.  By using this, the application would be promising that the encoding of the byte string matches the database encoding, so mogrify() would only have to take care of doubling single quotes.

Right now I am using this horrific kludge:

```
def quote_utf8_as_text(s):
    return b"'" + s.replace(b"'", b"''") + b"'"

def intern_blob(cur, table, column, hash, blob, is_jsonb):
    hash = cur.mogrify("%s", (hash,))
    cur.execute(b"SELECT id FROM " + table + b" WHERE hash = " + hash)
    rv = cur.fetchall()
    if rv:
        return rv[0][0]

    blob = quote_utf8_as_text(blob)
    if is_jsonb:
        blob += b"::jsonb"

    cur.execute(b"INSERT INTO " + table + b"(hash, " + column + b")"
                b" VALUES (" + hash + b"," + blob + b") RETURNING id")
    return cur.fetchone()[0]
```

and what I'd like to be able to write is something like

```
def intern_blob(cur, table, hash, blob, is_jsonb):
    cur.execute("SELECT id FROM " + table + "WHERE hash = %s", (hash,))
    rv = cur.fetchall()
    if rv: return rv[0][0]

    insert = ("INSERT INTO " + table + "(hash," + column + ")"
              " VALUES (%s, %s" + ("::jsonb" if is_jsonb else "") + ") RETURNING id")
    cur.execute(insert, (hash, psycopg2.extensions.ByteStringAsText(blob)))
    return cur.fetchone()[0]
```

That may look like only a *little* less manual paste-up of SQL, but it totally eliminates the case where I have to worry about proper quotation.

**Comment by dvarrazzo** [comment]
I think the best fix would be to drop the [check for Py3](https://github.com/psycopg/psycopg2/blob/a2b01cd/psycopg/adapter_qstring.c#L63) so that it would be possible to register the `QuotedString` adapter on `bytes` (the test should become `Bytes_Check`). Do you want to try and propose a pull request? If it works as expected we can sneak the patch into 2.6.2 because it's really a useless limitation of the adapter: more a bug than a new feature.

**Comment by dvarrazzo** [comment]
"can't quote non-string object (or missing encoding)"... ugh, we can definitely tell these two apart :)

**Comment by zackw** [comment]
I'm afraid I don't understand the code well enough to patch it myself.

**Comment by dvarrazzo** [comment]
Now it is possible to register `QuotedString` on the `bytes` type to allow quoting it without encoding/decoding.
