### ISSUE TITLE
Upload binary wheels (for windows) to pypi

### ISSUE THREAD

**Issue by nonZero** [psycopg/psycopg2#368]
Hi All!

psycopg2 is great!

I spend a lot of time teaching students about python and django, and many of my students use windows as their OS.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg supplies working windows binaries for psycopg - but installing them requires the user to:
1. Open a browser on this site,
2. Find the correct package manually on the site,
3. Download the package to the local computer manually,
4. Install the wheel file with `pip`.

Each of these four steps is prone to user errors (not knowing about the site above, selecting the wrong download - python version or architecture, downloading to a bad filename for example - wheel is very picky, etc.)

By uploading the wheel files to pypi, this whole process can be eliminated and psycopg2 can be installed in its binary form by using:

    pip install psycopg2

Since `pip` has become the major installation tool in the python ecosystem, and since binary wheels support was established, some other major packages already support this excellent workflow: [pandas](https://pypi.python.org/pypi/pandas/0.17.0/), [Pillow](https://pypi.python.org/pypi/Pillow/3.0.0), [matplotlib][https://pypi.python.org/pypi/matplotlib) to name a few.

I would thank you very much if you could consider uploading these binaries to pypi for the sake of windows users.

Thank you very much!

Udi

PS: https://pypi.python.org/pypi/matplotlib supplies exe files which are not compatible with pip, only with the obsolete tool `easy_install`, and is not updated to python 3.5.

**Comment by dvarrazzo** [comment]
@jerickso what do you think?

**Comment by jerickso** [comment]
Adding the wheel file creation to my build processes looks to be pretty straight forward.   What we would have to determine is how to get the whl files into PyPI.  I am not that familiar with PyPI so not sure if a second developer could be added to the PyPI record to upload files to the psycopg2 package, or if I inform @fogzot when I have new whl files to upload and have him import them into PyPI.

**Comment by dvarrazzo** [comment]
@jerickso [as far as I can see](https://pypi.python.org/pypi?:action=role_form&package_name=psycopg2) (replace the package name with some you have ownership of), PyPI only has Owner and Maintainer levels and it seems Maintainer can only change metadata, but [somewhere else](http://stackoverflow.com/questions/12857123/pypi-role-maintenance-owners-vs-maintainers) it seems it should be enough to upload a package. What is your username on PyPI? I can try to make you a Maintainer.

**Comment by jerickso** [comment]
My username on PyPI is: jerickso.

**Comment by dvarrazzo** [comment]
@jerickso I have added you as maintainer. Do you want to try if you can upload a wheel and if it works ok?

**Comment by jerickso** [comment]
It looks like I can successfully upload files as a maintainer.  Interestingly, I was not able to upload to the test server (testpypi.python.org), but we don't need that :).  I have been successful uploading a few versions, I'll work on the rest.

There is a minor setup.py file change that I'll submit into github today to support the wheel creation.

Also, I'll delay uploading python 3.5 until we have the minor changes needed for the new Visual Studio compiler in the release source code.

**Comment by dvarrazzo** [comment]
Stunning job, @jerickso, thank you very much.

I hope the build and upload process is scripted and doesn't take you too much to prepare the release?

**Comment by nonZero** [comment]
Thank you very much @dvarrazzo  and @jerickso ! Many many happy users will enjoy your efforts!

**Comment by jerickso** [comment]
Building and uploading the files should add very little to my process.  Of course, I say that now, we'll see how true that is in reality.

**Comment by leafstorm** [comment]
@jerickso Has the code needed to create Python 3.5 wheels been released yet? I'm currently using an unofficial wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg, but I'd prefer to use official wheels from PyPI.

**Comment by jerickso** [comment]
@leafstorm, it has not.  Let's ping @dvarrazzo to see what he is thinking for the next release.

**Comment by leafstorm** [comment]
Just installed a wheel of 2.6.2 from PyPI. Thanks!
