### ISSUE TITLE
psycopg2.extensions.connection.cursor no longer accepts cursor_factory argument.

### ISSUE THREAD

**Issue by csawyerYumaed** [psycopg/psycopg2#371]
In the 2.5 series, psycopg2.extensions.connection.cursor no longer accepts a cursor_factory argument.

    cursor = psycopg2.extensions.connection.cursor(self, cursor_factory=DBCursor)
TypeError: __init__() takes exactly 2 arguments (3 given)

I know the default cursor accepts cursor_factory now, but why did you take it away from psycopg2.extentions.connection.cursor() ?  This seems painful, for those of us that have a custom Connection object as well as a custom Cursor.

This breaks a lot of existing code - it hurts.  Especially when I have a unified code-base and am trying to slowly upgrade servers, instead of bulk-update ALL of them all at once, just to handle this change.

**Comment by dvarrazzo** [comment]
I'm sorry but I don't understand what sort of usage is yours: why and where are you calling an unbound method as it was a constructor?

It smells like you shoud have used `cursor = super(MyConnectionClass, self).cursor(cursor_factory=DBCursor)`. However I couldn't reproduce your error: please provide a more complete test to reproduce it.

**Comment by csawyerYumaed** [comment]
UGH. sorry I'm a MORON.  My problem was my DBCursor __init__() was not accepting the cursor_factory keyword argument.  **kwargs took care of my problem.  Sorry! :)

and yes, I should use super() and have updated the code to reflect that. :)
