### ISSUE TITLE
Unhelpful error message when inserting seemingly valid timestamps

### ISSUE THREAD

**Issue by matthewruttley** [psycopg/psycopg2#388]
With a table columns: (createtime, modifytime, some_string), trying to insert simple data like:

    INSERT INTO my_table
            VALUES (
                ('2016-01-05 16:37:13:123456', '2016-01-05 16:37:13:123456', 'some text'),
                ('2016-01-05 16:37:13:123456', '2016-01-05 16:37:13:123456', 'other text')
            );

Produces the somewhat unhelpful message:

    ProgrammingError: (psycopg2.ProgrammingError) column "createtime" is of type timestamp without time zone but expression is of type record
    LINE 4:             ('2016-01-05 16:29:45:123456', '2016-01-05 16:29:45:123456', '...
                        ^
    HINT:  You will need to rewrite or cast the expression.

I've tried using `to_timestamp()` (with or without quotes), other timestamp formats (e.g. with a T in the center) but nothing seems to work. Could this error message be made more descriptive? "Is of type record" doesn't really help. The string is a valid timestamp (I think), and appears to fit the error's description of "timestamp without time zone".

(Also if anyone can hint as to why my code is failing that would be amazing too :D)

Digging through stackoverflow for similar issues brings up people with very different problems, for example somebody who put in some incorrect brackets: https://stackoverflow.com/questions/8390653/postgres-syntax-error-with-insert-into-tablefoo-select-from-tablefoo and got `"ERROR:  column "routine_id" is of type integer but expression is of type record
HINT:  You will need to rewrite or cast the expression.". `

I'd love to help out here and maybe submit a pull request to improve this area, but can't find exactly where ProgrammingError is defined.

**Comment by mwalton21** [comment]
Try the following:


INSERT INTO my_table
        VALUES
            ('2016-01-05 16:37:13:123456', '2016-01-05
16:37:13:123456', 'some text'),
            ('2016-01-05 16:37:13:123456', '2016-01-05
16:37:13:123456', 'other text')
        ;

**Comment by matthewruttley** [comment]
Thanks! Ah so it actually was sort of the same error in that neither `SELECT` nor `VALUES` should enclose what follows in brackets.
