### ISSUE TITLE
psycopg2 problem install virtualenv (Fedora 23)

### ISSUE THREAD

**Issue by CARocha** [psycopg/psycopg2#390]
Hi, i try install psycopg2 version 2.6.1 in virtualenv inside Fedora 23
previus install all packages for the compilation liked that

postgresql-libs-9.4.5-1.fc23.x86_64
postgresql-contrib-9.4.5-1.fc23.x86_64
postgresql-9.4.5-1.fc23.x86_64
postgresql-server-9.4.5-1.fc23.x86_64
postgresql-devel-9.4.5-1.fc23.x86_64

any problem latest version of psycopg2 for postgresql version 9.4.x??
or is my problem my operation system Fedora 23 internal bugs?

inside virtualenv i try install:
(virtualenv)$ pip install psycopg2

this is the error, sorry for verbose is alot

Collecting psycopg2
  Using cached psycopg2-2.6.1.tar.gz
Building wheels for collected packages: psycopg2
  Running setup.py bdist_wheel for psycopg2
  Complete output from command /home/crocha/proyectos/django/simas/virtual/venvmapasfincas/bin/python -c "import setuptools;__file__='/tmp/pip-build-R66W1y/psycopg2/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpbCuJWepip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_json.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/psycopg1.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/_range.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/extensions.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/extras.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/pool.py -> build/lib.linux-x86_64-2.7/psycopg2
  copying lib/tz.py -> build/lib.linux-x86_64-2.7/psycopg2
  creating build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_bugX000.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_notify.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_connection.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_cursor.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_with.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/testutils.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_green.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_module.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_psycopg2_dbapi20.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_types_extras.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_copy.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/dbapi20_tpc.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_lobject.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_dates.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_cancel.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_transaction.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_types_basic.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_extras_dictcursor.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_quote.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/testconfig.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_async.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/test_bug_gc.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  copying tests/dbapi20.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/psycopg
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.6.1 (dt dec pq3 ext lo64)" -DPG_VERSION_HEX=0x090405 -DHAVE_LO64=1 -I/usr/include/python2.7 -I. -I/usr/include -I/usr/include/pgsql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No existe el fichero o el directorio
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2
  Running setup.py install for psycopg2
    Complete output from command /home/crocha/proyectos/django/simas/virtual/venvmapasfincas/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-R66W1y/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HbGcs4-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/crocha/proyectos/django/simas/virtual/venvmapasfincas/include/site/python2.7/psycopg2:
    running install
    running build
    running build_py
    running build_ext
    building 'psycopg2._psycopg' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.6.1 (dt dec pq3 ext lo64)" -DPG_VERSION_HEX=0x090405 -DHAVE_LO64=1 -I/usr/include/python2.7 -I. -I/usr/include -I/usr/include/pgsql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No existe el fichero o el directorio
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

Cheers

**Comment by dagnaldo** [comment]
at this line: "gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No existe el fichero o el directorio"

Have you tried to install rpm-build?

It works for me! 

Hasta!

**Comment by dvarrazzo** [comment]
You are missing build prerequisites.

**Comment by trishnaguha** [comment]
Even I am having the same issue continuously.
