### ISSUE TITLE
Can't connect with very long passwords

### ISSUE THREAD

**Issue by galileopy** [psycopg/psycopg2#392]
Seems that passwords longer than 100 characters do not work with psycopg2 while are still usable with psql.

My knowledge of postgres is limited, though a quick google search didn't reveal that this is a hard limit on postgres. And the fact that I can still connect with psql gives me a hint that this might be an issue with psycopg2.

Tried on Ubuntu 15.10 with Postgres 9.4.5, and psycopg 2.6.1

**Comment by dvarrazzo** [comment]
Works for me. Tested with a 160 chars long password.

```
In [4]: cnn = psycopg2.connect("host=localhost dbname=passwd password=123...890")
In [6]: cnn = psycopg2.connect(host="localhost", database="passwd", password="123...890")
```
