### ISSUE TITLE
psycopg2.pool.SimpleConnectionPool with very large timeout

### ISSUE THREAD

**Issue by matheusssilva** [psycopg/psycopg2#396]
I did a test, I turned off the server and I called the psycopg2.pool.SimpleConnectionPool method.
The exception OperationalError slow to appear.

Is there a way to change that?

**Comment by dvarrazzo** [comment]
This is a bug tracker: no-one reads this message, apart from the core developers.

I don't have an answer for your question; unless a handful of people does you will receive no answer.

Please post your question to the Mailing List, where more people can help you. StackOverflow could do too.

**Comment by matheusssilva** [comment]
But this is normal? This latency to throw the exception?

**Comment by tommyjcarpenter** [comment]
I am also trying to figure out how to get the simpleConnectionPool to throw an error much sooner (ideally at a specified timeout).

**Comment by tommyjcarpenter** [comment]
There is extremly poor documentation here: http://initd.org/psycopg/docs/pool.html (it doesnt tell you what kwargs are even used!)

However, from digging into the code, It appears from: https://github.com/psycopg/psycopg2/blob/master/lib/pool.py that kwargs is passed directly into connect:

```
_connect(self, key=None):
        """Create a new connection and assign it to 'key' if not None."""
        conn = psycopg2.connect(*self._args, **self._kwargs)
```

however I cannot seem to find a "timeout" keywork in the connect class either: http://initd.org/psycopg/docs/module.html

**Comment by dvarrazzo** [comment]
Yes, there is a `connect_timeout` connection parameter which is not handled by psycopg but by the libpq itself.

https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT-CONNECT-TIMEOUT
