### ISSUE TITLE
DELETE RETURNING with specified columns is not properly deserialized

### ISSUE THREAD

**Issue by mgyucht** [psycopg/psycopg2#406]
Suppose I have the following table in a database called `mydb`:

```
CREATE TABLE IF NOT EXISTS exercise_table (
  exercise VARCHAR(100) NOT NULL,
  reps INT NOT NULL,
);
```

and suppose this table has a row in it where `exercise` is `'pushups'` and `reps` is `10`. Then, when I run

```
conn = psycopg2.connect('mydb')
cursor = conn.cursor()
cursor.execute("DELETE FROM exercise_table RETURNING *")
cursor.fetchone()
```

the result is `("pushups", 10)`, as you would expect. However, if I do

```
conn = psycopg2.connect('mydb')
cursor = conn.cursor()
cursor.execute("DELETE FROM exercise_table RETURNING (exercises, reps)")
cursor.fetchone()
```

the result is `('(pushups, 10)',)`, a tuple whose first (and only) entry is a string which, when parsed, would be exactly what I'd expect to be returned, as opposed to a stringified version of it.

**Comment by fogzot** [comment]
This is expected: by putting the column names in parentheses you are returning a single, composite value. If you want to return multiple columns just avoid the parentheses:

    cursor.execute("DELETE FROM exercise_table RETURNING exercises, reps")
