### ISSUE TITLE
Document that libpq must be *available* at runtime

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#408]
People installs the libpq in whatever corner they fancy of their systems and then assume psycopg will find it. This could be reasonable, but no: it's too system dependent to rely on that so I don't want to go there.

Document in the install docs that the libpq must be *available*, i.e. the dynamic loader must be able to find the library in the environment where psycopg is used. How this is accomplished (copying libpq in the right directory, hacking `$LD_LIBRARY_PATH`) is outside psycopg scope.

See issues #378, #407.

**Comment by jerickso** [comment]
That libpq must be available isn't entirely true, as I link against the static libraries (Several years back I had support hell with the .DLL versions and switch to static libraries).  Also, there is a psycopg2 config option (static_libpq) to build against the static versions, but not sure how much that is used, or on what platforms it is supported.

For most situations, I agree that we need to note that the libpq shared library must be available/accessible (Maybe note in the following way: 'unless knowing built against the static version of libpq ...').

**Comment by dvarrazzo** [comment]
Yes. I should also review that building --static is still a thing under linux, because people build psycopg out of `/pat/to/some/funky/postgres/version/bin/pg_config` and then expect to work...
