### ISSUE TITLE
Assertion error in cursor_type.c:344

### ISSUE THREAD

**Issue by koniiiik** [psycopg/psycopg2#414]
I'm getting an assertion error when executing the following test case:
```python
import psycopg2
conn = psycopg2.connect("")
cursor = conn.cursor()
cursor.execute("SELECT %s, %s", (1, 2, 3))
```
As you can see, this happens when the number of parameters exceeds the number of placeholders. I discovered this while trying to run the Django test suite, and it was triggered by https://github.com/django/django/blob/97eb3356b2a7488c8d0ca0e47ef3e538852d44a2/tests/backends/tests.py#L441.

The assertion error is:
```
python: psycopg/cursor_type.c:344: _psyco_curs_merge_query_args: Assertion `((((((PyObject*)(str))->ob_type))->tp_flags & ((1UL << 27))) != 0)' failed.
```

The second case succeeds in that test (i.e. does not crash the interpreter, but raises an IndexError).

I'm experiencing this in Python 3.4.3, Postgres 9.5.1, all psycopg2 master. I wanted to bisect psycopg2, but as it turns out, it happens on 2_4_0, too, which from what I understand is the first version with Py3k support.

**Comment by dvarrazzo** [comment]
I get a normal IndexError. Are you trying with a debug build of Python?

**Comment by koniiiik** [comment]
On Sat, Mar 05, 2016 at 10:27:39AM -0800, Daniele Varrazzo wrote:
> I get a normal IndexError. Are you trying with a debug build of Python?

Not as far as I'm aware.

I just gave it a try with other versions of Python, and I get the same
error with Python 3.3.5, but not with 2.7.10 (there it raises a
TypeError).

**Comment by koniiiik** [comment]
Looks like it's specific to Gentoo builds of CPython, I've opened a ticket there, too: https://bugs.gentoo.org/show_bug.cgi?id=577182
