### ISSUE TITLE
New Error With Homebrew Postgres 9.5.1/Pyenv

### ISSUE THREAD

**Issue by BradRuderman** [psycopg/psycopg2#421]
Getting the following error:

```
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Symbol not found: _PyUnicodeUCS2_AsEncodedString
  Referenced from: /usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Expected in: flat namespace
 in /usr/local/opt/pyenv/versions/adwords/lib/python2.7/site-packages/psycopg2/_psycopg.so
```

I have pyenv, pyenv-virtualenv, and postgres all installed via home-brew on mac os x 10.11.4.

![1__python__python2_7__and_new_issue_ _psycopg_psycopg2](https://cloud.githubusercontent.com/assets/2366784/14336626/c8e57ce0-fc1a-11e5-820b-634edd1426a6.png)

In addition here is my homebrew list:

![1__bradruderman_brads-macbook-pro_____zsh_](https://cloud.githubusercontent.com/assets/2366784/14336646/01f20440-fc1b-11e5-9f6a-e4f7a87039e1.png)

**Comment by dvarrazzo** [comment]
It seems some mixup with python library: most likely you are compiling psycopg with one Python installation and dynamically linking with a different one. Nothing we can help with.

**Comment by BradRuderman** [comment]
@dvarrazzo I think its a packaging error with psycopg2. See here:

https://github.com/yyuu/pyenv/issues/425

And here:

https://github.com/psycopg/psycopg2/issues/230

Thanks!
