### ISSUE TITLE
cursor.execute automatically wraps params with single quotes

### ISSUE THREAD

**Issue by makered** [psycopg/psycopg2#423]
I realize this might be out of scope for psycopg2 but thought I would mention it in case someone else ran into this.

I am connecting to AWS Redshift (based on PostgreSQL 8.0.2) and noticed if I try to run:

```cursor.execute(query, params)```

params are wrapped by single quotes during interpolation which is by design. However, Redshift does not seem to like param quotes when running a query similar to:

```ALTER GROUP 'group_param' ADD USER 'user_param'```

but the following would be fine:

```ALTER GROUP group_param ADD USER user_param```

So in this case I am forced to use string interpolation directly on the query string, which I know is evil but in this context I am in full control of the source params.

Any thoughts?

Thanks

**Comment by dvarrazzo** [comment]
You are trying to pass identifiers to the query, for which the query parameters are not suitable. We are adding identifiers escaping to the next psycopg release: see #359.

**Comment by dideler** [comment]
It's not clear to me what the proposed solution is. Should we use `quote_ident` from `psycopg2.extensions`?

That requires a connection or cursor to be passed to it. For situations where queries are being prepared separately from the query executions (i.e. no access to the connection or cursor), how would we avoid the single quotes?

**Comment by dvarrazzo** [comment]
@dideler If you are preparing statements without interacting with the database you will have to use normal string manipulation. We have pretty advanced ways to create sql statements dynamically (e.g. see the [`psycopg2.sql`](http://initd.org/psycopg/docs/sql.html) module) but they all assume the use of a connection or a cursor to convert them to string.
