### ISSUE TITLE
COPY_FROM async

### ISSUE THREAD

**Issue by sfer033** [psycopg/psycopg2#428]
Hi,

From the documentation:

```
COPY commands are not supported either in asynchronous mode, but this will be probably implemented in a future release.
```

Any idea when we could expect such a feature? 

My use case: Using psycopg2 via a txpostgres `ConnectionPool` in Twisted; needing to do large numbers of inserts asynchronously.

**Comment by rad-pat** [comment]
Is this enhancement something we might expect in the near future? It has been quite some time since the original issue.

**Comment by dvarrazzo** [comment]
@rad-pat I do have some time for some [free-software development](https://www.varrazzo.com/software/) at the moment, but async copy is relatively low in the list: I had in mind to focus on a few other projects first.

If you have interest in that feature please consider [sponsoring the development](https://github.com/sponsors/dvarrazzo). Thank you very much!

**Comment by dvarrazzo** [comment]
Asynchronous copy is [implemented in psycopg3](https://www.psycopg.org/psycopg3/docs/usage.html#copy).

**Comment by dan-cbm** [comment]
here's a working link for the relevant psycopyg3 docs 

https://www.psycopg.org/psycopg3/docs/basic/copy.html#asynchronous-copy-support

**Comment by dan-cbm** [comment]
I'm trying with --insert only, new error is:

````bash
executing: 'INSERT INTO cms.calendars VALUES (933, 'Quebec Cap-and-Trade Workshop', '2023-12-05 19:30:00', '2023-12-05 20:30:00', false, 'https://www.environnement.gouv.qc.ca/changementsclimatiques/evaluation-parametres-fonctionnement-spede-en.htm', false, 'The MELCCFP will hold a webcast to receive comments from the public and the entities registered with the C&T System on the following topics: GHG storage;'


sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.PostgresSyntaxError'>: unterminated quoted string at or near "'The MELCCFP will hold a webcast to receive comments from the public and the entities registered with the C&T System on the following topics: GHG storage;"
[SQL: INSERT INTO cms.calendars VALUES (933, 'Quebec Cap-and-Trade Workshop', '2023-12-05 19:30:00', '2023-12-05 20:30:00', false, 'https://www.environnement.gouv.qc.ca/changementsclimatiques/evaluation-parametres-fonctionnement-spede-en.htm', false, 'The MELCCFP will hold a webcast to receive comments from the public and the entities registered with the C&T System on the following topics: GHG storage;]
(Background on this error at: https://sqlalche.me/e/20/f405)

````
