### ISSUE TITLE
Ambiguous behavior of the cursor as iterable

### ISSUE THREAD

**Issue by aniljava** [psycopg/psycopg2#433]
SUMMARY:
---------------

    for x in cursor:
        print x

throws `psycopg2.ProgrammingError: no results to fetch` whereas, fetchall() prints rows

    for x in cursor.fetchall():
        print x

If there were no results, should not `fetchall()` throw the same error or an empty list. 

------------------

For the following code i have:

    # ....
    def test(self):
        cursor = self.connection.cursor()
        SQL = "SELECT id, data FROM products WHERE data->>'folderid' = %s"
        cursor.execute(SQL, ['new'])
        for c in cursor:
            print c
    # ...

Above code throws: `psycopg2.ProgrammingError: no results to fetch`

But when the code is changed with `fetchall()` added, it works as expected:

    # ....
    def test(self):
        cursor = self.connection.cursor()
        SQL = "SELECT id, data FROM products WHERE data->>'folderid' = %s"
        cursor.execute(SQL, ['new'])
        for c in cursor.fetchall():
            print c
    # ...

When same code is tested in a new script without any other db operation or few inserts, before it, It works fine without a `fetchall()`

    connection = psycopg2.connect("user=postgres") 
    cursor = connection.cursor()
    SQL = "SELECT id, data FROM products WHERE data->>'folderid' = %s"
    cursor.execute(SQL, ['new'])
    for c in cursor:
        print c

I thought of having uncommitted rows (even though not the case) causing the a empty results, but if it were a case for any reason, should not the fetchall() throw the same error. 

I also tested with a fresh connection in first case as:

    ...
    self.connection = psycopg2.connect("user=postgres") 
    cursor = self.connection.cursor()
    ...

Same error `psycopg2.ProgrammingError: no results to fetch` is thrown. 

The operations before the above codes were `DELETE from products WHERE data->>'folderid' = '"new"'` followed by insertion of new rows. The insertions were committed with self.connection.commit() before the test() was called. Again, if it was the matter of uncommitted rows, the fetchall() returns the rows fine.

**Comment by aniljava** [comment]
Found, the same cursor was used inside loop, clearing internal state. the `fetchall()` i think created a separate reference to cursor or copied the values allowing the other execution on the cursor to carry on.

**Comment by dvarrazzo** [comment]
Yup. "no result to fetch" is returned not after a select returning no row, but after a statement returning no result, such as a CREATE TABLE, or a DELETE without RETURNING.
