### ISSUE TITLE
DELETE statements don't work when executed via named cursors on PostgreSQL

### ISSUE THREAD

**Issue by eduardo-matos** [psycopg/psycopg2#437]
```python
import psycopg2
conn = psycopg2.connect(database='', user='', password='', host='', port='')
cursor = conn.cursor('my_cursor')
cursor.execute('DELETE FROM my_table WHERE my_table.id = 1')
# ProgrammingError: syntax error at or near "DELETE"
# LINE 1: DECLARE "my_cursor" CURSOR WITHOUT HOLD FOR DELETE FROM my_table...
```

When executing the above code snippet we receive a syntax error.
According to PostgreSQL documentation, the `DECLARE` statement should be followed by a `SELECT` or `VALUES` command.

Maybe it's better not to send the `DECLARE` hunk of code to the database at all when executing commands different from `SELECT` or `VALUES` (depending on the database version).

**Comment by fogzot** [comment]
Catching that vedere execution requires client side parsing of the statement, not trivial. Right now, you try to do something illegal and you get back an exception: that seems fine to me (maybe not optimal, but fine).
