### ISSUE TITLE
psycopg2 wheels not available on Linux

### ISSUE THREAD

**Issue by ehashman** [psycopg/psycopg2#440]
When I attempted to install `psycopg2` in `tox` for a project I'm currently working on, installation failed with the error:

```
Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
```

I can go ahead and install these system dependencies on my dev box, but it would be really awesome if you distributed a [manylinux1 wheel](https://github.com/pypa/python-manylinux-demo) so I didn't have to do that. It appears you are already distributing wheels for Windows, so perhaps you can add support for Linux and OS X as well!

Let me know if there's any way I can help?

**Comment by aRkadeFR** [comment]
> Psycopg is not distributed in binary form on Linux: it is only distributed in source form. Packaging is not our responsibility.

https://github.com/psycopg/psycopg2/issues/425

**Comment by dvarrazzo** [comment]
@ehashman I eventually gave up and prepared some manylinux wheels to test:

    pip install -i https://testpypi.python.org/pypi psycopg2

can you please test them and let me know if they work ok? Thank you.
