### ISSUE TITLE
Migrate from CObject to capsule objects

### ISSUE THREAD

**Issue by benf-wspdigital** [psycopg/psycopg2#448]
The `python2 -3` option enables warnings for code that will cause problems for migrating to Python 3.

In the `psycopg2` code base (as of version 2.6.1) the following warning is emitted:

```
…/site-packages/psycopg2/__init__.py:50: DeprecationWarning: CObject type is not supported in 3.x. Please use capsule objects instead.
  from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
```

**Comment by dvarrazzo** [comment]
Will be considered for a version where Python 2.5 support is dropped.

**Comment by dvarrazzo** [comment]
Not an issue: the code is ifdeffed away in Python 3.
```c
    /* Create a CObject containing the API pointer array's address */
    /* If anybody asks for a PyCapsule we'll deal with it. */
#if PY_VERSION_HEX < 0x03020000
    c_api_object = PyCObject_FromVoidPtr((void *)PSYCOPG_API, NULL);
    if (c_api_object != NULL)
        PyModule_AddObject(module, "_C_API", c_api_object);
#endif
```

Nobody asked for a capsule yet (or proposed a merge request, `$GOD` forbid), so leaving it as it is.
