### ISSUE TITLE
pip error installing new version pg_config executable not found.

### ISSUE THREAD

**Issue by InbarRose** [psycopg/psycopg2#451]
When using this command to install:

`python -m pip install --upgrade --egg --ignore-installed psycopg2`

```
Collecting psycopg2
  Downloading psycopg2-2.6.2.tar.gz (376kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\psycopg2.egg-info
    writing pip-egg-info\psycopg2.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\psycopg2.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\psycopg2.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\psycopg2.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.
```

**Comment by dvarrazzo** [comment]
And do you have `pg_config` in your path?

**Comment by InbarRose** [comment]
I didn't need to have it before. (2.6.1) 
Have the requirements for this package changed?

**Comment by dvarrazzo** [comment]
Yes, you needed it before too.

There was some change in this package, yes: it uses setuptools in preference to distutils because a lot of features need it (see #370). If your problem comes from this change I'm interested to know.

pg_config has been a building requirement for years. Maybe the previous version was installed as precompiled binary from packages, or you had it before and was uninstalled (it's not a runtime requirement).

Closing this ticket as the evidence suggests that making pg_config available would fix the problem. If this is not the case and we need further investigation (setuptools makes me *very* nervous...) please let me know.

Thank you very much.

**Comment by InbarRose** [comment]
I don't think you understand. 

I use sterile environments (VM's that are reverted to the same snapshot each time)

And the same process occurs each time.

I didn't specify a version for the package, and now since a new package was released, the process began failing - so that means that something must have changed. when specifying the older package (2.6.1) everything works fine again.

Therefore, as far as i am concerned and form my perspective - there has been no change in the requirements of the package, and the new version doesn't install.

**Comment by dvarrazzo** [comment]
I agree, the package should build as before, and it does in my tests: the package installs with all the supported Python version (from 2.5 to 3.5).

I can ensure you that pg_config was required in 2.6.1 too.

I don't know what is the content of your VM: if you can help debugging it and explaining why the difference I'd be grateful.

**Comment by InbarRose** [comment]
Okay. very strange.

Under careful observation now - I note that when manually attempting this it fails because of missing pg_config when specifying 2.6.1 or when simply letting it take latest.

However - when unattended during the automated process, no such failure occurs when specifying 2.6.1, but when unspecified, or 2.6.2 is specified, it will fail when unattended because of missing pg_config.

What files/debug info can I provide to help with this?

is the pg_config package something that can be installed with pip? Shouldn't it be able to be added as part of the normal pip command to install psycopg2?

meanwhile here is output from unattended successful installation:

> Running setup.py install for psycopg2: started
> Running setup.py install for psycopg2: finished with status 'done'

as you can see, not much i can provide about why it works unattended but fails when doing it manually.

For now I am simply specifying the previous version (2.6.1) with my unattended scripts, and it's working fine. But I would like to be able to use the newer version. 

So, I will try to assist as much as I can.
