### ISSUE TITLE
import order with copy_expert

### ISSUE THREAD

**Issue by manutor1** [psycopg/psycopg2#452]
Hello,

I am encountering difficulties to import a CSV file : i can not get the same row order in the PostGre table than in the CSV file, using "copy_expert" with psycopg 2.6.1 on Windows
I am doing this :

```
fileObjC = open(somefile,'r')
cur = connexion.cursor()
cur.copy_expert(sql="COPY mass.sae_14_dico_vars FROM STDIN WITH CSV HEADER ENCODING 'LATIN1' DELIMITER AS ';'", file=fileObj, size=800000)
connexion.commit()
cur.close()
cur = connexion.cursor()
cur.execute("ALTER TABLE mass.sae_14_dico_vars ADD COLUMN id serial")
```

When selecting this table on postGre, it appears that the row which is number 1926 in CSV file appears a the 282nd row of postGre table.
Any explanation to this ?

Best regards,

**Comment by dvarrazzo** [comment]
There is no guarantee in the rows order in a relational database. But if you add your serial before the import your can use that for ordering.

Anyway psycopg is a database driver, not the database: this bug tracker is not the right place for this question.

**Comment by manutor1** [comment]
Thank you for your answer. I heard about the fact that there was no row order guarantee but a COPY FROM directly on PostGre server keeps the row order. That was a bit puzzlling.
What will you recommend as import method, preserving the original data integrity as much as possible ?
a. give an index in the file before COPY
b. give an index when reading file in python, before COPY
c. read line by line and insert into instead of copy ? ... so this will keep the order.
d. other method ?

Best regards,

**Comment by dvarrazzo** [comment]
Again, this is not the place to answer these questions. I suggest you to ask them to pgsql-novice or pgsql-general.

https://www.postgresql.org/list/

**Comment by manutor1** [comment]
"Again" ... well, I am quite surprised : i did not find any topic solving this so I though that suggesting a method taking advantage of psycopg power will be interesting for users of this module. As far as this question is not a full PostGreSQL issue... Is there any other place ?

Best Regards,
