### ISSUE TITLE
wrong content in columns with same (implicit) name

### ISSUE THREAD

**Issue by mzabuawala** [psycopg/psycopg2#454]
```
SELECT
field1 || ' - ' || field2,
field3,
field4 || '; ' || field5 from sometable;
```

This leads to three columns, the first and the last implicitly named "?column?".
Unfortunately all such columns end up with the contents of the last concatenated "?column?" - their proper contents are not displayed.

So for sometable with columns and contents like this:
```
field1	field2	field3	field4	field5
first	second	third	fourth	fifth
The query result is:
fourth; fifth	third	fourth; fifth
```

Used cursor in our code,
`cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
`

**Test Query:**
`select 1 as A , 2 as B, 3 as A, 4 as C;`

Can someone please suggest way to fix this issue?

**Comment by fogzot** [comment]
You have two different ways to fix this:

1) don't use a `DictCursor` and access the row by index; or
2) write a better query that gives unique names to columns.

**Comment by dvarrazzo** [comment]
Use:

```
SELECT
field1 || ' - ' || field2 AS somename,
field3,
field4 || '; ' || field5 AS anothername from sometable;
```

**Comment by mzabuawala** [comment]
Hi,

We are working on pgAdmin4 project and one of our user raise this issue, In pgAdmin4 user are free to enter any query in query editor.

What we are doing is something like below,
```

# Fetch the column info 
if cur.description is not None:
    colinfo = [desc for desc in cur.description]

# Any rows?
if cur.rowcount > 0:
   result = []
   try:
      for row in cur:
         result.append(dict(row))
   except psycopg2.ProgrammingError:
       result = None

# response for html table
return Response(
    response=json.dumps(colinfo, result),
    status=status,
    mimetype="text/json"
)
```

And use this response (column/row mapping) to create table at client side.

And we have used DictCursor in our code,
`cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
`

**Comment by dvarrazzo** [comment]
Hi @mzabuawala,

I'm sure you know enough about postgres to understand that the titles are made up by the database, not by the driver:

```
=# select 1, 2;
 ?column? | ?column? 
----------+----------
        1 |        2
(1 row)
```

You **cannot** represent this record with a dictionary. `DictCursor` is the wrong object for you. If you don't have control on the name of the column please write a subclass of `extension.cursor` making up your rule to associate columns titles to record values.

**Comment by mzabuawala** [comment]
Okay Daniele, Thank you.
