### ISSUE TITLE
Ability to insert a search_path into a connection string

### ISSUE THREAD

**Issue by murphyke** [psycopg/psycopg2#465]
It would be nice to have a function to patch a connection string with a search_path. It seems somewhat challenging to reliably parse a connection string into key value pairs (with values optionally delimited by quotes), then operate on the `options` value, either inserting or modifying an existing `-c search_path=FOO` clause.

What's the easiest way to do this using psycopg2?  Are there any lower level functions for parsing and reconstructing connection strings that could be of help?

**Comment by dvarrazzo** [comment]
In psycopg 2.7 there will be functionalities to parse and manipulate the dsn, see #321, so yes, there is some conninfo parsing support.

However parsing [the sub-language in `options`](https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNECT-OPTIONS) is out of what I really want psycopg to do: it seems too much of a libpq hack to me, and I don't want to further hack on top of it. OTOH if you are writing an application you have probably much more control of what your DSN `options` contains, before adding your `-c search_path`, e.g. it will always be empty or it will never contain another search path. So I'd say I'd leave merging `search_path` to the application needing it, without having to teach `connect()` the entire "Chapter 18" of postgres manual.

**Comment by murphyke** [comment]
Fair enough.
