### ISSUE TITLE
Python 3.5 Cl.exe

### ISSUE THREAD

**Issue by Sakat** [psycopg/psycopg2#466]
**Hi, i have this annoying problem :s**
Python 3.5 / Windows

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin>cd C:\wamp64\www\Bonjour\branches\dev\app

C:\wamp64\www\Bonjour\branches\dev\app>pip3 install -r requirements/dev.txt
Requirement already satisfied (use --upgrade to upgrade): setuptools==18.5 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): wheel==0.26.0 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.10.4 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Flask-SQLAlchemy==2.1 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy==1.0.9 in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from -r requirements\prod.txt (line 15))
Collecting psycopg2==2.6.1 (from -r requirements\prod.txt (line 16))
  Using cached psycopg2-2.6.1.tar.gz
Collecting Flask-Migrate==1.6.0 (from -r requirements\prod.txt (line 19))
Collecting Flask-WTF==0.12 (from -r requirements\prod.txt (line 22))
Collecting WTForms==2.0.2 (from -r requirements\prod.txt (line 23))
  Using cached WTForms-2.0.2-py2.py3-none-any.whl
Collecting gunicorn>=19.1.1 (from -r requirements\prod.txt (line 26))
  Using cached gunicorn-19.6.0-py2.py3-none-any.whl
Collecting Flask-Assets==0.11 (from -r requirements\prod.txt (line 29))
Collecting cssmin>=0.2.0 (from -r requirements\prod.txt (line 30))
Collecting jsmin>=2.0.11 (from -r requirements\prod.txt (line 31))
Collecting Flask-Login==0.3.2 (from -r requirements\prod.txt (line 34))
Collecting Flask-Bcrypt==0.7.1 (from -r requirements\prod.txt (line 35))
Collecting Flask-Cache>=0.13.1 (from -r requirements\prod.txt (line 38))
Collecting Flask-DebugToolbar==0.10.0 (from -r requirements\prod.txt (line 41))
Collecting pytest==2.8.2 (from -r requirements/dev.txt (line 5))
  Using cached pytest-2.8.2-py2.py3-none-any.whl
Collecting WebTest==2.0.20 (from -r requirements/dev.txt (line 6))
Collecting factory-boy==2.6.0 (from -r requirements/dev.txt (line 7))
  Using cached factory_boy-2.6.0-py2.py3-none-any.whl
Collecting Flask-Script==2.0.5 (from -r requirements/dev.txt (line 10))
Collecting flake8==2.5.0 (from -r requirements/dev.txt (line 13))
  Using cached flake8-2.5.0-py2.py3-none-any.whl
Collecting flake8-blind-except==0.1.0 (from -r requirements/dev.txt (line 14))
Collecting flake8-debugger==1.4.0 (from -r requirements/dev.txt (line 15))
Collecting flake8-docstrings==0.2.1.post1 (from -r requirements/dev.txt (line 16))
Collecting flake8-isort==0.2 (from -r requirements/dev.txt (line 17))
Collecting flake8-quotes==0.1.1 (from -r requirements/dev.txt (line 18))
Collecting isort==4.2.2 (from -r requirements/dev.txt (line 19))
  Using cached isort-4.2.2-py2.py3-none-any.whl
Collecting pep8-naming==0.3.3 (from -r requirements/dev.txt (line 20))
  Using cached pep8_naming-0.3.3-py2.py3-none-any.whl
Collecting alembic>=0.6 (from Flask-Migrate==1.6.0->-r requirements\prod.txt (line 19))
Collecting webassets>=0.11 (from Flask-Assets==0.11->-r requirements\prod.txt (line 29))
Collecting bcrypt (from Flask-Bcrypt==0.7.1->-r requirements\prod.txt (line 35))
  Using cached bcrypt-3.1.0-cp35-cp35m-win32.whl
Collecting Blinker (from Flask-DebugToolbar==0.10.0->-r requirements\prod.txt (line 41))
Collecting colorama; sys_platform == "win32" (from pytest==2.8.2->-r requirements/dev.txt (line 5))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest==2.8.2->-r requirements/dev.txt (line 5))
  Using cached py-1.4.31-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\joe\appdata\local\programs\python\python35-32\lib\site-packages (from WebTest==2.0.20->-r requirements/dev.txt (line 6))
Collecting beautifulsoup4 (from WebTest==2.0.20->-r requirements/dev.txt (line 6))
  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
Collecting WebOb>=1.2 (from WebTest==2.0.20->-r requirements/dev.txt (line 6))
  Using cached WebOb-1.6.1-py2.py3-none-any.whl
Collecting waitress>=0.8.5 (from WebTest==2.0.20->-r requirements/dev.txt (line 6))
  Using cached waitress-0.9.0-py2.py3-none-any.whl
Collecting fake-factory>=0.5.0 (from factory-boy==2.6.0->-r requirements/dev.txt (line 7))
  Using cached fake_factory-0.6.0-py2.py3-none-any.whl
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8==2.5.0->-r requirements/dev.txt (line 13))
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting mccabe<0.4,>=0.2.1 (from flake8==2.5.0->-r requirements/dev.txt (line 13))
  Using cached mccabe-0.3.1-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8==2.5.0->-r requirements/dev.txt (line 13))
  Using cached pyflakes-1.0.0-py2.py3-none-any.whl
Collecting pep257 (from flake8-docstrings==0.2.1.post1->-r requirements/dev.txt (line 16))
  Using cached pep257-0.7.0-py2.py3-none-any.whl
Collecting python-editor>=0.3 (from alembic>=0.6->Flask-Migrate==1.6.0->-r requirements\prod.txt (line 19))
Collecting Mako (from alembic>=0.6->Flask-Migrate==1.6.0->-r requirements\prod.txt (line 19))
Collecting cffi>=1.1 (from bcrypt->Flask-Bcrypt==0.7.1->-r requirements\prod.txt (line 35))
  Using cached cffi-1.7.0-cp35-none-win32.whl
Collecting python-dateutil>=2.4 (from fake-factory>=0.5.0->factory-boy==2.6.0->-r requirements/dev.txt (line 7))
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1->bcrypt->Flask-Bcrypt==0.7.1->-r requirements\prod.txt (line 35))
Building wheels for collected packages: psycopg2
  Running setup.py bdist_wheel for psycopg2 ... error
  Complete output from command c:\users\joe\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\joe\\AppData\\Local\\Temp\\pip-build-lfbutyq2\\psycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\joe\AppData\Local\Temp\tmpe3ti9fbfpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.5
  creating build\lib.win32-3.5\psycopg2
  copying lib\errorcodes.py -> build\lib.win32-3.5\psycopg2
  copying lib\extensions.py -> build\lib.win32-3.5\psycopg2
  copying lib\extras.py -> build\lib.win32-3.5\psycopg2
  copying lib\pool.py -> build\lib.win32-3.5\psycopg2
  copying lib\psycopg1.py -> build\lib.win32-3.5\psycopg2
  copying lib\tz.py -> build\lib.win32-3.5\psycopg2
  copying lib\_json.py -> build\lib.win32-3.5\psycopg2
  copying lib\_range.py -> build\lib.win32-3.5\psycopg2
  copying lib\__init__.py -> build\lib.win32-3.5\psycopg2
  creating build\lib.win32-3.5\psycopg2\tests
  copying tests\dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\dbapi20_tpc.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\testconfig.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\testutils.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_async.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_bugX000.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_bug_gc.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_cancel.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_connection.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_copy.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_cursor.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_dates.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_extras_dictcursor.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_green.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_lobject.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_module.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_notify.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_psycopg2_dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_quote.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_transaction.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_types_basic.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_types_extras.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\test_with.py -> build\lib.win32-3.5\psycopg2\tests
  copying tests\__init__.py -> build\lib.win32-3.5\psycopg2\tests
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build\temp.win32-3.5
  creating build\temp.win32-3.5\Release
  creating build\temp.win32-3.5\Release\psycopg
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSYCOPG_DEFAULT_PYDATETIME=1 "-DPSYCOPG_VERSION=\"2.6.1 (dt dec pq3 ext)\"" -DPG_VERSION_HEX=0x090504 -Ic:\users\joe\appdata\local\programs\python\python35-32\include -Ic:\users\joe\appdata\local\programs\python\python35-32\include -I. -IC:/PROGRA~1/PostgreSQL/9.5/include -IC:/PROGRA~1/PostgreSQL/9.5/include/server /Tcpsycopg\psycopgmodule.c /Fobuild\temp.win32-3.5\Release\psycopg\psycopgmodule.obj
  psycopgmodule.c
  c:\users\joe\appdata\local\programs\python\python35-32\include\pyconfig.h(68): fatal error C1083: Impossible d'ouvrir le fichier include : 'io.h' : No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2, Flask-Script, python-editor, Mako, alembic, Flask-Migrate, WTForms, Flask-WTF, gunicorn, webassets, Flask-Assets, cssmin, jsmin, Flask-Login, pycparser, cffi, bcrypt, Flask-Bcrypt, Flask-Cache, Blinker, Flask-DebugToolbar, colorama, py, pytest, beautifulsoup4, WebOb, waitress, WebTest, python-dateutil, fake-factory, factory-boy, pep8, mccabe, pyflakes, flake8, flake8-blind-except, flake8-debugger, pep257, flake8-docstrings, isort, flake8-isort, flake8-quotes, pep8-naming
  Found existing installation: psycopg2 2.6.2
    Uninstalling psycopg2-2.6.2:
      Successfully uninstalled psycopg2-2.6.2
  Running setup.py install for psycopg2 ... error
    Complete output from command c:\users\joe\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\joe\\AppData\\Local\\Temp\\pip-build-lfbutyq2\\psycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\joe\AppData\Local\Temp\pip-6a9d48kj-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\psycopg2
    copying lib\errorcodes.py -> build\lib.win32-3.5\psycopg2
    copying lib\extensions.py -> build\lib.win32-3.5\psycopg2
    copying lib\extras.py -> build\lib.win32-3.5\psycopg2
    copying lib\pool.py -> build\lib.win32-3.5\psycopg2
    copying lib\psycopg1.py -> build\lib.win32-3.5\psycopg2
    copying lib\tz.py -> build\lib.win32-3.5\psycopg2
    copying lib\_json.py -> build\lib.win32-3.5\psycopg2
    copying lib\_range.py -> build\lib.win32-3.5\psycopg2
    copying lib\__init__.py -> build\lib.win32-3.5\psycopg2
    creating build\lib.win32-3.5\psycopg2\tests
    copying tests\dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\dbapi20_tpc.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\testconfig.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\testutils.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_async.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_bugX000.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_bug_gc.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_cancel.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_connection.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_copy.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_cursor.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_dates.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_extras_dictcursor.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_green.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_lobject.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_module.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_notify.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_psycopg2_dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_quote.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_transaction.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_types_basic.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_types_extras.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\test_with.py -> build\lib.win32-3.5\psycopg2\tests
    copying tests\__init__.py -> build\lib.win32-3.5\psycopg2\tests
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build\temp.win32-3.5
    creating build\temp.win32-3.5\Release
    creating build\temp.win32-3.5\Release\psycopg
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPSYCOPG_DEFAULT_PYDATETIME=1 "-DPSYCOPG_VERSION=\"2.6.1 (dt dec pq3 ext)\"" -DPG_VERSION_HEX=0x090504 -Ic:\users\joe\appdata\local\programs\python\python35-32\include -Ic:\users\joe\appdata\local\programs\python\python35-32\include -I. -IC:/PROGRA~1/PostgreSQL/9.5/include -IC:/PROGRA~1/PostgreSQL/9.5/include/server /Tcpsycopg\psycopgmodule.c /Fobuild\temp.win32-3.5\Release\psycopg\psycopgmodule.obj
    psycopgmodule.c
    c:\users\joe\appdata\local\programs\python\python35-32\include\pyconfig.h(68): fatal error C1083: Impossible d'ouvrir le fichier include : 'io.h' : No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of psycopg2
Command "c:\users\joe\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\joe\\AppData\\Local\\Temp\\pip-build-lfbutyq2\\psycopg2\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\joe\AppData\Local\Temp\pip-6a9d48kj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\joe\AppData\Local\Temp\pip-build-lfbutyq2\psycopg2\`

Thx guys.

**Comment by dvarrazzo** [comment]
Python 3.5 on Windows is only supported from psycopg 2.6.2 (bug #380), for which you would find the wheel package on PyPI (https://pypi.python.org/pypi?:action=display&name=psycopg2&version=2.6.2).
