### ISSUE TITLE
Hanging with psycopg2.extras.wait_select when timeout expected

### ISSUE THREAD

**Issue by darikg** [psycopg/psycopg2#468]
Running the following:

```
import psycopg2
import psycopg2.extras
import psycopg2.extensions as ext
ext.set_wait_callback(psycopg2.extras.wait_select)
psycopg2.connect(host='localhost');
```

Hangs indefinitely and can't be killed on windows when postgresql isn't running. If I comment out the `set_wait_callback`, I correctly get an `OperationalError: timeout expired`, as expected.

**Comment by dvarrazzo** [comment]
Can it be interrupted if you add a timeout in the `select()` call?

**Comment by darikg** [comment]
Yup, that fixes it. My bad for not looking into the actual definition of `psycopg2.extras.wait_select`. Thanks!

**Comment by dvarrazzo** [comment]
Well, it's probably worth to add a timeout for us too in `wait_select`. Thank you for testing.

**Comment by dvarrazzo** [comment]
Behaviour on linux seems saner: the select can be interrupted with ctrl-c. We can't write this function in a generic way, or we should handle a short timeout and loop. If the problem is only on windows I'll wait for some window user to provide a patch, whenever it will happen (holding my breath...)
