### ISSUE TITLE
Can't get fetchone() after INSERT INTO with RETURNING *

### ISSUE THREAD

**Issue by b5y** [psycopg/psycopg2#469]
Hi there,

I am using ```psycopg2``` in flask and have some problem with getting id of last added data.

This is [example](http://stackoverflow.com/questions/5247685/python-postgres-psycopg2-getting-id-of-row-just-inserted) on how use ```fetchone``` to solve my problem. But, what is interesting more, sometimes ```fetchone``` works well and sometimes does not (i.e. it returns None).

Is it a bug or there must be another ways to implement my problem?

I am using psql (PostgreSQL) 9.5.4, python 2.7.12, psycopg2==2.6.2.

Best regards,
b5y

**Comment by b5y** [comment]
Moreover, I have tried in psql my query and it works well.

**Comment by fogzot** [comment]
If you use "RETURNING ..." and then fetchone()[0] on the same cursor it should work.
Can you provide an example (database dump and python code) that exposes the error?

**Comment by b5y** [comment]
The sample of how I am using fetchone() is [here](https://github.com/b5y/ticket-system/blob/master/app.py#L79).

**Comment by dvarrazzo** [comment]
Hi @b5y, I've seen you closed the ticket: was it an error on your side?

**Comment by b5y** [comment]
Hi @dvarrazzo, yes, it was my error. Thank you for response!
