### ISSUE TITLE
copy_from() is rising problem when separator is comma and comma is in string field

### ISSUE THREAD

**Issue by ultimatecoder** [psycopg/psycopg2#470]
Using  copy_from() function with below argument, it raises **DataError**.

```
cursor.copy_from(
    file=location_file,
    table='quote_location',
    columns=('name', 'country', 'source', 'type'),
    sep=',',
    null=''
)
``` 

```
psycopg2.DataError: extra data after last expected column
CONTEXT:  COPY quote_location, line 3092: "3249,"Al-Dhabbaya transmitter, Tower North",ae,geo,other,0101000020E610000097FF907EFB3A384016359886E..."
```

**Reason is comma(,) in name "Al-Dhabbaya transmitter, Tower North". While the csv file is working properly without any error with other csv readers.**

**Comment by dvarrazzo** [comment]
If you have a comma in your values you cannot use the comma as a separator. Use a different character, as a tab. Or use CSV and use copy expert to tell so, and quote the values.

This is not a psycopg matter: psycopg just forwards the data to postgres. Please refer to the [copy documentation](https://www.postgresql.org/docs/current/static/sql-copy.html) and provide postgres valid data.

**Comment by ultimatecoder** [comment]
@dvarrazzo Thanks for your replay. If you can observe the value is already quoted when there is comma in that. I believe it should work when value is quoted and comma is there inside it. The same data works fine while dealing with `COPY` utility of postgresql but in psycopg2 it is creating error.

You referenced CSV and copy expert. Will it be possible to give any reference on this? I am unable to identify exactly which utilities are you talking about.

**Comment by fogzot** [comment]
PostgreSQL COPY doesn't work like that. You *have* to tell it that the file uses quotes or to interpret the file as CSV (CSV format is more that just "comma separated values"). See https://www.postgresql.org/docs/current/static/sql-copy.html and use `copy_expert`.

**Comment by dvarrazzo** [comment]
@ultimatecoder you should use [cursor.copy_expert()](http://initd.org/psycopg/docs/cursor.html#cursor.copy_expert) and use any feature Postgres offers, e.g. (untested):

```python
cursor.copy_expert("copy quote_location from stdin (format csv)", location_file)
```

**Comment by ultimatecoder** [comment]
@dvarrazzo @fogzot  Okay, Thanks for replay and suggesting copy_export().

I believe `copy_from()` is wrapper on `COPY` functionality of postgresql. If it is then there should be separate argument for specifying file type as a comma separated value or text just like described in the documentation [here](https://www.postgresql.org/docs/current/static/sql-copy.html)

**Comment by dvarrazzo** [comment]
@ultimatecoder, Postgres developers continuously add new features to `COPY`: `copy_from` and `copy_to` were maybe complete at the time when they were introduced, some 15 years ago, but with more features added every year it doesn't make sense try to duplicate all of them into a different parameter (Alan Perlis said *If you have a procedure with ten parameters, you probably missed some*). 

It's not dissimilar from normal SQL: `execute()` doesn't know every Postgres SQL feature and doesn't try to wrap them into objects or parameters: it allows sending a command as a string, letting the developer and the database interacting using all the features and without getting in the way, the only responsibility being marshalling Python objects into a format the database knows. IMO `copy_from` and `copy_to` could be dropped, leaving only `copy_expert` there (maybe renamed as `copy()`). But we are sentimental and don't get rid of methods which has been around probably longer than our girlfriends. `copy_from()` was actually at dinner with me yesterday, and I ensured him we won't fire him, no, just he won't have more parameters added. ;)

**Comment by sulphide0** [comment]
we can't use copy_expert if we are not superuser.

**Comment by kemin711** [comment]
I am having the same issue.  the straight copy works with "quoted,comma,works" a string field with comma inside.  The \COPY ... with (format 'csv', delimiter ',', quote '"')  In the past I have also written parsers to work with quoted comma.  It is only a few extra lines of code and should not be easy (this is in C++); in python it should be even simpler.  Asking the user to user alternative is not as good as adding more functionality to the implementation.

**Comment by kemin711** [comment]
cur.copy_expert("COPY test TO STDOUT WITH CSV HEADER", sys.stdout) the example given is not very clear.  If I have a table testcopy and a file tmpfile.txt how should I proceed?  cur.copy_expert("copy testcopy from tmpfile.txt with (format 'csv', delimiter ',', header True, quote '"')", 'tmpfile')  Is this redundant?

**Comment by kemin711** [comment]
For anyone who is suffering from this, I just wrote a few extra lines of code. 
You need to 
import csv
     def comma2tab(inputfile):
         """ will discard the header line """
         outfile=inputfile + ".tab"
         ouf=open(outfile, 'w')
         with open(inputfile, 'r') as csvf:
             next(csvf) # discard header
             csvin = csv.reader(csvf, delimiter=',')
             for row in csvin:
                 ouf.write("\t".join(row))
         ouf.close()
         return outfile

**Comment by dvarrazzo** [comment]
@kemin711 this is a bug tracker, you are using it as a rubber duck. You have added, changed, removed comments which are just your toying with the library.

If you have observations or questions write the mailing list.

Locking the issue because I've had enough email about new comments just to see they were rewritten or discarded and this is not even a bug.
