### ISSUE TITLE
Can't create a table with a json column

### ISSUE THREAD

**Issue by ethanphunter** [psycopg/psycopg2#476]
I am trying to create a table from a python script with a similar query to this:

`create table MyTable(name text, personal_info json, age int)` 

And I am executing the query with `cursor.execute(query)` where `cursor` is set up similarly to how it is [shown in the documentation](http://initd.org/psycopg/docs/usage.html). 

The error I'm getting is `psycopg2.ProgrammingError: type "json" does not exist`

I've been working on this for a while and can't find any resources on this. I'm using psycopg2 version 2.6.2 and python 2. Any help with this would be greatly appreciated.

**Comment by fogzot** [comment]
It seems that your version of PostgreSQL doesn't support the `json` type. Which version are you using?

**Comment by dvarrazzo** [comment]
You are surely using an old PostgreSQL version. This is not a psycopg error.

**Comment by ethanphunter** [comment]
That appears to maybe the answer. My test environment is different than my developing environment and I didn't realize that travis ci used an old version of postgres by default. Thank you for the help!
