### ISSUE TITLE
Please update PIP with new extensions

### ISSUE THREAD

**Issue by solidsnack** [psycopg/psycopg2#480]
The version of `extensions.py` in recent PIP releases is ~2 years old:

https://github.com/psycopg/psycopg2/blob/1690fbace1bf498abd5a4c4f68bfaab609bc3587/lib/extensions.py

It is missing `quote_ident` and other essential conveniences. Will these features find their way onto PIP soon?

**Comment by dvarrazzo** [comment]
I'm working to wrap up the version 2.7.

**Comment by solidsnack** [comment]
:thumbsup:
