### ISSUE TITLE
LoggingConnection fails with "can't concat bytes to str" error in Python 3

### ISSUE THREAD

**Issue by VladV** [psycopg/psycopg2#483]
I initialize LoggingConnection as following: `connection.initialize(open('sql.log', a))`.
When executing a query, the logging fails here, since `msg` is `bytes`:

```
    def _logtofile(self, msg, curs):
        msg = self.filter(msg, curs)
        if msg: self._logobj.write(msg + _os.linesep)
```

Here `query` is `str`, but `self.query` is `bytes`:

```
    def execute(self, query, vars=None):
        try:
            return super(LoggingCursor, self).execute(query, vars)
        finally:
            self.connection.log(self.query, self)
```

**Comment by dvarrazzo** [comment]
mmm, yes, I guess that cursor was meant more as an example than as something serious to work with. However it's in the lib so we'll have to maintain it. Thank you for the report.

I guess that's Python 3.x, right?

**Comment by VladV** [comment]
Sure, Python 3.5 that is.

It's obviously easy to fix the cursor. However, there probably are some inconsistencies in the code that result in `query` being bytes or string in different places under Python 3. I'm not familiar with the library code enough to suggest whether and how in should be fixed.

**Comment by dvarrazzo** [comment]
Query is always a binary, encoded in the connection encoding. The most important parts of the adapter are well tested and the string types tracked correctly. This object hasn't received as much love as others.
