### ISSUE TITLE
SSL error: called a function you should not call

### ISSUE THREAD

**Issue by ljean** [psycopg/psycopg2#485]
I have a Python3.5/Django 1.10 application running with Postgres 9.5.2 database and psycopg2 2.6.2.

This app is served over SSL

It works fine most of time. Sometimes, I have a `(SSL error: called a function you should not call)` exception while trying to query the database.

It is difficult for me to understand the root cause but some people pointed a possible problem in the way psycopg2 initializes the connections to the database. http://stackoverflow.com/q/40278044/117092

What do you think about it?

**Comment by dvarrazzo** [comment]
It seems a libpq bug to me. Psycopg doesn't use openssl directly.

**Comment by ljean** [comment]
Ok thanks. 

It seems that this can be reproduced anytime by settings the `sslmode=require` option of the Django DB. https://www.postgresql.org/docs/9.1/static/libpq-ssl.html

I guess that there are some OpenSSL issue when using SSL for serving the app and for the database.

**Comment by dvarrazzo** [comment]
Can you report the thing to postgres devs? You would probably need the output of pg_config to report what libpq version you are using.

If there is something to be done on psycopg side please let us know. Thank you very much.

**Comment by ljean** [comment]
Ok. First, I need to check with my host provider if everything is ok. Thanks for your help.
