### ISSUE TITLE
Deprecation Warning on PersistentConnectionPool?

### ISSUE THREAD

**Issue by kjmph** [psycopg/psycopg2#486]
Hello,

We are having warnings pop up just recently on a feature we are using extensively in Psycopg2. Here is the warning:

```
/usr/local/lib/python2.7/site-packages/psycopg2/pool.py:198: DeprecationWarning: deprecated: use ZPsycopgDA.pool implementation
  DeprecationWarning)
```

However, looking at the commit history, this code has been unchanged for a very long time (4 years). It almost looks like this warning was inserted recently, and history was rewrote, as the blame doesn't even show this line until a recent merge.

In what way do I deal with this warning? There is very little documentation on ZPsycopgDA. It would be very nice to continue using PersistentConnectionPool. Any clarification here?

**Comment by dvarrazzo** [comment]
The ZPsycopgDA adapter has been separated into a package of its own which contains its own pool implementation: https://github.com/psycopg/ZPsycopgDA

The state of the package is untested and unmaintained: no psycopg maintainer has any Zope expertise. If you would like to contribute documentation, tests, code you are very welcome.
