### ISSUE TITLE
Reusing a connection across processes

### ISSUE THREAD

**Issue by pkch** [psycopg/psycopg2#487]
According to [`psycopg2` docs](http://initd.org/psycopg/docs/usage.html#thread-and-process-safety):

> `libpq` connections [shouldn’t be used by a forked processes](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT), so when using a module such as `multiprocessing` or a forking web deploy method such as FastCGI make sure to create the connections _after_ the fork.

Following [the link](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNECT) from that document leads to:

> On Unix, forking a process with open `libpq` connections can lead to unpredictable results because the parent and child processes share the same sockets and operating system resources. For this reason, such usage is not recommended, though doing an exec from the child process to load a new executable is safe.

But [it seems](http://stackoverflow.com/questions/6014055/how-is-socket-connection-being-handled-in-a-forked-process) there's no inherent problem with forking processes with open sockets. So what's the reason for `psycopg2`'s warning against forking when connections are open?

The reason for my question is that I saw a (presumably successful) [multiprocessing approach](http://stackoverflow.com/a/7556042/336527) that opened a connection right before forking.

Perhaps it is safe to fork open connections under some restrictions (e.g., only one process actually ever uses the connection, etc.)? It would be nice to clarify the docs one way or the other.

(I posted the same question on [SO](http://stackoverflow.com/questions/40482555/sharing-psycopg2-libpq-connections-across-processes))

**Comment by dvarrazzo** [comment]
If it works for libpq it works for psycopg.
