### ISSUE TITLE
Deprecate connect()'s async keyword as it'll become a keyword in Python 3.7

### ISSUE THREAD

**Issue by timgraham** [psycopg/psycopg2#495]
`psycopg2.connect()` takes a `async` keyword but this will be prohibited in Python 3.7.
```
psycopg2/__init__.py:164: DeprecationWarning: 'async' and 'await' will become
reserved keywords in Python 3.7
```
Idea: rename `async=False` to `async_=False` (or whatever) and pop `'async'` from `kwargs` and raise a warning about it.

**Comment by dvarrazzo** [comment]
So fun :(

**Comment by dvarrazzo** [comment]
Added `async_` as an alias to the `psycopg2.connect()` function, `connection.__init__()`, and the `connection.async` attribute.
