### ISSUE TITLE
Is it possible to use postgres NOTIFY,LISTEN in windows using psycopg2?

### ISSUE THREAD

**Issue by tzahij** [psycopg/psycopg2#497]
I have tried all combinations with\without select and poll - did not help me.
Thanks,
Tzahi Jakubovitz

**Comment by dvarrazzo** [comment]
I guess it is, but there is not a hope to help you if you don't show what you have done.

This is a bug tracker and not the place to ask this question: nobody using windows would read it here. Please ask the mailing list.
