### ISSUE TITLE
psycopg2 fails to compile under GCC 6.3.1

### ISSUE THREAD

**Issue by piotr-szpetkowski** [psycopg/psycopg2#500]
Hi.
Today I've been trying to setup new virtual environment and to my surprise I couldn't install psycopg2 with pip, because of the following error during compilation process:

> psycopg/psycopgmodule.c: In function ‘psyco_register_type’:
> psycopg/psycopgmodule.c:176:1: internal compiler error: Segmentation fault

There isn't much I can tell about what might be wrong in code, however here are versions of software I use:
- Python 3.6
- GCC 6.3.1 (as mentioned)
- pip 9.0.1

I've temporarily downgraded GCC to 6.2.1 and seems like it solved the problem.

Oh, and I've also tried to install from git - received the same error.

**Comment by dvarrazzo** [comment]
It seems pretty much a compiler bug, not a psycopg bug to me?

Feel free to shotgun-debug it, changing random things inside that function until it works. If your result is reasonable I would apply the patch.

**Comment by piotr-szpetkowski** [comment]
It seems that `cryptography` dependency also fails to compile under GCC 6.3.1 therefore it definitely is something wrong with the compiler.

At the moment I have simply decided to use clang instead of gcc in case of failing pypi packages:
```
env CC=clang pip install psycopg2
```

However it is not really a solution, in spare time I'll try to drill further into the issue.

**Comment by dvarrazzo** [comment]
Closing as not our bug.
