### ISSUE TITLE
Error while executing COPY statement with Large Dataset on AWS Redshift

### ISSUE THREAD

**Issue by sdeshpande** [psycopg/psycopg2#501]
Hello Guys,

I am running into an issue while using "psycopg2" to load data from S3 to Redshift.
If the Data Set is small (few millions of rows) the operation completes without any error. 
But in case of large data set (billions of rows) the python program produces following error.

"psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request."

On Redshift database I see the command completed successfully but I am concerned about the correctness of Data. 
Can someone please tell me if there needs to be any specific parameter I need to add to my connection string ?
con=psycopg2.connect(dbname= ' ', host=' ', port= ' ', user= ' ', password= ' ')

Regards,
Saurabh

**Comment by dvarrazzo** [comment]
One of the two, redshift or s3, closed the connection I guess. I don't know which one. You should ask them if they need extra parameters to keep the connection alive.

**Comment by sdeshpande** [comment]
Thank you. Can you tell me how to provide extra parameter in the connection string in case aws provides it to me?

**Comment by dvarrazzo** [comment]
Extra keyword arguments on `connect()` are forwarded to the libpq. The supported parameters are documented [here](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS). You may even use [conn.fileno()](http://initd.org/psycopg/docs/connection.html#connection.fileno) to pass the file descriptor of the open connection to OS system calls to manipulate the connection tcp parameters if you know what to do.

**Comment by sdeshpande** [comment]
Thank you.
