### ISSUE TITLE
New in 2.7 execute_values method

### ISSUE THREAD

**Issue by ClodoaldoPinto** [psycopg/psycopg2#502]
Is it relevant to have a `mogrify_values` method for the new in 2.7 `execute_values`? Or else how to know what is being sent to the server other than inspecting logs? Will it throw an exception in case the length of the sequences (or any of them) is different from the number of columns? There is no example in the docs about the template parameter.

**Comment by dvarrazzo** [comment]
Hi, thank you for your feedback. I don't think we should add `mogrify_*` function for the new functions added. The function may send more than one query, so it's not even clear what to return. You may see that the implementation is rather simple: if you have necessity of logging I think it's better to implement your own variant of it and log where you need.

The function will throw some random exception if the parameters list is inconsistent: this is sort of obvious and is also the behaviour of `executemany()`. Hopefully the resulting error message would explain what went wrong.

I've improved [the functions docs](http://initd.org/psycopg/docs/extras.html#fast-execution-helpers), including a better description of *template*.

**Comment by hollowgalaxy** [comment]
@dvarrazzo  I don't see who `execute_values` sends multiple queries. If `execute_values` is indeed only one query, then `mogrify_values` makes sense.
