### ISSUE TITLE
Connection with wrong port does not fail

### ISSUE THREAD

**Issue by latusaki** [psycopg/psycopg2#508]
Connecting to a DB expecting connection on port 5433 instead of 5432. Trying to connect without providing the port did not produce any error.
Inserting data appeared to work (returned values included id and auto-increment fields) but the values were not stored in the database. Should there be an exception, or something similar singling the wrong port ? version 2.6.2

**Comment by dvarrazzo** [comment]
You are probably connecting to a database you didn't have to know. Use `sudo netstat -ntpl | grep 5433` on the server to see what is talking to you. There is no way psycopg returns data or an incrementing id on a port with nothing attached :)

**Comment by latusaki** [comment]
You are right, I was too upset to think of this. There was a DB copy on the default port. 😱
