### ISSUE TITLE
NameError in Python

### ISSUE THREAD

**Issue by jbylund** [psycopg/psycopg2#509]
I'm getting the following traceback from a script I'm running.  Unfortunately I can't reproduce every time, seems to fail (with this error) about 75% of the time.  My arguments to execute are query:
```
SELECT level1 AS level1, COALESCE(SUM(iva), 0) AS iva, COALESCE(SUM(l), 0) AS l FROM frackles.bylevel1 WHERE level0top = %(level0top)s AND %(start)s <= date AND date <= %(end)s GROUP BY level1
```
and kwargs of
```
{
"start": "2017-02-14",
"end": "2017-02-14",
"level0top": "FORBES2"
}
```

The traceback:
```
Traceback (most recent call last):
  File "datasource.py", line 215, in <module>
    main()
  File "datasource.py", line 211, in main
    print frackles.get_data(level0top='*****', date=yesterday, columns=['level1', 'iva', 'l'])
  File "datasource.py", line 180, in get_data
    curs.execute(compiled_query, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/extras.py", line 228, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.InternalError: Error in python: NameError
DETAIL:  name 'conn' is not defined
```

Edit: 
```
In [2]: psycopg2.__version__
Out[2]: '2.6.2 (dt dec pq3 ext lo64)'
```

**Comment by jbylund** [comment]
Sorry, this one way my fault.

**Comment by dvarrazzo** [comment]
I'm curious about how you did it...

**Comment by jbylund** [comment]
I guess the psycopg2.InternalError could be a little confusing, but there's a multicorn fdw (python) running on the server I'm connecting to that's throwing an error and I was just misinterpreting it and looking in the wrong place.  And now I'm going to go hang my head in shame and fix my code.

**Comment by dvarrazzo** [comment]
Ha ha, no it's totally confusing :D it's a python/postgres/python sandwich....
