### ISSUE TITLE
Django and beta naming

### ISSUE THREAD

**Issue by aklaver** [psycopg/psycopg2#510]
Tried to test psycopg2==2.7b2 with Django 1.8 and ran into problem:

```
django.core.exceptions.ImproperlyConfigured: psycopg2_version 2.4.5 or newer is required; you have 2.7b2 (dt dec pq3 ext lo64)

Django uses the below to test for psycopg2 version:

def psycopg2_version():
    version = psycopg2.__version__.split(' ', 1)[0]
    return tuple(int(v) for v in version.split('.') if v.isdigit())

PSYCOPG2_VERSION = psycopg2_version()

if PSYCOPG2_VERSION < (2, 4, 5):
    raise ImproperlyConfigured("psycopg2_version 2.4.5 or newer is required; you have %s" % psycopg2.__version__)

So:
In [1]: import psycopg2

In [2]: def psycopg2_version():
   ...:     version = psycopg2.__version__.split(' ', 1)[0]
   ...:     return tuple(int(v) for v in version.split('.') if v.isdigit())
   ...: 

In [3]: psycopg2.__version__
Out[3]: '2.7b2 (dt dec pq3 ext lo64)'

In [4]: psycopg2_version()
Out[4]: (2,)


def psycopg2_version_mod():
    version = ver.split(' ', 1)[0]
    return tuple(int(v) for v in version.split('.') if v.isdigit())

In [9]: ver = '2.7.0b2'

In [10]: psycopg2_version_mod()
Out[10]: (2, 7)
```

Would it be possible to go to a three part versioning? Maybe not for this release as it is so close to stable, but maybe for future releases.

**Comment by dvarrazzo** [comment]
Hi Adrian,

I appreciate your tests on django, thank you very much.

Psycopg follows [pep 440](https://www.python.org/dev/peps/pep-0440/) for its version numbering. The algorithm to break the version that Django uses doesn't account for that. The solution of using three numbers for our version is not a correct one: version `2.4.9b1` would be parsed as (2, 4) and wouldn't pass the test.

At least I see if we release 2.7 it will work no problem, without it needing to be 2.7.0. I'll submit them a merge request.

Thank you for the report.

**Comment by dvarrazzo** [comment]
Already being addressed in https://github.com/django/django/pull/8068

**Comment by aklaver** [comment]
Oops, turns out I created the issue on the wrong project. It is being addressed so all is good.
