### ISSUE TITLE
[2.7b2] conn.isolation_level is `None` on new connection

### ISSUE THREAD

**Issue by doktorstick** [psycopg/psycopg2#513]
From the docs:

_Changed in version 2.7: the default value for isolation_level is ISOLATION_LEVEL_DEFAULT; previously the property would have queried the server and returned the real value applied. To know this value you can run a query such as show transaction_isolation. Usually the default value is READ COMMITTED, but this may be changed in the server configuration._

Demonstrating the bug(?):

```python
>>> import psycopg2
>>> psycopg2.__version__
'2.7b2 (dt dec pq3 ext lo64)'
>>> conn = psycopg2.connect (db.POLDB)
>>> conn.closed
0
>>> conn.isolation_level
>>>
```

**Comment by dvarrazzo** [comment]
Worksforme:

```python
>>> psycopg2.extensions.ISOLATION_LEVEL_DEFAULT is None
True
```

what is the problem?

**Comment by doktorstick** [comment]
Whoops, there isn't one. I mistakenly assumed the define was a non-`None` value.

**Comment by dvarrazzo** [comment]
Originally that was the case, but things started not making much sense with `ISOLATION_LEVEL_DEFAULT = 5`; `None` ended up being a better value.
