### ISSUE TITLE
`connect` with user/password = None fails in 2.7

### ISSUE THREAD

**Issue by pfhayes** [psycopg/psycopg2#517]
In the latest release (2.7), calling `connect` with user/password = None fails. In versions < 2.6.2 this would succeed

```
>>> from psycopg2 import connect
>>> connect(host='localhost', port=5432, database='basedb', user=None, password=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrick/.virtualenvs/sigopt/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "None" does not exist
```

Is this new expected behaviour? If so, should 2.7 be a new major release (3.0) to indicate backwards-incompatible changes?

**Comment by dvarrazzo** [comment]
It wasn't expected, no. However the fact that None was interpreted as unspecified seems an undocumented side effect to me. I think we can fix it and drop the None kwargs, but it seems to me your use of `connect()` is a bit stretched.

**Comment by pfhayes** [comment]
Hm, okay. I am happy to fix this on my end but this does seem to me to be a pretty natural way to specify no user/password. I suspect that 2.7 will break other code in the wild as well

**Comment by pfhayes** [comment]
Thanks @dvarrazzo !

**Comment by dvarrazzo** [comment]
You are right: although undocumented it is quite idiomatic, so I'm inclined to fix it anyway.

**Comment by reece** [comment]
Confirming that fix resolved the issue for me (#524, biocommons/hgvs#398). Thanks!

**Comment by samjewell** [comment]
>  dvarrazzo closed this in 44d8edf on 2 Mar 2017

Hi @dvarrazzo 
I can see you've said this is fixed in the release notes for 2.7.1
But I'm using `psycopg2-binary          2.8.6`, and I'm still seeing 
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/samjewell/anaconda3/envs/bridgeu-python/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "None" does not exist
```

Any thoughts? Is there any way this fix could have escaped the binary? Thanks so much.

**Comment by dvarrazzo** [comment]
@samjewell no, if that bug was still a thing there would be the internet screaming at my door now.

```
In [2]: import psycopg2                                                                                              

In [3]: cnn = psycopg2.connect(user=None)                                                                            

In [4]: cnn.dsn                                                                                                      
Out[4]: ''

In [5]: psycopg2.__version__                                                                                         
Out[5]: '2.8.6 (dt dec pq3 ext lo64)'
```

You either have a string containing `"None"` or the wrong version of psycopg2. I bet the first.

**Comment by samjewell** [comment]
> You either have a string containing `"None"` or the wrong version of psycopg2. I bet the first.

Oh wow, yes I'm sure you are right. Thank you so much fro your reply, and so quickly too. I'm very grateful for your help. I'm a bit stronger at Ruby than Python, but if there's anything I can do to return the favour let me know. 🙏
