### ISSUE TITLE
create ssl connection to postgre fail.

### ISSUE THREAD

**Issue by baoyonglei** [psycopg/psycopg2#525]
With psycopg2 of version 2.2.5 and sqlalchemy 1.0.11,  when create connection to postgre server,  exception occurs randomly with low possibility(once some hours).  Exception like this:
    "[resource.py:131 resource] (client error): (psycopg2.OperationalError) SSL connection has been closed unexpectedly."
      
I have looked into postgre server,  and found there is no abnormal logs at all.   
What reason will cause this exception?

**Comment by baoyonglei** [comment]
Add exception stack:

./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource     return dialect.connect(*cargs, **cparams)
./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource     return self.dbapi.connect(*cargs, **cparams)
./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource   File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource     conn = _connect(dsn, connection_factory=connection_factory, async=async)
./neutron-server.log.200.38.gz:2017-02-22 23:48:25.979 92487 ERROR neutron.api.v2.resource
./neutron-server.log.200.38.gz:2017-02-22T23:48:25.990+08:00 localhost neutron-server ERROR [pid:92487] [MainThread][tid:880639664] [req-4ca58766-64e4-49d9-a416-ea41c13fe41f] [resource.py:131 resource] (client error): (psycopg2.OperationalError) SSL connection has been closed unexpectedly

**Comment by dvarrazzo** [comment]
I have no idea what is causing your problems, I assume some networking problem, but the client has no part in it.
