### ISSUE TITLE
connection.dsn shows password for uri format dsn

### ISSUE THREAD

**Issue by yamagoya** [psycopg/psycopg2#528]
The connection.dsn string occludes the password when connection is made with a dsn but not when a connection is made with a URI:

    >>> dbconn=connect ('dbname=dev user=yama password=secret')
    >>> dbconn.dsn
    'dbname=dev user=yama password=xxxxxx'
    >>> dbconn=connect ('postgres://yama:secret@localhost/dev')
    >>> dbconn.dsn
    'postgres://yama:secret@localhost/dev'

Shouldn't it also be occluded in the URI case?

**Comment by dvarrazzo** [comment]
I guess so
