### ISSUE TITLE
execute_batch, execute_values "not defined"

### ISSUE THREAD

**Issue by oneroyalace** [psycopg/psycopg2#530]
Python: 3.5.1
Postgres: 9.5

I saw that 2.7 included a few updates that make large insertions a bit easier. Unfortunately, I haven't been able to get them to work. I updated psycopg2 through pip, but when running

`execute_batch(cur, sqlComment, dicList)`
I get told
 `NameError: name 'execute_batch' is not defined`

Probably not relevant, but I have sqlComment defined as 
`sqlComment = '''INSERT INTO comment(id, body, created_utc, gilded, score, controversiality) VALUES (%(id)s, %(body)s, %(created_utc)s, %(gilded)s, %(score)s, %(controversiality)s)'''`

and dicList is a tuple of dictionaries (I've also tried with a list of values, etc.)

Same thing happens when running execute_values with proper inputs

**Comment by dvarrazzo** [comment]
Have you, ehm, imported it?

```python
from psycopg2.extras import execute_batch
```

**Comment by oneroyalace** [comment]
... Can I not answer that but leave a discreet thank you?
