### ISSUE TITLE
copy_from ? features/issue/error

### ISSUE THREAD

**Issue by apiszcz** [psycopg/psycopg2#531]
1 the CSV HEADER options do not appear to be available and are in the psql capability.

2 I have a field wktdata that is enclosed in double quotes, however it seems that those are not being used to delimit the field, and 'may be causing the error below.

```
(Pdb) cur.copy_from(istream, 'data', sep=',', columns=('locid', 'epoch', 'attr', 'wktdata'))
*** psycopg2.DataError: extra data after last expected column
CONTEXT:  COPY data, line 2: "2,1,ATTRIBUTE02,"LINESTRING (1 1, 2 2, 3 3)""
```

FROM psql
```
sdb=# \copy data(locid, epoch, attr, wktdata) FROM 'sample01.csv' DELIMITERS ',' CSV HEADER;
COPY 3

```

**Comment by dvarrazzo** [comment]
You should use [copy_expert](http://initd.org/psycopg/docs/cursor.html#cursor.copy_expert) with parameters compatible. E.g. (untested):

```python
cur.copy_expert(
    "copy data (locid, epoch, attr, wktdata) from stdin delimiters ',' csv header",
    istream)
```
