### ISSUE TITLE
A lot of 'hstore'-related queries executed

### ISSUE THREAD

**Issue by failedguidedog** [psycopg/psycopg2#535]
Hi,
we're running a Django app using psycopg2 as a Postgres connector.
While analyzing Postgres logs to try and debug some performance issues I've noticed this query gets run a lot:

`SELECT t.oid, typarray FROM pg_type t JOIN pg_namespace ns ON typnamespace = ns.oid WHERE typname = 'hstore';`

I'm seeing this at the rate of 8% of all queries (200k out of 2.5M queries), which amounts to quite some processing time.

I've traced this to the [lib/extras.py](https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L885) file, but can't really figure out why this would be needed. The thing is, we don't use hstore fields anywhere in our app.

Is there a way I could disable this?

**Comment by dvarrazzo** [comment]
Hi,

that query is generated by your application or by Django calling [register_hstore()](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.register_hstore). As per docs:

> The connection or cursor passed to the function will be used to query the database and look for the OID of the hstore type (which may be different across databases). If querying is not desirable (e.g. with asynchronous connections) you may specify it in the oid parameter, which can be found using a query such as SELECT 'hstore'::regtype::oid. Analogously you can obtain a value for array_oid using a query such as SELECT 'hstore[]'::regtype::oid.

So my suggestion would be to reduce the call to once per connection, calling `get_oid()` yourself, caching the result and passing the oids to `register_hstore()` using the specific parameters.

**Comment by failedguidedog** [comment]
@dvarrazzo Thank you for your suggestion. I will see if there's anything that can be done on Django side.

**Comment by exslim** [comment]
We have the same issue. Is this somehow related to changes in 2.7 version? We haven't seen this in 2.6.x versions of psycopg

**Comment by exslim** [comment]
@failedguidedog - how did you manage to solve this? I'm thinking of override signal connection in AppConfig for django.contrib.postgresql app (where register_hstore_handler gets called). Or simply enable persistent connections with enabling CONN_MAX_AGE
