### ISSUE TITLE
Wrong defaults for socket dir in 2.7

### ISSUE THREAD

**Issue by eshkinkot** [psycopg/psycopg2#538]
By default postgres use /tmp for unix socket:
```src/include/pg_config_manual.h:#define DEFAULT_PGSOCKET_DIR  "/tmp"```

Debian maintainers change it to "/var/run/postgresql" so in Debian by default postgres socket is /var/run/postgresql/.s.PGSQL.5432

psycopg2 2.7 from PyPI is supplied now with internal libpq:
```psycopg2/.libs/libpq-9c51d239.so.5.9```
and this libpq version is looks like from Debian
```
$ strings psycopg2/.libs/libpq-9c51d239.so.5.9 | grep /var/run
/var/run/postgresql
```
All of this is break connections by default, for example in Slackware:
```
In [1]: import psycopg2 as pg
In [2]: conn = pg.connect('')
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-2-fe5f4e182f27> in <module>()
----> 1 conn = pg.connect('')

.../psycopg2/__init__.pyc in connect(dsn, connection_factory, cursor_factory, **kwargs)
    128 
    129     dsn = _ext.make_dsn(dsn, **kwargs)
--> 130     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    131     if cursor_factory is not None:
    132         conn.cursor_factory = cursor_factory

OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

I must explicitly set connection string now for all of my scripts, like:
```python
conn = pg.connect('host=/tmp')
```

That is not funny :-)

**Comment by eshkinkot** [comment]
Aha! ```pip install --no-binary psycopg2 psycopg2``` fix problem for me. Feel free to close this issue, sorry for the noice :-)

**Comment by eshkinkot** [comment]
May be mention this somethere in documentation?

**Comment by dvarrazzo** [comment]
No problem. It's probably worth mentioning that the wheel package follow the debian/redhat convention of storing the sockets in `/run`. As you discovered, if a different default is needed you will have to use your own libpq by compiling psycopg from source.
