### ISSUE TITLE
On windows it always depends on vc9 runtime

### ISSUE THREAD

**Issue by thierryba** [psycopg/psycopg2#541]
I'm building python with vc2015 as well as psycopg but the setup.py script make it use a vc9 manifest unconditionally.
That makes it that even if it doesn't really need that runtime, the psycopg module cannot be loaded if you don't have the vc2008 redistributables.

**Comment by dvarrazzo** [comment]
If you propose a fix we can use we can integrate it. If you are building python your own custom way you should customise psycopg too I guess.

**Comment by thierryba** [comment]
I'm just building python 3.5+. That builds by default with vc 2015. My own fix is to mot use the manifest but I'm not sure that is a good idea... or is it?

**Comment by dvarrazzo** [comment]
Maybe @jerickso knows...

**Comment by jerickso** [comment]
From what I vaguely remember, the purpose of the manifest is for when python is used in an embedded type situation (such as apache/mod_wsgi), where python.exe is not the main executable.  In these situations, the master program might be using different versions of the MSVC runtime libraries.

If you are not using psycopg in an embedded environment, the manifest is not required.

The true fix for the distribution is to have the proper manifests for each version.  I'll put that on my task list to fix.

**Comment by dvarrazzo** [comment]
I guess we should try and match [what we build with](https://github.com/psycopg/psycopg2/blob/master/.appveyor.yml#L17-L19):

        # Py 2.7 = VS Ver. 9.0  (VS 2008)
        # Py 3.3, 3.4 = VS Ver. 10.0 (VS 2010)
        # Py 3.5, 3.6 = VS Ver. 14.0 (VS 2015)

@thierryba can you please provide a patch? Thank you

**Comment by dvarrazzo** [comment]
Any news about this issue?

**Comment by jerickso** [comment]
Hmm, I'll see if I have time over the next two days to tackle this.

-jason

**Comment by dvarrazzo** [comment]
Hello @thierryba, could you please verify if the fix proposed in #566 solves your problem? Thank you very much.

**Comment by dvarrazzo** [comment]
No news from the op. Assuming the issue fixed.
