### ISSUE TITLE
Misssing logging for executemany()

### ISSUE THREAD

**Issue by xflr6** [psycopg/psycopg2#546]
Using `psycopg2.extras.LoggingConnection` all possible methods of execution seem to be logged except for the one with `executemany()`:

```python
import logging

import psycopg2
from psycopg2.extras import execute_batch, execute_values

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger('psycopg2')

class LoggingConnection(psycopg2.extras.LoggingConnection):

    def __init__(self, *args, **kwargs):
        super(LoggingConnection, self).__init__(*args, **kwargs)
        self.initialize(logger)

conn = psycopg2.connect('postgresql://postgres@',
                        connection_factory=LoggingConnection)
cur = conn.cursor()

cur.execute('CREATE TEMPORARY TABLE spam (id INTEGER)')

cur.execute('INSERT INTO spam (id) VALUES (%s)', (1,))

cur.execute('INSERT INTO spam (id) VALUES (%s), (%s)', (1, 2))

execute_batch(cur, 'INSERT INTO spam (id) VALUES (%s)', [(1,), (2,)])

execute_values(cur, 'INSERT INTO spam (id) VALUES %s', [(1,), (2,)])

logger.info('executemany')

# not logged
cur.executemany('INSERT INTO spam (id) VALUES (%s)', [(1,), (2,)])
```

If this is intended (for performance reasons?), it would be nice mention it in the docs.

**Comment by dvarrazzo** [comment]
Meh, `LoggingConnection` is not an object I'm in love with. Looking at the implementation of the other methods I think just adding a log() call like for the other ones will result in a single log entry, with the last parameters; logging every single parameters group would require implementing the object in C.

If you want to propose an improvement for the docs please send a patch.
