### ISSUE TITLE
keepalive_interval option throws an error 

### ISSUE THREAD

**Issue by rugging24** [psycopg/psycopg2#547]
Hello, 
I am using psycopg2 for postgres logical decoding. both sync and async streaming consumptions works really well. However the sync stream consumption does not accept the keepalive_interval parameter. 
consume_stream(consume,keepalive_interval=10)

It terminates with the error : 

RuntimeError: more argument specifiers than keyword list entries (remaining format:'d')

any clue how to get this right ?

thanks .

**Comment by dvarrazzo** [comment]
It is a bug: fixing.
