### ISSUE TITLE
ProgrammingError: column "typarray" does not exist

### ISSUE THREAD

**Issue by zeromake** [psycopg/psycopg2#556]
## ERROR
```
File "/usr/lib/python2.7/site-packages/psycopg2/extras.py", line 905, in get_oids
    """ % typarray)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "typarray" does not exist
LINE 1: SELECT t.oid, typarray
```

system: centos7's docker
docker FROM alpine:latest pip install psycopg2
psycopg2==2.7.1
``` Dockerfile
FROM alpine:latest

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk add --no-cache mariadb-dev postgresql-dev gcc g++ make python2 python2-dev py2-pip linux-headers

COPY server/requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt -i https://mirrors.ustc.edu.cn/pypi/web/simple

```
print(conn.server_version)
> 80300

https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L894
changed is ok
```
typarray = "NULL" #conn.server_version >= 80300 and "typarray" or "NULL"
```

**Comment by dvarrazzo** [comment]
Are you sure? There should be tests of this object in the test suite, running with 8.3, and according to 

https://www.postgresql.org/docs/8.3/static/catalog-pg-type.html

typarray is there.

Are you connecting to a normal postgres?

**Comment by zeromake** [comment]
psql connecting message：
```
psql (9.2.18, server 8.3devel)
WARNING: psql version 9.2, server version 8.3.
         Some psql features might not work.
Type "help" for help.
```
server 8.3devel ......
ucloud Provide services
https://www.ucloud.cn/site/product/udw.html
I should ucloud let postgres up ？

**Comment by zeromake** [comment]
@dvarrazzo 
I asked UDW：
> UDW based on Greenplum 2016/2 postgres，pg_type table not typarray

can close issues

**Comment by dvarrazzo** [comment]
Yes, that's what I supposed. "8.3.0", smack 0 bugfix level, seemed a bit too round to me.

I don't have greenplum in my test suite and I don't know how it advertise itself on connection so can't work around its specific quirkness.

You can either copy the code from the psycopg and customize it in your project or pass an oid to `register_adapter()` which you can query using a query that works for you (e.g. the one for postgres 8.2).

Have a good day.
