### ISSUE TITLE
IF NOT EXISTS is not supported even on postgres version > 9.5

### ISSUE THREAD

**Issue by noahrowland** [psycopg/psycopg2#559]
This statement runs fine against a postgres db v9.5:

Create Index if not exists idx_ds_aps_eabollkp_created_ts ON ds_aps_eabollkp(created_ts);

this properly returns:
sql> Create Index if not exists idx_ds_aps_eabollkp_created_ts ON ds_aps_eabollkp(created_ts)
[2017-05-25 15:01:56] [42P07] relation "idx_ds_aps_eabollkp_created_ts" already exists, skipping
[2017-05-25 15:01:56] completed in 8ms

However, when executing via psycog2 with a cursor.execute() returns a programming error:
*** ProgrammingError: syntax error at or near "not"

The library does not seem to support the new syntax added in postgres 9.5 release.

**Comment by dvarrazzo** [comment]
Psycopg doesn't parse sql. It has no idea about "create index" or any other statement you try to execute.

You are connecting to the wrong database. Try checking [connection.server_version](http://initd.org/psycopg/docs/connection.html#connection.server_version).
