### ISSUE TITLE
python setup.py egg_info failed with error code 1

### ISSUE THREAD

**Issue by rofi93** [psycopg/psycopg2#560]
I'm trying to install `psycopg2==2.6.2` in my virtual environment with pip, but gives `python setup.py egg_info failed` error.
I tried to install using following command:

`pip3 install psycopg2==2.6.2`

I'm using python `3.5.2` on Ubuntu `16.04.02` 64 bit.
`setuptools` is updated.
How to solve this ?

**Comment by iamaaronknight** [comment]
@rofi93 I'm getting similar errors on Amazon Linux instances. Did you solve this?

**Comment by rofi93** [comment]
@iamaaronknight Yeah. [This](https://stackoverflow.com/questions/28253681/you-need-to-install-postgresql-server-dev-x-y-for-building-a-server-side-extensi/43512004#43512004) solution solved my problem.

**Comment by zeeshanaligold** [comment]
Here is the solution to solve error. 

sudo apt-get install libpq-dev python-dev
pip install psycopg2

**Comment by viniciuscsouza** [comment]
> Here is the solution to solve error.
> 
> sudo apt-get install libpq-dev python-dev
> pip install psycopg2

Aqui funcionou! Muito obrigado pela ajuda.

**Comment by reedv** [comment]
> Here is the solution to solve error.
> 
> sudo apt-get install libpq-dev python-dev pip install psycopg2

I have Ubuntu 18.04.06 and get the error...
```bash
➜  ~ sudo apt-get install libpq-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpq-dev : Depends: libpq5 (= 10.21-0ubuntu0.18.04.1) but 14.4-1.pgdg18.04+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
and if I do...
```bash
sudo apt install libpq5=10.12-0ubuntu0.18.04.1
```
... that runs fine, but I still get the 
> Command "python setup.py egg_info" failed with error code 1

error.

**Comment by Alok650** [comment]
Hi guys,
getting the issue with psycopg2-binary==2.8.5 and psycopg2==2.8.5


```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2_binary.egg-info
    writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
```
