### ISSUE TITLE
Time to release 2.7.2?

### ISSUE THREAD

**Issue by underyx** [psycopg/psycopg2#564]
We didn't want to be pushy, but https://github.com/psycopg/psycopg2/issues/410 was fixed over two months ago. Since then, we're still getting `unknown error` exceptions around once a week on average. We're too scared to install psycopg2 from a commit hash on `master` so we're just praying that there's nothing important behind these errors. Is there any chance that fix could make it into an official release? 😇

**Comment by dvarrazzo** [comment]
Yes, was thinking about that. There's a handful of issues currently open though, and I was hoping to nail a problem in logical replication, but has happened only a couple of times in one month so I'm not holding my breath for that.

I've reviewed the state of the bug tracker: this is the list of [issues I'd like to close to release 2.7.2](https://github.com/psycopg/psycopg2/milestone/12). One is doc. One is maybe. Two are thorny.

Thank you for the gentle push: helping with the open issues would be welcome. I'll do my best to work on them in the next days but I'm in a busy period with `$PAYING_JOB` so psycopg may have to wait.

**Comment by dvarrazzo** [comment]
#557 is the last guy open. It is a badass bug, and after seeing what happened with #551 I wouldn't even be so surprised if that is tickling some Py 3.6 interpreter bug. Anyway, closing this ticket: the nudge has been received ok and psycopg 2.7.2 is on its way to be released (compatibly with my available time).
