### ISSUE TITLE
Inserting binaries with extras.execute_values

### ISSUE THREAD

**Issue by ClodoaldoPinto** [psycopg/psycopg2#568]
Trying to insert binaries using `extras.execute_values` in Psycopg 2.7.1 and Python 2.7.13:

    binaries = ['\x00\x20', '\x00\x30']
    binaries = [Binary(b) for b in binaries]
    
    insert_query = 'insert into t (b) values %s'
    psycopg2.extras.execute_values (
        cursor, insert_query, binaries, page_size=100
    )

Error:

    Traceback (most recent call last):
      File "./stackoverflow.py", line 16, in <module>
        cursor, insert_query, binaries, page_size=100
      File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 1244, in execute_values
        template = b'(' + b','.join([b'%s'] * len(page[0])) + b')'
    TypeError: object of type 'psycopg2.extensions.Binary' has no len()

**Comment by dvarrazzo** [comment]
Please [read the docs](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_values). *argslist* must be a sequence of sequences, not a sequences of binaries.

**Comment by ClodoaldoPinto** [comment]
Sorry for the noise
