### ISSUE TITLE
Pool: improve getconn() documentation

### ISSUE THREAD

**Issue by bernhardreiter** [psycopg/psycopg2#569]
Hello,
http://initd.org/psycopg/docs/pool.html currently reads:
```
getconn(key=None)
Get a free connection and assign it to key if not None.
```
It is unclear what key is used for (unless studying the code).
Someone would assume that a caller will get the same connection if the same key is used,
but this is not stated.

In addition it would be nice to explain the behaviour of the pool classes in more depth, especially: 
 * Must users of getconn() always call putconn()?
 * Will getconn() always return a  trouble free connection (e.g. no current transaction, not closed)?
 * What is the relation of the transaction handling with the pool classes?

Thanks for psycopg2 as Free Software, we'll use it quite a bit and you are also on
my flattr subscription!

**Comment by dvarrazzo** [comment]
Hi Bernhard,

you probably know better than us the shortcoming of the pool docs. Could you please provide a patch writing down what you would have expected to find there? Thank you very much!

**Comment by bernhardreiter** [comment]
Hi Daniele,
usually, when the fix is easy, I do propose a patch. Thanks for your willingness to include one.
Though, in this case I do not know the answers of the questions well enough to provide one. In order to find, I would have to read the code in several places, do a number of experiments to see if my mental model of it is good and then I'd still be left with not knowing what the intention of some parts of the behaviour would be.

This is why I've tried to describe the questions that the documentation should answer as good as I can.
For the key if the behaviour is like I expect it to be, I'd write something like

```
You can assign a key to a connection by using the key parameter. If the a key is used
more than once, the same connection object will be returned.
```
(Now I don't know if and when the connections are resetted or cleared, which I'd put in the next sentence.)

**Comment by dvarrazzo** [comment]
Ok, I'll leave the bug open and review the docs based on your points. I was asking because I'm not really practical with the pool either :P and I thought that you had read the code instead to make up for the missing docs :D

Thank you for your input

**Comment by bernhardreiter** [comment]
> Ok, I'll leave the bug open and review the docs based on your points. 

Cool, sounds good!
