### ISSUE TITLE
RealDictCursor with multiple tables with homonymous columns

### ISSUE THREAD

**Issue by tywoodpav** [psycopg/psycopg2#571]
Consider

    SELECT tweets.created_at, likes.created_at FROM tweets LEFT JOIN likes ON likes.tweet_id = tweets.id LIMIT 1;

Using `RealDictCursor` results in 

    [{ 'created_at': '2017-06-18 20:17:04.417122' }]

This is an unambiguous query returning an ambiguous result.

Perhaps a better way would be to return 
    
    [{ 'tweets': { 'created_at': '2017-06-18 20:17:04.417122' }, 'likes': { 'created_at': '2017-06-18 20:18:23.147970' }}]

This would only be useful for `JOIN` so perhaps a `RealDictTableCursor`?

For joins with many fields this would be incredibly useful because the current solution is to use indices (from what I can tell). Although I'm a fan of Sesame Street, I really don't like to count. 

Is there a way around using indices (default cursor) with the current `psycopg2`?

Related: #418

**Comment by dvarrazzo** [comment]
Just don't write ambiguous column names:

    SELECT tweets.created_at AS tweet_created_at, likes.created_at as likes_created_at
    FROM tweets
    LEFT JOIN likes ON likes.tweet_id = tweets.id LIMIT 1;

We try our best to behave in a reasonable way upon reasonable input. We reserve the right of crying, or laughing, or barfing, or sneering, on the expectation of a sane result upon broken input.

Otherwise developing psycopg would be boring :D

**Comment by tywoodpav** [comment]
just realized. dope.
