### ISSUE TITLE
mogrify() doesn't work with str arrays of DATE/TIME/TIMESTAMP

### ISSUE THREAD

**Issue by daveisfera** [psycopg/psycopg2#572]
When trying to insert and array of `DATE`/`TIME`/`TIMESTAMP` from string values, `mogrify()` uses the `ARRAY[]` syntax which causes Postgres to fail with a type error. When the `{}` syntax is used, the type are converted as expected.

Here's a small example of the problem:
```
import psycopg2
 
conn = psycopg2.connect(...)
cursor = conn.cursor()
cursor.execute("CREATE TABLE test_array_date (a DATE[]);")
query = "INSERT INTO test_array_date (a) VALUES (%s);"
cursor.execute("INSERT INTO test_array_date (a) VALUES ('{2017-01-01, 2016-01-01}')")
print(cursor.mogrify(query, [["2017-01-01", "2016-01-01"]]))
cursor.execute(query, [["2017-01-01", "2016-01-01"]])
```

**Comment by dvarrazzo** [comment]
It works perfectly fine for me:

```python
In [14]: d = datetime.date.today()

In [15]: cur.mogrify("select %s", [[d, d]])
Out[15]: "select ARRAY['2017-06-20'::date, '2017-06-20'::date]"

In [16]: cur.execute("select %s", [[d, d]])

In [17]: cur.fetchone()[0]
Out[17]: [datetime.date(2017, 6, 20), datetime.date(2017, 6, 20)]
```

with strings:

```python
In [18]: ds = str(d)

In [19]: cur.mogrify("select %s", [[ds, ds]])
Out[19]: "select ARRAY['2017-06-20', '2017-06-20']"

In [20]: cur.execute("select %s", [[ds, ds]])

In [21]: cur.fetchone()[0]
Out[21]: ['2017-06-20', '2017-06-20']
```

Inserting into a table works as well

```python
In [22]: cur.execute("CREATE TABLE test_array_date (a DATE[]);")

In [23]: cur.execute("insert into test_array_date values (%s)", [[d,d]])

In [24]: cur.execute("select * from test_array_date")

In [25]: cur.fetchall()
Out[25]: [([datetime.date(2017, 6, 20), datetime.date(2017, 6, 20)],)]
```

if you are expecting this to work:

```python
In [26]: cur.execute("insert into test_array_date values (%s)", [[ds,ds]])
ProgrammingError                          Traceback (most recent call last)
<ipython-input-26> in <module>()
----> 1 cur.execute("insert into test_array_date values (%s)", [[ds,ds]])

ProgrammingError: column "a" is of type date[] but expression is of type text[]
LINE 1: insert into test_array_date values (ARRAY['2017-06-20', '201...
                                            ^
HINT:  You will need to rewrite or cast the expression.
```

you have to do like the server suggests: use a cast

```python
In [32]: cur.execute("insert into test_array_date values (%s::date[])", [[ds,ds]])

In [33]: cur.execute("select * from test_array_date")

In [34]: cur.fetchall()
Out[34]: [([datetime.date(2017, 6, 20), datetime.date(2017, 6, 20)],)]
```

The adapter is working as expected. The use of the `{}` syntax for array will come eventually. But not now.

**Comment by daveisfera** [comment]
Yes, I expecting that 4th example to work. The cast solves the problem but makes the query more complex and can be difficult when writing generic code that is supposed to write to several tables with varying types.

**Comment by dvarrazzo** [comment]
Well, you are clearly passing objects of the wrong type: your expectation that this may lead to the right result is at best optimistic. Also, you seem to suggest that just using the literal expression for array instead of the ARRAY[] construct may solve all the problems. While that is a direction psycopg will eventually take, it will actually require more casting in the queries, not less (many more cases will be ambiguous).

You can write your own adapter for list of dates, or list of specific objects, to be turned I to arrays of a specific type. Psycopg uses python classes to define the types: a list of strings is converted into an array of text, and generally this makes sense. If it doesn't for you, you can customise your way of adapting your types.

**Comment by daveisfera** [comment]
I understand that this is not the way that psycopg2 is implemented and it may be more difficult than I realize to switch to the `{}` syntax, but technically, a string is the "native input format" for `DATE`/`TIME`/`TIMESTAMP` in Postgres and when the `{}` syntax is used the casting happens automatically. Using the `ARRAY[]` syntax prevents that because then Postgres has to decide on the type of the array and doesn't allow conversion from `TEXT[]` instead of allowing the normal input parsing to happen on each of the elements in the array.

**Comment by fogzot** [comment]
No, the string is NOT the "native input format" for DATE/TIME/TIMESTAMP. PostgreSQL implements automatic typecasts from string to *some* types but that is what is it, an automatic typecast that sometimes works. If string was the "native input format" it would work anywhere, even in ARRAY[].

Said that, you can help psycopg build the correct query string, with an explicit typecast by passing it the correct *Python* types. Without type information psycopg can't build the correct query and should rely on PostgreSQL automatic typecast that, as you have seen, sometimes simply don't work.
