### ISSUE TITLE
Display place holder instead of binary data

### ISSUE THREAD

**Issue by mzabuawala** [psycopg/psycopg2#575]
I have table test with columns id (of _bigint_ type) & data (of _bytea_ type).

I don't want to display actual binary data from _data_ column when I execute below query in Python.

`select * from test;`

I just want a place holder which display `<binary data>` or `<BLOB>`, because some of data are in hundreds of MB in that column which does not make any sense to display binary data in column, it also consumes lots of memory.

Is it possible to identify and replace binary data with just a place holder in psycopg2?

```
#!/usr/bin/python

import psycopg2

conn = psycopg2.connect(database = "testdb", user = "postgres", password = "pass123", host = "127.0.0.1", port = "5432")
print "Opened database successfully"

cur = conn.cursor()

cur.execute("SELECT id, data from test")
rows = cur.fetchall()
for row in rows:
   print("ID = ", row[0], "DATA = ", row[1])

print "Operation done successfully";
conn.close()

# Expected output
# ID =  1 DATA = <BLOB>  <-- Just a place holder not actual binary data from column
# ID =  2 DATA = <BLOB>
# ID =  3 DATA = <BLOB>
```
Link for question on [SF](https://stackoverflow.com/questions/44907091/handling-of-binary-data-with-python-psycopg2-db-postgres-9-5)

**Comment by dvarrazzo** [comment]
If the data is bytea you can write your own bytea typecaster as an object that wraps a binary string.

Note that the data is fetched and sent on the network anyway. If you don't want that overhead just don't select those fields.

```python
>>> import psycopg2

>>> class Wrapper:
...     def __init__(self, thing):
...         self.thing = thing
...         

>>> psycopg2.extensions.register_type(
...     psycopg2.extensions.new_type(
...         psycopg2.BINARY.values, "WRAPPER", lambda x, cur: Wrapper(x)))

>>> cnn = psycopg2.connect('')
>>> cur = cnn.cursor()
>>> cur.execute("create table btest(id serial primary key, data bytea)")
>>> cur.execute("insert into btest (data) values ('foobar')")
>>> cur.execute("select * from btest")
>>> r = cur.fetchone()
>>> r
(1, <__main__.Wrapper instance at 0x7fb8740eba70>)
>>> r[1].thing
'\\x666f6f626172'
```

Please refer to the documentation for the `extensions` functions used.

**Comment by mzabuawala** [comment]
Thank you for the answer 👍
