### ISSUE TITLE
Calling mogrify on closed cursor

### ISSUE THREAD

**Issue by drtyrsa** [psycopg/psycopg2#579]
Currently it's impossible to call `mogrify` on closed cursor. Is it really necessary? It seems that mogrifying is done on client side and doesn't use DB server, so it shouldn't care whether cursor is closed or not.

The context where it's relevant is logging sql on exception:
  
    try:
        cursor.execute(sql, params)
    except psycopg2.Error:
        logger.exception('Database error when executing %s', cursor.mogrify(sql, params))

If cursor is somehow closed it's impossible to log final sql query.

**Comment by dvarrazzo** [comment]
Maybe the test is eccessive, but maybe some adapter will call some libpq function that may fail if the connection is close - especially I think about escaping strings. We can take a look.
