### ISSUE TITLE
pythonhosted.org News list not updated with latest release (2.7.3)

### ISSUE THREAD

**Issue by klaplong** [psycopg/psycopg2#581]
All versions are there except the latest. http://pythonhosted.org/psycopg2/news.html

**Comment by dvarrazzo** [comment]
Uploading to that website fails continuously.

I will replace that stuff with a redirect to our website.

**Comment by dvarrazzo** [comment]
404 Not Found

The resource could not be found.

Good. this fixes the problem. Please use the docs at http://initd.org/psycopg/docs/ thank you.
