### ISSUE TITLE
Can't use sub-module  directly 

### ISSUE THREAD

**Issue by Nick-Alam** [psycopg/psycopg2#582]
I was trying work with sub-module of psycopg2q, and I import psycopg2 as below:
```python 
import psycopg2
psycopg2.pool
psycopg2.extras
```
With Error:
```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-34e44a99e628> in <module>()
----> 1 psycopg2.pool
AttributeError: module 'psycopg2' has no attribute 'pool'
AttributeError: module 'psycopg2' has no attribute 'extras'

```
But if I import ```pool``` and  ```extras``` first,  still access them with ```psycopg2.pool``` ```psycopg2.extras```
```python
import psycopg2
from psycopg2 import pool, extras
psycopg2.pool
psycopg2.extras
```
 Error is gone:
```bash
<module 'psycopg2.pool' from '/opt/Anaconda/3/lib/python3.6/site-packages/psycopg2/pool.py'>
<module 'psycopg2.extras' from '/opt/Anaconda/3/lib/python3.6/site-packages/psycopg2/extras.py'>
```

Problem is, why can't I use psycopg2 sub-module directly? 

My python version ```Python 3.6.2 :: Anaconda custom (64-bit)```, tested on ```Ipython``` & ```Jupyter```

please help, thanks a lot in advance

**Comment by dvarrazzo** [comment]
Because they are designed this way: they are not imported automatically if not needed. This is standard Python practice.
