### ISSUE TITLE
Date typecasting in UPDATE using execute_values and a sequence of dictionaries

### ISSUE THREAD

**Issue by a455bcd9** [psycopg/psycopg2#583]
Hi,

I tried to give an explicit title but I guess this example will be more explicit. Tested on both Ubuntu 16.04 and RHEL, with Python 3.5.3 :: Continuum Analytics, Inc. and psycopg2==2.7.3.1 and Postgres 9.5:

```
import psycopg2, datetime

conn = psycopg2.connect('dbname=mydb')

c = conn.cursor()

c.execute('CREATE TABLE IF NOT EXISTS t (d date)')
c.execute('TRUNCATE t')

date_list = [{'d': datetime.date(2003, 9, 18)}]
empty_date_list = [{'d': None}]

# INSERT works, with both non empty and empty dates
psycopg2.extras.execute_values(c, "INSERT INTO t (d) VALUES %s;", date_list, template="(%(d)s)")
psycopg2.extras.execute_values(c, "INSERT INTO t (d) VALUES %s;", empty_date_list, template="(%(d)s)") 

# UPDATE works with a non empty date BUT fails with an empty date
psycopg2.extras.execute_values(c, "UPDATE t SET d = data.d FROM (VALUES %s) AS data (d);", empty_date_list, template="(%(d)s)")
psycopg2.extras.execute_values(c, "UPDATE t SET d = data.d FROM (VALUES %s) AS data (d);", my_list, template="(%(d)s)")
```

Results in:

```
ProgrammingError: column "d" is of type date but expression is of type text
LINE 1: UPDATE t SET d = data.d FROM (VALUES (NULL)) AS data (d);
                         ^
HINT:  You will need to rewrite or cast the expression.
```

If I reproduce the operations directly in pgAdmin 4, I can also reproduce the error:

```
INSERT INTO test (mydate) VALUES ('2000-01-01'::date);  -- Works
INSERT INTO test (mydate) VALUES (NULL::date);  -- Works
INSERT INTO test (mydate) VALUES ('2000-01-01');  -- Works
INSERT INTO test (mydate) VALUES (NULL);  -- Works

UPDATE t SET d = data.d FROM (VALUES ('2000-01-01'::date)) AS data (d);  -- Works
UPDATE t SET d = data.d FROM (VALUES (NULL::date)) AS data (d);  -- Works
UPDATE t SET d = data.d FROM (VALUES ('2000-01-01')) AS data (d);  -- Fails
UPDATE t SET d = data.d FROM (VALUES (NULL)) AS data (d);  -- Fails
```

So it seems `None` is converted to `NULL` instead of `NULL::date`, but I guess the error is inherent to the way Postgres handles the `FROM (VALUES ())` syntax and maybe there's no way to fix this, because we don't know in advance what's the type of the column. In this case, the part of the documentation with the UPDATE example should be removed. Maybe the problem could be solved using Python 3.6 type hints (PEP 484)? 

Please let me know if you need more details.

**Comment by dvarrazzo** [comment]
As you have verified it is a problem with the query generated and the server.

You can easily work around it following the server hint to cast the expression: this works as expected:

```python
psycopg2.extras.execute_values(c,
    "UPDATE t SET d = data.d FROM (VALUES %s) AS data (d);",
    empty_date_list,
    template="(%(d)s::date)")
```

**Comment by a455bcd9** [comment]
Thanks @dvarrazzo!

Unfortunately, I don't think your work around would work in my case, as I would like to do a generic "bulk update" method that only received a dictionary with columns and values and automatically generates the template.

**Comment by MartinProcsea** [comment]
Hello @a455bcd9 ,

Sorry for the old topic!
I am facing the same issue. Have you figured out a general workaround this problem?
Thanks a lot !
