### ISSUE TITLE
error on compiler windows using msys2

### ISSUE THREAD

**Issue by welitonfreitas** [psycopg/psycopg2#588]
`    C:\msys32\mingw32\bin/i686-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -DPSYCOPG_DEFAULT_PYDATETIME=1 "-DPSYCOPG_VERSION=\\\"2.7.3.1 (dt dec pq3 ext)\\\"" -DPG_VERSION_NUM=90603 -IC:/msys32/mingw32/include/python3.6m -I. -IC:/msys32/mingw32/include -IC:/msys32/mingw32/include/POSTGR~1/server -c psycopg/psycopgmodule.c -o build/temp.mingw-3.6/psycopg/psycopgmodule.o -O3 -fno-strict-aliasing
    <command-line>:0:18: warning: missing terminating " character
    In file included from ./psycopg/config.h:153:0,
                     from ./psycopg/psycopg.h:37,
                     from psycopg/psycopgmodule.c:27:
    ./psycopg/win32_support.h:42:6: error: #elif with no expression
     #elif
          ^
    psycopg/psycopgmodule.c: In function 'PyInit__psycopg':
    <command-line>:0:17: error: stray '\' in program
    psycopg/psycopgmodule.c:1020:55: note: in expansion of macro 'PSYCOPG_VERSION'
         PyModule_AddStringConstant(module, "__version__", PSYCOPG_VERSION);
                                                           ^
    <command-line>:0:18: error: missing terminating " character
    psycopg/psycopgmodule.c:1020:55: note: in expansion of macro 'PSYCOPG_VERSION'
         PyModule_AddStringConstant(module, "__version__", PSYCOPG_VERSION);
                                                           ^
    psycopg/psycopgmodule.c:1020:70: error: expected expression before ')' token
         PyModule_AddStringConstant(module, "__version__", PSYCOPG_VERSION);
                                                                          ^
    error: command 'C:\\msys32\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1

`
version: 2.7.3.1
gcc: gcc version 7.2.0 (Rev1, Built by MSYS2 project)

**Comment by dvarrazzo** [comment]
msys is not supported. 

If you want to support it patches are welcome. In order to declare it supported the library must also be built and tested with appveyor.

https://github.com/psycopg/psycopg2-wheels
https://ci.appveyor.com/project/psycopg/psycopg2-wheels/branch/master
