### ISSUE TITLE
Inserting a list of IntEnum members into integer[] fails

### ISSUE THREAD

**Issue by DragoonAethis** [psycopg/psycopg2#591]
This was originally reported as a peewee ORM issue [here](https://github.com/coleifer/peewee/issues/1346), but it turns out it's a problem down here. Inserting an array of IntEnum members as an array of integers fails, since psycopg2 tries to take those IntEnum members by their name instead of by their value (as it should be treated).

Let's say we have a happy little table:

```sql
CREATE TABLE public.maduser (
  id SERIAL PRIMARY KEY,
  login TEXT NOT NULL,
  password TEXT NOT NULL,
  roles INTEGER[] NOT NULL
);
```

...and we have the following code using that table:

```python
# Each user could have a lot of those roles/permissions/etc.
class Role(IntEnum):
    can_sign_in = 0
    view_posts = 1
    edit_posts = 2
    delete_posts = 3  # And so on...
    admin = 1000

conn = psycopg2.connect("dbname=sometable user=nope password=sorry")
cur = conn.cursor()
cur.execute("INSERT INTO maduser (login, password, roles) VALUES (%s, %s, %s)", ["admin", "test", [Role.admin]]);  # Boom!
```

...which fails with:

```python
Traceback (most recent call last):
  File "/somewhere/in/the/universe/psycopg-boom.py", line 26, in <module>
    cur.execute("INSERT INTO maduser (login, password, roles) VALUES (%s, %s, %s)", ["admin", "test", [Role.admin]]);
psycopg2.ProgrammingError: missing FROM-clause entry for table "role"
LINE 1: ..., password, roles) VALUES ('admin', 'test', ARRAY[Role.admin...
```

Since [IntEnum members are subclasses of ints](https://docs.python.org/3/library/enum.html#intenum), it should be possible to assign those members directly. Many other Python mechanisms treat them much like integers (so, say, Role.admin == 1000 works as you'd expect), yet it doesn't in there.

The workaround would be to pass an array of [int(Role.etc), int(Role.asn), ...] instead of [Role.etc, Role.asn, ...] but this looks like it's just a bug.

**Comment by dvarrazzo** [comment]
Yeah, these objects are not supported, I didn't know anything about them TBH.

I think it should be easy to add an adapter for them.

**Comment by DragoonAethis** [comment]
Great, thanks!
