### ISSUE TITLE
Cannot query database with psycopg2 - relation does not exist 

### ISSUE THREAD

**Issue by aradler** [psycopg/psycopg2#593]
I'm having issues querying my database on a linux box. Happy to give any necessary info. When I connect using macOS I can do all the database operations just fine. All of my connections are local on each machine. Our production machine is a debian box; I can query using postgres just fine with it. But when I use psycopg2, there are issues. I've worked on this for a few hours, and haven't been able to find a solution on SO. I'm thinking this might be a bug.

`relation "users" does not exist
LINE 1: SELECT * from users;`
                      ^

But in postgres:

`postgres=# select * from users;
 id | card_id  |  ......
----+----------+----------+----------+-------------------+---------------
  1 | 16808635 | 16808635 | removed   | for          | privacy`

Any guidance on what to do next would be greatly appreciated!`

**Comment by dvarrazzo** [comment]
I guess you are connecting to the wrong database.

**Comment by pengcao** [comment]
you maybe connect the wrong database

**Comment by gorgevorgyan** [comment]
> connect the wrong database

siktir exi boz
