### ISSUE TITLE
SET operations fail while using a server side (named) cursor

### ISSUE THREAD

**Issue by bmoscon** [psycopg/psycopg2#596]
I'm using server side cursors and I want to set the search path to a specific schema. It works with normal cursors, but not with server side:

```
import psycopg2

conn = psycopg2.connect("dbname='template1' host='localhost'")
cur = conn.cursor(name='server_side')
cur.execute("""SET search_path to schema_name""")
```

gives the following error:
```
Traceback (most recent call last):
  File "error.py", line 5, in <module>
    cur.execute("""SET search_path to schema_name""")
psycopg2.ProgrammingError: syntax error at or near "SET"
LINE 1: DECLARE "server_side" CURSOR WITHOUT HOLD FOR SET search_pat...
```

Is something like this possible while using named cursors?

**Comment by fogzot** [comment]
Why, but WHY do you want to do that?! Cursors are for queries, for everything else just send the SQL.

**Comment by bmoscon** [comment]
Forgive my ignorance, but I don't know what you mean. I've never seen an example of how to execute a SQL statement that didn't use cursor.execute(). I'm definitely no expert, so please enlighten me! :)

**Comment by fogzot** [comment]
Just don't use a server side cursor:
```
conn = psycopg2.connect("dbname='template1' host='localhost'")
cur = conn.cursor()
cur.execute("""SET search_path to schema_name""")
```

**Comment by Daenyth** [comment]
What if we want to set the search path for queries that follow after, and the size of the data involved forces us to use server-side cursors? Is it just impossible?

I don't think this is unreasonable:
```
with conn.cursor(name='foo') as cursor:
    cursor.execute('SET search_path TO blah')
    do_stuff_with_prepared_cursor(cursor)
```

**Comment by bmoscon** [comment]
There are some use cases which necessitate a server side cursor. Isn't that why they are provided?

**Comment by dvarrazzo** [comment]
You can use two cursors, one normal and one named, on the same connection. They would issue commands in the same database session. Use the named cursor to fetch data and the normal cursor to send the configuration commands.

**Comment by bmoscon** [comment]
thanks for the tip @dvarrazzo !
