### ISSUE TITLE
Files in .libs missing

### ISSUE THREAD

**Issue by evgenyfadeev** [psycopg/psycopg2#597]
Hi, could anyone please tell how to make sure that the system libraries are placed into the .libs folder? In some of my installs they are present and in some others - absent.

It is convenient to package dependencies for the AWS lambda when all the files are there, so I'd like to force the .libs directory populated and imported from by the psycopg2.

Thanks!

**Comment by dvarrazzo** [comment]
The `.libs` directory is installed by the wheels package. You can use the `--only-binary` pip option to force installing from wheels.

    pip install --only-binary=:all: psycopg2

it is probably possible to specify that in a `requirements.txt` file, adding something like (untested):

    psycopg2>=2.7,<2.8 --only-binary :all:

**Comment by evgenyfadeev** [comment]
Thank you, sir!
