### ISSUE TITLE
PostgreSQL 10 new password hash auth errors

### ISSUE THREAD

**Issue by evitalis** [psycopg/psycopg2#601]
I recently upgraded to PostgreSQL 10 which introduces a new hashing type for passwords, scram-sha-256, but existing clients cannot connect to it. An OperationError is returned with a code 10, I do not have access to the exact trace at the moment.

Does the psycopg2 project plan to support this new hashing algorithm or do users need to remain with the less secure, and hand rolled, MD5 implementation by the PostgreSQL team?

**Comment by dvarrazzo** [comment]
I suppose authentication is a matter between the libpq and the server. What version of libpq are you using?

**Comment by evitalis** [comment]
Yeah it is a new libpq as well.
Here is what I see ona  brand new CentOS 7.4 system.

```
[root@centos7dev ~]# find / -name "*libpq*"
/usr/pgsql-10/lib/libpq.so.5
/usr/pgsql-10/lib/libpq.so.5.10
/usr/pgsql-10/lib/libpqwalreceiver.so
/usr/pgsql-10/share/locale/cs/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/de/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/es/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/fr/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/he/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/it/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/ja/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/ko/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/pl/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/pt_BR/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/ru/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/sv/LC_MESSAGES/libpq5-10.mo
/usr/pgsql-10/share/locale/zh_CN/LC_MESSAGES/libpq5-10.mo
```

This is after installing PGSQL 10 from the official repos. 
https://www.postgresql.org/download/linux/redhat/

If I specify the path to pg_config and run build before installing then things work fine. However the version in pip does not out of the box.

Let me know if more info is needed.

**Comment by dvarrazzo** [comment]
No it is as expected: psycopg 2.7.3.1 is a binary package built using libpq from PostgreSQL 9.6.

I am currently working to release binary packages using libpq 10 (see #602). If you can please test the packages in http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/ using

    pip install http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/psycopg2-2.7.3.2.dev0-cp36-cp36m-manylinux1_x86_64.whl

and let me know if the new authentication is supported ok. Thank you very much!

**Comment by evitalis** [comment]
That does look like it connects just fine. I was also able to create a table so I assume adding data will work fine as well.

```
(psycopg2) [root@centos7dev ~]# pip install http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/psycopg2-2.7.3.2.dev0-cp36-cp36m-manylinux1_x86_64.whl
Collecting psycopg2==2.7.3.2.dev0 from http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/psycopg2-2.7.3.2.dev0-cp36-cp36m-manylinux1_x86_64.whl
  Downloading http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/psycopg2-2.7.3.2.dev0-cp36-cp36m-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 57.8MB/s
Installing collected packages: psycopg2
  Found existing installation: psycopg2 2.7.3.1
    Uninstalling psycopg2-2.7.3.1:
      Successfully uninstalled psycopg2-2.7.3.1
Successfully installed psycopg2-2.7.3.2.dev0
(psycopg2) [root@centos7dev ~]# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
psycopg2 (2.7.3.2.dev0)
setuptools (28.8.0)

(psycopg2) [root@centos7dev ~]# python3.6
Python 3.6.2 (default, Jul 18 2017, 22:59:34)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> connect = psycopg2.connect(dbname='pydemo', host='X.X.X.X', user='pydemo', password='XXXXX')
>>> cur = connect.cursor()
>>> cur.execute('CREATE TABLE testing (id SERIAL PRIMARY KEY, data TEXT)')
>>> connect.commit()
```

**Comment by dvarrazzo** [comment]
Thank you for testing! :+1:

I will release updated packages pending solution of #604. In the meantime you can install psycopg from source using `pip install --no-binary`. See http://initd.org/psycopg/docs/install.html#binary-install-from-pypi

**Comment by evitalis** [comment]
I will give it another shot on a different OS tomorrow and can report back, but if it works in one place I don't see why others wouldn't. If I was more of a Windows guy I could try and help with #604.
