### ISSUE TITLE
Support multiple hosts

### ISSUE THREAD

**Issue by saml** [psycopg/psycopg2#602]
With latest libpg (version 10),  connection string accepts multiple hosts:
https://www.postgresql.org/docs/current/static/libpq-connect.html#libpq-multiple-hosts

Current behavior:
```py
>>> psycopg2.connect('user=user1 password=password1 host=host1,host2 port=5432,5432 dbname=db1')
OperationalError: could not translate host name "host1,host2" to address: Name or service not known
```

Desired behavior:
```py
>>> psycopg2.connect('user=user1 password=password1 host=host1,host2 port=5432,5432 dbname=db1')
# Success
```
even when host1:5432 is down.

**Comment by dvarrazzo** [comment]
Are you compiling psycopg yourself or are you installing it from wheels?

If the problem above is with the wheels package, that's ok: I will release a new one linking with libpq 10. If you have installed psycopg from source it should work ok, provided you bind it with the libpq from pg 10. If not, we will investigate.

Let us know, thank you.

**Comment by saml** [comment]
@dvarrazzo I used wheels package. Did not psycopg2 from source.
I'll close this because next build of wheels package will support multiple hosts.  👍 

Thanks.

**Comment by dvarrazzo** [comment]
@saml will you be available to test the package for me with your setup? I'll send you the instructions as soon as the package is ready.

**Comment by saml** [comment]
@dvarrazzo sure. Glad to test!

**Comment by dvarrazzo** [comment]
Linux packages are ready for testing into http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/ It would be great if you can test them. You can use `pip install URL` pointing at the right package url for a test.

OSX packages are under way (Travis OSX is still busy). Window packages have #604 to solve.

**Comment by saml** [comment]
@dvarrazzo Looks good to me.

```sh
# install new build
pip install http://initd.org/psycopg/upload/psycopg2-2.7.3.2.dev0/psycopg2-2.7.3.2.dev0-cp36-cp36m-manylinux1_x86_64.whl

# start postgres 9  (server is 9 instead of 10 for fun)
# it listens to localhost:5454
POSTGRES_PASSWORD=postgres docker run --rm --detach --publish 5454:5432 --name db1 postgres:9

# test connection
# nothing listens to localhost:5455. expecting it to connect to localhost:5454
python -c "import psycopg2; psycopg2.connect('user=postgres password=postgres host=localhost,localhost port=5455,5454 dbname=postgres connect_timeout=3')"
```

Looks like server doesn't have to be version 10 to get multi-host dsn working. Purely libpq smartness.

This with pooling (from sqlalchemy, for example) makes application level failover easy 👍
