### ISSUE TITLE
PgAdmin4 and psycopg2 giving different results. 

### ISSUE THREAD

**Issue by erangadbw** [psycopg/psycopg2#605]
Hi.

Using Psycopg2 i  create the below table. 

`import psycopg2`
`conn = psycopg2.connect("dbname=postgres user=postgres host=localhost password=xxxxx")`	
`cur = conn.cursor()`
`cur.execute('create table public.testtableone ( coltwo character varying(5) NOT NULL)')`
`conn.commit()`
`conn.close()`

Now this works totally fine. When i run this line of code on a separate script. 
`cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';")`
it results in 
`[('testtableone')]`
As expected.

However when I open up pgAdmin 4 and look in my postgre database their is no table under the name of testableone under the public schema.

Similarly when I create a table underneath the public schema on pgAdmin4. The above line of code does not show any of the tables i create on pgAdmin4 only ones i create via python.

Is their someway to synch these two? The usuall issue of not commit the changes cant be the issue since pgAdmin4 auto commits and im running conn.commit() line to save the changes using python.

Am i somehow connected to a different instance of the database using psycopg2?

Any assistance would be fantastic.

**Comment by dvarrazzo** [comment]
If you are really committing in psycopg, then the only explanation is that you are connecting to two different databases.
