### ISSUE TITLE
[Question] How do I force psycpog2 to use particular version of libpq?

### ISSUE THREAD

**Issue by mzabuawala** [psycopg/psycopg2#607]
Is there any way I can force psycpog2 to use particular version of libpq.
I am using psycpog2 (2.7.1).

What I'm trying to do is, I trying to use new keyword parameter added libpq v.10 which is `passfile` from psycpog2 connect method.

Ref: 
https://www.postgresql.org/docs/10/static/libpq-pgpass.html
https://www.postgresql.org/docs/10/static/libpq-connect.html#libpq-connect-passfile

**Comment by dvarrazzo** [comment]
If installing from source, you can just make sure that `setup.py` will find `pg_config` from postgres 10, see [the docs](http://initd.org/psycopg/docs/install.html#install-from-source).

If installing from a binary package is good, 2.7.3.2 comes with libpq 10 included.

**Comment by mzabuawala** [comment]
Thank you Daniele.

**Comment by mzabuawala** [comment]
Hi Daniele,

Quick question, When I connect server with `passfile`  keyword parameter,
1) HOSTNAME (`host` parameter in connect() method) and PGPASS supplied, server is connected successfully.

2) HOST ADDRESS (`hostaddr ` parameter in connect() method) and PGPASS supplied, server doesn't connect and give error
"No pasword supplied"

Ref: https://www.postgresql.org/docs/9.3/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS

Is this a bug with psycopg2?

**Comment by dvarrazzo** [comment]
@mzabuawala these questions are not about the bug you opened. Please use the mailing list to ask for questions.
