### ISSUE TITLE
data_start and wal_end are always the same

### ISSUE THREAD

**Issue by rugging24** [psycopg/psycopg2#608]
Hello ,
I am currently using the psycopg2 to consumer streams from logical replication slots from PostgreSQL. And I found out that in the doc, data_start and wal_end were defined as : 

data_start : LSN position of the start of the message ,

wal_end : LSN position of the current end of WAL on the server.

Both these values are always the same. Is this correct ?

I am using the wal2json output plugin, when I convert the LSN obtained from the plugin to a base 10 int, it significantly differs from the LSN returned from the psycopg2 driver. 

Is this correct or am I missing something fundamental ?

regards

**Comment by dvarrazzo** [comment]
Hello @a1exsh, do you have any comment about this question? Thank you very much :)

**Comment by a1exsh** [comment]
@rugging24 Hi, could you please share more details, such the PostgreSQL server version you're using, psycopg2 version and an example of LSNs reported by psycopg2 replication message and the value provided by the plugin?

Can you also build and run psycopg2 with debugging messages turned on?  I can see that we log the values immediately after decoding them from the message header: https://github.com/psycopg/psycopg2/blob/f4aa40da0930cfc76ee11e8d7b6c7d8dfb87a220/psycopg/pqpath.c#L1693

Thank you.

**Comment by gclinch** [comment]
For **logical** replication (of which wal2json is an example) I believe it is intentional that data_start and wal_end have the same value - as generated in WalSndPrepareWrite() - https://github.com/postgres/postgres/blob/master/src/backend/replication/walsender.c#L1144
