### ISSUE TITLE
Problem retrieving array of point

### ISSUE THREAD

**Issue by jw35** [psycopg/psycopg2#613]
Given this table:

```
icp=# create table psycopg2_test (points point[]);
CREATE TABLE
icp=# insert into psycopg2_test values ('{"(1,2)","(3,4)"}');
INSERT 0 1
icp=# select * from psycopg2_test;
      points
-------------------
 {"(1,2)","(3,4)"}
(1 row)
```

this script

```
#!/usr/bin/env python3

import psycopg2

conn = psycopg2.connect("dbname='icp' host='localhost'")
cur = conn.cursor()

query = 'select points from psycopg2_test'

cur.execute(query)

for row in cur.fetchall():
    print(repr(row))
```

throws ValueError:

```
Traceback (most recent call last):
  File "./array_test.py", line 12, in <module>
    for row in cur.fetchall():
ValueError: could not convert string to float: '(1,2)'
```

I'm a bit new to both Postgresql Arrays and psycopg2 so I may be misunderstanding. I understand that I could (and have) worked around this using the type casting functions, but I think the documentation says that values of unknown array types will be returned in their underlying text format and that doesn't seem to be happening here.

This seems to be something of a problem for pgcli which blows up with the same message.

I may be imagining things, but in my copy of Postgres, the typarray value for the point datatype is 1017, and the value 1017 is associated with typecast_FLOATARRAY_types[] in typecast_builtins.c which might perhaps explain what's going on?

**Comment by fogzot** [comment]
Mm.. in fact, 1017 seems to be the OID that identities an array of points. Removing it from `typecast_FLOATARRAY_types[]` makes your code work and return just a string, as expected. Unless @dvarrazzo is already working on this I'll add the simple fix (and a test) during the weekend.

**Comment by jw35** [comment]
Thanks, I think that will be good.

For what it's worth I went through all the other values assigned to ARRAY_types in typecast_builtins.c and (apart from this one) they all seem to correspond to OIDs for plausible base types for each array type.

**Comment by dvarrazzo** [comment]
Yup, confirmed, 1017 shouldn't be associated to float array. It was since we have arrays, circa 2005 :D 

Thank you for checking the other values, @jw35. @fogzot fix it if you can, otherwise I'll do it sometimes the next days (I was off for a few days and catching up just now).

**Comment by fogzot** [comment]
@dvarrazzo no problem. I already have the fix. Just need to write a test and commit.
