### ISSUE TITLE
Drop support for Python 2.6?

### ISSUE THREAD

**Issue by hugovk** [psycopg/psycopg2#626]
I'd like to suggest Psycopg drop Python 2.6 sooner rather than later (eg. the next release). Python 2.6 hasn't received security updates in 4 years, and many other libraries have already dropped it, with more in the process, making it harder to support (as you've discovered with wheel), and some are already planning on [dropping 2.7 in mid-2018](https://github.com/PyCQA/meta/issues/19)!

See https://snarky.ca/stop-using-python-2-6/ and http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

Here's the pip installs for psycopg2 from PyPI for the last month (via `pypinfo --percent --pip psycopg2 pyversion`), showing a very small fraction for 2.6.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   66.3% |      1,204,104 |
| 3.6            |   16.2% |        295,175 |
| 3.5            |   10.5% |        190,975 |
| 3.4            |    6.0% |        108,275 |
| 2.6            |    0.8% |         15,099 |
| 3.7            |    0.1% |          1,774 |
| 3.3            |    0.1% |          1,147 |
| 3.2            |    0.0% |             25 |
| None           |    0.0% |             21 |

It would also be beneficial to drop support for EOL Python 3.2 (has tricky Unicode handling) and 3.3, and both are barely used.

**Comment by dvarrazzo** [comment]
That was a rage! What tool did you use for the code cleanup?

Also thank you for the stats: was looking for them yesterday.

**Comment by dvarrazzo** [comment]
Can you also fix:
- `.travis.yml`
- `NEWS`

I could do myself but if you are rebasing to address the comments I left in the patch I don't want to trample on your feet...

**Comment by hugovk** [comment]
I used PyCharm's code inspection to find them (Code -> Inspect Code...), and there's more there.

PyCharm (and all JetBrains tools) is free for non-commercial open source projects!

https://www.jetbrains.com/buy/opensource/

Yes, will update those.

**Comment by hugovk** [comment]
Please remember to submit a review on the comments for them to show up.
