### ISSUE TITLE
The rowcount seems always equal -1 after executemany(), is it the right result?

### ISSUE THREAD

**Issue by goodnewday** [psycopg/psycopg2#633]
Hello,
          After commit   **[Discard any result produced by cursor.executemany()](https://github.com/psycopg/psycopg2/commit/71393b9ae96fecb0d6be24ccb8486526c1a7e102#diff-74ab814c570c59d22268a387145c4f41)**,I found that after the executemany() ,the rowcount always equal -1 when the statement contain RETURNING (if not contain ,rowcount seems right), I have readed [**execute_batch(), execute_values() give wrong rowcount**](https://github.com/psycopg/psycopg2/issues/540), I know that I shouldn't    concern rowcount  after execute_batch and execute_values , but what about executemany() ?

Thank you very much!

**Comment by dvarrazzo** [comment]
You might be right: even if discarding the result we should probably still read the rowcount. I'll check if it's doable. Thank you for the report.
