### ISSUE TITLE
Placeholder %s doesn't get replaced in query string + invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by piotrp88** [psycopg/psycopg2#657]
I'm experiencing a weird behaviour. I built a very simple class that connects to PgBouncer and executes simple queries (`SELECT start, stop, pid FROM instances WHERE id = %s`). This class is used by different processes created using the `multiprocessing` library and each process executes many queries. I have many of those processes up and running. Things run smootly except that sometimes the placeholder doesn't get replaced.

I placed a `try ... except` on the `cursor.execute(query, args)` and `conn.commit()` methods and print both `query` and `args` in order to inspect their value. What I get is that `args` is properly defined (a tuple with one value, for example `(123,)`) and so is `query` (its value is `SELECT start, stop, pid FROM instances WHERE id = %s`). In the log file of PostgreSQL I find the following error:

```
ERROR:  syntax error at or near "%" at character 56
INSTRUCTION:  SELECT start, stop, pid FROM instances WHERE id = %s
```

In the PostgreSQL log file I also find this message reported many times in random order:

```
ERROR:  invalid byte sequence for encoding "UTF8": 0xe4
```

Is this a known behaviour or a bug? I tried everything I could in order to understand what's happening but didn't find a solution.

**Comment by dvarrazzo** [comment]
Not that I know. But psycopg never sends `%s` to the server, it always merges the arguments on the client side. So I really think your program sometimes, somehow, sends the query string without the arguments (kinda performing a `cursor.execute(query)`)

**Comment by dvarrazzo** [comment]
Don't see this being a bug in psycopg.
