### ISSUE TITLE
psycopg2.OperationalError: FATAL:  too many connections for role

### ISSUE THREAD

**Issue by ajayrfhp** [psycopg/psycopg2#663]
Psycopg2 version - 2.7.3.2 (dt dec pq3 ext lo64)
Python - 3.5
Platform - Os X

I am running 2 versions in staging and production. If I start a local version, it throws up this error. Are there ways to check number of active connections ?

Here is the code

``` conn = psycopg2.connect(database_url)

with conn.cursor() as cur:

    cur.execute(query)

    conn.commit()

    cur.close()

**Comment by dvarrazzo** [comment]
The above doesn't close the connection, it only closes the transaction. If the `conn` object is maintained alive by python you will leak connections. Call `conn.close()` explicitly.
