### ISSUE TITLE
Should arguments of LIMIT and OFFSET passed via cur.execute() directly?

### ISSUE THREAD

**Issue by balthild** [psycopg/psycopg2#664]
The document says:

> Only query values should be bound via this method: it shouldn’t be used to merge table or field names to the query (Psycopg will try quoting the table name as a string value, generating invalid SQL). If you need to generate dynamically SQL queries (for instance choosing dynamically a table name) you can use the facilities provided by the psycopg2.sql module:

Can I use such statement to generate SQL?

```python
cur.execute("SELECT * FROM some_table LIMIT %s OFFSET %s;", (10, 20)) # generates
```

```sql
SELECT * FROM some_table LIMIT 10 OFFSET 20;
```

**Comment by dvarrazzo** [comment]
Yes, it is common practice to pass these values as query values. If you need further flexibility in the query generation (e.g. to include or not the `LIMIT` and `OFFSET` keywords themselves) you can take a look at the [psycopg2.sql](http://initd.org/psycopg/docs/sql.html) module.
