### ISSUE TITLE
More of a question: Are named cursors way better than regular cursors when dealing batch processes

### ISSUE THREAD

**Issue by upendram91** [psycopg/psycopg2#666]
I deal with queries that return around 10M records,
Correct me here, if I am wrong. Regular cursors when call fetchall(), they return all of the rows from the result set, and memory has to be allocated in client process to play around those 10M records.

Server side cursors are meant to handle this efficiently, but is it still the same in the latest version of psycopg2 library.
Can some one list any other use cases/uses of named cursor over regular cursor.

Thanks,
Upendra

**Comment by dvarrazzo** [comment]
The questions are for the mailing list. These questions are addressed in the [faq](http://initd.org/psycopg/docs/faq.html#faq-named-cursors)
