### ISSUE TITLE
Timestamptz and None

### ISSUE THREAD

**Issue by sergeychibunin** [psycopg/psycopg2#670]
Hello.
I have the db field "datetime1" timestamp with time zone type without modifiers.
I want insert the None object from a python in this field and receiving:
`psycopg2.InternalError: failed to find conversion function from unknown to timestamp with time zone`

**Comment by dvarrazzo** [comment]
try using a placeholder like `%s::timestampz` in your query. It may work or it may reveal another cause for which it's not working.

**Comment by sergeychibunin** [comment]
Thank you.
I guess my way is another adapter for a type.
