### ISSUE TITLE
psycopg2 build - setting RPATH

### ISSUE THREAD

**Issue by sandeepthakakr** [psycopg/psycopg2#671]
Hi,
We installed psycopg2 using pip and then linked our application with it. But the application fails to load on Linux with the following error:
--

> **"_psycopg.so: ELF load command address/offset not properly aligned"**

--
This error is specific to v2.7.3.2. We tried installing psycopg2 using pip --no-binary option and the application works fine but then we had set the LD_LIBRARY_PATH because _psycopg2.so didn't contain rpath. How can we pass this flag during pip so that rpath is set for that library?

**Comment by dvarrazzo** [comment]
Hello,

We are in the process of moving aside the binary build into a separate package and future psycopg versions will be source only, so I will not investigate in the "address not properly aligned error". Feel free to forward the problem to the pypa project (https://github.com/pypa/manylinux/) if you are interested in having it solved.

psycopg, and in general Python, relies on the operative system to find the shared libraries it needs. If the libpq is in a standard lib directory you shouldn't need setting `LD_LIBRARY_PATH`.

What is the error you get after installing psycopg from source? Where are the libraries mentioned in the error?
