### ISSUE TITLE
conn.isolation_level not working as expected

### ISSUE THREAD

**Issue by frn123** [psycopg/psycopg2#672]
conn.isolation_level does not change if setting it to ISOLATION_LEVEL_AUTOCOMMIT .

See the attached test case and output:

Default
('read committed',)
None

Read commited
('read committed',)
1

Read uncommited
('read uncommitted',)
4

Autocommit
('read committed',)
4  <--- this should be 0!

Serializable
('serializable',)
3

[test.txt](https://github.com/psycopg/psycopg2/files/1707463/test.txt)

**Comment by dvarrazzo** [comment]
Autocommit as an isolation level is a design error of the early psycopg days.

Please avoid using AUTOCOMMIT with isolation_level; use the `connection.autocommit` attribute instead to read and write.

**Comment by frn123** [comment]
This did work as expected in the 2.4.x versions as expected. So it should really be either fixed or removed, otherwise it will lead to data loss or corruption for other people too.

At the very least there should be a scary warning that it should be used.
