### ISSUE TITLE
pip install --no-binary

### ISSUE THREAD

**Issue by PeterSlickers** [psycopg/psycopg2#673]
The following command is not working for me:
    pip install --no-binary psycopg2  

Instead, I had to use this command:
  pip install --no-binary psycopg2 psycopg2

The option '--no-binary' requires a mandatory argument, which specifies on which (of potentially several) packages it should act. 'pip install -help' has more explanations on this:
   --no-binary <format_control>
    Do not use binary packages. Can be supplied multiple times, and each time adds to the existing 
    value. Accepts either :all: to disable
    all binary packages, :none: to empty the set, or one or more package names with commas between 
    them. Note that some packages are tricky to compile and may fail to install when this option is used on 
    them.

**Comment by dvarrazzo** [comment]
Thank you for reporting. I've fixed the example in the docs. Is the wrong usage advertised anywhere else?
