### ISSUE TITLE
arrays sometimes converted to nested lists

### ISSUE THREAD

**Issue by beldaz** [psycopg/psycopg2#676]
I have a table of the form:
```
CREATE TABLE foo (
    my_code varchar PRIMARY KEY,
    x double precision[],
    y double precision[]
);

CREATE TABLE bar(
    my_code varchar PRIMARY KEY REFERENCES foo,
    x double precision[],
    y double precision[],
    err double precision[],
    desc varchar
)
```
I use pyscopg2 to insert data into this table quite happily. Note that the arrays x, y and err can be ~1000 elements.  The problem is when I try to read this data. I was using code of the form:
```
import pandas as pd
import psycopg2, psycopg2.extras
conn_str = "..."
conn = psycopg2.connect(conn_str, cursor_factory = psycopg2.extras.DictCursor)

def get_density(code):
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT F.x, F.y, B.y AS newy, B.err 
            FROM Foo F, Bar B
            WHERE F.my_code = %s
            AND F.my_code=B.my_code
        """, [code])
        row=cursor.fetchone()
        df = pd.DataFrame(data={'x': row['x'], 
                                'y':  row['y'],
                                'newy': row['newy'], 
                                'err': row['errr'] })
    conn.commit()
    return df
```
But I have various type errors when I used the retrieved data. Ultimately I tracked this down to the second two arrays (`newy` and `err`) not being lists of floats, but rather lists of lists of floats. I see no reason for why this should be so. Is this a bug?

At present my workaround is to conditionally flatted each of the arrays with
```
import itertools

def flatten(l):
    if len(l) >0 and isinstance(l[0], list):
        return list(itertools.chain.from_iterable(l))
    else:
        return l
```

**Comment by dvarrazzo** [comment]
What do that data look like in psql? Or in Python if you cast is as text, i.e. `B.y::text AS newy`?

**Comment by beldaz** [comment]
Annoyingly I can't reproduce this with a simple synthetic example. I'll try to get the real data examples later today.

**Comment by beldaz** [comment]
Here is the original output from
```
with conn.cursor() as cursor:
    cursor.execute("""
        SELECT B.y
        FROM Bar B
        WHERE B.my_code = %s
    """, ['weird'])
    row=cursor.fetchone()
    print(row['y'])
```

[printed_array.txt](https://github.com/psycopg/psycopg2/files/1730375/printed_array.txt)

**Comment by beldaz** [comment]
Here is the output when I change to `SELECT B.y::text ...`
[printed_cast_array.txt](https://github.com/psycopg/psycopg2/files/1730386/printed_cast_array.txt)

**Comment by beldaz** [comment]
Here is the output when I change to ```SELECT array_to_string(B.y, ',', '*') ...```
[printed_array_to_string.txt](https://github.com/psycopg/psycopg2/files/1730393/printed_array_to_string.txt)

**Comment by beldaz** [comment]
Using PostgreSQL 10 from Docker container `postgres:10`
```
SELECT version()
PostgreSQL 10.2 (Debian 10.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit
```

And psycopg2 installed recently via pip in another Docker container:
```
print(psycopg2.__version__)
2.7.4 (dt dec pq3 ext lo64)
```

**Comment by beldaz** [comment]
Ahh, but output from psql looks like:
```
 {{2.20751909662576},{2.20679071024511},{2.20615506273571},{2.2055910715332},{2.
20507756148068},{2.20459435596551},{2.20412336646322},{2.20364958013081},{2.2031
618420891},{2.20265334228114},{2.20212174686242},{2.20156895755458},{2.201000532
12516},{2.20042484573123},{2.19985210697606},{2.19929335742568},{2.1987595765431
},{2.19826098783408},{2.19780662274576},{2.19740415504621},{2.19705997866427},{2
.19677947299938},{2.1965673849541},{2.19642825612809},{2.1963668334181},{2.19638 ...
```
and ```SELECT array_ndims(y) FROM Bar ...``` gives me 2. So my insert code must be passing in arrays of the wrong shape, and Postgres is not caring that they are not exactly of the schema I declared.

So, not a psycopg bug.

**Comment by dvarrazzo** [comment]
Thought so :stuck_out_tongue:
