### ISSUE TITLE
Preserving the JSON structure/order as returned by the server

### ISSUE THREAD

**Issue by dratchkov** [psycopg/psycopg2#680]
I think the structure and filed order should be preserved as returned by the server.
In my particular case I have a query that uses row_to_json, e.g.:

SELECT id,time,row_to_json(row(data#>'{data1}',data#>'{data2}',data#>'{data3}',data#>'{data1}' < data#> '{data2}')) AS data 
FROM table
The server would nicely order the json {"f1": "66", "f2": "108", "f3": null, "f4": false }, but then the json typecaster reorders it as { "f4": false, "f2": "108", "f3": null, "f1": "66" }.

It would be nice if the typecaster uses OrderedDict instead of dict, or at least there should be some way to override the default dict if needed.

In my case, the data will be parsed by a human first, so keeping the order of the fields, while not mandated, would greatly improve the user experience.

Here is what changed to _json.py.

```diff
@@ -28,13 +28,14 @@
 # License for more details.
 
 import sys
+import collections
 
 from psycopg2._psycopg import ISQLQuote, QuotedString
 from psycopg2._psycopg import new_type, new_array_type, register_type

@@ -178,7 +190,7 @@
     def typecast_json(s, cur):
         if s is None:
             return None
-        return loads(s)
+        return loads(s, object_pairs_hook=collections.OrderedDict)
 
     JSON = new_type((oid, ), name, typecast_json)
     if array_oid is not None:
```

**Comment by dratchkov** [comment]
```
@@ -28,6 +28,7 @@
 # License for more details.
 
 import sys
+import collections
 
 from psycopg2._psycopg import ISQLQuote, QuotedString
 from psycopg2._psycopg import new_type, new_array_type, register_type
@@ -189,7 +190,7 @@
     def typecast_json(s, cur):
         if s is None:
             return None
-        return loads(s)
+        return loads(s, object_pairs_hook=collections.OrderedDict)
 
     JSON = new_type((oid, ), name, typecast_json)
     if array_oid is not None:
```

**Comment by dvarrazzo** [comment]
Thank you but the builtin configuration is fine doing the simplest possible thing. You can configure your application to use the typecaster of your choice as explained in the documentation.
