### ISSUE TITLE
[2.7.4] Can't install/build psycopg2 on Solaris 11.3

### ISSUE THREAD

**Issue by danowar2k** [psycopg/psycopg2#681]
Base vagrant box:
https://app.vagrantup.com/heavybeans/boxes/solaris11-minimal-server

Command:
`CC=gcc pip install psycopg2`

Result:
[pipinstall.txt](https://github.com/psycopg/psycopg2/files/1752179/pipinstall.txt)

Installed Solaris Packages:
[pipout.txt](https://github.com/psycopg/psycopg2/files/1752173/pipout.txt)

Installed Pip packages:
[pkgout.txt](https://github.com/psycopg/psycopg2/files/1752174/pkgout.txt)

**Comment by danowar2k** [comment]
Anything else needed as input?

**Comment by danowar2k** [comment]
I just successfully installed psycopg2 2.7.3, so this is a problem specific to 2.7.4.

The only thing strange was I had to first create a link:
ln -s /usr/bin/gcc /usr/bin/cc

Or otherwise even if I tell pip where gcc is (CC=gcc) at the end the build failed because it still tried to use cc.

**Comment by danowar2k** [comment]
Hmm... Does this commit here solve the problem?

https://github.com/psycopg/psycopg2/commit/f766d90704b03cbe277e3fd4b4153d892960f135

**Comment by dvarrazzo** [comment]
Indeed this was fixed in #677.
