### ISSUE TITLE
There's no way to build 32Bit version of psycopg2.so when used Postgres is 64Bit

### ISSUE THREAD

**Issue by danowar2k** [psycopg/psycopg2#683]
I'm stuck with Solaris 11.3 at the moment. The python libraries on Solaris are mostly 32Bit libraries. My self compiled tools have up to this point been compiled with 64Bit. I use the 64Bit Solaris binaries from Postgres.
Therefore when I install psycopg2 (2.7.3, because 2.7.4 has other problems at the moment), it builds 64Bit libraries because it detects that Postgres is 64Bit.

But using the python interpreter with
`help('psycopg2')`
I then get an ELF64 error, obviously (?) because 32/64Bit python shouldn't be mixed (?)

It seems there is no way to tell pip or whatever I use to build 32Bit libraries. Or is it?

**Comment by dvarrazzo** [comment]
Obviously the python binary and the postgres library must have the same architecture. If you went all the way to build Python yourself you may build the libpq with the same architecture as well.

**Comment by danowar2k** [comment]
I thought as much, but had to ask...ah well, back to building 32Bit tools.
