### ISSUE TITLE
Best way to test exceptions

### ISSUE THREAD

**Issue by PythonDevOp** [psycopg/psycopg2#687]
Hello!

I am not quite sure how to explain, but when trying to use Python's `unittest`, I am unable to figure out how to test that exceptions are actually being thrown. I see in my logs an exception is thrown, but cant assert one.

Here is a brief example:
```
import unittest
import psycopg2
import logging


def pull_pg_data(conn, cursor, first, last):
    try:
        cursor.execute('SELECT first_name, last_name, email, street FROM user_data WHERE first_name =%s AND last_name=%s',(first, last))
    except psycopg2.OperationalError as msg:
        logging.error(msg)
        raise
    conn.commit()
    result = cursor.fetchall()
    return result


class SampleTestCases(unittest.TestCase):
    def setUp(self):
        try:
            self.conn = psycopg2.connect(dbname='postgres', user='postgres', host='localhost', port=5432,
                                         connect_timeout=10)
        except psycopg2.OperationalError as msg:
            logging.critical(msg)
            raise
        self.conn.autocommit = True
        self.cursor = self.conn.cursor()
        self.cursor.execute('DROP TABLE IF EXISTS user_data', [])
        self.cursor.execute('CREATE TABLE user_data (first_name TEXT, last_name TEXT, email TEXT, street TEXT)', [])
        self.cursor.execute("INSERT INTO user_data(first_name, last_name, email, street) VALUES('someFirstName', 'someLastName', 'some@example.com', '123 road')",[])

    def test_pull_pg_data_fail(self):
        conn = psycopg2.connect(dbname='foo', user='postgres', host='localhost', port=5432, connect_timeout=10)
        cursor = conn.cursor()
        self.assertRaises(psycopg2.OperationalError, pull_pg_data, conn, cursor, 'someFirstName', 'someLastName')


if __name__ == '__main__':
    unittest.main()
```

I would expect the test to pass (an exception IS raised), because the database `foo` does not exist. However, I don't get that. I only get the logged message `psycopg2.OperationalError: FATAL:  database "foo" does not exist`.

What is the best way to test things like `ProgrammingError`, `DatabaseError` or `OperationalError`?

**Comment by dvarrazzo** [comment]
Pretty much all psycopg errors derive from [DatabaseError](http://initd.org/psycopg/docs/module.html#psycopg2.DatabaseError), you can check the inheritance diagram, so you can catch that to get all of them.

**Comment by PythonDevOp** [comment]
Im not sure this answer's the question. In my test above, the assertion does not pass if an error is thrown (no DB exists). Am I testing this properly?

**Comment by dvarrazzo** [comment]
This is a psycopg bug tracker, not an unittest tutorial. Please read the documentation for your testing package.
