### ISSUE TITLE
Can't pickle psycopg2.extensions objects

### ISSUE THREAD

**Issue by decaz** [psycopg/psycopg2#688]
I'm using SQLAlchemy and some exceptions are raised with `psycopg2.extensions` objects included. But I can't pickle these exceptions due to impossibility of pickling such objects.

```python
import pickle

import psycopg2.extensions

obj = psycopg2.extensions.Binary(b'Test')
pickle.dumps(obj)
```
raises `TypeError: can't pickle psycopg2.extensions.Binary objects`

The same with `Boolean`, `Float`, etc.

**Comment by dvarrazzo** [comment]
I don't think any psycopg exception is raised with adapters attached. Can you make an example?

Adapters are not supposed to be pickled, they only work correctly in conjunction with their connection and the connection cannot be pickled.

**Comment by decaz** [comment]
```python
import pickle

import sqlalchemy as sa

url = 'postgresql://user:pass@host/test_db'
engine = sa.create_engine(url, echo=True)
connection = engine.connect()
metadata = sa.MetaData()
table = sa.Table('test_table', metadata,
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('data', sa.LargeBinary),
)
metadata.create_all(engine)

try:
    engine.execute(table.insert(), {'id': 'invalid_integer', 'data': b'test'})
except Exception as exc:
    pickle.dumps(exc)
```
gives `TypeError: can't pickle psycopg2.extensions.Binary objects`.

**Comment by dvarrazzo** [comment]
This is either a sqlalchemy problem - they shouldn't attach an object which is not pickleable to the exception, or yours: you assume sqlalchemy exceptions are pickleable when they are not. You should have a chat with them to understand what is the case.

As far as psycopg is concerned psycopg exceptions are pickleable (but they lose the reference to the cursor, which is not pickleable, so e.g. `diag` will be empty), the adapters are not and there is no plan to make them so.
