### ISSUE TITLE
wrong ELF class on mod_wsgi

### ISSUE THREAD

**Issue by asztalosdani** [psycopg/psycopg2#690]
Hi,

I am trying to deploy a flask server with peewee and psycopg2 on mod_wsgi. When importing psycopg2 from console it runs ok, but when the mod_wsgi runs it, this error shows up:
`ImportError: /home/sysadm/customizer/venv/local/lib/python2.7/site-packages/psycopg2/_psycopg.so: wrong ELF class: ELFCLASS32`

**Comment by dvarrazzo** [comment]
Probably a mix between 32/64 bits architectures on your system. Nothing we can solve for you.
