### ISSUE TITLE
JSONB to dict conversion truncating floating numbers

### ISSUE THREAD

**Issue by TDRR** [psycopg/psycopg2#693]
I have a JSONB column storing JSON identical to the following: 

<pre>
'field': [[0.48161993769470407, 0.4881240911294<b>2318</b>], [0.845482885837<b>55493</b>, 0.5729520320892334]]
</pre>

When querying this with psycopg2, I get the following rounded/truncated dict

<pre>
`'field': [[0.48161993769470407, 0.4881240911294<b>232</b>], [0.845482885837<b>5549</b>, 0.5729520320892334]]`
</pre>

Is this a limitation of the built-in json adapter, psycopg2, or something else?

I'd be willing to help on a fix.

PS. The High precision is important to my project.

`select version();` returns `PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623`

`psycopg2 version 2.7.3`

**Comment by dvarrazzo** [comment]
It is whatever the default behaviour of the json adapter provides. What you see is Python rounding.

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 

>>> print repr(0.48812409112942318)
0.4881240911294232
```

The json adapter is heavily customizable: if you need absolute precision you can convert json floats into `Decimal` objects: see [the docs about json adaptation](http://initd.org/psycopg/docs/extras.html#json-adaptation):

```
>>> loads = lambda x: json.loads(x, parse_float=Decimal)
>>> psycopg2.extras.register_default_jsonb(loads=loads)
>>> cur.execute("""select '{"num": 0.48812409112942318}'::jsonb""")
>>> cur.fetchone()[0]
{u'num': Decimal('0.48812409112942318')}
```
