### ISSUE TITLE
Generic connection failure callback function

### ISSUE THREAD

**Issue by tzachshabtay** [psycopg/psycopg2#698]
Hi, I couldn't find a way to attach a generic failure callback function on the connection object, that I can hook up to in order to get all database errors in the application (assuming I'm using a single connection).

Something like this, for example:

```
connection = psycopg2.connect(connection_string)
connection.on_error = on_db_error

def on_db_error(error_message):
    print error_message
    print traceback.format_exc()
```

Is there some generic mechanism like this? If not, can one be added?
Thanks.

**Comment by dvarrazzo** [comment]
No, but it's no problem for you to subclass the connection/cursor and do it yourself.

**Comment by tzachshabtay** [comment]
@dvarrazzo can you post an example on how to achieve that?
Thanks.
