### ISSUE TITLE
Enhance copy_from method to deal with auto increment column 

### ISSUE THREAD

**Issue by spencerpomme** [psycopg/psycopg2#702]
When a table has a auto increment column, then the copy_from fails.

For example, the table in db is:
id | col1 | col2

The csv file to be inserted is:
col1 | col2

if do:
cursor.copy_from(file, 'tablename', sep=',')

Then the columns will skew on column to the left, and exception will raise when col1 and col2 have different data type(good case) or just silently write wrong data!.

It's a functionality enhancement proposal.

**Comment by fogzot** [comment]
ALready there:
```
cursor.copy_from(file, 'tablename', sep=',', columns=('col1', 'col2'))
```

Read The Fine Manual.

**Comment by spencerpomme** [comment]
Thank you for your reply, I must have overlooked it with extra carelessness.😑

**Comment by randomseed42** [comment]
Does this behavior changed? Because I'm encountering UniqueViolation error at psycopg2 v2.9.10. Below is a minimal reproduction code:

```python
from io import StringIO

import psycopg2

with psycopg2.connect(
    host='localhost',
    port='5432',
    user='postgres',
    password='postgres',
    dbname='postgres',
) as conn:
    with conn.cursor() as cur:
        cur.execute('CREATE SCHEMA IF NOT EXISTS test_schema')
        cur.execute('CREATE TABLE IF NOT EXISTS test_schema.test_table (id SERIAL PRIMARY KEY, name TEXT)')
        conn.commit()

        cur.execute('SET search_path TO test_schema')

        data_1 = '1,Alice\n2,Bob\n'
        cur.copy_from(StringIO(data_1), 'test_table', columns=('id', 'name'), sep=',')
        conn.commit()

        breakpoint()

        data_2 = 'Charlie\nDavid\n'
        cur.copy_from(StringIO(data_2), 'test_table', columns=('name',), sep=',')
        conn.commit()
        
# psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "test_table_pkey"
# DETAIL:  Key (id)=(1) already exists.
# CONTEXT:  COPY test_table, line 1
```

**Comment by dvarrazzo** [comment]
> Has this behavior changed?

No. in `data_1` you insert values without increasing the counter. The example you posted has never worked, even if you try in psql.

```
# create table test_table (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE

# insert into test_table (id, name) values (1, 'Alice'), (2, 'Bob');
INSERT 0 2

# insert into test_table (name) values ('Charlie');
ERROR:  duplicate key value violates unique constraint "test_table_pkey"
DETAIL:  Key (id)=(1) already exists.
```

if you insert values manually in the id field the counter will not be updated. See in #1782 how to fix it.
