### ISSUE TITLE
Documentation Problems: Licence Missing & No Source Links

### ISSUE THREAD

**Issue by GadgetSteve** [psycopg/psycopg2#704]
The documentation at http://initd.org/psycopg/docs/ makes no mention of the licence - this is a problem in some contexts because some _legal type_ people search for licence in the documentation and if they don't find it say that the whole package cannot be used.

I also noticed that there is no link to the source repository https://github.com/psycopg/psycopg2 in the documentation which also gives problems with ascertaining the licence a problem and knowing where to raise a ticket such as this.

**Comment by dvarrazzo** [comment]
- If you are more lawyer than us, please propose a merge request with the changes you suppose correct.
- If you are less lawyer than us, then you are fine.
- The place to submit issues is probably best found by googling "psycopg issue" than looking in the docs. However, again, if you feel the docs are missing something you know the answer please propose a patch. The state of the docs is currently satisfactory for the docs authors: if you don't think so please specify how.
