### ISSUE TITLE
Can't extract interval as string

### ISSUE THREAD

**Issue by crystalneth** [psycopg/psycopg2#707]
I'm trying to use postgresql to convert an interval to an ISO string.

```
        cur = self.conn().cursor()
        cur.execute("SET INTERVALSTYLE='iso_8601'")
        cur.execute("SELECT interval '2 hours'")
        iso_interval = cur.fetchone()
```

Throws an error: ValueError: invalid literal for int() with base 10: 'PT2H'

Any other format returns a python interval, not a string.

The postgresql TO_CHAR requires an explicit format and does not support ISO.

For one, the output above seems like a bug. Second, is there a supported way to accomplish this?

**Comment by crystalneth** [comment]
Ok, I dug in and figured out a way to do this. Leaving this bug open as I don't think a ValueError should be thrown in the above case.

For future reference, this forces the value to be processed as text:

```
        cur = self.conn().cursor()
        cur.execute("SET INTERVALSTYLE='iso_8601'")
        cur.execute("SELECT (interval '2 hours')::text")
        iso_interval = cur.fetchone()
```

**Comment by dvarrazzo** [comment]
Raising `psycopg2.NotSupportedError` now. We may add parsing iso_8601 intervals in the future, but there is no huge pressure for it, as this is the first time this issue is reported in ~18 years.
