### ISSUE TITLE
Occupy memory too large and execute too slow

### ISSUE THREAD

**Issue by kelent** [psycopg/psycopg2#709]
I am trying to use psycopg2 to connect to a Postgresql. My purpose is to use "SELECT" to obtain some data and save it to local. However, the process is too slow. The data I need is around several million rows, and it seems to stuck in the "execute" code. Moreover, I try a much smaller dataset which is around 60mb large, and I only select one column from it, the memory which python occupied goes up to  5,000 mb, and it seems still stuck in the "execute" code. 

My code is similar to the following, and I have try both server-side cursor and local cursor, which shows no different.

```
import psycopg2

rows=[]

conn = psycopg2.connect(database="...", user="...", password="...", host="...", port="5432");
cur = conn.cursor("pCursor")
cur.itersize=100000
cur.execute("SELECT column1 FROM table_name;")

for row in cur:
    rows.append(row)

cur.close()
conn.close()
```

**Comment by dvarrazzo** [comment]
Use a named cursor with a smaller `itersize`. Try with 10, 100, 1000, until you get the right trade-off between number of roundtrip and client-size memory.

**Comment by fogzot** [comment]
Also, you're stuffing all the rows in memory (your `rows` list). If you don't want to use memory just use a small `itersize` and _save the data to disk while you fetch it_.
