### ISSUE TITLE
issue of format string parsing with `psycopg2.extras.execute_batch()`

### ISSUE THREAD

**Issue by OXPHOS** [psycopg/psycopg2#710]
I am not sure whether it is designed this way or I did something wrong.

I have some python lists in a dictionary:
```
files = {file1': [['a', 1], ['b', 2]], 
        'file2': [['a', 10], ['b', 20]], 
        'file3': [['a', 100], ['b', 200]]}
```
And I am trying to dump the lists to different tables in psql with `psycopg2`. What I am doing is:

```
for (key, val) in files.items():
     cur.execute("""
          CREATE TABLE %s (
              col1 text PRIMARY KEY,
              col2 integer) 
          """ % key)

   mydict = map(lambda x : {'tbname': key, 'col1': x[0], 'col2': x[1]}, val)

   query = """ INSERT INTO %(tbname)s VALUES (%(col1)s, %(col2)s)"""
   psycopg2.extras.execute_batch(cur, query, mydict)
   conn.commit()
```

I could successfully create the table, but for the `execute_batch` line I got error:

```
psycopg2.ProgrammingError: syntax error at or near "'file1'"
LINE 1:  INSERT INTO 'file1' VALUES...
```

The `' '` around the table name was preventing accessing the table.

I also tried `UPDATE %(tbname)s` with `psycopg2.extras.execute_batch()` so I guess it is the problem witht he method.

**Vesrions:**
 `psycopg2`: `2.7.4`
`python`: `3.6.5`

**Comment by OXPHOS** [comment]
UPDATE: I found a solution:

`query = """INSERT INTO %s""" % key + """VALUES (%(col1)s, %(col2)s)"""`

However, I am still curious whether the way I mentioned above is achievable.

**Comment by dvarrazzo** [comment]
No. The variable parts must be values, not identifiers.
