### ISSUE TITLE
Inserting a floating point number as a part of a jsonb field can come back as an integer

### ISSUE THREAD

**Issue by Rovanion** [psycopg/psycopg2#717]
Say that we have two tables, one contains a json and the other a jsonb column.

```sql
     create table example_jsonb (value jsonb);
     create table example_json (value json);
```

We then insert the same floating precision value held in a json object into the two:

```sql
    insert into example_jsonb values ('{"number": 2.561422288066971e+16}');
    insert into example_json values ('{"number": 2.561422288066971e+16}');
```

Selecting the two tables then gives us two different representations for the same value, different but representing the exact same number:

```sql
    select * from example_json;
                   value
    -----------------------------------
     {"number": 2.561422288066971e+16}
    
    select * from example_jsonb;
                 value
    -------------------------------
     {"number": 25614222880669710}
```

This within itself is not an issue. Where it becomes an issue is in how this then get read into Python and the mismatch between the exactness of the JavaScript and Python number types. Even though the two have exactly the same data/value type in the database

```sql
    select jsonb_typeof(value->'number') from example_jsonb;
     jsonb_typeof
    --------------
     number
    
    select json_typeof(value->'number') from example_json;
     json_typeof
    -------------
     number
```

they end up read as different types in Python. I'll first list all the setup you will need to establish a connection to some database, it is more complex than what is minimally needed but it's what I've got lying around:

```
    import os
    from contextlib import contextmanager
    from collections import OrderedDict
    
    from psycopg2 import Error as SQLError
    from psycopg2.pool import ThreadedConnectionPool
    from psycopg2.extras import RealDictCursor
    
    connectionPool = None
    
    def initializePool(overrides={}):
      # First merge the default conf with any given environment variables and overrides.              
      settings = {
          **{key: os.environ.get(key)
             for key in ["DB_PASSWORD", "DB_USER", "DB_NAME", "DB_HOST"]
             if os.environ.get(key)},
          **overrides
      }
      description = ("dbname='{DB_NAME}' user='{DB_USER}' host='{DB_HOST}' "
                     "password='{DB_PASSWORD}'").format(**settings)
      return ThreadedConnectionPool(1, 10, dsn=description, cursor_factory=RealDictCursor)
    
    
    @contextmanager
    def getCursor():
      global connectionPool
      if not connectionPool:
        connectionPool = initializePool() #INSERT DB CONF HERE
      connection = connectionPool.getconn()
      try:
        yield connection.cursor()
        connection.commit()
      finally:
        connectionPool.putconn(connection)
    
    
    def runQuery(query, parameters=[]):
      try:
        with getCursor() as cursor:
          cursor.execute(query, OrderedDict(parameters))
          if cursor.description:
            return list(cursor.fetchall())
          else:
            return cursor.statusmessage
      except SQLError as e:
        print("Psycopg2 failed to execute query: ", e)
```

Then to the actual test:

```
    type(runQuery('select * from example_json;')[0][0]['number'])
    # => float
    type(runQuery('select * from example_jsonb;')[0][0]['number'])  
    # => int
```

The issue with this is that if you put in a number in a jsonb field in Postgres through psycopg2 you can't be sure that you will get the same data type back out. I think it is it is reasonable to assume that you'd get out the same thing as that which you put in when interacting with the database. I myself may know of this quirk now, but another programmer working on the code at a later point may not.

Is it even feasible to solve this problem given that Postgres masks the data type as merely a number? Though it doing so may be the right thing to do given that there is no more precise data type for a number in JavaScript. Does the database adapter have anything to go on beyond that the value should be a "number"?

It may be that this issue is impossible to solve on your side. But here it is either way.

**Comment by fogzot** [comment]
`json` and `jsonb` types are black boxes. You put a *string* in, you get a *string* out. Unless you explicitly create the string using json operators in the SQL query you have absolutely no control on what PostgreSQL decides to send back. So, unfortunately, this is impossible to solve on psycopg2 side.

**Comment by dvarrazzo** [comment]
This is not even a problem with the interaction between Python and postgres: It's just postgres doing some assumption/rounding:

```
=# select '{"number": 2.561422288066971e+16}'::jsonb;
             jsonb             
-------------------------------
 {"number": 25614222880669710}
(1 row)
```

Python passes down to the json library pretty much what it receives from the database. If there was something bad there it might be customizable as explained in the docs about json adaptation. However this is a purely postgres artifact of the jsonb type. The json type (which is just a blob of text) doesn't show the same rounding:

```python
In [2]: import psycopg2
In [3]: cnn = psycopg2.connect("")
In [4]: cur = cnn.cursor()
In [5]: cur.execute("""select '{"number": 2.561422288066971e+16}'::jsonb""")
In [6]: cur.fetchone()[0]
Out[6]: {u'number': 25614222880669710}

In [7]: cur.execute("""select '{"number": 2.561422288066971e+16}'::json""")
In [8]: cur.fetchone()[0]
Out[8]: {u'number': 2.561422288066971e+16}
```

You should hear from the postgres guys. In my experience however, in json, if you want absolute precision with numbers, you better store them as strings.
