### ISSUE TITLE
Split packages for explicit binary or source installation

### ISSUE THREAD

**Issue by tysonclugg** [psycopg/psycopg2#719]
Consider renaming the `psycopg2` package to `psycopg2-nobinary`, and introducing a new `psycopg2` [namespace only package](https://packaging.python.org/guides/packaging-namespace-packages/), optionally with the following `extras_require`:
```python
extras_require={
    'nobinary': ['psycopg2-nobinary'],
    'binary': ['psycopg2-binary'],
}
```
Ensure that both the `psycopg2-nobinary` source package and the `psycopg2-binary` wheel package both have `psycopg2` in their `install_requires`.  In the README, highlight the need to install either `psycopg2-binary` or `psycopg2-nobinary` to users (with the appropriate caveats), and for libraries to only depend on `psycopg2`.

The above changes will:
 - [Not introduce segfaults](https://github.com/psycopg/psycopg2/issues/674#issuecomment-364778620).
 - Prevent [mistakes using the `--no-binary` arguments with pip](https://github.com/psycopg/psycopg2/issues/673).
 - Prevent [namespace conflicts experienced as a result of both `psycopg2` and `psycopg2-binary` being installed](https://github.com/psycopg/psycopg2/issues/674#issuecomment-371115810).
 - Make `psycopg2-binary` [satisfy the `psycopg2` dependency](https://github.com/psycopg/psycopg2/issues/674#issuecomment-375518203) (at least indirectly).
 - Allow other packages to include `psycopg2` in their `install_requires` without forcing either source or binary installation.
 - Force users to [explicitly opt in or opt out of using wheels](https://github.com/psycopg/psycopg2/issues/701#issuecomment-379714441).
 - Not burden users who have changed their `psycopg2` requirement to `psycopg2-binary`.

The subset of users who upgrade without having either `psycopg2-nobinary` or `psycopg2-binary` in their requirements will find that nothing works, rather than [introducing random segfaults on production server environments](https://github.com/psycopg/psycopg2/issues/701#issuecomment-380860117).  The prominent message in the README will provide a clear answer as to what should be done.

Idea inspired by [a comment](https://github.com/psycopg/psycopg2/issues/674#issuecomment-384318290) on #674.

**Comment by tysonclugg** [comment]
There's a slight variation on this suggestion, where the `psycopg2` package isn't a namespace package, but instead imports functionality from either `psycopg2-nobinary` or `psycopg2-binary` (and throws a helpful error/warning if both are installed).  This would obviate the need for an overly prominent message in the README.

**Comment by dvarrazzo** [comment]
Can you provide a merge request to upgrade codebase, documentation, and build system?

**Comment by tysonclugg** [comment]
@dvarrazzo Do you have a preference between `psycopg2` being a namespace only package versus `psycopg2` importing functionality from the other packages?

**Comment by dvarrazzo** [comment]
My plan is to release 2.8 in a few weeks time. At the moment I'm struggling even just to restart the build system to build 2.7.5, which I would have liked to release tonight (and maybe still can).

FYI, 2.8 plans to support Python 2.7 and >= 3.4.

About the tradoff namespace only vs. other packages, I don't know.

Looking at [the example](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages), here we are talking about subpackages so I don't really see the schema applying to psycopg (well, I have a few ideas, but they are still filed under my "hacks" mental dir...)

**Comment by tysonclugg** [comment]
I'd love to help get a release out ASAP, but I'm busy with last minute GDPR compliance tasks.
If nobody gets to this first, I'll eventually attempt one or both suggested approaches and see how it works out.

**Comment by dvarrazzo** [comment]
@tysonclugg can I close this issue as we won't do it?

**Comment by dvarrazzo** [comment]
I guess so
