### ISSUE TITLE
execute_batch or executemany with SELECT statement

### ISSUE THREAD

**Issue by gabri94** [psycopg/psycopg2#720]
Hello, I have to run many SELECT statements on my postgres/postgis DB.
I would like to use some batch functionalities as the one in the title, but i discovered that they return only the result of the last query. Is there a way to receive the results from all the queries?

**Comment by dvarrazzo** [comment]
No, it's not possible with these function, and there isn't support in the libpq to return more than one result at time.

**Comment by nartes** [comment]
I think about the two following options:
- make a custom function with a cursor that will have inside for loop
- run insert statement with psycopg2.extras.execute_batch
  the overhead is that each complex queyr would involve adding of a new custom function
  into migration
- and afterwards fetch the result with a single execute statement
  the overhead is an additional table per query
Which one you advice to consider?

**Comment by n1000** [comment]
For simple SELECTs, where I was looking up a set of rows based on one column, I was able to do the following:

I replaced:
```python
    start_time = time.monotonic()

    # "One-at-a-time" SELECT based on an index
    #
    # user_ids_test_set is a previously looked up set of user IDs, in the form
    # of [(id1,), (id2,), (id3,)]
    #
    result1 = []
    for user_id in user_ids_test_set:
        db_cur.execute('SELECT * FROM user_info WHERE user_id = %s', user_id)
        result1 += db_cur.fetchall()

    end_time = time.monotonic()
    print('loop select took {} seconds'.format(end_time - start_time))

```
With:
```python
    start_time = time.monotonic()

    # Batch select, using IN
    #
    # user_ids_test_set is a previously looked up set of user IDs, in the form
    # of [(id1,), (id2,), (id3,)]
    #
    # The resulting sel_tuple is of the form ((id1, id2, id3, ..., idN),)
    sel_tuple = (tuple([x[0] for x in user_ids_test_set]),)
    db_cur.execute('SELECT * FROM user_info WHERE user_id IN %s', sel_tuple)
    result2 = db_cur.fetchall()

    end_time = time.monotonic()
    print('batched loop select took {} seconds'.format(end_time - start_time))

```

This dramatically improved performance in my use case (about 10-18x performance gain).

**Comment by Alexmhack** [comment]
I have the same issue where I want to execute multiple SELECT queries like,

```
SELECT websearch_to_tsquery('english', 'first'); SELECT websearch_to_tsquery('english', 'second'); SELECT websearch_to_tsquery('english', 'third'); # and so on ...
```

This is just simple SELECT statements without any update / insert so `execute_batch` throws error when using `fetchall()`


```
r = cur.fetchall()
psycopg2.ProgrammingError: no results to fetch
```


This is what I tried,

```
cursor.execute("PREPARE stmt AS SELECT websearch_to_tsquery('english', '$1')")

from psycopg2.extras import execute_batch

execute_batch(cursor, "EXECUTE stmt (%s)", [("expense",), ("more",), ("reverse",), ("snippet",), ("customer",), ("emails",), ("manager",), ("queryset",), ("query",), ("multiple",)])

cursor.execute("DEALLOCATE stmt")

[r for r in cursor.fetchall()]
---------------------------------------------------------------------------
...
----> 1 [r for r in cursor.fetchall()]

ProgrammingError: no results to fetch

```

Is there any workaround to this, like with [mysql-connector-python](https://github.com/mysql/mysql-connector-python/blob/0e84955ecfb53d3b477584557e8345c6427a1493/examples/multi_resultsets.py) module gives a `multi` argument in cursor,

```
operation = 'SELECT 1; INSERT INTO t1 VALUES (); SELECT 2'
for result in cursor.execute(operation, multi=True):
    ...

```

**Comment by dvarrazzo** [comment]
@Alexmhack `execute_values()` support a `fetch` parameter. If that's not enough just look at the source for the `execute_batch()` function and customise it. It's not that difficult.
