### ISSUE TITLE
Segfault in psycopg2 2.7.4 -> libcrypto 1.0.2n; any advice to get more details?

### ISSUE THREAD

**Issue by sphet** [psycopg/psycopg2#723]
We're seeing daily segfaults in a python app which is using psycopg2. One of the engineers has setup something that catches the segmentation fault details, but the backtrace only includes the following line:

Backtrace:
/home/buildmaster/buildbot/sandbox/lib/python3.5/site-packages/psycopg2/.libs/./libcrypto-1e9dee74.so.1.0.2n(+0x748be)[0x7f1780c408be]

Not a very good backtrace since there is only one line!

We're running Postgres on Ubuntu 16.04.3. Psycopg2 (2.7.4) is up  to date as is libcrypto (1.0.2n)

I'm generally a windows developer, so I wonder if anyone has any ideas on what I could do to get a better stack trace -- ie. what was psycopg doing, or what was actually being called in libcrypto?

**Comment by dvarrazzo** [comment]
It is a known problem with wheel packages (there are a few bugs open about it). Please install psychog from source. See the docs for details.
