### ISSUE TITLE
Process finished with error code 132 (interrupted by signal 4: SIGILL) for Python 2.7

### ISSUE THREAD

**Issue by DeliDouble** [psycopg/psycopg2#725]
I recently started working with databases and wanted to try and implement some python to do some of the work for me. A few colleagues recommended psycopg2, so installed the newest version (2.7.4). I am running Pycharm CE(at time of post 2018.1)  on an old MacBook primarily used for testing and auxiliary. with a Mid 2009 era 2.8GHz Core 2 Duo Intel processor about 8GB of ram.
I run my code and after about 10 lines it kicks out and gives the error in my title (Process finished with exit code 132 (interrupted by signal 4: SIGILL)). The weird thing is to verify i ran it on a newer computer and the error didn't happen. Is there a workaround or bug fix that I am not aware of?

**Comment by DeliDouble** [comment]
i tried using previous versions on the older computer but pycharm wouldn't accept them, might have been personal error(still new to pycharm). Newer Computer has 4.2 GHz Intel Core i7 and 16GB of RAM.

**Comment by dvarrazzo** [comment]
This doesn't seem a psycopg bug. If you manage to create a traceback showing it's somewhat related we can investigate.
