### ISSUE TITLE
Return PQhost of a connection.

### ISSUE THREAD

**Issue by Farit** [psycopg/psycopg2#726]
In our project, we are specifying connection string with the multiple hosts. It would be great if connection object would have a method which will return PQhost because we need to know to which host we are made a connection.

**Comment by dvarrazzo** [comment]
The same goes for [several informative functions](https://www.postgresql.org/docs/current/static/libpq-status.html) on the connection. We have some exposed on the connection, some not, in an inconsistent way. Maybe it would be useful to have an object similar to [Error.diag](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.Diagnostics) exposing everything the libpq knows about the libpq connection.

I'll give it a think for 2.8

**Comment by Farit** [comment]
Thanks. We will impatiently wait for the psycopg 2.8 ))

**Comment by dvarrazzo** [comment]
You may actually give a hand too either with the design or the implementation as well :P

Shall we expose an object as `connection.pgconn`, a class PGConnection which would have internally a pointer to the PGconn struct (likely a weakref to the psycopg connection, from which to get to the PGconn) and add an array of read-only properties and methods on it? Other ideas?

**Comment by dvarrazzo** [comment]
Closed via MR #787. Grazie Marco :)

**Comment by dvarrazzo** [comment]
Actually, reopening. Only `host` was implemented in #787, but I'd rather have the other informative functions implemented as well.

**Comment by dvarrazzo** [comment]
Merged to master. [Docs available here](http://initd.org/psycopg/docs/extensions.html#psycopg2.extensions.ConnectionInfo). Feedback welcome as there is still space for changes.
