### ISSUE TITLE
How to execute tests and check the results 

### ISSUE THREAD

**Issue by Steve888888** [psycopg/psycopg2#733]
Hi guys,
I try to run the tests but found the following results.I didnot find the instructions how to run the tests in the source files.
_ubuntu@lilun-db:~/psycopg2/tests$  python testutils.py "dbname=postgres host=xx.xx.xx.xx port=5432 user=postgres password=postgres"
Traceback (most recent call last):
  File "testutils.py", line 32, in <module>
    from .testconfig import dsn, repl_dsn
ValueError: Attempted relative import in non-package_

Thanks.

**Comment by dvarrazzo** [comment]
In short,

    make check

in longer, read [the docs](http://initd.org/psycopg/docs/install.html#running-the-test-suite).
