### ISSUE TITLE
ImportError: DLL load failed: The operating system cannot run %1

### ISSUE THREAD

**Issue by pbdanny** [psycopg/psycopg2#734]
Windows 7 32-bit
Python 3.6.3 Anaconda (32-bit)
psycopg2  2.7.4 (conda-forge)
psycopg2-binary 2.7.4 (pip)

Experience error when importing modules
"ImportError: DLL load failed: The operating system cannot run %1"

As error massage point to __init__.py at row 50 but no further clue.

**Comment by dvarrazzo** [comment]
I think you have [this problem](https://xkcd.com/1987/).

I can only suggest you to simplify your installation.

**Comment by huanfachen** [comment]
I solved this problem recently. FYI.

Windows 7 64-bit
Python 2.7 Anaconda
psycopg2 2.7.5 (conda-forge)

solution:
conda remove psycopg2 (remove it from conda)
download the win-psycopg2 package 2.6.2. Use easy-install to install it. Works.
link: https://stackoverflow.com/a/38124825/4667568

**Comment by peter-petrov** [comment]
We don't have this problem

https://xkcd.com/1987/

The reported issue is real. I am reporting it again today. This bug should be reopened.

https://stackoverflow.com/questions/64314141/psycopg2-importerror-dll-load-failed-while-importing-psycopg-the-operating

**Comment by dvarrazzo** [comment]
@peter-petrov 

**Conda is not supported by psycopg2.**

With this statement I mean, I have never heard of a single Conda representative getting in touch with us telling about a problem. Until such, if you have a bug with psycopg2 in conda, it is a conda bug, not a psycopg2 bug. The only distributions we support are the ones on PyPI.

**psycopg2 may be supported by Conda**

This is the right direction of the arrow. Is not like psycopg2 installs Conda for you. If it doesn't work, open a bug to Conda.
