### ISSUE TITLE
`async` is a keyword in Python 3.7

### ISSUE THREAD

**Issue by bit** [psycopg/psycopg2#737]
async has become a keyword in Python 3.7 and can not be used as an argument name . See https://mail.python.org/pipermail/python-dev/2017-March/147678.html

tests/test_async_keyword.py still uses the async keyword:

```
python3.7 tests/test_async_keyword.py
  File "tests/test_async_keyword.py", line 44
    self.conn = self.connect(async=True)
                                 ^
SyntaxError: invalid syntax
```

**Comment by Ge0** [comment]
Got the same problem here:

```python
    from .connection import connect, Connection, TIMEOUT as DEFAULT_TIMEOUT
  File "/home/ge0/.virtualenvs/mynah/lib/python3.7/site-packages/aiopg/connection.py", line 109
    self._conn = psycopg2.connect(dsn, async=True, **kwargs)
```

The `psycopg2.connect` API needs to be refactored.

**Comment by vsel** [comment]
Just use `async_`

**Comment by bit** [comment]
I opened this ticket regarding the use of async in the  test, not the use of the old api in other projects, that was added by @Ge0 as a comment. I also opened a pull request to update the test to use/test async_

**Comment by dvarrazzo** [comment]
`async_` is supported as alias for `async` both as connection parameter and as attribute.
