### ISSUE TITLE
Psycopg2-Binary not on PyPi for macOS and Windows (Python 3.7)

### ISSUE THREAD

**Issue by AlexanderNeilson** [psycopg/psycopg2#740]
Hi All, I am just wondering if there was an outstanding issue resulting in no python 3.7 wheels for psycopg2-binary for Windows i386 / i386_64 and for macOS?

Apologies for the many edits of the title of this, I am still getting used to my new keyboard on my mac (hence installing python 3.7 with homebrew).

Regards
Alexander

**Comment by rpkilby** [comment]
I also just ran into this. The workaround for me right now is to just force Homebrew to install Python 3.6

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
```

**Comment by AlexanderNeilson** [comment]
@rpkilby This fix will work for people running into this who don't want to install postgresql.

However I am hopefully finding out if there is an issue needing resolving (lack of available build machines, broken auto build script, other issue) that I can help with fixing.

Also as advised in @rgov linked issue #745 the "error" message is unhelpful in directing people to install psycopg2-binary even when that is the package failing. Hopefully I can provide a patch to improve this without too much further guidance but guidance still needed for the above root cause.

Regards
Alexander

**Comment by dvarrazzo** [comment]
Binary packages for Python 3.7 on OSX and Windows released.
