### ISSUE TITLE
whitespace in mogrify ARRAY return value

### ISSUE THREAD

**Issue by cjerdonek** [psycopg/psycopg2#743]
Hi, I noticed in one of my project's tests that in going from version 2.7.4 to 2.7.5, the spacing of `mogrify()`'s return value changed from `ARRAY[(1), (2)]` to `ARRAY[(1),(2)]` for a `params` value that was a list of tuples. (I'm guessing it would also happen for a list of numbers.)

However, when I looked at psycopg2's tests, I didn't see a test case for this. I'm guessing the spacing change is a result of this commit (https://github.com/psycopg/psycopg2/commit/098c00d73e193f09ce9589a6bb574f5833be714), but I don't know for sure. 

It seems like it would be good to add a test case for cases like this if one isn't already there. This would provide greater visibility into how the formatting of queries change from version to version.

**Comment by fogzot** [comment]
The formatting of queries is an implementation details no external code should depend on. As long as it is valid SQL your code should work.

**Comment by dvarrazzo** [comment]
The SQL generated is not part of the interface. You are testing for an implementation details that is not part of our contract: as such you have to be prepared to change your test accordingly - as we did ourselves, if you [look at the commit](https://github.com/psycopg/psycopg2/commit/098c00d73e193f09ce9589a6bb574f5833be714#diff-991eb476a8e005c2b2b390f469f1ec19) you refer to

There are plenty of tests and others are added routinely, but what they verify that certain Python arrays are transformed in the correct Postgres representation, and the other way around: this is the interface that we plan to keep consistent and correct. Whitespaces shouldn't matter to end users and we should be able to change them without too much bureaucracy around it.

**Comment by cjerdonek** [comment]
Okay. But for the record, I understand that the SQL isn't part of the interface. I wasn't asking that it not change or even suggesting that that be a bad thing. I was simply suggesting that you add a test for an iterable in the interests of the code itself and greater visibility into the code base, e.g. like you have for `Decimal`:
https://github.com/psycopg/psycopg2/blob/6becf0ef550e8eb0c241c3835b1466eef37b1784/tests/test_cursor.py#L102-L108

And yes, I did notice the change in [those lines](https://github.com/psycopg/psycopg2/commit/098c00d73e193f09ce9589a6bb574f5833be714#diff-991eb476a8e005c2b2b390f469f1ec19) when I posted the link to this issue, but those lines seem incidental to a test of something else (`test_adapt_9`) rather than testing `mogrify()` specifically (e.g. like `test_mogrify_decimal_explodes()` referenced above).

**Comment by dvarrazzo** [comment]
`test_mogrify_decimal_explodes` tested something else, [some ancient bug on Python 2.5](https://psycopg.lighthouseapp.com/projects/62710/tickets/7), not that a certain type is adapted in a specific way. It is a test *of* `mogrify()`, which in the past IIRC had a very different (and more buggy) code path than `execute()`: you are wrong thinking that it is a test about how `Decimal` is adapted. Likely there are dozen tests verifying that certain decimals roundtrip from Python to the database and back correctly, and none checking how decimals are specifically adapted.

**Comment by cjerdonek** [comment]
> you are wrong thinking that it is a test about how Decimal is adapted

Why this insistence that "you are wrong"? That's not what I was thinking at all. I was merely noting that the code already contains a test of `mogrify()` that passes a certain type. If you don't want to add a test like I'm suggesting, that's fine. It's up to you. But there's no need to put words into other people's mouths.
