### ISSUE TITLE
Named cursor is not closed when no query run

### ISSUE THREAD

**Issue by Tishka17** [psycopg/psycopg2#746]
1. We use stored functions in postgresql, that return named cursor as out paramter.
It has code like (it is not prodution code but shows an idea)
```sql
CREATE OR REPLACE FUNCTION list_myobj(
  OUT    o_rs     refcursor
) AS $$
BEGIN
   o_rs = 'result';
   OPEN o_rs FOR SELECT obj_name from myobj;
END
$$ language plpgsql;

```
We have many similar functions 

2. In python i call these functions and read the contents on `o_rs`.  Code is similar to
```python
with closing(conn.cursor()) as cursor:
  cursor.callproc("list_myobj")
  result = cursor.fetchone()
  with closing(self.dbo.cursor(result[0])) as cur2:
    return cur2.fetchall()
```

3. It worked on version 2.7.4 of psycopg2, but on 2.7.5 it breaks when several funcitons called in same connection. I got an exception
```
psycopg2.ProgrammingError: cursor "result" already in use
```

As i can see in changes made for #716, cursor is not closed when no query is ran, which is not correct.

**Comment by dvarrazzo** [comment]
I don't see how #716 is related to this. Or why you are using `closing`. Can you provide a failing test?

**Comment by Tishka17** [comment]
it does not matter if i use `closing(...)` or close cursor manually. 

In commit https://github.com/psycopg/psycopg2/commit/7aea6b846ef755b8cc0a67e42467e1923aba92cc (related to that issue) i see check `if (!self->query)`. I'm not sure, but probably there would be never any query in cursor, which was returned from a stored function. But at the same time it is not unused.

I'll try to prepare minimal example

**Comment by dvarrazzo** [comment]
Uhm, I think I understand what you mean. Probably the test to choose whether to `CLOSE` the cursor or not shouldn't be on if a query has been run, rather if consuming has been attempted.

**Comment by dvarrazzo** [comment]
Thank you very much: I'll try to work on it ASAP.
