### ISSUE TITLE
psycopg2 UserWarning, flying block (unclosed block)

### ISSUE THREAD

**Issue by marcvisconte** [psycopg/psycopg2#750]
I'm on a Red Hat vm.  I have installed a small virtual environment using venv.
pyscopg2 was installed using pip.
There is a UserWarning that gets posted on import that results in output that is badly formatted.
This shows up also in interactive mode:

```
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2 as dbapi
/opt/data/datalake_env/python_env/lib64/python3.4/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
>>>
```

The last line is the flying block:     """)

The code is in __init__.py :
```
# This is a wheel package: issue a warning on import
from warnings import warn   # noqa
warn("""\
The psycopg2 wheel package will be renamed from release 2.8; in order to \
keep installing from binary please use "pip install psycopg2-binary" instead. \
For details see: \
<http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.\
""")
```

Is there anything that can be done to fix this, short of my mangling the code?  :-D

**Comment by dvarrazzo** [comment]
I have no idea of what you mean, sincerely. And that warning is only temporary until 2.8 so I'm not overly fussed.

Closing the bug. If you have improvements send a MR (to [psycopg2-wheels](https://github.com/psycopg/psycopg2-wheels/blob/master/scripts/build-manylinux.sh#L35)).

**Comment by marcvisconte** [comment]
OK.  Thank you.  I just assumed I should report it here.  I guess I could just remove that warning from my install.  That should get rid of the text and the artifact.

**Comment by boussouira** [comment]
You can disable the warning wihtout editing files using:
```python
import warnings
warnings.filterwarnings("ignore", module="psycopg2")

```

**Comment by marcvisconte** [comment]
Thank you.  That's just what I needed.  It's not "psycoph2", but it's what I need to use it!
