### ISSUE TITLE
setup.cfg overrides static_libpq setting

### ISSUE THREAD

**Issue by omerfarukdogan** [psycopg/psycopg2#756]
I'm trying to install psycopg2 using pip with `static_libpq=1`. I have modified ~/.pydistutils.cfg and added these lines:

```
[build_ext]
static_libpq=1
```

After trying several times, I couldn't get this to work. After seeing `static_libpq=0` line in setup.cfg, I have figured out that my configuration is being overriden by it.

Can we remove this value from setup.cfg (leave it like `static_libpq=`) so that it is easier to change it, without manually downloading and editing setup.cfg?

**Comment by dvarrazzo** [comment]
[apparently no](https://travis-ci.org/psycopg/psycopg2/jobs/412977314)

**Comment by dvarrazzo** [comment]
Ah but the error is in `setup.py`, which assumes that's an integer. So maybe it can be done. Opening back.

**Comment by omerfarukdogan** [comment]
I have commented that line out and builds seem to be passing now. In setup.py:

```
if parser.has_option('build_ext', 'static_libpq'):
    static_libpq = int(parser.get('build_ext', 'static_libpq'))
else:
    static_libpq = 0
```

This case falls into else clause, meaning it will be 0 as default.

**Comment by dvarrazzo** [comment]
I will have to check what happens with that file, because if you package the project (`make sdist`) and check the `setup.cfg` file packaged, you will find it mangled by setuptools. Anyway I accept that the command line option should override the `.cfg`: I'll try to solve this issue, with your proposed patch or some other way.

**Comment by dvarrazzo** [comment]
Even fixing the `setup.py` with a patch like:

```diff
diff --git a/setup.cfg b/setup.cfg
index a5efdcf..0e64c87 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -20,10 +20,10 @@ mx_include_dir=
 # For Windows only:
 # Set to 1 if the PostgreSQL library was built with OpenSSL.
 # Required to link in OpenSSL libraries and dependencies.
-have_ssl=0
+have_ssl=
 
 # Set to 1 to statically link against the postgresql client library.
-static_libpq=0
+static_libpq=
 
 # Add here eventual extra libraries required to link the module.
 libraries=
diff --git a/setup.py b/setup.py
index 0241e24..d49d45e 100644
--- a/setup.py
+++ b/setup.py
@@ -579,12 +579,12 @@ else:
 define_macros.append(('PSYCOPG_VERSION', PSYCOPG_VERSION_EX))
 
 if parser.has_option('build_ext', 'have_ssl'):
-    have_ssl = int(parser.get('build_ext', 'have_ssl'))
+    have_ssl = int(parser.get('build_ext', 'have_ssl') or '0')
 else:
     have_ssl = 0
 
 if parser.has_option('build_ext', 'static_libpq'):
-    static_libpq = int(parser.get('build_ext', 'static_libpq'))
+    static_libpq = int(parser.get('build_ext', 'static_libpq') or '0')
 else:
     static_libpq = 0
 ```

building fails down the line with:

```
$ make
python setup.py build_ext --build-lib=/home/piro/dev/psycopg2/build/lib.2.7
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running build_ext
error: invalid truth value ''
Makefile:84: recipe for target '/home/piro/dev/psycopg2/build/lib.2.7/psycopg2/_psycopg.so' failed
make: *** [/home/piro/dev/psycopg2/build/lib.2.7/psycopg2/_psycopg.so] Error 1
```

On the other hand, `--static-libpq` can still be used from command line: that's not the use case that @omerfarukdogan wants to solve. On the third hand, `--static-libpq` seems broken - the library produced fails building against other libraries.

```
$ PYTHONPATH=`pwd`/build/lib.2.7 python -c "import psycopg2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/piro/dev/psycopg2/build/lib.2.7/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /home/piro/dev/psycopg2/build/lib.2.7/psycopg2/_psycopg.so: undefined symbol: GSS_C_NT_HOSTBASED_SERVICE
```

I have no big interest in fixing it overall, I don't know what would be used for. So closing it here with no action.
