### ISSUE TITLE
lbank missing float cast

### ISSUE THREAD

**Issue by JanPokorny** [psycopg/psycopg2#759]
Trying to fetch_markets with lbank gives the following error:

```
File "/usr/local/lib/python3.5/dist-packages/ccxt/async/lbank.py", line 144, in fetch_markets
    'min': math.pow(10, -precision['amount']),
TypeError: bad operand type for unary -: 'str'
```

Clearly the 'amount' field is a string, so it needs an explicit cast.

**Comment by dvarrazzo** [comment]
I don't think this is the right bug tracker.

**Comment by JanPokorny** [comment]
Shit, sorry for that. I got lost in my open tabs and accidentally posted it here instead of ccxt...
