### ISSUE TITLE
License for psycopg2

### ISSUE THREAD

**Issue by nrhy** [psycopg/psycopg2#762]
Hey there!

A firm I work for is looking to use psycopg2 and there have been questions around the GNU license. My question is, why differ from using the MIT or BSD licenses? Is there a particular reason for this?

Furthermore, what qualifies as modification? If we import psycopg2 and utilize its methods without changing any of the modules underlying functionalities - does that qualify as making a modification?

Apologies if this comes across as legal questions - I just imagine that GNU was selected for some of these reasons.

Thank you!

**Comment by dvarrazzo** [comment]
Psycopg is not LGPL, as such using it as a library without modification doesn't impose any constraint to the license of your project.

**Comment by sullyfischer** [comment]
@dvarrazzo could you please explain how come it's not LGPL? I'm looking to use it in a project that I'm going to release in MIT License, but am afraid because of the LGPL license you're using. 

https://github.com/psycopg/psycopg2/blob/master/LICENSE

**Comment by dvarrazzo** [comment]
Sorry, the above is a typo, I don't know what my fingers were thinking. It is LGPL, I think the "not" is a typo.

Being LGPL what I wrote after comes as a consequence: "such using it as a library without modification doesn't impose any constraint to the license of your project".

I'll amend the above, thank you for pointing out.
