### ISSUE TITLE
psycopg2.extras: register_inet, Inet to be deprecated - suggested actions

### ISSUE THREAD

**Issue by mzpqnxow** [psycopg/psycopg2#763]
Hello folks,

I use psycopg2 extensively and have had many cases where register_inet and the Inet class were very useful. I see in the documentation and warnings that they are deprecated.

I am wondering what the suggested behavior is for users to prepare for this deprecation. I've actually had these implemented in my own codebase (though in a not as feature complete way) for a while, so I can simply keep them as part of a package of my own, but if there's a future for something similar *within* psycopg2, it would be nice to know.

I'm also curious, why are they being deprecated? I realized they're relatively simple, but they don't seem to add a large amount of clutter to the codebase. Thanks!

**Comment by mzpqnxow** [comment]
FWIW, this is how I implement it today in my own code:

```
class Inet(object):
    # Simple class stub for doing text to INET type conversion in psycopg2
    def __init__(self, addr):
        self.addr = addr

def adapt_inet(address):
    """psycopg2 Adapter to typecast Python strings into INET types"""
    return AsIs("'%s'::inet" % address.addr)

# Register the adapter, call it on any INET type during/before insert
# You can use a simple comprehension if you are inserting an INET[]
register_adapter(Inet, adapt_inet)

def text_list_to_inet_list(addresses):
    """Make it nice and easy to adapt a list of strings to INET type

    TODO: ensure each address is actually an INET string, otherwise
          you could end up with injection issues. Don't use this in
          a public facing application taking user input !!
    """
    return [Inet(a) for a in addresses]
```

In an insert, i just wrap Inet() around any Inet values I am inserting. Perhaps this is overengineered?

**Comment by dvarrazzo** [comment]
Hello,

these "adapters" serve pretty much no purpose, as they make no validation. On the other hand people were expecting features from them, like accessing the elements in the address, things we shouldn't be concerned about.

The adapter docstring suggests it is useful to avoid sql-injection, but this is a problem that doesn't exist: strings are escaped as well and don't create any injection problem. Your implementation on the other hand does and allows people to bypass escaping.

There is no need to replace the `Inet()` wrappers with anything: just pass the string down the query.

**Comment by mzpqnxow** [comment]
Understood, honestly my use was simply for the typecast, not validation or
escaping SQL metachsrs- I saw no way that could be happening and took it
upon myself to strictly enforce the INET format. Which I guess seems silly,
but I like to do things the “right” way as best as I can figure- so if the
package provides functionality (and it’s a stable feature) I tend to want
to use it as opposed to my own. It futureproofs me for free :>

Regarding security- it’s funny you mention SQL injection- a decent chunk of
my career involved appsec and I was unlucky enough to have to do more than
a few dozen web app assessments.. I more or less concluded that there are
people who use ORMs or a similarvabsyraction 100%  of the time, and people
who construct queries. I found that despite the protections available by
psycgopg2 and similar libraries in other languages, 20% seem to “go off the
reservation” and just start concatenation strings.. it’s especially
frustrating because it’s obviously easier and cleaner to use what the
library provides, resulting in proper and secure queries. But you know this
and I’m digressing..

One thing to add, if it’s a matter of making the adapter work “properly”
like other psycopg2 mechanisms, I’d be happy to add the code needed to do
that, just out of appreciation of the project. That said, if there’s no
interest, it can die and I’ll undetstand why.

Anyway, thank you for the response and as always, I’m very appreciative of
the time put into this project.

**Comment by dvarrazzo** [comment]
> One thing to add, if it’s a matter of making the adapter work “properly”
> like other psycopg2 mechanisms, I’d be happy to add the code needed to do
> that, just out of appreciation of the project. That said, if there’s no
> interest, it can die and I’ll undetstand why.

I would say there is no interest, because adapters are used to adapt python types to postgres types. The types involved here are a python string and a postgres inet: psycopg knows already how to adapt a python string; the fact it happens to contain an ip address is irrelevant: that's about the content of the string, not about its type. The adapter doesn't perform any conversion, so there is an implicit assumption that the string is in the format accepted by Postgres. Adding the need to wrap these strings into a wrapper object is entirely gratuitous :)

**Comment by mzpqnxow** [comment]
Ah.. for some reason I thought I had trouble inserting without the explicit cast- but that makes sense. Thanks again
