### ISSUE TITLE
Validating connection when called pool.getconn

### ISSUE THREAD

**Issue by kesavkolla** [psycopg/psycopg2#764]
currently there is a check for connection closed while returning connection back into pool.  There should be a similar check should happen when we get connection from pool.  I had observed a scenario where the connection is put back into pool after that there was a server restart.  When I retrieved connection from pool then got closed connection.   It would be nice to check for validity of connection when we call **pool.getconn**.  Even so making a simple query like `SELECT 1` while retrieving connection.

**Comment by dvarrazzo** [comment]
Yes, it would be nice, but it's not possible: nothing tells us the connection is broken until we use it, and using the connection is expensive: we could do a "select 1" but an extra roundtrip every time a connection is taken from the pool is not necessarily what the average customer wants. If that's ok for you feel free to subclass the connection adding your "select 1" test.
