### ISSUE TITLE
Bind parameters in comments are not ignored.

### ISSUE THREAD

**Issue by dliff** [psycopg/psycopg2#766]
A bind parameter `%(name)s` left in a commented line of SQL will attempt to be bound upon execution, often leading to a KeyError if that parameter doesn't happen to be used on a part of the query that is not commented.
I'm not 100% sure this is unintended behavior, but since psycopg2 generally supports sending queries with comments to PostgreSQL it can be a tricky error to run across.

**Comment by dvarrazzo** [comment]
Of course. That's here to stay: psycopg doesn't parse sql to figure out comments from the rest.
