### ISSUE TITLE
bad connection no exception on try block

### ISSUE THREAD

**Issue by insidebitrunner** [psycopg/psycopg2#769]
when I try to connect to postgresql database using the code below, I get neither a good connection or an exception in a try block:
def postgres_conn():

    try:
       
 
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
       
        connect_str = "host=localhost dbname=insiderdb user=postgres password=postgres"
                  
    # use our connection values to establish a connection
        conn = psycopg2.connect(connect_str)
        
        print ( "Connecting to database\n    ->%s" % (connect_str))
 
        
        # create a new cursor
        return conn
     
            
    except psycopg2.Error as e:
         print('Unable to connect!\n{0}').format(e)
         sys.exit(1)

When I mouse over the conn variable, it says the database is close. However, I can access fine in dbeaver and psql. When I try to insert a row into a table, tracing through the code it produces an atrribute exception but doesn;t triigger the try block

**Comment by insidebitrunner** [comment]
system is ubuntu 18.04 postgresql 10 python 3.6 psycopg2 v.2.7.5

**Comment by dvarrazzo** [comment]
Can you connect to the database with psql using the command:

    psql "host=localhost dbname=insiderdb user=postgres password=postgres"

What is the exception raised? What happens if you type in the python shell:

    import psycopg2
    psycopg2.connect("host=localhost dbname=insiderdb user=postgres password=postgres")

**Comment by insidebitrunner** [comment]
I can connect in psql w/o problems as well as dbeaver.  No exceptions get raised in the try except block.  I traced through psycopg2 in pydev, it looked like it had some trouble with the connection string,  so connection_factory never got executed . I checked to make sure it wasn't any spelling errors in the parameters, so at a loss. AndyOn Sep 6, 2018 6:53 AM, Daniele Varrazzo <notifications@github.com> wrote:Can you connect to the database with psql using the command:
psql "host=localhost dbname=insiderdb user=postgres password=postgres"

What is the exception raised? What happens if you type in the python shell:
import psycopg2
psycopg2.connect("host=localhost dbname=insiderdb user=postgres password=postgres")

**Comment by insidebitrunner** [comment]
Didn't try the python shell. AndyOn Sep 6, 2018 10:04 AM, Andy Yonce <Andrew742@comcast.net> wrote:I can connect in psql w/o problems as well as dbeaver.  No exceptions get raised in the try except block.  I traced through psycopg2 in pydev, it looked like it had some trouble with the connection string,  so connection_factory never got executed . I checked to make sure it wasn't any spelling errors in the parameters, so at a loss. AndyOn Sep 6, 2018 6:53 AM, Daniele Varrazzo <notifications@github.com> wrote:Can you connect to the database with psql using the command:
psql "host=localhost dbname=insiderdb user=postgres password=postgres"

What is the exception raised? What happens if you type in the python shell:
import psycopg2
psycopg2.connect("host=localhost dbname=insiderdb user=postgres password=postgres")

**Comment by dvarrazzo** [comment]
Can't reproduce.

```
$ cat test.py 
import sys
import psycopg2

try:
    conn = psycopg2.connect("dbname=baddb")
    print (conn)
        
except psycopg2.Error as e:
     print('Unable to connect!\n{0}'.format(e))
     sys.exit(1)

$ python test.py 
Unable to connect!
FATAL:  database "baddb" does not exist

$ PYTHONPATH=`pwd`/build/lib.3.6/ python3 test.py 
Unable to connect!
FATAL:  database "baddb" does not exist
```
