### ISSUE TITLE
psycopg2 conn.poll() hangs when used with sshtunnel 

### ISSUE THREAD

**Issue by akshay-joshi** [psycopg/psycopg2#777]
Hello,

I am using **psycopg2 2.7.4** to connect to the PostgreSQL database server using **asynchronous** support. It is working absolutely fine. I have used [sshtunnel](https://pypi.org/project/sshtunnel/) v0.1.3 in **pgAdmin4**. When I connect the PostgreSQL database server using ssh tunnel and run the valid/correct query it works fine, but when I run any wrong query(invalid column of table) my application gets hang on conn.poll() function.

Please refer the code how we use conn.poll() with timeouts https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob;f=web/pgadmin/utils/driver/psycopg2/connection.py;h=4f11c12b30882209c308cb3558e67189c97ea31e;hb=15fe26a7106610b710f3de5b604cd038302c926a#l1363  

Can you please provide some pointer?

**Comment by dvarrazzo** [comment]
No, I don't know how to fix it. Please ask the ML as here nobody will read.
