### ISSUE TITLE
With statement does not return connection to pool

### ISSUE THREAD

**Issue by Sonique** [psycopg/psycopg2#778]
Example:
```
connection_pool = ThreadedConnectionPool(...)
with connection_pool.getconn() as connection:
     ...
```
Expected behaviour:  cursor will be closed, connection will be returned to the connection pool.

Now connection does not returns to the pool and one will get error `psycopg2.pool.PoolError: connection pool exhausted`

**Comment by dvarrazzo** [comment]
See #367
