### ISSUE TITLE
Similar mechanism like WAL heartbeat when use LogicalReplicationConnection?

### ISSUE THREAD

**Issue by jiamo** [psycopg/psycopg2#780]
With using `LogicalReplicationConnection`  I meet a problem. When there is no data change, the replication from a PostgreSQL source so idle logical replication slots do not hold on to old WAL logs which may result in storage full situations on the source.  See detail on my stackoverflow problem (https://stackoverflow.com/questions/52589058/aws-rds-postgresql-transaction-logs-keep-going-when-there-is-no-data-change) I don't find some tech in psycopyg2 like WAL heartbeat  in https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReleaseNotes.html.

**Comment by dvarrazzo** [comment]
I am not especially expert in the replication area, and nobody will answer in this bug tracker. I suggest you to ask a question to the pgsql-general mailing list.
