### ISSUE TITLE
Cannot query a value containing backslashes

### ISSUE THREAD

**Issue by alandmoore** [psycopg/psycopg2#785]
I'm using psycopg2 2.7.5 with python 3.5 on Debian with Postgresql 9.6 also on Debian. (I also get the same results from python3.6 on Arch linux).

When I try to query a value in a table that contains backslashes, I don't get a match even when I should.

Consider this code example:
```
import psycopg2

mypath = r'c:\users\bobby.tables'

# add your connection details
cx = psycopg2.connect()
cu = cx.cursor()

cu.execute('CREATE TABLE IF NOT EXISTS test (string varchar(256))')
cu.execute('INSERT INTO test(string) VALUES (%s)', (mypath,))

# now search for the record
cu.execute('SELECT * FROM test WHERE string LIKE %s', (mypath,))

# should have one record, but doesn't
print(cu.fetchall())

# Note the slashes here
print(cu.mogrify('SELECT * FROM test WHERE string LIKE %s', (mypath,)))

# cleanup
cu.execute('DROP TABLE test')
```
If you try this, you'll see that you get no rows back, even though you are searching for the exact same value.  If you set `mypath` to something that doesn't contain backslashes, the code works as expected.

Based on the output of `mogrify`, it looks like maybe the slashes are being over-escaped?

**Comment by alandmoore** [comment]
I understand and agree with you, however, this issue is perplexing when one encounters it; I searched for most of a day and couldn't figure it out.  Would you accept a pull request against the documentation to add this issue to the FAQ?

**Comment by fogzot** [comment]
Sure. I'd add it to the documentation section about bound variables and quoting.

http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries
