### ISSUE TITLE
The adaption of nested empty list in `2.7.5`

### ISSUE THREAD

**Issue by iamalbert** [psycopg/psycopg2#788]
The adaption of empty list is different in `2.7.4` and `2.7.5`

The result of 2.7.5 will cause `malformed array literal` if it used with `=ANY(:arr)`

```
>>> import psycopg2; psycopg2.__version__
'2.7.4 (dt dec pq3 ext lo64)'
>>> from psycopg2.extensions import adapt, register_adapter, AsIs
>>> adapt([]).getquoted()
b"'{}'"
>>> adapt([[]]).getquoted()
b"ARRAY['{}']"
>>> adapt([[[]]]).getquoted()
b"ARRAY[ARRAY['{}']]"
```

```
>>> import psycopg2; psycopg2.__version__
'2.7.5 (dt dec pq3 ext lo64)'
>>> from psycopg2.extensions import adapt
>>> adapt([]).getquoted()
b"'{}'"
>>> adapt([[]]).getquoted()
b"'{{}}'"
>>> adapt([[[]]]).getquoted()
b"'{{{}}}'"
```

**Comment by fogzot** [comment]
I just added a test for this regression:

https://github.com/psycopg/psycopg2/commit/ebcfbe03f9db86591a520758d3569cce1354bed8

**Comment by dvarrazzo** [comment]
For reference, the change was needed to fix #325.

**Comment by dvarrazzo** [comment]
Observation 1: the previously returned value was wrong:

```
=# select ARRAY['{}'];
 {"{}"}
=# select ARRAY[ARRAY['{}']];
 {{"{}"}}
```

This is an array containing the string `{}`.

Observation 2: postgres doesn't just do array of empty arrays:

```
=# select ARRAY['{}'::text[]];
 {}
=# select ARRAY[ARRAY['{}'::text[]]];
 {}
```

at this point I have no idea how we are supposed to fix this bug :\

**Comment by fogzot** [comment]
We can determine if the variable is just a nest of empty arrays and send a single one to PostgreSQL. We lose round-tripping but the value is lost anyway.

**Comment by dvarrazzo** [comment]
```
=# select array[array[]]::text[][] = array[]::text[];
 t
```

This sucks so much... /cringe However it's valid syntax.
