### ISSUE TITLE
Additional placeholders in execute_values

### ISSUE THREAD

**Issue by felipeochoa** [psycopg/psycopg2#793]
Could not find a feature request for this, but it would be great to be able to use the new `execute_values` method with additional parameters. My use case is filtering a table based on 3 fields -- one field is constant across the filter and the other 2 vary. Ideally I'd like to write:

```sql
SELECT t1.field_4, t1.field_5
  FROM table1 t1
  JOIN VALUES %s t2(field_1, field_2)
    ON t1.field_1 = t2.field_1 AND t1.field_2 = t2.field_2
 WHERE t1.field_3 = %s
```

I realize it's trivial in this case to modify the query to give `t2` a `field_3`, but that forces me to create a bunch of single-use tuples on the client side and needlessly repeats the 3rd field value to the server a bunch of times. I'd also guess that it affects the query planner's ability to use indexes on `field_3`.

For completeness, there's a better solution [here](https://dba.stackexchange.com/questions/100665/unknown-returned-type-in-postgresql-query#100669) using `unnest` and defining a type for the `(field_1, field_2)` record but I think this also is less query planner friendly.

**Comment by dvarrazzo** [comment]
You can use the `psycopg2.sql` module to inject a constant in the query and execute it with `execute_values()`. I don't think I would like to add other parameters to the function, and if we did, it would do exactly that.

**Comment by dvarrazzo** [comment]
Note: this may be affected by #794, which should be fixed soon.
