### ISSUE TITLE
execute_values does not accept Composed

### ISSUE THREAD

**Issue by sam-s** [psycopg/psycopg2#794]
The following code
```python
extras.execute_values(cursor,sql.SQL("INSERT INTO {t} ({k}, {v}) VALUES %s").format(
                t=sql.Identifier(table),
                k=sql.Identifier(keycol),
                v=sql.Identifier(valcol)),
                                  buffer)
```
raises an exception
```
AttributeError: 'Composed' object has no attribute 'encode'
```
so I have to call `.as_string(connection)`.
It seems like it would be a good idea to support it `sql.SQL` directly, like `cursor.execute` does.

**Comment by dvarrazzo** [comment]
Good catch! Will fix.

**Comment by jkldgoefgkljefogeg** [comment]
It would be great if argslist supports `sql.Literal` or some way to escape/safe-check argslist
