### ISSUE TITLE
ProgrammingError: can't adapt type 'Identifier'

### ISSUE THREAD

**Issue by sam-s** [psycopg/psycopg2#795]
Similar to https://github.com/psycopg/psycopg2/issues/794:
```python
from psycopg2 import sql
with connection.cursor() as cu:
    cu.execute(sql.SQL("SELECT pg_table_size(%(t)s), pg_indexes_size(%(t)s)"),
               {"t":sql.Identifier(table)})
```
results in
```
psycopg2.ProgrammingError: can't adapt type 'Identifier'
```
so I have to use `as_string`:
```python
with connection.cursor() as cu:
    cu.execute(sql.SQL("SELECT pg_table_size(%(t)s), pg_indexes_size(%(t)s)"),
               {"t":sql.Identifier(table).as_string(connection)})
```
It would be nice if `as_string` were not necessary.

**Comment by dvarrazzo** [comment]
Yes, it would be nice. But no, it won't happen. The above query might stop working eventually hence our decision to not make Identifiers adaptables and to add the whole `psycopg2.sql` extra layer.

`as_string()` is not necessary though: you should use instead:

```python
with connection.cursor() as cu:
    cu.execute(sql.SQL("SELECT pg_table_size({t}), pg_indexes_size({t})")
        .format(t=sql.Identifier(table)))
```

but wait, would this even be valid? You can't say `SELECT pg_table_size("my_table")`, can you? That doesn't look valid.

In your specific case ISTM you don't need identifiers altogether: you can use the table names into strings with:

```python
with connection.cursor() as cu:
    cu.execute("SELECT pg_table_size(%(t)s::regclass), pg_indexes_size(%(t)s::regclass)",
        (table,))
```

**Comment by sam-s** [comment]
I am afraid your first solution does not work, [How to make psycopg2 emit nested quotes?](https://stackoverflow.com/q/52670840/850781).

```python
with connection.cursor() as cu:
    cu.execute(sql.SQL("SELECT pg_table_size({t}), pg_indexes_size({t})")
        .format(t=sql.Identifier("testDB")))
```
==> 
```
ProgrammingError: column "testDB" does not exist
LINE 1: SELECT pg_table_size("testDB"), pg_indexes_size("testDB");
```

your second solution does work, but seems to violate the rule of always using `sql.SQL` when passing SQL to cursors (also, it works even without `::regclass`).

Thanks for your help.

**Comment by dvarrazzo** [comment]
You have to solve your problems in SQL first. Build a query that works in psql and then you can see how to express it in python+psycopg2. If you have a table names with uppercase you are heading for troubles but that's PostgreSQL matter, not psycopg.

**Comment by sam-s** [comment]
The working query is 
```
remoteid=> SELECT pg_table_size('testDB'), pg_indexes_size('testDB');
 pg_table_size | pg_indexes_size 
---------------+-----------------
          8192 |               0
(1 row)
```
Thank you very much for your help.
(you can reply on SO if you want)
