### ISSUE TITLE
Can't adapt type 'dict'

### ISSUE THREAD

**Issue by novikovfred** [psycopg/psycopg2#796]
Hello, I have dict and i want to store it in postgresql.

I have JSONB column, but I can't insert because of `Can't adapt type 'dict'`.

```INSERT_SQL = """
INSERT INTO mail (
    a0, a1, a2, a3, a4, a5, a6, a7
)
VALUES (
    %s, %s, %s, %s, %s, NOW(), %s::int, %s
);
"""
```
Traceback:
```
    json.dumps({}),
psycopg2.ProgrammingError: can't adapt type 'dict'
```

**Comment by novikovfred** [comment]
With `from psycopg2.extras import Json` it doesn't work too.

**Comment by novikovfred** [comment]
Version `psycopg2==2.7.5`

**Comment by aandrey5** [comment]
And how you resolved it?

**Comment by dvarrazzo** [comment]
@aandrey5 probably with https://www.psycopg.org/docs/extras.html#json-adaptation

**Comment by shayneoneill** [comment]
Did you ever get an answer to this?
