### ISSUE TITLE
ssl=false not translated as sslmode=disabled

### ISSUE THREAD

**Issue by kokes** [psycopg/psycopg2#803]
Hi,
we needed to disable SSL on one server, so we switched `ssl=true` to `ssl=false` and that caused an error. This seems to be an issue with the C implementation, not the Python wrapper.

I thought `ssl` was a boolean argument, but that doesn't seem to be the case here. `sslmode` on its own works just fine.

Tested on Mac OS X and Ubuntu, Python 3.7, psycopg2 2.7.5 (installed as `psycopg2-binary`)

```
import psycopg2
import psycopg2.extensions

print(psycopg2.__version__)

psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?sslmode=disabled')
psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?ssl=true')
psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?ssl=false')

2.7.5 (dt dec pq3 ext lo64)

---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-65-cc792a8bc871> in <module>()
      6 psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?sslmode=disabled')
      7 psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?ssl=true')
----> 8 psycopg2.extensions.parse_dsn('postgresql://a:b@localhost:5432/mydb?ssl=false')

ProgrammingError: invalid dsn: invalid URI query parameter: "ssl"
```

**Comment by dvarrazzo** [comment]
The connection parameters are just passed down the libpq for the connection. The valid parameters are [documented here](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS) where I don't see an `ssl` parameter documented, only `sslmode`. If you find errors here you should report them to the postgres devs: we are only messengers.
