### ISSUE TITLE
Attempt to resolve domain socket as host name

### ISSUE THREAD

**Issue by thorstenkampe** [psycopg/psycopg2#808]
Psycopg (latest version) attempts to resolve a domain socket as a host name on Windows (see below). The same does not happen on Linux or Cygwin.

Background: trying to run the following command on Windows: `pgcli postgresql://postgres:password@`
```
>>> import psycopg2
>>> conn = psycopg2.connect(user = 'postgres', password = 'password', host = '/tmp')
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-7-baf0a55895c4> in <module>
----> 1 conn = psycopg2.connect(user = 'postgres', password = 'password', host = '/tmp')

f:\portableapps\python\lib\site-packages\psycopg2\__init__.py in connect(dsn, connection_factory, cursor_factory, **kwargs)
    128
    129     dsn = _ext.make_dsn(dsn, **kwargs)
--> 130     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    131     if cursor_factory is not None:
    132         conn.cursor_factory = cursor_factory

OperationalError: could not translate host name "/tmp" to address: Unknown host
```

**Comment by dvarrazzo** [comment]
The problem seems happening in the libpq. In psycopg 2.7.6 I bumped the version from 10.4 to 10.5. Since it they released 10.6 and 11.1.

I've built test packages using libpq 11.1, they are [available on Test PyPI](https://test.pypi.org/project/psycopg2/2.7.6.1.dev0/) as release 2.7.6.1.dev0. Can you try testing it using:

```
pip install -i https://test.pypi.org/simple/ psycopg2==2.7.6.1.dev0
```

If that fails I'll report the problem upstream. Thank you very much.

**Comment by thorstenkampe** [comment]
The issue remains
```
>>> psycopg2.__version__
'2.7.6.1.dev0 (dt dec pq3 ext lo64)'
```

**Comment by thorstenkampe** [comment]
I'm doing a bit of detective work here...

2.7.5 was released in June. I downgraded to 2.7.5 via `pip` and the issue remains. On the other hand, my description [here](https://github.com/dbcli/pgcli/issues/963#issue-377089117), proves that one week ago the issue couldn't have been present.

I download and installed 2.7.5 from Christoph Gohlke's well-known "Unofficial Windows Binaries for Python Extension Packages" site and with that packages the issue is gone. Did you rebuild 2.7.5 against a more recent version of `libpq` and update the PyPI package??

**Comment by dvarrazzo** [comment]
No I didn't, I would have changed release number :)

Can you tell me the libpq version of the working package and the ones of the non-working ones? You may use:

>>> print(psycopg2.__libpq_version__)
>>> print(psycopg2.extensions.libpq_version())

I'm interested in both values: the first is the version used at compile time, the second at runtime, and they may differ. Thank you very much.

**Comment by dvarrazzo** [comment]
See also dbcli/pgcli#860

**Comment by dvarrazzo** [comment]
Are you sure you were using psycopg 2.7.5 from libpq in your previous installation? Would you be able to trace back a PyPI release working?

If something stopped working on your machine maybe something changed there? Could someone else from pgcli reproduce the bug?

Thank you.

**Comment by thorstenkampe** [comment]
* I tried the `pg_hba.conf` workaround (mentioned in the pgcli ticket) to no avail. No surprise here because the client trying to resolve `/tmp` via DNS has nothing to do with the authorization settings of the server.

* in case it's not obvious: neither Windows (Python client) nor the Cygwin emulation layer (PostgreSQL server) are supporting Unix domain sockets. So client and server are effectively doing a normal TCP session:

> If you omit the host name, psql will connect via a Unix-domain socket to a server on the local host, or via TCP/IP to localhost on machines that don't have Unix-domain sockets.

**Comment by thorstenkampe** [comment]
I'm not sure if the psycopg2 package I used one week ago was from PyPI (I guess that is your question). Normally I only install from the "Unofficial Windows Binaries" repository if there is no PyPI wheel available at the time I need it.

**Comment by dvarrazzo** [comment]
Uhm, even if `/tmp` was interpreted as a unix socket path, if windows doesn't support unix socket, what would it connect to? `/tmp` doesn't even look like a valid path (it is for Python but the conninfo is parsed in C). Maybe for some freak accident that's interpreted as `C:\TMP` and in other connection attempt the cwd is on a different disk?

What do you want to obtain connecting on `host = '/tmp'` on Windows? What does it mean that with what I now assume are the unofficial package the connection "works"?

**Comment by thorstenkampe** [comment]
`/tmp` is coming directly from the server as a result of `pgcli`'s query:
```sql
SELECT setting
FROM pg_settings
WHERE name = 'unix_socket_directories'
```
I guess that value is used for the second connection `pgcli` uses by default for completions.
```
\conninfo
You are connected to database "postgres" as user "postgres" on socket "/tmp" at port "None".
```
`pgcli` connects directly to port 5432 for socket connections and `psql` to a high TCP port to which Cygwin's "socket" points.

Anyway, it doesn't really make sense to use a fake socket connection on Windows. I'll  just add "@localhost" to the connection string.

Feel free to close this ticket.

**Comment by dvarrazzo** [comment]
Sounds good. I guess passing a directory path on windows just gets into the realm of undefined behaviour.

Thank you very much for helping investigating.
