### ISSUE TITLE
Behavioral differences between 2.6 and 2.7

### ISSUE THREAD

**Issue by hsmj1412** [psycopg/psycopg2#809]
After upgrading psycopg2 from 2.6.2 to 2.7.*, I could not connect to server with the same code[1]. Although the error message[2] is about GSS error, but when I downgrade to 2.6.2, the code will pass. So anyone could some help?
Thanks a lot.

[1]
`import psycopg2 `
`connect_option = "dbname=%s user=%s " % (dbname, username) `
`connect_option += "sslmode=require krbsrvname=postgres " `
`connect_option += "host=%s port=%s" % (hostname, port) `
`conn = psycopg2.connect(connect_option) `
[2]
failed to connect to Teiid:
GSSAPI continuation error: Unspecified GSS failure.  Minor code may provide more information
GSSAPI continuation error: No credentials cache found

**Comment by dvarrazzo** [comment]
Are you using 2.7.* from wheel package or from source package?

**Comment by hsmj1412** [comment]
> Are you using 2.7.* from wheel package or from source package?

With pip install

**Comment by dvarrazzo** [comment]
This doesn't help, sorry.

Try installing psycopg with:

```
pip install "psycopg2>=2.7" --no-binary :all:
```

and please let me know if the bug is still there.

**Comment by hsmj1412** [comment]
> This doesn't help, sorry.
> 
> Try installing psycopg with:
> 
> ```
> pip install "psycopg2>=2.7" --no-binary :all:
> ```
> and please let me know if the bug is still there.

Thanks Daniele, it works now. Due to lost postgresql-devel but "pip install psycopg2" did not give any info

**Comment by FatfoutiMontassar** [comment]
Hello,

I'm having the same problem with psycopg2-binary=2.8.6 :/ 

code returns "GSSAPI continuation error: No credentials cache found"

i'm trying to deploy a django website on a linux machine (ubuntu 20.04) with python 3.85

any Help !

**Comment by dvarrazzo** [comment]
@FatfoutiMontassar Don't use the binary package

**Comment by FatfoutiMontassar** [comment]
i deleted the binary package and installed psycopg2 with pip directly 'pip install psycopg2' but i still have the same error:

`django.db.utils.OperationalError: GSSAPI continuation error: unspecified GSS failure. minor core may provide more information
GSSAP continuation error: no kerberos credentials available (default cache: File: /tmp/krb5cc_1000)`

PS: i can connect to the local DB and to an online DB that i created with elephantSql, i'm having this problem only with the work DB, maybe i should do something to connect to a database in the intranet !!

Thanks for your help.

**Comment by dvarrazzo** [comment]
Can you connect with psql?

**Comment by FatfoutiMontassar** [comment]
yes, i can

**Comment by dvarrazzo** [comment]
So it's not an issue with psycopg. Ask the pgsql-general mailing list.
