### ISSUE TITLE
insert - RETURNING 'id' .fetchone() returns 'no results to fetch ' error, for concurrent requests.

### ISSUE THREAD

**Issue by GSargsyan** [psycopg/psycopg2#811]
Previous issues addressing the same type of error had different resolutions.

On concurrent requests(10 requests) `psycopg2` occasionally fails to insert a row, therefore raising error `'no results to fetch'`. Can you please help me to resolve this issue? Which config should I change in postgresql.conf or how psycopg2 connections must be handled? I can provide any info needed.

**Comment by GSargsyan** [comment]
@fogzot - Sure, but the insert statement is unlikely to fail. Besides it fails `occasionally`, meaning it's rather a problem concerning concurrency - memory error etc..

**Comment by fogzot** [comment]
I suppose it fails inside PostgreSQL (and in that case it is not something we can fix in psycopg). And even if it fails in PostgreSQL a concurrency error that aborts the transaction is not a bug and is completely different from a memory error.

Anyway, if you want help, please provide a short program that exhibits the problem, tell us what you expect it to do and what you get, and why the error is related to psycopg.

**Comment by GSargsyan** [comment]
My app is web-application. The app and Postgres app run on docker but I don't think that has anything to do with the problem. If I do the requests one by one, everything is ok, but I need to initialize ajax requests at the same time. 
`psycopg2.ProgrammingError: no results to fetch` is raised sometimes, on the row
`execute(INSERT ...  RETURNING ...).fetchone()`. Some of the columns that had to be inserted are missing when this happens, the half of the data in row is corrupted.
But I suppose too it's rather a problem inside PostgreSQL, not psycopg2. Anyway thank you! And any advice on PostgreSQL could be helpful.

**Comment by fogzot** [comment]
It seems a problem in your application, not PostgreSQL.

**Comment by dvarrazzo** [comment]
This could have been a duplicate of #346, fixed in 2.7.7.
