### ISSUE TITLE
Could not load library pg_trgm.so: undefined symbol: AllocSetContextCreateExtended

### ISSUE THREAD

**Issue by Nukesor** [psycopg/psycopg2#812]
Since updating to `postgresql 11.1-2` with `postgresql-libs 11.1-2` I'm receiving the following error:
```
InternalError: (psycopg2.InternalError) could not load library "/usr/lib/postgresql/pg_trgm.so": /usr/lib/postgresql/pg_trgm.so: undefined symbol: AllocSetContextCreateExtended
```
I'm using the `psycopg2-binary-2.7.6.1` in combination with `SQLAlchemy 1.2.14`. 
The only functionality I'm using is Sqlalchemy's `func.similarity`.

**Comment by dvarrazzo** [comment]
As you can see it is an internal error of the server, nothing related to psycopg, which is on the client side.

Please ask the psql-general mailing list.
