### ISSUE TITLE
Does psycopg2 support Postgresql 11?

### ISSUE THREAD

**Issue by tomascassidy** [psycopg/psycopg2#815]
The [release notes for 2.7.6.1](http://initd.org/psycopg/docs/news.html#what-s-new-in-psycopg-2-7-6-1) mention that psycopg2 was compiled with libpq 11.1, but the [features page](http://initd.org/psycopg/features/) on your site mentions only support up to PostgreSQL 10.  Does psycopg2 currently support PostgreSQL 11, or will that appear in a future release?

**Comment by dvarrazzo** [comment]
The feature page needed an update. Postgres 11 works fine with any psycopg version: there was no change needed to support the new database server.
