### ISSUE TITLE
connections requiring krb5 user TGTs fail, if the user has no postgres service ticket.

### ISSUE THREAD

**Issue by awuersch** [psycopg/psycopg2#816]
psycopg2.connect() to a db at host requiring Kerberos credentials, with a user@realm TGT for the user, but no postgres/host@realm service ticket for the host, fails with an OperationalError "GSSAPI continuation error: Cannot contact any KDC for requested realm". However, if psql connects to the db at host before psycopg2 is tried, the psql connection succeeds and the user gets a postgres service ticket. Then psycopg2.connect() completes successfully.  So psql gets, uses, and leaves a postgres service ticket, while psycopg2 requires it. Could psycopg2 do here what psql does?

**Comment by awuersch** [comment]
My db config has a pg_ident.conf map to get a username, i.e., MAPNAME "krb" SYSTEM-USERNAME "/^(.*)@realm" and PG-USERNAME "\\1". The hba.conf method is "gss include_realm=1 krb_realm=realm map=krb".

**Comment by awuersch** [comment]
Psql calls PQconnectdb from libpq. Psycopg may call PQconnectStart. PQconnectdb calls PQconnectPoll in a loop. Can psycopg be configured to call PQconnectdb?

**Comment by dvarrazzo** [comment]
Maybe if there is any difference, is that you are using the wheel package of psycopg, which comes with a gssapi library obtained from Centos5, which could be too old and not support certain features, whereas psql uses the system libraries.

So, the first test you should do is installing psycopg from source, making sure to use `--no-binary`, and try again.

If psycopg from source works and the wheel version doesn't you may want to suggest a patch for [this script](https://github.com/psycopg/psycopg2-wheels/blob/master/scripts/build_libpq.sh) to build a more modern and correctly configured gssapi library. Or you may just stick to the source version.

The difference in the way psycopg and libpq connect should be of no concern. However psycopg should normally call `PQconnectdb`, and only call `PQconnectStart/Poll` in asynchronous or green mode.

All of the above assuming you are using Linux. If that's not the case please let me know.

**Comment by awuersch** [comment]
installing psycopg from source worked. Thanks for your help, @dvarrazzo .
