### ISSUE TITLE
Automatic gevent monkeypatching

### ISSUE THREAD

**Issue by spladug** [psycopg/psycopg2#826]
In gevent 1.3, they've added a system to allow other libraries to automatically integrate with the `gevent.monkey.patch_all()` call and variants using setuptools entrypoints.  This would make it much easier for users on gevent to safely use psycopg2.

http://www.gevent.org/api/gevent.monkey.html#plugins

I was excited to see `psycopg2` in the example there so came looking here. However, it doesn't look like the integration exists yet. Is this something you all would be interested in having? I'd be happy to make the patch if so.

**Comment by dvarrazzo** [comment]
https://bitbucket.org/dvarrazzo/psycogreen/src/master/

**Comment by spladug** [comment]
Yeah, psycogreen is great. The advantage of putting this hook into setup.py in psycopg2 would be that you wouldn't need an extra dependency to do it right when using gevent, it'd just happen automatically.
