### ISSUE TITLE
ProgrammingError: syntax error at or near “,” in psycopg2 update query using extras.execute_values

### ISSUE THREAD

**Issue by rohanhodarkar** [psycopg/psycopg2#830]
I am trying to update a Redshift table using psycopg2.extras.execute_values module. 
Below is the code
```
from psycopg2 import extras
cur = con.cursor()

update_query = """update my_table
                  set gender = data.gender 
                  from (VALUES %s) as data (gender,firstname) 
                  where my_table.firstname = data.firstname
                  and my_table.gender is NULL"""

new_values = [("F","Charlene"),("F","BRITTANY")]

extras.execute_values (cur, update_query, new_values)
```
This is the same code taken from official page http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_values

Below is the error I am getting:

![psycopg2](https://user-images.githubusercontent.com/19485472/50513923-05930d80-0ac1-11e9-9109-1ce7e48ff4be.JPG)

Not sure if this is a bug.

TIA.
- Rohan H

**Comment by dvarrazzo** [comment]
Your example works perfectly with Postgres. Maybe Redshift doesn't support the VALUES construct.

**Comment by rohanhodarkar** [comment]
> Your example works perfectly with Postgres. Maybe Redshift doesn't support the VALUES construct.

Thanks and yes it looks like RedShift doesn't support this statement. We have to use executemany for updating multiple records in the database.
