### ISSUE TITLE
Canot connect using c api

### ISSUE THREAD

**Issue by WHK102** [psycopg/psycopg2#832]
When try connect using c api for python 3.6 canot connect to database.

Example:

From python:

```
self.dbHandler = psycopg2.connect(
    user     = 'user',
    password = 'pass',
    host     = '127.0.0.1',
    port     = 5432,
    database = 'demo'
)
```

From c api:

`... PyObject* pModule = PyImport_Import(PyUnicode_FromString(corePythonModuleName)); ...`

The result:

```
  None
  File "/etc/python_capi/modules/demo/demo.py", line 38, in dbConnect       
    database = 'demo'                                                     
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 130
, in connect                                                              
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
```

The error message says a `None` error, i print the arguments but all are defined.

From bash works fine, but from c api library does not works.

**Comment by WHK102** [comment]
I print all objects in the line:

`print(str({'__connect': _connect, 'args': {'dsn':dsn, 'connection_factory':connection_factory, 'kwasync':kwasync}}))`

`{'__connect': <built-in function _connect>, 'args': {'dsn': 'user=user password=pass host=127.0.0.1 port=5432 dbname=demo', 'connection_factory': None, 'kwasync': {}}}`

**Comment by dvarrazzo** [comment]
I don't understand

**Comment by WHK102** [comment]
It is invalid, the problem is selinux, canot connect to postgre database from httpd module using c api from python.

Fix with `setsebool httpd_can_network_connect_db 1`.
