### ISSUE TITLE
NamedTupleCursor is inefficient

### ISSUE THREAD

**Issue by Changaco** [psycopg/psycopg2#838]
Calling the standard library's `namedtuple` function over and over again to create ephemeral classes isn't efficient. (You may want to take a look at [`namedtuple`'s source code](https://github.com/python/cpython/blob/3.7/Lib/collections/__init__.py#L310-L312) if you're not familiar with it.)

Instead of doing that a single `Record` class could be created and used as the `row_factory`. It could be similar to `DictRow` but with a `__getattr__` method in addition to `__getitem__`.

The current `NamedTupleCursor` implementation also degrades performance by calling `re.compile()` and `re.sub()` repeatedly in its [`_make_nt()` method](https://github.com/psycopg/psycopg2/blob/3f20f7934ad3efdf793ae81a61a842bec7adb85c/lib/extras.py#L384-L398). The `Record` class could avoid that most of the time by only generating the python-compatible names when an attribute lookup fails.

Would a Pull Request implementing those changes be merged?

**Comment by Changaco** [comment]
Yes. I also confirm that I was aware of that caching mechanism when I wrote my previous comment.

**Comment by dvarrazzo** [comment]
So we are talking about a single `namedtuple()` call for every `execute()`, which implies a roundtrip to the server, the server running the query, returning the data on the network, and then there is all the Postgres to Python data type adaptation. To me it doesn't sound a worthwhile optimisation. Do you have numbers to back its need?

I'm more ok with micro-optimisations e.g. the `re.compile()` call, which are very probably not measurable either but at least they fit in a pattern of correct usage, and still produce a named tuple on a thing called `NamedTupleCursor`.

If we have to update the named tuple to "a thing with `__getattr__`" it should be an entirely different object (it could even be `DictRow` itself as far as I'm concerned), or calling it `NamedTupleCursor` would be a lie. The overhead of doing it is also in documentation and upgrade path for the users, and of course `NamedTupleCursor` should stay where it is and with unchanged semantics as a lot of users use it expecting precisely named tuples.

**Comment by Changaco** [comment]
> Do you have numbers to back its need?

Yes, I've been profiling a web app. With Python 3.6 the calls to `namedtuple` make up 14% of the time needed to process a thousand requests for a page that executes 3 SQL queries, even surpassing the 13% taken by the actual processing of the queries (the `execute` method). In Python 3.7 `namedtuple` was optimized and the calls to it consume a more reasonable 4.5% of the time, versus 15% for the query processing. However that's still a significant overhead.

(The sub-call to the builtin `exec` function is the most expensive part of `namedtuple`.)

> If we have to update the named tuple to "a thing with `__getattr__`" it should be an entirely different object (it could even be `DictRow` itself as far as I'm concerned), or calling it `NamedTupleCursor` would be a lie.

A single `Record` class could mimic the classes created by `namedtuple` in almost every way: it could be a `tuple` subclass and have similar methods (`__repr__`, `_asdict`, etc.). Consequently I don't think `NamedTupleCursor` would be a lie, but if you still prefer that a new cursor factory class be created instead then I'm fine with that.

**Comment by dvarrazzo** [comment]
Interesting to know, thank you.

A much simpler optimisation would be to cache namedtuples by names, keeping a lru-cache of e.g. 100-1000 of them.

**Comment by Changaco** [comment]
Caching the classes would speed things up, but it would also cost extra RAM, and it only works well as long as the cache size remains larger than the number of classes used regularly by the application.

**Comment by dvarrazzo** [comment]
Caching 100-1000 of them is not that much ram. I don't believe your application uses so many different ones. If your page runs 3 sql queries that's the same 3 classes built over and over...

**Comment by Changaco** [comment]
Obviously the web app has more than one page. A cache size of 100 would most likely be too low since we have more than 500 SQL queries in our app.

I'm not going to write or use a caching version of the current `NamedTupleCursor`, because in my opinion it's not the correct solution to this issue.

**Comment by dvarrazzo** [comment]
In branch https://github.com/psycopg/psycopg2/tree/fast-namedtuple:

Moved to use a proper LRU cache: the stats can be accessed by `NamedTupleCursor._cached_make_nt.cache_info()`. Interested to know the hit/miss ratio after your app has been running for a while, thank you.
