### ISSUE TITLE
cursor.fetchmany() requires the "size" argument instead of using curs.arraysize

### ISSUE THREAD

**Issue by psycoteam** [psycopg/psycopg2#84]
Originally submitted by: Samuel PHAN

Depending on the connection factory you use, the `cursor.fetchmany()` may requires the `size` argument instead of using `cursor.arraysize`.
- `psycopg2.extras.RealDictConnection`: KO - the `cursor.fetchmany()` requires the `size` argument.
- `psycopg2.extras.DictConnection`: KO - the `cursor.fetchmany()` requires the `size` argument.
- `psycopg2.extras.NamedTupleConnection`: KO - the `cursor.fetchmany()` requires the `size` argument.
- `psycopg2._psycopg.connection`: OK.

psycopg2 version 2.4.4, Ubuntu 10.10

**Comment by mnemonicflow** [comment]
Is there any reason why this is not consistent? 

* when setting the arraysize but not the size param it should use the arraysize regardless of cursor class
* when setting the size param is should use that param regardless of cursor class
* when setting both the arraysize and size param it should use the size param regardless of cursor class

Just lost more about an hour troubleshooting and trying to figure out why fetchmany refused to retrieve more than 1000 results even though I've set cursor.arraysize before calling cursor.execute()

I've tried setting `cursor.arraysize = 1000` with a cursor factory of `extras.DictCursor` and it would refuse to fetch more than 1000 rows

**Comment by dvarrazzo** [comment]
This bug was fixed 4 years ago and it's not clear what you are asking. 

```
In [14]: cur = cnn.cursor(cursor_factory=psycopg2.extras.DictCursor)

In [15]: cur.execute("select generate_series(1,100)")

In [16]: len(cur.fetchmany())
Out[16]: 1

In [17]: len(cur.fetchmany(10))
Out[17]: 10

In [18]: cur.arraysize = 20

In [19]: len(cur.fetchmany())
Out[19]: 20

In [20]: len(cur.fetchmany(10))
Out[20]: 10

In [21]: len(cur.fetchmany(30))
Out[21]: 30
```

On 2.6.1 fetchmany returns size records if specified, otherwise cur.arraysize records. This is consistent with both the base cursor and `DictCursor`. What is that is not working for you? Open a new bug report with a test case.

**Comment by mnemonicflow** [comment]
As I've said: using arraysize doesn't work with DictCursor

Will have to check tomorrow but the code I had looked something this:

```
cursor = connection.cursor('my_cursor, cursor_factory=extras.DictCursor)
cursor.execute("select * from table1") # this query if run in psql will return aprox. 200000 rows
cursor.arraysize = 1000
row_count = 0
for row in cursor.fetchmany():
    row_count +=1 
    if row_count >= 1000:
      print("Success")
      sys.exit(0)
```
vs
```
cursor = connection.cursor('my_cursor, cursor_factory=extras.DictCursor)
cursor.execute("select * from table1") # this query if run in psql will return aprox. 200000 rows
row_count = 0
for row in cursor.fetchmany(1000):
    row_count +=1 
    if row_count >= 1000:
      print("Success")
      sys.exit(0)
```

The first example stops after 1000 rows returned, whereas the second will not.

**Comment by dvarrazzo** [comment]
Let me know, because this seems working for me, even using a named cursor as in your example. I suspect you have an outdated psycopg version.

```
In [1]: import psycopg2.extras

In [2]: cnn = psycopg2.connect('')

In [3]: cur = cnn.cursor('foo', cursor_factory=psycopg2.extras.DictCursor)

In [4]: cur.execute("select generate_series(1,100)")

In [5]: len(cur.fetchmany(30))
Out[5]: 30

In [6]: len(cur.fetchmany())
Out[6]: 1

In [7]: cur.arraysize = 50

In [8]: len(cur.fetchmany())
Out[8]: 50
```
