### ISSUE TITLE
fetchall() sometimes returns invalid results

### ISSUE THREAD

**Issue by anze555** [psycopg/psycopg2#840]
I have this code that is called from a Flask endpoint:

```python
def get_list(somefield):
    with db.cursor() as c:
        ret = []
        c.execute('SELECT name, slug FROM mytable WHERE somefield = %s ORDER BY name;', (somefield,))
        for name, slug in c:
            ret.append({'name': name, 'slug': slug})
        return ret
```

The code worked as expected when using psycopg2 version 2.7.5.

After I (accidentaly) upgraded to version 2.7.7, every fifth to tenth time iterating `c` would return just a tuple `(1,)` instead of `("...name...", "...slug...",)`, leading to `ValueError: not enough values to unpack (expected 2, got 1)`. 

Note that in most cases the resulting tuples were correct, it was an intermittent error.

Explicitly calling `fetchall` didn't help:
```python
        for name, slug in c.fetchall():  # still exhibits the same problem
```

Downgrading to 2.7.5 fixed the bug, but it probably need to be fixed in 2.7.7 too. Let me know if you need additional info.

**Comment by anze555** [comment]
Please wait until dealing with this issue, it seems that the same thing happens occasionally with 2.7.5 too. Will investigate further.

**Comment by dvarrazzo** [comment]
Thank you for looking into this: please let us know :)

**Comment by anze555** [comment]
No need to thank me, I am just solving my problem - thank you for providing this library, and most of all for taking the time to answer! :)

I have spent some time trying to debug this. What didn't help:

- using older versions of `psycopg2` 
- using older versions of my app
- using `pyscopg2-binary` instead of `psycopg2`
- using python 3.7.2 (instead of 3.6.8)
- restarting the machine ;)

What *did* help:
- running outside of Docker (I was unable to reproduce the bug outside of it)

I am stumped. The bug is quite predictable and I can reproduce it easily, just by repeating the same REST request about 10 times. I have wrapped my `execute()` call with some debugging and this is how it looks like:

```
with db.cursor() as c:
    ret = []
    log.info('SQL: SELECT name, slug FROM dashboards WHERE account = {} ORDER BY name;'.format(account_id))
    try:
        c.execute('SELECT name, slug FROM dashboards WHERE account = %s ORDER BY name;', (account_id,))
        for name, slug in c.fetchall():
            ret.append({'name': name, 'slug': slug})
    except:
        log.exception("SQL FAILED!")
        raise
    return ret
```
In logs I get:
```
2019-02-11 21:53:56 | INF | SQL: SELECT name, slug FROM dashboards WHERE account = 1 ORDER BY name;
2019-02-11 21:53:56 | ERR | SQL FAILED!
Traceback (most recent call last):
  File ...
ValueError: not enough values to unpack (expected 2, got 1)
```

I don't see how that SQL sentence could ever return just one value... I am not even sure this is psycopg2 problem anymore, since running the same script outside of Docker works flawlessly. If you have any suggestions on how to further debug this, I would appreciate it. Maybe running tcpdump and listening to communication with Postgres? Would building a debug version of psycopg2 help?

**Comment by dvarrazzo** [comment]
Why don't you print what `c.fetchall()` returns and look what it is instead of having it clobbered by the unpacking exception?

Building a debug version could be useful. It's not hard to do it.

If your cursor's result are getting mixed with another cursor would be definitely a problem to address. The fact it happens only in docker may suggest that `pthread_mutex` is broken in docker? It sounds like a long shot...

**Comment by anze555** [comment]
Thank you for the response. I have already printed out the result at the start (it is `(1,)` in this case) - I apologise if the example wasn't clear enough.

But it doesn't matter - I have since figured out what the problem was. 

I knew I wasn't using psycopg2 in a thread-safe way, but I didn't realize that it mattered, because I thought I was using multiple _processes_. I have not enabled threads in uWSGI, and have set the number of processes to 5. However apparently with uWSGI fork happens only after the imports:

> uWSGI works by creating an instance of the python interpreter and importing the python files related to your application. If you configure it with more than one process, it will fork that instance of the interpreter until there are the required number of processes

https://www.reddit.com/r/Python/comments/4s40ge/understanding_uwsgi_threads_processes_and_gil/

This means that psycopg2 was shared among multiple processes.

I have since started using `ThreadedConnectionPool` and switched to threads (with processes I keep getting `psycopg2.OperationalError: server closed the connection unexpectedly`, probably because of the way the fork is [done](https://stackoverflow.com/questions/1573579/psycopg2-disconnects-from-server)), and everything works reliably again.

I am sorry for the noise - it turns out it wasn't `psycopg2`'s fault after all. I don't know if `psycopg2` could detect such usage and issue a warning, but if yes, I think it would be a nice addition.

Thank you for helping me figure this out, and thank you for maintaining such a great library!

Feel free to close the ticket.

**Comment by dvarrazzo** [comment]
I wonder if we should have a PID guard: storing the PID in the connection when created and marking it invalid if it's changed on usage. However that would only happen when you try to use it, so you would get an error anyway. Maybe we could have a connection pool guarding for it and discarding connections created in the wrong process...

Anyway, closing this. Thank you for the investigation.

**Comment by anze555** [comment]
Just my 0.02 EUR: if this would work, I think it would be awesome! Granted, one would still get an error, but the message could point to the correct cause (in my case I assumed there was some memory corruption issue). 

Not sure about performance implications though, I assume the checks would need to be rare enough, so they wouldn't slow down the library noticeably.

Thanks again!
