### ISSUE TITLE
Unable to execute "copy command"

### ISSUE THREAD

**Issue by aleaficionado** [psycopg/psycopg2#841]
Hi,

We're using psycopg2 to connect to Redshift. We'd like to load a parquet file by issuing a command to redshift: 
`copy table from 's3://bucket/parquet' iam_role 'arn:aws:iam::000000000:role/role' format as parquet`

The command executes correctly in Workbench, but it does not seem to be issued to Redshift when triggered from psycopg2. 

`   

    c = __connection.cursor()

    sql = """copy table from 's3://bucket/parquet' iam_role 'arn:aws:iam::000000000:role/role' format as parquet"""

    c.execute(sql)

    print(c.statusmessage)

    c.execute("insert into table values (-1....)")

    __connection.commit()
`

After running the above (sanitised) code, the table will contain only one entry (for -1). I couldn't find any entry for the copy command in any of the STL tables and based on my limited understanding of psycopg2 it looks like this command is not sent to the cluster.

Am I missing an obvious step? Is there a way to send a "raw" SQL to the cluster, bypassing all the checks?

**Comment by aleaficionado** [comment]
This was not due to psycopg2, but most likely to AWS S3/ Lambda. If anyone is intrerested in this, the parquet file generated by Pandas/ PyArrow was not "created" until the AWS Lambda function terminated (tested using a sleep function). The psycopg2 copy call was in the same AWS Lambda function.
I was able to force the file generation by making an "list_objects" API call on the file and everything worked as expected (hence it looks like an issue with S3/ Lambda rather than anything else). 

However, psycopg2 could be improved by providing the full output of the command - at the moment it is impossible to see using psycopg2 alone if the copy command was successful or not. Workbench provides a textual output of the operation and this is something that might be added in the future; the status message of the operation was 'COPY' and perhaps a full message can be added in the future.

**Comment by dvarrazzo** [comment]
If psycopg didn't raise an exception, then it "worked", whatever that means with aws, lambda, etc. There is nothing else that it should have reported.

**Comment by aleaficionado** [comment]
It worked, but below is the output when running the command manually - is it possible to have the second line available (warning contents) available in some field? The status message just said 'COPY'.
`
Warnings:
Load into table 'zzzzzzzzzzzz' completed, 7 record(s) loaded successfully.

0 rows affected
COPY executed successfully

Execution time: 0.99s
Statement 1 of 1 finished
`

**Comment by dvarrazzo** [comment]
```
In [1]: import psycopg2

In [2]: cnn = psycopg2.connect('')

In [3]: cur = cnn.cursor()

In [4]: cur.execute("copy testin from '/home/piro/testin.txt';")

In [5]: cur.statusmessage
Out[5]: 'COPY 3'

In [6]: cur.rowcount
Out[6]: 3
```

If AWS does something different is all a server-side business we don't have part of.

**Comment by aleaficionado** [comment]
Cheers for that and the fast replies are very much appreciated! I'll need to test that RS can produce the same result, but it's a good baseline of expected behaviour.
