### ISSUE TITLE
Is there any possibility we can show the details(schema) of user-defined-type 

### ISSUE THREAD

**Issue by itismewxg** [psycopg/psycopg2#842]
if we made an user-defined type, e.g. udt_1, in psql, we can use \d udt_1 to see its details, but how could we do this in sql, or in other words, how could we get it from psycopg?

**Comment by dvarrazzo** [comment]
You can use `psql -E` to print the queries psql uses internally to implement commands such as `\d`. It will query system tables such as `pg_class`, `pg_attribute` etc, and you can use the same queries from psycopg.

**Comment by itismewxg** [comment]
Got it! Thank you so much!
