### ISSUE TITLE
sql module doesn't tab complete in python repl

### ISSUE THREAD

**Issue by jonassteinberg1** [psycopg/psycopg2#844]
I don't know if I'm missing something, but for whatever reason the sql module is present in the repl's `help(psycopg2)`, but does not seem to be present when `import psycopg2` is executed and rather only when the module is _explicitly imported:_ `from psycopg2 import sql`.  The below image has had the `import psycopg2` command executed successfully, as can be inferred from the tab completion in the python repl...and yet no tab completion for sql.   If this is how the package is supposed to function then my apologies for the bogus issue.

<img width="1438" alt="screen shot 2019-02-13 at 7 47 53 am" src="https://user-images.githubusercontent.com/7853938/52724660-9dab6000-2f64-11e9-8a3f-a401f0bc89cb.png">

**Comment by dvarrazzo** [comment]
Probably because it's not imported into the main package by default. This is a pretty standard policy in Python modules.

**Comment by jonassteinberg1** [comment]
@dvarrazzo Okay, yeah I've never seen an `import package` then require a `from package import module`.  I thought `import package` was like...the whole deal.
