### ISSUE TITLE
Add a chat and networking platform for users

### ISSUE THREAD

**Issue by henrykironde** [psycopg/psycopg2#845]
I think it would be a good idea to connect the software to some of the chat, GitHub integrated platforms. A good example could be https://gitter.im/

**Comment by dvarrazzo** [comment]
How much do you offer to pay for the service?

**Comment by henrykironde** [comment]
Well I think there are many platforms free for open source. I want to think gitter is free.

**Comment by dvarrazzo** [comment]
Is my time free?

**Comment by henrykironde** [comment]
Sorry if you thought that I implied that you have to respond to the users and waste time or get paid. A chat platform will enable the software get a community where users help other users. A good example is postgres https://postgres-slack.herokuapp.com/ . Currently they have  **237 users online now of 3977 registered.** These users help each other. 

I am a contributor to open source and I totally know how exhausting it is to be closing and reviewing issue. I came to this page to ask some question that I believe many users may have faced like when trying to maintain backward/forward compatibility in their environments for example, 
```python
 psycopg2/__init__.py:144: UserWarning: The psycopg2 
wheel package will be renamed from release 2.8; in order to keep installing from 
binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    """)

```
But did not what to burden the maintainer or developers. And am not trying to sell Gitter, to you. I just gave an example. And any code of conduct would be appropriate for the chat platform. https://www.postgresql.org/about/policies/coc/

**Comment by dvarrazzo** [comment]
You can use the search functionality in the bug tracker to look for information. Or even the documentation. Or even google.

I have a full time job, I likely live in a different timezone than yours. On a chat I will get for sure the same questions over and over. People would expect an answer *immediately* and will be moaning if they don't get it. This project is way smaller than Postgres itself and I don't expect many people in the chat to subscribe and answer: there will be mostly me, repeating over and over how to escape single quotes in strings.

Other ways to get help from the community: there is the Mailing List. If you make a question there someone might answer before me. There is no expectation of an answer in 15 seconds. The answers are indexed by google and available for the future. A chat on a web up is much more ephemeral.

I don't personally intend to open a chat, maintain it, answer there. Feel free to motivate people on the mailing list about the need of such chat and about its COC: the mailing list is the right place to have this conversation, not a bug tracker.
