### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by henrykironde** [psycopg/psycopg2#846]
It is a good practice for users and developers of open source communities to understand and follow a more ethical and appropriate manner as they contribute to open software.

It is common for contributors to burn out and become rude, and it is common for new users to act in a manner not ethical for open source.

The code of conduct enables all users to be nice to each other in these public spaces.
#845

**Comment by fogzot** [comment]
Ah... I was waiting for this one. A have stong social and political opinions agains COCs and I'd like to just say NO, but given that I am not yet burned out I will limit myself to suggesting to discuss this topic on psycopg mailing list first.

Now, closing this untill an agreement is reached on the ML.

**Comment by dvarrazzo** [comment]
The adoption of a code of conduct should be discussed in the mailing list: it's not something I desire to received as a copypasted policy without understanding if we have any community issues to address.

You need to define first what "ethical" means and receive an agreement.

I also see that you refer explicitly to another issue where you seem to imply my time is to be devolved to support user via chat, in addition of providing this software for free - as in beer. This is a passive-aggressive behaviour which borderlines trolling I do not tolerate.
