### ISSUE TITLE
ThreadedConnectionPool "gotcha" with respect to 0 keys

### ISSUE THREAD

**Issue by Magtheridon96** [psycopg/psycopg2#848]
I think it should be mentioned somewhere in the documentation that using the integer `0` as a key with a `ThreadedConnectionPool` will cause a `PoolError` to be thrown upon calling `putconn`. This wasn't clear to me until I read the snippet of code at the top of the `putconn` function:

```python
if key is None:
    key = self._rused.get(id(conn))

if not key:
    raise PoolError("trying to put unkeyed connection")
```

Was this behavior intentionally undocumented or am I missing something obvious?

**Comment by dvarrazzo** [comment]
Probably that check should have been `if key is None`, as it's guarding that the key wasn't found in the `_rused` map. I'll fix it that way, it seems harmless.
