### ISSUE TITLE
Missing psycopg2.extensions.BYTES

### ISSUE THREAD

**Issue by gnomic** [psycopg/psycopg2#859]
The documentation mentions 
```
psycopg2.extensions.BYTESARRRAY
psycopg2.extensions.BYTES
```
However, in psycopg 7.6 and 7.7 dir(psycopg2.extensions) using Python 3.6 does not list these as an option and gives a syntax error when trying to use them.

**Comment by dvarrazzo** [comment]
You missed the

> New in version 2.8: the BYTES and BYTESARRAY objects.

2.8 is about to be released. There is an outstanding bug I'm about to fix.
