### ISSUE TITLE
多线程同时insert时  sql语句字符多的时候 报错

### ISSUE THREAD

**Issue by zhengedaidan** [psycopg/psycopg2#860]
![issue1](https://user-images.githubusercontent.com/33029216/54107486-4dfd6e80-4414-11e9-9135-9a8ae34a77b4.png)
![error](https://user-images.githubusercontent.com/33029216/54107503-55bd1300-4414-11e9-9220-381fa43dde54.png)

简短的sql语句没有报错
字符长的sql语句会发生图2的错误 请教一下 谢谢

**Comment by dvarrazzo** [comment]
I am afraid we don't speak Chinese.

Psycopg 2.7.7 fixed some concurrency problems: please check you are using it.

You should provide a self-contained use case. There are too many variables or things you may be doing wrong, for instance I don't know if you are trying to share cursors across threads.

Closing until further details are shared.
