### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-uakhrewh/psycopg2/

### ISSUE THREAD

**Issue by Raveesha24** [psycopg/psycopg2#861]
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-uakhrewh/psycopg2/

Help me guyzzzz..

**Comment by dvarrazzo** [comment]
This is a bug tracker.
