### ISSUE TITLE
Overzealous warning for 2.8 release?

### ISSUE THREAD

**Issue by ddahan** [psycopg/psycopg2#880]
I'm using `django-heroku`, a python Package that requires any version of `psycopg2` (not `psycopg2-binary`).

When running my Django server, I get this warning: `he psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead.`

- **Problem 1**: I can't get ride of this warning, since I'm not developing the `django-heroku` package.
- **Problem2**: When getting in touch with the `django-heroku` maintainer, he says that the [warning is overzealous because the package actually needs the `psycopg2` dependency,](https://github.com/heroku/django-heroku/issues/7#issuecomment-402815092) not the `psycopg2-binary` one.

- NOTE: I'm using PipEnv, not pip. The main difference is that you specify the packages you want to use directly, not dependencies. That's why I should not add something related to psycopg in it.
But if it there exists a workaround, I can accept to add it as a normal package.

If there any solution to remove this useless warning in my case?
Thanks.

**Comment by dvarrazzo** [comment]
Wait a few days for the release of 2.8.
