### ISSUE TITLE
select() failed: Operation not permitted

### ISSUE THREAD

**Issue by anandreddyakidi** [psycopg/psycopg2#881]
Hi,

Getting select() failed: Operation not permitted while querying select query to redshift spectrum. with single thread it is working fine. If run in multithread(100 threads) environment getting error. Below is my sample code.

 try:
    conn = psycopg2.connect(
      dbname=REDSHIFT_DATABASE,
      user=REDSHIFT_USER,
      password=REDSHIFT_PASSWD,
      port=REDSHIFT_PORT,
      host=REDSHIFT_ENDPOINT)
    conn.set_session(autocommit=True)
   except Exception as ERROR:
    print(ERROR)
    sys.exit(1)
   
   cursor=conn.cursor()
   try:
        cursor.execute(REDSHIFT_QUERY)
        for row in cursor.fetchall():
            print(row)

Regards
Anand

**Comment by dvarrazzo** [comment]
Not a thing we can look into with those information.

**Comment by anandreddyakidi** [comment]
Thanks for the reply. But what are the possible reasons for Operation not permitted on cursor.execute. Could you please help?

**Comment by dvarrazzo** [comment]
I guess you should look at strace for the kernel errors if the problem is client-side, or to the server errors if the error is server-side.

**Comment by Jwan622** [comment]
I am also seeing this error. What was the cause?
