### ISSUE TITLE
Importing both psycopg2 and psycopg2-binary - what's the effect of this?

### ISSUE THREAD

**Issue by MartyMacGyver** [psycopg/psycopg2#885]
I have a project that for old reasons has been pinning its psycopg2 dependency thus:

    psycopg2==2.7.7 --no-binary psycopg2

As of today though, we had a problem thanks to a dependency of a dependency that explicitly uses `psycopg2-binary` (unpinned). Up to now that was also 2.7.7... the mismatch when that dependency alone started grabbing 2.8 led (unsurprisingly in retrospect) to a build failure.

The fix was to pin both `psycopg2` and `psycopg2-binary` to the same version (currently 2.7.7 but 2.8 seems to work as well - just don't mix different versions!)

**My questions:**

- Is `--no-binary` as shown above unnecessary for 2.8+? It appears that way.
- What is the net effect of importing both `psycopg2` and `psycopg2-binary`? We've obviously been doing that for a while now, and it worked fine til the version mismatch, but are they both active, or does only one of them actually end up being used? Which one?

**Comment by dvarrazzo** [comment]
If you have questions you have to make them to the mailing list, not to a bug tracker.

- `--no-binary` is unnecessary and allowed transparent migration from 2.7
- you can't import `psycopg2-binary`, at most you can install it, and the net effect of having both is confusion in your virtualenv.

Fix the project using `psycopg-binary` as a dependency. As documented, it is not advised, just a lazy shortcut.

**Comment by MartyMacGyver** [comment]
Thank you - this all stems from UWSGI. Here's the original issue, should anyone else happen upon this thread.

https://github.com/unbit/uwsgi/issues/1569
