### ISSUE TITLE
'Unexpectedly, there's no async cursor here'

### ISSUE THREAD

**Issue by PCaff** [psycopg/psycopg2#887]
Started getting this error this week. Nothing has changed in my processes. I could not longer pull this package as python3 -m pip install pyscopg2, had to change to python3 -m pip install pyscopg2-binary. 

Can anyone explain why this would happen? I set my connection as async_=True, but now all of a sudden that config is not passed to the cursor.

**Comment by dvarrazzo** [comment]
It's something that changed with psycopg 2.8. Do you have a way to reproduce?

**Comment by dvarrazzo** [comment]
If there is a bug I suggest to go back to psycopg 2.7.7 but I would like to investigate as you shouldn't see this message.

**Comment by PCaff** [comment]
I'm sure a simple test of an async process would produce this. I'm going to try to do this now.

**Comment by PCaff** [comment]
Looks like you cannot pull a cursor out:
`import psycopg2
connection = psycopg2.connect(dbname=db, host=host, port='5439', user=user, password=passw, async_=True)
cursor = connection.cursor()`

Error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.OperationalError: asynchronous connection attempt underway
`

**Comment by dvarrazzo** [comment]
You have to complete connection before using cursors.

```python
>>> import psycopg2
>>> from psycopg2.extras import wait_select
>>> cnn = psycopg2.connect('', async_=True)
>>> wait_select(cnn)
>>> cur = cnn.cursor()
```

**Comment by PCaff** [comment]
Oh wow, didn't have to do that in 2.7. Is this new functionality? @dvarrazzo

**Comment by PCaff** [comment]
@dvarrazzo 
So, after a 

> wait_select(connection)

 the error is reproduced by 

> connection.poll()

**Comment by dvarrazzo** [comment]
> Oh wow, didn't have to do that in 2.7. Is this new functionality? @dvarrazzo

No, it's no new functionality: it's as it always worked.

**Comment by dvarrazzo** [comment]
I see, will try to push a fix soon as I'm sure it will affect many people.
