### ISSUE TITLE
psycopy2-2.8.1 libpq.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by EricCheung3** [psycopg/psycopg2#892]
When updating the psycopg2 library to the latest version, we got this error:
_Downloading https://files.pythonhosted.org/packages/52/be/f898e712f5f08131d651a62754fca82a1deb42e4e9889ad01932f770a2be/psycopg2-2.8.1.tar.gz (367kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'_

We installed libqp-dev, this problem was solved, but when testing our function, we got this error 
unable to import module _libpq.so.5: cannot open shared object file: No such file or directory_

But everything works very well before version psycopy2-2.8.1.
Now we are forcing to use version 2.7.7 or 2.7.5 to avoid the issue.

Does anyone have the similiar problem? or how to avoid the prob by using the latest version? 

Update our command from "pip install psycopg2" to "pip install psycopg2-binary", is this what we should do?

Many thanks!!!

**Comment by EricCheung3** [comment]
I tried using "pip install psycopg2-binary", after installed, when we tested it, we got this error: No module named 'psycopg2._psycopg'.

**Comment by dvarrazzo** [comment]
`pip uninstall` both `psycopg2` and `psycopg2-binary`, then install `psycopg2-binary`.

**Comment by arkha98** [comment]
still got output same error
