### ISSUE TITLE
Comparison between RealDictRow

### ISSUE THREAD

**Issue by ProgVal** [psycopg/psycopg2#895]
Hi,

Sorry to bother you again with RealDictCursor, but I noticed a change of behavior in 2.8.1:

```
>>> import psycopg2, psycopg2.extras
>>> db = psycopg2.connect('service=swh-replica', cursor_factory=psycopg2.extras.RealDictCursor)
>>> cur = db.cursor()
>>> cur.execute('SELECT 1 AS a, 2 AS b;'); row1 = cur.fetchone()
>>> cur.execute('SELECT 2 AS b, 1 AS a;'); row2 = cur.fetchone()
>>> row1 == row2
False
>>> dict(row1.items()) == dict(row2.items())
True
```

Before then, the first comparison would be True.

I'm not sure this is a bug, feel free to close this ticket if this is the intended behavior.

**Comment by dvarrazzo** [comment]
Now they are OrderedDict, so that's their behaviour.

I'm ok with it, I don't think it is a huge problem. If it turns out it is we could do orderless comparison.

So, closing with "maybe" for now.
