### ISSUE TITLE
Cannot update column in a RealDictRow (related to #886)

### ISSUE THREAD

**Issue by jasonrubenstein** [psycopg/psycopg2#896]
```  
File "/x/y/.pyenv/versions/3.6.6/envs/z/lib/python3.6/site-packages/psycopg2/extras.py", line 282, in __setitem__
    super(RealDictRow, self).__setitem__(mapping[key], value)
graphql.error.located_error.GraphQLLocatedError: list indices must be integers or slices, not str
```

Example code: 
```
row[col] = some_function(row[col], some_param).decode('utf-8')
```
(where row is an instance of RealDictRow)

psycopg2-binary v2.8.1 
https://github.com/psycopg/psycopg2/commit/cc815e8e8d33d5f39e602eebd6f7341952dfe058

**Comment by jasonrubenstein** [comment]
Looks like #891 might cover this problem (commit https://github.com/psycopg/psycopg2/commit/4058f363d69159b7c0193b6bd873aa0ee0621a89)
?

**Comment by dvarrazzo** [comment]
How was the row created?

**Comment by dvarrazzo** [comment]
It's probably more related to #884. Could you check if https://github.com/psycopg/psycopg2/commit/4058f363d69159b7c0193b6bd873aa0ee0621a89 fixes the problem?

**Comment by jasonrubenstein** [comment]
Will do.

**Comment by jasonrubenstein** [comment]
@dvarrazzo   Yes, it does.

**Comment by dvarrazzo** [comment]
Cool, thank you: I'll try to release 2.8.2 with a fix in the next days.
