### ISSUE TITLE
DictCursor extremely slow

### ISSUE THREAD

**Issue by sarink** [psycopg/psycopg2#897]
I noticed that `DictCursor` is causing a huge slowdown in my app.

I then wrote this function myself, and began using it instead:
```
def build_row_dict(columns, row):
    index = 0
    dict = {}
    for key in columns:
        value = row[index]
        dict[key] = value
        index += 1
    return dict
```

Usage:
```
cursor.execute("SELECT a,b,c FROM table");
for row in cursor:
  row_dict = build_row_dict(['a', 'b', 'c'], row)
  ...
```

After profiling both on the same queries (large dataset, ~5 million rows), I found the above to be 40% faster than the built in `DictCursor`

**Comment by dvarrazzo** [comment]
What psycopg version?

**Comment by dvarrazzo** [comment]
Still waiting to know the version you tested...

**Comment by sarink** [comment]
Sorry! `psycopg2-binary` version `2.7.5`

**Comment by chenz-svsarrazin** [comment]
I am also experiencing a performance regression with DictCursors, but only in 2.8.x. Going from 2.7.7 to 2.8.1 doubles the runtime (2.8 crashes).

Here is some profile data:

2.7.7

    PATH: '/redacted'
             1814607 function calls (1814595 primitive calls) in 3.977 seconds
    
       Ordered by: internal time, call count
       List reduced from 257 to 30 due to restriction <30>
    
       ncalls  tottime  percall  cumtime  percall filename:lineno(function)
            6    0.955    0.159    0.955    0.159 {method 'execute' of 'psycopg2.extensions.cursor' objects}
       101539    0.839    0.000    1.414    0.000 /usr/lib/python2.7/decimal.py:515(__new__)
        46556    0.524    0.000    2.554    0.000 /path/to/ve/local/lib/python2.7/site-packages/psycopg2/extras.py:105(__iter__)
       415881    0.467    0.000    0.467    0.000 /path/to/ve/local/lib/python2.7/site-packages/psycopg2/extras.py:273(__setitem__)
       406158    0.199    0.000    0.199    0.000 {method 'group' of '_sre.SRE_Match' objects}
       101541    0.172    0.000    0.172    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
        46209    0.137    0.000    0.137    0.000 /path/to/ve/local/lib/python2.7/site-packages/psycopg2/extras.py:265(__init__)

2.8.1

    PATH: '/redacted'
             4099107 function calls (4099095 primitive calls) in 9.517 seconds
    
       Ordered by: internal time, call count
       List reduced from 266 to 30 due to restriction <30>
    
       ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       462090    1.516    0.000    3.416    0.000 /path/to/ve/local/lib/python2.7/site-packages/psycopg2/extras.py:278(__setitem__)
       462106    1.424    0.000    1.424    0.000 /usr/lib/python2.7/collections.py:54(__setitem__)
            6    0.976    0.163    0.976    0.163 {method 'execute' of 'psycopg2.extensions.cursor' objects}
       101539    0.960    0.000    1.628    0.000 /usr/lib/python2.7/decimal.py:515(__new__)
        46210    0.831    0.000    1.701    0.000 /usr/lib/python2.7/collections.py:38(__init__)
        46558    0.619    0.000    7.695    0.000 {next}
      1076230    0.463    0.000    0.463    0.000 {len}
        46209    0.286    0.000    2.193    0.000 /path/to/ve/local/lib/python2.7/site-packages/psycopg2/extras.py:259(__init__)
        46210    0.244    0.000    0.714    0.000 /path/to/ve/lib/python2.7/_abcoll.py:526(update)
       101541    0.241    0.000    0.241    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
       406158    0.214    0.000    0.214    0.000 {method 'group' of '_sre.SRE_Match' objects}
        46211    0.178    0.000    0.300    0.000 /path/to/ve/lib/python2.7/abc.py:128(__instancecheck__)
        92418    0.174    0.000    0.226    0.000 /usr/lib/python2.7/collections.py:64(__delitem__)
       224555    0.168    0.000    0.468    0.000 {isinstance}

**Comment by dvarrazzo** [comment]
Hi @chenz-svsarrazin, @sarink,

I don't have a lot of time to investigate into this: I don't have a test case ready, but I wouldn't mind if someone made some progress.

As you have test cases, and because this is pretty straightforward python code, can you try optimising this code path and propose a MR?

Thank you very much

**Comment by chenz-svsarrazin** [comment]
My issue is with RealDictRow, and the performance regression is due to the switch from dict to OrderedDict as a backing class. OrderedDict is a lot slower.
    
    # test.py
    from collections import OrderedDict
    import sys
    
    def test(cls):
        for i in range(10000):
            d = cls()
            for j in range(40):
                d[j] = j + i
    
    cls = eval(sys.argv[1])  
    for j in range(100):
        test(cls)

    $ time python test.py dict
    
    real	0m1.836s
    user	0m1.836s
    sys	0m0.000s
    $ time python test.py OrderedDict
    
    real	0m23.445s
    user	0m23.446s
    sys	0m0.000s

I don't understand yet why the switch to OrderedDict was made - as an API user I would expect RealDict do have dict semantics.

**Comment by dvarrazzo** [comment]
@chenz-svsarrazin #177 is a reasonable request

**Comment by chenz-svsarrazin** [comment]
Having looked at the *DictCursor implementation some more, I can't think of a good way to fix it. The fact that these classes try to implement both dict and list interfaces seems very awkward to me. Also does not help performance that it has to inspect the arguments to determine the mode (list or dict) it should be in.

Something as simple as this fits my needs and outperforms even 2.7.x RealDictCursor:

    def map_dicts(cursor):
        index = [d[0] for d in cursor.description]
        for row in cursor:
            yield dict((index[i], v) for i, v in enumerate(row))

   cursor.execute(...)
   for d in map_dicts(cursor):
        ...

**Comment by sir-sigurd** [comment]
@chenz-svsarrazin 
You could also try this:
```
def map_dicts(cursor):
    names = [d[0] for d in cursor.description]
    indexes = range(len(names))
    for row in cursor:
        yield {names[i]: row[i] for i in indexes}
```

**Comment by septatrix** [comment]
#177 is a reasonable request but should have been implemented as a separate cursor type IMO. Reverting that change however would break a lot of things.

That being said I would like to propose reverting the OrderedDict to a dict as soon as support for Python 3.6 gets dropped.

**Comment by dvarrazzo** [comment]
I don't think this will receive attention. psycopg 3 cursors are much more performing and easy to implement.
