### ISSUE TITLE
execute_batch() slow for large insert queries

### ISSUE THREAD

**Issue by ydinari** [psycopg/psycopg2#902]
Hi,
execute_batch() creates an sql insert query per dictionary in the input sequence. A bunch of these gets sent to the database, but this is still much slower than creating a single sql query with multiple tuples (like the one created by execute_values()).
It would be nice if it behaved like execute_values(), or at least had some flag to get it to work that way if you want.
Thanks

**Comment by dvarrazzo** [comment]
Why can't you use execute_values() then? Propose an use case please.

**Comment by ydinari** [comment]
I'm using sqlalchemy, and it creates queries with named place holders and dictionary arguments, so it uses execute_batch() and not execute_values().
I imagine that every time you prefer named place holders and dictionaries (so you get the benefit of not caring about arguments order and using a place holder multiple times) you would use execute_batch(), and still want the better performance.
Thanks

**Comment by dvarrazzo** [comment]
Unless we made something impossible to do, supporting sqlalchemy is not one of psycopg2 goals, it is the other way around.

How do you imagine this function's interface should be?

**Comment by ydinari** [comment]
I think it should be the same interface as it is now, just creates a single query (per page size) instead of multiple ones

**Comment by dvarrazzo** [comment]
Maybe if it's not that way it's before it can't be done... 

Can you send a concrete example of how you would like this to work, and so what interface you see for this function? And maybe a patch implementing it?

**Comment by ydinari** [comment]
Hi,
I'm attaching a patch with the proposed change. There's no new function or interface, just a different implementation for execute_batch() in extras.py if a 'VALUES (...)' clause is found in the input sql.
If not found the previous implementation will be applied.
[execute_batch_single_query_patch.txt](https://github.com/psycopg/psycopg2/files/3103169/execute_batch_single_query_patch.txt)

**Comment by dvarrazzo** [comment]
Psycopg has a policy of not parsing sql. Postgres has a complex parser and we don't want to emulate a subset of it. Your patch doesn't allow a newline after `VALUES` and isn't even case-insensitive.

I wouldn't accept a patch that changes behaviour so radically on different content of the input string: this interface is not robust enough. I would have preferred if you had explained the change in interface/behaviour beforehand. Before writing code, please express the idea about what you want to do, or you risk wasting a lot of time. If you do want to write code please send a merge request, which can be commented on in github, and you should provide tests and documentation as well.

In my view, adding extra arguments to the query can be adequately done by the `psycopg2.sql` module, adding values as literals to the query and adding a single unnamed placeholder at the right place. It could be possible to use that module to write a bridge function. Alternatively, as you have seen, the execute_values() function itself is not very complex: you may have your own utility function in your project with the interface you desire, or propose it as a patch to SQLAlchemy to make a better use of it.

Please provide a compelling use case for this function: describe what arguments you have, and the final query you would like to see. If we find something that can't be done simply, and if the resulting interface is not too horrible, then we can find an implementation for it. I'm >50% sure what you want to do can be done adequately with what is already available.

Thank you for sharing your ideas: that's very appreciated.

**Comment by ydinari** [comment]
Hi,
OK, here's a use case: I have a query with named placeholders and arguments in dictionaries, and I call execute_batch() to execute it:

```
sql = 'INSERT INTO my_table (account_id, name) VALUES (%(account_id)s, %(name)s)'

# Very large list of dictionaries
args = [{'account_id': 1, 'name': 'Yuval Pizza'},
        {'account_id': 2, 'name': 'Sunset Hair Saloon'},
        {...}, ...]

psycopg2.extras.execute_batch(cursor, sql, args)
```
This will result in a call to execute() with sql query per element in args:

```
cur.execute("INSERT INTO my_table (account_id, name) VALUES (1, 'Yuval Pizza');
             INSERT INTO my_table (account_id, name) VALUES (2, 'Sunset Hair Saloon');
             ...")

```

This however can be sped up (by around 40% from my experiments) if we merge the insertions of all those rows into a single insert query:

```
cur.execute("INSERT INTO my_table (account_id, name) VALUES
                 (1, 'Yuval Pizza'),
                 (2, 'Sunset Hair Saloon'),
                 ...")

```
This is what I tried to implement in my patch. This is not a new interface or function, just an optimization of the existing execute_batch() function.
This optimization can't be always applied because it depends on the existing of a 'VALUES (...)' clause in the sql, which isn't always there (e.g. an update query).
As for your technical comments about the patch, I agree and fixed them. I don't seem to have permission to create a branch in the repo, that's why I sent the patch instead of a pull request.
As for the parsing of sql, I'm not doing much more parsing than is done by execute_values().
So my suggestion should be viewed as an optimization, not as new functionality. Indeed this could be achieved on the user side of psycopg2, but I feel like a performance optimization is better done by the library, without adding work for the user, changing the interface, or forcing the use of execute_values() while the user code is more suited for using execute_batch().
I'm attaching the new patch. If you feel like this is worth while then I can add documentation and tests.
Thanks
[execute_batch_single_query_patch.txt](https://github.com/psycopg/psycopg2/files/3103527/execute_batch_single_query_patch.txt)

**Comment by dvarrazzo** [comment]
What you say can already be done by `execute_values()`. Using your values:

```python
>>> psycopg2.extras.execute_values(cur, sql, args, template='(%(account_id)s, %(name)s)')
# fails because I don't have the table, but:

>>> cur.query
"INSERT INTO my_table (account_id, name) VALUES (1, 'Yuval Pizza'),(2, 'Sunset Hair Saloon')"
```

Is [the documentation](http://initd.org/psycopg/docs/extras.html#psycopg2.extras.execute_values) not clear?
