### ISSUE TITLE
error: command 'gcc' failed with exit status 1 -Python3.7 MacOs Mojave

### ISSUE THREAD

**Issue by IlirBajrami** [psycopg/psycopg2#903]
Trying to install psycopg2 on Python3.7 MacOs Mojave and i get this error.
    
    sudo pip3 install psycopg2
    .
    .
    .
    .
    .
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import 
    setuptools, tokenize;__file__='/private/tmp/pip-install- 
    1aqd5u6c/psycopg2/setup.py';f=getattr(tokenize, 'open', open) 
    (__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install 
     --record /private/tmp/pip-record-q0w4n30y/install-record.txt --single-version-externally- 
    managed --compile" failed with error code 1 in /private/tmp/pip-install- 
    1aqd5u6c/psycopg2/

**Comment by dvarrazzo** [comment]
Let's do this: I close this bug sending you to read http://initd.org/psycopg/docs/faq.html#problems-compiling-and-installing-psycopg2

If there's something uncovered, let us know what is the error message (the part you omitted).

**Comment by IlirBajrami** [comment]
> Let's do this: I close this bug sending you to read http://initd.org/psycopg/docs/faq.html#problems-compiling-and-installing-psycopg2
> 
> If there's something uncovered, let us know what is the error message (the part you omitted).

thanks for the suggestion dvarrazzo, however this didn't fix my issue, but after days of going from one error to another i found this solution (in case anyone else has this issue): https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249

p.s its a Mojave problem (in my case)

**Comment by claudiokc** [comment]
https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249

That solved my problem thanks for the link.

**Comment by Ilir-Qualifirst** [comment]
> [python-pillow/Pillow#3438 (comment)](https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249)
> 
> That solved my problem thanks for the link.

glad it helped you!

**Comment by IlirBajrami** [comment]
> [python-pillow/Pillow#3438 (comment)](https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249)
> 
> That solved my problem thanks for the link.

glad it helped you!

**Comment by schen-wmfr** [comment]
That also solved my problem thanks so much!

**Comment by MediaByte** [comment]
Thank you.  This solved my problem.

**Comment by ClearMarble** [comment]
Solved it for me too, thanks so much! Link from dvarrazzo was no help however.

**Comment by cadu-leite** [comment]
> > Let's do this: I close this bug sending you to read http://initd.org/psycopg/docs/faq.html#problems-compiling-and-installing-psycopg2
> > If there's something uncovered, let us know what is the error message (the part you omitted).
> 
> thanks for the suggestion dvarrazzo, however this didn't fix my issue, but after days of going from one error to another i found this solution (in case anyone else has this issue): [python-pillow/Pillow#3438 (comment)](https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249)
> 
> p.s its a Mojave problem (in my case)

@ IlirBajrami answer help ! problem solved

**Comment by revolutionisme** [comment]
Thanks @IlirBajrami, for the response to how you solved it. Arrogance/Sarcasm of the committer was not needed at all!

**Comment by dylanxia2017** [comment]
> > Let's do this: I close this bug sending you to read http://initd.org/psycopg/docs/faq.html#problems-compiling-and-installing-psycopg2
> > If there's something uncovered, let us know what is the error message (the part you omitted).
> 
> thanks for the suggestion dvarrazzo, however this didn't fix my issue, but after days of going from one error to another i found this solution (in case anyone else has this issue): [python-pillow/Pillow#3438 (comment)](https://github.com/python-pillow/Pillow/issues/3438#issuecomment-435169249)
> 
> p.s its a Mojave problem (in my case)

problem solved by that, thank you

**Comment by gopikrishna-a** [comment]
Hi There,

I'm the same issue on **MacOS Catalina version 10.15.2**  and I'm not able to run following command since there is no path:```/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.2.pkg -target ``` On **MacOS Catalina version 10.15.2**

**Error:**
```
agk@agk ~ % sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.2.pkg -target /
installer: Error - the package path specified was invalid: '/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.15.2.pkg'.
```


Can someone help me with this..?

**Comment by rahulkp220** [comment]
@gopikrishna-a Use this method as it worked for me
```
>> xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
>> env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip install psycopg2==2.8.4
Collecting psycopg2==2.8.4
  Using cached psycopg2-2.8.4.tar.gz (377 kB)
Installing collected packages: psycopg2
  Attempting uninstall: psycopg2
    Found existing installation: psycopg2 2.7.7
    Uninstalling psycopg2-2.7.7:
      Successfully uninstalled psycopg2-2.7.7
    Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.8.4
```
Done!

**Comment by qemtek** [comment]
https://stackoverflow.com/questions/59493078/python-3-7-psycopg2-xcode-error-error-command-gcc-failed-with-exit-status @gopikrishna-a Follow these instructions, you need xcode installed to get the Developer folder

**Comment by qemtek** [comment]
@gopikrishna-a  install psycopg2-binary instead and it works

**Comment by mfinaly** [comment]
@rahulkp220 That worked. Thanks!

**Comment by kevinlakhani** [comment]
@qemtek thank you

**Comment by SubhajitC** [comment]
psycopg2==2.8.5
  ERROR: Command errored out with exit status 1:
     command: /home/subhajit/Venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sfrkkmrl/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sfrkkmrl/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2rx1qqkm
         cwd: /tmp/pip-install-sfrkkmrl/psycopg2/
    Complete output (7 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-2rx1qqkm/psycopg2.egg-info
    writing /tmp/pip-pip-egg-info-2rx1qqkm/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-2rx1qqkm/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-2rx1qqkm/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-2rx1qqkm/psycopg2.egg-info/SOURCES.txt'
    Error: b'You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.\n'
  getting error  help me

**Comment by SubhajitC** [comment]
within 10 min let me know
