### ISSUE TITLE
psycopg2.ProgrammingError: subprogram body is not ended correctly at end of input

### ISSUE THREAD

**Issue by vieyahn2017** [psycopg/psycopg2#905]
```python
import psycopg2
conn = psycopg2.connect(database='testXXX', user='iXXX', password='BiXXXX', host='8.XXXXX', port=25308)
tcursor = conn.cursor()
sql = """SELECT 1 AS foo;"""
tcursor.execute(sql)
```

such simple code,  this error occurs. 
i m utterly  confused

**Comment by vieyahn2017** [comment]
```
psycopg2.__version__
'2.7.5 (dt dec pq3 ext)'
```

**Comment by vieyahn2017** [comment]
environment:
```
cat /proc/version
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
```

**Comment by dvarrazzo** [comment]
This is not a psycopg error, it is a server error psycopg is just reporting.

Is it even a postgres database? If it is isn't might be configured weird.

**Comment by vieyahn2017** [comment]
sorry,  the error is because the postgres database version conficts.

**Comment by leaTepes** [comment]
> sorry, the error is because the postgres database version conficts.
hi there,
meet the same problem as you were,can you tell me the detail of "postgres database version conficts."?
is that mean the version of pg does not match the version of psycopy?
