### ISSUE TITLE
Calls to functions converted to string in mogrify()

### ISSUE THREAD

**Issue by daveisfera** [psycopg/psycopg2#908]
We are using a prepared statement and calling `mogrify()` to handle escaping of the inputs. It's working well, but we would like to include a function call in these inputs and the function call gets turned into a string and isn't evaluated by Postgres. Is there a way to allow the function call to still be passed in instead of being escaped?

Here's an example of raw SQL that works:
```
CREATE TABLE test (a INTEGER, b TIMESTAMP);
PREPARE test_execute AS INSERT INTO test (a, b) VALUES ($1, $2);
EXECUTE test_execute(1, DATE_TRUNC('day', '2019-01-02T03:04:05.678'::TIMESTAMP));
```

If we do the same thing using `psycopg2` with `mogrify()`, then the call to `DATE_TRUNC()` is turned into a string and not evaluated like we need it to be.

**Comment by dvarrazzo** [comment]
Please take a look at [the `psycopg2.sql` module](http://initd.org/psycopg/docs/sql.html), which contains facilities to compose sql statements dynamically much more powerful than `mogrify()`.
