### ISSUE TITLE
Package version above 2.7.5 failed installation in Pipenv

### ISSUE THREAD

**Issue by priyashpatil** [psycopg/psycopg2#909]
Getting package installation failed error when run `pipenv install pyscopg2` or `pipenv update` with Pipfile configurations below.

**Pipfile**
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
flake8 = "*"
autopep8 = "*"

[packages]
django = "==2.2"
psycopg2 = "*"

[requires]
python_version = "3.7"
```

Tried versions 2.8, 2.8.1, 2.8.2 all gives same error.

**It works fine with version 2.7.5 and below**. I had to specify version manually in Pipfile. But getting following warning in terminal when try to run migrations or server.

```
virtualenvs/django-zq8fdNRu/lib/python3.7/site-packages/psycopg2/__init__.py:144:
UserWarning: The psycopg2 wheel package will be renamed from release 2.8; 
in order to keep installing from binary please use "pip install psycopg2-binary" instead. 
For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```

I'm using 

- macOs Mojave & home brew
- Postgres 11.2
- Python 3.7
- pipenv 2018.11.26

**Comment by dvarrazzo** [comment]
With 2.8 you need the build prerequisites.

http://initd.org/psycopg/docs/install.html#build-prerequisites

Install those, or install the binary version, or install 2.7.

**Comment by priyashpatil** [comment]
Thanks dvarrazzo for reply. I should have went through documentation first.
