### ISSUE TITLE
Question about docs-txt

### ISSUE THREAD

**Issue by crunchyjoea** [psycopg/psycopg2#910]
Hey!

I noticed as of [this commit](https://github.com/psycopg/psycopg2/commit/f70d6fd0edaa56027fb3047477ee850dba2b529e), the support for outputting the documentation as a text file was removed. I was wondering the origin of this change, mostly just as a point of curiosity. Thank you!

**Comment by dvarrazzo** [comment]
I don't think it was used. It wasn't published anywhere, wasn't part of the sdist: I don't think people would have rendered it and kept it for themselves, using it in preference of the html version.
