### ISSUE TITLE
column "rules" is of type jsonb[] but expression is of type text[]

### ISSUE THREAD

**Issue by felipeaugustox** [psycopg/psycopg2#911]
I'm using `execute_values` to insert the content of many tables on other tables, I already set the adapter of `dict` to `json` when I received other error, however I don't know how to treat this one:

> psycopg2.ProgrammingError: column "rules" is of type jsonb[] but expression is of type text[]
        LINE 1: ...UES (1,'tturxvrtgvvsrqgzsedcoyqujakyepjordrbbjdw',ARRAY['{"i...

The only way to handle that was something like the issue #585, but I would need to treat each column ...

Maybe there are ways to create a new adapter, but I couldn't achieve how to do that by the docs.

```python
register_adapter(dict, Json)

execute_values(
            dest_cursor,
            f'''
            INSERT INTO {t} VALUES %s ON CONFLICT DO NOTHING;
            ''',
            records,
    )
```

**Comment by dvarrazzo** [comment]
You can use the `template` parameter of `execute_values()` to cast the 3rd item of your record to jsonb array, like (untested):

```python
execute_values(
            dest_cursor,
            f'''
            INSERT INTO {t} VALUES %s ON CONFLICT DO NOTHING;
            ''',
            records,
            template="(%s, %s, %s::jsonb[], %s, %s)" # as many placeholders requested
    )
```

**Comment by felipeaugustox** [comment]
So easy!! Thank you so much @dvarrazzo!

**Comment by cansjt** [comment]
For those using SQLAlchemy the documentation provides [a work-around](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#using-json-jsonb-with-array). 

If you don't use it, I used the following alternative, which is similar to the above work-around:
```python
from psycopg2 import extras
class Json(extras.Json):
    def getquoted(self):
        return super().getquoted() + b'::jsonb'
```
Which seem more sensible, to me, than have to play with query templates at all `execute` call sites (might depend on the scale of your project). This implementation does not deal with JSON vs. JSONB though. Didn't look into it 'cause I only use the latter. I would not be surprised to learn there is a way to make this better though.
