### ISSUE TITLE
psycopg2-binary-2.8.2 libcrypt.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by loleg** [psycopg/psycopg2#912]
```
    import psycopg2
  File "/home/oleg/.local/share/virtualenvs/backend-CqoIE4Q5/lib/python3.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libcrypt.so.1: cannot open shared object file: No such file or directory
```

This error has popped up since upgrading to Fedora 30. I believe it has to do with the [deprecation](https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt) of Glib's libcrypt in favor of https://github.com/besser82/libxcrypt .. but I'm not sure what's going on here, since nowhere is it mentioned in the code or libpqxx.

**Comment by loleg** [comment]
Via https://fedoraproject.org/wiki/Changes/FullyRemoveDeprecatedAndUnsafeFunctionsFromLibcrypt the workaround is to install the **libxcrypt-compat** system package. However, there are numerous security gotchas related to this, and it would be great if we could figure out where to bump the reference to `libcrypt.so.2` as suggested.

**Comment by dvarrazzo** [comment]
This is not something we specifically chose to do, but comes from the Python wheel build system and I don't believe it can be changed without creating a new standard

https://www.python.org/dev/peps/pep-0513/
https://www.python.org/dev/peps/pep-0571/

maybe @matthew-brett has more up-to-date info?

**Comment by dvarrazzo** [comment]
Assuming the problem has been solved by the PyPA folks
