### ISSUE TITLE
Document library versions linked in psycopg2-binary

### ISSUE THREAD

**Issue by jdufresne** [psycopg/psycopg2#914]
From http://initd.org/psycopg/docs/install.html#binary-install-from-pypi

> The binary packages come with their own versions of a few C libraries, among which libpq and libssl, which will be used regardless of other libraries available on the client

Can the actual version of these libraries be stated explicitly? At the moment, the docs don't say.

**Comment by dvarrazzo** [comment]
It's in the news. It can also be read from the packaged libraries names (libcrypto wasn't, it's patched for the purpose).

 I think that's enough.
