### ISSUE TITLE
Connecting is very slow.

### ISSUE THREAD

**Issue by merspieler** [psycopg/psycopg2#916]
Since a few days I'm encounting problems with connect().

It takes more than two minutes to establish a connection.

I've written this sample code:
```
#! /usr/bin/python3
import psycopg2
connection = psycopg2.connect(database="mydb", host="localhost", port="5432", user="myuser", password="...")
cur = connection.cursor()
cur.execute("""SELECT datname from pg_database""")
rows = cur.fetchall()
for row in rows:
        print ("   ", row[0])
```
If i run this script with `time ./test.py`, time returns the following:
```
real	2m9,784s
user	0m0,084s
sys	0m0,004s
```

This problem started to occure about 1-2 weeks ago.

I'm running `psycopg2-binary 2.7.7` in a venv on debian buster.

If I conect with psql I've got no problem so I'm inclined to belive it's not on the server side.

How can I find the cuase of this problem and resolve it?

**Comment by dvarrazzo** [comment]
No idea. It is either a networking or a server configuration problem, or server, not psycopg. You would have the same slowness if you ran the same on psql.

**Comment by merspieler** [comment]
I defenetly do NOT have the same slownes with psql on the command line...
networking can be ruled out since it runs on the same machine

If it's the server conf (which i didn't touch in that time since this occures) what could affect psycopg but not psql?

**Comment by dvarrazzo** [comment]
Your script does a connection, a query, and a select. It which step it is slow? In the connect?

**Comment by merspieler** [comment]
Yes, the connect

**Comment by dvarrazzo** [comment]
Can you run the following?
```
export DSN="database=mydb host=localhost port=5432 user=myuser password=xxx"
time python -c "import os, psycopg2; print psycopg2.connect(os.environ['DSN'])"
time psql -c "" "$DSN"
```

**Comment by merspieler** [comment]
Sure

**Comment by merspieler** [comment]
Um... i get an error:
```
$ time python -c "import os, psycopg2; print (psycopg2.connect(os.environ['DSN']))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/storage/scenery/osm2city/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 129, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/storage/scenery/osm2city/venv/lib/python3.7/site-packages/psycopg2/extensions.py", line 155, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "database"
```

**Comment by dvarrazzo** [comment]
`dbname=mydb`

**Comment by merspieler** [comment]
Okay, that's strange... I get two times about 2min and 10 sec...  
If I connect manually (just running `psql mydb` it works instantly)

**Comment by dvarrazzo** [comment]
You must have the definition of `localhost` screwed up in `/etc/hosts`, or NetworkManager messing up with it. Had this problem in Ubuntu a long time ago, can't remember the details now, but google is your friend.

If you connect with psql without specifying the host it will use the unix socket so it will skip the name resolution mess you seem to have. To be sure whether it's a DSN problem or not you can check if connecting to `host=127.0.0.1` is fast instead.

**Comment by merspieler** [comment]
Thanks for the hint... works again.
localhost did resolve to ::1 (ipv6) while both, v4 and v6, were available but psql was only listening on v4.
