### ISSUE TITLE
ALTER INDEX gives "relation does not exist" error

### ISSUE THREAD

**Issue by xiaoshieefocus** [psycopg/psycopg2#917]
cur.execute("ALTER INDEX my_table_idx RENAME TO my_table_idx_backup")

this gives "relation my_table_idx does not exist".

looks like it treats "my_table_idx" as table name, but it should be index name.

**Comment by dvarrazzo** [comment]
That is a database message, not psycopg. You are probably connected to the wrong database.

**Comment by xiaoshieefocus** [comment]
ok thanks i will double check. also it would be great if anyone can share some success on ALTER INDEX...having hard time make it work.
