### ISSUE TITLE
sqlalchemy package is not installing. No issues raised while installing but not found in python program

### ISSUE THREAD

**Issue by DivyaMereddy007** [psycopg/psycopg2#918]
sqlalchemy package is not installed. No issues raised while installing but not found in the python program. 

System:AWS linux 
Command used pip install sqlalchemy.

(django) [ec2-user@ip-172-31-32-173 mysite-PS-Django]$ ^C
(django) [ec2-user@ip-172-31-32-173 mysite-PS-Django]$ pip install sqlalchemy
Collecting sqlalchemy
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-1.3.3
You are using pip version 18.0, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

No issues raised:

>>> import sqlalchemy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'sqlalchemy'

Not able to understand anything. I googled a lot but didn't find a solution. I also tried pip install sqlalchemy-redshift. it has raised 
ommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ce5ngjwm/psycopg2/

**Comment by dvarrazzo** [comment]
Wrong bug tracker mate.
