### ISSUE TITLE
GPG Key to verify initd.org tarball downloads

### ISSUE THREAD

**Issue by shepdelacreme** [psycopg/psycopg2#919]
I've looked here and on the initd.org site for the following key ID 6013BD3AFCF957DE that I can download and import in order to verify the tarballs and sigs downloaded from http://initd.org/psycopg/tarballs/ I checked a few gpg keyservers and couldn't find it either.

What am I missing? I can't seem to find it anywhere.

**Comment by dvarrazzo** [comment]
I don't know how to help here.
