### ISSUE TITLE
pip install psycopg2 dont work

### ISSUE THREAD

**Issue by mujasiyam** [psycopg/psycopg2#920]
pip install psycopg2
Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/23/7e/93c325482c328619870b6cd09370f6dbe1148283daca65115cd63642e60f/psycopg2-2.8.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2zs1cqex/psycopg2/

OS: Kubuntu 19.4

**Comment by mujasiyam** [comment]
### work for me ..

Debian/Ubuntu
### Python 2
`sudo apt install libpq-dev python-dev`
### Python 3
`sudo apt install libpq-dev python3-dev`

### Additional
If none of the above solve your issue, try
`sudo apt install build-essential`
or
`sudo apt install postgresql-server-dev-all`

**Comment by Brunocristianods** [comment]
> ### trabalhe para mim ..
> Debian / Ubuntu
> 
> ### Python 2
> `sudo apt install libpq-dev python-dev`
> 
> ### Python 3
> `sudo apt install libpq-dev python3-dev`
> 
> ### Adicional
> Se nenhuma das opções acima resolver seu problema, tente
> `sudo apt install build-essential`
> ou
> `sudo apt install postgresql-server-dev-all`

Thanks!
