### ISSUE TITLE
Is the binary package still discouraged in production?

### ISSUE THREAD

**Issue by darakian** [psycopg/psycopg2#921]
Hey all,

In order to speed up my build process I've been looking into using the psycopg2 binary package despite the warning on the docs. After reading
https://github.com/psycopg/psycopg2/issues/543 and https://github.com/psycopg/psycopg2/issues/836
I've been running tests using `psycopg2-binary` and things seem to be working, but I'd like to get some developer commentary. Is the binary package still discouraged for production deployment? If not, is there any difference between the `psycopg2-binary` package and the `psycopg2` package without the `--no-binary` flag?

**Comment by dvarrazzo** [comment]
People who ran tests showed encouraging results. If for you shaving seconds out of your build process is a valuable result try using the binary packages. I don't feel like endorsing the binary package so far to push it as the default as was done optimistically in previous releases.

As of psycopg 2.8, `pip install psycopg2` is equivalent to using `--no-binary`. The difference is that the `-binary` package packages its own libraries (libpq, libcrypto...) whereas the package installed from source uses the system libraries.

**Comment by darakian** [comment]
Cool. Thanks for the reply.
