### ISSUE TITLE
python - Why psycopg2 are so slow with me?

### ISSUE THREAD

**Issue by ilovesport** [psycopg/psycopg2#925]
-bash-4.2$ time psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -X -c "select true"
 bool 
------
 t
(1 行记录)

real    0m0.142s
user    0m0.003s
sys     0m0.012s
-bash-4.2$ time psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -X -c "select true"
 bool 
------
 t
(1 行记录)

real    0m0.041s
user    0m0.004s
sys     0m0.006s
-bash-4.2$ time psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -X -c "select true"
 bool 
------
 t
(1 行记录)

real    0m0.076s
user    0m0.007s
sys     0m0.005s
-bash-4.2$ time psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -X -c "select true"
 bool 
------
 t
(1 行记录)

real    0m0.076s
user    0m0.006s
sys     0m0.002s
-bash-4.2$ time psql -h 127.0.0.1 -p 5432 -U postgres -d postgres -X -c "select true"
 bool 
------
 t
(1 行记录)

**Comment by ilovesport** [comment]
[root@cenos7x64-redash 桌面]# python Psycopg2Instance.py 
_connect_able  1558702346.2 1558702346.31 0.1146671772
execute  1558702346.31 1558702346.34 0.0275540351868
commit  1558702346.34 1558702346.34 0.00102615356445
result_data  1558702346.34 1558702346.34 0.0001540184021
{'salary': 33000, 'departmentid': 1, 'id': 1, 'name': 'Bertram'}
{'salary': 56000, 'departmentid': 1, 'id': 2, 'name': 'Caesar'}
{'salary': 54000, 'departmentid': 1, 'id': 3, 'name': 'Darnell'}
{'salary': 52000, 'departmentid': 2, 'id': 4, 'name': 'Edward'}
{'salary': 52000, 'departmentid': 2, 'id': 5, 'name': 'Elijah'}
{'salary': 67000, 'departmentid': 2, 'id': 6, 'name': 'Geoffrey'}
{'salary': 60000, 'departmentid': 2, 'id': 7, 'name': 'Hobart'}
{'salary': 120000, 'departmentid': 3, 'id': 8, 'name': 'Keith'}
Get dict format data  1558702346.2 1558702346.34 0.144738912582
_connect_able  1558702346.34 1558702346.46 0.11777806282
execute  1558702346.46 1558702346.46 0.00364899635315
commit  1558702346.46 1558702346.46 0.00100803375244
result_data  1558702346.46 1558702346.46 2.00271606445e-05
(1, 'Bertram', 33000, 1)
(2, 'Caesar', 56000, 1)
(3, 'Darnell', 54000, 1)
(4, 'Edward', 52000, 2)
(5, 'Elijah', 52000, 2)
(6, 'Geoffrey', 67000, 2)
(7, 'Hobart', 60000, 2)
(8, 'Keith', 120000, 3)
Get dict format data  1558702346.34 1558702346.47 0.12343287468

**Comment by ilovesport** [comment]
_connect_able 1558702346.2 1558702346.31 0.1146671772
_connect_able 1558702346.34 1558702346.46 0.11777806282

psycopg2.connect(host=self._host, user=self._user, password=self._password, port=self._port, database=self._database)

create connection cost a lot of time, why?

**Comment by dvarrazzo** [comment]
If it takes more than psql to open the connection then you are using different connection parameters.

nothing we can debug for you.
