### ISSUE TITLE
Unable to connect on Windows using pg_services.conf

### ISSUE THREAD

**Issue by jgrocha** [psycopg/psycopg2#926]
I'm using `pg_services.conf` to provide access to a Postgresql database.

The pg_services.conf file is:
```
[pg_trabalho]
host=192.168.1.24
port=5432
dbname=trabalho
```

The services are working well, either on Ubuntu and on Windows. I'm using QGIS to access the database and it works well. QGIS is using cpp code to access the database.

I can also connect on the command line, using `psql service=pg_trabalho` as in the following example:
```
jgr@zoe:~$ psql service=pg_trabalho
psql (10.8 (Ubuntu 10.8-0ubuntu0.18.10.1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

trabalho=> 
```

So, I think the pg_services are properly configured and working.

### Problem

In Windows, I'm not able to connect using `psycopg2`. The following code does not work on Windows.

```python
import psycopg2

print (psycopg2.__version__)
connection = psycopg2.connect(service='pg_trabalho')
# connection = psycopg2.connect(user = "cmb.user", password = "xxxxxxx", host = "192.168.1.24", port = "5432", database = "trabalho")
cursor = connection.cursor()
print ( connection.get_dsn_parameters(),"\n")
cursor.execute("SELECT version();")
record = cursor.fetchone()
print("Connected to - ", record,"\n")
```

It works well in Ubuntu, but not on Windows. Both works well if pg_services are not used, and the connection is made using `connect(user = "cmb.user", password = "xxxxxxx", host = "192.168.1.24", port = "5432", database = "trabalho")`.

### Error on Windows

This is the error reported in WIndows:

```
2.7.5 (dt dec pq3 ext lo64)
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "192.168.1.24
" to address: Unknown host
```

Can it be a psycopg2 problem? 

I'm using psycopg2 2.7.5, on WIndows 10.

**Comment by dvarrazzo** [comment]
This is not an error in psycopg: we don't parse that file. It is an error in libpq. Please report the problem to the pgsql-bugs mailing list.

**Comment by jgrocha** [comment]
Thank you @dvarrazzo for the feedback. I'll reporting upstream, although I only have this error in Python. In C or CPP the usage of `pg_services.conf` works smoothly.

**Comment by dvarrazzo** [comment]
Above you tried with psql on linux (`jgr@zoe:~$`). Have you tried psql on windows?

psycopg doesn't handle the `pg_services.conf` file: the `service` connection parameter is just passed down to the libpq connection function.

**Comment by dvarrazzo** [comment]
Reopening this issue because, if connecting via psql works and psycopg doesn't it may be that the libpq we build uses the wrong libraries

@jgrocha can you double, triple check that on the same machine `psql "service=pg_trabalho"` connects alright but `psycopg2.connect("service=pg_trabalho")` gives the error?

@jerickso the context is [this conversation](https://www.postgresql.org/message-id/1473.1560866085%40sss.pgh.pa.us): it's not immediately clear for me what libc we are linking. Can we make sure we use one which does the right thing?

**Comment by jerickso** [comment]
We are using the MSVC libc variant, with the version based upon what python version uses to build the their distribution, so:
- MSVC 2017 (14.0) - Python 3.5, 3.6, 3.7
- MSVC 2010  (10.0) - Python 3.3, 3.4
- MSVC 2008 (9.0) - Python 2.6, 2.7, 3.0, 3.1, 3.2

Correct me if I'm wrong, from the email thread, it sounds like on Windows, it doesn't seem to be stripping off the '\r' from the configuration file.  psql does not seem to be affected by this, but psycopg2 is.

Looking at the documentation, the MS `fgets` includes the newline character in the returned string, so I can also see it including the '\r' in the returned string, too.  Tho, the `fopen` when opened in text mode (the default) is suppose to translate CR/LF to LF, but it is not quite clear that `fgets` does the translation.

The interesting thing is why psql isn't affected.  Maybe psql is stripping the CR elsewhere in their code?  Maybe python is setting a global variable to open all files in binary mode?  Maybe our building/linking in AppVeyor inadvertently forces the default to binary mode?

**Comment by jgrocha** [comment]
Thank you @dvarrazzo and @jerickso 

I was able to run psycopg2 in a new Windows virtual machine and it works well, with or without `\r`.

The python process (inspected with Process Explorer) used the library `_psycopg.cp37-win_amd64.pyd`, as we can see in the screenshot.

![python process uses _psycopg cp37-win_amd64 pyd](https://user-images.githubusercontent.com/163681/59724364-6fdf6c00-9221-11e9-871b-4dccfd6f7d6a.PNG)

The library is properly compiled with MSVC, as @jerickso pointed out.

I'll close this issue.

### Problem not solved

I still have the problem in psycopg2, but only if I run t inside QGIS. I'll debug it further, but right now the problem is isolated to QGIS. QGIS uses two libraries: the same `_psycopg.cp37-win_amd64.pyd` and also `C:\Program Files\QGIS 3.6\bin\libpq.dll`. Maybe this last one overrides the psycopg2 one.

### fgets using MVS

I confirm that MVS `fgets` discards `\r` when the file is opened with `"r"`. Opening the file with `"rb"` preserves the `\r`.

I used the following C program and compiled it with the free Microsoft Visual Studio Community 2019 (version 16.1.2). I used a `pg_services.conf` file with `\r\n` line endings.

```c
#pragma warning(disable:4996)

#include <stdio.h>
#include <string.h>

int main(int argc, char* argv[])
{
	FILE* f;
	char buf[200], *line;

	f = fopen(argv[1], "rb");
	if (f != NULL)
	{
		while ((line = fgets(buf, sizeof(buf), f)) != NULL)
		{

			/* ignore EOL at end of line */
			if (strlen(line) && line[strlen(line) - 1] == '\n') {
				line[strlen(line) - 1] = 0;
				printf("\\n ");
			}

			/* ignore CR at end of line */
			if (strlen(line) && line[strlen(line) - 1] == '\r') {
				line[strlen(line) - 1] = 0;
				printf("\\r ");
			}

			printf("%s\n", strrev(line));

		}
		fclose(f);
	}
	return 0;
}
```

#### Test file pg_service.conf

```
jgr@berlin:/mnt/c/Users/Jorge$ od -c pg_service.conf
0000000   [   p   g   _   m   a   d   e   i   r   a   ]  \r  \n   h   o
0000020   s   t   a   d   d   r   =   1   0   .   0   .   3   .   2  \r
0000040  \n   p   o   r   t   =   5   4   3   2  \r  \n   d   b   n   a
0000060   m   e   =   m   a   d   e   i   r   a  \r  \n   u   s   e   r
0000100   =   m   a   d   e   i   r   a  \r  \n   p   a   s   s   w   o
0000120   r   d   =   i   l   o   v   e   p   o   s   t   g   r   e   s
0000140  \r  \n
0000142
```

#### Binary mode "rb"

```
jgr@berlin:/mnt/c/Users/Jorge$ Source/Repos/pg_services/Release/pg_services.exe pg_service.conf
\n \r ]ariedam_gp[
\n \r 2.3.0.01=rddatsoh
\n \r 2345=trop
\n \r ariedam=emanbd
\n \r ariedam=resu
\n \r sergtsopevoli=drowssap
```

#### Text mode "r"

```
jgr@berlin:/mnt/c/Users/Jorge$ Source/Repos/pg_services/Release/pg_services.exe pg_service.conf
\n ]ariedam_gp[
\n 2.3.0.01=rddatsoh
\n 2345=trop
\n ariedam=emanbd
\n ariedam=resu
\n sergtsopevoli=drowssap
```

**Comment by dvarrazzo** [comment]
@jerickso thank you for checking the issue out, and @jgrocha thank you for your analysis.

**Comment by jerickso** [comment]
@jgrocha thanks for the quick code check of `fgets`.  If I had time tomorrow, I was going to try the same type of test as I was curious how `fgets` reacted, but you beat me to it.  Thanks again for the effort.

Note that since psycopg2 is linking against the static libpq library, we do not use the imported dll version.

To me it feels like for some reason it is opening up the file in binary mode and therefor not doing the translation.  Since libpq is calling fopen without any mode type (ie text/binary), my guess is that somewhere (in QGIS?) they are changing the default behavior of fopen to be binary.  [The MS docs ](https://docs.microsoft.com/en-us/cpp/c-runtime-library/fmode?view=vs-2019) describes 3 ways to change the default setting.

Actually, looking at the code for QGIS, I believe that is the case.  I see `_set_fmode( _O_BINARY );` being called for windows in [main.cpp](https://github.com/qgis/QGIS/blob/master/src/app/main.cpp#L489).

I would think ideally libpq calling the fopen function should specify that it is a text file, but I'm not sure the crossplatformness of 't' as a mode option as well as any strange corner cases with doing so.

Can we trick it in QGIS?  Possibly with ctypes in python:

```
from ctypes import cdll, c_int, byref
old_fmode = c_int()
cdll.msvcrt._get_fmode(byref(old_fmode))
# _O_BINARY = 0x8000
# _O_TEXT   = 0X4000
cdll.msvcrt._set_fmode(0x4000)

# Do your code here

# Clean up
# With my tests, this call doesn't work if old_fmode = 0
cdll.msvcrt._set_fmode(old_fmode)
```

Note that this code isn't thread safe and not sure what other side effects it may create, so be forewarned.

**Comment by jgrocha** [comment]
@jerickso Thank you for your very interesting findings! Probably, you found the problem in QGIS.

I've tried the workaround, forcing `cdll.msvcrt._set_fmode(0x4000)` but it didn't work. Setting the `_fmode` global variable is not enough for some reason.

I'll need to setup a compiler environment to compile QGIS using MSC to confirm that forcing binary mode is the culprit. I also need to understand why this setting was introduced.

For a **closed issue**, this one has been so valuable!

**Comment by dvarrazzo** [comment]
@jgrocha would you like to follow up on pgsql-bugs and/or on QGIS bug tracker to tell them about those findings? Probably either the former should force opening the file in text mode (if that's even possible), and/or QGIS should drop changing the global mode (but git blame says that line has been there for 10 years and last change was just a reindent so I guess the whole shack is built on that assumption).

**Comment by jgrocha** [comment]
This issue was solved at libpq level by the following [commit](https://github.com/postgres/postgres/commit/b654714f9bcfb4443bcc531c32f059fd85f798ec). 
Kudos for the Postgresql team (Tom Lane and Michael Paquier).

Thank you @dvarrazzo and @jerickso for helping to identify the problem.
