### ISSUE TITLE
FAQ: How to ask questions?

### ISSUE THREAD

**Issue by guettli** [psycopg/psycopg2#930]
I think the FAQ should tell users where they can ask questions.

I see these ways:

* StackOverflow
* https://github.com/psycopg/psycopg2
* The mailing list: https://www.postgresql.org/list/psycopg/

FAQ I talk about: http://initd.org/psycopg/docs/faq.html

**Comment by dvarrazzo** [comment]
It's the wrong order. github is a bug tracker, not a place to ask for homeworks. You can have conversations about your problem on the mailing list, where more people can read and answer. So, for me.

- read the docs
- read the faqs
- google
- ask the mailing list

http://initd.org/psycopg/docs/install.html#if-you-still-have-problems

However, yes, that can be added on top of FAQ.

**Comment by guettli** [comment]
I have not seen "if you still have problems". For me a link from the FAQ to "if you still have problems" would be enough.

**Comment by guettli** [comment]
thank you.
