### ISSUE TITLE
Up to a 30+ sec delay when getting psycopg2.OperationalError with "no route to host"

### ISSUE THREAD

**Issue by gil0109** [psycopg/psycopg2#933]
I am testing when dropping a HA Postgres implementation with flask=sqlalchemy.  It seems there is a delay prior to receive the no route to host error.  I have tried to drop connect_timeout to 1 but it has no impact.  Other OperationErrors do not take this long.  It seems just the no route to host.

The route only takes 300ms at most to switch over.  Tested with psql connection tests.

==> api_call_with_retry: Try #: 4; time: 2019-06-15 05:28:43.558005
--
  | --> delay:   300.0; total delay: 600.0
  | --> elapsed: 0:00:00.300477; total elapsed: 0:00:00.643459
  | --> SQLAlchemyError: 2019-06-15 05:29:49.689271
  | --> Message:         (psycopg2.OperationalError) could not connect to server: No route to host
  | Is the server running on host "patroni-mastertheq" (172.50.68.141) and accepting
  | TCP/IP connections on port 5432?

This error is never delayed:

==> api_call_with_retry: Try #: 2; time: 2019-06-15 05:28:43.026012
--
  | --> delay:   100; total delay: 100
  | --> elapsed: 0:00:00.111466; total elapsed: 0:00:00.111466
  | --> SQLAlchemyError: 2019-06-15 05:28:43.037212
  | --> Message:         (psycopg2.OperationalError) could not connect to server: Connection refused
  | Is the server running on host "patroni-mastertheq" (172.50.68.141) and accepting
  | TCP/IP connections on port 5432?

Any suggestions would be appreciated...

**Comment by dvarrazzo** [comment]
It's a name resolution or networking problem, not psycopg.
