### ISSUE TITLE
Error "failed to map segment from shared object" when importing psycopg2

### ISSUE THREAD

**Issue by KShutter** [psycopg/psycopg2#937]
I installed `psycopg2` successfully for both my Python 2.7 and my Python 3.6. However, whenever I try importing psycopg2, I get an error.

In Python 2.7:
```
    import psycopg2

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/kshutter/.local/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
>     from psycopg2._psycopg import (                     # noqa
> ImportError: /home/kshutter/.local/lib/python2.7/site-packages/psycopg2/_psycopg.so: failed to map segment from shared object
> 
```

In Python 3.6:
```
    import psycopg2

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/kshutter/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
>     from psycopg2._psycopg import (                     # noqa
> ImportError: /home/kshutter/.local/lib/python3.6/site-packages/psycopg2/_psycopg.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object
> 
```
I have been trying to solve it in multiple ways, including following the answers and comments in this somewhat related SO question: https://stackoverflow.com/questions/20919771/centos-6-4-failed-to-map-segment-from-shared-object-permission-denied

Any help would be very much appreciated.

**Comment by dvarrazzo** [comment]
Nothing I've ever seen. Because I doubt anyone else will see this issue I suggest you to ask the ML or some other forum.

**Comment by celiberate** [comment]
Any solution for this? I am also facing similar issue
