### ISSUE TITLE
Issues building on Centos

### ISSUE THREAD

**Issue by fields** [psycopg/psycopg2#938]
I have tried to install psycopg2 from source on Centos 7, and got the following error:

`Error: pg_config executable not found.`

Even though postgresql-devel is installed and pg_config is in /usr/bin in the $PATH.

I tried adding the pg_config path to the requirements file:

`psycopg2==2.8.3 --install-option="--pg-config /usr/bin/pg_config"`

But then I got:

`option --pg-config /usr/bin/pg_config not recognized`

Installing psycopg2-binary works, but that's not recommended for production systems. How can I troubleshoot this?

**Comment by dvarrazzo** [comment]
I don't know about the requirement files syntax. Try to debug the setup.py and check why pg_config is said not found.

**Comment by dvarrazzo** [comment]
Any further news? I guess we can close this?
