### ISSUE TITLE
Supporting multistatement and UNION fetching

### ISSUE THREAD

**Issue by huitredelombre** [psycopg/psycopg2#942]
Hi,

right now if I do a multi statement such as:

`curs2.execute("SELECT * FROM masa WHERE masa='71555' ; SELECT * FROM masa WHERE masa='09219'" )`

The fetch only access the last query result.

If I do:
`curs2.execute("SELECT * FROM masa WHERE masa='71555' UNION ALL SELECT * FROM masa WHERE masa='09219'" )`

The fetch access the whole result, but loose the information about which was the result was about.

I expected both cases to work the same: fetch return a table storing the result of each separated query.

This look doable looking wire-shark captures: the server concatenate a "command completion" to the packet to separate each statement result.

Also you can delete the issue if you want. I will repost it. I accidentally posted in the first seconds while it was empty.

**Comment by huitredelombre** [comment]
Hi, 

right now if I do a multi statement such as:

`curs2.execute("SELECT * FROM masa WHERE masa='71555' ; SELECT * FROM masa WHERE masa='09219'" )`

The fetch only access the last query result.

If I do: 
`curs2.execute("SELECT * FROM masa WHERE masa='71555' UNION ALL SELECT * FROM masa WHERE masa='09219'" )
`

The fetch access the whole result, but loose the information about which was the result was about. 

I expected both cases to work the same: fetch return a table storing the result of each separated query.

This look doable looking wire-shark captures: the server concatenate a "command completion" to the packet to separate each statement result.

**Comment by fogzot** [comment]
While the wire protocol allows for it, `libpq`, used by psycopg to communicate with PostgreSQL, does not. If you want the results of two queries as two separated data sets, you should issue two separate `.execute()` calls.

Reference: https://www.postgresql.org/docs/9.5/libpq-exec.html#LIBPQ-EXEC-MAIN

> [...] Note however that the returned PGresult structure describes only the result of the last command executed from the string. Should one of the commands fail, processing of the string stops with it and the returned PGresult describes the error condition.
