### ISSUE TITLE
psycopg2.ProgrammingError: must be owner of relation runs

### ISSUE THREAD

**Issue by Zlopez** [psycopg/psycopg2#945]
I recently updated to version `2.7.7` and I'm now hitting this issue when running `alembic-3 -c /etc/anitya/alembic.ini upgrade head`.

Do I need to run this as specific user? I'm now running this as root in container.

Here is the whole stacktrace: [release-monitoring-web-216.log](https://github.com/psycopg/psycopg2/files/3372104/release-monitoring-web-216.log)

**Comment by dvarrazzo** [comment]
This is an error message from the database, psycopg is only relying it back and I don't know of the software you mention.

**Comment by Zlopez** [comment]
@dvarazzo: Thanks, I didn't know this comes back from database
