### ISSUE TITLE
External use of array deserialization?

### ISSUE THREAD

**Issue by jbergknoff-rival** [psycopg/psycopg2#946]
We're using logical replication, with wal2json, to consume Postgres changes. When a change is made to a column with an array type, the value returned by wal2json is simply the Postgres-serialized version, e.g. `'{abc,def}'`. A full payload looks like this:

```
{
  "nextlsn": "0/1705CF0",
  "timestamp": "2019-07-11 18:50:47.984744+00",
  "change": [
    {
      "kind": "insert",
      "schema": "stuff",
      "table": "array_thing",
      "columnnames": [
        "id",
        "a"
      ],
      "columntypes": [
        "integer",
        "text[]"
      ],
      "columnvalues": [
        3,
        "{abc,def,\"string,with,comma\",\"string\\\"with'quotation\\\"marks\"}"
      ]
    }
  ]
}
```

My understanding is that psycopg2 will deserialize such array strings into Python types when we query the database. Is it currently possible to invoke those deserialization methods from Python code? If not, could they be exposed so that it's possible to call them from Python code?

Since logical replication need not be done with wal2json (it's just one decoding plugin), I don't think it's psycopg2's responsibility to do the conversion. However, it would be nice if we could reuse the existing, robust code, instead of implementing it again.

**Comment by dvarrazzo** [comment]
Yes I see. Yes, there's something you can use in psycopg:

```python
>>> o = json.loads(s) # your example
>>> psycopg2.extensions.STRINGARRAY(o['change'][0]['columnvalues'][1], None)
['abc', 'def', 'string,with,comma', 'string"with\'quotation"marks']
```

**Comment by jbergknoff-rival** [comment]
Excellent, thank you!

**Comment by jbergknoff-rival** [comment]
Circling back: this works great, though it seems that the second argument (cursor) must be supplied, or else we get a segfault.

**Comment by dvarrazzo** [comment]
Why did my example work? (it was Python 2: maybe it blows on Python 3?)

You may understand that your use case is outside our scope and I don't have personally spare capacity to work on the case too much. However if you provide a patch to guard for null cursor and do something sensible in that case I'll be happy to merge.

**Comment by jbergknoff-rival** [comment]
I looked into making this gracefully handle a cursor of `None`, but it looks like a pretty significant change. The cursor is passed down through a few functions, and fields are dereferenced off of it all the way down. I'm not familiar enough with the internals of psycopg2 or Postgres to do this work quickly. It's not a blocking issue, either, so I'll leave it as is.

Interesting that it does work in Python 2. (And I just have to ask... why are you using Python 2!? :smile: ) I wrote a test case which segfaults in Python 3 and passes in Python 2.

Aside: I didn't find any details in the documentation about setting up a development environment, so I'll just leave this for anybody who lands here in the future:

```
(host system) $ docker run -it --rm -v $(pwd):$(pwd) -w $(pwd) python:3.7.4-slim-buster bash
root# apt-get update
root# apt-get install build-essential postgresql postgresql-server-dev-11
root# /etc/init.d/postgresql start
root# ln -s $(which python) /bin/python3.7.4
root# make
root# su postgres
postgres$ make testdb TESTDB=psycopg2_test
postgres$ make check
```

Similar steps set up the Python 2.7.16 environment that I used to verify that the test passed.

Here's the test case (tests/test_types_basic.py)

```
def testArrayParseWithNoCursor(self):
    self.assertEqual(['abc', 'def'], psycopg2.extensions.STRINGARRAY('{abc,def}', None))
```

Thanks again for your guidance.

**Comment by fogzot** [comment]
@jbergknoff-rival please, try this branch and let me know if it works:

https://github.com/fogzot/psycopg2/tree/feature-typecasts-no-cursor

It is not OK for a pull into mainline, because I need to review it for usage of the cursor in all typecasters (not just array) but it pretty much works.

**Comment by dvarrazzo** [comment]
The reason why it works for Py2 and not Py3 is that by default Py2 deals with bytes, Py3 with unicode. So there must be somewhere an operation to dereference the cursor in order to find the encoding, and that one segfaults.

Thinking about Py3, the typecaster is actually designed to work on bytes (because that's what comes out of the network), but you are passing it an unicode string: that too is probably not designed to work that way.

What I think is that someone calling the typecaster manually as you do should first encode the string into bytes, let's say in utf8, and psycopg should assume utf8 to decode, if it doesn't have a cursor to read the encoding from.

**Comment by cidiomar-jr** [comment]
I've come across the same issue and passing the cursor class to STRINGARRAY was enough.

**Comment by pulserdd** [comment]
> Yes I see. Yes, there's something you can use in psycopg:
> 
> ```python
> >>> o = json.loads(s) # your example
> >>> psycopg2.extensions.STRINGARRAY(o['change'][0]['columnvalues'][1], None)
> ['abc', 'def', 'string,with,comma', 'string"with\'quotation"marks']
> ```

thanks this works for deserialization. What about serialization? Below doesn't work when doing UPDATE to the table with integer array column :( any pointers? Thanks
```
v = psycopg2.extensions.INTEGERARRAY(v, None)
```
