### ISSUE TITLE
potentially incorrect instruction for some users

### ISSUE THREAD

**Issue by jkjc** [psycopg/psycopg2#949]
http://initd.org/psycopg/download/
suggests:
pip install -U pip # make sure to have an up-to-date pip

which provides:
ImportError: cannot import name 'main'

resolved by:
https://github.com/pypa/pip/issues/5599

**Comment by dvarrazzo** [comment]
Not our issue

**Comment by jkjc** [comment]
It seems to me that your psycopg2 install instruction via pip contradicts pip instructions. Let people find out the hard way. Not your issue.

**Comment by dvarrazzo** [comment]
Issue defaced by the OP. The original was:

> http://initd.org/psycopg/download/
> suggests:
> pip install -U pip # make sure to have an up-to-date pip
> 
> which provides:
> ImportError: cannot import name 'main'
> 
> resolved by:
> pypa/pip#5599

The OP wasn't happy of my response, so he answered:

> It seems to me that your psycopg2 install instruction via pip contradicts pip instructions. Let people find out the hard way. Not your issue.

I stand to what I say, and as of pretty much now the pip suggestion is of the tone of:

```
WARNING: You are using pip version 19.2, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

There's nothing else to add I believe.
