### ISSUE TITLE
set_client_encoding() quietly aborts the current transaction

### ISSUE THREAD

**Issue by asqui** [psycopg/psycopg2#950]
If a transaction is in progress, calling `connection.set_client_encoding()` implicitly aborts the current transaction.

Two questions:
1. Why is this necessary? I tried changing encoding mid-transaction in psql and had no problems.
2. Assuming there is a reason, then should this side-effect be mentioned in the [docs for `set_client_encoding()`](http://initd.org/psycopg/docs/connection.html#connection.set_client_encoding)

Happy to submit a PR for the documentation update, if that's what's deemed necessary.

**Comment by dvarrazzo** [comment]
Hi,

changing encoding halfway is not a good idea because data might have been transferred after an `execute()` but only converted in python in a `fetch*()`, so the codec used at transfer time would be inconsistent with what used to create the objects.

If you would like to propose a docs improvements be my guest.

**Comment by asqui** [comment]
> data might have been transferred after an `execute()` but only converted in python in a `fetch*()`, so the codec used at transfer time would be inconsistent with what used to create the objects.

That sounds like a more general hazard of changing encoding in between `execute()` and `fetch*()`, which I agree is not a good idea, and could be detected and prevented by psycopg2, if desired.

But I don't see how silently aborting the current transaction helps...

To give you a concrete example of how this manifests for us: we are using the [psycopg-nestedtransactions](https://github.com/asqui/psycopg-nestedtransactions) `Transaction()` context manager, and an internal `changeConnectionEncoding()` context manager to write code like this:

```
with getConnection(...) as cxn:
    with changeConnectionEncoding(cxn, ...):
        with Transaction(cxn):
            ...
```

The fact that `set_client_encoding()` rolls back any transaction places an unnecessary constraint of having `changeConnectionEncoding()` outside the `Transaction()` context, which seems unnecessary.

If you get the ordering wrong, and put `Transaction()` outside and `changeConnectionEncoding()`, this will cause a counterintuitive error exemplified in [this test](https://github.com/asqui/psycopg-nestedtransactions/blob/5424dd7bdad59bc20de38006f1d86c75ef5a67c7/tests/test_transaction.py#L374), and I don't think that there is anything that the `Transaction` context manager can reasonably do to detect that the user has called `set_client_encoding()` within the transaction, thereby hosing the carefully constructed arrangement of transaction and savepoints that the context manager is maintaining...

**Comment by dvarrazzo** [comment]
It is inconsistent with what a more recently developed method does:

```
In [9]: cur.execute("select 1")

In [11]: cnn.set_session(readonly=True)
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-11-b75cad4cc15f> in <module>()
----> 1 cnn.set_session(readonly=True)

ProgrammingError: set_session cannot be used inside a transaction
```

throwing an exception would be a better behaviour.

Having a writable attribute would be less Python 2.2 too.

**Comment by asqui** [comment]
> It is inconsistent with what a more recently developed method does

I'm sorry, I don't understand. 

Are you saying that `set_client_encoding()` should raise an exception rather than quietly rolling-back when a transaciton is in progress? If so, that is an improvement that we could discuss separatly (perhaps under a different issue).

For the purposes of this issue, I'm reasoning that the implicit rollback in `set_client_encoding()` creates problems (as described above), but solves none (specifically, it does _not_ prevent you from changing the encoding between an `execute()` and `fetch*()` operation), and should therefore be removed.

Thoughts?

**Comment by dvarrazzo** [comment]
Yes, I say that, provided that the client encoding cannot be changed in the middle of a transaction, one reason being the execute/fetch mismatch explained but there could be others reading back the code, between the choice of issuing a quiet rollback and throwing an exception, the exception would have been a way better choice and if I had to change how psycopg works that's what I'd do. I don't see a use case to allow changing encoding halfway a transaction - for me it would be set from the beginning and not changing for the lifetime of the connection.

**Comment by asqui** [comment]
Sorry, I don't understand what you mean by _"but there could be others reading back the code"_.

There's a difference between:
1. Changing client encoding in the middle of a cursor operation (the example you have given); and
2. Changing client encoding during a transaction, in between independent cursor operations.

e.g. Is there any reason why this shouldn't work?
```
cxn = getConnection(...)
with Transaction(cxn):
    loadSomeData(cxn)
    makeSomeChanges(cxn)
    makeSomeChangesThatRequreDifferentClientEncoding(cxn)
    makeMoreChanges(cxn)
```

When executed, the effects of `makeSomeChanges(cxn)` will be quietly discarded.

If I remove the `with Transaction()` then everything works as intended.

I don't see anything that links transactions and client encoding; it seems like the link is between cursor operations and client encoding, but maybe that's because I haven't understood what you meant by _"but there could be others reading back the code"_.

**Comment by dvarrazzo** [comment]
I mean, I can't remember by heart if there is any other reason for which changing encoding during a transaction is a bad idea.

In case of doubt I prefer to err on the safe side. So it's rather "why do you _need_ to change encoding during a transaction"? If there is a genuine use case we can look into it.

Speaking about how to avoid encoding to be changed: rolling back the transaction quietly seems a silly way of doing it. I would rather throw an exception.

**Comment by asqui** [comment]
> why do you _need_ to change encoding during a transaction

Because I'd like code like this to work correctly:

```
cxn = getConnection(...)
with Transaction(cxn):
    loadSomeData(cxn)  # Load data from table A
    makeSomeChanges(cxn)  # Update table A
    makeSomeChangesThatRequreDifferentClientEncoding(cxn)  # Insert an audit record into table B
    makeMoreChanges(cxn)  # More updates to table A

def makeSomeChangesThatRequreDifferentClientEncoding(cxn):
    with changeConnectionEncoding(cxn, ...):  # Calls set_client_encoding()
        ...
```

**Comment by dvarrazzo** [comment]
The encoding is a property of the connection between the server and the client. It's not data representation, a property of the data on the python side or on the postgres side. Why does the change require a different encoding? Can you make a _real_ example?

**Comment by asqui** [comment]
In our specific case, this need arises from the fact that we have a database configured with a server encoding of SQL_ASCII (for historic reasons, and difficult to change) and different tables have had data stored with different encodings.

This isn't an ideal design, but this is where we find ourselves and unfortunately it has been deemed infeasible to resolve these design issues properly, so we need to continue to deal with them going forward.

**Comment by dvarrazzo** [comment]
In this case you can write binary data instead of python strings for these tables.

Psycopg doesn't understand SQL_ASCII and mistakes it for ascii encoding: that's a long standing inconvenience (#519).
