### ISSUE TITLE
Depending on either psycopg2 or psycopg2-binary

### ISSUE THREAD

**Issue by holtgrewe** [psycopg/psycopg2#952]
Hi, is it possible to specify a dependency on either `psycopg2` or `psycopg2-binary`? I have a package that I'd like to install with `psycopg2-binary` but it has a transient dependency on `psycopg2` via another one... Is it possible to specify this `or` condition in the intermediate package?

**Comment by dvarrazzo** [comment]
No, it's not possible, and don't use `psycopg2-binary` as a dependency: you will give endless headache to your users. Trawl previous issues for all the horror stories you need.

**Comment by holtgrewe** [comment]
Fair enough, thanks.
