### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by hamashoool** [psycopg/psycopg2#954]
```
(venv) zola@kali:~/PycharmProjects/simpleposts/someposts$ sudo pip install psycopg2Collecting psycopg2
  Using cached https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2_hrhqeh/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2_hrhqeh/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-2_hrhqeh/psycopg2/
    Complete output (7 lines):
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'

```

**Comment by dvarrazzo** [comment]
Well, do what the message says, no?

**Comment by Drisyaparol** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\parol suresh\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PAROLS~1\\AppData\\Local\\Temp\\pip-install-0maqkbp_\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\PAROLS~1\\AppData\\Local\\Temp\\pip-install-0maqkbp_\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\PAROLS~1\AppData\Local\Temp\pip-install-0maqkbp_\pycocotools\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PAROLS~1\AppData\Local\Temp\pip-install-0maqkbp_\pycocotools\setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

What does it means?

**Comment by HaiyunC** [comment]
I also have the same issue!

I tried 'pip install rpy2' but got an error 
 
'Complete output (17 lines):
    'sh' is not recognized as an internal or external command,
    operable program or batch file.
     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      ..........
     ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.'

Is this related to running .sh file in windows?

**Comment by dvarrazzo** [comment]
Blocking because this is psycopg bug tracker and people ask here how to fix R or Cython.

I am losing faith in the human race.
