### ISSUE TITLE
Needed a way to specify Postgres types in ARRAY expressions

### ISSUE THREAD

**Issue by greatvovan** [psycopg/psycopg2#959]
**Example 1:**
```
import psycopg2
db = psycopg2.connect('postgresql://postgres@host:5432/postgres')
cur = db.cursor()
cur.execute('select * from unnest(%s) as t(a int, b text)', ([(1, 'x'), (2, 'y')],))
```
> psycopg2.errors.DatatypeMismatch: function return row and query-specified return row do not match
> DETAIL:  Returned type unknown at ordinal position 2, but query expects text.

Postgres log:

`STATEMENT:  select * from unnest(ARRAY[(1, 'x'),(2, 'y')]) as t(a int, b text)`

Expected: `select * from unnest(ARRAY[(1, 'x'::text),(2, 'y'::text)]) as t(a int, b text);`

**Example 2:**
```
import psycopg2
db = psycopg2.connect('postgresql://postgres@host:5432/postgres')
cur = db.cursor()
cur.execute('select * from unnest(%s) as t(a int, b bigint)', ([(1, 10), (2, 20)],))
```
> psycopg2.errors.DatatypeMismatch: function return row and query-specified return row do not match
> DETAIL:  Returned type integer at ordinal position 2, but query expects bigint.

Postgres log:

`STATEMENT:  select * from unnest(ARRAY[(1, 10),(2, 20)]) as t(a int, b bigint)`

Expected:

`select * from unnest(ARRAY[(1, 10::bigint),(2, 20::bigint)]) as t(a int, b bigint)`

I am sorry if I am missing some useful functionality of the library, but I cannot find a way to solve it. I was looking for type wrappers to force the lib to use cast, but failed to find.

**Comment by dvarrazzo** [comment]
This is a bug tracker: it is for bugs, not for personal support.

Please send your question to the mailing list.
