### ISSUE TITLE
Importing table in postgresql table Schema return empty datatable

### ISSUE THREAD

**Issue by renauld94** [psycopg/psycopg2#960]
It seems that from Pandas 0.15 version, it can be imported in a selected Postgresql **Schema**. 
It is creating a "universe" table in my schema "calls" but without any data in my table. If I do not specify the schema, it will export properly the data in my default public schema. How I can fix that issue? The code is the following :

```
universe.head(0).to_sql('universe', engine, schema='calls', if_exists='replace',index=False) #truncates the table
conn = engine.raw_connection()
cur = conn.cursor()
output = io.StringIO()
universe.to_csv(output, sep='\t', header=False, index=False)
output.seek(0)
contents = output.getvalue()
cur.copy_from(output,'universe', null="") # null values become ''
conn.commit()
```

**Comment by dvarrazzo** [comment]
This is a bug tracker, not an help desk.
