### ISSUE TITLE
table_oid should be unsigned

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#961]
Hey @dvarrazzo,

Few of our users get the table_oid as negative value. It mostly happens with large DB's with lot many tables and columns. 
Doing a SELECT (-123434)::oid returns correct result, where -123434 is the table_oid returned.
I'm sorry I am not able to share the simulation data, but could you please have go through on the changes again and see if we are using signed int for OIDs may be ?

Thanks for the great work :)

_Originally posted by @adityatoshniwal in https://github.com/psycopg/psycopg2/issues/661#issuecomment-527739621_

**Comment by dvarrazzo** [comment]
@adityatoshniwal Is the system you are testing on a 32 bit, is it Windows or Linux? what is `sys.maxint`?

`Oid` is defined as an unsigned 32 bits. On 64 bits systems, even if we were handling Oid types in a sloppy way, the result seems correct. I'm making handling more robust anyway.

**Comment by adityatoshniwal** [comment]
The user is facing issue on on Windows 10 Enterprise x64 1809 (pgAdmin application)

Thanks a lot !!

**Comment by dvarrazzo** [comment]
Figured out so: [Window 64 bits defines long as 32 bits unlike Linux](https://stackoverflow.com/questions/384502/what-is-the-bit-size-of-long-on-64-bit-windows).

Anyway, the patch landed in master and wiil be released in 2.8.4. Could you be able to test it?

**Comment by adityatoshniwal** [comment]
Unfortunately I am not able to reproduce at my end. I can only ask the users facing issue to upgrade pyscopg2  once released. :(
