### ISSUE TITLE
PostgreSQL 11 has been released in the meantime

### ISSUE THREAD

**Issue by df7cb** [psycopg/psycopg2#962]
I guess that deserves an update:
https://github.com/psycopg/psycopg2/blob/33d3c074fa2a7591ab539c625bad1c934e21fc37/scripts/travis_test.sh#L70-L73

**Comment by dvarrazzo** [comment]
If it is supported on travis, it's the present. Otherwise it's the future :)

It was still future a few months PG 11 was already my present...

Would you like to provide a patch to move 11 to the present and 9.4 to the past?

**Comment by df7cb** [comment]
It was just something I noticed. I don't intend to fix that myself, sorry.

**Comment by dvarrazzo** [comment]
NP I'll act on it when I get about working on this area, thank you for the report :)

**Comment by dvarrazzo** [comment]
PG 11 and 12 included in test grid.
