### ISSUE TITLE
Build fails on os x 10.14.6 with some gcc complaints.

### ISSUE THREAD

**Issue by mtobis** [psycopg/psycopg2#964]
Forgive me I am an absolute psycopg* newbie, but the obvious route to Django through pip3 in a virtualenv seems insurmountable or at least very confusing. I think something is broken? 

psycopg-binary worked though.

**Comment by dvarrazzo** [comment]
Stuff is documented. If you read the error messages and google for them you will look for solution. I don't have anything else to add, if not that this is a bug tracker and not a helpdesk.

**Comment by mtobis** [comment]
Yeah I bashed (pun intended) at this for hours trying this and that, eventually got as far as https://stackoverflow.com/questions/26288042/error-installing-psycopg2-library-not-found-for-lssl and then decided you guys need to come up with a fix. Trying to be helpful.
