### ISSUE TITLE
Issue with typecast_BOOLEAN_cast

### ISSUE THREAD

**Issue by lbuttay** [psycopg/psycopg2#965]
When using psycopg2 with an H2 DB, boolean are always return as "False" even if the vlaue is "TRUE" in the database.

Replacing : "if (s[0] == 't')"
by : "if (s[0] == 't' || s[0] == 'T')"
In typecast_basic.c line 121 resolves this issue.

**Comment by dvarrazzo** [comment]
H2 is not really a supported database, but this seems useful to have. Thank you for the report.

**Comment by dvarrazzo** [comment]
Added to psycopg 2.8.4.
