### ISSUE TITLE
Logging connection does not support LoggerAdapter

### ISSUE THREAD

**Issue by stevenmwade** [psycopg/psycopg2#966]
Initializing a connection with a logger only seems to support a logger that is an instance of `logging.Logger` and defaults to a file logger otherwise. This means you can't use a logger of type `logging.LoggerAdapter` to give context to the logger and causes an error that it does not have an attribute of 'write' which a LoggerAdapter does not have.

https://github.com/psycopg/psycopg2/blob/master/lib/extras.py#L412-L415

https://docs.python.org/3/library/logging.html#logging.LoggerAdapter

**Comment by dvarrazzo** [comment]
Probably it wasn't designed for a different object than `Logger`.

The logging connection is not an object I especially love and I don't desire adding it new features. If you would like your issue fixed please provide a patch.
