### ISSUE TITLE
Passing a table of values for bulk update

### ISSUE THREAD

**Issue by bfelbo** [psycopg/psycopg2#968]
We need to do bulk updates of many rows, and want to use the SQL syntax below. How do we do that using psycopg2?

```
UPDATE table_to_be_updated
SET msg = update_payload.msg
FROM (VALUES %(update_payload)s) AS update_payload(id, msg)
WHERE table_to_be_updated.id = update_payload.id
RETURNING *
```

**Attempt 1 - Passing values**
To do that, we need to pass a nested iterable format. For the `update_payload`, I've tried passing a list of lists, list of tuples, and tuples of tuples. It all fails with various errors.

**Attempt 2 - Writing custom class with __conform__**
Tried to write a custom class that we can use for these operations, which would return 
```
(VALUES (row1_col1, row1_col2), (row2_col1, row2_col2), (...))
```
I've coded up like this following instructions [here](http://initd.org/psycopg/docs/advanced.html#adapting-new-types), but it's clear that I'm doing something wrong. For instance, in this approach I'll have to handle quoting of all values inside the table, which would be cumbersome and prone to errors.

```
class ValuesTable(list):
    def __init__(self, *args, **kwargs):
        super(ValuesTable, self).__init__(*args, **kwargs)

    def __repr__(self):
        data_in_sql = ""
        for row in self:
            str_values = ", ".join([str(value) for value in row])
            data_in_sql += "({})".format(str_values)
        return "(VALUES {})".format(data_in_sql)

    def __conform__(self, proto):
        return self.__repr__()

    def getquoted(self):
        return self.__repr__()

    def __str__(self):
        return self.__repr__()
```

**Comment by dvarrazzo** [comment]
This is a bug tracker, not a support forum. Please write to the mailing list.

**Comment by bfelbo** [comment]
This is a common use case. Perhaps you'd want to add an example to the documentation?
