### ISSUE TITLE
PQconninfo not available in libpq < 9.3

### ISSUE THREAD

**Issue by haneyf** [psycopg/psycopg2#976]
Hi!
I am trying to use https://github.com/dbcli/pgcli, and whenever I try to connect onto the database, I get an error:

```
$ pgcli -h localhost -U abc
Password for abc:
PQconninfo not available in libpq < 9.3
```

I noticed in the source code, you call this out, but there are no workarounds I could find or solutions to this problem, can you please help?

```
$ pip list | grep psy
psycopg2                 2.8.3
psycopg2-binary          2.8.3
```

  Operating System: CentOS Linux 7 (Core)

**Comment by dvarrazzo** [comment]
What you are seeing _is_ the workaround: without it you would have failed compiling.

The workaround should be in pgcli maybe, which should handle the case of PQconninfo not available in a better way (which can be checked using `psycopg2.__libpq_version__`).

Alternatively, install a supported libpq version: 9.3 and the previous versions are unsupported.

Alternatively, install a previous version of psycopg. 2.6.x maybe, not sure.
