### ISSUE TITLE
Unable to install chatterbot

### ISSUE THREAD

**Issue by AkshaySinha22** [psycopg/psycopg2#978]
ERROR: Command errored out with exit status 1:
   command: 'c:\users\abc\appdata\local\programs\python\python37-32\python.exe' 'c:\users\abc\appdata\local\programs\python\python37-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\akshaysi\AppData\Local\Temp\pip-build-env-bdqcecss\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (8 lines):
  Collecting setuptools
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x066FE0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x066FE710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x066FE310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x066FE030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x066FE930>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/setuptools/
    ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\\appdata\local\programs\python\python37-32\python.exe' 'c:\users\\appdata\local\programs\python\python37-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\akshaysi\AppData\Local\Temp\pip-build-env-bdqcecss\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

**Comment by dvarrazzo** [comment]
Man, what project is this?
