### ISSUE TITLE
NUL byte exception

### ISSUE THREAD

**Issue by alexcmcdaniel** [psycopg/psycopg2#979]
Referencing: [https://github.com/psycopg/psycopg2/pull/459].

We are in the process of upgrading from 2.6.2 to 2.8.3. We are currently using psycopg2 cursors in many places within our codebase, which makes it a bit troublesome to purge each execute in each of the cursors to ensure there aren't any null bytes. Is there a way to use the functionality of 2.6.2 (in terms of the handling of null bytes) when the connection is initialized versus at the cursor level?

Thanks!!

**Comment by dvarrazzo** [comment]
You can write your own string adapter which, in case the string contains a `'\0'`, would truncate it. Instructions about writing a customized adapter are in the documentation.
