### ISSUE TITLE
PY3.7 Binary.getquoted() fails due to `TypeError: can't escape str to binary`

### ISSUE THREAD

**Issue by kevin1chun** [psycopg/psycopg2#980]
From the example in http://initd.org/psycopg/docs/extensions.html?highlight=binary#psycopg2.extensions.Binary.getquoted and use-cases in my own usages via SQLAlchemy, 
the Binary type cannot serialize when given a string input.

``` 
 File "/Users/*/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/*/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
TypeError: can't escape str to binary
```

I can however get by this by pre-processing the input as follows:
`Binary(bytes(value, "utf-8")).getquoted()`

Note: I am not experiencing this on python 2.7 though, only py3.7

**Comment by dvarrazzo** [comment]
You can experience the same in Python 2 if you pass an unicode object to `Binary`.

I will fix the documentation specifying that it only applies to bytes strings. Furthermore in Python 3 you don't need `Binary` at all: just passing bytes works as expected, so `Binary` is actually only useful on Python 2.

    >>> psycopg2.extensions.Binary(b'hel\0lo').getquoted() == adapt(b'hel\0lo').getquoted()
    True

**Comment by kevin1chun** [comment]
ok that makes sense, thanks for the info.
We had been using a plain `str` in py2 without issues for `Binary` (indirectly through sqlalchemy-utils' `EncryptedType` https://github.com/kvesteri/sqlalchemy-utils/blob/989d12a3a39a78d09ce31cde85251eb990bc1442/sqlalchemy_utils/types/encrypted/encrypted_type.py#L222)

I'll trying serializing to bytes first. thanks for the info!
