### ISSUE TITLE
ImportError: /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PQsslAttribute

### ISSUE THREAD

**Issue by billerby** [psycopg/psycopg2#983]
Provisioning a new centos box (CentOS Linux release 7.7.1908 (Core))

Ansible installs postgres9.4 and psycopg2:
- name: add postgres yum repo
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm"
    conf_file: '/etc/yum.conf'
  become: yes

- name: install postgres
  yum: 
    name:
       - postgresql94-server
       - python-psycopg2
    conf_file: '/etc/yum.conf'
  become: yes

After that db, schema and user creation fails due to psycopg2 error.

Doing an import in python cmd reveals:
`>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PQsslAttribute
>>> `

On centos 7.6 this problem did not exist...

Any idea

**Comment by kadnan** [comment]
@billerby Did you sort it out?

**Comment by billerby** [comment]
@kadnan no, I did not. I know PQsslAttribute should reside in the package "libpq" which for some reason must be of the wrong version. 

When googling I stumbled upon this blogpost, that however is not helping me since I do not have muliptle libpq-packages installed on the system.

**Comment by epu** [comment]
I am hitting something similar.

If I follow the binaries using ldd, and grep the binaries for symbols, it's for sure not in there.
My version resolved to libpq.so.5.7.

[user@hostname ~]$ readelf -Ws /usr/pgsql-9.4/lib/libpq.so.5.7 | grep -i PQ  |grep -i ssl
   193: 000000000001d4b0    19 FUNC    GLOBAL DEFAULT   12 PQgetssl
   259: 000000000001d2f0     7 FUNC    GLOBAL DEFAULT   12 PQinitSSL
   300: 000000000001d2d0    26 FUNC    GLOBAL DEFAULT   12 PQinitOpenSSL

The documentation for PQsslAttribute says that 'Only available if psycopg was built with libpq >= 9.5; raise NotSupportedError otherwise.'

I also rely on older 9.4 binaries; could support for 9.4 have been not compiled in? Maybe there's a new minimum version supported?

**Comment by VilleS1** [comment]
In this repo https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7.7-x86_64/
python2-psycopg2-2.8.3-1.rhel7.x86_64.rpm works
python2-psycopg2-2.8.3-2.rhel7.x86_64.rpm is broken

**Comment by dvarrazzo** [comment]
We don't maintain those packages. Please ask for support to Red Hat.

**Comment by sebasmannem** [comment]
@dvarrazzo This repo is not maintained by RedHat either. This is Postgres Community repo.
@VilleS1 , @billerby , @kadnan , @epu , in my case, I noticed psycopg2 was coming from pgdg10 repo.
I fixed this by installing postgresql11-server.x86_64.
What I think is going on, is that:

- All of these psycopg2 rpms are built against latest postgres libraries
- They contain PQencryptPasswordConn (probably a feature that came together with SCRAM)
- Installing Postgres 10 or 11 adds the required libraries that support this.

You might:

- Install Postgresql10-server or 11-server
- Test with postgresql10 or postgresql11 (will probably also work)
- install psycopg2 using pip (and virtalenv if you like)
- install the earlier psycog2 binary as opted by @VilleS1

**Comment by sebasmannem** [comment]
Just tested and verified. It does work if you also install postgresql10-libs...

**Comment by dvarrazzo** [comment]
@sebasmannem This is not the community repo bug tracker either. That's pgsql-bugs@postgresql.org. This project is only responsible for what you find on PyPI.

**Comment by justinsousa** [comment]
had a similar problem. somehow the pgdg10 repo was added in addition to the pgdg94 repo and the version of psycopg2 that was installed via yum was from the pgdg10 repo. I fixed by removing the package installed from the pgdg10 repo and reinstalling from pgdg94 (I also use Postgres 9.4).

**Comment by VilleS1** [comment]
I switched the client libs from postgresql95-libs to postgresql10-libs and now the package python2-psycopg2-2.8.3-3.rhel7.x86_64.rpm works.

**Comment by NickVolynkin** [comment]
I installed `psycopg2-binary` instead of `psycopg2` and it fixed this problem for me.
My setup is Ansible 2.9.4 on my machine and CentOS 7, Python 2.7.5  on target host.

**Comment by stevecj** [comment]
psycopg2-binary is not recommended for production use though.
