### ISSUE TITLE
Can not use with macOS 10.15 

### ISSUE THREAD

**Issue by GitHubZHH** [psycopg/psycopg2#986]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/9910841/66990430-c0e06d80-f0f8-11e9-83db-b5972052aaf5.png">

Collecting psycopg2
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info
         cwd: /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/dc/d3d4kyhn65j__hxm3zpwt3kc0000gn/T/pip-install-8rko2udq/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by tdakkota** [comment]
did you try use psycopg2-binary?

**Comment by samosudov** [comment]
psycopg2-binary works fine (macOS 10.14.3)

**Comment by tdakkota** [comment]
@GitHubZHH Did you install Postgresql?

**Comment by dvarrazzo** [comment]
Missing dependencies
