### ISSUE TITLE
ProgrammingError: no results to fetch

### ISSUE THREAD

**Issue by haripriyanharry** [psycopg/psycopg2#988]
I have created a database as sparkifydb and there are few tables as below
![image](https://user-images.githubusercontent.com/56644128/67038243-a9c36f00-f13c-11e9-9f14-53921fc72063.png)

When I type \dt in psql prompt I am able to list all these tables. However when I run \dt or select * from tables in pandas using psycopg2 I am getting the below error,

**ProgrammingError: no results to fetch**

The entire code is
try:
    #list down tables created
    cur.execute("""select * from tables;""")
except psycopg2.Error as e:
    print("Error: select *")
    print (e)

    
row = cur.fetchall()
while row:
    print(row)
    row = cur.fetchall()
I have even used cur.fetchone still no luck

**Comment by dvarrazzo** [comment]
If you have an error you have no result to fetch

**Comment by haripriyanharry** [comment]
I have 6 tables in the database as per the snap, then how can I list down the tables inside pandas?

**Comment by dvarrazzo** [comment]
This is a bug tracker, not a support forum. Please ask some mailing list.
