### ISSUE TITLE
Error PGRES_TUPLES_OK when multiprocessing

### ISSUE THREAD

**Issue by diegocorradini** [psycopg/psycopg2#994]
Hi,

I am stuck with the following database concurrency problem.

I am building a django webapp using psycopg2 to comunicate with a PostgreSQL database. The queries are run from different processes.

In order to lock rows, all the queries are inside a transaction atomic block.

```
   with transaction.atomic():
       self.analysis_obj = Analysis.objects.select_for_update().get(pk=self.analysis_id)
```
However sometimes I get random error like:
- 'no results to fetch',
- 'pop from empty list',
- 'error with status PGRES_TUPLES_OK and no message from the libpq'.

Any idea to deal with this problem?
Many thanks.

**Comment by dvarrazzo** [comment]
You cannot run queries from another process.

**Comment by Jwan622** [comment]
waht do you mean? 2 processes can't talk to postgres?
