### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by thedrow** [psycopg/psycopg2#998]
Python 3.4 has reached EOL in March, 2019.
Psycopg2 should drop support for it as well.

**Comment by dvarrazzo** [comment]
It will in next major release (2.9)

**Comment by jerickso** [comment]
Hmm, Last week I added the following as a comment for PR #1000 when I think it should be documented in this issue:

Removing Python 2.7 and 3.4 support will also help with moving the Windows builds to use the latest versions of Postgres libpq.

Basically, the Postgres 12 and 13 build scripts included in their distribution does not support Visual Studio versions before 2013 (Python 2.7 uses 2008 and Python 3.4 uses 2010).

I'll work on a pull request against master that will drop support for Python 2.7 and 3.4 for the Windows builds and use Postgres 13.

**Comment by jerickso** [comment]
Created a Windows pull request #1192 against the master branch that removes Python 2.7 and Python 3.4 from the AppVeyor builds.
